//! Prose composition for `narrative=true`.
//!
//! When a local qwen3 backend is configured (`[worklog] narrative_backend`,
//! default `qwen3-4b`) and available, each project's bullets are generated by the
//! model from the collected facts. The model load + greedy decode are blocking
//! (a multi-GB GGUF load from the HuggingFace cache + token loop), so generation
//! runs in `spawn_blocking` and never stalls the async daemon. If the model or GPU
//! is unavailable — or the backend isn't a local qwen3 variant — every project
//! falls back to [`compose`], the deterministic, fully-reproducible prose path.
//! The engine actually used is surfaced in the report's `normalized.narrative_engine`.

use super::ProjectSummary;
use crate::llm::qwen3::{Qwen3LocalExtractor, Qwen3Variant};

/// `generate_all` result: per-project bullets keyed by project index (present
/// when the model ran), plus the engine label that was used.
type NarrativeOutput = (Option<Vec<(usize, Vec<String>)>>, String);

/// Annotate each project's `narrative` field, returning the engine label that
/// actually ran (e.g. `"qwen3-4b"` or a `"deterministic…"` fallback reason).
pub async fn annotate(
    projects: &mut [ProjectSummary],
    backend: String,
    max_tokens: usize,
) -> String {
    if projects.is_empty() {
        return "n/a".to_string();
    }
    let prompts: Vec<(usize, String)> = projects
        .iter()
        .enumerate()
        .map(|(i, p)| (i, prompt_for(p)))
        .collect();

    // Model load + decode are blocking — keep them off the async runtime.
    let (results, engine) =
        tokio::task::spawn_blocking(move || generate_all(&backend, max_tokens, prompts))
            .await
            .unwrap_or((None, "deterministic-fallback (task join error)".to_string()));

    match results {
        // Model unavailable → deterministic prose for every project.
        None => {
            for p in projects.iter_mut() {
                p.narrative = Some(compose(p));
            }
        }
        // Model ran → use its bullets; empty output for a project falls back.
        Some(per_project) => {
            for (i, bullets) in per_project {
                if bullets.is_empty() {
                    let fallback = compose(&projects[i]);
                    projects[i].narrative = Some(fallback);
                } else {
                    projects[i].narrative = Some(bullets);
                }
            }
        }
    }
    engine
}

/// Map a `narrative_backend` string to a local qwen3 variant, if any.
fn variant_of(backend: &str) -> Option<Qwen3Variant> {
    match backend.trim().to_ascii_lowercase().as_str() {
        "qwen3-8b" => Some(Qwen3Variant::Eight),
        "qwen3-4b" => Some(Qwen3Variant::Four),
        _ => None,
    }
}

/// Blocking: load the model once and generate bullets for every prompt. Returns
/// `(None, reason)` when the model can't be used (caller does the deterministic
/// fallback), or `(Some(per_project_bullets), engine_label)` on success. An empty
/// bullet list for a project signals "generation failed — fall back for this one".
fn generate_all(
    backend: &str,
    max_tokens: usize,
    prompts: Vec<(usize, String)>,
) -> NarrativeOutput {
    let Some(variant) = variant_of(backend) else {
        return (
            None,
            format!("deterministic (narrative_backend='{backend}' is not a local qwen3 variant)"),
        );
    };
    let model = match Qwen3LocalExtractor::new(variant) {
        Ok(m) => m,
        Err(e) => {
            tracing::warn!(error = %e, backend, "work_summary narrative: qwen3 load failed; deterministic fallback");
            return (
                None,
                format!("deterministic-fallback (qwen3 unavailable: {e})"),
            );
        }
    };
    let mut out = Vec::with_capacity(prompts.len());
    for (i, prompt) in prompts {
        match model.complete(&prompt, max_tokens) {
            Ok(raw) => out.push((i, parse_bullets(&raw))),
            Err(e) => {
                tracing::warn!(error = %e, "work_summary narrative: generation failed for one project; deterministic fallback");
                out.push((i, Vec::new()));
            }
        }
    }
    (Some(out), backend.to_string())
}

/// Build the generation prompt for one project from its collected facts.
fn prompt_for(p: &ProjectSummary) -> String {
    let span = match (&p.first, &p.last) {
        (Some(f), Some(l)) => format!("{f}..{l}"),
        _ => "n/a".to_string(),
    };
    let scopes = p
        .top_scopes
        .iter()
        .take(5)
        .map(|(s, _)| s.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let kws = p
        .top_keywords
        .iter()
        .take(6)
        .map(|(k, _)| k.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let samples = p
        .samples
        .iter()
        .map(|s| format!("- {s}\n"))
        .collect::<String>();
    let dirty = match &p.uncommitted {
        Some(u) if u.dirty => format!(
            "Uncommitted: {} modified, {} staged, {} untracked on {}.\n",
            u.modified,
            u.staged,
            u.untracked,
            u.branch.as_deref().unwrap_or("?")
        ),
        _ => String::new(),
    };
    format!(
        "Summarize one software project's work for a monthly status report. Write 1-2 short, \
         factual bullet points (one sentence each, no preamble, no markdown) using ONLY the facts \
         below. Do not invent anything.\n\n\
         Project: {name}\n\
         Commits: {commits} (+{added}/-{deleted} lines), {span}\n\
         Areas (commit scopes): {scopes}\n\
         Keywords: {kws}\n\
         Sample commit subjects:\n{samples}{dirty}\n\
         Bullets:\n",
        name = p.name,
        commits = p.commits,
        added = p.added,
        deleted = p.deleted,
    )
}

/// Clean a model completion into at most 3 bullet strings (strip bullet/number
/// markers and obvious prompt-echo lines).
fn parse_bullets(raw: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in raw.lines() {
        let mut s = line.trim().trim_start_matches(['-', '*', '•', '·']).trim();
        // Strip a leading "N." / "N)" enumeration.
        if let Some((head, rest)) = s.split_once(['.', ')'])
            && !head.is_empty()
            && head.len() <= 2
            && head.chars().all(|c| c.is_ascii_digit())
        {
            s = rest.trim();
        }
        if s.is_empty() {
            continue;
        }
        let low = s.to_ascii_lowercase();
        if low == "bullets:"
            || low.starts_with("project:")
            || low.starts_with("commits:")
            || low.starts_with("here are")
            || low.starts_with("sample commit")
        {
            continue;
        }
        out.push(s.to_string());
        if out.len() >= 3 {
            break;
        }
    }
    out
}

/// Deterministic prose fallback — composes 1–2 sentences from the collected
/// facts. Fully reproducible; used whenever the model is unavailable.
pub fn compose(p: &ProjectSummary) -> Vec<String> {
    let mut out = Vec::with_capacity(2);

    if p.commits > 0 {
        let span = match (&p.first, &p.last) {
            (Some(f), Some(l)) if f != l => format!(" between {f} and {l}"),
            (Some(f), _) => format!(" on {f}"),
            _ => String::new(),
        };
        let focus = if !p.top_scopes.is_empty() {
            let s: Vec<&str> = p
                .top_scopes
                .iter()
                .take(3)
                .map(|(s, _)| s.as_str())
                .collect();
            format!(", focused on {}", s.join(", "))
        } else if !p.top_keywords.is_empty() {
            let s: Vec<&str> = p
                .top_keywords
                .iter()
                .take(3)
                .map(|(k, _)| k.as_str())
                .collect();
            format!(", touching {}", s.join(", "))
        } else {
            String::new()
        };
        out.push(format!(
            "Landed {} commit{} (+{}/−{} lines){}{}.",
            p.commits,
            if p.commits == 1 { "" } else { "s" },
            p.added,
            p.deleted,
            span,
            focus
        ));
    }

    if let Some(u) = &p.uncommitted
        && u.dirty
    {
        let branch = u.branch.as_deref().unwrap_or("a feature branch");
        out.push(format!(
            "Work is still in flight on `{}` ({} modified, {} staged, {} untracked).",
            branch, u.modified, u.staged, u.untracked
        ));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn variant_of_maps_known_backends() {
        assert_eq!(variant_of("qwen3-4b"), Some(Qwen3Variant::Four));
        assert_eq!(variant_of("QWEN3-8B"), Some(Qwen3Variant::Eight));
        assert_eq!(variant_of("cloud"), None);
        assert_eq!(variant_of("disabled"), None);
    }

    #[test]
    fn parse_bullets_strips_markers_and_echo() {
        let raw =
            "Bullets:\n- Did the thing.\n2. Did another thing.\n\n* Final item.\n- four\n- five";
        let b = parse_bullets(raw);
        assert_eq!(
            b,
            vec![
                "Did the thing.".to_string(),
                "Did another thing.".to_string(),
                "Final item.".to_string(),
            ]
        );
    }

    #[test]
    fn parse_bullets_keeps_sentence_periods() {
        // A real sentence with a mid-line period must not be truncated.
        let b = parse_bullets("Refactored e.g. the parser into modules.");
        assert_eq!(
            b,
            vec!["Refactored e.g. the parser into modules.".to_string()]
        );
    }
}
