use axum::extract::Path;
use axum::http::header::{CACHE_CONTROL, CONTENT_SECURITY_POLICY, CONTENT_TYPE};
use axum::http::{HeaderMap, HeaderValue, StatusCode};
use axum::response::{IntoResponse, Response};

const INDEX_HTML: &str = include_str!("../resources/index.html");
const APP_CSS: &str = include_str!("../resources/app.css");
const APP_JS: &str = include_str!("../resources/app.js");

// Generated by build.rs: `GRAMMAR_ASSETS: &[(&str, &[u8])]` — the tree-sitter
// grammar `.wasm`/`.scm` files under resources/grammars/, served (embedded) at
// `/webui/grammars/...` for web-tree-sitter read-only highlighting.
include!(concat!(env!("OUT_DIR"), "/grammar_assets.rs"));

// `'wasm-unsafe-eval'` is required for web-tree-sitter / the tree-sitter runtime
// to instantiate its WebAssembly; it does NOT permit `eval`/`unsafe-eval` of
// JS. Everything else stays as tight as before (self-hosted single app.js).
const CSP: &str = "default-src 'self'; connect-src 'self' ws: wss:; img-src 'self' data:; \
                   style-src 'self' 'unsafe-inline'; style-src-elem 'self'; \
                   style-src-attr 'unsafe-inline'; script-src 'self' 'wasm-unsafe-eval'; \
                   object-src 'none'; base-uri 'none'; frame-ancestors 'none'";

pub async fn index() -> Response {
    asset_response(INDEX_HTML, "text/html; charset=utf-8", false)
}

pub async fn asset(Path(path): Path<String>) -> Response {
    match path.as_str() {
        "app.css" => asset_response(APP_CSS, "text/css; charset=utf-8", true),
        "app.js" => asset_response(APP_JS, "text/javascript; charset=utf-8", true),
        "" => asset_response(INDEX_HTML, "text/html; charset=utf-8", false),
        p if p.starts_with("grammars/") => grammar_asset(&p["grammars/".len()..]),
        _ => not_found_response(),
    }
}

fn grammar_asset(rel: &str) -> Response {
    let Some(entry) = GRAMMAR_ASSETS.iter().find(|e| e.0 == rel) else {
        return not_found_response();
    };
    let content_type = if rel.ends_with(".wasm") {
        "application/wasm"
    } else if rel.ends_with(".scm") {
        "text/plain; charset=utf-8"
    } else {
        "application/octet-stream"
    };
    let mut headers = HeaderMap::new();
    headers.insert(CONTENT_TYPE, HeaderValue::from_static(content_type));
    headers.insert(CONTENT_SECURITY_POLICY, HeaderValue::from_static(CSP));
    headers.insert(
        CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=86400, immutable"),
    );
    let bytes: &'static [u8] = entry.1;
    (StatusCode::OK, headers, bytes).into_response()
}

fn asset_response(body: &'static str, content_type: &'static str, cache: bool) -> Response {
    let mut headers = HeaderMap::new();
    headers.insert(CONTENT_TYPE, HeaderValue::from_static(content_type));
    headers.insert(CONTENT_SECURITY_POLICY, HeaderValue::from_static(CSP));
    headers.insert(
        CACHE_CONTROL,
        HeaderValue::from_static(if cache {
            "public, max-age=60"
        } else {
            "no-store"
        }),
    );
    (StatusCode::OK, headers, body).into_response()
}

fn not_found_response() -> Response {
    let mut headers = HeaderMap::new();
    headers.insert(
        CONTENT_TYPE,
        HeaderValue::from_static("text/plain; charset=utf-8"),
    );
    headers.insert(CONTENT_SECURITY_POLICY, HeaderValue::from_static(CSP));
    headers.insert(CACHE_CONTROL, HeaderValue::from_static("no-store"));
    (StatusCode::NOT_FOUND, headers, "webui asset not found").into_response()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn known_assets_are_served_with_specific_content_types() {
        let css = asset(Path("app.css".to_string())).await;
        assert_eq!(css.status(), StatusCode::OK);
        assert_eq!(
            css.headers()
                .get(CONTENT_TYPE)
                .and_then(|v| v.to_str().ok()),
            Some("text/css; charset=utf-8")
        );

        let js = asset(Path("app.js".to_string())).await;
        assert_eq!(js.status(), StatusCode::OK);
        assert_eq!(
            js.headers().get(CONTENT_TYPE).and_then(|v| v.to_str().ok()),
            Some("text/javascript; charset=utf-8")
        );
    }

    #[tokio::test]
    async fn unknown_assets_do_not_fall_back_to_the_app_shell() {
        let response = asset(Path("missing.js".to_string())).await;
        assert_eq!(response.status(), StatusCode::NOT_FOUND);
        assert_eq!(
            response
                .headers()
                .get(CONTENT_TYPE)
                .and_then(|v| v.to_str().ok()),
            Some("text/plain; charset=utf-8")
        );
        assert_eq!(
            response
                .headers()
                .get(CACHE_CONTROL)
                .and_then(|v| v.to_str().ok()),
            Some("no-store")
        );
    }

    #[test]
    fn csp_allows_react_style_attributes_without_relaxing_scripts() {
        assert!(CSP.contains("style-src-attr 'unsafe-inline'"));
        assert!(CSP.contains("style-src-elem 'self'"));
        assert!(CSP.contains("script-src 'self'"));
        assert!(!CSP.contains("script-src 'self' 'unsafe-inline'"));
        // WASM instantiation for tree-sitter is allowed; JS eval is not.
        assert!(CSP.contains("script-src 'self' 'wasm-unsafe-eval'"));
    }

    #[tokio::test]
    async fn grammar_wasm_is_served_with_wasm_content_type() {
        let response = asset(Path("grammars/markdown/grammar.wasm".to_string())).await;
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response
                .headers()
                .get(CONTENT_TYPE)
                .and_then(|v| v.to_str().ok()),
            Some("application/wasm")
        );
    }
}
