//! Unicode lookup tables for the LaTeX → plain-text renderer.
//!
//! These map LaTeX control words (as they appear in `latex_parser`'s `MathExpr`
//! and `Node` trees) to readable Unicode. They are pure data + lookups, no
//! dependencies. Math symbol/operator coverage is a superset of what
//! `latex_parser::math_sem` can classify, so the renderer can always produce
//! something better than the raw TeX that `pandoc --to plain` dumps.

/// Greek letters and standalone math symbols (`\alpha` → `α`, `\infty` → `∞`).
pub fn math_symbol(name: &str) -> Option<&'static str> {
    Some(match name {
        // lowercase Greek
        "alpha" => "α",
        "beta" => "β",
        "gamma" => "γ",
        "delta" => "δ",
        "epsilon" | "varepsilon" => "ε",
        "zeta" => "ζ",
        "eta" => "η",
        "theta" | "vartheta" => "θ",
        "iota" => "ι",
        "kappa" => "κ",
        "lambda" => "λ",
        "mu" => "μ",
        "nu" => "ν",
        "xi" => "ξ",
        "pi" | "varpi" => "π",
        "rho" | "varrho" => "ρ",
        "sigma" | "varsigma" => "σ",
        "tau" => "τ",
        "upsilon" => "υ",
        "phi" | "varphi" => "φ",
        "chi" => "χ",
        "psi" => "ψ",
        "omega" => "ω",
        // uppercase Greek
        "Gamma" => "Γ",
        "Delta" => "Δ",
        "Theta" => "Θ",
        "Lambda" => "Λ",
        "Xi" => "Ξ",
        "Pi" => "Π",
        "Sigma" => "Σ",
        "Upsilon" => "Υ",
        "Phi" => "Φ",
        "Psi" => "Ψ",
        "Omega" => "Ω",
        // common symbols
        "infty" => "∞",
        "partial" => "∂",
        "nabla" => "∇",
        "emptyset" | "varnothing" => "∅",
        "aleph" => "ℵ",
        "hbar" => "ℏ",
        "ell" => "ℓ",
        "wp" => "℘",
        "Re" => "ℜ",
        "Im" => "ℑ",
        "angle" => "∠",
        "top" => "⊤",
        "bot" => "⊥",
        "vdash" => "⊢",
        "models" => "⊨",
        "Box" => "□",
        "Diamond" => "◇",
        "checkmark" => "✓",
        "dagger" => "†",
        "ddagger" => "‡",
        "prime" => "′",
        _ => return None,
    })
}

/// Math operators, relations, arrows, big operators, and integrals
/// (`\le` → `≤`, `\sum` → `∑`, `\int` → `∫`).
pub fn math_operator(name: &str) -> Option<&'static str> {
    Some(match name {
        // binary operators
        "times" => "×",
        "cdot" => "⋅",
        "div" => "÷",
        "pm" => "±",
        "mp" => "∓",
        "ast" => "∗",
        "star" => "⋆",
        "circ" => "∘",
        "bullet" => "•",
        "oplus" => "⊕",
        "ominus" => "⊖",
        "otimes" => "⊗",
        "odot" => "⊙",
        "cup" => "∪",
        "cap" => "∩",
        "uplus" => "⊎",
        "sqcup" => "⊔",
        "sqcap" => "⊓",
        "setminus" => "∖",
        "wedge" | "land" => "∧",
        "vee" | "lor" => "∨",
        "lnot" | "neg" => "¬",
        // relations
        "leq" | "le" => "≤",
        "geq" | "ge" => "≥",
        "neq" | "ne" => "≠",
        "equiv" => "≡",
        "approx" => "≈",
        "cong" => "≅",
        "sim" => "∼",
        "simeq" => "≃",
        "propto" => "∝",
        "asymp" => "≍",
        "doteq" => "≐",
        "ll" => "≪",
        "gg" => "≫",
        "prec" => "≺",
        "succ" => "≻",
        "preceq" => "⪯",
        "succeq" => "⪰",
        "in" => "∈",
        "notin" => "∉",
        "ni" => "∋",
        "subset" => "⊂",
        "subseteq" => "⊆",
        "supset" => "⊃",
        "supseteq" => "⊇",
        "sqsubseteq" => "⊑",
        "sqsupseteq" => "⊒",
        "perp" => "⊥",
        "parallel" => "∥",
        "mid" => "∣",
        // quantifiers / logic
        "forall" => "∀",
        "exists" => "∃",
        "nexists" => "∄",
        "implies" => "⟹",
        "iff" => "⟺",
        // arrows
        "rightarrow" | "to" => "→",
        "leftarrow" | "gets" => "←",
        "leftrightarrow" => "↔",
        "Rightarrow" => "⇒",
        "Leftarrow" => "⇐",
        "Leftrightarrow" => "⇔",
        "mapsto" => "↦",
        "longrightarrow" => "⟶",
        "longleftarrow" => "⟵",
        "uparrow" => "↑",
        "downarrow" => "↓",
        "hookrightarrow" => "↪",
        "rightharpoonup" => "⇀",
        // dots
        "cdots" => "⋯",
        "ldots" | "dots" => "…",
        "vdots" => "⋮",
        "ddots" => "⋱",
        // big operators
        "sum" => "∑",
        "prod" => "∏",
        "coprod" => "∐",
        "bigcup" => "⋃",
        "bigcap" => "⋂",
        "bigvee" => "⋁",
        "bigwedge" => "⋀",
        "bigoplus" => "⨁",
        "bigotimes" => "⨂",
        "bigodot" => "⨀",
        "biguplus" => "⨄",
        "bigsqcup" => "⨆",
        // integrals
        "int" => "∫",
        "iint" => "∬",
        "iiint" => "∭",
        "iiiint" => "⨌",
        "oint" => "∮",
        "oiint" => "∯",
        "oiiint" => "∰",
        // roots / misc
        "surd" => "√",
        "sqrt" => "√",
        _ => return None,
    })
}

/// The combining diacritic for an accent command name (`'` → U+0301 acute,
/// `hat` → U+0302 circumflex). Applied after a base character; the downstream
/// `normalize_extracted_text` NFKC pass composes it to a precomposed glyph
/// (e.g. `e` + U+0301 → `é`) where one exists.
pub fn accent_combining(name: &str) -> Option<char> {
    Some(match name {
        // text-mode single-char accents
        "'" | "acute" => '\u{0301}',
        "`" | "grave" => '\u{0300}',
        "\"" | "ddot" => '\u{0308}',
        "^" | "hat" | "widehat" => '\u{0302}',
        "~" | "tilde" | "widetilde" => '\u{0303}',
        "=" | "bar" => '\u{0304}',
        "." | "dot" => '\u{0307}',
        "u" | "breve" => '\u{0306}',
        "v" | "check" => '\u{030C}',
        "H" => '\u{030B}',
        "c" => '\u{0327}',
        "k" => '\u{0328}',
        "r" | "mathring" => '\u{030A}',
        "b" => '\u{0331}',
        "d" => '\u{0323}',
        "vec" => '\u{20D7}',
        "overline" => '\u{0305}',
        "underline" => '\u{0332}',
        "dddot" => '\u{20DB}',
        _ => return None,
    })
}

/// A literal Unicode character produced by a text-mode symbol command
/// (`\&` → `&`, `\ss` → `ß`, `\oe` → `œ`).
pub fn text_symbol(name: &str) -> Option<&'static str> {
    Some(match name {
        "&" => "&",
        "%" => "%",
        "_" => "_",
        "#" => "#",
        "$" => "$",
        "{" => "{",
        "}" => "}",
        " " => " ",
        "textbackslash" => "\\",
        "textasciitilde" => "~",
        "textasciicircum" => "^",
        "ss" => "ß",
        "ae" => "æ",
        "AE" => "Æ",
        "oe" => "œ",
        "OE" => "Œ",
        "o" => "ø",
        "O" => "Ø",
        "aa" => "å",
        "AA" => "Å",
        "l" => "ł",
        "L" => "Ł",
        "i" => "ı",
        "j" => "ȷ",
        "dag" => "†",
        "ddag" => "‡",
        "copyright" => "©",
        "textregistered" => "®",
        "texttrademark" => "™",
        "pounds" => "£",
        "texteuro" => "€",
        "S" => "§",
        "P" => "¶",
        "dots" | "ldots" | "textellipsis" => "…",
        "LaTeX" => "LaTeX",
        "LaTeXe" => "LaTeX2ε",
        "TeX" => "TeX",
        "BibTeX" => "BibTeX",
        "today" => "today",
        _ => return None,
    })
}
