(*
 * ADR-009 (Phase 5) — Rocq metatheory for the CSM / Multiparty-Session-Type
 * coordination model (src/csm/). Single self-contained file: `scripts/verify.sh`
 * runs `coqc` per .v standalone (sorted), so inter-file `Require` is avoided and
 * everything Requires only the Rocq 9.x Stdlib.
 *
 * No `Axiom` / `Hypothesis` / `Admitted` (CLAUDE.md). Section `Variable`s are
 * universally-quantified parameters (role/label with decidable equality), not
 * axiomatic assumptions — same posture as TransducerMandateDedup.v.
 *
 * Faithful fragment: pgmcp validates *bounded* runs (sequential rounds,
 * recursive depth, deliberation max_rounds) against *unrolled, finite* global
 * types — so the global type is modeled here as a finite tree (no μ/coinduction),
 * over which the metatheorems hold by structural induction.
 *
 * Theorems:
 *   T1  rlm_terminates           — RLM self-recursion halts (well-founded on the
 *                                  strictly-decreasing depth_remaining).
 *   T2  deliberation_terminates  — the bounded reflect/act loop halts
 *                                  (well-founded on max_rounds − round).
 *   T3  global_progress          — a non-End well-formed global type can step.
 *   T4  wf_preserved             — well-formedness is preserved by a global step
 *                                  (subject reduction).
 *   T5  projection soundness      — GENERAL (incl. GChoice): each global head
 *       (project_send/recv_sound,    construct's step is matched by the sender's
 *        project_choice_sender/...)  LSend/LSelect, the receiver's LRecv/LBranch,
 *                                  and leaves bystanders unchanged (the plain
 *                                  external-choice merge, via bystanders_agree).
 *   T6  operational                — GENERAL bidirectional correspondence: every
 *       correspondence               global step is generated by a sender-side
 *       (projection_sound,           local step and conversely, per head
 *        gstep_iff_sender_lstep)     construct (GMsg/GChoice are the only
 *                                  steppable constructors), with no behaviour
 *                                  invented; protocol_fidelity is the
 *                                  choice-free corollary.
 *
 * T5/T6 are now general over ALL well-formed global types including GChoice
 * (the Deliberation pattern), so projection-with-choice is mechanically proved
 * here — no longer only cross-checked by TLC (docs/formal/tla/CfsmNetwork.tla)
 * and the Rust conformance tests (src/csm/conformance.rs). The plain-merge
 * discipline follows Honda, Yoshida & Carbone (POPL 2008) and Scalas & Yoshida
 * (POPL 2019).
 *)

From Stdlib Require Import List.
From Stdlib Require Import Bool.
From Stdlib Require Import Arith.
From Stdlib Require Import PeanoNat.
From Stdlib Require Import Lia.
From Stdlib Require Import Wf_nat.

Import ListNotations.

Section Csm.

  Variable role : Type.
  Variable label : Type.
  Variable eq_role_dec : forall x y : role, {x = y} + {x <> y}.
  Variable eq_label_dec : forall x y : label, {x = y} + {x <> y}.

  (* ===================================================================== *)
  (* T1 — RLM self-recursion terminates.                                   *)
  (*                                                                       *)
  (* RlmFrame::entered clamps depth_remaining to a strictly smaller value  *)
  (* on each self-call; the recursion relation `rlm_child c p` therefore   *)
  (* strictly decreases `fdepth`, and < on a nat measure is well-founded.  *)
  (* ===================================================================== *)

  Record frame := { fdepth : nat; fbudget : nat }.

  Definition rlm_child (c p : frame) : Prop := fdepth c < fdepth p.

  Theorem rlm_terminates : well_founded rlm_child.
  Proof.
    apply (well_founded_lt_compat frame fdepth rlm_child).
    intros x y H. unfold rlm_child in H. exact H.
  Qed.

  (* ===================================================================== *)
  (* T2 — the bounded deliberation loop terminates.                        *)
  (*                                                                       *)
  (* Each `continue` advances round → round+1 while round < max; the       *)
  (* measure (max − round) strictly decreases, so the step relation is     *)
  (* well-founded (no infinite continue-chain).                            *)
  (* ===================================================================== *)

  Definition delib_step (max c p : nat) : Prop := c = S p /\ c <= max.

  Theorem deliberation_terminates : forall max, well_founded (delib_step max).
  Proof.
    intro max.
    apply (well_founded_lt_compat nat (fun r => max - r) (delib_step max)).
    intros x y [Heq Hle]. lia.
  Qed.

  (* ===================================================================== *)
  (* Global types (finite, unrolled) and their reduction.                  *)
  (* ===================================================================== *)

  Inductive gtype : Type :=
  | GEnd : gtype
  | GMsg : role -> role -> label -> gtype -> gtype
  | GChoice : role -> role -> list (label * gtype) -> gtype.

  (* not-equal-role test as a bool. *)
  Definition rne (p q : role) : bool :=
    if eq_role_dec p q then false else true.

  Fixpoint wf (g : gtype) : bool :=
    match g with
    | GEnd => true
    | GMsg p q _ k => rne p q && wf k
    | GChoice p q brs =>
        rne p q
        && negb (Nat.eqb (length brs) 0)
        && forallb (fun pr => wf (snd pr)) brs
    end.

  (* One global reduction step: a message exposes its continuation; a choice
     selects one of its branches. *)
  Inductive gstep : gtype -> gtype -> Prop :=
  | GS_Msg : forall p q l k, gstep (GMsg p q l k) k
  | GS_Choice : forall p q brs l k, In (l, k) brs -> gstep (GChoice p q brs) k.

  (* ===================================================================== *)
  (* T3 — progress: a non-End well-formed global type can take a step.     *)
  (* ===================================================================== *)

  Theorem global_progress :
    forall g, wf g = true -> g <> GEnd -> exists g', gstep g g'.
  Proof.
    intros g Hwf Hne.
    destruct g as [| p q l k | p q brs].
    - exfalso. apply Hne. reflexivity.
    - exists k. apply GS_Msg.
    - (* GChoice: wf forces a non-empty branch list, so a branch exists. *)
      destruct brs as [| [lab k] rest].
      + simpl in Hwf.
        (* length [] = 0 ⇒ negb (0 =? 0) = false ⇒ wf = false. *)
        rewrite Bool.andb_false_r in Hwf. discriminate.
      + exists k. apply GS_Choice with (l := lab). simpl. left. reflexivity.
  Qed.

  (* ===================================================================== *)
  (* T4 — subject reduction: a global step preserves well-formedness.      *)
  (* ===================================================================== *)

  Theorem wf_preserved :
    forall g g', wf g = true -> gstep g g' -> wf g' = true.
  Proof.
    intros g g' Hwf Hstep.
    destruct Hstep as [p q l k | p q brs l k Hin].
    - (* GMsg p q l k → k *)
      simpl in Hwf. apply andb_true_iff in Hwf. destruct Hwf as [_ Hk]. exact Hk.
    - (* GChoice p q brs → k, with (l,k) ∈ brs *)
      simpl in Hwf.
      apply andb_true_iff in Hwf. destruct Hwf as [_ Hall].
      (* Hall : forallb (fun pr => wf (snd pr)) brs = true *)
      rewrite forallb_forall in Hall.
      specialize (Hall (l, k) Hin). simpl in Hall. exact Hall.
  Qed.

  (* ===================================================================== *)
  (* Local types and projection (G ↾ r) — GENERAL fragment.                *)
  (*                                                                       *)
  (* T5/T6 below are now general over ALL well-formed global types,        *)
  (* including GChoice (sender-driven internal/external choice with the    *)
  (* standard "plain merge"). The four linear patterns (Sequential /       *)
  (* Mixture / Distillation / Recursive) are the choice-free special case; *)
  (* the Deliberation pattern is the GChoice case, now covered here in     *)
  (* addition to TLC (docs/formal/tla/CfsmNetwork.tla) and the Rust        *)
  (* conformance tests. The merge metatheory follows Honda-Yoshida-Carbone *)
  (* (POPL'08) and Scalas-Yoshida (POPL'19).                               *)
  (* ===================================================================== *)

  (* Local (endpoint) types. LSelect is a sender's internal choice (it    *)
  (* picks a branch); LBranch is a receiver's external choice (it offers   *)
  (* branches). Bystanders observe neither and so keep a single residual.  *)
  Inductive ltype : Type :=
  | LEnd : ltype
  | LSend : role -> label -> ltype -> ltype
  | LRecv : role -> label -> ltype -> ltype
  | LSelect : role -> list (label * ltype) -> ltype   (* sender's internal choice *)
  | LBranch : role -> list (label * ltype) -> ltype.  (* receiver's external choice *)

  (* Projection G ↾ r as a TOTAL structural Fixpoint (no option/fuel/      *)
  (* coinduction): it reduces under cbn/simpl. For GChoice the branch list *)
  (* is projected by an INNER fix; Coq's guard checker accepts it because  *)
  (* the inner fix only calls the outer `project` on `gk`, a structural    *)
  (* subterm of `brs` (hence of the GChoice argument).                     *)
  (*                                                                       *)
  (* The bystander case takes the HEAD branch's projection. This is the    *)
  (* standard "plain merge" surfaced as a typed side-condition rather than *)
  (* a partial merge function: `bystanders_agree` (below) asserts that for *)
  (* any bystander every branch projects identically, so the head is the   *)
  (* canonical representative and no information is lost. This deliberately *)
  (* avoids needing decidable equality / a Boolean merge on ltype.         *)
  Fixpoint project (g : gtype) (r : role) : ltype :=
    match g with
    | GEnd => LEnd
    | GMsg p q l k =>
        if eq_role_dec r p then LSend q l (project k r)
        else if eq_role_dec r q then LRecv p l (project k r)
        else project k r
    | GChoice p q brs =>
        if eq_role_dec r p
        then LSelect q ((fix pbrs (bs : list (label * gtype)) : list (label * ltype) :=
                           match bs with
                           | [] => []
                           | (l, gk) :: rest => (l, project gk r) :: pbrs rest
                           end) brs)
        else if eq_role_dec r q
        then LBranch p ((fix pbrs (bs : list (label * gtype)) : list (label * ltype) :=
                           match bs with
                           | [] => []
                           | (l, gk) :: rest => (l, project gk r) :: pbrs rest
                           end) brs)
        else match brs with
             | [] => LEnd
             | (_, gk) :: _ => project gk r
             end
    end.

  (* Standalone branch-list projection, used to reason about the GChoice   *)
  (* arm. proj_branches_eq below proves it equals the inner fix above.     *)
  Fixpoint proj_branches (bs : list (label * gtype)) (r : role) : list (label * ltype) :=
    match bs with
    | [] => []
    | (l, gk) :: rest => (l, project gk r) :: proj_branches rest r
    end.

  Lemma proj_branches_eq :
    forall brs r,
      (fix pbrs (bs : list (label * gtype)) : list (label * ltype) :=
         match bs with
         | [] => []
         | (l, gk) :: rest => (l, project gk r) :: pbrs rest
         end) brs = proj_branches brs r.
  Proof.
    induction brs as [| [l gk] rest IH]; intro r.
    - reflexivity.
    - simpl. f_equal. apply IH.
  Qed.

  (* The mergeability side-condition (plain merge), as a Prop over project *)
  (* equality: for any bystander r and any two branches, the per-branch    *)
  (* projections coincide. This is exactly what makes the head branch a    *)
  (* sound canonical representative for a bystander's view of a choice.    *)
  Definition bystanders_agree (p q : role) (brs : list (label * gtype)) : Prop :=
    forall r l1 g1 l2 g2,
      r <> p -> r <> q -> In (l1, g1) brs -> In (l2, g2) brs ->
      project g1 r = project g2 r.

  (* Local-type one-step relation for a single role's endpoint view. *)
  Inductive lstep : ltype -> ltype -> Prop :=
  | LStep_Send : forall q l k, lstep (LSend q l k) k
  | LStep_Recv : forall p l k, lstep (LRecv p l k) k
  | LStep_Sel  : forall q brs l k, In (l, k) brs -> lstep (LSelect q brs) k
  | LStep_Bra  : forall p brs l k, In (l, k) brs -> lstep (LBranch p brs) k.

  (* ===================================================================== *)
  (* T5 — projection soundness (GENERAL).                                  *)
  (*                                                                       *)
  (* The shape of a role's projection for each global head construct:      *)
  (* GMsg gives LSend (sender) / LRecv (receiver) / residual (bystander);  *)
  (* GChoice gives LSelect (sender) / LBranch (receiver) / head (bystander)*)
  (* ===================================================================== *)

  (* --- GMsg --- *)
  Theorem project_send_sound :
    forall p q l k, project (GMsg p q l k) p = LSend q l (project k p).
  Proof.
    intros. simpl. destruct (eq_role_dec p p) as [_ | n].
    - reflexivity.
    - exfalso. apply n. reflexivity.
  Qed.

  Theorem project_recv_sound :
    forall p q l k, p <> q -> project (GMsg p q l k) q = LRecv p l (project k q).
  Proof.
    intros p q l k Hpq. simpl. destruct (eq_role_dec q p) as [e | _].
    - exfalso. apply Hpq. symmetry. exact e.
    - destruct (eq_role_dec q q) as [_ | n].
      + reflexivity.
      + exfalso. apply n. reflexivity.
  Qed.

  Theorem project_bystander :
    forall p q l k r, r <> p -> r <> q -> project (GMsg p q l k) r = project k r.
  Proof.
    intros p q l k r Hp Hq. simpl.
    destruct (eq_role_dec r p) as [e | _]; [exfalso; apply Hp; exact e |].
    destruct (eq_role_dec r q) as [e | _]; [exfalso; apply Hq; exact e |].
    reflexivity.
  Qed.

  (* --- GChoice --- *)
  Theorem project_choice_sender :
    forall p q brs, project (GChoice p q brs) p = LSelect q (proj_branches brs p).
  Proof.
    intros p q brs. simpl.
    destruct (eq_role_dec p p) as [_ | n]; [| exfalso; apply n; reflexivity].
    f_equal. apply proj_branches_eq.
  Qed.

  Theorem project_choice_receiver :
    forall p q brs, p <> q ->
      project (GChoice p q brs) q = LBranch p (proj_branches brs q).
  Proof.
    intros p q brs Hpq. simpl.
    destruct (eq_role_dec q p) as [e | _]; [exfalso; apply Hpq; symmetry; exact e |].
    destruct (eq_role_dec q q) as [_ | n]; [| exfalso; apply n; reflexivity].
    f_equal. apply proj_branches_eq.
  Qed.

  Theorem project_choice_bystander :
    forall p q brs r,
      r <> p -> r <> q ->
      project (GChoice p q brs) r =
        match brs with [] => LEnd | (_, gk) :: _ => project gk r end.
  Proof.
    intros p q brs r Hp Hq. simpl.
    destruct (eq_role_dec r p) as [e | _]; [exfalso; apply Hp; exact e |].
    destruct (eq_role_dec r q) as [e | _]; [exfalso; apply Hq; exact e |].
    reflexivity.
  Qed.

  (* Membership transport: a chosen global branch (l,k) ∈ brs yields the   *)
  (* projected branch (l, project k r) ∈ proj_branches brs r — so the      *)
  (* sender's LSelect (resp. receiver's LBranch) has a matching lstep.      *)
  Lemma in_proj_branches :
    forall brs r l k, In (l, k) brs -> In (l, project k r) (proj_branches brs r).
  Proof.
    induction brs as [| [l0 g0] rest IH]; intros r l k Hin; [inversion Hin |].
    simpl in Hin. destruct Hin as [Heq | Hin'].
    - inversion Heq; subst. simpl. left. reflexivity.
    - simpl. right. apply IH. exact Hin'.
  Qed.

  (* Inverse transport: every projected branch comes from a real global    *)
  (* branch with the same label (used for completeness / "no invention").  *)
  Lemma in_proj_branches_inv :
    forall brs r l lk,
      In (l, lk) (proj_branches brs r) ->
      exists gk, In (l, gk) brs /\ lk = project gk r.
  Proof.
    induction brs as [| [l0 g0] rest IH]; intros r l lk Hin; [inversion Hin |].
    simpl in Hin. destruct Hin as [Heq | Hin'].
    - inversion Heq; subst. exists g0. split; [left; reflexivity | reflexivity].
    - destruct (IH r l lk Hin') as [gk [Hgk Heq]].
      exists gk. split; [right; exact Hgk | exact Heq].
  Qed.

  (* ===================================================================== *)
  (* T6 — operational correspondence (GENERAL).                            *)
  (*                                                                       *)
  (* SOUNDNESS: a global step is matched by the participants' local steps  *)
  (* — the sender's projection lsteps to the residual, the receiver's      *)
  (* likewise, and every bystander's projection is unchanged (the GChoice  *)
  (* bystander case uses the plain-merge side-condition bystanders_agree). *)
  (* COMPLETENESS: every global step is *generated by* a sender-side local *)
  (* step, and no behaviour is invented (every fired label labels a real   *)
  (* branch). Stated as a bidirectional iff at the label level.            *)
  (* ===================================================================== *)

  (* --- Soundness, sender side --- *)
  Lemma sound_msg_sender :
    forall p q l k, lstep (project (GMsg p q l k) p) (project k p).
  Proof.
    intros p q l k. simpl.
    destruct (eq_role_dec p p) as [_ | n]; [| exfalso; apply n; reflexivity].
    apply LStep_Send.
  Qed.

  Lemma sound_choice_sender :
    forall p q brs l k,
      In (l, k) brs -> lstep (project (GChoice p q brs) p) (project k p).
  Proof.
    intros p q brs l k Hin.
    rewrite project_choice_sender.
    apply LStep_Sel with (l := l). apply in_proj_branches. exact Hin.
  Qed.

  (* --- Soundness, receiver side --- *)
  Lemma sound_msg_receiver :
    forall p q l k, p <> q -> lstep (project (GMsg p q l k) q) (project k q).
  Proof.
    intros p q l k Hpq. simpl.
    destruct (eq_role_dec q p) as [e | _]; [exfalso; apply Hpq; symmetry; exact e |].
    destruct (eq_role_dec q q) as [_ | n]; [| exfalso; apply n; reflexivity].
    apply LStep_Recv.
  Qed.

  Lemma sound_choice_receiver :
    forall p q brs l k,
      p <> q -> In (l, k) brs -> lstep (project (GChoice p q brs) q) (project k q).
  Proof.
    intros p q brs l k Hpq Hin.
    rewrite project_choice_receiver by exact Hpq.
    apply LStep_Bra with (l := l). apply in_proj_branches. exact Hin.
  Qed.

  (* --- Soundness, bystander side: projections are unchanged. --- *)
  Lemma sound_msg_bystander :
    forall p q l k r, r <> p -> r <> q -> project (GMsg p q l k) r = project k r.
  Proof.
    intros p q l k r Hp Hq. simpl.
    destruct (eq_role_dec r p) as [e | _]; [exfalso; apply Hp; exact e |].
    destruct (eq_role_dec r q) as [e | _]; [exfalso; apply Hq; exact e |].
    reflexivity.
  Qed.

  (* The key MERGE lemma: under bystanders_agree, the bystander's view of   *)
  (* the choice (the head branch's projection) equals its view of WHICHEVER *)
  (* branch is chosen — so a global choice step leaves a bystander          *)
  (* unchanged regardless of which branch fires.                            *)
  Lemma sound_choice_bystander :
    forall p q brs l k r,
      r <> p -> r <> q ->
      bystanders_agree p q brs ->
      In (l, k) brs ->
      project (GChoice p q brs) r = project k r.
  Proof.
    intros p q brs l k r Hp Hq Hag Hin.
    rewrite project_choice_bystander by assumption.
    destruct brs as [| [l0 g0] rest]; [inversion Hin |].
    apply (Hag r l0 g0 l k Hp Hq).
    - simpl. left. reflexivity.
    - exact Hin.
  Qed.

  (* BUNDLED SOUNDNESS: every global step is matched, on the sender's       *)
  (* projection, by a corresponding local step. The sender is recovered by  *)
  (* casing on the step (GEnd cannot step, discharged by True).             *)
  Theorem projection_sound :
    forall g g',
      gstep g g' ->
      match g with
      | GEnd => True
      | GMsg p _ _ _ => lstep (project g p) (project g' p)
      | GChoice p _ _ => lstep (project g p) (project g' p)
      end.
  Proof.
    intros g g' Hstep.
    destruct Hstep as [p q l k | p q brs l k Hin].
    - apply sound_msg_sender.
    - apply sound_choice_sender with (l := l). exact Hin.
  Qed.

  (* --- Completeness / bidirectional correspondence --- *)

  (* GMsg: the protocol fires the message IFF the sender's LSend fires. *)
  Lemma gstep_iff_sender_lstep_msg :
    forall p q l k,
      gstep (GMsg p q l k) k <-> lstep (project (GMsg p q l k) p) (project k p).
  Proof.
    intros p q l k. split.
    - intros _. apply sound_msg_sender.
    - intros _. apply GS_Msg.
  Qed.

  (* GChoice: globally firing branch label l (reaching gk) IFF the sender's *)
  (* LSelect fires label l (reaching project gk p). Bidirectional, at the   *)
  (* label level: no global behaviour without a matching local one and vice *)
  (* versa.                                                                  *)
  Lemma gstep_iff_sender_lstep_choice :
    forall p q brs l gk,
      (In (l, gk) brs /\ gstep (GChoice p q brs) gk)
      <->
      (In (l, gk) brs /\ lstep (project (GChoice p q brs) p) (project gk p)).
  Proof.
    intros p q brs l gk. split.
    - intros [Hin _]. split; [exact Hin |].
      apply sound_choice_sender with (l := l). exact Hin.
    - intros [Hin _]. split; [exact Hin |].
      apply GS_Choice with (l := l). exact Hin.
  Qed.

  (* "No behaviour invented": every global step out of a choice fires a     *)
  (* label that genuinely labels one of the choice's branches.              *)
  Lemma gstep_choice_fires_real_label :
    forall p q brs k,
      gstep (GChoice p q brs) k -> exists l, In (l, k) brs.
  Proof.
    intros p q brs k Hstep.
    inversion Hstep as [| p' q' brs' l' k' Hin Heq1 Heq2]; subst.
    exists l'. exact Hin.
  Qed.

  (* Completeness, sender-generated, GChoice: any local step the sender's   *)
  (* projection can take is generated by (and reflected as) a real global   *)
  (* step on a matching branch — the constructive inverse of soundness.     *)
  Lemma sender_lstep_induces_gstep_choice :
    forall p q brs lk,
      lstep (project (GChoice p q brs) p) lk ->
      exists l gk, In (l, gk) brs /\ lk = project gk p /\ gstep (GChoice p q brs) gk.
  Proof.
    intros p q brs lk Hls.
    rewrite project_choice_sender in Hls.
    inversion Hls as [| | q' brs' l' k' Hin Heq1 Heq2 | ]; subst.
    destruct (in_proj_branches_inv brs p l' lk Hin) as [gk [Hgk Heq]].
    exists l', gk. split; [exact Hgk | split; [exact Heq |]].
    apply GS_Choice with (l := l'). exact Hgk.
  Qed.

  (* ===================================================================== *)
  (* T6 corollary — protocol fidelity for the choice-free fragment: the    *)
  (* projection of a linear protocol onto a role is exactly that role's     *)
  (* view of the global trace (no communication lost, none invented). This  *)
  (* is the original T6, retained verbatim as a special case of the general *)
  (* correspondence above.                                                  *)
  (* ===================================================================== *)

  Fixpoint choice_free (g : gtype) : bool :=
    match g with
    | GEnd => true
    | GMsg _ _ _ k => choice_free k
    | GChoice _ _ _ => false
    end.

  Fixpoint gtrace (g : gtype) : list (role * role * label) :=
    match g with
    | GEnd => []
    | GMsg p q l k => (p, q, l) :: gtrace k
    | GChoice _ _ _ => []
    end.

  Fixpoint local_of_trace (tr : list (role * role * label)) (r : role) : ltype :=
    match tr with
    | [] => LEnd
    | (p, q, l) :: rest =>
        if eq_role_dec r p then LSend q l (local_of_trace rest r)
        else if eq_role_dec r q then LRecv p l (local_of_trace rest r)
        else local_of_trace rest r
    end.

  Theorem protocol_fidelity :
    forall g r, choice_free g = true -> project g r = local_of_trace (gtrace g) r.
  Proof.
    induction g as [| p q l k IH | p q brs]; intros r Hcf.
    - reflexivity.
    - simpl in Hcf. specialize (IH r Hcf). simpl.
      destruct (eq_role_dec r p) as [_ | _]; destruct (eq_role_dec r q) as [_ | _];
        rewrite IH; reflexivity.
    - simpl in Hcf. discriminate.
  Qed.

End Csm.

