//! Auto-active program verifiers: source + annotations discharged largely
//! automatically by an SMT backend.

use super::{FV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        tool(
            "dafny",
            "Dafny",
            FV,
            "auto_active_verifier",
            "Verification-aware language whose pre/postconditions and invariants are discharged automatically by Z3.",
            "You write methods with `requires`/`ensures`/`invariant`/`decreases` annotations; Dafny generates verification conditions, proves them with Z3, then compiles to C#/Java/Go/Python/JS.",
            "Reach for Dafny to verify imperative algorithms (sorting, data structures, invariants) with minimal manual proof — the SMT solver does the heavy lifting; great for teaching and for correct-by-construction code.",
            "Input: `.dfy` source with specifications. Output: a verification verdict + compiled program in a target language.",
            "`dafny verify Foo.dfy` checks; `dafny build/run Foo.dfy` compiles/runs; `dafny test` runs `{:test}` methods.",
            "Low proof burden (SMT-automated); multi-language codegen; strong termination/framing support.",
            "Hits SMT brittleness on nonlinear/quantified goals; verification can be flaky/slow; not for interactive higher-order proofs.",
            &["why3", "verus", "fstar", "z3"],
            "pacman: dafny-bin (/usr/bin/dafny)",
            "https://dafny.org",
        ),
        tool(
            "why3",
            "Why3",
            FV,
            "auto_active_verifier",
            "Deductive-verification platform that dispatches proof obligations to many backend provers (Z3, CVC5, E, …).",
            "WhyML programs/specs are translated to verification conditions that Why3 sends to a configurable pool of SMT solvers and ITPs; it is also the proof backend used by Creusot, Frama-C, and SPARK.",
            "Reach for Why3 when you want a prover-agnostic VC platform — try several solvers on each goal, split/transform obligations in the IDE, and fall back to Coq for the hard ones.",
            "Input: `.mlw` (WhyML) or VCs from a front-end. Output: per-goal proved/unproved status across the chosen provers.",
            "`why3 config detect` registers installed solvers; `why3 prove -P z3 Foo.mlw` proves on the CLI; `why3 ide Foo.mlw` opens the proof-session IDE.",
            "Solver-agnostic (one goal, many provers); transformations + session management; the hub behind Creusot/SPARK.",
            "Front-end/setup overhead; ultimately bounded by the backend solvers; WhyML is a niche language.",
            &["creusot", "dafny", "z3", "cvc5", "rocq"],
            "opam: ~/.opam/default/bin/why3 (1.8.2)",
            "https://www.why3.org",
        ),
        tool(
            "verus",
            "Verus",
            FV,
            "auto_active_verifier",
            "SMT-based verifier for a subset of Rust — prove panic-freedom and functional correctness of real Rust code.",
            "Verus extends Rust with `requires`/`ensures`/`invariant`/`proof` blocks and ghost code, encoding them to Z3 so you verify ownership-aware Rust (including `unsafe`/concurrency idioms) without leaving the language.",
            "Reach for Verus to prove memory-safety, absence of overflow/panics, or full functional correctness of Rust — ideal for this workspace's Rust code where you want machine-checked guarantees, not just tests.",
            "Input: Rust crates using the `vstd`/`builtin` spec API. Output: a verification verdict (compiles the proof, erases ghost code).",
            "`verus foo.rs` verifies a file; project integration via the `verus`/`cargo-verus` driver; backed by a bundled Z3.",
            "Verifies idiomatic Rust in-language; reasons about ownership/linearity; strong for systems code.",
            "Supports a Rust subset (not all std); SMT brittleness on complex specs; tooling still maturing.",
            &["creusot", "dafny", "fstar", "z3"],
            "pacman: verus-bin (/usr/bin/verus)",
            "https://verus-lang.github.io/verus/guide/",
        ),
        tool(
            "creusot",
            "Creusot",
            FV,
            "auto_active_verifier",
            "Deductive verifier for Rust that translates annotated code to WhyML for proof via Why3.",
            "Using the Pearlite specification language in `#[requires]`/`#[ensures]` attributes, Creusot compiles ownership-typed Rust to WhyML and discharges the obligations through Why3's solver pool.",
            "Reach for Creusot to verify safe Rust against rich first-order specs while leveraging Why3's multi-prover backend — an alternative to Verus that routes through Why3 rather than calling Z3 directly.",
            "Input: Rust with Pearlite specs. Output: WhyML + a Why3 proof session (proved/unproved goals).",
            "`cargo creusot` translates+proves a crate (then drive the proof in `why3 ide`). NOTE: not currently on PATH here.",
            "Leverages Why3's many backends; models Rust ownership precisely; Pearlite specs are expressive.",
            "Not installed on this machine; safe-Rust subset; depends on a working Why3 toolchain.",
            &["verus", "why3", "dafny"],
            "Not currently installed (creusot / cargo-creusot absent from PATH). Install via `cargo install creusot` + a Why3 setup; Why3 itself is present (opam).",
            "https://github.com/creusot-rs/creusot",
        ),
        tool(
            "esbmc",
            "ESBMC",
            FV,
            "auto_active_verifier",
            "Bounded / k-induction model checker for C and C++ that finds bugs and proves bounded safety via SMT.",
            "ESBMC unrolls a program and encodes paths to an SMT solver to detect memory-safety, overflow, and assertion violations, or to prove their absence by k-induction / incremental BMC.",
            "Reach for ESBMC to hunt undefined behavior and memory errors in C/C++ (or prove their absence up to a bound) without annotating the source — push-button, counterexample-producing analysis.",
            "Input: `.c`/`.cpp` translation units. Output: VERIFICATION SUCCESSFUL/FAILED + a counterexample trace.",
            "`esbmc foo.c --incremental-bmc` (incremental BMC); `esbmc foo.c --k-induction` (unbounded proof attempt); `--overflow-check --memory-leak-check` enable extra properties.",
            "Push-button (no annotations); concrete counterexamples; mature C/C++ memory-safety checks.",
            "Bounded by default (may miss deep bugs); state explosion on large programs; less suited to full functional correctness.",
            &["dafny", "verus", "z3", "bitwuzla", "gpuverify"],
            "pacman: esbmc (/usr/bin/esbmc)",
            "http://esbmc.org",
        ),
    ]
}
