//! Interactive debuggers, compiler sanitizers, and the async-runtime / JVM
//! introspection tools.

use super::{DEV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- Debuggers ----
        tool(
            "gdb",
            "GDB",
            DEV,
            "debugger",
            "The GNU source-level debugger for native programs — breakpoints, stepping, inspection, and core dumps.",
            "GDB controls a process (or core dump): set breakpoints/watchpoints, step, inspect variables/registers/memory, walk stacks, script with Python, and even reverse-execute. Native process-record reverse debugging (`target record-full` then `reverse-step`/`reverse-continue`/`reverse-next`) replays execution backward from a breakpoint to the instruction that corrupted state — invaluable for `wrong value got here` bugs, though record-full is slow and x86/64-only.",
            "Reach for GDB to debug crashes, inspect a hung process, or analyze a core dump for C/C++/Rust — set breakpoints, print state, and get a backtrace at the fault. For `how did this value get here?` use reverse execution: `target record-full`, continue to the fault, then `reverse-continue`/`reverse-step` back to the culprit (or use rr for a faster, lower-overhead time-travel replay).",
            "Input: a binary, a PID (`-p`), or a core file. Output: an interactive session / scripted output (e.g. backtraces).",
            "`gdb ./prog` (then `break`/`run`/`bt`/`print`); `gdb -p <pid>`; `gdb --batch -ex run -ex bt ./prog core`; reverse debugging: `(gdb) target record-full` → `continue` → `reverse-continue` / `reverse-step` / `reverse-next`.",
            "Powerful + scriptable (Python); attach/core support; built-in reverse debugging (`target record-full`/`reverse-continue`); ubiquitous.",
            "Native code (needs debug symbols); CLI learning curve; weak Rust pretty-printing without rust-gdb.",
            &["lldb", "cgdb", "rust-gdb", "rr"],
            "pacman: gdb (/usr/bin/gdb)",
            "https://sourceware.org/gdb/",
        ),
        tool(
            "rr",
            "rr (record & replay)",
            DEV,
            "debugger",
            "Mozilla's record-and-replay time-travel debugger: record a run once, then deterministically replay it forward AND backward under gdb.",
            "rr records a process's execution to a trace by serializing nondeterminism (syscalls, signals, thread scheduling) onto a single core, then replays that trace deterministically — every replay reproduces the exact same execution, including the bug. Replays drive a gdb backend, so you get gdb's full command set plus reliable `reverse-continue`/`reverse-step`/`reverse-next` and hardware watchpoints to run time backward to where a value was clobbered. Far lower overhead than gdb's own `record-full`.",
            "Reach for rr when a bug is intermittent, timing-dependent, or `how did this value get corrupted?` — record until it reproduces, then replay and step backward from the fault to the root cause. The deterministic replay turns a heisenbug into a reproducible one you can revisit as many times as needed.",
            "Input: a command to record (`rr record ./prog args`). Output: a trace under ~/.local/share/rr replayed with `rr replay` (drops into gdb).",
            "`rr record ./prog --flags`; `rr replay` (then `continue`, `reverse-continue`, `reverse-step`, `watch -l expr`); `rr ps` / `rr pack` to manage traces.",
            "Deterministic replay (heisenbugs become reproducible); true reverse execution with gdb's UX; low overhead vs record-full; hardware watchpoints in replay.",
            "Linux/x86-64 + recent Intel/AMD (needs specific perf counters; best-effort on Zen3 — some PMU features are restricted, so verify `rr record` succeeds on your CPU); single-core record (perturbs heavy parallelism); native code only.",
            &["gdb", "lldb", "valgrind-memcheck"],
            "pacman: rr (/usr/bin/rr)",
            "https://rr-project.org/",
        ),
        tool(
            "cgdb",
            "CGDB",
            DEV,
            "debugger",
            "Curses front-end to GDB with a split source/command view.",
            "CGDB drives GDB underneath while showing the source with the current line and breakpoints in a top pane and the GDB console below — vim-like navigation over a live debug session.",
            "Reach for CGDB when you want GDB's power but with a visible source context in the terminal, without a full IDE.",
            "Input: same as GDB (binary/PID/core). Output: a split-screen interactive debug session.",
            "`cgdb ./prog`; navigate the source pane with vim keys; the lower pane is the normal GDB prompt.",
            "Source context in the terminal; all of GDB underneath; lightweight.",
            "Terminal-only; thin wrapper (GDB knowledge still required); native code.",
            &["gdb"],
            "pacman: cgdb (/usr/bin/cgdb)",
            "https://cgdb.github.io/",
        ),
        tool(
            "lldb",
            "LLDB",
            DEV,
            "debugger",
            "The LLVM project's source-level debugger, the Clang/Swift/Rust-friendly counterpart to GDB.",
            "LLDB offers breakpoints, stepping, expression evaluation, and scripting (Python) atop LLVM, often with better Clang/Rust type support and a modern command grammar.",
            "Reach for LLDB to debug Clang/Rust binaries (especially where LLVM debug info is richer), or when you prefer its command set/Python API over GDB.",
            "Input: a binary, a PID (`-p`), or a core. Output: an interactive session / scripted output.",
            "`lldb ./prog` (then `b`/`r`/`bt`/`p`); `lldb -p <pid>`; `lldb -o run -o bt -b ./prog` for batch.",
            "Strong LLVM/Clang/Rust support; Python scripting; modern UX.",
            "Native code; command syntax differs from GDB; pretty-printing best via rust-lldb for Rust.",
            &["gdb", "rust-lldb"],
            "pacman: lldb (/usr/bin/lldb)",
            "https://lldb.llvm.org/",
        ),
        tool(
            "rust-gdb",
            "rust-gdb",
            DEV,
            "debugger",
            "GDB wrapper that loads Rust pretty-printers for readable `Vec`/`String`/enum/`Option` inspection.",
            "rust-gdb launches GDB with the Rust standard-library pretty-printers registered, so values print in Rust form instead of raw memory layout.",
            "Reach for rust-gdb instead of plain GDB when debugging Rust binaries in this workspace — you get legible Rust values and enum variants out of the box.",
            "Input: a Rust debug binary / PID / core. Output: a GDB session with Rust-aware printing.",
            "`rust-gdb ./target/debug/prog`; otherwise identical to GDB (`break`/`run`/`bt`/`print`).",
            "Readable Rust values; everything GDB can do; ships with the Rust toolchain.",
            "Rust-focused; still GDB underneath (same learning curve); needs debug builds.",
            &["gdb", "rust-lldb"],
            "rustup: ~/.cargo/bin/rust-gdb",
            "https://doc.rust-lang.org/cargo/commands/cargo-test.html",
        ),
        tool(
            "rust-lldb",
            "rust-lldb",
            DEV,
            "debugger",
            "LLDB wrapper that loads Rust pretty-printers for readable value inspection.",
            "rust-lldb starts LLDB with the Rust formatters registered so Rust types display idiomatically; the LLDB analogue of rust-gdb.",
            "Reach for rust-lldb to debug Rust with LLDB (e.g. where LLVM debug info or your platform favours LLDB) while keeping legible Rust value printing.",
            "Input: a Rust debug binary / PID / core. Output: an LLDB session with Rust-aware printing.",
            "`rust-lldb ./target/debug/prog`; otherwise the normal LLDB commands (`b`/`r`/`bt`/`p`).",
            "Readable Rust values under LLDB; ships with the Rust toolchain.",
            "Rust-focused; LLDB command set; needs debug builds.",
            &["lldb", "rust-gdb"],
            "rustup: ~/.cargo/bin/rust-lldb",
            "https://doc.rust-lang.org/cargo/commands/cargo-test.html",
        ),
        // ---- Sanitizers ----
        tool(
            "asan",
            "AddressSanitizer (ASan)",
            DEV,
            "sanitizer",
            "Compiler-instrumentation detector for memory-corruption bugs with low overhead and precise reports.",
            "Built into GCC/Clang (and Rust nightly), ASan instruments memory accesses + allocations to catch heap/stack/global buffer overflows, use-after-free/return/scope, and (with LSan) leaks, printing the faulting + allocation stacks.",
            "Reach for ASan as the first line against memory corruption in C/C++/Rust-`unsafe`/FFI — it's ~2× overhead (vs Valgrind's 10–30×) and gives exact buggy + allocation stacks, ideal in tests/CI.",
            "Input: code compiled with `-fsanitize=address -g`. Output: a runtime abort with a detailed error + stacks.",
            "`cc -fsanitize=address -g prog.c && ./a.out`; Rust: `RUSTFLAGS=-Zsanitizer=address cargo +nightly test`; tune via `ASAN_OPTIONS`.",
            "Fast vs. Valgrind; precise overflow/UAF detection; great in CI.",
            "Requires recompilation; ~2× CPU + extra memory; can't instrument prebuilt libs.",
            &["valgrind-memcheck", "lsan", "ubsan"],
            "GCC/Clang runtime: libasan (pacman); clang/clang19; Rust nightly -Zsanitizer",
            "https://clang.llvm.org/docs/AddressSanitizer.html",
        ),
        tool(
            "tsan",
            "ThreadSanitizer (TSan)",
            DEV,
            "sanitizer",
            "Compiler-instrumentation detector for data races and some synchronization bugs.",
            "TSan (GCC/Clang, Rust nightly) instruments memory accesses + sync primitives to detect data races, reporting the two conflicting accesses with stacks and the involved threads.",
            "Reach for TSan to find data races in multithreaded C/C++/Rust by building with it and exercising concurrent paths under tests — catches races that only sometimes manifest.",
            "Input: code compiled with `-fsanitize=thread -g`. Output: a race report (two stacks + threads) at detection.",
            "`cc -fsanitize=thread -g prog.c && ./a.out`; Rust: `RUSTFLAGS=-Zsanitizer=thread cargo +nightly test`; `TSAN_OPTIONS` to tune.",
            "Finds real data races with both stacks; far faster than re-deriving from crashes.",
            "Recompilation; ~5–15× overhead + memory; misses races on unexercised interleavings.",
            &["valgrind-helgrind", "asan"],
            "GCC/Clang runtime: libtsan (pacman); Rust nightly -Zsanitizer=thread",
            "https://clang.llvm.org/docs/ThreadSanitizer.html",
        ),
        tool(
            "lsan",
            "LeakSanitizer (LSan)",
            DEV,
            "sanitizer",
            "Lightweight memory-leak detector, usable standalone or bundled inside AddressSanitizer.",
            "LSan tracks allocations and, at exit, reports blocks still reachable-but-unfreed with their allocation stacks, at much lower cost than a full Valgrind leak check.",
            "Reach for LSan for cheap leak detection in tests/CI — either via `-fsanitize=leak` alone or automatically as part of an ASan build.",
            "Input: code built with `-fsanitize=leak` (or ASan). Output: an end-of-run leak report with stacks.",
            "`cc -fsanitize=leak -g prog.c && ./a.out`; with ASan it runs automatically at exit; `LSAN_OPTIONS`/suppressions to tune.",
            "Cheap leak detection; allocation stacks; CI-friendly.",
            "Leaks only (not corruption); recompilation; suppressions often needed for libs.",
            &["asan", "valgrind-memcheck", "heaptrack"],
            "GCC/Clang runtime: liblsan (pacman); part of ASan",
            "https://clang.llvm.org/docs/LeakSanitizer.html",
        ),
        tool(
            "ubsan",
            "UndefinedBehaviorSanitizer (UBSan)",
            DEV,
            "sanitizer",
            "Compiler-instrumentation detector for undefined behaviour at run time.",
            "UBSan inserts checks for signed-integer overflow, out-of-bounds indexing, null/misaligned pointers, invalid casts/enums, division by zero, and more, reporting the exact offending operation.",
            "Reach for UBSan to flush out latent UB in C/C++ that 'works by luck' — build with it and run your tests to catch overflow/OOB/alignment bugs at their source.",
            "Input: code built with `-fsanitize=undefined -g`. Output: a precise UB diagnostic at each violation.",
            "`cc -fsanitize=undefined -g prog.c && ./a.out`; combine with ASan; `-fsanitize=undefined,address`; `UBSAN_OPTIONS=print_stacktrace=1`.",
            "Pinpoints UB precisely; cheap; composes with ASan.",
            "C/C++-centric; recompilation; only the checks you enable; some checks need a runtime lib.",
            &["asan"],
            "GCC/Clang runtime: libubsan (pacman)",
            "https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html",
        ),
        // ---- Async-runtime / JVM ----
        tool(
            "tokio-console",
            "tokio-console",
            DEV,
            "async_debugger",
            "Runtime debugger for Tokio async applications — live task, resource, and poll-time introspection.",
            "tokio-console connects to an instrumented Tokio app (via the `console-subscriber`) and shows per-task busy/idle/poll times, wakers, and resource waits, surfacing stalled tasks, long polls, and leaks of tasks/resources.",
            "Reach for tokio-console to diagnose async problems this workspace's Tokio runtime can hit — a task that never wakes, a future that blocks the executor, or steadily growing task counts.",
            "Input: a Tokio app built with `console-subscriber` + `tokio_unstable`. Output: a live TUI of tasks/resources.",
            "App: add `console_subscriber::init()` and build with `RUSTFLAGS=\"--cfg tokio_unstable\"`; then run `tokio-console` to connect.",
            "Purpose-built async visibility (poll times, stalls, leaks); live TUI; the right tool for executor issues.",
            "Requires app instrumentation + `tokio_unstable`; Tokio-specific; not a CPU profiler.",
            &["gdb", "perf"],
            "pacman: tokio-console (/usr/bin/tokio-console)",
            "https://github.com/tokio-rs/console",
        ),
        tool(
            "visualvm",
            "VisualVM",
            DEV,
            "jvm_profiler",
            "All-in-one visual tool for monitoring and profiling Java Virtual Machines.",
            "VisualVM attaches to local/remote JVMs to show live CPU/memory/thread metrics, sampling/instrumenting CPU + memory profilers, heap-dump analysis, and thread dumps — integrating several JDK tools in one GUI.",
            "Reach for VisualVM to profile or diagnose JVM programs (this machine has many JVM tools: Gradle/Maven/Kotlin/Scala/Clojure) — find Java hotspots, memory growth, or thread contention.",
            "Input: a running JVM (local or JMX/remote) or a heap dump. Output: interactive profiles, heap analysis, thread dumps.",
            "`visualvm` launches the GUI; pick a JVM process to monitor/profile, or load a `.hprof` heap dump.",
            "Free, GUI, all-in-one JVM CPU/memory/thread profiling + heap analysis; remote via JMX.",
            "JVM-only; sampling/instrumenting overhead; GUI/desktop required.",
            &["perf", "vtune"],
            "pacman: visualvm (/usr/bin/visualvm)",
            "https://visualvm.github.io/",
        ),
    ]
}
