//! Diagramming tools that draw *structure* from text: node-edge graph layout,
//! UML / architecture / sequence "diagrams-as-code", and programmatic vector
//! picture languages. Probe-grounded for this machine (TeX Live 2026, graphviz
//! 14.x, OpenJDK 26, repo workspace npm tools).

use super::{DIA, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- graph_layout ----
        tool(
            "graphviz",
            "Graphviz",
            DIA,
            "graph_layout",
            "The canonical node-edge graph layout suite — DOT language in, SVG/PNG/PDF out, six layout engines.",
            "Graphviz lays out directed/undirected graphs written in the DOT language using a family of engines: `dot` (layered/hierarchical DAGs), `neato`/`fdp`/`sfdp` (force-directed/spring), `twopi` (radial), `circo` (circular), plus `osage`/`patchwork` (clustered/treemap). It renders to SVG, PNG, PDF, PS, and JSON, and ships graph-processing filters (`acyclic`, `tred` transitive reduction, `ccomps`, `unflatten`, `gvpack`).",
            "Reach for Graphviz to visualize any relationship graph from text — call graphs, dependency/import graphs, state machines, ER sketches, org charts — especially when the diagram is generated programmatically; it is the de-facto backend most other tools (PlantUML, dot2tex, doxygen) emit DOT for.",
            "Input: a `.dot`/`.gv` file or stdin (DOT language). Output: `-Tsvg`/`-Tpng`/`-Tpdf`/`-Tps`/`-Tjson` to stdout or `-o file`.",
            "`dot -Tsvg graph.dot -o graph.svg` (hierarchical); `neato -Tpng` or `sfdp -Tsvg` for large force-directed graphs; `twopi`/`circo` for radial/circular; pick an engine inline with `dot -Kfdp`; `tred in.dot | dot -Tsvg` to drop redundant edges first.",
            "Ubiquitous, scriptable, deterministic; six layout algorithms; huge format support; the lingua-franca DOT format other tools target; handles very large graphs with `sfdp`.",
            "Automatic layout can be ugly for hand-tuned diagrams (use d2/draw.io for control); DOT has no semantic diagram types (no native UML/sequence — use PlantUML); edge routing on dense graphs gets cluttered.",
            &["d2", "gvpr", "dot2tex", "mermaid-cli"],
            "pacman: graphviz (/usr/bin/dot, v14.1.5; engines neato/fdp/sfdp/twopi/circo/osage/patchwork + filters acyclic/tred/ccomps/unflatten/gvpack)",
            "https://graphviz.org/",
        ),
        tool(
            "gvpr",
            "gvpr (Graphviz pattern scanner)",
            DIA,
            "graph_layout",
            "awk-for-graphs — a DOT graph stream editor that filters, transforms, and computes over nodes/edges.",
            "gvpr (Graph Pattern Recognizer) runs a C-like per-node/per-edge program over a DOT graph, in the spirit of awk: it selects subgraphs, rewrites attributes, computes degrees/paths, extracts neighborhoods, and emits a transformed DOT graph — letting you preprocess a graph before handing it to a Graphviz layout engine.",
            "Reach for gvpr when you need to slice or rewrite a generated graph before drawing it — extract the k-hop neighborhood of a node, recolor edges by weight, prune leaf nodes, or merge duplicate edges — without writing a full graph-library program.",
            "Input: a DOT graph (file/stdin) + a gvpr program (`-f prog.gvpr` or inline `-c`). Output: a transformed DOT graph.",
            "`gvpr -c 'N[indegree==0]' g.dot` keeps source nodes; `gvpr -f prune.gvpr g.dot | dot -Tsvg`; `BEGIN/END/N{}/E{}` blocks mirror awk; pair with `ccomps -x` to split components.",
            "Graph-aware stream editing with no external dependency; composes perfectly with the Graphviz pipeline; access to degrees, paths, and node/edge attributes.",
            "Niche DSL with a learning curve; per-graph imperative logic only (not a query language like Cypher); ships with Graphviz so it lives or dies with the DOT format.",
            &["graphviz"],
            "pacman: graphviz (/usr/bin/gvpr, v14.1.5)",
            "https://graphviz.org/pdf/gvpr.1.pdf",
        ),
        // ---- uml_architecture ----
        tool(
            "plantuml",
            "PlantUML",
            DIA,
            "uml_architecture",
            "Text-to-UML powerhouse — sequence, class, state, activity, component, deployment, ER, C4, mindmap, Gantt.",
            "PlantUML compiles a compact textual notation into rendered diagrams for nearly every UML type plus many non-UML kinds (ER, JSON/YAML, mindmaps, WBS, Gantt, network/nwdiag, C4 via the C4-PlantUML stdlib). It uses Graphviz for some layouts and its own engine for sequence diagrams, emitting SVG/PNG/PDF/LaTeX.",
            "Reach for PlantUML as the default for *semantic* software diagrams kept under version control — a sequence or class diagram defined in text diffs cleanly, regenerates in CI, and stays in sync with the code far better than a binary drawing.",
            "Input: a `.puml`/`.plantuml` file (or stdin via `-pipe`). Output: `-tsvg`/`-tpng`/`-tpdf`/`-tlatex` next to the source or to stdout.",
            "`plantuml -tsvg diagram.puml` writes diagram.svg; `plantuml -pipe < in.puml > out.svg`; C4: `!include <C4/C4_Container>` then `Container(...)`; `plantuml -checkonly` validates; sequence/class/state via `@startuml … @enduml`.",
            "Covers the widest range of UML + adjacent diagram types of any text tool; mature; great for sequence diagrams; C4 support; CI-friendly and diffable.",
            "JVM startup latency per invocation; Graphviz-backed layouts inherit auto-layout ugliness; large diagrams need `-DPLANTUML_LIMIT_SIZE`; styling is less flexible than d2/draw.io.",
            &["mermaid-cli", "d2", "structurizr", "drawio", "mscgenjs"],
            "pacman: plantuml (/usr/bin/plantuml, v1.2026.5; runs on OpenJDK 26)",
            "https://plantuml.com/",
        ),
        tool(
            "mermaid-cli",
            "Mermaid CLI (mmdc)",
            DIA,
            "uml_architecture",
            "Markdown-friendly diagrams-as-code — flowcharts, sequence, class, state, ER, Gantt, gitgraph — rendered headless.",
            "The Mermaid CLI (`mmdc`) renders Mermaid's concise text syntax (the same syntax GitHub/GitLab render inline) into SVG/PNG/PDF via headless Chromium. It covers flowcharts, sequence, class, state, ER, user-journey, Gantt, pie, gitgraph, and C4 diagrams.",
            "Reach for Mermaid when the diagram source should be portable to Markdown/docs sites and rendered both inline (GitHub) and to files (CI) — it is the lowest-friction way to keep flowcharts and sequence diagrams beside the code.",
            "Input: a `.mmd` file (or Markdown with ```mermaid fences) + optional `-c config.json`/`-t theme`. Output: `-o out.svg`/`.png`/`.pdf`.",
            "`mmdc -i diagram.mmd -o diagram.svg`; `-t dark -b transparent` for theming; `-i README.md -o out.md` renders fenced blocks; puppeteer/Chromium runs headless (may need `-p puppeteer.json` with `--no-sandbox`).",
            "Same syntax as GitHub/GitLab inline rendering; broad diagram coverage; clean modern output; trivial Markdown integration.",
            "Bundles headless Chromium (heavy; sandbox flags often needed in CI); less expressive than PlantUML for full UML; layout is automatic with limited control.",
            &["plantuml", "d2", "drawio", "structurizr"],
            "pacman: mermaid-cli (/usr/bin/mmdc, v11.15.0; headless Chromium/puppeteer)",
            "https://mermaid.js.org/",
        ),
        tool(
            "d2",
            "D2 (Terrastruct)",
            DIA,
            "uml_architecture",
            "Modern declarative diagram language with multiple layout engines and first-class styling/animation.",
            "D2 is a diagram scripting language and compiler purpose-built for software architecture: you declare shapes, connections, containers, and SQL/UML tables, and D2 lays them out via pluggable engines (`dagre`, `elk`, or the proprietary `tala`), rendering crisp SVG/PNG/PDF with themes, sketch mode, and multi-board (layered) diagrams.",
            "Reach for D2 when you want architecture diagrams that look hand-designed but stay text-defined — its container model, connection styling, and `elk` layout produce noticeably cleaner system diagrams than Graphviz/Mermaid, and `--watch` gives a live preview while editing.",
            "Input: a `.d2` file. Output: `out.svg`/`.png`/`.pdf` (format inferred from extension).",
            "`d2 architecture.d2 out.svg`; `d2 --layout elk in.d2 out.svg` for the cleaner engine; `d2 --watch in.d2` serves a live-reload preview; `d2 fmt in.d2` formats; `--theme 200` and `--sketch` for styling.",
            "Best-in-class auto-layout aesthetics for architecture; containers/nesting; multiple engines; live watch; SQL-table & UML-class shapes; actively developed.",
            "Younger ecosystem than PlantUML/Graphviz; `tala` (the prettiest engine) is proprietary; not the inline-render default on code hosts (Mermaid is).",
            &[
                "plantuml",
                "mermaid-cli",
                "structurizr",
                "graphviz",
                "drawio",
            ],
            "/usr/bin/d2 (v0.7.1; layout engines dagre/elk)",
            "https://d2lang.com/",
        ),
        tool(
            "structurizr",
            "Structurizr CLI",
            DIA,
            "uml_architecture",
            "C4-model architecture-as-code — one DSL workspace exported to PlantUML/Mermaid/D2/Ilograph and more.",
            "Structurizr CLI turns a Structurizr DSL workspace (a single model of software systems, containers, components, and people) into multiple C4 views, then exports them to PlantUML, Mermaid, D2, DOT, Ilograph, or JSON. The model-once/render-many approach keeps a System Context, Container, and Component diagram consistent because they derive from one source of truth.",
            "Reach for Structurizr when documenting software architecture with the C4 model — define the model once in the DSL and generate consistent context/container/component diagrams, rather than hand-drawing each level and letting them drift.",
            "Input: a `workspace.dsl` (Structurizr DSL). Output: `export -format <plantuml|mermaid|d2|dot|ilograph|json>` writing per-view files.",
            "`structurizr export -workspace workspace.dsl -format mermaid` (or `plantuml`/`d2`); `structurizr validate -workspace workspace.dsl`; the new vNext command set replaces the deprecated `structurizr-cli` wrapper.",
            "Enforces the C4 model; single model → consistent multi-level views; exports to whichever renderer you already use; great for architecture docs in git.",
            "C4-specific (not a general drawing tool); requires learning the Structurizr DSL; the rich interactive features live in the paid Structurizr cloud/on-prem, not the CLI.",
            &["plantuml", "d2", "mermaid-cli", "drawio"],
            "/usr/bin/structurizr (v2026.05.16, engine 6.2.1; OpenJDK 26)",
            "https://docs.structurizr.com/cli",
        ),
        tool(
            "kroki",
            "Kroki",
            DIA,
            "uml_architecture",
            "One self-hosted HTTP render gateway: POST diagram source to `/<type>/<format>` and get SVG/PNG/PDF back. This instance fronts ~22 engines (Graphviz/PlantUML/D2/Structurizr/BPMN/Excalidraw/…).",
            "Kroki is a rendering server that unifies many text-to-diagram engines behind a single HTTP API: POST diagram source (or GET a deflate+base64url-encoded URL) to `/<type>/<format>` and it returns the rendered image. Engines split between the JVM core image and optional companion containers. This deployment (a `docker compose` stack: the `yuzutech/kroki` core + the `kroki-bpmn` and `kroki-excalidraw` companions, on :8000) renders graphviz/dot, plantuml + c4plantuml, d2, structurizr, nomnoml, umlet, erd, dbml, bytefield, wavedrom, tikz, pikchr, svgbob, ditaa, goat, vega + vega-lite, wireviz, symbolator, bpmn, and excalidraw — 22 engines verified by probe. The mermaid and diagrams.net companions are deliberately not run here (use the locally-installed `mermaid-cli`/`drawio` instead), and the `kroki-blockdiag` companion image is broken (returns empty SVGs), so the blockdiag suite is unavailable.",
            "Reach for Kroki when you want one uniform HTTP render endpoint instead of installing each engine's CLI — the simplest way to render diagram source over HTTP from any language with no local toolchain — and especially for engines you may not have standalone (bpmn, excalidraw, wireviz, symbolator) plus erd/nomnoml. For Mermaid use the local `mermaid-cli` (mmdc) and for draw.io use the local `drawio`; their Kroki companions aren't run on this instance. The blockdiag suite (blockdiag/seqdiag/actdiag/nwdiag/packetdiag/rackdiag) is unavailable here — its companion image renders empty.",
            "Input: raw diagram source as the POST body (or deflate+base64url-encoded in the GET path); supported `<type>` on this instance ∈ {graphviz, plantuml, c4plantuml, d2, structurizr, erd, dbml, nomnoml, umlet, bytefield, wavedrom, tikz, pikchr, svgbob, ditaa, goat, vega, vegalite, wireviz, symbolator, bpmn, excalidraw}; `<format>` ∈ {svg, png, pdf, jpeg, base64, txt} (engine-dependent). Output: the rendered bytes. Not served here: mermaid, diagramsnet, and the blockdiag suite.",
            "POST source: `curl -s http://localhost:8000/plantuml/svg --data-binary @diagram.puml -o out.svg` (swap `plantuml`→`graphviz`/`d2`/`bpmn`/`excalidraw`/`erd`/… and `svg`→`png`/`pdf`); JSON POST to root: `curl -s http://localhost:8000/ -H 'Content-Type: application/json' -d '{\"diagram_source\":\"digraph{a->b}\",\"diagram_type\":\"graphviz\",\"output_format\":\"svg\"}'`; GET form: `http://localhost:8000/<type>/<format>/<deflate+base64url-source>`; health: `curl -s http://localhost:8000/health` (lists a version for EVERY engine even when its companion isn't running — trust a real render, not the manifest).",
            "One HTTP endpoint for ~22 engines with no per-engine CLI install or version drift; renders engines you may not have standalone (bpmn, excalidraw, wireviz, symbolator) plus erd/nomnoml; language-agnostic HTTP; self-hosted (no diagram source leaves the host).",
            "Requires the Docker compose stack running on :8000 — not a binary on PATH, so every route fails if a container is down. Engines split between the JVM core and optional companion containers: this stack runs the bpmn + excalidraw companions but NOT mermaid or diagrams.net (use the local `mermaid-cli`/`drawio` cards), and the `kroki-blockdiag` companion image is broken — it returns HTTP 200 with an empty body for blockdiag/seqdiag/actdiag/nwdiag/packetdiag/rackdiag. `/health` reports versions for engines whose companion isn't running, so confirm with a real render. Output formats are engine-dependent (not every engine emits PDF/PNG); large diagrams can hit the server body-size limit; the GET form needs deflate+base64url pre-encoding.",
            &["plantuml", "mermaid-cli", "d2", "graphviz", "structurizr"],
            "docker compose (yuzutech/kroki core + kroki-bpmn + kroki-excalidraw companions) on http://localhost:8000 (Kroki 0.31.0, build 3c49ecd; verify with `curl -s http://localhost:8000/health`)",
            "https://docs.kroki.io/",
        ),
        tool(
            "drawio",
            "draw.io / diagrams.net (desktop)",
            DIA,
            "uml_architecture",
            "Full diagram editor whose agent-usable surface is headless `.drawio` → SVG/PNG/PDF export.",
            "draw.io Desktop is an Electron diagram editor (flowcharts, UML, network, BPMN, mockups). For automation its value is the command-line export: it renders a `.drawio`/`.xml` file to SVG, PNG, PDF, or VSDX without opening the UI — useful for regenerating committed `.drawio` diagrams in a pipeline.",
            "Reach for draw.io export when a repository already stores hand-authored `.drawio` diagrams and you need to (re)generate the published SVG/PNG headlessly; for greenfield text-defined diagrams prefer d2/PlantUML/Mermaid.",
            "Input: a `.drawio`/`.xml` file. Output: `--export --format svg|png|pdf --output out.ext`.",
            "`xvfb-run -a drawio -x -f svg -o out.svg diagram.drawio` (headless needs a virtual display); `--no-sandbox` in containers; `-f pdf --crop` for tight PDFs; multi-page via `-p N`.",
            "Round-trips human-authored diagrams; broad shape libraries; export to many formats; keeps `.drawio` as an editable source of truth.",
            "GUI-first (Electron) — headless export needs `xvfb-run`/`--no-sandbox` and a real display server; not a text DSL, so diagrams aren't cleanly diffable; heavyweight for CI.",
            &["plantuml", "mermaid-cli", "d2", "inkscape"],
            "pacman: drawio-desktop (/usr/bin/drawio, v30.0.4; Electron — headless export via xvfb-run)",
            "https://www.drawio.com/",
        ),
        tool(
            "mscgenjs",
            "mscgenjs",
            DIA,
            "uml_architecture",
            "Message Sequence Chart compiler — protocol/interaction timelines from a tiny text DSL.",
            "mscgenjs renders Message Sequence Charts from the classic `mscgen` language plus the richer `xù`/`msgenny` dialects: entities across the top, time flowing down, and arrows for synchronous/asynchronous/lost messages, boxes, and arcs — purpose-built for protocol and inter-process interaction diagrams.",
            "Reach for mscgenjs when documenting a wire protocol, an API handshake, or an inter-service message exchange where a dedicated MSC reads more clearly than a general UML sequence diagram — and you want it generated from text.",
            "Input: an `.msc`/`.mscin`/`.xu` file. Output: `-T svg|png|... -o out.svg` (SVG by default).",
            "`mscgenjs -T svg -i handshake.msc -o handshake.svg`; `-T png` for raster; `-i in.xu -p` for the richer msgenny/xù dialect; runs on Node from the workspace `node_modules/.bin`.",
            "Focused, readable MSC output; supports the standard mscgen syntax plus richer dialects; pure-JS (no native deps); good for protocol docs.",
            "Single diagram family (sequence/MSC only); smaller community than PlantUML/Mermaid sequence diagrams; installed repo-locally so invocation needs the workspace path or `npx`.",
            &["plantuml", "mermaid-cli", "wavedrom-cli"],
            "npm (workspace node_modules): /home/dylon/Workspace/f1r3fly.io/node_modules/.bin/mscgenjs (mscgenjs-cli v5.0.1)",
            "https://mscgen.js.org/",
        ),
        tool(
            "umlet",
            "UMLet",
            DIA,
            "uml_architecture",
            "Fast UML sketching tool with a headless batch converter for `.uxf` → SVG/PDF/PNG/EPS.",
            "UMLet is a lightweight UML tool using a text-property panel per element; its agent-usable surface is the batch converter, which turns `.uxf` diagram files into SVG, PDF, PNG, or EPS from the command line, so committed UMLet diagrams can be regenerated in a build.",
            "Reach for UMLet's converter when a project stores `.uxf` UML diagrams and you need to export them headlessly; for text-first UML prefer PlantUML, and reserve UMLet for diagrams already authored in its format.",
            "Input: a `.uxf` (UMLet XML) file. Output: `-action=convert -format <svg|pdf|png|eps> -filename in.uxf` (writes alongside the source).",
            "`umlet -action=convert -format svg -filename diagram.uxf`; `-output out.svg` to redirect; runs on the JVM (headless conversion may need an X/virtual display for some versions).",
            "Very fast diagram authoring; simple `.uxf` text-XML format; batch export to vector and raster; no cloud dependency.",
            "Primarily a GUI tool; `.uxf` is UMLet-specific (less portable than PlantUML text); JVM/SWT may require a display for conversion in some environments.",
            &["plantuml", "drawio", "mermaid-cli"],
            "pacman: umlet (/usr/bin/umlet, v15.1; OpenJDK 26)",
            "https://www.umlet.com/",
        ),
        tool(
            "dbml-renderer",
            "dbml-renderer",
            DIA,
            "uml_architecture",
            "Database schema (ER) diagrams from DBML — tables, columns, keys, and relationships rendered to SVG/PNG.",
            "dbml-renderer compiles DBML (Database Markup Language) — a concise text format for tables, columns, types, indexes, and `Ref` relationships — into an entity-relationship diagram (SVG/PNG/PDF), giving a version-controlled, diffable picture of a database schema.",
            "Reach for dbml-renderer to document or review a relational schema: write/maintain the schema in DBML (or export it from a DB via dbml tooling) and generate an ER diagram in CI, keeping the picture in lockstep with migrations.",
            "Input: a `.dbml` file. Output: `-o out.svg`/`.png`/`.pdf` (format from extension).",
            "`dbml-renderer -i schema.dbml -o schema.svg`; `-o schema.png` for raster; runs on Node from the workspace `node_modules/.bin`.",
            "Purpose-built for ER/schema diagrams; clean output; DBML is readable and tool-friendly; pairs with the broader DBML ecosystem (db→dbml exporters).",
            "Schema/ER diagrams only; DBML must be authored or exported; installed repo-locally (invoke via the workspace path or `npx`).",
            &["plantuml", "graphviz", "d2"],
            "npm (workspace node_modules): /home/dylon/Workspace/f1r3fly.io/node_modules/.bin/dbml-renderer (v1.0.31)",
            "https://github.com/softwaretechnik-berlin/dbml-renderer",
        ),
        // ---- diagram_language ----
        tool(
            "metapost",
            "MetaPost",
            DIA,
            "diagram_language",
            "Programmable PostScript/SVG figure language — precise technical diagrams with solved linear constraints.",
            "MetaPost is a Metafont-derived language that produces resolution-independent figures (EPS/SVG/MPS) by *describing* points, paths, and pens and letting it solve linear equations for positions — so you specify geometric relationships (\"a is the midpoint of b and c\") and it computes coordinates exactly. Output integrates natively into TeX with real typeset labels.",
            "Reach for MetaPost when a scientific/technical figure needs mathematical precision and TeX-quality labels — commutative diagrams, geometric constructions, parametric curves, plots with exact tangents — and you want the source to be a tiny, reproducible program.",
            "Input: a `.mp` source file. Output: one EPS per `beginfig(n)…endfig` (`figs.1`, `figs.2`, …) or SVG with `-s 'outputformat=\"svg\"'`; `mptopdf` for PDF.",
            "`mpost figures.mp` emits figures.1, figures.2 (EPS); `mpost -s 'outputformat=\"svg\"' fig.mp`; `mptopdf fig.mp` for PDF; `\\input` the EPS into LaTeX/ConTeXt for typeset labels.",
            "Exact constraint-solved geometry; tiny reproducible sources; native TeX label typesetting; resolution-independent; part of TeX Live.",
            "Steep, idiosyncratic language; per-figure EPS output workflow; weaker for freeform/illustrative art (use Inkscape/Asymptote for 3D); slow to learn.",
            &["asymptote", "tikz", "pic"],
            "TeX Live 2026: /usr/bin/mpost (MetaPost v3.00; + mptopdf)",
            "https://www.tug.org/metapost.html",
        ),
        tool(
            "tikz",
            "TikZ / PGF",
            DIA,
            "diagram_language",
            "The LaTeX vector-graphics language — publication-grade diagrams with native math typesetting.",
            "TikZ (atop the PGF engine) draws vector graphics directly inside LaTeX: nodes, paths, trees, automata, circuits (circuitikz), plots (pgfplots), commutative diagrams, and more, with full access to LaTeX math and fonts so labels are typeset, not pasted. It compiles to PDF/SVG via the normal LaTeX toolchain.",
            "Reach for TikZ when a figure must match a paper's typography exactly and embed real math — state machines, trees, geometric figures, annotated plots — accepting a steeper authoring cost for the best-looking, fully-typeset result.",
            "Input: LaTeX with `\\usepackage{tikz}` + `tikzpicture` environments. Output: PDF (`pdflatex`/`lualatex`); SVG via `dvisvgm` or the `standalone` class + crop.",
            "`\\usepackage{tikz}` then `\\begin{tikzpicture}…\\end{tikzpicture}`; compile `lualatex doc.tex`; use the `standalone` document class for a cropped single-figure PDF; `dvisvgm` to get SVG; libraries: `arrows.meta`, `automata`, `positioning`, `calc`.",
            "Unmatched typographic/math integration; vast library ecosystem; publication standard in academia; one toolchain for figures + document.",
            "Steepest learning curve here; slow compile for complex pictures; needs a full LaTeX install; not interactive — edit/compile loop.",
            &["pgfplots", "circuitikz", "metapost", "asymptote", "dot2tex"],
            "TeX Live 2026: tikz.sty (kpsewhich /usr/share/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty); compile via pdflatex/lualatex",
            "https://tikz.dev/",
        ),
        tool(
            "pic",
            "GNU pic",
            DIA,
            "diagram_language",
            "The classic troff PIC language — box-and-arrow diagrams from a terse, readable description.",
            "GNU pic compiles the PIC language (boxes, circles, arrows, lines positioned relatively — \"box; arrow; circle\") into troff drawing commands, or to other backends, for line diagrams embedded in groff/man pages and documents. Its declarative relative-positioning model makes simple block diagrams quick to write and easy to read as source.",
            "Reach for pic for lightweight block-and-arrow or flow diagrams in groff/troff documents and man pages, or when you want a minimal, decades-stable text language for simple schematic figures; for Markdown/SVG-first work prefer its modern descendant Pikchr.",
            "Input: PIC source (between `.PS`/`.PE`, or stdin). Output: troff (`groff -p`), TeX (`-t`), or images via `pic2plot`.",
            "`pic diagram.pic | groff -p -Tps > out.ps`; `groff -p -Tpdf doc.ms`; `pic2plot -Tsvg diagram.pic > out.svg` (via plotutils) for direct SVG; relative placement: `box \"A\"; arrow; box \"B\"`.",
            "Minimal, stable, readable language; ideal for groff/man-page figures; relative positioning avoids coordinate math; ubiquitous.",
            "Troff-centric output workflow; dated for web/SVG (Pikchr modernizes it); limited to line/box diagrams; styling is basic.",
            &["pikchr", "graphviz", "metapost"],
            "groff: /usr/bin/pic (GNU pic v1.24.1)",
            "https://www.gnu.org/software/groff/",
        ),
        tool(
            "asymptote",
            "Asymptote",
            DIA,
            "diagram_language",
            "Vector graphics *programming* language for technical 2D/3D figures with TeX-quality labels.",
            "Asymptote is a C++-like language for descriptive vector graphics: it offers exact 2D/3D geometry, a deferred-drawing model, a rich standard library (graphs, geometry, 3D surfaces, contour, tube), and LaTeX-typeset labels, exporting EPS/PDF/SVG/PNG and interactive 3D PRC/PDF. It is effectively a programmable successor to MetaPost with 3D.",
            "Reach for Asymptote for mathematically precise scientific figures — 3D surfaces, vector fields, geometric constructions, function graphs — where you want programmatic control plus publication-quality typeset labels in one reproducible source.",
            "Input: an `.asy` source file. Output: `-f pdf|eps|svg|png -o name fig.asy` (PDF default; 3D → PRC/PDF).",
            "`asy -f svg -o figure figure.asy` (writes figure.svg); `asy -f pdf fig.asy`; `import graph; import three;` for plotting/3D; embed in LaTeX via the `asymptote` package; `-V` to preview.",
            "Programmable 2D *and* 3D; exact geometry; TeX-quality labels; strong scientific/math libraries; multiple high-quality output formats.",
            "Programming-language learning curve; compile-oriented (no live canvas); 3D output best viewed as PRC/PDF; overkill for simple box diagrams.",
            &["metapost", "tikz", "gnuplot", "matplotlib"],
            "pacman: asymptote (/usr/bin/asy, v3.12)",
            "https://asymptote.sourceforge.io/",
        ),
        tool(
            "pikchr",
            "Pikchr",
            DIA,
            "diagram_language",
            "PIC-derived diagram language that emits self-contained SVG — designed to embed in Markdown.",
            "Pikchr (by the SQLite/Fossil author) modernizes PIC: the same readable relative-positioning model (\"box; arrow; box\") but with a safe, dependency-free C implementation that outputs self-contained SVG and is meant to be embedded in Markdown/Fossil/technical docs. It adds modern niceties (colors, classes, layered objects) while staying tiny and deterministic.",
            "Reach for Pikchr to embed box-and-arrow, flow, or simple block diagrams directly in Markdown documentation with no external renderer and no binary assets — the SVG is generated inline from readable text.",
            "Input: Pikchr source (file or stdin; or a ```pikchr fenced block). Output: a self-contained `.svg` on stdout.",
            "`pikchr diagram.pikchr > diagram.svg`; `pikchr --svg-only in.pikchr`; embed as a ```pikchr fenced block in Fossil/Markdown; relative layout like PIC: `box \"start\"; arrow; box \"end\"`.",
            "Self-contained SVG, zero dependencies; safe/deterministic; modern PIC syntax; ideal for docs-as-code and Markdown embedding.",
            "Line/box diagrams only (no UML/plots); smaller ecosystem than Graphviz/Mermaid; manual relative layout (no auto-layout for big graphs).",
            &["pic", "graphviz", "d2", "svgbob"],
            "/usr/bin/pikchr (v1.0)",
            "https://pikchr.org/",
        ),
    ]
}
