//! Diagramming tools that render and convert: ASCII-art → image, diagram/vector
//! format conversion (SVG/PDF/PNG/EPS, .fig/.odg, DVI), circuit/EDA schematics,
//! and protocol/packet/timing diagrams. Probe-grounded for this machine.

use super::{DIA, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- ascii_diagram ----
        tool(
            "ditaa",
            "ditaa",
            DIA,
            "ascii_diagram",
            "Turns ASCII-art boxes/lines drawn in a text file into a polished raster/vector diagram.",
            "ditaa (DIagrams Through Ascii Art) parses a monospaced text drawing — `+`, `-`, `|`, `/` corners, `--->` arrows — and renders rounded, shaded, colored boxes and connectors to PNG (or SVG), recognizing color tags (`cRED`), shape hints, and dashed lines. The diagram lives as readable ASCII in the source and becomes a clean picture on render.",
            "Reach for ditaa when a diagram is naturally sketched as ASCII in a README/code comment and you want a presentable rendered version without learning a DSL — it is the classic \"ASCII boxes → nice PNG\" converter, also available as a PlantUML/Asciidoctor block.",
            "Input: a `.txt`/`.ditaa` ASCII-art file. Output: a PNG (default) or SVG with `--svg`.",
            "`ditaa diagram.txt diagram.png`; `ditaa --svg diagram.txt diagram.svg`; `-E` disables separation of close shapes; `-r` rounds corners; color via `cBLU`/`cRED` tags inside boxes.",
            "Source stays human-readable ASCII; attractive shaded output; color/shape tags; integrates with PlantUML/Asciidoctor.",
            "You must hand-draw the ASCII (no auto-layout); raster-first (SVG is newer/less polished); JVM startup cost; not for large/complex graphs.",
            &["svgbob", "pikchr", "graphviz"],
            "pacman: ditaa (/usr/bin/ditaa, v0.11.0; runs on OpenJDK 26)",
            "https://ditaa.sourceforge.net/",
        ),
        tool(
            "svgbob",
            "Svgbob",
            DIA,
            "ascii_diagram",
            "Converts ASCII/Unicode line-art into clean, scalable SVG — diagrams that stay editable as text.",
            "Svgbob reads a monospaced text drawing and emits crisp SVG, interpreting `-`, `|`, `+`, `/`, `\\`, arrowheads, and Unicode box-drawing characters as smooth lines, boxes, arrows, and curves. Unlike ditaa it targets vector output, so the result scales and the source remains a plain-text diagram beside the code.",
            "Reach for Svgbob to render ASCII diagrams embedded in source/Markdown into resolution-independent SVG — ideal for docs-as-code where the diagram should be both readable in the raw file and sharp when published.",
            "Input: an ASCII/Unicode text drawing (file or stdin). Output: SVG on stdout or `-o out.svg`.",
            "`svgbob_cli diagram.txt -o diagram.svg`; `svgbob_cli < in.txt > out.svg`; tune with `--scale`/`--font-size`; recognizes Unicode box-drawing for finer shapes.",
            "Vector (scalable) output; source stays plain-text/diffable; handles Unicode box-drawing; tiny, fast Rust binary; great for Markdown.",
            "Hand-drawn ASCII only (no auto-layout); best for line/box art, not rich UML/plots; styling is limited compared to a full vector editor.",
            &["ditaa", "pikchr", "graphviz"],
            "cargo: ~/.cargo/bin/svgbob_cli (v0.7.6)",
            "https://github.com/ivanceras/svgbob",
        ),
        // ---- diagram_conversion ----
        tool(
            "imagemagick",
            "ImageMagick",
            DIA,
            "diagram_conversion",
            "Swiss-army raster/vector converter — rasterize SVG/PDF, montage panels, annotate, and batch-process diagrams.",
            "ImageMagick (`magick`) reads and writes 200+ formats and is the general-purpose glue around a diagram pipeline: rasterize an SVG/PDF diagram to PNG at a chosen density, assemble multiple diagrams into a contact sheet (`montage`), trim/pad/annotate exports, and batch-convert whole directories.",
            "Reach for ImageMagick to post-process diagram outputs — convert a renderer's SVG/PDF to a sized PNG, stitch several diagrams into one image, add labels/borders, or normalize a batch of exports for publishing.",
            "Input: image/vector files (SVG/PDF/PNG/EPS/…). Output: any target format via `magick in out` or `convert`/`montage`/`composite`.",
            "`magick -density 300 diagram.pdf diagram.png` (high-DPI rasterize); `magick in.svg -resize 1200x out.png`; `magick montage a.png b.png -tile 2x1 sheet.png`; `magick in.png -bordercolor white -border 20 out.png`.",
            "Reads/writes nearly everything; scriptable batch pipelines; montage/annotate/trim; ubiquitous; density control for crisp vector→raster.",
            "Rasterizes vectors via a delegate (librsvg/Ghostscript) — for faithful SVG prefer rsvg-convert directly; complex CLI; not a diagram *authoring* tool.",
            &["graphicsmagick", "rsvg-convert", "inkscape"],
            "pacman: imagemagick (/usr/bin/magick, v7.1.2-25 Q16-HDRI)",
            "https://imagemagick.org/",
        ),
        tool(
            "graphicsmagick",
            "GraphicsMagick",
            DIA,
            "diagram_conversion",
            "Lean, stable ImageMagick fork — fast batch raster conversion with a smaller, consistent CLI.",
            "GraphicsMagick (`gm`) is a performance- and stability-focused fork of ImageMagick offering the same core convert/composite/montage operations through a single `gm <command>` entry point. It is favored for high-throughput batch conversion and for environments that want a smaller, API-stable dependency.",
            "Reach for GraphicsMagick when batch-converting or compositing many diagram images and you want lower overhead and a more stable interface than ImageMagick — e.g. a build step that rasterizes hundreds of SVG/PDF figures.",
            "Input: image files. Output: via `gm convert in out`, `gm montage`, `gm composite`.",
            "`gm convert -density 300 diagram.pdf diagram.png`; `gm convert in.svg -resize 1000x out.png`; `gm montage *.png -tile 3x sheet.png`; `gm batch` for scripted runs.",
            "Faster/leaner than ImageMagick for batch; stable CLI/API; single `gm` binary; good throughput.",
            "Smaller format/feature set than ImageMagick; SVG fidelity depends on delegates (prefer rsvg-convert for SVG); not an authoring tool.",
            &["imagemagick", "rsvg-convert"],
            "pacman: graphicsmagick (/usr/bin/gm, v1.3.47 Q16)",
            "http://www.graphicsmagick.org/",
        ),
        tool(
            "rsvg-convert",
            "rsvg-convert (librsvg)",
            DIA,
            "diagram_conversion",
            "Faithful SVG → PNG/PDF/PS renderer built on librsvg + cairo — the accurate way to rasterize diagrams.",
            "rsvg-convert renders SVG (the output of most diagram tools) to PNG, PDF, or PostScript using GNOME's librsvg + cairo + pango stack, giving high-fidelity rasterization with correct CSS/text/gradient handling. It is the preferred SVG converter when ImageMagick's delegate rendering is too lossy.",
            "Reach for rsvg-convert to turn a Graphviz/Mermaid/d2/PlantUML SVG into a precisely-sized PNG or a vector PDF for publishing — it honors fonts, gradients, and CSS more faithfully than a general image tool.",
            "Input: an `.svg` file. Output: `-f png|pdf|ps -o out.ext` (with `-w`/`-h`/`--zoom` sizing).",
            "`rsvg-convert -f pdf -o diagram.pdf diagram.svg`; `rsvg-convert -w 1600 diagram.svg -o diagram.png`; `--zoom 2 --background-color white`; `-f ps` for PostScript.",
            "High-fidelity SVG rendering (cairo/pango); precise sizing; vector PDF/PS output; fast and dependency-light vs a full browser.",
            "SVG input only (not a general converter); no diagram authoring; very new SVG2/CSS features may render imperfectly.",
            &["imagemagick", "inkscape", "dvisvgm", "graphicsmagick"],
            "pacman: librsvg (/usr/bin/rsvg-convert, v2.62.3; cairo 1.18/pango 1.57)",
            "https://gitlab.gnome.org/GNOME/librsvg",
        ),
        tool(
            "dvisvgm",
            "dvisvgm",
            DIA,
            "diagram_conversion",
            "DVI/EPS/PDF → SVG converter — the bridge that turns TikZ/MetaPost/LaTeX figures into web SVG.",
            "dvisvgm converts DVI (and EPS/PDF) into highly-optimized SVG, faithfully reproducing TeX output including fonts (as paths or WOFF), specials, PostScript graphics, and embedded color. It is the standard last step for getting a TikZ, PGFplots, circuitikz, or MetaPost figure out of the LaTeX toolchain and onto the web.",
            "Reach for dvisvgm whenever a diagram authored in TikZ/PGFplots/circuitikz/MetaPost needs to become a standalone SVG — compile the figure to DVI/PDF, then dvisvgm it for a crisp, font-correct vector asset.",
            "Input: a `.dvi`/`.pdf`/`.eps` (from `latex`/`lualatex --output-format=dvi`/`mpost`). Output: `-o out.svg` (optionally `-s` to stdout).",
            "`dvisvgm figure.dvi -o figure.svg`; `dvisvgm --pdf figure.pdf -o figure.svg`; `--font-format=woff --exact` for web-ready fonts; `latex standalone.tex && dvisvgm standalone.dvi`.",
            "Faithful TeX→SVG with correct fonts/specials; handles PostScript/PDF specials; font embedding options; the canonical TikZ/MetaPost → SVG path.",
            "Expects TeX-produced DVI/PDF/EPS input; PostScript specials need Ghostscript; not a general image converter.",
            &["rsvg-convert", "tikz", "metapost", "pgfplots"],
            "TeX Live 2026: /usr/bin/dvisvgm (v3.6)",
            "https://dvisvgm.de/",
        ),
        tool(
            "dot2tex",
            "dot2tex",
            DIA,
            "diagram_conversion",
            "Graphviz DOT → TikZ/PGF/PSTricks — keeps Graphviz layout but renders with LaTeX typography.",
            "dot2tex takes a Graphviz graph (or runs the layout itself) and emits LaTeX/TikZ (or PGF/PSTricks) code, so you get Graphviz's automatic graph layout *plus* TeX-quality labels, math in node text, and figures that match your document's fonts. It can also just annotate a DOT file with computed coordinates.",
            "Reach for dot2tex when a graph is easiest to define/layout in DOT but must look native in a LaTeX paper — automatic Graphviz layout, then TikZ rendering with real math labels and consistent typography.",
            "Input: a `.dot` file (or DOT on stdin). Output: LaTeX/TikZ source (stdout or `-o out.tex`).",
            "`dot2tex -ftikz graph.dot > graph.tex`; `dot -Txdot graph.dot | dot2tex -tmath > graph.tex`; `--figonly` for an includable figure; then `\\input{graph}` and compile with TikZ.",
            "Marries Graphviz auto-layout with TikZ typography; math in labels; multiple backends (TikZ/PGF/PSTricks); great for papers.",
            "Output still needs a LaTeX/TikZ compile; large graphs produce heavy TikZ; depends on Graphviz for layout.",
            &["graphviz", "tikz", "dvisvgm"],
            "/usr/bin/dot2tex (v2.12.0)",
            "https://dot2tex.readthedocs.io/",
        ),
        tool(
            "inkscape",
            "Inkscape (CLI)",
            DIA,
            "diagram_conversion",
            "Pro SVG editor whose headless CLI exports, converts, and transforms diagrams without the GUI.",
            "Inkscape is a full SVG editor, but its command line is a capable headless engine: export SVG to PNG/PDF/PS/EPS at chosen DPI/area, convert between vector formats, query object geometry, and run scripted `--actions` (select, transform, text-to-path, vacuum) — useful for finishing or converting diagram assets in a pipeline.",
            "Reach for Inkscape's CLI to export a diagram SVG to PDF/PNG with precise control (DPI, page vs drawing area, background), flatten text to paths for portability, or batch-convert vector files — when rsvg-convert's simpler model isn't enough.",
            "Input: an `.svg`/vector file. Output: `--export-type=png|pdf|ps|eps --export-filename=out` (+ `--export-dpi`, `--export-area-drawing`).",
            "`inkscape in.svg --export-type=pdf --export-filename=out.pdf`; `inkscape in.svg --export-type=png --export-dpi=300 --export-area-drawing -o out.png`; `inkscape in.svg --actions='select-all;object-to-path;export-do'`; `--query-width in.svg`.",
            "Powerful headless export/convert/transform; precise DPI/area control; text-to-path; `--actions` scripting; reads many vector formats.",
            "Heavier than rsvg-convert for plain SVG→PNG; primarily a GUI app; startup cost; overkill when you only need a simple conversion.",
            &[
                "rsvg-convert",
                "imagemagick",
                "calligraconverter",
                "fig2dev",
            ],
            "pacman: inkscape (/usr/bin/inkscape, v1.4.4)",
            "https://inkscape.org/",
        ),
        tool(
            "fig2dev",
            "fig2dev (Fig → many formats)",
            DIA,
            "diagram_conversion",
            "Headless converter for Xfig `.fig` drawings — exports SVG/PDF/PNG/EPS and even TikZ/PSTricks.",
            "fig2dev (the Transfig toolset) is the command-line exporter for the Fig format: it converts a `.fig` vector drawing into 30+ targets including SVG, PDF, EPS, PNG, and crucially LaTeX backends (tikz, pstricks, pict2e, pstex) — so Xfig-authored figures can be regenerated headlessly and even embedded in LaTeX with typeset text.",
            "Reach for fig2dev when a project stores `.fig` diagrams (Xfig is the GUI; fig2dev is the agent path) and you need to export them in a build, or to convert a Fig drawing into TikZ/PSTricks for a LaTeX document.",
            "Input: a `.fig` file. Output: `-L <lang> in.fig out.ext` (lang = svg/pdf/png/eps/tikz/pstricks/pict2e/…).",
            "`fig2dev -L svg diagram.fig diagram.svg`; `fig2dev -L pdf in.fig out.pdf`; `fig2dev -L tikz in.fig out.tex` for LaTeX with typeset labels; `fig2dev -L png -m 2 in.fig out.png` (2× scale).",
            "Many output targets incl. LaTeX/TikZ; faithful Fig rendering; pure CLI (no GUI needed); stable and scriptable.",
            "Only consumes the Fig format; `.fig` is typically authored in the Xfig GUI; dated format/ecosystem.",
            &["inkscape", "rsvg-convert", "imagemagick"],
            "/usr/bin/fig2dev (v3.2.9; Transfig/fig2dev)",
            "https://sourceforge.net/projects/mcj/",
        ),
        tool(
            "calligraconverter",
            "calligraconverter (Calligra/Karbon)",
            DIA,
            "diagram_conversion",
            "Headless converter for Calligra/Karbon and ODF graphics — `.odg`/Karbon → SVG/PDF/PNG.",
            "calligraconverter is the command-line document/graphics converter shipped with Calligra: it turns Karbon vector drawings and OpenDocument graphics (`.odg`) — and other Calligra-supported formats — into SVG, PDF, PNG, and more, providing the agent-usable path for diagrams authored in Karbon (the GUI vector app).",
            "Reach for calligraconverter when diagrams live in `.odg`/Karbon format and must be exported headlessly to SVG/PDF/PNG in a pipeline — Karbon itself is GUI-only, so the converter is the automation surface.",
            "Input: an `.odg`/Karbon/Calligra document. Output: `calligraconverter in.odg out.svg` (target inferred from extension; PNG export takes geometry flags).",
            "`calligraconverter diagram.odg diagram.svg`; `calligraconverter in.odg out.pdf`; `calligraconverter --batch in.odg out.png`; ODF graphics in, SVG/PDF/PNG out.",
            "Bridges the ODF/Karbon graphics world into standard vector/raster formats; batch-capable; reuses Calligra's import filters.",
            "Niche (ODF/Karbon-centric); pulls in Calligra/Qt; export options are limited vs Inkscape; may need a display for some filters.",
            &["inkscape", "rsvg-convert", "imagemagick"],
            "pacman: calligra (/usr/bin/calligraconverter, v26.04.2)",
            "https://calligra.org/",
        ),
        // ---- circuit_diagram ----
        tool(
            "circuitikz",
            "CircuiTikZ",
            DIA,
            "circuit_diagram",
            "LaTeX/TikZ package for publication-quality electronic & electrical circuit schematics.",
            "CircuiTikZ extends TikZ with a circuit-drawing language: `to[R]`, `to[C]`, `to[L]`, sources, transistors, logic gates, and labels positioned on a coordinate grid, producing clean, consistent schematics with full LaTeX math/typography for component values. It is the academic standard for circuits in papers and books.",
            "Reach for CircuiTikZ to typeset circuit schematics that must match a document's typography and carry precise math labels (impedances, transfer functions) — analog, digital, or power circuits authored as reproducible text.",
            "Input: LaTeX with `\\usepackage{circuitikz}` + a `circuitikz` environment. Output: PDF (LaTeX), or SVG via dvisvgm.",
            "`\\begin{circuitikz}\\draw (0,0) to[R=$R_1$] (2,0) to[C=$C_1$] (2,-2);\\end{circuitikz}`; compile `lualatex`; `standalone` class + `dvisvgm` for SVG; bipoles/monopoles/transistors libraries.",
            "Publication-grade, math-aware schematics; consistent component style; text source diffs cleanly; one toolchain with the document.",
            "LaTeX learning curve; manual coordinate placement (no schematic capture/auto-route); not a netlist/simulation tool (use KiCad for EDA).",
            &["tikz", "kicad", "xcircuit", "dvisvgm"],
            "TeX Live 2026: circuitikz.sty (kpsewhich /usr/share/texmf-dist/tex/latex/circuitikz/circuitikz.sty)",
            "https://www.ctan.org/pkg/circuitikz",
        ),
        tool(
            "kicad",
            "KiCad (kicad-cli)",
            DIA,
            "circuit_diagram",
            "Full EDA suite with a headless CLI — export schematics/PCBs to SVG/PDF/Gerber and run ERC/DRC.",
            "KiCad is a complete electronics design automation suite; `kicad-cli` is its scriptable, GUI-free front end that exports schematics (`.kicad_sch`) and boards (`.kicad_pcb`) to SVG/PDF/PNG, generates Gerber/drill/STEP manufacturing files, produces BOMs/netlists, and runs Electrical-Rule-Check (ERC) and Design-Rule-Check (DRC) — making real EDA diagrams part of CI.",
            "Reach for kicad-cli to render a project's schematic or PCB to SVG/PDF for docs/review, regenerate fabrication outputs, or gate a design in CI with ERC/DRC — the headless path into a genuine EDA toolchain, not just a drawing.",
            "Input: `.kicad_sch`/`.kicad_pcb` files. Output: `kicad-cli sch export <svg|pdf>`, `kicad-cli pcb export <svg|gerbers|step>`, `kicad-cli sch erc`, `kicad-cli pcb drc`.",
            "`kicad-cli sch export svg --output out.svg board.kicad_sch`; `kicad-cli pcb export pdf board.kicad_pcb`; `kicad-cli pcb export gerbers -o gbr/ board.kicad_pcb`; `kicad-cli sch erc board.kicad_sch`.",
            "Real EDA (schematic + PCB + manufacturing + rule checks); fully headless CLI; CI-friendly fabrication/diagram exports; free/open.",
            "Heavyweight (full EDA install); consumes KiCad-native files (not a quick general diagram tool); schematic authoring is still GUI-centric.",
            &["circuitikz", "xcircuit"],
            "pacman: kicad (/usr/bin/kicad-cli, v10.0.3)",
            "https://www.kicad.org/",
        ),
        tool(
            "xcircuit",
            "XCircuit",
            DIA,
            "circuit_diagram",
            "Schematic-capture & circuit drawing tool that outputs publication-quality PostScript; Tcl-scriptable batch.",
            "XCircuit draws electronic circuit schematics and general technical figures and outputs encapsulated PostScript (and SPICE netlists). It is primarily interactive, but its embedded Tcl interpreter allows batch/scripted generation and export, and its native output is clean, LaTeX-friendly PostScript.",
            "Reach for XCircuit when you want hand-drawn schematic capture with PostScript output for inclusion in papers, or scripted figure generation via its Tcl interface; for headless EDA pipelines prefer kicad-cli, and for pure-LaTeX circuits prefer CircuiTikZ.",
            "Input: XCircuit `.ps`/library files or Tcl scripts. Output: encapsulated PostScript (EPS); SPICE netlists; raster via a converter.",
            "Interactive: `xcircuit schematic.ps`; scripted: drive the built-in Tcl interpreter to load/export EPS in batch; convert the EPS onward with rsvg-convert/ImageMagick/Inkscape.",
            "PostScript output integrates with LaTeX; schematic capture + general drawing; Tcl scripting; netlist export.",
            "GUI-first (interactive capture); batch/headless use is awkward (Tcl-only); EPS-centric workflow; smaller community than KiCad.",
            &["kicad", "circuitikz"],
            "pacman: xcircuit (/usr/bin/xcircuit, v3.10.30)",
            "http://opencircuitdesign.com/xcircuit/",
        ),
        // ---- protocol_data_diagram ----
        tool(
            "bytefield-svg",
            "bytefield-svg",
            DIA,
            "protocol_data_diagram",
            "Generates packet / byte-field layout diagrams from a concise DSL — the standard for protocol structure.",
            "bytefield-svg renders network-packet and data-structure layout diagrams — the grid-of-bytes pictures used in RFCs — from a compact EDN/Clojure-flavored DSL describing rows, fields, bit/byte widths, and labels, emitting clean SVG. It is purpose-built for showing how a binary protocol or on-disk structure is laid out bit-by-bit.",
            "Reach for bytefield-svg to document a wire protocol, file-format header, or binary message layout — the canonical \"boxes of bytes with bit offsets\" diagram, generated from text so it stays accurate as the format evolves (directly relevant to security/protocol analysis).",
            "Input: a bytefield DSL source (`.edn`/stdin). Output: SVG (`-o out.svg`).",
            "`bytefield-svg -s packet.edn -o packet.svg`; pipe the DSL on stdin: `bytefield-svg < header.edn > header.svg`; define rows with `(draw-box ...)`/`(draw-bytes ...)` and bit-width headers; runs on Node from the workspace `node_modules/.bin`.",
            "Purpose-built for byte/bit-field layouts; RFC-style output; text source stays in sync with the spec; clean SVG.",
            "Single diagram family (packet/struct layouts); EDN DSL has a learning curve; installed repo-locally (invoke via the workspace path or `npx`).",
            &["wavedrom-cli", "mscgenjs", "tikz"],
            "npm (workspace node_modules): /home/dylon/Workspace/f1r3fly.io/node_modules/.bin/bytefield-svg (v1.11.0)",
            "https://bytefield-svg.deepsymmetry.org/",
        ),
        tool(
            "wavedrom-cli",
            "WaveDrom CLI",
            DIA,
            "protocol_data_diagram",
            "Digital timing-diagram & register-layout renderer from WaveJSON — clocks, signals, buses, gaps.",
            "WaveDrom renders digital timing diagrams and bit-field/register layouts from WaveJSON: it draws clock edges, signal waveforms, multi-bit buses, gaps, and arrows for a hardware-style timing picture, and also produces register-description diagrams — the standard tool for documenting digital interfaces and protocols.",
            "Reach for WaveDrom to document a synchronous protocol's timing (SPI/I²C/bus transactions), a state sequence over clock cycles, or a register's bit layout — authored as WaveJSON so the diagram regenerates with the spec.",
            "Input: a WaveJSON file. Output: `-s out.svg` (SVG) or `-p` PNG.",
            "`wavedrom-cli -i wave.json -s wave.svg`; WaveJSON `{signal:[{name:'clk',wave:'p...'},{name:'data',wave:'x.34.x',data:['A','B']}]}`; `reg:[...]` for register layouts; runs on Node from the workspace `node_modules/.bin`.",
            "Standard for digital timing diagrams; register/bit-field layouts too; compact WaveJSON; widely used in hardware docs/RFCs.",
            "Hardware-timing/register niche; WaveJSON only; installed repo-locally (invoke via the workspace path or `npx`).",
            &["bytefield-svg", "mscgenjs", "gnuplot"],
            "npm (workspace node_modules): /home/dylon/Workspace/f1r3fly.io/node_modules/.bin/wavedrom-cli (v3.2.0)",
            "https://wavedrom.com/",
        ),
    ]
}
