//! Diagramming tools for scientific plotting & charting: data/function plots,
//! statistical and declarative charts, and the LaTeX plotting stack. Probe-grounded
//! for this machine (gnuplot 6, TeX Live 2026, pacman python-* libs on Python 3.14,
//! R 4.6, workspace npm vega-cli).

use super::{DIA, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- scientific_plotting ----
        tool(
            "gnuplot",
            "gnuplot",
            DIA,
            "scientific_plotting",
            "The workhorse scientific plotter — functions and data to SVG/PDF/PNG from a tiny script.",
            "gnuplot is a command-driven plotting program for 2D/3D scientific graphs: line/point/bar/heatmap/contour/vector plots of data files and mathematical functions, with fine control over axes, scales (log), keys, fits, and dozens of output terminals (svg, pngcairo, pdfcairo, epslatex, postscript). It scripts cleanly and is the default for quick, reproducible scientific figures.",
            "Reach for gnuplot to plot a data file or function to a publishable figure from the command line — benchmark results, experimental curves, 3D surfaces — especially in a Makefile/CI where a small `.gp` script regenerates the plot deterministically.",
            "Input: data files and/or function expressions + commands (a `.gp` script, `-e`, or stdin). Output: a file via `set terminal`/`set output` (svg/pdf/png/eps).",
            "`gnuplot -e \"set term svg; set output 'p.svg'; plot 'data.dat' u 1:2 w lines\"`; `gnuplot plot.gp`; `set terminal pdfcairo` / `epslatex` for papers; `set logscale y`; `fit f(x) 'd' via a,b` for curve fitting.",
            "Ubiquitous and scriptable; huge terminal/format support; function + data plotting; curve fitting; tiny reproducible sources; great for CI.",
            "Dated default styling (tunable); imperative DSL has a learning curve; not interactive/exploratory (use matplotlib/plotly); 3D is functional but basic.",
            &["matplotlib", "veusz", "plotutils", "pgfplots"],
            "pacman: gnuplot (/usr/bin/gnuplot, v6.0 patchlevel 4)",
            "http://www.gnuplot.info/",
        ),
        tool(
            "plotutils",
            "GNU plotutils",
            DIA,
            "scientific_plotting",
            "Classic Unix plotting filters — `graph` plots X-Y data to SVG/PS; plus `spline`/`ode`/`plot`.",
            "GNU plotutils is a suite of small, composable plotting/graphics utilities: `graph` reads X-Y datasets and emits a 2D plot (SVG, PS, PNG, X11), `spline` interpolates/smooths a dataset, `ode` integrates ordinary differential equations, and `plot` translates GNU metafile graphics. `pic2plot` (same suite) also renders PIC to SVG/PNG.",
            "Reach for plotutils when you want a tiny Unix-pipeline plot — feed columns of numbers to `graph -T svg` and get a chart with no script — or to spline-smooth/ODE-integrate data on the command line before plotting it.",
            "Input: whitespace-separated X-Y data (stdin/files), or PIC for `pic2plot`. Output: `-T svg|ps|png|X` to stdout.",
            "`graph -T svg -C data.dat > plot.svg`; `graph -T ps < data | ...`; `spline data | graph -T svg > smooth.svg`; `ode < system.ode | graph -T svg`; `pic2plot -T svg fig.pic > fig.svg`.",
            "Pure Unix-pipeline composability; no scripting needed for a quick plot; bundles spline/ODE/PIC utilities; lightweight and stable.",
            "Spartan styling and features vs gnuplot/matplotlib; small/aging toolset; basic 2D only.",
            &["gnuplot", "matplotlib", "pic"],
            "pacman: plotutils (/usr/bin/graph + plot/spline/ode/pic2plot, v2.6)",
            "https://www.gnu.org/software/plotutils/",
        ),
        tool(
            "matplotlib",
            "Matplotlib",
            DIA,
            "scientific_plotting",
            "Python's foundational plotting library — scriptable, headless, publication-grade figures in any format.",
            "Matplotlib is the de-facto Python 2D (and basic 3D) plotting library: line/scatter/bar/hist/heatmap/contour/quiver and more, with total control over every artist, and a headless `Agg` backend that writes SVG/PDF/PNG/EPS without a display. It underpins seaborn and pandas `.plot()`, making it the base layer of the scientific-Python plotting stack.",
            "Reach for Matplotlib when a plot is generated inside a Python script/notebook or needs pixel-level customization and a headless render in CI — it produces anything from a quick diagnostic to a camera-ready multi-panel figure.",
            "Input: Python arrays/DataFrames via the `pyplot` API. Output: `savefig('out.svg'|'.pdf'|'.png', dpi=...)` (use the `Agg` backend headless).",
            "`python -c \"import matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt; plt.plot([1,2,3]); plt.savefig('p.svg')\"`; `plt.subplots()` for panels; `plt.savefig('f.pdf', bbox_inches='tight')` for papers.",
            "Total control; headless (Agg); every format; foundation for seaborn/pandas; huge ecosystem and docs.",
            "Verbose for complex/statistical plots (seaborn wraps it); imperative; default style is plain (tunable); needs Python.",
            &["seaborn", "plotly", "gnuplot", "veusz"],
            "pacman: python-matplotlib (v3.10.9; /usr/lib/python3.14/site-packages)",
            "https://matplotlib.org/",
        ),
        tool(
            "pgfplots",
            "PGFPlots",
            DIA,
            "scientific_plotting",
            "TikZ-based LaTeX plotting — data/function charts with native typesetting, perfect for papers.",
            "PGFPlots builds on TikZ/PGF to draw 2D/3D function and data plots directly in LaTeX: line/scatter/bar/surface/contour plots from inline data, CSV/`.dat` tables, or expressions, with axis control, legends, error bars, and color maps — all typeset in the document's fonts and math. The result is a vector figure that matches the paper exactly.",
            "Reach for PGFPlots when a chart must be indistinguishable from the surrounding LaTeX document — consistent fonts, real math in axis labels, and vector output — accepting a compile step for the best typographic result.",
            "Input: LaTeX with `\\usepackage{pgfplots}` + `axis`/`addplot` (inline data, `\\addplot table {file.dat}`, or expressions). Output: PDF (LaTeX); SVG via dvisvgm.",
            "`\\begin{axis}\\addplot table {data.dat};\\end{axis}`; `\\addplot {sin(deg(x))};` for functions; `standalone` class + `dvisvgm` for SVG; `\\pgfplotsset{compat=1.18}`.",
            "Publication-perfect typography/math; reads CSV/tables; 2D+3D; one toolchain with the document; vector output.",
            "LaTeX learning curve; slow compile for big datasets (use `\\addplot table` + external data); not interactive; needs a full TeX install.",
            &["tikz", "gnuplot", "matplotlib", "dvisvgm"],
            "TeX Live 2026: pgfplots.sty (kpsewhich /usr/share/texmf-dist/tex/latex/pgfplots/pgfplots.sty)",
            "https://ctan.org/pkg/pgfplots",
        ),
        tool(
            "vega-cli",
            "Vega CLI (vg2svg/vg2png/vg2pdf)",
            DIA,
            "scientific_plotting",
            "Renders Vega visualization specs (declarative JSON grammar) to SVG/PNG/PDF headlessly.",
            "The Vega CLI renders a Vega specification — a JSON grammar of interactive visualization describing data, scales, marks, and axes — to static SVG, PNG, or PDF via `vg2svg`/`vg2png`/`vg2pdf`. Vega is the lower-level engine beneath Vega-Lite/Altair; the CLI is the headless way to turn a (possibly Altair-generated) spec into an image.",
            "Reach for the Vega CLI to render a declarative chart spec in a pipeline — e.g. compile an Altair/Vega-Lite chart to a Vega spec, then `vg2svg` it to a committed asset — or to render hand-written Vega specs without a browser.",
            "Input: a Vega JSON spec (`.vg.json`). Output: `vg2svg spec.vg.json out.svg` (also `vg2png`, `vg2pdf`).",
            "`vg2svg chart.vg.json chart.svg`; `vg2png chart.vg.json chart.png`; for Vega-Lite specs compile first (Altair `.save()` or `vl-convert`), then `vg2svg`; runs on Node from the workspace `node_modules/.bin`.",
            "Headless declarative-chart rendering; SVG/PNG/PDF; the engine behind Altair/Vega-Lite; reproducible spec→image.",
            "Consumes Vega (not Vega-Lite) specs directly — Vega-Lite needs a compile step; JSON specs are verbose by hand (generate via Altair); installed repo-locally.",
            &["altair", "plotly", "matplotlib"],
            "npm (workspace node_modules): /home/dylon/Workspace/f1r3fly.io/node_modules/.bin/vg2svg (vega-cli v6.2.0; + vg2png/vg2pdf)",
            "https://vega.github.io/vega/",
        ),
        tool(
            "veusz",
            "Veusz",
            DIA,
            "scientific_plotting",
            "Scientific plotting with a headless `--export` and a full Python API — publication-quality figures.",
            "Veusz is a scientific plotting package producing publication-quality 2D/3D graphs (xy, function, contour, image, vector, ternary, polar) with precise control over styling. Beyond the GUI it offers a command-line `--export` for batch rendering of `.vsz` documents and a `veusz.embed` Python API to build and export plots entirely in code.",
            "Reach for Veusz when you want carefully-styled scientific figures generated reproducibly — drive `veusz.embed` from Python to construct the plot and export SVG/PDF, or `--export` a committed `.vsz`, getting nicer defaults than raw matplotlib with less code than TikZ.",
            "Input: a `.vsz` document or a Python script using `veusz.embed`. Output: `--export=out.svg|.pdf|.png|.eps` (or `.Export()` in the API).",
            "`veusz --export=figure.pdf figure.vsz`; headless: `import veusz.embed as ve; g=ve.Embedded(hidden=True); ...; g.Export('out.svg')`; `--export-option` for DPI/size (offscreen Qt; a virtual display may be needed).",
            "Publication-quality defaults; scriptable via a real Python API; many scientific plot types; reproducible `.vsz` + export.",
            "Qt/offscreen rendering may need a display for headless export; GUI-centric design; smaller ecosystem than matplotlib.",
            &["matplotlib", "gnuplot", "pgfplots"],
            "pacman: veusz (/usr/bin/veusz, v4.2; + veusz.embed Python API)",
            "https://veusz.github.io/",
        ),
        tool(
            "r-graphics",
            "R / Rscript graphics",
            DIA,
            "scientific_plotting",
            "R's base & grid graphics via Rscript — statistical plots straight to SVG/PDF/PNG devices.",
            "R is a statistical computing environment whose graphics devices (`svg()`, `pdf()`, `png()`, `cairo_pdf()`) render base, lattice, and grid plots to files headlessly via `Rscript`. It is the substrate for ggplot2 and the natural home for statistical graphics — distributions, regressions, multivariate displays — driven from a script.",
            "Reach for Rscript graphics to generate statistical plots in a reproducible pipeline when the analysis is already in R, or when you want base/lattice plotting without the ggplot2 grammar; for layered grammar-of-graphics use ggplot2 on top.",
            "Input: an R script / `-e` expression operating on data frames. Output: open a device (`svg('out.svg')`), plot, then `dev.off()`.",
            "`Rscript -e 'svg(\"p.svg\"); plot(pressure); dev.off()'`; `Rscript -e 'png(\"p.png\",1200,800); hist(rnorm(1e4)); dev.off()'`; `cairo_pdf()` for high-quality vector PDF; source a `.R` file for full analyses.",
            "Best-in-class statistics + graphics together; multiple vector/raster devices; reproducible from scripts; foundation for ggplot2.",
            "R language learning curve; base-graphics API is dated (ggplot2 is nicer); heavier runtime than a plotting library.",
            &["ggplot2", "gnuplot", "matplotlib", "veusz"],
            "pacman: r (/usr/bin/Rscript, R v4.6.0)",
            "https://www.r-project.org/",
        ),
        tool(
            "ggplot2",
            "ggplot2 (grammar of graphics)",
            DIA,
            "scientific_plotting",
            "R's grammar-of-graphics library — layered, statistically-aware plots exported via ggsave.",
            "ggplot2 implements the Grammar of Graphics in R: you map data columns to aesthetics (x/y/color/size), add geometry layers (`geom_point`, `geom_line`, `geom_bar`, `geom_boxplot`), facets, scales, and statistical transforms, and ggplot2 composes a polished plot. `ggsave()` exports SVG/PDF/PNG headlessly. It is the standard for high-quality statistical graphics.",
            "Reach for ggplot2 when you want elegant, statistically-aware figures with minimal code — faceted small-multiples, fitted trends, distribution comparisons — generated reproducibly from R and exported to a committed asset.",
            "Input: an R data frame + a ggplot specification. Output: `ggsave('out.svg'|'.pdf'|'.png', plot, width, height, dpi)`.",
            "`Rscript -e 'library(ggplot2); ggsave(\"p.svg\", ggplot(mpg,aes(displ,hwy,color=class))+geom_point())'`; add `+facet_wrap(~class)`, `+geom_smooth()`, `+theme_minimal()`; `ggsave(..., device=\"pdf\")` for papers.",
            "Concise grammar for complex/statistical plots; beautiful defaults; faceting + statistical layers; the academic/data-science standard.",
            "Requires R + the package; grammar has a learning curve; slower than base graphics for trivial plots.",
            &["r-graphics", "matplotlib", "seaborn"],
            "R package (v4.0.3; install.packages('ggplot2'); invoked via Rscript)",
            "https://ggplot2.tidyverse.org/",
        ),
        tool(
            "seaborn",
            "seaborn",
            DIA,
            "scientific_plotting",
            "Statistical plotting on matplotlib — concise distribution, regression, and matrix charts.",
            "seaborn is a high-level statistical visualization library built on matplotlib: one-call functions for distributions (`histplot`/`kdeplot`), relationships (`scatterplot`/`lmplot` with fitted regressions), categorical plots (`boxplot`/`violinplot`), and matrices (`heatmap`/`clustermap`), with attractive themes and DataFrame-native input. It renders headlessly through matplotlib's Agg backend.",
            "Reach for seaborn to produce a statistically-meaningful chart in one line — a correlation heatmap, a faceted distribution, a regression scatter — when matplotlib would take many calls; it is the fastest path to a good-looking statistical figure in Python.",
            "Input: a pandas DataFrame via seaborn's API. Output: save the underlying matplotlib figure with `savefig` (Agg backend, headless).",
            "`python -c \"import matplotlib; matplotlib.use('Agg'); import seaborn as sns, matplotlib.pyplot as plt; sns.heatmap(df.corr()); plt.savefig('h.svg')\"`; `sns.lmplot(data=df,x=...,y=...)`; `sns.set_theme()` for styling.",
            "One-call statistical charts; great defaults; DataFrame-native; built on matplotlib (full customizability underneath).",
            "Statistical-chart focus (general custom plots → matplotlib); inherits matplotlib's headless setup; needs Python + pandas.",
            &["matplotlib", "plotly", "ggplot2"],
            "pacman: python-seaborn (v0.13.2; /usr/lib/python3.14/site-packages)",
            "https://seaborn.pydata.org/",
        ),
        tool(
            "plotly",
            "Plotly (Python)",
            DIA,
            "scientific_plotting",
            "Interactive web charts (HTML) plus static SVG/PNG export — rich, explorable scientific visualization.",
            "Plotly's Python library builds interactive, web-native charts (zoom/hover/pan) — scatter, line, bar, 3D, contour, maps, dashboards — emitting self-contained HTML, and exporting static SVG/PNG/PDF via the Kaleido engine. It excels when a figure benefits from interactivity or 3D exploration that a static image can't convey.",
            "Reach for Plotly when the audience benefits from an interactive/explorable chart (hover detail, zoom, 3D rotation) shipped as standalone HTML, or when you want one library for both interactive dashboards and static export.",
            "Input: data via `plotly.express`/`graph_objects`. Output: `fig.write_html('out.html')` (interactive) or `fig.write_image('out.svg'|'.png')` (static, via Kaleido).",
            "`python -c \"import plotly.express as px; px.line(df,x='t',y='v').write_html('c.html')\"`; `fig.write_image('c.svg')` for static (needs `python-kaleido`); `px.scatter_3d(...)` for 3D.",
            "Interactive HTML output; 3D and geographic charts; one API for interactive + static; great for dashboards/reports.",
            "Static export needs the Kaleido dependency; interactive HTML is heavier than an SVG; less typographic control than TikZ/matplotlib.",
            &["matplotlib", "altair", "seaborn"],
            "pacman: python-plotly (v6.8.0; static export needs python-kaleido)",
            "https://plotly.com/python/",
        ),
        tool(
            "altair",
            "Vega-Altair",
            DIA,
            "scientific_plotting",
            "Declarative Python charting (Vega-Lite grammar) — concise specs rendered to SVG/PNG via vl-convert.",
            "Altair is a declarative statistical-visualization library: you describe encodings (data column → x/y/color/size) and Altair emits a Vega-Lite JSON spec, which renders to interactive HTML or static SVG/PNG/PDF (via the `vl-convert` engine). The declarative model produces correct, composable charts with minimal code and a portable spec.",
            "Reach for Altair when you want concise, declarative charts whose specification is a portable Vega-Lite JSON (renderable by the Vega CLI, Kroki, or browsers) — ideal for reproducible, composable statistical graphics in notebooks or pipelines.",
            "Input: a pandas DataFrame via Altair's encoding API. Output: `chart.save('out.svg'|'.png'|'.html'|'.json')` (static needs vl-convert).",
            "`python -c \"import altair as alt, pandas as pd; alt.Chart(df).mark_point().encode(x='a',y='b').save('c.svg')\"`; `.save('c.json')` for the portable Vega-Lite spec → render with `vg2svg`/Kroki; install `python-vl-convert` (pacman extra) for headless SVG/PNG.",
            "Declarative/composable; portable Vega-Lite spec output; concise; interactive HTML or static; pairs with the installed Vega CLI.",
            "Static image export needs `python-vl-convert` (not yet installed — `sudo pacman -S python-vl-convert`); declarative model is less flexible for bespoke layouts; needs Python + pandas.",
            &["vega-cli", "plotly", "matplotlib", "seaborn"],
            "pacman: python-altair (v6.2.1); headless export via python-vl-convert (available in pacman extra, not yet installed)",
            "https://altair-viz.github.io/",
        ),
        tool(
            "wolfram-graphics",
            "Wolfram Language graphics",
            DIA,
            "scientific_plotting",
            "Mathematical visualization from the Wolfram Language kernel — function/data/3D/contour plots and graph diagrams exported to SVG/PDF/PNG.",
            "The Wolfram Language renders a broad range of graphics — `Plot`/`ListPlot`/`Plot3D`/`ContourPlot`/`DensityPlot`, charts (`Histogram`/`BarChart`), and network/graph diagrams (`Graph`/`GraphPlot`/`LayeredGraphPlot`) — and `Export[\"f.svg\"|.pdf|.png, …]` writes them headlessly from the kernel (no display needed).",
            "Reach for Wolfram graphics to plot a function/dataset or draw a graph diagram when the data or model is already in the Wolfram Language, or when you want publication-grade 2D/3D math visualization with exact symbolic input in one Export call.",
            "Input: a Wolfram Language graphics expression (`.wl`/`.wls` script or `-code`). Output: `Export[\"fig.svg\"|\".pdf\"|\".png\"|\".eps\", expr]` (vector SVG/PDF, headless).",
            "`wolfram -script plot.wl` whose body is `Export[\"fig.svg\", Plot[Sin[x],{x,0,2 Pi}]]`; `/usr/local/Wolfram/Wolfram/15.0/Executables/wolframscript -code 'Export[\"f.svg\", Plot3D[...]]'`; also the live `Wolfram` MCP server.",
            "Symbolic + numeric input in one language; 2D/3D/contour and graph diagrams; exact math in labels; vector SVG/PDF straight from the kernel (headless).",
            "Proprietary (needs license/activation); heavy kernel startup vs gnuplot/matplotlib; `wolframscript` not on PATH (use `wolfram -script` or the full path).",
            &["matplotlib", "gnuplot", "pgfplots"],
            "manual: Wolfram 15.0.0.0 (/usr/local/bin/wolfram; wolframscript at /usr/local/Wolfram/Wolfram/15.0/Executables/; MCP server \"Wolfram\")",
            "https://reference.wolfram.com/language/guide/Graphics.html",
        ),
    ]
}
