//! Model checkers and temporal/behavioural verification tools — the TLA⁺
//! ecosystem, explicit-state and timed checkers, process algebra, and
//! probabilistic checking.

use super::{FV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        tool(
            "tla-plus",
            "TLA⁺ / TLC",
            FV,
            "model_checker",
            "Leslie Lamport's specification language for concurrent/distributed systems, with the TLC explicit-state model checker.",
            "You model a system and its safety/liveness properties in TLA⁺ (or PlusCal), then TLC enumerates the reachable state space to find invariant/temporal violations and prints a counterexample trace.",
            "Reach for TLA⁺/TLC to design-check concurrency and distributed protocols (this repo's own TLA⁺ proofs use it): catch race/ordering/safety bugs in the spec before they reach code.",
            "Input: a `.tla` spec + `.cfg` (constants, invariants). Output: OK or a shortest counterexample trace.",
            "`tlc Spec.tla` (with Spec.cfg) model-checks; `pcal Spec.tla` translates PlusCal first; the TLA⁺ Toolbox/VS Code wrap `tla2tools.jar`.",
            "Excellent for protocol design; readable counterexamples; mature tooling and large example corpus.",
            "Explicit-state → state-space explosion on big models; bounded by `CONSTANTS`; not a code-level checker.",
            &["apalache", "tlaps", "spin", "storm"],
            "pacman: tla-tools (/usr/bin/tlc, pcal)",
            "https://lamport.azurewebsites.net/tla/tla.html",
        ),
        tool(
            "apalache",
            "Apalache",
            FV,
            "model_checker",
            "Symbolic (SMT-backed) model checker for TLA⁺ that checks bounded executions without enumerating states.",
            "Apalache translates a type-annotated TLA⁺ spec into SMT and uses Z3 to check inductive invariants and bounded behaviours, scaling to specs whose state space TLC cannot enumerate.",
            "Reach for Apalache when TLC explodes — prove an inductive invariant, or bounded-check a spec with large/infinite data domains — as a symbolic complement to TLC.",
            "Input: a typed `.tla` spec. Output: invariant holds / counterexample (within the bound/inductive check).",
            "`apalache-mc check --inv=Inv Spec.tla`; `apalache-mc check --inductive-inv` for inductive invariants; needs TLA⁺ type annotations.",
            "Handles large/symbolic state spaces; inductive-invariant checking; SMT-precise.",
            "Requires type annotations; bounded reasoning; inherits Z3's incompleteness on hard theories.",
            &["tla-plus", "tlaps", "z3"],
            "pacman: apalache-bin (/usr/bin/apalache-mc)",
            "https://apalache-mc.org",
        ),
        tool(
            "tlaps",
            "TLAPS (TLA⁺ Proof System)",
            FV,
            "proof_assistant",
            "Proof system for TLA⁺ that machine-checks hierarchical proofs by dispatching obligations to backend provers.",
            "TLAPS turns a structured TLA⁺ proof into obligations farmed out to Zenon, Isabelle, and SMT solvers, letting you prove unbounded safety (and some liveness) properties TLC can only test on finite models.",
            "Reach for TLAPS when bounded model checking isn't enough and you need a *proof* that an invariant holds for all parameters — the natural escalation from TLC/Apalache on the same spec.",
            "Input: a `.tla` spec with a `THEOREM … PROOF` structure. Output: per-obligation proved/failed status.",
            "`tlapm Spec.tla` checks the proofs (the TLA⁺ Toolbox drives it interactively); backends include Zenon/Isabelle/SMT.",
            "Unbounded, machine-checked TLA⁺ proofs; reuses the same spec as TLC; hierarchical proof structure.",
            "Proof effort is high; backend gaps on hard goals; TLA⁺-specific (not a general prover).",
            &["tla-plus", "zenon", "isabelle", "apalache"],
            "TLAPS: ~/.local/tlaps/bin/tlapm",
            "https://proofs.tlapl.us",
        ),
        tool(
            "spin",
            "SPIN",
            FV,
            "model_checker",
            "Explicit-state LTL model checker for concurrent software, using the Promela modeling language.",
            "SPIN compiles a Promela model into an optimized C verifier (`pan`) that exhaustively checks safety and LTL properties of interleaved processes, with partial-order reduction and bitstate hashing.",
            "Reach for SPIN to verify concurrent algorithms and protocols expressed as communicating processes — assertion/deadlock/LTL checking with fast, C-compiled search.",
            "Input: a `.pml` Promela model (+ LTL claims). Output: verification OK or a counterexample trail.",
            "`spin -a model.pml` emits `pan.c`; `cc -o pan pan.c && ./pan -a` verifies; `spin -t` replays a trail.",
            "Very fast C-compiled search; partial-order reduction + bitstate for big models; battle-tested.",
            "Promela is low-level; explicit-state limits; LTL only (no real-time/probabilities).",
            &["tla-plus", "mcrl2", "uppaal"],
            "pacman: spin (/usr/bin/spin)",
            "https://spinroot.com",
        ),
        tool(
            "ivy",
            "Ivy",
            FV,
            "model_checker",
            "Tool for specifying and verifying distributed protocols using decidable logic and inductive invariants.",
            "Ivy keeps verification conditions inside decidable fragments (EPR) so invariant checking is push-button and counterexamples are finite; it also supports protocol modeling, refinement, and code extraction.",
            "Reach for Ivy to verify safety of distributed/concurrent protocols by finding inductive invariants with decidable, counterexample-guided checks — avoiding SMT timeouts by construction.",
            "Input: `.ivy` protocol + invariants. Output: invariant inductive / a concrete counterexample-to-induction.",
            "`ivy_check spec.ivy` checks invariants; `ivy spec.ivy` opens the interactive GUI for invariant discovery.",
            "Decidable checks (predictable, finite counterexamples); good distributed-protocol workflow.",
            "Staying in the decidable fragment constrains modeling; smaller ecosystem; Python-2-era tooling.",
            &["tla-plus", "z3", "spin"],
            "pacman: ivy-git (/usr/bin/ivy, ivy_check)",
            "https://kenmcmil.github.io/ivy/",
        ),
        tool(
            "uppaal",
            "UPPAAL",
            FV,
            "timed_model_checker",
            "Model checker for real-time systems modeled as networks of timed automata with clocks.",
            "UPPAAL verifies reachability, safety, and liveness over timed automata (clock constraints, invariants, synchronization) and visualizes counterexample traces; CLI checking is via `verifyta`.",
            "Reach for UPPAAL when timing matters — real-time protocols, schedulers, timeouts, embedded controllers — where you must reason about clocks/deadlines, not just interleavings.",
            "Input: a `.xml` timed-automata model + a `.q` query file. Output: property satisfied / counterexample trace.",
            "`uppaal` opens the GUI editor/checker; CLI `verifyta query.q model.xml` (the GUI is installed here; verifyta ships with the toolkit).",
            "Purpose-built for timed automata; excellent GUI + simulation; symbolic zone-based search.",
            "Specialized to real-time models; not for general data/temporal logic; GUI-centric workflow.",
            &["spin", "storm", "tla-plus"],
            "pacman: uppaal (/usr/bin/uppaal — GUI)",
            "https://uppaal.org",
        ),
        tool(
            "mcrl2",
            "mCRL2",
            FV,
            "process_algebra",
            "Toolset for specifying and analyzing concurrent systems with an ACP-style process algebra and the modal μ-calculus.",
            "mCRL2 compiles a process specification to a linear process (LPS) and state space (LTS), then checks μ-calculus properties, behavioural equivalences (bisimulation), and does simulation/visualization.",
            "Reach for mCRL2 to verify communicating concurrent systems via process algebra and μ-calculus, or to compare two models up to (branching) bisimulation.",
            "Input: a `.mcrl2` spec (+ `.mcf` μ-calculus formula). Output: an LPS/LTS, equivalence/property verdict.",
            "`mcrl22lps spec.mcrl2 spec.lps` then `lps2lts` builds the state space; PBES tools check μ-calculus formulas; `ltsgraph` visualizes.",
            "Rich process-algebra + μ-calculus; behavioural-equivalence checking; strong visualization.",
            "Steep learning curve; multi-step toolchain; explicit-state limits on huge systems.",
            &["spin", "tla-plus", "storm"],
            "pacman: mcrl2 (/usr/bin/mcrl22lps, lps2lts, …)",
            "https://mcrl2.org",
        ),
        tool(
            "storm",
            "Storm",
            FV,
            "probabilistic_model_checker",
            "High-performance probabilistic model checker for Markov chains and MDPs.",
            "Storm computes reachability probabilities, expected rewards/costs, and PCTL/CSL properties over DTMCs, CTMCs, MDPs, and Markov automata, accepting PRISM, JANI, and explicit formats.",
            "Reach for Storm when behaviour is stochastic — fault-tolerance under failure rates, randomized algorithms, expected-time/cost analysis — to get quantitative guarantees, not just yes/no.",
            "Input: a PRISM/JANI model + a property file. Output: probabilities / expected values / a satisfaction verdict.",
            "`storm --prism model.pm --prop 'P=? [F \"goal\"]'`; `--jani model.jani`; supports symbolic (dd) and explicit engines.",
            "Fast, multi-engine; broad model + property support; quantitative results.",
            "State-space/numerical blow-up on large chains; modeling stochastic dynamics is its own skill.",
            &["uppaal", "mcrl2", "tla-plus"],
            "pacman: stormchecker (/usr/bin/storm)",
            "https://www.stormchecker.org",
        ),
    ]
}
