//! CPU profilers (sampling / instrumenting) and profile-visualization tools.

use super::{DEV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- CPU profilers ----
        tool(
            "perf",
            "perf (Linux perf_events)",
            DEV,
            "cpu_profiler",
            "The Linux kernel's sampling profiler, PMU-counter reader, and lightweight tracer.",
            "perf samples on-CPU stacks at a configurable rate, reads hardware/software performance counters (cycles, cache misses, branch misses), and can trace kernel/user events — the first-stop, lowest-overhead profiler on Linux.",
            "Reach for perf first to find CPU hotspots in a native (Rust/C/C++) program, count cache/branch-miss events, or profile system-wide; the default before any optimization. Pin to a core and fix the frequency (`taskset -c`, performance governor) for stable numbers.",
            "Input: a command or PID + an event spec. Output: `perf.data` (analyzed via `perf report`) or counter summaries.",
            "`perf record --call-graph lbr -- ./prog` then `perf report`; `perf stat ./prog` for counters; `perf top` for live system-wide sampling; `perf script` to export stacks.",
            "Lowest overhead; hardware counters + accurate stacks (LBR); ubiquitous; pairs with flamegraph/hotspot.",
            "Native code only (symbols needed); kernel/perf-paranoid permissions; raw reports are dense without a viewer.",
            &["vtune", "samply", "hotspot", "flamegraph", "bpftrace"],
            "pacman: perf (/usr/bin/perf)",
            "https://perfwiki.github.io/main/",
        ),
        tool(
            "vtune",
            "Intel VTune Profiler",
            DEV,
            "cpu_profiler",
            "Intel's advanced profiler for hotspot, microarchitecture, memory-access, and threading analysis.",
            "VTune drives the CPU's performance-monitoring unit for deep analyses — top-down microarchitecture exploration, memory-access/bandwidth, threading/locks, and HPC characterization — with a rich GUI and CLI.",
            "Reach for VTune when perf isn't enough: to attribute stalls to front-end/back-end/memory bound, find false sharing, analyze NUMA/bandwidth, or get microarchitecture-level guidance on Intel hardware.",
            "Input: a target binary/command + an analysis type. Output: a result directory viewable in `vtune-gui` or as reports.",
            "`vtune -collect hotspots -- ./prog`; `vtune -collect uarch-exploration -- ./prog`; `vtune-gui` opens results. Installed under /opt/intel/oneapi/vtune.",
            "Deep microarchitecture + memory + threading insight; excellent GUI; top-down methodology.",
            "Best on Intel CPUs; heavier setup/overhead than perf; large result directories.",
            &["perf", "hotspot", "samply"],
            "Intel oneAPI: /opt/intel/oneapi/vtune/latest/bin64/vtune (on PATH)",
            "https://www.intel.com/content/www/us/en/developer/tools/oneapi/vtune-profiler.html",
        ),
        tool(
            "samply",
            "samply",
            DEV,
            "cpu_profiler",
            "Cross-platform sampling profiler that opens results in the Firefox Profiler UI.",
            "samply records a sampling profile of a command or running process (using perf_events on Linux) and serves an interactive Firefox-Profiler view with stacks, a timeline, and per-thread tracks.",
            "Reach for samply when you want a quick, pretty, shareable interactive profile of a native/Rust program without configuring perf reporting — great for ad-hoc hotspot hunting.",
            "Input: a command or PID. Output: a local web view (Firefox Profiler) of the sampled profile.",
            "`samply record ./prog` profiles and opens the UI; `samply record -p <pid>` attaches to a process.",
            "Zero-config interactive UI; cross-platform; shareable profiles; great for Rust.",
            "Sampling only (no counters); needs the same perf permissions on Linux; younger tool.",
            &["perf", "cargo-flamegraph", "vtune"],
            "cargo: ~/.cargo/bin/samply",
            "https://github.com/mstange/samply",
        ),
        tool(
            "gprof",
            "gprof",
            DEV,
            "cpu_profiler",
            "Classic call-graph profiler for binaries compiled with `-pg` instrumentation.",
            "gprof reads the `gmon.out` produced by a `-pg`-instrumented run and reports a flat profile and call graph with self/cumulative times and call counts.",
            "Reach for gprof for a simple, portable call-graph + call-count profile when you can recompile with `-pg` and don't need sampling or hardware counters; otherwise prefer perf.",
            "Input: a `-pg`-compiled binary + its `gmon.out`. Output: flat profile + call-graph report.",
            "`gcc -pg -o prog prog.c && ./prog` writes `gmon.out`; `gprof prog gmon.out` prints the report.",
            "Exact call counts; portable; no special privileges.",
            "Requires recompilation/instrumentation; perturbs timing; weak with shared libs/threads; coarse.",
            &["perf", "kcachegrind"],
            "pacman: binutils (/usr/bin/gprof)",
            "https://sourceware.org/binutils/docs/gprof/",
        ),
        // ---- Profile visualization ----
        tool(
            "hotspot",
            "Hotspot",
            DEV,
            "profile_visualization",
            "GUI for Linux `perf` data — flame graphs, caller/callee, top-down, and off-CPU views.",
            "Hotspot loads a `perf.data` file and renders interactive flame graphs, a timeline, caller/callee tables, and summary metrics, turning raw perf output into a navigable analysis.",
            "Reach for Hotspot to actually *read* a perf recording — visually drill into hotspots, inspect per-thread timelines, and view off-CPU time — instead of squinting at `perf report`.",
            "Input: a `perf.data` (or it can record one). Output: an interactive GUI analysis.",
            "`perf record --call-graph dwarf -- ./prog` then `hotspot perf.data`; Hotspot can also launch the recording itself.",
            "Best-in-class perf GUI; flame graphs + timelines + off-CPU; no data conversion needed.",
            "Consumes perf data (Linux); GUI/desktop required; large recordings can be heavy.",
            &["perf", "flamegraph", "kcachegrind"],
            "pacman: hotspot (/usr/bin/hotspot)",
            "https://github.com/KDAB/hotspot",
        ),
        tool(
            "kcachegrind",
            "KCachegrind",
            DEV,
            "profile_visualization",
            "GUI to visualize Callgrind/Cachegrind profiles — call graph, cost maps, and annotated source.",
            "KCachegrind loads Valgrind callgrind/cachegrind output (or other formats) and shows the call graph, per-function event costs, a treemap, and source/assembly annotation; `callgrind_annotate` is the CLI equivalent.",
            "Reach for KCachegrind after a `valgrind --tool=callgrind` run to navigate exact instruction/cache costs by function and line — the standard viewer for Callgrind data.",
            "Input: a `callgrind.out.<pid>` (or cachegrind) file. Output: an interactive cost-analysis GUI.",
            "`valgrind --tool=callgrind ./prog` then `kcachegrind callgrind.out.<pid>`; CLI: `callgrind_annotate callgrind.out.<pid>`.",
            "Precise per-line/function cost navigation; call-graph + treemap; pairs perfectly with Callgrind.",
            "Visualizes Callgrind/Cachegrind data (which is ~10–50× slower to collect); desktop GUI.",
            &["valgrind-callgrind", "valgrind-cachegrind", "hotspot"],
            "pacman: kcachegrind (/usr/bin/kcachegrind, callgrind_annotate)",
            "https://kcachegrind.github.io/",
        ),
        tool(
            "flamegraph",
            "FlameGraph (Brendan Gregg)",
            DEV,
            "profile_visualization",
            "The original Perl toolkit that turns folded stack samples into an interactive SVG flame graph.",
            "`stackcollapse-*.pl` fold sampled stacks (from perf, dtrace, eBPF, etc.) into a line-per-stack format that `flamegraph.pl` renders as a zoomable SVG where width = time on CPU.",
            "Reach for this toolkit to generate a portable, shareable flame-graph SVG from any stack source — the canonical visualization for 'where is CPU time going'.",
            "Input: folded stacks (e.g. from `perf script`). Output: an interactive `.svg` flame graph.",
            "`perf record -g -- ./prog && perf script | stackcollapse-perf.pl | flamegraph.pl > out.svg`.",
            "Source-agnostic; tiny/portable; produces self-contained interactive SVGs.",
            "Manual pipeline; Perl scripts; you supply the sampler (perf/eBPF).",
            &["perf", "cargo-flamegraph", "hotspot"],
            "pacman: flamegraph (/usr/bin/stackcollapse-perf.pl, flamegraph.pl)",
            "https://github.com/brendangregg/FlameGraph",
        ),
        tool(
            "cargo-flamegraph",
            "cargo-flamegraph",
            DEV,
            "profile_visualization",
            "One-command flame graphs for Rust (and any binary), wrapping perf + the Rust `inferno` renderer.",
            "`cargo flamegraph` builds with debug info, profiles your binary/benchmark with perf (DTrace elsewhere), and emits an `inferno`-rendered `flamegraph.svg` — no manual folding pipeline.",
            "Reach for cargo-flamegraph to flame-graph a Rust program/benchmark in a single command — the easiest path from `cargo` project to a CPU flame graph.",
            "Input: a cargo target or an external binary/PID. Output: `flamegraph.svg`.",
            "`cargo flamegraph --bin prog` (or `--bench`); `flamegraph -- ./prog`; `flamegraph --pid <pid>` to attach.",
            "Zero-setup for Rust; reuses perf; inferno renderer is fast; attaches to running processes.",
            "Needs perf permissions/debug symbols; SVG-only output; sampling (no counters).",
            &["flamegraph", "samply", "perf"],
            "cargo: ~/.cargo/bin/cargo-flamegraph, flamegraph",
            "https://github.com/flamegraph-rs/flamegraph",
        ),
    ]
}
