//! Memory profilers, cache/call-graph profilers, and the Valgrind dynamic
//! error-detection tools.

use super::{DEV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- Memory profilers ----
        tool(
            "valgrind-massif",
            "Valgrind Massif",
            DEV,
            "memory_profiler",
            "Valgrind's heap profiler — tracks heap usage over time and pinpoints what allocates peak memory.",
            "Massif takes periodic heap snapshots while a program runs, recording how much each call site allocates, so you can see the peak and the allocation that drives it; `ms_print` renders the timeline.",
            "Reach for Massif to understand a program's memory growth and peak: which call stacks dominate the heap, and how usage evolves over time. (The user's go-to for memory profiling.)",
            "Input: a target command. Output: `massif.out.<pid>` (rendered by `ms_print`/`massif-visualizer`).",
            "`valgrind --tool=massif ./prog` then `ms_print massif.out.<pid>`; `--pages-as-heap=yes` to include all memory.",
            "Precise, call-stack-attributed heap snapshots; no recompilation; clear peak attribution.",
            "Large slowdown (Valgrind VM); heap-focused; sampling interval can miss spikes.",
            &["heaptrack", "bytehound", "valgrind-dhat"],
            "pacman: valgrind (/usr/bin/valgrind --tool=massif)",
            "https://valgrind.org/docs/manual/ms-manual.html",
        ),
        tool(
            "valgrind-dhat",
            "Valgrind DHAT",
            DEV,
            "memory_profiler",
            "Valgrind's dynamic heap-analysis tool — allocation hot spots, block lifetimes, and access patterns.",
            "DHAT records every heap block's size, lifetime, and read/write access counts, exposing short-lived allocations, never-read blocks, and over-allocation that Massif's snapshots don't show.",
            "Reach for DHAT to find allocation churn and wasteful heap usage: blocks allocated-then-barely-used, high turnover, or poor read/write density — guidance for preallocation and reuse.",
            "Input: a target command. Output: `dhat.out.*` viewed in the bundled `dh_view.html`.",
            "`valgrind --tool=dhat ./prog` then open the printed `dh_view.html` and load the output file.",
            "Unique lifetime/access-density insight; great for reducing allocation churn.",
            "Valgrind slowdown; heap-only; the web viewer workflow is a bit clunky.",
            &["valgrind-massif", "heaptrack", "bytehound"],
            "pacman: valgrind (/usr/bin/valgrind --tool=dhat)",
            "https://valgrind.org/docs/manual/dh-manual.html",
        ),
        tool(
            "heaptrack",
            "heaptrack",
            DEV,
            "memory_profiler",
            "Fast heap-memory profiler that traces every allocation with stacks, far cheaper than Massif.",
            "heaptrack intercepts allocations (via injection) and records call stacks, sizes, and lifetimes with low overhead, then its GUI shows peak consumers, leaks, allocation counts, and flame graphs.",
            "Reach for heaptrack when you want detailed allocation profiling with much less slowdown than Valgrind — find leaks, peak RSS contributors, and allocation-count hotspots interactively.",
            "Input: a command (or attach to a PID). Output: a `heaptrack.*.zst` trace opened in `heaptrack_gui`.",
            "`heaptrack ./prog` records; `heaptrack_gui heaptrack.prog.<pid>.zst` analyzes; `heaptrack --pid <pid>` attaches.",
            "Low overhead vs. Massif; rich GUI (flame graphs, leaks, peak); allocation-count analysis.",
            "Linux + glibc-centric; GUI for best use; large traces on alloc-heavy programs.",
            &["valgrind-massif", "bytehound", "valgrind-dhat"],
            "pacman: heaptrack (/usr/bin/heaptrack, heaptrack_gui)",
            "https://github.com/KDE/heaptrack",
        ),
        tool(
            "bytehound",
            "Bytehound",
            DEV,
            "memory_profiler",
            "Memory profiler for Linux with a web UI, focused on leaks, fragmentation, and allocation behaviour over time.",
            "Bytehound is `LD_PRELOAD`-injected to record allocations + stacks into a data file, then its server renders interactive graphs of memory over time, leak candidates, and per-stack breakdowns.",
            "Reach for Bytehound for long-running services where you want leak detection and time-series memory analysis with a browsable UI, as an alternative to heaptrack.",
            "Input: a program run with the profiler preloaded. Output: a `.dat` opened in the Bytehound web server.",
            "`LD_PRELOAD=/usr/lib/libbytehound.so ./prog` produces `memory-profiling_*.dat`; `bytehound server *.dat` opens the UI.",
            "Time-series memory view; good leak/fragmentation analysis; web UI.",
            "LD_PRELOAD workflow; Linux-only; overhead on allocation-heavy code.",
            &["heaptrack", "valgrind-massif"],
            "pacman: bytehound (/usr/bin/bytehound)",
            "https://github.com/koute/bytehound",
        ),
        // ---- Cache / call-graph profilers ----
        tool(
            "valgrind-cachegrind",
            "Valgrind Cachegrind",
            DEV,
            "cache_call_profiler",
            "Cache and branch-prediction profiler that simulates the CPU memory hierarchy for exact per-line miss counts.",
            "Cachegrind runs the program on a simulated I1/D1/LL cache + branch predictor and reports instruction, cache-miss, and branch-misprediction counts down to the source line.",
            "Reach for Cachegrind when you need deterministic, exact cache/branch statistics (not noisy hardware samples) to find cache-unfriendly code — reproducible across machines.",
            "Input: a target command. Output: `cachegrind.out.<pid>` (via `cg_annotate`/KCachegrind).",
            "`valgrind --tool=cachegrind ./prog` then `cg_annotate cachegrind.out.<pid>`.",
            "Exact, deterministic, per-line cache/branch counts; reproducible.",
            "Simulated model (not your real cache sizes unless configured); big slowdown; serial.",
            &["valgrind-callgrind", "perf", "kcachegrind"],
            "pacman: valgrind (/usr/bin/valgrind --tool=cachegrind, cg_annotate)",
            "https://valgrind.org/docs/manual/cg-manual.html",
        ),
        tool(
            "valgrind-callgrind",
            "Valgrind Callgrind",
            DEV,
            "cache_call_profiler",
            "Call-graph profiler (Cachegrind plus call-graph + instruction counts) visualized in KCachegrind.",
            "Callgrind records the dynamic call graph with per-function/per-line instruction counts (and optional cache simulation), producing data that KCachegrind navigates as a call graph and annotated source.",
            "Reach for Callgrind when you want an exact, deterministic call-graph profile — who calls whom and the instruction cost of each — to complement sampling profilers like perf.",
            "Input: a target command. Output: `callgrind.out.<pid>` (via `callgrind_annotate`/KCachegrind).",
            "`valgrind --tool=callgrind ./prog` then `callgrind_annotate callgrind.out.<pid>` or `kcachegrind callgrind.out.<pid>`.",
            "Exact call graph + instruction counts; great KCachegrind visualization; deterministic.",
            "Heavy slowdown (10–50×); instruction counts ≠ wall time; serial execution.",
            &["valgrind-cachegrind", "kcachegrind", "perf"],
            "pacman: valgrind (/usr/bin/valgrind --tool=callgrind, callgrind_annotate)",
            "https://valgrind.org/docs/manual/cl-manual.html",
        ),
        // ---- Valgrind dynamic error detectors ----
        tool(
            "valgrind-memcheck",
            "Valgrind Memcheck",
            DEV,
            "sanitizer",
            "Valgrind's default tool — detects memory errors and leaks in unmodified native binaries.",
            "Memcheck instruments every memory access to catch invalid reads/writes, use-after-free, uninitialized-value use, bad frees, and (with `--leak-check`) memory leaks — no recompilation required.",
            "Reach for Memcheck to debug memory corruption / leaks in C/C++ (or Rust FFI/`unsafe`) when you can't or don't want to recompile with sanitizers; the most thorough leak finder.",
            "Input: any native binary. Output: a report of memory errors + a leak summary.",
            "`valgrind ./prog` (Memcheck is default) or `valgrind --tool=memcheck --leak-check=full --track-origins=yes ./prog`.",
            "No recompilation; very thorough (incl. uninitialized reads); precise leak stacks.",
            "Large slowdown (10–30×); native code only; misses some stack/global bugs ASan catches.",
            &["asan", "lsan", "valgrind-helgrind"],
            "pacman: valgrind (/usr/bin/valgrind --tool=memcheck)",
            "https://valgrind.org/docs/manual/mc-manual.html",
        ),
        tool(
            "valgrind-helgrind",
            "Valgrind Helgrind",
            DEV,
            "sanitizer",
            "Valgrind's thread-error detector — data races, lock-ordering violations, and pthreads misuse.",
            "Helgrind monitors POSIX-threads synchronization and memory accesses to report data races, inconsistent lock orderings (potential deadlocks), and API misuse, without recompiling.",
            "Reach for Helgrind to hunt concurrency bugs in native multithreaded code when you can't rebuild with ThreadSanitizer — it flags races and lock-order inversions on the real binary.",
            "Input: a multithreaded native binary. Output: race / lock-order / API-misuse reports with stacks.",
            "`valgrind --tool=helgrind ./prog`; pair with `--history-level=full` for detailed race histories.",
            "No recompilation; detects lock-order inversions + races; complements Memcheck.",
            "Heavy slowdown; pthreads-focused; more false positives than TSan on some patterns.",
            &["tsan", "valgrind-memcheck"],
            "pacman: valgrind (/usr/bin/valgrind --tool=helgrind)",
            "https://valgrind.org/docs/manual/hg-manual.html",
        ),
    ]
}
