//! Interactive proof assistants (ITPs) and the Rocq/Coq reasoning libraries
//! installed alongside them.

use super::{FV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---------------------------------------------------------------
        // Proof assistants
        // ---------------------------------------------------------------
        tool(
            "agda",
            "Agda",
            FV,
            "proof_assistant",
            "Dependently-typed functional language and proof assistant where proofs are total programs.",
            "Checks that a program/proof inhabits a dependent type; proofs are written directly as terms with rich unification, pattern matching, and an interactive Emacs/VS Code hole-driven workflow.",
            "Reach for Agda when you want proofs-as-programs with a Martin-Löf / cubical type theory, strong pattern matching, and tight editor interaction — e.g. formalizing type theory, programming-language metatheory, or certified algorithms.",
            "Input: `.agda` modules. Output: a type-check verdict (and optionally compiled Haskell/JS via a backend).",
            "`agda Foo.agda` type-checks; `agda --compile --ghc-flag=-O Foo.agda` builds via the GHC backend; interactive editing through Emacs/VS Code `agda-mode` (load = C-c C-l).",
            "Total, constructive proofs-as-programs; excellent interactive hole filling; cubical extension for univalence.",
            "No tactic-style automation or hammer; large proofs are verbose; not aimed at classical/automated reasoning.",
            &["idris2", "lean", "rocq", "fstar"],
            "pacman: agda (/usr/bin/agda)",
            "https://agda.readthedocs.io",
        ),
        tool(
            "idris2",
            "Idris 2",
            FV,
            "proof_assistant",
            "Dependently-typed language with quantitative type theory, aimed at general-purpose verified programming.",
            "A practical, Agda-like language whose linearity-aware (QTT) type system lets you state and prove properties of real programs, then compile and run them.",
            "Reach for Idris 2 when you want dependent types for everyday programming with first-class compilation, linear resource tracking, and type-driven development — closer to a usable language than a pure proof assistant.",
            "Input: `.idr` modules / `.ipkg` packages. Output: a type-check verdict and a runnable executable.",
            "`idris2 Foo.idr` checks; `idris2` opens the REPL; `idris2 -o exe Foo.idr && ./build/exec/exe` compiles+runs; `idris2 --build pkg.ipkg` builds a package.",
            "Quantitative (linear) types; ergonomic type-driven editing; compiles to native/JS for real execution.",
            "Smaller library ecosystem than Coq/Lean; automation is limited; still maturing tooling.",
            &["agda", "lean", "fstar"],
            "pacman: idris2 (/usr/bin/idris2)",
            "https://idris2.readthedocs.io",
        ),
        tool(
            "isabelle",
            "Isabelle/HOL",
            FV,
            "proof_assistant",
            "Generic proof assistant most used with HOL, strong on automation (sledgehammer) and a large Archive of Formal Proofs.",
            "An LCF-style prover with the Isar structured proof language, the `sledgehammer` ATP/SMT bridge, the `nitpick`/`quickcheck` counterexample finders, and a mature Prover IDE (jEdit).",
            "Reach for Isabelle when you want heavy proof automation, classical higher-order logic, distributed-systems / real-analysis / floating-point formalizations, or to reuse the Archive of Formal Proofs.",
            "Input: `.thy` theories (+ session ROOT). Output: a checked session, optional PDF document, code export (SML/OCaml/Haskell/Scala).",
            "`isabelle jedit Foo.thy` opens the Prover IDE; `isabelle build -D .` batch-builds a session; `isabelle build -o document=pdf -D .` also emits the PDF.",
            "Best-in-class automation via sledgehammer + counterexample finders; vast AFP; robust batch builds.",
            "Classical HOL (not dependent types); the Isar/session model has a learning curve; rebuilds can be heavy.",
            &["rocq", "lean", "vampire", "z3"],
            "pacman: isabelle (/usr/bin/isabelle)",
            "https://isabelle.in.tum.de/documentation.html",
        ),
        tool(
            "lean",
            "Lean 4",
            FV,
            "proof_assistant",
            "Dependently-typed theorem prover and programming language with the large Mathlib library.",
            "Lean 4 is both an efficient functional language and a proof assistant; proofs use a powerful tactic framework and metaprogramming, with Mathlib supplying analysis, algebra, probability, and more.",
            "Reach for Lean when you want modern tactics + metaprogramming, the Mathlib library (autodiff, measure theory, concentration inequalities), and a language fast enough to also write tooling in.",
            "Input: `.lean` files in a Lake project. Output: a check verdict and compiled artifacts; `lakefile.lean` declares deps.",
            "`lake build` builds the project; `lean Foo.lean` checks one file; `lake env lean --run Foo.lean` runs; toolchains are pinned by elan via `lean-toolchain`.",
            "Excellent tactic + metaprogramming story; Mathlib breadth; fast compiler; active community.",
            "Mathlib moves fast (version churn); floating-point libraries are thinner than Coq+Flocq; large imports are slow.",
            &["rocq", "agda", "isabelle", "mathcomp"],
            "elan: ~/.elan/bin/lean (+ lake, leanc); toolchain via `elan`",
            "https://leanprover.github.io/theorem_proving_in_lean4/",
        ),
        tool(
            "rocq",
            "Rocq (Coq)",
            FV,
            "proof_assistant",
            "The Rocq prover (formerly Coq): tactic-based proof assistant on the Calculus of Inductive Constructions.",
            "Machine-checks proofs written with Ltac/Ltac2 tactics over dependent types; the engine behind this repo's own Rocq proofs, with libraries Flocq, Coquelicot, MathComp, Iris, and the coq-hammer automation.",
            "Reach for Rocq for inductive/algebraic correctness proofs, program extraction to OCaml/Haskell, floating-point envelopes (Flocq), or any proof reusing the installed Coq libraries; it is the project's default ITP.",
            "Input: `.v` files (+ `_CoqProject`). Output: compiled `.vo`, a proof-checked verdict, optional extracted code.",
            "`rocq compile Foo.v` (or `coqc Foo.v`) checks/compiles; `coqtop` / `coqide` for interactive; build big developments with `coq_makefile -f _CoqProject -o Makefile`. For memory-heavy proofs wrap in `systemd-run --user --scope -p MemoryMax=32G -p CPUQuota=1800% make -j1`.",
            "Mature tactics + extraction; rich library ecosystem (Flocq/Coquelicot/MathComp/Iris); reproducible batch builds.",
            "Steep tactic learning curve; weak native probabilistic reasoning; whole-development rebuilds can be slow/RAM-hungry.",
            &["lean", "isabelle", "agda", "coq-hammer", "iris"],
            "opam: ~/.opam/default/bin/{rocq,coqc,coqtop} (Rocq/Coq 9.1.1)",
            "https://rocq-prover.org/doc/",
        ),
        tool(
            "fstar",
            "F*",
            FV,
            "proof_assistant",
            "ML-style dependently-typed language with SMT-backed verification and effectful refinement types.",
            "F* discharges proof obligations from refinement/dependent types via Z3, supports user-defined effects and a Dijkstra-monad WP calculus, and extracts verified code to OCaml/C (KaRaMeL) — the basis of Project Everest / HACL*.",
            "Reach for F* to verify effectful systems code (crypto, parsers, protocols) with SMT automation and then extract it to efficient C; a middle ground between auto-active SMT and a full ITP.",
            "Input: `.fst`/`.fsti` modules. Output: a verification verdict; extracted OCaml or C (via KaRaMeL).",
            "`fstar.exe Foo.fst` verifies a module; `fstar.exe --version`; large projects drive verification + extraction through a Makefile.",
            "Powerful refinement types + effects with SMT automation; real extraction to C; proven at scale (HACL*).",
            "Relies on Z3 (brittle SMT timeouts/quantifiers); steeper than plain Dafny; build setup is involved.",
            &["dafny", "verus", "why3", "z3"],
            "pacman: fstar-git (/usr/bin/fstar.exe, fstar)",
            "https://www.fstar-lang.org",
        ),
        // ---------------------------------------------------------------
        // Rocq/Coq reasoning libraries (no standalone binary; depended on
        // via opam and `Require Import`ed inside a Rocq development)
        // ---------------------------------------------------------------
        tool(
            "coq-itree",
            "Interaction Trees (coq-itree)",
            FV,
            "coq_library",
            "Rocq library for representing impure, possibly-nonterminating computations with equational (weak-bisimulation) reasoning.",
            "Provides the `itree` coinductive type plus the `eutt` (equivalence-up-to-tau) relation and combinators, so effectful/recursive programs can be specified and proved equal by rewriting.",
            "Reach for Interaction Trees when modeling effectful or divergent computations (interpreters, compilers, semantics) in Rocq and you want monadic equational reasoning rather than ad-hoc step relations.",
            "Input: `From ITree Require Import ITree.` in a Rocq dev. Output: reusable definitions/lemmas linked into your `.vo`.",
            "Declare the opam dep `coq-itree` (or in dune `(depends coq-itree)`), then `From ITree Require Import ITree.`",
            "Clean monadic/equational reasoning over impurity and nontermination; composes with the dune/opam build.",
            "Coinductive proofs (often via paco) have a learning curve; not a standalone tool — only usable inside Rocq.",
            &["coq-paco", "rocq", "iris"],
            "opam: coq-itree 5.2.1",
            "https://github.com/DeepSpec/InteractionTrees",
        ),
        tool(
            "coq-paco",
            "Paco (coq-paco)",
            FV,
            "coq_library",
            "Rocq library for parameterized coinduction, making greatest-fixpoint proofs compositional.",
            "Replaces raw `cofix` with `pcofix`/`paco` combinators that support incremental accumulation of coinductive hypotheses, the standard backbone for bisimulation proofs (e.g. over interaction trees).",
            "Reach for Paco whenever you prove a coinductive property (bisimilarity, infinite traces, `eutt`) and want guarded, compositional coinduction instead of fragile `cofix`.",
            "Input: `From Paco Require Import paco.` Output: reusable coinduction infrastructure in your proof.",
            "opam dep `coq-paco`, then `From Paco Require Import paco.` and drive proofs with `pcofix`/`paco`.",
            "Sound, compositional coinduction; integrates with itree-style developments.",
            "Conceptually subtle (parameterization, monotonicity obligations); library-only, Rocq-specific.",
            &["coq-itree", "rocq"],
            "opam: coq-paco 4.2.3",
            "https://github.com/snu-sf/paco",
        ),
        tool(
            "iris",
            "Iris",
            FV,
            "coq_library",
            "Higher-order concurrent separation logic framework in Rocq, with the Iris Proof Mode tactics.",
            "A general framework for building program logics: resource algebras, invariants, ghost state, and the IPM (`iIntros`/`iApply`/`iMod`) for interactive separation-logic proofs; HeapLang is its sample language.",
            "Reach for Iris to verify concurrent / stateful programs with separation logic — fine-grained locks, message passing, refinement — or to build a bespoke program logic for your language.",
            "Input: `From iris.proofmode Require Import proofmode.` (+ `iris.heap_lang`). Output: separation-logic proofs in your dev.",
            "opam dep `rocq-iris` (+ `rocq-stdpp`), then `From iris.proofmode Require Import proofmode.`",
            "State-of-the-art concurrent separation logic; powerful ghost-state/invariant machinery; reusable across languages.",
            "Steep learning curve; dev (unstable) versions track Rocq closely; library-only.",
            &["rocq", "stdpp", "coq-itree"],
            "opam: rocq-iris (dev) + rocq-iris-heap-lang",
            "https://iris-project.org",
        ),
        tool(
            "stdpp",
            "std++ (coq-stdpp)",
            FV,
            "coq_library",
            "Extended “standard library” for Rocq — finite maps/sets, lists, tactics — underpinning Iris.",
            "Supplies well-engineered data structures (gmap, gset), typeclass-driven lemmas, and tactics (`set_solver`, `done`) that many Rocq developments (notably Iris) build on.",
            "Reach for std++ when you want robust finite maps/sets and strong automation tactics in Rocq, or because a dependency (Iris) requires it.",
            "Input: `From stdpp Require Import ...`. Output: reusable data structures + tactics in your proof.",
            "opam dep `rocq-stdpp`, then e.g. `From stdpp Require Import gmap.`",
            "Batteries-included finite structures + tactics; the de-facto base for Iris developments.",
            "Opinionated typeclass design; dev versions track Rocq; library-only.",
            &["iris", "rocq", "mathcomp"],
            "opam: rocq-stdpp (dev)",
            "https://gitlab.mpi-sws.org/iris/stdpp",
        ),
        tool(
            "coquelicot",
            "Coquelicot",
            FV,
            "coq_library",
            "Rocq real-analysis library (limits, derivatives, integrals, series) layered on the standard reals.",
            "Provides a user-friendly development of real analysis — `Lim`, `Derive`, `RInt`, power series — with total functions and lemmas convenient for engineering proofs.",
            "Reach for Coquelicot when a Rocq proof needs calculus/analysis: convergence bounds, derivative/integral facts, or numeric-method correctness.",
            "Input: `From Coquelicot Require Import Coquelicot.` Output: analysis lemmas/definitions in your dev.",
            "opam dep `coq-coquelicot`, then `From Coquelicot Require Import Coquelicot.`",
            "Total, ergonomic real analysis; pairs well with Flocq/Interval for numeric proofs.",
            "Classical reals (not constructive); library-only; some advanced analysis still missing.",
            &["flocq", "coq-interval", "rocq"],
            "opam: coq-coquelicot 3.4.4",
            "http://coquelicot.saclay.inria.fr",
        ),
        tool(
            "flocq",
            "Flocq",
            FV,
            "coq_library",
            "Rocq formalization of IEEE-754 floating-point arithmetic.",
            "Models binary/decimal floating-point formats, rounding modes, and error bounds, enabling proofs about the magnitude and rounding behaviour of `f64`/`f32` computations.",
            "Reach for Flocq to bound floating-point error or prove finiteness/rounding properties — e.g. this repo's MKN float-bounds proofs and any numeric-kernel envelope.",
            "Input: `From Flocq Require Import Core.` Output: floating-point lemmas in your Rocq proof.",
            "opam dep `coq-flocq`, then `From Flocq Require Import Core BinarySingleNaN.`",
            "Rigorous IEEE-754 model; basis for CompCert/Gappa-style numeric proofs; composes with Coquelicot/Interval.",
            "Bit-exact rounding proofs are intricate; library-only; needs analysis background.",
            &["coquelicot", "coq-interval", "rocq"],
            "opam: coq-flocq 4.2.2",
            "https://flocq.gitlabpages.inria.fr",
        ),
        tool(
            "coq-interval",
            "CoqInterval",
            FV,
            "coq_library",
            "Rocq tactic library that proves bounds on real-valued expressions automatically via interval arithmetic.",
            "The `interval`/`interval_intro` tactics discharge goals of the form `a <= expr <= b` (including transcendental functions) using rigorous interval and Taylor-model arithmetic.",
            "Reach for CoqInterval when you need an automatic, certificate-producing bound on a real expression instead of a manual analysis proof.",
            "Input: a real-inequality goal + `interval` tactic. Output: a closed proof of the bound.",
            "opam dep `coq-interval`, `From Interval Require Import Tactic.`, then `interval.` / `interval_intro expr.`",
            "Automatic, rigorous numeric bounds; handles transcendental functions; integrates with Flocq/Coquelicot.",
            "Only proves numeric bounds (not general analysis); tactic can be slow on wide intervals; library-only.",
            &["flocq", "coquelicot", "rocq"],
            "opam: coq-interval 4.11.4",
            "https://coqinterval.gitlabpages.inria.fr",
        ),
        tool(
            "mathcomp",
            "Mathematical Components (MathComp)",
            FV,
            "coq_library",
            "Rocq library for small-scale reflection (ssreflect) with a large algebra/finite-structures hierarchy.",
            "Supplies the ssreflect proof language and a coherent hierarchy (groups, rings, fields, finite types, matrices) that powers large formalizations such as the Odd Order theorem.",
            "Reach for MathComp when proving algebraic/combinatorial results, or whenever you want the ssreflect tactic discipline (`//`, `rewrite`, `case`) and reusable finite-structure lemmas.",
            "Input: `From mathcomp Require Import all_ssreflect.` Output: ssreflect proofs over the algebra hierarchy.",
            "opam dep `rocq-mathcomp-ssreflect` (+ `-algebra`), then `From mathcomp Require Import all_ssreflect.`",
            "Battle-tested algebra hierarchy; concise ssreflect proofs; huge body of reusable theory.",
            "ssreflect style is its own learning curve; heavy imports; library-only.",
            &["rocq", "lean", "coq-equations"],
            "opam: rocq-mathcomp-ssreflect 2.5.0 (+ algebra)",
            "https://math-comp.github.io",
        ),
        tool(
            "coq-hammer",
            "CoqHammer",
            FV,
            "coq_library",
            "Automation for Rocq that dispatches goals to external ATPs/SMT and reconstructs the proof.",
            "The `hammer` tactic translates the goal + selected lemmas to E/Vampire/CVC5, then reconstructs a Rocq proof from the solver’s output; `sauto`/`hauto` provide strong general-purpose search.",
            "Reach for CoqHammer to close routine first-order goals automatically (sledgehammer-style), or use `sauto` for heavy proof search before hand-finishing.",
            "Input: a Rocq goal + installed ATPs (E/Vampire). Output: a reconstructed tactic proof.",
            "opam dep `coq-hammer`, `From Hammer Require Import Hammer.`, then `hammer.` (or `sauto`/`hauto`). Needs eprover/vampire on PATH (both installed).",
            "Brings Isabelle-style hammer automation to Rocq; `sauto` is a strong solver; reuses installed ATPs.",
            "Reconstruction can fail/time out; premise selection is heuristic; depends on external provers.",
            &["rocq", "vampire", "eprover", "cvc5"],
            "opam: coq-hammer 1.3.2 (+ coq-hammer-tactics)",
            "https://coqhammer.github.io",
        ),
        tool(
            "coq-equations",
            "Equations",
            FV,
            "coq_library",
            "Rocq plugin for defining functions by dependent pattern matching and well-founded/structural recursion.",
            "The `Equations` command compiles rich dependent matches and recursion (with automatically derived equations, `funelim`, and graph) that the kernel would not accept directly.",
            "Reach for Equations when a function needs dependent pattern matching, nested/well-founded recursion, or clean elimination principles that raw `Fixpoint`/`match` make painful.",
            "Input: `From Equations Require Import Equations.` + an `Equations` definition. Output: the function plus its equation/elim lemmas.",
            "opam dep `rocq-equations`, then `From Equations Require Import Equations.` and define with `Equations f ... := ...`.",
            "Tames dependent matching and well-founded recursion; derives useful elimination/equation lemmas.",
            "Adds a plugin dependency; generated obligations can be heavy; library-only.",
            &["rocq", "mathcomp"],
            "opam: rocq-equations 1.3.1",
            "https://mattam82.github.io/Coq-Equations/",
        ),
    ]
}
