//! Term-rewriting analysis (termination / complexity / confluence) and
//! rewriting-logic / semantics frameworks.

use super::{FV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        tool(
            "aprove",
            "AProVE",
            FV,
            "termination_complexity",
            "Automated termination and complexity prover for rewriting systems and real programs (Java, C, Haskell, Prolog).",
            "AProVE proves termination and derivational/runtime complexity by translating programs to term-rewriting / integer-transition systems and applying a large portfolio of techniques, emitting a certifiable proof.",
            "Reach for AProVE to automatically prove termination or complexity bounds — of a TRS, or of actual Java/C/Haskell/Prolog code — when you want a machine-found, certifiable proof rather than a hand argument.",
            "Input: a TRS (`.trs`/`.xml` WST format) or a supported program. Output: YES/NO/MAYBE + a (certifiable) proof.",
            "`aprove problem.trs` runs the prover (Java-based; also has a web/Eclipse front-end); produces a proof tree.",
            "Broadest technique portfolio; handles real languages; certifiable (CeTA-checkable) proofs.",
            "Java startup overhead; MAYBE on hard inputs; proof output is large/complex.",
            &["ttt2", "tct-trs", "ttt2-cat"],
            "pacman: aprove (/usr/bin/aprove)",
            "https://aprove.informatik.rwth-aachen.de",
        ),
        tool(
            "ttt2",
            "TTT2 (Tyrolean Termination Tool 2)",
            FV,
            "termination_complexity",
            "Automated termination prover for term-rewriting systems, with a modular strategy language.",
            "TTT2 proves (non-)termination of TRSs using dependency pairs, reduction orders, and matrix/polynomial interpretations, exposing a composable strategy language to combine techniques.",
            "Reach for TTT2 to settle termination of a term-rewriting system, or as a fast, scriptable engine when you want to experiment with specific termination techniques.",
            "Input: a TRS in WST/TPDB (`.trs`/`.xml`) format. Output: YES/NO/MAYBE + proof, often CeTA-certifiable.",
            "`ttt2 problem.trs`; a strategy can be supplied to compose techniques (DP framework, interpretations).",
            "Fast; modular strategy language; certifiable proofs; long-standing competition tool.",
            "Termination only (see ttt2-cat/ttt2-csi for complexity/confluence); TRS-focused.",
            &["aprove", "ttt2-cat", "ttt2-csi", "tct-trs"],
            "pacman: ttt2-hg (/usr/bin/ttt2)",
            "http://cl-informatik.uibk.ac.at/software/ttt2/",
        ),
        tool(
            "ttt2-cat",
            "CaT (TTT2 complexity tool)",
            FV,
            "termination_complexity",
            "Complexity-analysis companion to TTT2: derives upper bounds on the runtime/derivational complexity of TRSs.",
            "CaT builds on TTT2's interpretation/DP machinery to infer asymptotic complexity bounds (e.g. polynomial degree) for term-rewriting systems.",
            "Reach for CaT (ttt2-cat) when you need a *complexity* bound for a rewriting system, not just a yes/no termination answer.",
            "Input: a TRS (WST/TPDB). Output: an asymptotic complexity bound (or MAYBE).",
            "`ttt2-cat problem.trs` infers a complexity bound.",
            "Reuses TTT2's solid foundations; produces quantitative complexity bounds.",
            "Bounds can be loose / MAYBE on hard systems; TRS-focused.",
            &["tct-trs", "ttt2", "aprove"],
            "pacman: ttt2-cat (/usr/bin/ttt2-cat)",
            "http://cl-informatik.uibk.ac.at/software/cat/",
        ),
        tool(
            "ttt2-csi",
            "CSI (confluence tool)",
            FV,
            "termination_complexity",
            "Automated confluence prover for term-rewriting systems, built on the TTT2 infrastructure.",
            "CSI proves or disproves confluence (and related properties like ground/commutation) of TRSs using critical-pair criteria, decomposition, and certifiable techniques.",
            "Reach for CSI (ttt2-csi) to decide whether a rewriting system is confluent — e.g. checking that a set of equations/rewrite rules has unique normal forms.",
            "Input: a TRS (WST/TPDB). Output: YES/NO/MAYBE for confluence (+ certifiable proof).",
            "`ttt2-csi problem.trs` proves/disproves confluence. (Note: the unrelated `csi` on PATH is Chicken Scheme.)",
            "Dedicated confluence engine; certifiable proofs; competition-grade.",
            "Confluence only; MAYBE on hard systems; TRS-focused.",
            &["ttt2", "maude", "aprove"],
            "pacman: ttt2-hg (/usr/bin/ttt2-csi)",
            "http://cl-informatik.uibk.ac.at/software/csi/",
        ),
        tool(
            "tct-trs",
            "TcT (Tyrolean Complexity Tool, TRS)",
            FV,
            "termination_complexity",
            "Automated complexity analyzer for term-rewriting systems (runtime and derivational complexity).",
            "TcT infers polynomial and other asymptotic complexity bounds for TRSs via a strategy-driven combination of interpretation, dependency-tuple, and decomposition techniques.",
            "Reach for TcT when you want certified complexity bounds for rewriting (or as a cross-check against CaT) — quantitative cost analysis of a rewrite system.",
            "Input: a TRS (WST/TPDB). Output: an asymptotic complexity certificate (or MAYBE).",
            "`tct-trs problem.trs`; strategies select the complexity techniques applied.",
            "Strong complexity portfolio; strategy-driven; competition-grade.",
            "Complexity only; bounds may be loose; TRS-focused.",
            &["ttt2-cat", "aprove", "ttt2"],
            "pacman: tct-trs (/usr/bin/tct-trs)",
            "http://cl-informatik.uibk.ac.at/software/tct/",
        ),
        tool(
            "maude",
            "Maude",
            FV,
            "rewriting_semantics",
            "High-performance rewriting-logic system for executable specifications, with reflection and a built-in LTL model checker.",
            "Maude executes equational + rewriting-logic theories (functional and system modules), supports reduce/rewrite/search, metalevel reflection, and an LTL model checker — a workhorse for language semantics and concurrency.",
            "Reach for Maude to define and *run* the operational semantics of a calculus or protocol, search reachable states, or LTL-model-check a rewrite theory; a natural fit for Rholang/process-calculus experiments.",
            "Input: `.maude` modules. Output: reduced terms, search solutions, or model-checking results.",
            "`maude file.maude` loads + runs; inside: `reduce t .`, `rewrite t .`, `search t =>* p .`, `red modelCheck(init, prop) .`.",
            "Fast rewriting engine; reflection/metaprogramming; built-in search + LTL checking.",
            "Untyped-ish flexibility can hide errors; LTL checker is explicit-state; niche language.",
            &["k-framework", "ttt2-csi", "ott"],
            "pacman: maude (/usr/bin/maude)",
            "https://maude.cs.illinois.edu",
        ),
        tool(
            "k-framework",
            "K Framework",
            FV,
            "rewriting_semantics",
            "Framework for defining programming-language semantics from which interpreters, verifiers, and tools are generated.",
            "In K you write a language's syntax + configuration + rewrite rules once; `kompile` then yields an executable interpreter, a symbolic-execution/verification engine (via the Haskell backend + Z3), and more.",
            "Reach for K to give a language a single rigorous operational semantics and get an interpreter and a program verifier for free — the approach behind KEVM and the C/Java semantics.",
            "Input: a `.k` language definition (+ programs). Output: a compiled semantics; execution traces; proof results.",
            "`kompile lang.k` compiles the semantics; `krun program` executes; `kprove spec.k` does reachability verification.",
            "One semantics → many tools; symbolic execution + reachability proofs; proven at scale (KEVM).",
            "Steep learning curve; compilation is heavy; verification depends on Z3 limits.",
            &["maude", "ott", "rocq"],
            "pacman: k-framework (/usr/bin/kompile, krun, kparse)",
            "https://kframework.org",
        ),
        tool(
            "ott",
            "Ott",
            FV,
            "rewriting_semantics",
            "Tool for writing definitions of programming languages and calculi, generating LaTeX and proof-assistant definitions.",
            "From a single Ott source (grammar + inductive relations) it generates typeset LaTeX plus Coq/Rocq, HOL, and Isabelle inductive definitions, keeping a paper's rules and its mechanization in sync.",
            "Reach for Ott when formalizing a calculus' syntax and judgments: author the rules once and emit both the paper's typeset semantics and the Rocq/Isabelle definitions to prove over.",
            "Input: a `.ott` definition. Output: LaTeX and/or Coq/Rocq/HOL/Isabelle source.",
            "`ott -i defn.ott -o defn.tex` (LaTeX); `ott -i defn.ott -coq defn.v` emits Rocq definitions.",
            "Single source of truth for syntax/semantics; multi-backend codegen; great for PL metatheory papers.",
            "Generates definitions, not proofs (you still prove in the ITP); binder handling needs care (locally-nameless/LNgen).",
            &["k-framework", "rocq", "maude"],
            "opam: ~/.opam/default/bin/ott (0.34)",
            "https://www.cl.cam.ac.uk/~pes20/ott/",
        ),
        tool(
            "discopy-categorical",
            "DisCoPy (categorical semantics / ZX)",
            FV,
            "rewriting_semantics",
            "Compute with string diagrams in Python: free monoidal categories, functorial semantics, ZX-calculus rewriting, and pregroup grammars.",
            "DisCoPy builds the free monoidal category over a signature — with `monoidal`, `braided`, `symmetric`, `rigid`, `compact`, `frobenius`, `traced`, `markov`, and `hypergraph` layers — and interprets it through a `Functor` into concrete semantics (numpy/tensorflow tensors, python functions, quantum channels). On top of that sit the ZX-calculus (`quantum.zx`), quantum circuits and ansätze, pregroup/DisCoCat derivations (`grammar.pregroup`), Thue rewrite systems (`grammar.thue`), diagram `normal_form()`, and structural equality.",
            "Reach for DisCoPy to model a system as a monoidal category and check equalities by diagram rewriting: verify a quantum-circuit identity through ZX, give functorial semantics to a protocol or process algebra, or explore compositional (DisCoCat) grammar. It answers \"do these two processes denote the same thing?\" compositionally, where `maude`/`k-framework` answer it by term rewriting over a syntax.",
            "Input: Python term construction (`>>`, `@`, `.dagger()`) plus a `Functor` assigning objects to dimensions and boxes to arrays. Output: normalized diagrams, functor images (tensors / python functions), booleans from equality checks, and drawings.",
            "ZX: `python -c \"from discopy.quantum.zx import Z,X,Id; print(Z(1,2) >> Id(1) @ X(1,1))\"`; semantics: `from discopy.frobenius import Ty,Box; from discopy.tensor import Dim,Functor; x=Ty('x'); f=Box('f',x,x); F=Functor(ob={x:Dim(2)}, ar={f:[[0,1],[1,0]]}); F(f>>f).array` → the 2×2 identity; normalization: `d.normal_form()`; pregroup: `from discopy.grammar.pregroup import Ty,Word,Cup,Id`.",
            "Compositional by construction — a `Functor` *is* the semantics, so syntax and meaning cannot silently drift apart; ZX rewriting for circuit identities; sympy-backed symbolic scalars for parameterised diagrams; the same object also draws (see the `discopy` card).",
            "NOT machine-checked: there is no proof object or trusted kernel, and equality is structural or numeric (floating-point) — reach for `rocq`, `z3`, or `tla-plus` when a proof is required. The optional `pytket`, `pennylane`, `torch`, and `nltk` backends are NOT installed here, so `quantum.tk`, `quantum.pennylane`, the torch tensor backend, and `grammar.cfg` NLTK parsing are unavailable (`sympy` and `tensorflow` are present).",
            &["maude", "k-framework", "ott", "discopy"],
            "pacman: python-discopy (/usr/lib/python3.14/site-packages/discopy, v1.2.2)",
            "https://discopy.org/",
        ),
    ]
}
