//! Security-protocol verifiers, GPU-kernel verifiers, and the
//! computer-algebra / logic / optimization solvers that round out the
//! formal-verification toolbox.

use super::{FV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- Security-protocol verifiers ----
        tool(
            "proverif",
            "ProVerif",
            FV,
            "security_protocol_verifier",
            "Symbolic cryptographic-protocol verifier (Dolev-Yao) proving secrecy and authentication for unbounded sessions.",
            "ProVerif models a protocol in the applied pi-calculus, compiles it to Horn clauses, and proves reachability/correspondence/equivalence properties against an active network attacker for an unbounded number of sessions.",
            "Reach for ProVerif to verify key-exchange / authentication protocols symbolically — secrecy, authentication, and observational-equivalence (privacy) goals — with a high degree of automation.",
            "Input: a `.pv` (applied-pi) model. Output: property true / false + an attack derivation, or 'cannot be proved'.",
            "`proverif protocol.pv` runs the analysis; `proverif -in pitype protocol.pv`; horn-clause resolution is fully automatic.",
            "Unbounded-session proofs; high automation; handles equivalence/privacy properties.",
            "Symbolic model only (no computational/probabilistic guarantees); may report false attacks; abstraction can loop.",
            &["tamarin"],
            "pacman: proverif (/usr/bin/proverif)",
            "https://bblanche.gitlabpages.inria.fr/proverif/",
        ),
        tool(
            "tamarin",
            "Tamarin Prover",
            FV,
            "security_protocol_verifier",
            "Symbolic protocol verifier based on multiset rewriting, strong on Diffie-Hellman and stateful protocols.",
            "Tamarin models protocols as multiset-rewriting rules and proves trace/equivalence properties (specified in a guarded fragment) using backward search, with built-in Diffie-Hellman/bilinear-pairing equational theories and an interactive proof GUI.",
            "Reach for Tamarin for protocols with rich algebraic operators (DH, signatures, XOR) or mutable global state, or when you want to guide the proof interactively when full automation stalls.",
            "Input: a `.spthy` theory (rules + lemmas). Output: each lemma verified / falsified (with an attack graph).",
            "`tamarin-prover --prove protocol.spthy` proves all lemmas; `tamarin-prover interactive protocol.spthy` opens the GUI.",
            "Powerful equational theories (DH); handles global state; interactive proof guidance.",
            "Proofs may need manual 'oracle'/lemma guidance; can be slow; symbolic model only.",
            &["proverif"],
            "pacman: tamarin-prover (/usr/bin/tamarin-prover)",
            "https://tamarin-prover.com",
        ),
        // ---- GPU-kernel verifiers ----
        tool(
            "gpuverify",
            "GPUVerify",
            FV,
            "gpu_verifier",
            "Static verifier for CUDA and OpenCL kernels, proving freedom from data races and barrier divergence.",
            "GPUVerify encodes a kernel into a sequential Boogie program over two arbitrary threads and uses an SMT solver to prove the absence of intra-group data races and barrier divergence.",
            "Reach for GPUVerify to check that a CUDA/OpenCL kernel is data-race- and barrier-divergence-free before trusting it — static, no test inputs required.",
            "Input: a `.cu`/`.cl` kernel + thread/group dimensions. Output: verified or a race/divergence witness.",
            "`gpuverify --local_size=256 --num_groups=64 kernel.cu` (CUDA) or `--local_size=... kernel.cl` (OpenCL).",
            "Sound race/divergence checks without test inputs; CUDA + OpenCL.",
            "Needs fixed thread dimensions/annotations; abstraction can yield false alarms; project is older/less maintained.",
            &["faial", "esbmc"],
            "pacman: gpuverify-git (/usr/bin/gpuverify)",
            "https://www.gpuverify.org",
        ),
        tool(
            "faial",
            "Faial",
            FV,
            "gpu_verifier",
            "Modern data-race-freedom analyzer for GPU kernels.",
            "Faial checks CUDA kernels for data-race freedom using a scalable, inference-based encoding to SMT, often handling kernels and thread configurations that defeat older tools.",
            "Reach for Faial as a newer alternative/cross-check to GPUVerify for proving GPU kernels race-free, especially when GPUVerify times out or rejects valid code.",
            "Input: a CUDA kernel source. Output: data-race-free or a counterexample.",
            "`faial-drf kernel.cu` runs the data-race-freedom check (the installed binary is `faial-drf`).",
            "Scales better than older tools on many kernels; focused, fast DRF analysis.",
            "Focused on data-race freedom (not full functional correctness); CUDA-centric.",
            &["gpuverify"],
            "pacman: faial-git (/usr/bin/faial-drf)",
            "https://gitlab.com/umb-svl/faial",
        ),
        // ---- Computer algebra / logic / optimization ----
        tool(
            "sagemath",
            "SageMath",
            FV,
            "computer_algebra",
            "Comprehensive open-source computer-algebra system built on Python, integrating PARI, GAP, Singular, Maxima, and more.",
            "Sage provides a unified Python interface to a vast range of mathematics — number theory, algebra, combinatorics, elliptic curves, cryptography, symbolic + numerical computation — wrapping many specialized backends.",
            "Reach for SageMath to compute and check mathematics underpinning a proof or crypto design: factor/solve, explore groups/rings/curves, sanity-check conjectures, or prototype number-theoretic attacks.",
            "Input: Sage/Python expressions or `.sage` scripts. Output: computed mathematical objects/values.",
            "`sage` opens the REPL; `sage script.sage` runs a script; `sage -python` for plain Python with Sage libs.",
            "Enormous breadth; one interface over many CAS backends; full programming language.",
            "Heavy install/startup; not a prover (computation, not machine-checked proof); occasional backend quirks.",
            &["wolfram", "msolve", "swi-prolog", "csdp"],
            "pacman: sagemath (/usr/bin/sage); sagemath-giac, sagetex",
            "https://www.sagemath.org",
        ),
        tool(
            "msolve",
            "msolve",
            FV,
            "computer_algebra",
            "Fast C library/CLI for solving multivariate polynomial systems via Gröbner bases.",
            "msolve computes Gröbner bases and uses them to decide ideal membership, count/real-solve polynomial systems, and perform real root isolation, with state-of-the-art performance.",
            "Reach for msolve when a problem reduces to polynomial-system solving — real solutions, ideal membership, parametric systems — and you need speed beyond a general CAS.",
            "Input: a polynomial system (msolve `.ms` format). Output: solutions / a Gröbner basis / real root isolation.",
            "`msolve -f system.ms -o solutions.txt`; flags select real solving vs. Gröbner-basis output.",
            "Very fast Gröbner/real-solving; clean CLI + C API; great for certified algebraic computations.",
            "Specialized (polynomial systems only); input format is low-level; not a general CAS.",
            &["sagemath", "csdp"],
            "pacman: msolve (/usr/bin/msolve)",
            "https://msolve.lip6.fr",
        ),
        tool(
            "wolfram",
            "Wolfram Language",
            FV,
            "computer_algebra",
            "Proprietary computer-algebra and technical-computing system (the Mathematica engine) spanning symbolic, numeric, and modeling mathematics in one language.",
            "The Wolfram Language evaluates a vast built-in library — symbolic algebra, equation/ODE/PDE solving, calculus, linear algebra, number theory, optimization, statistics, and arbitrary-precision numerics — through a uniform symbolic-rewriting kernel.",
            "Reach for Wolfram Language to model and check the mathematics under a proof or design: simplify symbolically, solve equation/ODE systems, integrate/sum, do matrix algebra or optimization, or sanity-check a closed form — broad coverage in one expression. Its proof, decision-procedure, modeling, and plotting surfaces are carded separately as `wolfram-prover`, `wolfram-solver`, `wolfram-modeling`, and `wolfram-graphics`.",
            "Input: Wolfram Language expressions or `.wl`/`.wls`/`.m` scripts. Output: computed symbolic/numeric results (and exportable plots/data).",
            "`wolfram -script foo.wl` runs a script (on PATH); `/usr/local/Wolfram/Wolfram/15.0/Executables/wolframscript -code 'expr'` / `-file foo.wls`; also the live `Wolfram` MCP server (`mcp__Wolfram__WolframLanguageEvaluator`), which is the lowest-friction agent path.",
            "Enormous built-in breadth (symbolic + numeric + modeling) in one language; exact/arbitrary precision; already wired as an MCP server for direct agent calls.",
            "Proprietary. **Only 2 concurrent kernels** (`$MaxLicenseProcesses == 2`): each long-lived `Wolfram/AgentTools` MCP server holds a seat for its whole session, so when two agent sessions are up, EVERY new kernel — `wolfram -script`, `wolframscript`, another MCP server — dies with the misleading `No valid password found.` (rc 85). That message means seat exhaustion, not a bad license; diagnose with `ps -eo pid,etimes,args | grep WolframKernel` and free a seat before blaming activation. Heavy kernel startup. `wolframscript` is not on PATH (use `wolfram -script` or the full `Executables/` path). Computation is not proof — but note `wolfram-prover` DOES emit machine-checked equational `ProofObject`s.",
            &[
                "sagemath",
                "msolve",
                "wolfram-prover",
                "wolfram-solver",
                "wolfram-modeling",
                "wolfram-graphics",
            ],
            "manual: Wolfram 15.0.0.0, $LicenseType Professional, $MaxLicenseProcesses 2 (/usr/local/bin/wolfram; wolframscript at /usr/local/Wolfram/Wolfram/15.0/Executables/; MCP server \"Wolfram\")",
            "https://reference.wolfram.com/language/",
        ),
        tool(
            "swi-prolog",
            "SWI-Prolog",
            FV,
            "logic_programming",
            "Mature ISO Prolog system with constraint (CLP) libraries, tabling, and broad library support.",
            "SWI-Prolog executes logic programs via SLD resolution with extensions — constraint solving (CLP(FD)/CLP(R)), tabling for termination, DCGs for parsing, and a large package ecosystem.",
            "Reach for SWI-Prolog for relational/constraint problems, rapid prototyping of inference rules, parsing with DCGs, or exploring search problems declaratively.",
            "Input: `.pl` programs + queries. Output: query solutions (with backtracking) / constraint solutions.",
            "`swipl` opens the REPL; `swipl script.pl`; `swipl -g main -t halt script.pl` runs a goal and exits.",
            "Robust, fast, feature-rich (CLP, tabling, DCG); great docs; embeddable.",
            "Not a verifier/prover of correctness; performance needs care; Prolog's cut/negation has pitfalls.",
            &["sagemath"],
            "pacman: swi-prolog (/usr/bin/swipl)",
            "https://www.swi-prolog.org",
        ),
        tool(
            "csdp",
            "CSDP",
            FV,
            "optimization_solver",
            "COIN-OR semidefinite-programming solver, used to produce sums-of-squares / Positivstellensatz certificates.",
            "CSDP solves semidefinite programs by a predictor-corrector interior-point method; in verification it backs SOS-based nonnegativity certificates (e.g. the `psatz`/`csdp` tactics in proof assistants).",
            "Reach for CSDP when a proof or analysis needs a semidefinite/SOS certificate — proving a polynomial is nonnegative, bounding a quadratic form — or for general SDP optimization.",
            "Input: an SDP in SDPA sparse format (`.dat-s`). Output: primal/dual solution + objective value.",
            "`csdp problem.dat-s` solves and writes the solution; typically invoked by an SOS/Positivstellensatz front-end.",
            "Reliable SDP interior-point solver; the standard SOS-certificate backend.",
            "SDP-specific; needs problems in SDPA format; numerical conditioning matters.",
            &["coin-or-clp", "msolve"],
            "pacman: coin-or-csdp (/usr/bin/csdp)",
            "https://github.com/coin-or/Csdp",
        ),
        tool(
            "coin-or-clp",
            "COIN-OR CLP",
            FV,
            "optimization_solver",
            "COIN-OR's open-source linear-programming (simplex/barrier) solver, with CBC for mixed-integer problems.",
            "CLP solves large linear programs by primal/dual simplex or interior-point; together with CBC (branch-and-cut) it handles mixed-integer programs, exposed via files and the CoinMP C API.",
            "Reach for COIN-OR CLP/CBC for linear and mixed-integer optimization — resource allocation, scheduling relaxations, LP-bounded analyses — when you want a dependency-free open-source solver.",
            "Input: an LP/MIP in `.mps`/`.lp` format. Output: an optimal solution + objective (or infeasible/unbounded).",
            "`clp model.mps -solve -solution out.txt`; the CoinMP library (pacman coin-or-mp) exposes the C API.",
            "Robust open-source LP/MIP; scriptable + embeddable; no license cost.",
            "Not a verifier; tuning needed on hard MIPs; commercial solvers are faster on the largest models.",
            &["csdp", "msolve"],
            "pacman: coin-or-clp (/usr/bin/clp); coin-or-mp",
            "https://github.com/coin-or/Clp",
        ),
        // ---- Wolfram: proof / decision procedures / system modeling ----
        // One installation (`wolfram`, the CAS card above) surfaces three further
        // agent-facing capabilities that are NOT computer algebra. Slugs are
        // globally unique, so each gets its own card in its own category.
        tool(
            "wolfram-prover",
            "Wolfram FindEquationalProof",
            FV,
            "first_order_atp",
            "Automated equational theorem prover that returns an inspectable, machine-checked ProofObject.",
            "`FindEquationalProof[thm, axioms]` runs Wolfram's equational-logic prover (a Waldmeister-lineage completion/superposition engine) and returns a `ProofObject` — not a yes/no. The object exposes `ProofLength`, `Axioms`, `ProofDataset` (every step with its justification), `ProofFunction`, and `ProofGraph`/`ProofGraphLabeled`/`ProofGraphWeighted`, so the derivation can be replayed, audited, and rendered.",
            "Reach for it to prove an equational identity from a set of axioms — group/ring/lattice/Boolean-algebra laws, rewrite-system consequences, algebraic-specification obligations — when you want a checkable proof term and a proof graph rather than an SMT sat/unsat verdict. For non-equational first-order goals use `eprover`/`vampire`; for inductive/dependent proofs use `rocq`/`lean`.",
            "Input: a goal equation (optionally `ForAll`-quantified) plus a list of axiom equations. Output: a `ProofObject` (or `$Failed`); `pf[\"ProofGraph\"]` is exportable to SVG/PDF.",
            "`FindEquationalProof[ForAll[{a,b}, f[a,b]==f[b,a]], {ForAll[{a,b,c}, f[f[a,b],c]==f[a,f[b,c]]], ForAll[{a,b}, f[a,f[b,a]]==b]}]` → ProofObject (ProofLength 11); inspect `pf[\"ProofDataset\"]`, render `Export[\"proof.svg\", pf[\"ProofGraph\"]]`. Drive it via the `Wolfram` MCP server (`mcp__Wolfram__WolframLanguageEvaluator`) or `wolfram -script`.",
            "Emits a real proof object (steps + justification + graph), not just a verdict; strong on pure equational theories; the proof graph exports straight to SVG for documentation.",
            "Equational logic ONLY — no predicates, no induction, no quantifier alternation beyond the implicit universals. Proprietary. Search may not terminate (bound it with `TimeConstraint`). Shares the 2-process license seat pool (see the `wolfram` card).",
            &["eprover", "vampire", "zenon", "wolfram", "maude"],
            "manual: Wolfram 15.0.0.0, $LicenseType Professional (/usr/local/bin/wolfram; MCP server \"Wolfram\")",
            "https://reference.wolfram.com/language/ref/FindEquationalProof.html",
        ),
        tool(
            "wolfram-solver",
            "Wolfram Reduce / Resolve / SatisfiabilityInstances",
            FV,
            "smt_solver",
            "Exact decision procedures: real/complex quantifier elimination (CAD), Diophantine solving, and Boolean satisfiability.",
            "`Resolve`/`Reduce` decide quantified formulas over the reals by Cylindrical Algebraic Decomposition (and over algebraically closed fields, integers, and mixed domains), returning an equivalent quantifier-free condition rather than a witness. `SatisfiableQ`/`SatisfiabilityInstances` are a Boolean SAT front end, `FindInstance` produces witnesses over Reals/Integers/Complexes, `BooleanMinimize` canonicalizes propositional formulas, and `Eliminate` removes variables from polynomial systems.",
            "Reach for it when the obligation is a *nonlinear real arithmetic* question that SMT solvers handle poorly or incompletely — parameter ranges for which an invariant holds, feasibility of a polynomial constraint set, an exact symbolic side-condition — and you want the full quantifier-free characterization, not one model. For bit-vectors, arrays, uninterpreted functions, or fast UNSAT cores use `z3`/`cvc5`.",
            "Input: a (quantified) formula plus a domain (`Reals`/`Integers`/`Complexes`). Output: an equivalent quantifier-free condition, a witness list, or `True`/`False`.",
            "`Resolve[ForAll[x, Element[x,Reals], x^2 + b x + 1 > 0], Reals]` → `-2 < b < 2`; `SatisfiabilityInstances[(p||q) && !p, {p,q}]` → `{{False,True}}`; `FindInstance[x^3+y^3==z^3+1 && x>0 && y>0, {x,y,z}, Integers]`; `Reduce[x^2+y^2==1 && x>y, {x,y}, Reals]`.",
            "Complete and exact over real closed fields (CAD), where SMT nonlinear-real support is partial; returns a symbolic condition, not merely a model; exact arithmetic throughout — no floating-point unsoundness.",
            "CAD is doubly-exponential in the number of variables — it stalls well before z3 does on large problems. No SMT theories (bit-vectors, arrays, UF), no proof certificate, no UNSAT core, no SMT-LIB input. Proprietary; shares the 2-process license seat pool (see the `wolfram` card).",
            &["z3", "cvc5", "yices", "bitwuzla", "wolfram", "sagemath"],
            "manual: Wolfram 15.0.0.0, $LicenseType Professional (/usr/local/bin/wolfram; MCP server \"Wolfram\")",
            "https://reference.wolfram.com/language/ref/Reduce.html",
        ),
        tool(
            "wolfram-modeling",
            "Wolfram System Modeler (Modelica) & control-systems modeling",
            FV,
            "system_modeling",
            "Equation-based Modelica system modeling with compiled simulation, plus state-space / transfer-function control models and Markov processes.",
            "The installed WSMLink paclet exposes 7,317 Modelica component models (`SystemModels[]`); `SystemModel[name]` loads one and `SystemModelSimulate` compiles it to a native executable and integrates it, returning a `SystemModelSimulationData` object you can sample at any time point. Alongside it the control-systems layer provides `StateSpaceModel`, `AffineStateSpaceModel`, `TransferFunctionModel`, and the structural predicates `ControllableModelQ`/`ObservableModelQ`/`TransferFunctionPoles`; `NDSolve`/`ParametricNDSolve` integrate ODE/DAE systems, and `DiscreteMarkovProcess`/`ContinuousMarkovProcess` model stochastic dynamics.",
            "Reach for it to model and simulate a *physical or control* system — a circuit, a plant, a mechanical assembly — or to check structural control properties (controllability, observability, pole placement/stability) before committing a design. It is simulation and structural analysis, NOT exhaustive verification: use `tla-plus`/`uppaal`/`storm` when you need to model-check a state space, and `dafny`/`why3` for program proofs.",
            "Input: a Modelica model name (or `.mo` source), or matrices/equations for a state-space, transfer-function, ODE, or Markov model. Output: a `SystemModelSimulationData` trajectory (sampleable), symbolic model objects, structural predicates, and exportable plots.",
            "`SystemModelSimulate[SystemModel[\"Modelica.Electrical.Analog.Examples.ChuaCircuit\"], {0, 20}]` then `sim[QuantityVariable[\"L.i\", \"ElectricCurrent\"]][10]` → `0.0599818`; `ControllableModelQ[StateSpaceModel[{{{0,1},{-2,-3}},{{0},{1}},{{1,0}},{{0}}}]]` → `True`; `TransferFunctionPoles[TransferFunctionModel[ss]]` → `{{{-2,-1}}}` (poles nested per input×output); `NDSolve[{y''[t]+0.3 y'[t]+Sin[y[t]]==0, y[0]==1, y'[0]==0}, y, {t,0,10}]`.",
            "Huge curated Modelica standard library already installed; acausal equation-based composition; compiles models to native code so simulations are fast; control-theoretic structural predicates and stochastic processes in the same language.",
            "Simulation and structural analysis, NOT model checking — it explores trajectories, not the whole state space, and proves nothing about all inputs. Proprietary. Simulation compiles a scratch executable under `/tmp/WolframSystemModeler-$USER-15.0/`. Shares the 2-process license seat pool (see the `wolfram` card).",
            &["uppaal", "storm", "tla-plus", "wolfram", "sagemath"],
            "manual: Wolfram 15.0.0.0 + WSMLink paclet, $LicenseType Professional (/usr/local/bin/wolfram; MCP server \"Wolfram\")",
            "https://reference.wolfram.com/language/ref/SystemModelSimulate.html",
        ),
    ]
}
