//! Security-protocol verifiers, GPU-kernel verifiers, and the
//! computer-algebra / logic / optimization solvers that round out the
//! formal-verification toolbox.

use super::{FV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- Security-protocol verifiers ----
        tool(
            "proverif",
            "ProVerif",
            FV,
            "security_protocol_verifier",
            "Symbolic cryptographic-protocol verifier (Dolev-Yao) proving secrecy and authentication for unbounded sessions.",
            "ProVerif models a protocol in the applied pi-calculus, compiles it to Horn clauses, and proves reachability/correspondence/equivalence properties against an active network attacker for an unbounded number of sessions.",
            "Reach for ProVerif to verify key-exchange / authentication protocols symbolically — secrecy, authentication, and observational-equivalence (privacy) goals — with a high degree of automation.",
            "Input: a `.pv` (applied-pi) model. Output: property true / false + an attack derivation, or 'cannot be proved'.",
            "`proverif protocol.pv` runs the analysis; `proverif -in pitype protocol.pv`; horn-clause resolution is fully automatic.",
            "Unbounded-session proofs; high automation; handles equivalence/privacy properties.",
            "Symbolic model only (no computational/probabilistic guarantees); may report false attacks; abstraction can loop.",
            &["tamarin"],
            "pacman: proverif (/usr/bin/proverif)",
            "https://bblanche.gitlabpages.inria.fr/proverif/",
        ),
        tool(
            "tamarin",
            "Tamarin Prover",
            FV,
            "security_protocol_verifier",
            "Symbolic protocol verifier based on multiset rewriting, strong on Diffie-Hellman and stateful protocols.",
            "Tamarin models protocols as multiset-rewriting rules and proves trace/equivalence properties (specified in a guarded fragment) using backward search, with built-in Diffie-Hellman/bilinear-pairing equational theories and an interactive proof GUI.",
            "Reach for Tamarin for protocols with rich algebraic operators (DH, signatures, XOR) or mutable global state, or when you want to guide the proof interactively when full automation stalls.",
            "Input: a `.spthy` theory (rules + lemmas). Output: each lemma verified / falsified (with an attack graph).",
            "`tamarin-prover --prove protocol.spthy` proves all lemmas; `tamarin-prover interactive protocol.spthy` opens the GUI.",
            "Powerful equational theories (DH); handles global state; interactive proof guidance.",
            "Proofs may need manual 'oracle'/lemma guidance; can be slow; symbolic model only.",
            &["proverif"],
            "pacman: tamarin-prover (/usr/bin/tamarin-prover)",
            "https://tamarin-prover.com",
        ),
        // ---- GPU-kernel verifiers ----
        tool(
            "gpuverify",
            "GPUVerify",
            FV,
            "gpu_verifier",
            "Static verifier for CUDA and OpenCL kernels, proving freedom from data races and barrier divergence.",
            "GPUVerify encodes a kernel into a sequential Boogie program over two arbitrary threads and uses an SMT solver to prove the absence of intra-group data races and barrier divergence.",
            "Reach for GPUVerify to check that a CUDA/OpenCL kernel is data-race- and barrier-divergence-free before trusting it — static, no test inputs required.",
            "Input: a `.cu`/`.cl` kernel + thread/group dimensions. Output: verified or a race/divergence witness.",
            "`gpuverify --local_size=256 --num_groups=64 kernel.cu` (CUDA) or `--local_size=... kernel.cl` (OpenCL).",
            "Sound race/divergence checks without test inputs; CUDA + OpenCL.",
            "Needs fixed thread dimensions/annotations; abstraction can yield false alarms; project is older/less maintained.",
            &["faial", "esbmc"],
            "pacman: gpuverify-git (/usr/bin/gpuverify)",
            "https://www.gpuverify.org",
        ),
        tool(
            "faial",
            "Faial",
            FV,
            "gpu_verifier",
            "Modern data-race-freedom analyzer for GPU kernels.",
            "Faial checks CUDA kernels for data-race freedom using a scalable, inference-based encoding to SMT, often handling kernels and thread configurations that defeat older tools.",
            "Reach for Faial as a newer alternative/cross-check to GPUVerify for proving GPU kernels race-free, especially when GPUVerify times out or rejects valid code.",
            "Input: a CUDA kernel source. Output: data-race-free or a counterexample.",
            "`faial-drf kernel.cu` runs the data-race-freedom check (the installed binary is `faial-drf`).",
            "Scales better than older tools on many kernels; focused, fast DRF analysis.",
            "Focused on data-race freedom (not full functional correctness); CUDA-centric.",
            &["gpuverify"],
            "pacman: faial-git (/usr/bin/faial-drf)",
            "https://gitlab.com/umb-svl/faial",
        ),
        // ---- Computer algebra / logic / optimization ----
        tool(
            "sagemath",
            "SageMath",
            FV,
            "computer_algebra",
            "Comprehensive open-source computer-algebra system built on Python, integrating PARI, GAP, Singular, Maxima, and more.",
            "Sage provides a unified Python interface to a vast range of mathematics — number theory, algebra, combinatorics, elliptic curves, cryptography, symbolic + numerical computation — wrapping many specialized backends.",
            "Reach for SageMath to compute and check mathematics underpinning a proof or crypto design: factor/solve, explore groups/rings/curves, sanity-check conjectures, or prototype number-theoretic attacks.",
            "Input: Sage/Python expressions or `.sage` scripts. Output: computed mathematical objects/values.",
            "`sage` opens the REPL; `sage script.sage` runs a script; `sage -python` for plain Python with Sage libs.",
            "Enormous breadth; one interface over many CAS backends; full programming language.",
            "Heavy install/startup; not a prover (computation, not machine-checked proof); occasional backend quirks.",
            &["wolfram", "msolve", "swi-prolog", "csdp"],
            "pacman: sagemath (/usr/bin/sage); sagemath-giac, sagetex",
            "https://www.sagemath.org",
        ),
        tool(
            "msolve",
            "msolve",
            FV,
            "computer_algebra",
            "Fast C library/CLI for solving multivariate polynomial systems via Gröbner bases.",
            "msolve computes Gröbner bases and uses them to decide ideal membership, count/real-solve polynomial systems, and perform real root isolation, with state-of-the-art performance.",
            "Reach for msolve when a problem reduces to polynomial-system solving — real solutions, ideal membership, parametric systems — and you need speed beyond a general CAS.",
            "Input: a polynomial system (msolve `.ms` format). Output: solutions / a Gröbner basis / real root isolation.",
            "`msolve -f system.ms -o solutions.txt`; flags select real solving vs. Gröbner-basis output.",
            "Very fast Gröbner/real-solving; clean CLI + C API; great for certified algebraic computations.",
            "Specialized (polynomial systems only); input format is low-level; not a general CAS.",
            &["sagemath", "csdp"],
            "pacman: msolve (/usr/bin/msolve)",
            "https://msolve.lip6.fr",
        ),
        tool(
            "wolfram",
            "Wolfram Language",
            FV,
            "computer_algebra",
            "Proprietary computer-algebra and technical-computing system (the Mathematica engine) spanning symbolic, numeric, and modeling mathematics in one language.",
            "The Wolfram Language evaluates a vast built-in library — symbolic algebra, equation/ODE/PDE solving, calculus, linear algebra, number theory, optimization, statistics, and arbitrary-precision numerics — through a uniform symbolic-rewriting kernel.",
            "Reach for Wolfram Language to model and check the mathematics under a proof or design: simplify symbolically, solve equation/ODE systems, integrate/sum, do matrix algebra or optimization, or sanity-check a closed form — broad coverage in one expression.",
            "Input: Wolfram Language expressions or `.wl`/`.wls`/`.m` scripts. Output: computed symbolic/numeric results (and exportable plots/data).",
            "`wolfram -script foo.wl` runs a script (on PATH); `/usr/local/Wolfram/Wolfram/15.0/Executables/wolframscript -code 'expr'` / `-file foo.wls`; also the live `Wolfram` MCP server (`mcp__Wolfram__WolframLanguageEvaluator`).",
            "Enormous built-in breadth (symbolic + numeric + modeling) in one language; exact/arbitrary precision; already wired as an MCP server for direct agent calls.",
            "Proprietary (needs license/activation); heavy kernel startup; not a machine-checked prover (computation, not proof); `wolframscript` not on PATH (use `wolfram -script` or the full Executables path).",
            &["sagemath", "msolve"],
            "manual: Wolfram 15.0.0.0 (/usr/local/bin/wolfram; wolframscript at /usr/local/Wolfram/Wolfram/15.0/Executables/; MCP server \"Wolfram\")",
            "https://reference.wolfram.com/language/",
        ),
        tool(
            "swi-prolog",
            "SWI-Prolog",
            FV,
            "logic_programming",
            "Mature ISO Prolog system with constraint (CLP) libraries, tabling, and broad library support.",
            "SWI-Prolog executes logic programs via SLD resolution with extensions — constraint solving (CLP(FD)/CLP(R)), tabling for termination, DCGs for parsing, and a large package ecosystem.",
            "Reach for SWI-Prolog for relational/constraint problems, rapid prototyping of inference rules, parsing with DCGs, or exploring search problems declaratively.",
            "Input: `.pl` programs + queries. Output: query solutions (with backtracking) / constraint solutions.",
            "`swipl` opens the REPL; `swipl script.pl`; `swipl -g main -t halt script.pl` runs a goal and exits.",
            "Robust, fast, feature-rich (CLP, tabling, DCG); great docs; embeddable.",
            "Not a verifier/prover of correctness; performance needs care; Prolog's cut/negation has pitfalls.",
            &["sagemath"],
            "pacman: swi-prolog (/usr/bin/swipl)",
            "https://www.swi-prolog.org",
        ),
        tool(
            "csdp",
            "CSDP",
            FV,
            "optimization_solver",
            "COIN-OR semidefinite-programming solver, used to produce sums-of-squares / Positivstellensatz certificates.",
            "CSDP solves semidefinite programs by a predictor-corrector interior-point method; in verification it backs SOS-based nonnegativity certificates (e.g. the `psatz`/`csdp` tactics in proof assistants).",
            "Reach for CSDP when a proof or analysis needs a semidefinite/SOS certificate — proving a polynomial is nonnegative, bounding a quadratic form — or for general SDP optimization.",
            "Input: an SDP in SDPA sparse format (`.dat-s`). Output: primal/dual solution + objective value.",
            "`csdp problem.dat-s` solves and writes the solution; typically invoked by an SOS/Positivstellensatz front-end.",
            "Reliable SDP interior-point solver; the standard SOS-certificate backend.",
            "SDP-specific; needs problems in SDPA format; numerical conditioning matters.",
            &["coin-or-clp", "msolve"],
            "pacman: coin-or-csdp (/usr/bin/csdp)",
            "https://github.com/coin-or/Csdp",
        ),
        tool(
            "coin-or-clp",
            "COIN-OR CLP",
            FV,
            "optimization_solver",
            "COIN-OR's open-source linear-programming (simplex/barrier) solver, with CBC for mixed-integer problems.",
            "CLP solves large linear programs by primal/dual simplex or interior-point; together with CBC (branch-and-cut) it handles mixed-integer programs, exposed via files and the CoinMP C API.",
            "Reach for COIN-OR CLP/CBC for linear and mixed-integer optimization — resource allocation, scheduling relaxations, LP-bounded analyses — when you want a dependency-free open-source solver.",
            "Input: an LP/MIP in `.mps`/`.lp` format. Output: an optimal solution + objective (or infeasible/unbounded).",
            "`clp model.mps -solve -solution out.txt`; the CoinMP library (pacman coin-or-mp) exposes the C API.",
            "Robust open-source LP/MIP; scriptable + embeddable; no license cost.",
            "Not a verifier; tuning needed on hard MIPs; commercial solvers are faster on the largest models.",
            &["csdp", "msolve"],
            "pacman: coin-or-clp (/usr/bin/clp); coin-or-mp",
            "https://github.com/coin-or/Clp",
        ),
    ]
}
