//! Security tools that analyze source, dependencies, and secrets-at-rest:
//! secret scanners, secrets-management/encryption, SAST, and supply-chain audit.

use super::{SEC, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- secret_scanner ----
        tool(
            "gitleaks",
            "Gitleaks",
            SEC,
            "secret_scanner",
            "Fast regex+entropy secret scanner for git history and filesystems.",
            "Scans a git repo's full history, a directory, or stdin for hardcoded secrets — API keys, tokens, private keys — using a large built-in rule set plus Shannon-entropy heuristics, with file/line/commit provenance.",
            "Reach for Gitleaks to gate commits/CI against leaked credentials, or to audit a repo's history before making it public; the fastest first-pass secret scan.",
            "Input: a git repo, directory, or stdin (+ optional `.gitleaks.toml`). Output: findings (table/JSON/SARIF) with secret type, file, line, commit.",
            "`gitleaks git .` scans full history; `gitleaks dir .` the working tree; `gitleaks stdin` piped input; `--report-format json --report-path leaks.json` to persist.",
            "Very fast; rich default rules; pre-commit/CI friendly; SARIF output; history-aware.",
            "Regex/entropy heuristics yield false positives without tuning; does not verify a secret is live (use TruffleHog for confirmation).",
            &["trufflehog", "detect-secrets"],
            "pacman: gitleaks (/usr/bin/gitleaks, v8.30.1)",
            "https://github.com/gitleaks/gitleaks",
        ),
        tool(
            "trufflehog",
            "TruffleHog",
            SEC,
            "secret_scanner",
            "Secret scanner that calls provider APIs to confirm a found credential is live.",
            "Scans git history, filesystems, S3 buckets, and more for secrets using detector-per-service logic, then optionally verifies each finding by making a real API call to the issuing service — distinguishing active leaks from revoked or test credentials.",
            "Reach for TruffleHog when you need to know whether a found secret is still valid, not just present — its live-verification step filters the noise that regex scanners leave behind.",
            "Input: a git repo (`file://`), filesystem path, or cloud source (+ optional `--config`). Output: findings with secret type, source, line, and a `Verified: true/false` flag.",
            "`trufflehog git file://.` scans the local repo; `trufflehog filesystem PATH --only-verified` reports only confirmed-live secrets; `--json` for machine output.",
            "Live credential verification eliminates most false positives; broad detector library (700+ service types); handles non-git sources.",
            "Slower than pure-regex scanners due to API calls; `--only-verified` misses revoked secrets that should still be rotated; network access required for verification.",
            &["gitleaks", "detect-secrets"],
            "pacman: trufflehog (/usr/bin/trufflehog, v3.95.5)",
            "https://github.com/trufflesecurity/trufflehog",
        ),
        tool(
            "detect-secrets",
            "detect-secrets",
            SEC,
            "secret_scanner",
            "Baseline-driven secret scanner with an audit workflow to track and suppress known findings.",
            "Scans source files for high-entropy strings and known secret patterns, producing or updating a `.secrets.baseline` JSON file that records each finding's state (potential/audited/false-positive); subsequent scans diff against the baseline so only new findings block CI.",
            "Reach for detect-secrets when you need a triage workflow — the baseline lets a team audit findings once, mark false positives, and suppress them durably without re-reviewing on every commit.",
            "Input: source files or a directory (+ existing `.secrets.baseline`). Output: a baseline JSON file; non-zero exit when new secrets exceed the baseline.",
            "`detect-secrets scan --all-files > .secrets.baseline` seeds the baseline; `detect-secrets audit .secrets.baseline` walks findings interactively; wire `detect-secrets-hook` in `.pre-commit-config.yaml` for CI gating.",
            "Baseline/triage workflow prevents alert fatigue; pre-commit integration; configurable plugins per secret type.",
            "Python-only tool (no native binary); no live-verification of found secrets; initial audit of a legacy baseline can be time-consuming.",
            &["gitleaks", "trufflehog"],
            "pacman: python-detect-secrets (/usr/bin/detect-secrets, v1.5.0)",
            "https://github.com/Yelp/detect-secrets",
        ),
        // ---- secrets_management ----
        tool(
            "sops",
            "SOPS",
            SEC,
            "secrets_management",
            "Structured-file encryptor that encrypts values while keeping keys plaintext — git-friendly secrets in YAML/JSON/ENV.",
            "SOPS encrypts only the values in YAML, JSON, INI, or ENV files (keys remain readable), using age, PGP, AWS KMS, GCP KMS, or Azure Key Vault as the key-encryption layer, controlled by a `.sops.yaml` creation-rules config; the result diffs cleanly in git.",
            "Reach for SOPS to store secrets (API keys, database passwords) in version control alongside their config — the encrypted file is reviewable, mergeable, and decryptable only by holders of the correct key material.",
            "Input: a plaintext YAML/JSON/ENV file + `.sops.yaml` recipient config. Output: in-place encrypted file with ciphertext values and a SOPS metadata block.",
            "`sops -e -i secrets.yaml` encrypts in place; `sops -d secrets.yaml` decrypts to stdout; `sops secrets.yaml` opens an editor session (decrypt → edit → re-encrypt); `.sops.yaml` specifies age/PGP/KMS recipients per path pattern.",
            "Git-friendly (diff shows changed keys, not ciphertext blobs); multiple KMS backends; structured-file awareness; in-editor round-trip.",
            "Adds a SOPS metadata block that pollutes the file; key rotation requires re-encryption of every file; KMS backends need cloud credentials at decrypt time.",
            &["age"],
            "pacman: sops (/usr/bin/sops, v3.13.1)",
            "https://github.com/getsops/sops",
        ),
        tool(
            "age",
            "age",
            SEC,
            "secrets_management",
            "Simple, modern file-encryption tool with a minimal format and no configuration.",
            "age encrypts arbitrary files to one or more recipients (X25519 public keys, SSH keys, or passphrases) using ChaCha20-Poly1305 + HKDF, producing a binary or ASCII-armored ciphertext; `age-keygen` generates keypairs; it is the encryption backend SOPS commonly delegates to.",
            "Reach for age when you need straightforward file encryption without GPG's complexity — encrypt a secret file to a teammate's public key, or use it as the key-encryption layer behind SOPS for repo secrets.",
            "Input: any file + one or more recipient public keys or a passphrase. Output: an encrypted `.age` file (binary) or ASCII-armored with `-a`.",
            "`age-keygen -o key.txt` generates a keypair; `age -r RECIPIENT_PUBKEY -o out.age plaintext.txt` encrypts; `age -d -i key.txt out.age` decrypts; `age -p -o out.age file` uses a passphrase.",
            "Minimal, auditable format; no config files; composable (stdin/stdout); native SSH-key recipients; fast ChaCha20-Poly1305.",
            "No signing (use minisign or GPG for that); single-purpose (file encryption only); no structured-value encryption (use SOPS for YAML/JSON).",
            &["sops"],
            "pacman: age (/usr/bin/age, v1.3.1)",
            "https://github.com/FiloSottile/age",
        ),
        // ---- sast ----
        tool(
            "semgrep",
            "Semgrep",
            SEC,
            "sast",
            "Multi-language pattern-matching SAST with a large registry of security rules and support for custom patterns.",
            "Semgrep matches source code against rules expressed as syntactic patterns (with metavariables and taint tracking), covering 30+ languages; the public registry (`--config auto`) ships thousands of security, correctness, and performance rules; custom rules are YAML and take minutes to write.",
            "Reach for Semgrep as the primary SAST gate for multi-language projects — `semgrep ci` integrates with CI/CD, `--config auto` picks the right rule packs per language, and custom rules let you encode project-specific security invariants.",
            "Input: source files or a directory + a rule config (`auto`, a registry slug, or a local `.yaml`). Output: findings with rule ID, file, line, severity, and fix suggestions; `--json` for machine consumption.",
            "`semgrep scan --config auto .` runs registry rules; `semgrep ci` in a CI context with diff-aware output; `--json --output findings.json` persists; `semgrep --validate rules/` checks custom rule syntax.",
            "Multi-language; fast incremental scans; enormous public rule registry; expressive custom rules; taint-tracking mode; free OSS tier.",
            "Pattern rules miss complex data-flow issues that path-sensitive analyzers catch; registry `auto` pulls remotely (needs network in CI); taint rules require Pro for inter-file analysis.",
            &["bandit", "cppcheck", "clang-static-analyzer", "clang-tidy"],
            "pipx: ~/.local/bin/semgrep (v1.166.0)",
            "https://semgrep.dev",
        ),
        tool(
            "bandit",
            "Bandit",
            SEC,
            "sast",
            "Python-specific AST-based security linter that checks for common vulnerability patterns.",
            "Bandit walks Python ASTs and applies a plugin-per-check architecture to flag issues like hardcoded passwords, use of insecure functions (`exec`, `pickle`, `subprocess` with `shell=True`), weak crypto, and SQL injection patterns, grouped by severity and confidence.",
            "Reach for Bandit to do a quick security sweep of any Python codebase — it integrates trivially into CI, flags the most common Python security antipatterns with concrete line references, and needs no build step.",
            "Input: a Python file or directory. Output: findings with test ID, description, severity (HIGH/MEDIUM/LOW), confidence, file, and line.",
            "`bandit -r PROJECT/` scans recursively; `-ll` reports only HIGH-severity/HIGH-confidence findings to cut noise; `-f json -o bandit.json` for machine output; `-t B605,B608` to run specific tests.",
            "Zero-config for Python; fast; CI-friendly; well-known test IDs (`B*`) for suppression; covers the Python security OWASP top issues.",
            "Python-only; no data-flow / taint tracking (use Semgrep for that); can't reason about runtime values; false positives on intentional dynamic constructs.",
            &["semgrep"],
            "pipx: ~/.local/bin/bandit (v1.9.4)",
            "https://github.com/PyCQA/bandit",
        ),
        tool(
            "cppcheck",
            "Cppcheck",
            SEC,
            "sast",
            "C/C++ static analyzer focused on memory errors and undefined behaviour, requiring no build system integration.",
            "Cppcheck performs flow-sensitive checks on C/C++ source — out-of-bounds access, null-pointer dereference, use-after-free, uninitialized variables, integer overflow, resource leaks — plus optional MISRA-C and CERT-C compliance via addons, without needing a compilation database (though one improves accuracy).",
            "Reach for Cppcheck for a fast, build-free security and correctness pass over C/C++ — it finds memory and UB issues that compilers miss, with no instrumentation overhead, and exports results in SARIF/XML for CI.",
            "Input: C/C++ source files, a directory, or a `compile_commands.json`. Output: findings with error ID, severity, file, and line; `--xml` or `--output-file` to persist.",
            "`cppcheck --enable=all --inconclusive --project=compile_commands.json` for full coverage; `--addon=misra` / `--addon=cert` for compliance checks; `--xml --output-file=results.xml` for CI ingestion.",
            "No build required; finds real memory/UB bugs compilers miss; MISRA/CERT addon support; fast; SARIF/XML output.",
            "Higher false-positive rate without a compile database; less path-sensitive than Clang SA; C/C++ only; does not verify security properties (use ProVerif/Tamarin for protocols).",
            &["clang-static-analyzer", "clang-tidy", "semgrep"],
            "pacman: cppcheck (/usr/bin/cppcheck, v2.21.0)",
            "https://cppcheck.sourceforge.io/",
        ),
        tool(
            "clang-static-analyzer",
            "Clang Static Analyzer",
            SEC,
            "sast",
            "Path-sensitive, symbolic-execution-based static analyzer for C, C++, and Objective-C built into LLVM.",
            "The Clang Static Analyzer performs interprocedural, path-sensitive analysis by symbolically executing code paths and tracking constraints, catching null-pointer dereferences, use-after-free, uninitialized reads, API misuse (CoreFoundation, POSIX, OpenBSD), and security-relevant patterns that flow-insensitive tools miss.",
            "Reach for the Clang Static Analyzer when Cppcheck misses a bug that depends on the sequence of branches taken — its symbolic execution follows paths through conditionals and function calls, so it finds deeper logic-dependent defects in C/C++ code.",
            "Input: C/C++/ObjC source compiled via `scan-build` (wraps the build command) or `clang-check --analyze`. Output: an HTML report (default) or `plist`/`sarif` files with path-annotated bug traces.",
            "`scan-build make` or `scan-build cargo build` wraps the build; `scan-build -o report/` sets the output directory; `clang-check --analyze file.c` for single-file analysis; `scan-build --use-analyzer clang` to pin the LLVM version.",
            "Path-sensitive symbolic execution catches deep, control-flow-dependent bugs; no false-positive explosion from simple pattern matching; integrated into LLVM (no extra install).",
            "Requires wrapping the actual build (no standalone mode for complex projects); analysis time scales with code complexity; reports can be verbose; C/C++/ObjC only.",
            &["cppcheck", "clang-tidy", "semgrep"],
            "pacman: clang (/usr/bin/scan-build, /usr/bin/clang-check, LLVM 22)",
            "https://clang-analyzer.llvm.org/",
        ),
        tool(
            "clang-tidy",
            "clang-tidy",
            SEC,
            "sast",
            "Clang-based linter and static checker with security, bugprone, and CERT/MISRA check packs.",
            "clang-tidy parses C/C++ with full compiler semantics and runs modular check packs — `clang-analyzer-*` (wraps Clang SA), `bugprone-*`, `cert-*`, `hicpp-*`, `cppcoreguidelines-*` — providing both security findings and fix-it auto-corrections; requires compile flags (a `compile_commands.json` or explicit `-I`/`-D`).",
            "Reach for clang-tidy to enforce coding standards and catch security-relevant bugs in C/C++ during development — its fix-it suggestions integrate with editors and CI, and the `cert-*`/`bugprone-*` packs cover the most actionable security patterns.",
            "Input: C/C++ source + compile flags (a `compile_commands.json` or inline `-- -Iinclude -DFOO`). Output: diagnostics with check name, file, line, column, and optional fix-it patches.",
            "`clang-tidy file.cpp -- -Iinclude` for a single file; `clang-tidy -p . file.cpp` uses `compile_commands.json`; `-checks='clang-analyzer-*,bugprone-*,cert-*'` selects packs; `--fix` applies suggested corrections in place.",
            "Full compiler semantics (no parse errors from headers); fix-it auto-corrections; composable check packs; editor/IDE integration via `clangd`.",
            "Needs accurate compile flags; slower than pattern scanners; fix-its occasionally wrong; check packs overlap with Clang SA (some duplication); C/C++ only.",
            &["cppcheck", "clang-static-analyzer", "semgrep"],
            "pacman: clang (/usr/bin/clang-tidy, LLVM 22.1.6)",
            "https://clang.llvm.org/extra/clang-tidy/",
        ),
        // ---- supply_chain_audit ----
        tool(
            "cargo-deny",
            "cargo-deny",
            SEC,
            "supply_chain_audit",
            "Policy-enforcement gate for Rust dependencies: advisories, bans, licenses, and allowed sources.",
            "cargo-deny reads a `deny.toml` policy and checks the entire Cargo dependency graph against four lenses simultaneously: RUSTSEC advisories (CVEs/unsound), banned crate versions or duplicates, license compatibility, and allowed source registries/git hosts — failing CI if any policy is violated.",
            "Reach for cargo-deny as the single CI gate for Rust supply-chain policy — it enforces CVE advisories, license allow-lists, and duplicate-crate bans in one pass, going well beyond what cargo-audit alone covers.",
            "Input: `Cargo.lock` + `deny.toml` policy file. Output: per-lens pass/fail with violation details; `--format json` for machine consumption.",
            "`cargo deny check` runs all four lenses; `cargo deny check advisories` for CVEs only; `cargo deny check licenses` for license policy; `cargo deny list` shows the full dependency tree with license/source info; `deny.toml` configures each lens.",
            "One tool for four supply-chain concerns (CVE + bans + licenses + sources); fast; CI-native Rust tooling; `deny.toml` is version-controlled policy-as-code.",
            "Rust/Cargo only; license detection can mis-classify dual-licensed or custom SPDX expressions; advisory database requires periodic refresh (`cargo deny fetch`).",
            &["cargo-audit"],
            "cargo: ~/.cargo/bin/cargo-deny (v0.19.5)",
            "https://github.com/EmbarkStudios/cargo-deny",
        ),
        tool(
            "cargo-audit",
            "cargo-audit",
            SEC,
            "supply_chain_audit",
            "Canonical RUSTSEC advisory scanner for Rust — checks Cargo.lock against the RustSec advisory database.",
            "cargo-audit reads `Cargo.lock`, fetches the RustSec advisory database, and reports any dependency versions with known CVEs or soundness issues, including severity, CVSS score, patched versions, and a link to the advisory; it is the de-facto standard for Rust CVE checking.",
            "Reach for cargo-audit for a quick, focused CVE check on a Rust project's locked dependencies — it is lighter than cargo-deny (CVE-only, no policy config needed) and the canonical first step before a full cargo-deny policy sweep.",
            "Input: `Cargo.lock` in the current workspace. Output: a list of vulnerable dependencies with advisory ID, severity, affected versions, and patched version; `--json` for machine output.",
            "`cargo audit` runs the advisory check; `cargo audit --json` for CI ingestion; `cargo audit fix --dry-run` previews safe version bumps; `~/.cargo/advisory-db/` caches the database.",
            "Zero-config; the standard RUSTSEC advisory scanner; fast; fix preview with `cargo audit fix`.",
            "CVE/soundness only — no license or ban policy (use cargo-deny for that); requires a network fetch of the advisory DB; can't fix yanked crates or breaking-change upgrades automatically.",
            &["cargo-deny"],
            "pacman: cargo-audit (/usr/bin/cargo-audit, v0.22.2)",
            "https://github.com/rustsec/rustsec",
        ),
        tool(
            "syft",
            "Syft",
            SEC,
            "supply_chain_audit",
            "SBOM generator that produces CycloneDX or SPDX bills of materials from directories, container images, and more.",
            "Syft catalogs a source tree, container image, OCI artifact, or archive by detecting all package ecosystems present (Cargo, npm, pip, Debian, RPM, Alpine, Go modules, and 20+ more) and emitting a Software Bill of Materials in SPDX-JSON, CycloneDX-JSON/XML, or Syft-native JSON; the SBOM is then consumed by Grype for vulnerability matching.",
            "Reach for Syft to produce a point-in-time SBOM of a project or container image — as attestation for a release, as input to Grype for CVE scanning, or to audit what is actually bundled before shipping.",
            "Input: a directory (`dir:.`), a container image name/OCI tarball, or an archive. Output: an SBOM file in the chosen format.",
            "`syft dir:.` catalogs the working directory; `syft IMAGE -o spdx-json > sbom.json` emits SPDX for a container image; `syft IMAGE -o cyclonedx-json > sbom.cdx.json` for CycloneDX; `syft IMAGE -o syft-json` for Syft's native format (most complete).",
            "Multi-ecosystem detection in one tool; multiple SBOM formats (SPDX, CycloneDX); integrates cleanly with Grype; works on images without a running container.",
            "SBOM generation only — no vulnerability matching itself (pair with Grype); detection coverage varies by ecosystem maturity; large images can be slow.",
            &["grype", "trivy"],
            "pacman: syft (/usr/bin/syft, v1.44.0)",
            "https://github.com/anchore/syft",
        ),
        tool(
            "grype",
            "Grype",
            SEC,
            "supply_chain_audit",
            "Vulnerability scanner that matches a Syft SBOM or a direct scan target against multiple CVE databases.",
            "Grype catalogs a directory, container image, or pre-generated SBOM and matches each detected package version against the Anchore vulnerability database (aggregating NVD, GHSA, RedHat, Ubuntu, Alpine, and more), reporting CVE ID, severity, CVSS, affected version range, and the fixed version where available.",
            "Reach for Grype to scan a project or container image for known CVEs — either by pointing it directly at a directory/image, or by piping in a Syft-generated SBOM for reproducible, attestation-linked vulnerability reports.",
            "Input: a directory (`dir:.`), a container image, or a pre-generated SBOM file (`sbom:sbom.json`). Output: a table (default) or JSON/SARIF findings with CVE ID, package, installed version, fixed version, and severity.",
            "`grype dir:.` scans the working directory; `grype IMAGE` scans a container image; `grype sbom:sbom.json` matches against an existing SBOM; `grype IMAGE -o json > vulns.json` for CI ingestion; `--fail-on high` exits non-zero for HIGH+ findings.",
            "Multi-database CVE matching; accepts Syft SBOMs for reproducibility; `--fail-on` severity threshold for CI gates; JSON/SARIF output; no daemon or server required.",
            "Vulnerability matching only — no license or policy enforcement (use cargo-deny for Rust policy); database freshness requires periodic `grype db update`; image scanning pulls layers (needs registry access or local tarball).",
            &["syft", "trivy"],
            "pacman: grype-bin (/usr/bin/grype, v0.114.0)",
            "https://github.com/anchore/grype",
        ),
    ]
}
