//! Security tools that scan running systems, images, endpoints, and files:
//! vulnerability scanners, IaC/container linting, TLS/SSH audit, network recon,
//! and malware scanning.

use super::{SEC, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- vulnerability_scanner ----
        tool(
            "trivy",
            "Trivy",
            SEC,
            "vulnerability_scanner",
            "All-in-one scanner for images, filesystems, repos, and IaC.",
            "Scans container images, filesystems, and git repos for known CVEs in OS packages and language dependencies, plus embedded secrets, license issues, and IaC/Dockerfile misconfigurations; can emit an SBOM.",
            "Reach for Trivy as the broad first-pass vulnerability scan of a built artifact or working tree — one command covering deps, secrets, and config.",
            "Input: an image ref, filesystem path, repo URL, or config dir. Output: findings (table/JSON/SARIF/CycloneDX) by severity.",
            "`trivy fs .` scans the working tree; `trivy image IMG` a container; `trivy repo URL`; `trivy config .` for IaC/Dockerfile misconfig.",
            "One tool for deps+secrets+IaC+SBOM; fast; CI-friendly; broad ecosystem coverage.",
            "Network fetch for the vuln DB on first run; image/IaC breadth over depth; not a source SAST.",
            &["grype", "syft", "nuclei"],
            "pacman: trivy (/usr/bin/trivy, v0.71.1)",
            "https://github.com/aquasecurity/trivy",
        ),
        tool(
            "nuclei",
            "Nuclei",
            SEC,
            "vulnerability_scanner",
            "Template-driven DAST scanner for live endpoints with 9 000+ community CVE/misconfig probes.",
            "Sends crafted HTTP requests defined by YAML templates against live targets, matching responses for CVEs, exposed admin panels, default credentials, and misconfigurations; templates are versioned and community-maintained in the nuclei-templates repo.",
            "Reach for Nuclei when you have a running service and need to probe it for known CVEs or misconfigurations using a battle-tested template library — it is DAST, so a live target is required.",
            "Input: one or more target URLs (flag -u or -l urls.txt), plus optional template filters (-tags, -severity). Output: matched findings with template ID, severity, and matched evidence.",
            "`nuclei -update-templates` refreshes the template library; `nuclei -u https://HOST` runs all templates; `nuclei -u https://HOST -tags cve,misconfig -severity critical,high` narrows scope.",
            "Vast template library covering CVEs and misconfig classes; fast concurrent engine; easy to extend with custom YAML templates; CI integration via `-o results.json`.",
            "Requires a live reachable target (DAST only); can generate significant traffic that triggers WAFs or rate limits; template quality varies; not a static code scanner.",
            &["trivy"],
            "pacman: nuclei (/usr/bin/nuclei, v3.9.0)",
            "https://github.com/projectdiscovery/nuclei",
        ),
        // ---- iac_container_security ----
        tool(
            "hadolint",
            "Hadolint",
            SEC,
            "iac_container_security",
            "Dockerfile best-practice linter with embedded ShellCheck for RUN instructions.",
            "Parses a Dockerfile into an AST and checks it against a curated rule set drawn from Docker best practices and CIS benchmarks; delegates all `RUN` shell fragments to ShellCheck so shell-injection and quoting bugs are caught inline.",
            "Reach for Hadolint whenever you author or review a Dockerfile — it catches image-bloat anti-patterns (no --no-install-recommends, COPY instead of ADD), insecure defaults (running as root, curl|bash), and shell bugs in a single fast pass.",
            "Input: a Dockerfile path (or piped stdin). Output: DL-code violations with rule ID, line, severity, and fix suggestion (text, JSON, SARIF, or CodeClimate format).",
            "`hadolint Dockerfile` prints violations to stdout; `hadolint --format json Dockerfile` emits machine-readable output; `hadolint --ignore DL3008 Dockerfile` suppresses noisy rules; exit code non-zero on any finding.",
            "Zero-dependency single binary; catches both security and maintainability issues; ShellCheck integration elevates shell-in-RUN quality; SARIF output for GitHub/GitLab CI integration.",
            "Dockerfile-only — does not scan docker-compose or Kubernetes YAML; cannot catch runtime privilege escalation; no CVE database.",
            &["trivy"],
            "pacman: hadolint (/usr/bin/hadolint, v2.14.0)",
            "https://github.com/hadolint/hadolint",
        ),
        // ---- tls_ssh_audit ----
        tool(
            "sslscan",
            "SSLScan",
            SEC,
            "tls_ssh_audit",
            "Fast C-based TLS/SSL cipher and certificate enumerator.",
            "Connects to a TLS endpoint and probes the full set of supported cipher suites, protocol versions (SSLv2 through TLS 1.3), session renegotiation behavior, compression, and certificate details; highlights deprecated or weak items in colour.",
            "Reach for SSLScan when you need a quick inventory of what a TLS endpoint accepts — detecting SSLv2/3/TLS1.0 support, RC4 or NULL ciphers, and self-signed or expired certificates in seconds.",
            "Input: HOST:PORT (defaults to 443 if no port given). Output: colour-coded table of protocol support, cipher suite list with key exchange and encryption details, and certificate info.",
            "`sslscan HOST:443` performs a full probe; `sslscan --no-colour HOST:443 > report.txt` for plain-text capture; `sslscan --xml=out.xml HOST:443` for machine-readable output.",
            "Very fast due to native C implementation; clear colour-coded output distinguishing weak from strong; XML output for automated parsing; no external dependencies at runtime.",
            "Enumerates offered ciphers but does not test protocol-level vulnerabilities like Heartbleed or ROBOT — use testssl.sh for those; may trigger IDS alerts on aggressive enumeration.",
            &["testssl", "ssh-audit"],
            "pacman: sslscan (/usr/bin/sslscan, v2.2.2)",
            "https://github.com/rbsec/sslscan",
        ),
        tool(
            "testssl",
            "testssl.sh",
            SEC,
            "tls_ssh_audit",
            "Comprehensive bash TLS auditor that tests cipher quality and protocol vulnerability classes.",
            "A pure-bash script that drives OpenSSL (with its own statically-linked binary when system OpenSSL is too new) to enumerate ciphers, test for high-profile TLS vulnerabilities (Heartbleed, BEAST, POODLE, DROWN, ROBOT, LUCKY13, BREACH, CRIME), check HSTS/HPKP headers, and grade the overall TLS posture.",
            "Reach for testssl.sh when you need thorough TLS hardening analysis beyond cipher enumeration — it actively probes for named CVEs and produces a graded report suitable for a security review or compliance audit.",
            "Input: HOST:PORT or a full HTTPS URL. Output: structured per-check results with PASS/WARN/FAIL/INFO ratings; optional JSON/CSV/HTML output via --jsonfile/--csvfile/--htmlfile.",
            "`testssl HOST:443` runs all checks; `testssl https://HOST` also works; `testssl --quiet --json --jsonfile out.json HOST:443` for CI pipelines; `testssl --severity HIGH HOST:443` limits to high+ findings.",
            "No binary dependencies beyond bash and a bundled OpenSSL; tests named vulnerability classes not just cipher lists; produces human-readable grades; widely trusted for compliance evidence.",
            "Slower than sslscan due to per-vulnerability probing; bash + bundled OpenSSL binary can be fragile on exotic platforms; generates more TCP connections which may trigger WAFs.",
            &["sslscan", "ssh-audit"],
            "pacman: testssl.sh (/usr/bin/testssl)",
            "https://testssl.sh",
        ),
        tool(
            "ssh-audit",
            "ssh-audit",
            SEC,
            "tls_ssh_audit",
            "SSH server and client configuration auditor benchmarked against hardening guides.",
            "Connects to an SSH server (or inspects client config) and evaluates the advertised key-exchange algorithms, host-key types, symmetric ciphers, and MACs against current hardening recommendations (Mozilla, BSI); flags deprecated or weak primitives with a clear recommendation.",
            "Reach for ssh-audit when hardening or auditing an sshd configuration — it tells you exactly which kex/cipher/MAC algorithms to remove from sshd_config and which host-key types to disable to meet modern security baselines.",
            "Input: HOST (and optional PORT, default 22); or client config path for client mode. Output: per-algorithm PASS/WARN/FAIL table with colour coding and concrete sshd_config remediation lines.",
            "`ssh-audit HOST` audits a remote sshd; `ssh-audit -p 2222 HOST` for non-default port; `ssh-audit --level warn HOST` shows only warnings and failures; `ssh-audit -j HOST` emits JSON for automated ingestion.",
            "Purpose-built for SSH — far more detail than generic TLS scanners; tracks algorithm deprecations against evolving hardening guides; JSON output; no root or agent access required.",
            "SSH-only — does not cover TLS endpoints; client-mode analysis requires local access to ssh_config; cannot test authentication bypass vulnerabilities.",
            &["sslscan", "testssl"],
            "pacman: ssh-audit (/usr/bin/ssh-audit, v3.3.0)",
            "https://github.com/jtesta/ssh-audit",
        ),
        // ---- network_recon ----
        tool(
            "nmap",
            "Nmap",
            SEC,
            "network_recon",
            "The canonical port scanner with service fingerprinting and NSE scripting.",
            "Sends crafted TCP/UDP probes to enumerate open ports, identifies running service versions via banner analysis and the nmap-service-probes database, detects operating systems, and runs Nmap Scripting Engine (NSE) scripts for deeper checks including authentication, enumeration, and vulnerability detection.",
            "Reach for Nmap when you need to map what is listening on a host or network — from a quick open-port census to a deep service-version and vulnerability scan using the NSE library.",
            "Input: one or more host specs (IP, CIDR, hostname), port ranges, and scan-type flags. Output: per-host/port table of state, service, version, and script output; optionally in XML/grepable/JSON (with nmap-formatter).",
            "`nmap -sV -sC HOST` does service detection plus default NSE scripts; `nmap -p- HOST` scans all 65 535 ports; `nmap -A -T4 HOST` enables OS detection + traceroute + scripts; `nmap -oX out.xml HOST` for XML output.",
            "Extremely powerful and flexible; vast NSE script library; OS and service fingerprinting; industry-standard output formats; active community; IPv6 support.",
            "Requires root for SYN/OS scans; aggressive scans can crash fragile services; timing must be tuned per network; not designed for continuous monitoring at scale.",
            &["ncat", "socat", "tcp-cutter"],
            "pacman: nmap (/usr/bin/nmap, v7.99)",
            "https://nmap.org",
        ),
        tool(
            "ncat",
            "Ncat",
            SEC,
            "network_recon",
            "Modern netcat from the Nmap project with TLS, proxy, and broker support.",
            "A full-featured reimplementation of netcat that can open TCP/UDP connections, listen on ports, transfer data, chain proxies, and optionally wrap connections in TLS — all from one binary; included in the nmap package.",
            "Reach for Ncat when you need a reliable netcat for manual service interaction, port forwarding, file transfer, or setting up a listener for bind/reverse shells in a controlled test environment.",
            "Input: HOST PORT for connect mode; -l for listen mode; optional --ssl for TLS. Output: raw stdio bridged to the network socket; exit code reflects connection success.",
            "`ncat -lvp 4444` listens on TCP 4444; `ncat HOST PORT` connects; `ncat --ssl HOST 443` TLS connect; `ncat -e /bin/bash HOST PORT` exec mode (test environments only); `ncat --broker -l PORT` multi-client broker.",
            "Part of nmap so always available alongside it; TLS support without openssl invocation; proxy chaining; IPv6; broker mode for fan-out connections.",
            "Not suitable for production use in security-sensitive paths; exec mode is dangerous if exposed; no built-in encryption for data at rest.",
            &["nmap", "socat", "tcp-cutter"],
            "pacman: nmap (/usr/bin/ncat, v7.99)",
            "https://nmap.org/ncat/",
        ),
        tool(
            "socat",
            "socat",
            SEC,
            "network_recon",
            "Multipurpose bidirectional socket relay supporting pty, TLS, and Unix sockets.",
            "Bridges two arbitrary data streams — TCP, UDP, Unix domain sockets, ptys, files, pipes, or TLS — making it the Swiss Army knife for network plumbing in test and diagnostic scenarios; supports fork mode for persistent listeners.",
            "Reach for socat when you need flexible socket bridging that goes beyond netcat — TLS-wrapping a plaintext service, exposing a Unix socket over TCP, relaying traffic through a jump host, or attaching a pty to a network connection.",
            "Input: two address specifications (e.g. TCP-LISTEN:PORT, OPENSSL:host:port, UNIX-CONNECT:/path/to.sock, PTY). Output: bytes relayed between the two endpoints; exit on EOF or error.",
            "`socat TCP-LISTEN:8080,fork TCP:host:80` TCP relay with per-connection fork; `socat OPENSSL-LISTEN:443,cert=srv.pem,fork TCP:localhost:80` TLS-terminating proxy; `socat PTY,link=/dev/ttyV0 TCP:HOST:PORT` pty-to-network bridge.",
            "Handles more socket types than any other tool; TLS without separate certs setup; fork mode for concurrent connections; pty bridging for serial-over-network scenarios.",
            "Syntax is verbose and non-intuitive; easy to create insecure relay configurations; no built-in authentication beyond TLS client certs.",
            &["ncat", "nmap", "tcp-cutter"],
            "pacman: socat (/usr/bin/socat)",
            "http://www.dest-unreach.org/socat/",
        ),
        tool(
            "tcp-cutter",
            "cutter (tcp-cutter)",
            SEC,
            "network_recon",
            "Root-level tool that abruptly terminates live TCP connections via RST injection.",
            "Uses raw sockets to inject forged TCP RST segments into both endpoints of a live connection, causing immediate teardown without waiting for application-level close; designed for firewall and router administrators who need to abort stuck or suspicious TCP sessions.",
            "Reach for tcp-cutter when a TCP connection needs to be forcibly terminated from outside the application — dropping a stuck SSH session, aborting an unauthorized transfer, or testing connection-reset behaviour in network equipment.",
            "Input: source IP and optionally source port, destination IP and optionally destination port (all four tuple elements identify the connection to kill). Output: confirmation or error; requires root for raw socket access.",
            "`sudo tcp-cutter IP` kills all TCP connections to/from IP; `sudo tcp-cutter SRC_IP SRC_PORT DST_IP DST_PORT` kills one specific connection; no flags for dry-run — execution is immediate.",
            "Immediately terminates connections without application cooperation; useful on routers/firewalls where iptables REJECT is unavailable; minimal attack surface.",
            "Requires root; targets must be on a locally reachable path (you must be able to spoof RSTs); not the GUI tool Cutter from Rizin/RE world — that is a separate package.",
            &["nmap", "ncat", "socat"],
            "pacman: cutter (/usr/bin/tcp-cutter, v1.04)",
            "http://www.digitage.co.uk/digitage/software/linux-security/cutter",
        ),
        // ---- malware_scanner ----
        tool(
            "clamav",
            "ClamAV",
            SEC,
            "malware_scanner",
            "Open-source AV engine with a continuously updated signature database.",
            "Scans files and directories against a signature database of known malware, viruses, trojans, and phishing content; the freshclam daemon keeps the DB current; clamd runs as a persistent daemon for high-throughput scanning; clamscan is the one-shot CLI.",
            "Reach for ClamAV when you need to screen untrusted files, email attachments, or uploaded content for known malware signatures — particularly in automated pipelines or when operating on a budget without commercial AV.",
            "Input: file path(s) or directory tree with -r; optional --move or --remove for quarantine/deletion. Output: per-file FOUND/OK verdict with malware name; summary statistics; exit code 1 if any infection found.",
            "`freshclam` updates the signature DB; `clamscan -r --infected PATH` scans recursively and prints only infected files; `clamscan -r --infected --move=/quarantine PATH` quarantines hits; `clamscan --log=scan.log -r PATH` for audit trails.",
            "Free and open-source; broad signature coverage including email-borne threats; clamd daemon mode for low-latency repeated scans; integrates with mail servers (Postfix, Sendmail).",
            "Signature-based — misses novel malware and zero-days; higher false-negative rate than commercial solutions; DB updates require network access; slower than commercial AV on large trees.",
            &["yara"],
            "pacman: clamav (/usr/bin/clamscan, v1.5.2)",
            "https://www.clamav.net",
        ),
        tool(
            "yara",
            "YARA",
            SEC,
            "malware_scanner",
            "Pattern-matching rule engine for malware identification — effectively grep for malware.",
            "Evaluates user-authored rules consisting of string patterns (hex, text, regex) combined with boolean conditions against files, memory dumps, or process memory; rules can encode complex multi-indicator logic, making it the standard tool for custom malware family detection and threat hunting.",
            "Reach for YARA when you need to hunt for custom indicators of compromise, identify malware families by structural characteristics, or write detection rules for threats not covered by ClamAV signatures.",
            "Input: a rule file (.yar or pre-compiled .yarc) and a target (file path, directory, or process PID). Output: rule name and matched file/offset for each hit; exit code 0 if any match.",
            "`yara rules.yar TARGET` matches rules against a file; `yara -r rules.yar DIR` recurses a directory; `yarac rules.yar out.yarc` pre-compiles rules for faster repeated use; `yara -p 4 rules.yar DIR` uses 4 threads.",
            "Extremely flexible rule language supporting hex, text, regex, and boolean logic; pre-compilation for performance; process memory scanning; the de-facto standard in threat intelligence and malware research.",
            "Rules must be authored manually — no built-in signature DB; effectiveness depends entirely on rule quality; false positives require rule tuning; process memory scanning requires root.",
            &["clamav"],
            "pacman: yara (/usr/bin/yara, v4.5.6)",
            "https://virustotal.github.io/yara/",
        ),
    ]
}
