//! Security tools for binaries: coverage-guided fuzzers, ELF/binary inspection
//! and hardening, reverse-engineering frameworks, and digital forensics.

use super::{SEC, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- fuzzer ----
        tool(
            "cargo-fuzz",
            "cargo-fuzz",
            SEC,
            "fuzzer",
            "Rust-native coverage-guided fuzzing via libFuzzer, integrated with cargo.",
            "cargo-fuzz wraps libFuzzer as a cargo subcommand: it scaffolds a `fuzz/` workspace, compiles harnesses with instrumentation and sanitizers, and drives the fuzzer in-process — no separate build system needed. AddressSanitizer and UndefinedBehaviorSanitizer are enabled by default.",
            "Reach for cargo-fuzz when you want to fuzz a Rust library target with minimal boilerplate: it owns the harness template, the instrumented build, and corpus management in a single `cargo fuzz run T` invocation.",
            "Input: a Rust harness function (`fuzz_target!` macro) consuming arbitrary bytes. Output: corpus of interesting inputs + crash/timeout artifacts written to `fuzz/artifacts/<target>/`.",
            "`cargo fuzz init` scaffolds the fuzz workspace; `cargo fuzz add T` generates a new harness; `cargo fuzz run T` starts fuzzing; `cargo fuzz fmt T` and `cargo fuzz coverage T` inspect results.",
            "Seamlessly integrated with cargo; ASan/UBSan on by default; corpus is plain files; supports `#[no_std]` targets.",
            "Requires nightly Rust (unstable `-Z` flags); Linux/macOS only (no Windows libFuzzer); single-process throughput lower than fork-server fuzzers for heavy targets.",
            &["aflplusplus", "honggfuzz", "asan"],
            "cargo: ~/.cargo/bin/cargo-fuzz (v0.13.1)",
            "https://github.com/rust-fuzz/cargo-fuzz",
        ),
        tool(
            "aflplusplus",
            "AFL++",
            SEC,
            "fuzzer",
            "The leading coverage-guided greybox fuzzer with a rich mutator/instrumentation ecosystem.",
            "AFL++ extends the original AFL with LLVM-based persistent-mode instrumentation, CMPLOG, MOpt adaptive scheduling, custom mutators (Python/Rust/C API), and multiple coverage models (edge, path, context). Fork-server execution keeps harness startup cost amortised across millions of executions.",
            "Reach for AFL++ when fuzzing C/C++ (or any compiled target) at scale: it offers the best time-to-first-crash on complex parsers, network protocols, and format handlers, and its `@@` file-substitution model supports almost any target without source changes.",
            "Input: a seed corpus directory (`-i in`) and an instrumented executable (via `afl-cc`). Output: `out/queue/` (interesting inputs), `out/crashes/` (crash-triggering inputs), `out/hangs/`, and an `out/fuzzer_stats` summary.",
            "`afl-cc -o t t.c` instruments the target; `afl-fuzz -i in -o out -- ./t @@` starts a single instance; `afl-whatsup out/` monitors multiple instances; `afl-cmin -i corpus -o min -- ./t @@` minimises a corpus.",
            "Best-in-class mutation engine; low overhead fork-server; parallel multi-instance (`-M`/`-S`); binary-only mode via QEMU (`-Q`) or Frida (`-O`).",
            "C/C++ toolchain required for instrumentation; binary-mode throughput 5-10x lower than source; large output trees require periodic `afl-cmin` sweeps.",
            &["cargo-fuzz", "honggfuzz", "asan"],
            "pacman: afl++ (/usr/bin/afl-fuzz, v5.00c)",
            "https://aflplus.plus",
        ),
        tool(
            "honggfuzz",
            "honggfuzz",
            SEC,
            "fuzzer",
            "Google's hardware-counter-feedback fuzzer with first-class persistent-mode support.",
            "honggfuzz uses hardware performance counters (branch edges via `perf_event_open`) and sanitizer feedback to drive mutation, giving it signal beyond basic edge coverage. Its persistent mode (`HF_ITER`/`LLVMFuzzerTestOneInput`) keeps the target in-process for extremely high throughput — millions of iterations per second on tight loops.",
            "Reach for honggfuzz when you want hardware-assisted feedback beyond LLVM edge coverage, or when building a persistent-mode harness (share state across iterations) for maximum throughput on CPU-bound targets.",
            "Input: a seed corpus directory (`-i input`) and an instrumented binary compiled with `hfuzz-cc`. Output: crash/hang files in the working directory, plus real-time statistics on the terminal.",
            "`hfuzz-cc -o target target.c` instruments with honggfuzz feedback; `honggfuzz -i input -- ./target ___FILE___` runs file-based fuzzing; for persistent mode, the harness loops on `HF_ITER(&buf, &len)` with no `___FILE___` argument.",
            "Hardware-counter feedback catches coverage invisible to compiler instrumentation; easy persistent mode; low per-iteration overhead; good signal on crypto/compression targets.",
            "Requires Linux with `perf_event_open` privileges (or macOS with dtrace); persistent-mode harnesses require manual porting; smaller community than AFL++.",
            &["cargo-fuzz", "aflplusplus", "asan"],
            "pacman: honggfuzz-git (/usr/bin/honggfuzz, v2.6)",
            "https://github.com/google/honggfuzz",
        ),
        // ---- binary_analysis ----
        tool(
            "binutils",
            "GNU binutils",
            SEC,
            "binary_analysis",
            "The classic ELF inspection + disassembly toolkit (objdump/readelf/nm/strings).",
            "A suite of low-level binary utilities: objdump disassembles and dumps sections, readelf decodes ELF headers/segments/symbols/relocations, nm lists symbols, strings extracts printable runs — the first-stop kit for understanding an unknown binary.",
            "Reach for binutils to disassemble a function, inspect ELF headers/relocations/symbols, or pull strings from a binary before deeper RE; ubiquitous and scriptable.",
            "Input: an ELF object/executable/library. Output: textual disassembly, header/symbol dumps, or extracted strings.",
            "`objdump -d BIN` disassembles; `readelf -a BIN` dumps all ELF structure; `nm -D LIB` lists dynamic symbols; `strings -n8 BIN` extracts strings.",
            "Ubiquitous; scriptable; no setup; pairs with gdb for live analysis.",
            "Static/textual only (no interactivity); raw output is dense; not a decompiler.",
            &["checksec", "patchelf", "gdb"],
            "pacman: binutils (/usr/bin/{objdump,readelf,nm,strings}, v2.46)",
            "https://www.gnu.org/software/binutils/",
        ),
        tool(
            "checksec",
            "checksec",
            SEC,
            "binary_analysis",
            "Reports ELF hardening mitigations: RELRO, NX, PIE, stack-canary, and Fortify.",
            "checksec parses ELF headers and section flags to determine which exploit-mitigation features were compiled into or linked into a binary. It covers Full/Partial RELRO, NX (no-execute stack), PIE (position-independent executable), stack-smashing protection, Fortify Source, and RPATH/RUNPATH hygiene — producing a colour-coded summary per file or per running process.",
            "Reach for checksec when auditing a binary's hardening posture before a penetration test or after a build, to confirm that required mitigations (PIE, Full RELRO, stack canary) are present and that no RPATH regressions were introduced.",
            "Input: an ELF file path, a directory, or `--proc-all` for live processes. Output: a table of mitigation status per binary (ENABLED/DISABLED/PARTIAL).",
            "`checksec --file=BIN` checks a single binary; `checksec --proc-all` audits every running process; `checksec --dir=/usr/bin` surveys a directory; `checksec --json --file=BIN` emits machine-readable output.",
            "Zero dependencies beyond bash + readelf; covers all common ELF mitigations; process-mode shows live state; JSON output for CI integration.",
            "Shell script: not suitable for high-volume batch scanning (slow per-file); no PE/Mach-O support; does not verify runtime enforcement (e.g. SELinux).",
            &["binutils", "patchelf"],
            "pacman: checksec (/usr/bin/checksec)",
            "https://github.com/slimm609/checksec.sh",
        ),
        tool(
            "patchelf",
            "patchelf",
            SEC,
            "binary_analysis",
            "Rewrites ELF interpreter, RPATH, and shared-library dependencies in place.",
            "patchelf edits the dynamic-linking metadata of an ELF binary without recompilation: it can change the ELF interpreter (`PT_INTERP`), set or clear `DT_RPATH`/`DT_RUNPATH`, add or replace `DT_NEEDED` entries, and shrink the `PT_NOTE` segment. It is the standard tool for portability patching (NixOS), RE relocation, and fixing hard-coded loader paths in distributed binaries.",
            "Reach for patchelf when a binary refuses to run because its embedded interpreter path or RPATH is wrong, or when you need to redirect a `DT_NEEDED` dependency to a different `.so` without rebuilding from source.",
            "Input: an ELF executable or shared library. Output: the same file modified in place (optionally `--output FILE` for a copy).",
            "`patchelf --print-rpath ELF` reads the current RPATH; `patchelf --set-interpreter /lib/ld-linux.so.2 ELF` changes the loader; `patchelf --replace-needed libfoo.so.1 libfoo.so.2 ELF` redirects a dependency; `patchelf --remove-rpath ELF` strips embedded paths.",
            "Non-destructive by default with `--output`; handles segment resizing automatically; essential for NixOS/cross-root RE workflows.",
            "Modifies binary in place (risk of corruption without `--output`); cannot patch statically linked executables; does not verify that new paths/libraries exist.",
            &["binutils", "checksec"],
            "pacman: patchelf (/usr/bin/patchelf, v0.18.0)",
            "https://github.com/NixOS/patchelf",
        ),
        // ---- reverse_engineering ----
        tool(
            "radare2",
            "radare2",
            SEC,
            "reverse_engineering",
            "A scriptable command-line RE framework with disassembly, debugging, and a full binary-analysis tool suite.",
            "radare2 is a complete reverse-engineering platform: its core (`r2`) provides an interactive REPL for analysis, disassembly, patching, and debugging (native + remote via GDB/LLDB stubs). Companion tools handle every binary-analysis sub-task — `rabin2` reads headers/strings/imports, `radiff2` diffs two binaries, `rasm2` assembles/disassembles single instructions, `ragg2` generates shellcode, `rahash2` computes block hashes, and `rax2` converts between number bases.",
            "Reach for radare2 when you need a fully scriptable RE environment from the shell: automate analysis with `r2pipe` (Python/JS/Rust), diff patched binaries with `radiff2`, or script shellcode generation without a GUI.",
            "Input: any ELF/PE/Mach-O/raw binary. Output: disassembly listings, control-flow graphs (in ASCII, dot, or JSON), symbol tables, cross-references, and patch output.",
            "`r2 -A BIN` opens with full analysis (`aaa`); inside r2: `afl` lists functions, `pdf@main` disassembles main, `VV` shows a graph view; `r2 -d BIN` starts a debugger session; `rabin2 -I BIN` prints binary info; `rabin2 -z BIN` extracts strings; `radiff2 a b` shows bytewise differences; `rasm2 -d -a x86 -b 64 '4831c0'` decodes bytes.",
            "Full suite in one package; scriptable via `r2pipe`; works on ELF/PE/Mach-O/firmware blobs; active development + extensive plugin ecosystem.",
            "Steep learning curve (terse command language); interactive UI is text-only (use Cutter for a GUI); analysis quality below Ghidra/IDA for complex binaries.",
            &["rizin", "cutter", "binutils"],
            "pacman: radare2 (/usr/bin/{r2,rabin2,radiff2,rasm2,ragg2,rahash2,rax2}, v6.1.4)",
            "https://rada.re",
        ),
        tool(
            "rizin",
            "Rizin",
            SEC,
            "reverse_engineering",
            "A community fork of radare2 with a cleaner C API, improved UX, and active maintenance.",
            "Rizin is a hard fork of radare2 that keeps the same interactive command language but ships a reorganised C library (librizin), stricter API boundaries, improved documentation, and a focus on correctness. It is the backend powering Cutter's GUI. Commands (`rizin -A BIN`, `afl`, `pdf@main`) are largely identical to radare2, so radare2 knowledge transfers directly.",
            "Reach for Rizin when you prefer its cleaner codebase or when developing plugins/integrations against its stable C API, or when you want a CLI companion to Cutter's GUI.",
            "Input: ELF/PE/Mach-O/raw binary. Output: same as radare2 — disassembly, CFGs, symbols, cross-references.",
            "`rizin -A BIN` opens with analysis; `rizin -c 'aaa;pdf@main' -q BIN` non-interactively disassembles main; `rizin -d BIN` debugs; `rz-bin -I BIN` (Rizin's rabin2 equivalent) reads binary metadata.",
            "API-cleaner than radare2; actively maintained; backs Cutter; same command language means zero re-learning.",
            "Smaller plugin ecosystem than radare2; some radare2 plugins are not ported; analysis depth still below Ghidra for heavily optimised binaries.",
            &["radare2", "cutter"],
            "pacman: rizin (/usr/bin/rizin)",
            "https://rizin.re",
        ),
        tool(
            "cutter",
            "Cutter (rizin)",
            SEC,
            "reverse_engineering",
            "A Qt-based graphical RE frontend over Rizin, with a decompiler and integrated debugger.",
            "Cutter is the official GUI for Rizin: it renders disassembly as an interactive graph, integrates the rz-ghidra decompiler plugin for C pseudocode, hosts a debugger panel, and exposes Rizin's full analysis engine through a visual interface. All Rizin commands remain available via the built-in console. NOTE: Cutter is a reverse-engineering GUI — it is distinct from the `tcp-cutter` network traffic-interception tool.",
            "Reach for Cutter when you want a graphical disassembly/decompiler view for binary RE — especially when analysing complex control flow, recovering variable names, or navigating large binaries where a CLI REPL would be unwieldy.",
            "Input: ELF/PE/Mach-O/raw binary opened via the file dialog or `cutter BIN`. Output: graphical disassembly view, decompiled C pseudocode (rz-ghidra), cross-reference browser, and strings/imports panels.",
            "`cutter BIN` opens the binary in the GUI; the decompiler panel activates automatically with rz-ghidra installed; Rizin commands are available in the console tab; analysis depth is controlled via the initial analysis dialog.",
            "Graphical CFG rendering; integrated rz-ghidra decompiler; full Rizin power accessible via console; active development.",
            "Requires a display server (no headless use); rz-ghidra decompiler quality below Ghidra native; startup slower than CLI rizin.",
            &["rizin", "radare2"],
            "pacman: rz-cutter (/usr/bin/cutter, v2.4.1)",
            "https://cutter.re",
        ),
        // ---- forensics ----
        tool(
            "binwalk",
            "Binwalk",
            SEC,
            "forensics",
            "Firmware and binary blob analysis: signature scanning, entropy analysis, and embedded-file extraction.",
            "Binwalk scans a file for known magic-byte signatures (compressed archives, filesystems, kernels, certificates, etc.) using a curated signature database, plots entropy to locate compressed/encrypted regions, and extracts identified components — recursively if needed. It is the standard tool for unpacking firmware images, UEFI blobs, and any opaque binary containing embedded sub-files.",
            "Reach for Binwalk when analysing firmware images, UEFI/BIOS dumps, or any opaque binary where you suspect embedded filesystems, compressed archives, or certificates; the entropy plot quickly flags encrypted regions worth further investigation.",
            "Input: any file (firmware image, blob, executable). Output: a table of detected signatures with offsets, an entropy plot (PNG with `-E`), and extracted files in `_FILE.extracted/` (with `-e`).",
            "`binwalk FILE` scans and prints signature matches; `binwalk -e FILE` extracts detected components; `binwalk -Me FILE` extracts recursively; `binwalk -E FILE` plots entropy; `binwalk -B FILE` shows raw byte values.",
            "Comprehensive signature DB covering hundreds of firmware formats; recursive extraction; entropy visualisation; scriptable Python API.",
            "False positives on data blobs; recursive extraction can produce deeply nested directories; does not interpret filesystem semantics (use sleuthkit after extraction).",
            &["sleuthkit", "exiftool"],
            "pacman: binwalk (/usr/bin/binwalk, v3.1.0)",
            "https://github.com/ReFirmLabs/binwalk",
        ),
        tool(
            "sleuthkit",
            "The Sleuth Kit",
            SEC,
            "forensics",
            "Disk-image forensics: partition layout, filesystem traversal, deleted-file recovery, and inode extraction.",
            "The Sleuth Kit (TSK) provides a layered CLI for forensic analysis of raw disk images, E01 (EnCase) evidence files, and block devices. It operates at the volume (`mmls`), filesystem (`fls`, `fsstat`), and inode (`icat`, `ils`) layers, enabling non-destructive read-only analysis and data recovery without mounting the image.",
            "Reach for The Sleuth Kit when you need to examine a raw disk image or forensic evidence file: recover deleted files, list directory contents of an unmounted filesystem, extract a specific file by inode, or verify filesystem metadata without risking contamination by mounting.",
            "Input: a raw/E01 disk image or block device path, plus optional partition offset (`-o`). Output: partition tables, file listings with metadata, recovered file data written to a directory.",
            "`mmls IMG` shows the partition layout (offsets for `-o`); `fls -r -o OFFSET IMG` lists all files recursively including deleted ones; `tsk_recover -e -o OFFSET IMG OUTDIR` recovers all allocated and deleted files; `icat -o OFFSET IMG INODE` extracts a specific file by inode number.",
            "Read-only non-destructive analysis; handles deleted/unallocated files; supports raw, E01, and split images; scriptable via TSK framework API.",
            "CLI output is terse and requires forensic knowledge to interpret; no GUI (use Autopsy for graphical analysis); limited support for newer filesystems (Btrfs/ZFS).",
            &["binwalk", "exiftool"],
            "pacman: sleuthkit (/usr/bin/{mmls,fls,tsk_recover,icat})",
            "https://www.sleuthkit.org",
        ),
        tool(
            "exiftool",
            "ExifTool",
            SEC,
            "forensics",
            "Read, write, and strip metadata across images, documents, audio, and video files.",
            "ExifTool is a Perl library and CLI that reads and writes metadata in over 100 file formats — EXIF, IPTC, XMP, GPS coordinates, creation timestamps, camera make/model, document author, and hundreds of proprietary tag families. In forensics it is used to extract provenance information, verify or spoof timestamps, and strip identifying metadata before publishing files.",
            "Reach for ExifTool when you need to extract, verify, or sanitise metadata from media or document files: recover the original capture location from a photo, strip author/GPS data before sharing, or compare metadata between two versions of a file.",
            "Input: any supported file (JPEG, PNG, PDF, DOCX, MP4, RAW, etc.). Output: a key=value listing of all metadata tags, or the modified file when writing.",
            "`exiftool FILE` reads all metadata; `exiftool -json FILE` emits JSON; `exiftool -all= FILE` strips all metadata in place (destructive — use `-all= -o clean.jpg FILE` for a copy); `exiftool -GPSLatitude -GPSLongitude FILE` extracts GPS coordinates; `exiftool -r DIR` processes a directory recursively.",
            "Supports 100+ formats; extremely comprehensive tag coverage; non-destructive read by default; scriptable; `-r` recursive batch mode.",
            "Perl dependency; stripping metadata modifies the file (use `-o` for a copy); does not analyse binary structure or recover deleted metadata.",
            &["binwalk", "sleuthkit"],
            "pacman: perl-image-exiftool (/usr/bin/vendor_perl/exiftool)",
            "https://exiftool.org",
        ),
    ]
}
