//! Automated reasoning engines: SMT solvers, SAT solvers, and first-order
//! automated theorem provers.

use super::{FV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- SMT solvers ----
        tool(
            "z3",
            "Z3",
            FV,
            "smt_solver",
            "Microsoft's industry-standard SMT solver over arithmetic, bit-vectors, arrays, datatypes, strings, and quantifiers.",
            "Decides satisfiability of SMT-LIB formulas across many theories, returning models or unsat cores; it is the default backend for Dafny, Verus, F*, Why3, TLAPS, and more.",
            "Reach for Z3 to discharge logical/arithmetic constraints, build a custom verifier or symbolic-execution engine, or debug why an auto-active proof fails — it underpins most tools in this catalog.",
            "Input: SMT-LIB 2 (`.smt2`) or its API. Output: sat/unsat/unknown, plus a model or unsat core.",
            "`z3 file.smt2` solves; `z3 -in` reads SMT-LIB from stdin; `z3 file.smt2 -st` prints statistics; rich C/Python/OCaml APIs.",
            "Broadest theory coverage; superb tactics + APIs; the de-facto verification backend.",
            "Quantified/nonlinear goals are incomplete (timeouts); performance varies wildly with encoding/seed.",
            &["cvc5", "yices", "bitwuzla", "vampire"],
            "pacman: z3 (/usr/bin/z3); also python-z3-solver",
            "https://github.com/Z3Prover/z3",
        ),
        tool(
            "cvc5",
            "cvc5",
            FV,
            "smt_solver",
            "Open-source SMT solver with strong support for strings, finite-field, and SyGuS synthesis.",
            "Successor to CVC4; decides SMT-LIB problems across many theories, produces proofs/unsat cores, and solves syntax-guided synthesis (SyGuS) problems.",
            "Reach for cvc5 as a Z3 alternative/cross-check — especially for string constraints, the theory of finite fields, proof production, or program synthesis via SyGuS.",
            "Input: SMT-LIB 2 or SyGuS. Output: sat/unsat/unknown + model, proof, or synthesized function.",
            "`cvc5 file.smt2`; `cvc5 --produce-models --lang smt2`; `cvc5 --sygus file.sy` for synthesis.",
            "Excellent string/FF theories; proof + SyGuS support; good for differential checking against Z3.",
            "Like all SMT, incomplete on quantifiers/nonlinear; some theories slower than Z3.",
            &["z3", "cvc4", "yices", "bitwuzla"],
            "pacman: cvc5 (/usr/bin/cvc5); also symfpu-cvc5",
            "https://cvc5.github.io",
        ),
        tool(
            "cvc4",
            "CVC4",
            FV,
            "smt_solver",
            "Predecessor of cvc5: a mature SMT solver still used where a frozen/known-good backend is required.",
            "Decides SMT-LIB formulas across the standard theories; retained for tools and proof scripts pinned to CVC4's behaviour before the cvc5 rewrite.",
            "Reach for CVC4 only when a toolchain specifically targets it (legacy proof scripts, reproducibility) — otherwise prefer cvc5.",
            "Input: SMT-LIB 2. Output: sat/unsat/unknown + model.",
            "`cvc4 --lang smt2 file.smt2`; `cvc4 --produce-models`.",
            "Stable legacy behaviour; broad theory support; useful for reproducing older results.",
            "Superseded by cvc5 (no new development); fewer features and slower on many benchmarks.",
            &["cvc5", "z3", "yices"],
            "pacman: cvc4 (/usr/bin/cvc4)",
            "https://cvc4.github.io",
        ),
        tool(
            "yices",
            "Yices 2",
            FV,
            "smt_solver",
            "Fast SMT solver from SRI, strong on linear arithmetic, bit-vectors, and incremental solving.",
            "Provides both a native input language and an SMT-LIB 2 front-end (`yices-smt2`); known for speed on QF_LRA/QF_BV and a clean C API for embedding.",
            "Reach for Yices when you want a lean, fast solver for bit-vector / linear-arithmetic queries or to embed an SMT engine via its C API; a good third opinion alongside Z3/cvc5.",
            "Input: native `.ys` or SMT-LIB 2. Output: sat/unsat/unknown + model.",
            "`yices-smt2 file.smt2` (SMT-LIB 2); `yices file.ys` (native, with push/pop scripting).",
            "Very fast on its core theories; clean embeddable API; good incremental performance.",
            "Narrower theory coverage than Z3/cvc5; weaker quantifier/nonlinear support.",
            &["z3", "cvc5", "bitwuzla"],
            "pacman: yices (/usr/bin/yices, yices-smt2)",
            "https://yices.csl.sri.com",
        ),
        tool(
            "bitwuzla",
            "Bitwuzla",
            FV,
            "smt_solver",
            "SMT solver specialised for the quantifier-free theories of bit-vectors, arrays, and floating-point.",
            "A state-of-the-art engine for QF_BV/QF_ABV/QF_FP (and beyond), frequently the fastest on bit-precise problems; successor to Boolector.",
            "Reach for Bitwuzla when your obligations are bit-precise — hardware/firmware verification, bit-vector-heavy symbolic execution, or IEEE floating-point reasoning — where it often beats general solvers.",
            "Input: SMT-LIB 2 (BV/FP/arrays). Output: sat/unsat/unknown + model.",
            "`bitwuzla file.smt2`; `bitwuzla --produce-models`; C/Python APIs available.",
            "Top-tier on bit-vectors and floating-point; competition-winning; strong model generation.",
            "Focused on QF bit-precise theories; not a general arithmetic/quantifier solver.",
            &["z3", "cvc5", "yices", "esbmc"],
            "pacman: bitwuzla (/usr/bin/bitwuzla)",
            "https://bitwuzla.github.io",
        ),
        // ---- SAT solvers ----
        tool(
            "minisat",
            "MiniSat",
            FV,
            "sat_solver",
            "The classic compact CDCL SAT solver, the reference baseline and teaching implementation.",
            "Reads DIMACS CNF and decides Boolean satisfiability, emitting a satisfying assignment or UNSAT; its small codebase is the template most modern solvers descend from.",
            "Reach for MiniSat as a dependency-light SAT backend, a baseline to compare against, or to understand CDCL internals; fine for small/medium instances.",
            "Input: DIMACS `.cnf`. Output: SAT + model / UNSAT (optionally to a result file).",
            "`minisat input.cnf out.txt` solves and writes the result; exit code encodes SAT/UNSAT.",
            "Tiny, hackable, well-understood; ubiquitous baseline.",
            "Outclassed on hard modern instances by CaDiCaL/Kissat; no native proofs/XOR reasoning.",
            &["cadical", "kissat", "cryptominisat"],
            "pacman: minisat (/usr/bin/minisat)",
            "http://minisat.se",
        ),
        tool(
            "cadical",
            "CaDiCaL",
            FV,
            "sat_solver",
            "Modern, simplified CDCL SAT solver by Armin Biere with strong inprocessing and DRAT proofs.",
            "A clean, high-performance solver that emits DRAT certificates for UNSAT, widely embedded (e.g. as a Kissat companion) and competitive in SAT competitions.",
            "Reach for CaDiCaL when you need a fast, embeddable SAT solver that also produces checkable UNSAT proofs (DRAT) — a good default modern solver.",
            "Input: DIMACS `.cnf`. Output: SAT + model / UNSAT, optional DRAT proof.",
            "`cadical input.cnf`; `cadical input.cnf proof.drat` emits a DRAT certificate.",
            "Fast + clean; DRAT proof output; easy to embed via its API.",
            "Pure CNF/Boolean (no theories); no native XOR/Gaussian reasoning.",
            &["kissat", "minisat", "cryptominisat"],
            "pacman: cadical (/usr/bin/cadical)",
            "https://github.com/arminbiere/cadical",
        ),
        tool(
            "kissat",
            "Kissat",
            FV,
            "sat_solver",
            "Bare-metal C rewrite of CaDiCaL, repeatedly a SAT-Competition winner on raw solving speed.",
            "A keep-it-simple, highly optimized CDCL solver focused on single-thread performance for hard CNF instances.",
            "Reach for Kissat when you just need the fastest answer on a hard SAT/UNSAT instance and don't require an embedded API or incremental solving.",
            "Input: DIMACS `.cnf`. Output: SAT + model / UNSAT (+ optional proof).",
            "`kissat input.cnf`; `kissat --relaxed input.cnf` for tolerant parsing.",
            "Often the fastest single solver on competition benchmarks.",
            "Primarily a CLI batch solver (limited incremental/API use); CNF only.",
            &["cadical", "minisat", "cryptominisat"],
            "pacman: kissat (/usr/bin/kissat)",
            "https://github.com/arminbiere/kissat",
        ),
        tool(
            "cryptominisat",
            "CryptoMiniSat",
            FV,
            "sat_solver",
            "CDCL SAT solver with native XOR (Gaussian-elimination) reasoning, strong for cryptographic CNFs.",
            "Adds XOR-clause handling and advanced simplification to CDCL, making it effective on instances arising from cryptanalysis and on counting/sampling workloads.",
            "Reach for CryptoMiniSat when your CNF has heavy XOR structure (crypto, parity constraints) or you need its XOR-aware simplification that pure CDCL solvers lack.",
            "Input: DIMACS `.cnf` (optionally with `x`-prefixed XOR clauses). Output: SAT + model / UNSAT.",
            "`cryptominisat5 input.cnf`; supports XOR clauses and DRAT proofs.",
            "Native XOR/Gaussian reasoning; good on cryptographic instances; proof support.",
            "Heavier than Kissat on plain CNF; the XOR machinery adds overhead when unused.",
            &["cadical", "kissat", "minisat"],
            "pacman: cryptominisat (/usr/bin/cryptominisat5); also python-pycosat",
            "https://github.com/msoos/cryptominisat",
        ),
        // ---- First-order ATPs ----
        tool(
            "eprover",
            "E (eprover)",
            FV,
            "first_order_atp",
            "Saturation-based theorem prover for full first-order logic with equality (TPTP).",
            "E proves/refutes first-order conjectures via the superposition calculus with strong term orderings and literal selection; a standard CoqHammer/Sledgehammer backend.",
            "Reach for E to discharge first-order goals automatically — directly on TPTP problems, or as the external prover behind a hammer tactic in Rocq/Isabelle.",
            "Input: TPTP (`.p`) FOF/CNF/TFF. Output: proof/refutation status (+ a proof object in TPTP format).",
            "`eprover --auto --proof-object problem.p`; `eprover --tptp3-format --auto-schedule problem.p`.",
            "Robust, scriptable, great term-ordering heuristics; excellent hammer backend.",
            "First-order only (no higher-order/induction); needs a good clause/axiom selection to scale.",
            &["vampire", "zenon", "coq-hammer"],
            "pacman: eprover (/usr/bin/eprover)",
            "https://eprover.org",
        ),
        tool(
            "vampire",
            "Vampire",
            FV,
            "first_order_atp",
            "Leading first-order superposition prover, repeated CASC world champion, with some SMT/theory support.",
            "Vampire proves first-order (and limited theory/higher-order) conjectures with portfolio scheduling, AVATAR clause splitting, and built-in arithmetic; a top hammer backend.",
            "Reach for Vampire when E can't close a first-order goal, when you want portfolio/auto-schedule strength, or as a powerful external prover for CoqHammer/Sledgehammer.",
            "Input: TPTP (`.p`) or SMT-LIB. Output: proof/refutation (Refutation/Satisfiable) + proof object.",
            "`vampire problem.p`; `vampire --mode casc problem.p` runs the competition portfolio; reads SMT-LIB too.",
            "Best-in-class FOL strength; AVATAR + portfolio scheduling; some theory reasoning.",
            "First-order focus (limited higher-order); portfolio mode is resource-hungry.",
            &["eprover", "zenon", "z3", "coq-hammer"],
            "pacman: vampire (/usr/bin/vampire)",
            "https://vprover.github.io",
        ),
        tool(
            "zenon",
            "Zenon",
            FV,
            "first_order_atp",
            "Tableau-based first-order prover that emits checkable proofs, used as a TLAPS / Focalize backend.",
            "Zenon searches for proofs by analytic tableaux and outputs proof terms (e.g. Coq) that an external checker can verify; TLAPS calls it to discharge proof obligations.",
            "Reach for Zenon mostly indirectly — it is a default backend prover for TLAPS proof obligations; standalone it proves first-order goals and produces a verifiable proof.",
            "Input: first-order problems (Zenon/TPTP; TLA⁺ obligations via TLAPS). Output: a checkable proof or failure.",
            "Usually invoked by TLAPS automatically; standalone `zenon file` proves and can emit a Coq proof. Binary at ~/.local/tlaps and ~/.local/bin.",
            "Produces independently checkable proofs; integrates tightly with TLAPS.",
            "Weaker/older than E/Vampire on hard FOL; primarily valuable as a backend, not a standalone workhorse.",
            &["tlaps", "eprover", "vampire"],
            "TLAPS-bundled: ~/.local/bin/zenon; also opam zenon_modulo (0.5.0)",
            "http://zenon-prover.org",
        ),
    ]
}
