//! Live system / resource monitors and CPU frequency / power-state tools
//! (including the knobs for stabilizing a benchmarking environment).

use super::{DEV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        tool(
            "htop",
            "htop",
            DEV,
            "system_monitor",
            "Interactive process and resource viewer for the terminal.",
            "htop shows per-core CPU bars, memory/swap, load, and a sortable/filterable/tree process list with live CPU/MEM per process, and lets you renice or kill interactively.",
            "Reach for htop as the first glance at 'what is using this machine right now' — which process/core is hot, memory pressure, or a runaway thread.",
            "Input: none (system-wide) or a filter/user. Output: a live interactive TUI.",
            "`htop`; `F4` filter, `F6` sort, `t` tree view, `H` toggle user threads.",
            "Fast, interactive, per-core + per-process; tree view; ubiquitous.",
            "Snapshot/sampling view (not historical); local terminal; coarse for deep profiling.",
            &["glances", "turbostat"],
            "pacman: htop (/usr/bin/htop)",
            "https://htop.dev/",
        ),
        tool(
            "glances",
            "Glances",
            DEV,
            "system_monitor",
            "Cross-platform 'all-in-one' system monitor with CPU, memory, network, disk, sensors, and a web/REST mode.",
            "Glances presents a curated dashboard (CPU, load, memory, per-interface network, disk I/O, filesystems, sensors, containers, top processes) and can run as a web server or export to InfluxDB/Prometheus.",
            "Reach for Glances for a broad one-screen system overview, or to expose metrics remotely (web/REST/exporters) for light monitoring of a box.",
            "Input: none (or a server/export config). Output: a TUI dashboard, or a web/REST/exported feed.",
            "`glances`; `glances -w` serves the web UI; `--export prometheus` etc. for metrics.",
            "Broad coverage in one view; web/REST + exporters; sensors/containers.",
            "Higher overhead than htop; busy screen; Python startup.",
            &["htop", "iotop", "iftop"],
            "pacman: glances (/usr/bin/glances)",
            "https://nicolargo.github.io/glances/",
        ),
        tool(
            "iotop",
            "iotop",
            DEV,
            "system_monitor",
            "Per-process disk I/O monitor — see which processes are reading/writing the most.",
            "iotop uses kernel taskstats to show per-process/-thread read/write throughput and I/O wait, ranking the heaviest disk users live.",
            "Reach for iotop to attribute disk I/O to a process — find what's hammering storage when the system feels I/O-bound (complements biolatency's distribution view).",
            "Input: none (or `-p <pid>`). Output: a live per-process I/O TUI.",
            "`sudo iotop`; `iotop -o` shows only processes doing I/O; `-a` accumulates totals.",
            "Direct per-process I/O attribution; simple; live.",
            "Needs root + kernel taskstats; disk I/O only; sampling view.",
            &["glances", "biolatency"],
            "pacman: iotop (/usr/bin/iotop)",
            "https://github.com/Tomas-M/iotop",
        ),
        tool(
            "iftop",
            "iftop",
            DEV,
            "system_monitor",
            "Per-connection network bandwidth monitor for an interface.",
            "iftop sniffs an interface and displays a live, sorted list of host-pair connections with current/average bandwidth, so you can see who is sending/receiving the most traffic.",
            "Reach for iftop to see live network bandwidth by connection — identify a chatty peer or a bandwidth-hogging flow on a given interface.",
            "Input: an interface (`-i`). Output: a live per-connection bandwidth TUI.",
            "`sudo iftop -i eth0`; `-P` shows ports; `-n` disables name resolution.",
            "Immediate per-connection bandwidth view; lightweight.",
            "Per-connection (not per-process — see nethogs); needs root; one interface at a time.",
            &["nethogs", "glances"],
            "pacman: iftop (/usr/bin/iftop)",
            "https://pdw.ex-parrot.com/iftop/",
        ),
        tool(
            "nethogs",
            "NetHogs",
            DEV,
            "system_monitor",
            "Per-process network bandwidth monitor.",
            "NetHogs groups live network throughput by process (not by connection), so you can immediately see which program is consuming up/down bandwidth.",
            "Reach for nethogs to attribute network usage to a process — the per-process counterpart to iftop's per-connection view.",
            "Input: an interface (optional). Output: a live per-process bandwidth TUI.",
            "`sudo nethogs`; `sudo nethogs eth0`; `m` cycles units (KB/s, totals).",
            "Per-process attribution; instant; simple.",
            "Needs root; no historical data; bandwidth only.",
            &["iftop", "glances"],
            "pacman: nethogs (/usr/bin/nethogs)",
            "https://github.com/raboof/nethogs",
        ),
        tool(
            "i7z",
            "i7z",
            DEV,
            "system_monitor",
            "Real-time per-core frequency, C-state, and temperature monitor for Intel Core CPUs.",
            "i7z reads MSRs to display each core's live actual frequency, the share of time in each C-state, and temperatures — a quick way to see real clock behaviour under load.",
            "Reach for i7z to confirm cores are actually running at the expected (max) frequency during a benchmark, and to watch C-state residency / thermal throttling.",
            "Input: none (reads MSRs). Output: a live per-core frequency/C-state/temperature TUI.",
            "`sudo i7z`; watch the per-core actual-frequency column while a workload runs.",
            "Direct real-frequency + C-state + temperature view; great benchmarking sanity check.",
            "Intel-focused; needs root/MSR access; display-only (no control).",
            &["turbostat", "cpupower"],
            "pacman: i7z (/usr/bin/i7z)",
            "https://github.com/afontenot/i7z",
        ),
        tool(
            "turbostat",
            "turbostat",
            DEV,
            "system_monitor",
            "Reports per-CPU frequency, idle (C-state) residency, temperature, and power (RAPL) around a workload.",
            "turbostat samples MSRs/RAPL to report average and per-CPU effective frequency, busy %, C-state residency, package/core temperature, and energy — optionally bracketing a command you run.",
            "Reach for turbostat to characterize CPU frequency/power behaviour during benchmarking — verify turbo/clocks, measure energy, and detect throttling; run it around the workload for exact numbers.",
            "Input: an interval or a wrapped command. Output: per-CPU/-package frequency, C-state, temp, and power stats.",
            "`sudo turbostat --interval 1`; `sudo turbostat -- ./benchmark` reports stats for that run; `--Summary` for a compact view.",
            "Authoritative frequency/C-state/power/energy data; can bracket a command; RAPL energy.",
            "Intel-centric; needs root/MSR; tabular output is dense.",
            &["i7z", "cpupower", "x86-energy-perf-policy"],
            "pacman: turbostat (/usr/bin/turbostat)",
            "https://www.kernel.org/doc/man-pages/",
        ),
        tool(
            "kcpuid",
            "kcpuid",
            DEV,
            "system_monitor",
            "Dumps x86 CPUID feature flags in human-readable form.",
            "kcpuid (from the kernel tools) decodes the CPUID instruction's leaves into named feature flags — instruction-set extensions, cache/topology hints, and capabilities of the current CPU.",
            "Reach for kcpuid to check whether the CPU supports a feature (AVX-512, specific extensions) before enabling target-cpu flags or interpreting microarchitecture-specific profiling.",
            "Input: none (queries the local CPU). Output: a decoded list of CPUID feature flags.",
            "`kcpuid`; `kcpuid -d` for detailed leaf output.",
            "Quick, readable CPU-capability inventory.",
            "Static capability info (not a live monitor); x86-only.",
            &["turbostat", "i7z"],
            "pacman: kcpuid (/usr/bin/kcpuid)",
            "https://www.kernel.org/doc/html/latest/",
        ),
        tool(
            "intel-speed-select",
            "Intel Speed Select (intel-speed-select)",
            DEV,
            "system_monitor",
            "Configures Intel Speed Select Technology — per-core P-states, turbo-frequency, and priority.",
            "intel-speed-select inspects and applies SST features (SST-PP performance profiles, SST-BF base frequency, SST-CP core priority, SST-TF turbo frequency) on supported Xeon CPUs.",
            "Reach for intel-speed-select on supported Intel server CPUs to pin performance profiles or prioritize specific cores — e.g. to create a stable, high-frequency island for benchmarking.",
            "Input: SST feature subcommands. Output: current SST config / applied settings.",
            "`sudo intel-speed-select perf-profile info`; `sudo intel-speed-select core-power assoc -c <cpu>`; subcommands per SST feature.",
            "Fine-grained per-core frequency/priority control on capable hardware.",
            "Only on SST-capable Intel server CPUs; root; intricate feature model.",
            &["cpupower", "turbostat", "x86-energy-perf-policy"],
            "pacman: intel-speed-select (/usr/bin/intel-speed-select)",
            "https://www.kernel.org/doc/html/latest/admin-guide/pm/intel-speed-select.html",
        ),
        tool(
            "x86-energy-perf-policy",
            "x86_energy_perf_policy",
            DEV,
            "system_monitor",
            "Reads and sets the CPU's energy-vs-performance preference (EPB / HWP hint).",
            "x86_energy_perf_policy displays and adjusts the per-CPU Energy-Performance Bias / HWP energy-performance preference, biasing the hardware between power saving and performance.",
            "Reach for it to push the CPU toward maximum performance before benchmarking (bias = performance), then restore the default afterwards — part of stabilizing a measurement environment.",
            "Input: a policy value (e.g. performance) or none to read. Output: current/updated EPB/EPP per CPU.",
            "`sudo x86_energy_perf_policy --turbo-enable 1`; `sudo x86_energy_perf_policy performance`; run with no args to read.",
            "Direct control of the energy/performance hint; quick benchmarking prep.",
            "x86-only; needs root; one knob among several (pair with cpupower).",
            &["cpupower", "turbostat"],
            "pacman: x86_energy_perf_policy (/usr/bin/x86_energy_perf_policy)",
            "https://www.kernel.org/doc/man-pages/",
        ),
        tool(
            "cpupower",
            "cpupower",
            DEV,
            "system_monitor",
            "Inspects and controls CPU frequency scaling — governors, frequency limits, and idle states.",
            "cpupower reads and sets the cpufreq governor, min/max frequencies, and idle-state options per CPU, and reports current clocks — the standard knob for pinning the CPU to a performance governor.",
            "Reach for cpupower to fix the environment before benchmarking: set the `performance` governor so cores run at maximum frequency (the user's standard prep), then restore afterwards.",
            "Input: frequency/governor/idle subcommands. Output: current settings / applied changes.",
            "`cpupower frequency-info`; `sudo cpupower frequency-set -g performance` (max-frequency governor); `sudo cpupower frequency-set -g schedutil` to restore.",
            "The canonical governor/frequency control; simple; essential for stable benchmarks.",
            "Needs root; effect depends on the cpufreq driver; per-boot (not persistent by itself).",
            &["turbostat", "i7z", "x86-energy-perf-policy"],
            "pacman: cpupower (/usr/bin/cpupower)",
            "https://www.kernel.org/doc/man-pages/",
        ),
    ]
}
