//! eBPF / dynamic tracers, the syscall tracer, and benchmarking tools
//! (CLI harnesses + in-code microbenchmark libraries).

use super::{DEV, ToolSeed, tool};

pub(super) fn seeds() -> Vec<ToolSeed> {
    vec![
        // ---- eBPF / dynamic tracers ----
        tool(
            "bpftrace",
            "bpftrace",
            DEV,
            "ebpf_tracer",
            "High-level tracing language for Linux eBPF — DTrace-style one-liners over kernel and user events.",
            "bpftrace compiles concise scripts (probes + actions over tracepoints, kprobes, uprobes, USDT, profile timers) into eBPF, aggregating histograms/counts/stacks in-kernel with very low overhead.",
            "Reach for bpftrace for ad-hoc dynamic analysis: count/aggregate syscalls, latency-histogram a function, sample stacks, or trace a custom kernel/user event — when no canned tool exists.",
            "Input: a one-liner or `.bt` script. Output: live aggregated maps/histograms/stacks.",
            "`bpftrace -e 'tracepoint:syscalls:sys_enter_openat { @[comm]=count(); }'`; `bpftrace script.bt`; `bpftrace -l` lists probes.",
            "Extremely flexible; low overhead; in-kernel aggregation; great for one-off questions.",
            "Needs root/CAP_BPF + kernel BTF; its own language; not a persistent/GUI profiler.",
            &["bcc", "perf", "strace"],
            "pacman: bpftrace (/usr/bin/bpftrace)",
            "https://bpftrace.org",
        ),
        tool(
            "bcc",
            "BCC (BPF Compiler Collection tools)",
            DEV,
            "ebpf_tracer",
            "A toolkit of ready-made eBPF performance and tracing programs (the libbpf-tools suite).",
            "BCC ships dozens of purpose-built tools — offcputime, profile, funclatency, memleak, biolatency, execsnoop, and more — each answering a specific performance/observability question via eBPF.",
            "Reach for the BCC tools when there's a canned answer to your question (block-I/O latency, off-CPU time, function latency, allocation leaks) instead of writing a bpftrace script from scratch.",
            "Input: tool-specific flags (PID, duration, function pattern). Output: histograms / stacks / event streams.",
            "Run an individual tool, e.g. `offcputime -K 5`, `profile -F 99 10`, `funclatency 'vfs_read'`; tools live in /usr/bin (bcc-libbpf-tools).",
            "Curated, battle-tested tools (Brendan Gregg et al.); each is focused and documented.",
            "Root + recent kernel; many small tools to learn; per-tool option quirks.",
            &["bpftrace", "offcputime", "profile-bcc", "perf"],
            "pacman: bcc, bcc-libbpf-tools, python-bcc",
            "https://github.com/iovisor/bcc",
        ),
        tool(
            "bpftool",
            "bpftool",
            DEV,
            "ebpf_tracer",
            "Low-level utility to inspect and manage eBPF programs, maps, links, and BTF in the kernel.",
            "bpftool lists/loads/dumps eBPF objects, reads/writes maps, shows attached programs and BTF type info — the introspection tool for the eBPF subsystem itself.",
            "Reach for bpftool when debugging eBPF tooling: see what BPF programs/maps are loaded, dump a map's contents, or inspect BTF — meta-observability for the tracers above.",
            "Input: object/subcommand (prog, map, link, btf). Output: listings/dumps of kernel eBPF state.",
            "`bpftool prog show`; `bpftool map dump id <N>`; `bpftool btf dump file vmlinux`.",
            "Authoritative view of kernel eBPF state; manage/pin programs and maps.",
            "Low-level (not a profiler); root required; assumes eBPF knowledge.",
            &["bpftrace", "bcc"],
            "pacman: bpf (/usr/bin/bpftool)",
            "https://github.com/libbpf/bpftool",
        ),
        tool(
            "funclatency",
            "funclatency (BCC)",
            DEV,
            "ebpf_tracer",
            "eBPF tool that prints a latency histogram for a kernel or user function.",
            "funclatency attaches to a function (by name/pattern) and records a power-of-two histogram of its call durations, revealing slow tails and multimodal latency.",
            "Reach for funclatency to quantify how long a specific function takes — spot tail latency or bimodal behaviour in a hot path without editing the code.",
            "Input: a function name/pattern (+ optional PID/duration). Output: a latency histogram.",
            "`funclatency vfs_read`; `funclatency -p <pid> 'libc:malloc'`; add `-m` for millisecond buckets.",
            "Pinpoint per-function latency distribution; no recompilation.",
            "One function/pattern at a time; root + eBPF; uprobe overhead on very hot functions.",
            &["bpftrace", "offcputime", "perf"],
            "pacman: bcc-libbpf-tools (/usr/bin/funclatency)",
            "https://github.com/iovisor/bcc",
        ),
        tool(
            "offcputime",
            "offcputime (BCC)",
            DEV,
            "ebpf_tracer",
            "eBPF tool that samples the stacks where threads block (off-CPU), with blocked durations.",
            "offcputime records, per blocking event, the stack at which a thread went off-CPU and how long it stayed there — exposing time lost to locks, I/O waits, and sleeps that on-CPU profilers miss.",
            "Reach for offcputime to find why threads are *waiting* — lock contention, blocking syscalls, sleeps — a primary tool for diagnosing deadlocks/blocking and latency, complementing on-CPU profiling.",
            "Input: a duration (+ optional PID/TID). Output: off-CPU stacks aggregated by total blocked time (foldable to a flame graph).",
            "`offcputime -K 5` (kernel stacks, 5 s); `offcputime -p <pid> 10`; pipe folded output into FlameGraph for an off-CPU flame graph.",
            "Reveals blocking/wait time invisible to CPU profilers; stack-attributed; the deadlock/contention lens.",
            "Root + eBPF; high context-switch rates produce large output; stacks need symbols.",
            &["profile-bcc", "bpftrace", "perf"],
            "pacman: bcc-libbpf-tools (/usr/bin/offcputime)",
            "https://github.com/iovisor/bcc",
        ),
        tool(
            "profile-bcc",
            "profile (BCC)",
            DEV,
            "ebpf_tracer",
            "eBPF CPU profiler that samples on-CPU stacks system-wide at a fixed frequency.",
            "The BCC `profile` tool periodically samples the on-CPU stack of every CPU and aggregates counts in-kernel, giving a low-overhead, symbol-resolved on-CPU profile foldable into a flame graph.",
            "Reach for `profile` to see on-CPU wall-time stacks across the whole system or a process with minimal overhead — the on-CPU counterpart to offcputime.",
            "Input: a sample frequency + duration (+ optional PID). Output: aggregated on-CPU stacks.",
            "`profile -F 99 10` (99 Hz, 10 s); `profile -p <pid> -f 10 > out.folded` then render with FlameGraph.",
            "Very low overhead (in-kernel aggregation); system-wide; flame-graph-ready.",
            "Root + eBPF; sampling (not exact); needs symbols/frame pointers for good stacks.",
            &["offcputime", "perf", "flamegraph"],
            "pacman: bcc-libbpf-tools (/usr/bin/profile)",
            "https://github.com/iovisor/bcc",
        ),
        tool(
            "memleak",
            "memleak (BCC)",
            DEV,
            "ebpf_tracer",
            "eBPF tool that traces outstanding allocations and reports the stacks that leak memory.",
            "memleak attaches to the allocator and tracks allocations that are never freed, periodically printing the call stacks responsible and the bytes outstanding.",
            "Reach for memleak to catch leaks in a live process with low overhead — especially long-running services where you want leak stacks without a Valgrind-level slowdown.",
            "Input: a PID (or a command) + interval. Output: outstanding-allocation stacks ranked by bytes.",
            "`memleak -p <pid> 5`; `memleak -c './prog'`; `-a` shows individual allocations.",
            "Live, low-overhead leak detection with stacks; good for production-like processes.",
            "Root + eBPF; samples allocations (may miss some); user-allocator symbols needed.",
            &["heaptrack", "valgrind-memcheck", "bytehound"],
            "pacman: bcc-libbpf-tools (/usr/bin/memleak)",
            "https://github.com/iovisor/bcc",
        ),
        tool(
            "biolatency",
            "biolatency (BCC)",
            DEV,
            "ebpf_tracer",
            "eBPF tool that summarizes block-device I/O latency as a histogram.",
            "biolatency traces block-I/O request completion and prints a power-of-two latency histogram, optionally split by device, flags, or queue — revealing storage stalls.",
            "Reach for biolatency when disk/storage latency is suspect — see the distribution (and tail) of block-I/O times to confirm or rule out an I/O bottleneck.",
            "Input: an interval/count (+ optional flags). Output: a block-I/O latency histogram.",
            "`biolatency 1 10` (1 s, 10 times); `-D` per-disk; `-m` millisecond buckets.",
            "Quantifies I/O latency distribution + tails; negligible overhead.",
            "Block layer only (not file-system semantics); root + eBPF.",
            &["bpftrace", "iotop"],
            "pacman: bcc-libbpf-tools (/usr/bin/biolatency)",
            "https://github.com/iovisor/bcc",
        ),
        tool(
            "pcp-pmda-bcc",
            "PCP PMDA for BCC",
            DEV,
            "ebpf_tracer",
            "Performance Co-Pilot agent that exports eBPF/BCC metrics into PCP's time-series framework.",
            "This PMDA runs BCC-based eBPF modules and publishes their metrics into Performance Co-Pilot, so eBPF observability can be collected, archived, and graphed over time alongside other PCP metrics.",
            "Reach for pcp-pmda-bcc when you want continuous, recorded eBPF metrics (not one-off tracing) — long-term monitoring and historical analysis via PCP.",
            "Input: PMDA configuration selecting BCC modules. Output: PCP metrics (pmrep/pmchart/Grafana).",
            "Enable via the PCP PMDA install (`cd $PCP_PMDAS_DIR/bcc && ./Install`); then query with `pminfo`/`pmrep bcc.*`.",
            "Bridges eBPF into a full time-series stack; archival + dashboards.",
            "Requires a PCP deployment; configuration overhead; not for quick ad-hoc tracing.",
            &["bcc", "glances"],
            "pacman: pcp-pmda-bcc",
            "https://pcp.io",
        ),
        // ---- Syscall tracer ----
        tool(
            "strace",
            "strace",
            DEV,
            "syscall_tracer",
            "Diagnostic tracer that prints the system calls and signals a process makes.",
            "strace intercepts syscalls via ptrace and shows each call's arguments, return value, and timing — invaluable for seeing what a program actually asks the kernel to do (files, sockets, ioctls, failures).",
            "Reach for strace to debug 'why does this program fail/hang/stat the wrong path' — missing files, permission errors, blocking syscalls, or unexpected I/O — without source or recompilation.",
            "Input: a command or `-p <pid>`. Output: a stream of syscalls with args/returns (+ optional timing).",
            "`strace ./prog`; `strace -f -e trace=openat,read,write ./prog`; `strace -p <pid> -T -tt` (with timing).",
            "Shows exact kernel interactions + errno; no recompilation; filterable.",
            "High overhead via ptrace (slows the target a lot); syscalls only (not in-process logic); one process tree.",
            &["bpftrace", "gdb"],
            "pacman: strace (/usr/bin/strace)",
            "https://strace.io",
        ),
        // ---- CLI benchmarking ----
        tool(
            "hyperfine",
            "hyperfine",
            DEV,
            "cli_benchmark",
            "Statistical command-line benchmarking tool with warmup, outlier detection, and exports.",
            "hyperfine runs commands many times, reports mean ± σ with outlier detection, supports warmup runs, parameter sweeps, and prepare/cleanup hooks, and exports JSON/CSV/Markdown for analysis.",
            "Reach for hyperfine to benchmark and compare whole commands/CLIs rigorously (A vs B), with statistics — the user's default for command-line benchmarking. Pin to a core and fix the CPU frequency for stable results.",
            "Input: one or more shell commands (+ options). Output: timing stats per command, optional JSON/CSV/Markdown.",
            "`hyperfine './prog --a' './prog --b'`; `--warmup 3`; `-P n 1 8 'prog -j {n}'` parameter sweep; `--export-json out.json`.",
            "Rigorous stats + warmup + outlier handling; easy A/B; machine-readable exports.",
            "Benchmarks whole processes (includes startup); not for in-process microbenchmarks; wall-clock only.",
            &["time", "criterion"],
            "pacman: hyperfine (/usr/bin/hyperfine)",
            "https://github.com/sharkdp/hyperfine",
        ),
        tool(
            "time",
            "time (shell builtin / GNU time)",
            DEV,
            "cli_benchmark",
            "Measures the wall-clock, user, and system time (and, with GNU time, peak memory) of a command.",
            "The shell's `time` keyword reports real/user/sys for a single run; GNU `/usr/bin/time -v` additionally reports maximum resident set size, page faults, context switches, and more.",
            "Reach for `time` for a quick one-shot cost/memory check of a command; escalate to hyperfine when you need repeated runs and statistics.",
            "Input: a command. Output: real/user/sys time (+ max RSS and counters with GNU time `-v`).",
            "`time ./prog` (shell builtin); `/usr/bin/time -v ./prog` for max RSS + detailed resource stats (GNU time package).",
            "Always available; instant; GNU `-v` adds peak-memory/resource detail.",
            "Single run (no statistics/warmup); builtin output varies by shell; not for microbenchmarks.",
            &["hyperfine"],
            "Shell builtin (zsh/bash `time`); GNU `/usr/bin/time -v` via the `time` package",
            "https://www.gnu.org/software/time/",
        ),
        // ---- Benchmark libraries ----
        tool(
            "criterion",
            "Criterion.rs",
            DEV,
            "benchmark_library",
            "Statistics-driven microbenchmark harness for Rust with regression detection and HTML reports.",
            "Criterion runs Rust benchmark functions with warmup + many samples, estimates the distribution, detects performance changes between runs, and emits detailed HTML/plots — the standard Rust benchmarking crate.",
            "Reach for Criterion to microbenchmark specific Rust functions in this workspace (`benches/`), track regressions over time, and get statistically sound per-function timings (vs. hyperfine's whole-process view).",
            "Input: `#[bench]`-style functions using the Criterion API in `benches/`. Output: timing stats + HTML reports in `target/criterion`.",
            "Add criterion to `[dev-dependencies]` + a `[[bench]]` entry, then `cargo bench`. (Rust benches must be declared in Cargo.toml first.)",
            "Rigorous per-function stats; regression detection; rich HTML/plots; the Rust standard.",
            "Rust-only; benchmark must be coded; longer runs than a quick `time`.",
            &["hyperfine", "google-benchmark", "pytest-benchmark"],
            "cargo crate (add to [dev-dependencies]; run via `cargo bench`)",
            "https://github.com/bheisler/criterion.rs",
        ),
        tool(
            "google-benchmark",
            "Google Benchmark",
            DEV,
            "benchmark_library",
            "C++ microbenchmark library modeled on GoogleTest, with rich timing and complexity analysis.",
            "You write `BENCHMARK(fn)` cases against libbenchmark; it auto-tunes iteration counts, reports per-iteration time/throughput, supports fixtures/args/ranges, and can estimate Big-O complexity.",
            "Reach for Google Benchmark to microbenchmark C/C++ code paths with statistically meaningful per-iteration timings, parameter ranges, and counters.",
            "Input: C++ benchmark cases linked against libbenchmark. Output: per-benchmark timing/throughput tables (console/JSON/CSV).",
            "Link `-lbenchmark`; run the binary with `--benchmark_filter=`, `--benchmark_format=json`, `--benchmark_repetitions=N`.",
            "Auto iteration tuning; fixtures/ranges/counters; Big-O estimation; JSON output.",
            "C/C++ only; requires writing+linking benchmarks; microbenchmark pitfalls (DCE, warmup) apply.",
            &["criterion", "pytest-benchmark"],
            "pacman: benchmark (libbenchmark)",
            "https://github.com/google/benchmark",
        ),
        tool(
            "pytest-benchmark",
            "pytest-benchmark",
            DEV,
            "benchmark_library",
            "pytest fixture that benchmarks Python code with calibrated timing and statistics.",
            "The `benchmark` fixture calibrates and repeats a callable, reports min/max/mean/median/σ/ops, can compare against saved baselines, and integrates with the normal pytest workflow.",
            "Reach for pytest-benchmark to microbenchmark Python functions inside a test suite and track regressions against saved baselines.",
            "Input: tests using the `benchmark` fixture. Output: a timing stats table (+ optional saved/compared baselines).",
            "`def test_x(benchmark): benchmark(fn, *args)`; run `pytest --benchmark-only`; `--benchmark-autosave` / `--benchmark-compare`.",
            "Lives in pytest; calibrated timing + stats; baseline comparison.",
            "Python-only; in-process microbenchmark caveats; overhead for very fast callables.",
            &["criterion", "google-benchmark", "hyperfine"],
            "pacman: python-pytest-benchmark",
            "https://pytest-benchmark.readthedocs.io",
        ),
    ]
}
