//! Golden-file fixture harness.
//!
//! Storage format is [`postcard`] — a compact, schema-strict binary
//! encoding that handles f32/f64 losslessly. Each fixture is one
//! `.postcard` file under
//! [`pgmcp-testing/fixtures/golden/<component>/<name>.postcard`],
//! containing a [`Golden<I, O>`] struct wrapping the canonical input,
//! the golden output, an optional float tolerance, and audit metadata.
//!
//! ## Three entry points
//!
//! - [`load_golden`] — deserialize a fixture. Used in tests to retrieve
//!   the input and the frozen output.
//! - [`assert_match_exact`] / [`assert_match_epsilon`] — convenience
//!   wrappers that run the algorithm against the fixture's input and
//!   compare to the fixture's output.
//! - [`regen_golden`] — write a new fixture file. Called by the
//!   `regen-goldens` binary and by any generator that needs to update
//!   a fixture when an algorithm output legitimately changes.
//!
//! ## Regeneration workflow
//!
//! Goldens are regenerated by running the dedicated binary:
//!
//! ```text
//! cargo run --release -p pgmcp-testing --bin regen-goldens
//! ```
//!
//! The binary walks every registered generator, writes the new
//! payload, and prints a summary (`unchanged`, `updated`, `new`).
//! CI fails if `git diff --quiet pgmcp-testing/fixtures/golden/`
//! reports a change — reviewer must bless the diff by committing it.

use std::fmt;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// Schema version for the `Golden<I, O>` envelope. Bumped only when the
/// envelope fields themselves change — bumping invalidates *all*
/// fixtures and forces a full regeneration.
pub const SCHEMA_VERSION: u32 = 1;

/// A golden fixture: canonical input + frozen output + audit metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Golden<I, O> {
    /// Bumped on envelope-format changes. See [`SCHEMA_VERSION`].
    pub schema_version: u32,
    /// Canonical input the generator runs against.
    pub input: I,
    /// The output captured from the generator.
    pub output: O,
    /// Optional float tolerance for `assert_match_epsilon`. `None` for
    /// discrete fixtures that compare with structural equality.
    pub tolerance: Option<f64>,
    /// ISO-8601 timestamp of when this fixture was last regenerated.
    /// Strictly informational — tests never assert on this field.
    pub generated_at_iso: String,
    /// Identifier for the generator that produced this fixture.
    /// Typically `"regen-goldens:<component>/<name>"`.
    pub source: String,
}

/// Locate the `pgmcp-testing/fixtures/golden/` root from any test
/// binary's `CARGO_MANIFEST_DIR`. In the workspace this expands to
/// `<workspace>/pgmcp-testing/fixtures/golden/`.
pub fn fixtures_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join("golden")
}

/// Build the path for a named fixture: `<root>/<name>.postcard`.
/// Names may include `/` to group by component, e.g.
/// `"chunker/short_rust_file"`.
pub fn fixture_path(name: &str) -> PathBuf {
    fixtures_root().join(format!("{}.postcard", name))
}

/// Errors raised by the golden harness. Deliberately narrow — test
/// failures should panic with a descriptive assertion, not bubble up
/// typed errors.
#[derive(Debug)]
pub enum GoldenError {
    /// Fixture file doesn't exist. Hint: run `regen-goldens`.
    Missing(PathBuf),
    /// Fixture file exists but couldn't be read.
    Read(PathBuf, std::io::Error),
    /// Postcard deserialization failed — usually means the schema
    /// version bumped or the serialized type changed.
    Deserialize(PathBuf, postcard::Error),
    /// Envelope's schema_version doesn't match [`SCHEMA_VERSION`].
    SchemaMismatch {
        path: PathBuf,
        found: u32,
        expected: u32,
    },
}

impl fmt::Display for GoldenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Missing(p) => write!(
                f,
                "golden fixture missing: {} — run `cargo run --release -p pgmcp-testing --bin regen-goldens`",
                p.display()
            ),
            Self::Read(p, e) => write!(f, "read {}: {}", p.display(), e),
            Self::Deserialize(p, e) => write!(
                f,
                "deserialize {}: {} — schema may have drifted; regen if intended",
                p.display(),
                e
            ),
            Self::SchemaMismatch {
                path,
                found,
                expected,
            } => write!(
                f,
                "{}: schema_version {} (expected {}); regen all fixtures",
                path.display(),
                found,
                expected,
            ),
        }
    }
}

impl std::error::Error for GoldenError {}

/// Load a fixture by name. Panics with a clear message if the fixture
/// is missing or the schema has drifted — this is test-only.
pub fn load_golden<I, O>(name: &str) -> Golden<I, O>
where
    I: for<'de> Deserialize<'de>,
    O: for<'de> Deserialize<'de>,
{
    let path = fixture_path(name);
    match load_golden_result(&path) {
        Ok(g) => g,
        Err(e) => panic!("{}", e),
    }
}

fn load_golden_result<I, O>(path: &Path) -> Result<Golden<I, O>, GoldenError>
where
    I: for<'de> Deserialize<'de>,
    O: for<'de> Deserialize<'de>,
{
    if !path.exists() {
        return Err(GoldenError::Missing(path.to_path_buf()));
    }
    let bytes = std::fs::read(path).map_err(|e| GoldenError::Read(path.to_path_buf(), e))?;
    let g: Golden<I, O> = postcard::from_bytes(&bytes)
        .map_err(|e| GoldenError::Deserialize(path.to_path_buf(), e))?;
    if g.schema_version != SCHEMA_VERSION {
        return Err(GoldenError::SchemaMismatch {
            path: path.to_path_buf(),
            found: g.schema_version,
            expected: SCHEMA_VERSION,
        });
    }
    Ok(g)
}

/// Write a fixture file. Creates parent directories as needed. Used
/// by the `regen-goldens` binary; tests themselves should never call
/// this (it's not gated, but would silently pass on drifted outputs).
pub fn write_golden<I, O>(name: &str, input: I, output: O, tolerance: Option<f64>)
where
    I: Serialize,
    O: Serialize,
{
    let path = fixture_path(name);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("create fixtures dir");
    }
    let golden: Golden<I, O> = Golden {
        schema_version: SCHEMA_VERSION,
        input,
        output,
        tolerance,
        generated_at_iso: chrono::Utc::now().to_rfc3339(),
        source: format!("regen-goldens:{}", name),
    };
    let bytes = postcard::to_allocvec(&golden).expect("postcard serialize");
    std::fs::write(&path, bytes).expect("write fixture");
}

/// Assert that the generator applied to the fixture's input produces
/// the fixture's output, comparing with structural equality. Use for
/// discrete outputs (Vec<Chunk>, Vec<RawImport>, etc.).
///
/// Panics with a detailed message on mismatch. The fixture is loaded
/// fresh each call — no caching.
pub fn assert_match_exact<I, O>(name: &str, generator: impl FnOnce(&I) -> O)
where
    I: for<'de> Deserialize<'de>,
    O: for<'de> Deserialize<'de> + PartialEq + fmt::Debug,
{
    let g: Golden<I, O> = load_golden(name);
    let actual = generator(&g.input);
    if actual != g.output {
        panic!(
            "golden mismatch for `{}`\n  expected:\n{:#?}\n  actual:\n{:#?}\n  hint: run `cargo run --release -p pgmcp-testing --bin regen-goldens` if this drift is intentional",
            name, g.output, actual
        );
    }
}

/// Like [`assert_match_exact`] but uses a caller-supplied comparator
/// that returns the largest element-wise error. Use for outputs
/// containing f32/f64 fields where structural equality is too strict.
///
/// The fixture's `tolerance` field (set by the generator) is the
/// pass/fail threshold; `cmp` returns the empirical error for
/// logging.
pub fn assert_match_epsilon<I, O>(
    name: &str,
    generator: impl FnOnce(&I) -> O,
    cmp: impl Fn(&O, &O) -> f64,
) where
    I: for<'de> Deserialize<'de>,
    O: for<'de> Deserialize<'de> + fmt::Debug,
{
    let g: Golden<I, O> = load_golden(name);
    let actual = generator(&g.input);
    let err = cmp(&g.output, &actual);
    let tol = g.tolerance.unwrap_or_else(|| {
        panic!(
            "golden `{}` was written without a tolerance but assert_match_epsilon was called",
            name
        )
    });
    if !err.is_finite() || err > tol {
        panic!(
            "golden mismatch for `{}`: max error {} exceeds tolerance {}\n  expected:\n{:#?}\n  actual:\n{:#?}\n  hint: run `cargo run --release -p pgmcp-testing --bin regen-goldens` if this drift is intentional",
            name, err, tol, g.output, actual
        );
    }
}

/// State of a golden file after a regeneration run. Returned by
/// [`regen_golden`] for the `regen-goldens` binary's summary print.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RegenStatus {
    /// The file existed and the new bytes matched exactly.
    Unchanged,
    /// The file existed but its contents changed.
    Updated,
    /// The file didn't exist before and was just created.
    New,
}

impl fmt::Display for RegenStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unchanged => write!(f, "unchanged"),
            Self::Updated => write!(f, "updated"),
            Self::New => write!(f, "new"),
        }
    }
}

/// Byte-level comparison of the serialized envelope — detects any
/// change in input or output. Used by the regen binary to distinguish
/// `unchanged` from `updated`. Note: the `generated_at_iso` field
/// always drifts with each regeneration, so we compare against the
/// old envelope's input+output only.
///
/// This is implemented by deserializing the old file (if present) and
/// comparing its `postcard`-serialized input and output to the new
/// payload's. If either differs, we return `Updated`; otherwise
/// `Unchanged`.
pub fn regen_golden<I, O>(name: &str, input: I, output: O, tolerance: Option<f64>) -> RegenStatus
where
    I: Serialize + for<'de> Deserialize<'de>,
    O: Serialize + for<'de> Deserialize<'de>,
{
    let path = fixture_path(name);
    let old_io = if path.exists() {
        std::fs::read(&path).ok().and_then(|bytes| {
            postcard::from_bytes::<Golden<I, O>>(&bytes).ok().map(|g| {
                let io_bytes =
                    postcard::to_allocvec(&(g.input, g.output)).expect("re-serialize old io");
                (io_bytes, g.tolerance)
            })
        })
    } else {
        None
    };
    let new_io_bytes = postcard::to_allocvec(&(&input, &output)).expect("serialize new io");
    let status = match old_io {
        Some((old_bytes, old_tol)) => {
            if old_bytes == new_io_bytes && old_tol == tolerance {
                RegenStatus::Unchanged
            } else {
                RegenStatus::Updated
            }
        }
        None => RegenStatus::New,
    };
    write_golden(name, input, output, tolerance);
    status
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixtures_root_points_under_pgmcp_testing() {
        let root = fixtures_root();
        assert!(root.ends_with("pgmcp-testing/fixtures/golden"));
    }

    #[test]
    fn fixture_path_builds_component_subpath() {
        let p = fixture_path("chunker/example");
        assert!(p.ends_with("chunker/example.postcard"));
    }

    #[test]
    fn regen_new_then_unchanged_then_updated() {
        // Use a throwaway name under a "_sanity" namespace so we don't
        // collide with real fixtures. Clean up at the end.
        let name = "_sanity/regen_roundtrip";
        let path = fixture_path(name);
        let _ = std::fs::remove_file(&path);

        let first = regen_golden(name, 1i64, vec![1, 2, 3], None);
        assert_eq!(first, RegenStatus::New);

        let second = regen_golden(name, 1i64, vec![1, 2, 3], None);
        assert_eq!(second, RegenStatus::Unchanged);

        let third = regen_golden(name, 1i64, vec![1, 2, 4], None);
        assert_eq!(third, RegenStatus::Updated);

        // Clean up.
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn load_golden_panics_with_clear_message_when_missing() {
        let name = "_sanity/definitely_not_there";
        let path = fixture_path(name);
        let _ = std::fs::remove_file(&path);
        let result = std::panic::catch_unwind(|| {
            let _: Golden<i32, i32> = load_golden(name);
        });
        assert!(
            result.is_err(),
            "load_golden should panic when fixture is missing"
        );
    }

    #[test]
    fn schema_mismatch_detected() {
        let name = "_sanity/schema_mismatch";
        let path = fixture_path(name);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("mkdir");
        }
        let bad = Golden::<i32, i32> {
            schema_version: SCHEMA_VERSION.wrapping_add(1),
            input: 0,
            output: 0,
            tolerance: None,
            generated_at_iso: "2000-01-01T00:00:00Z".into(),
            source: "test".into(),
        };
        let bytes = postcard::to_allocvec(&bad).expect("serialize");
        std::fs::write(&path, bytes).expect("write");

        let err = load_golden_result::<i32, i32>(&path).expect_err("schema mismatch");
        assert!(matches!(err, GoldenError::SchemaMismatch { .. }));
        let _ = std::fs::remove_file(&path);
    }
}
