//! Classic software anti-patterns. All entries use `kind = "anti_pattern"`.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- Existing ----------
        pat(
            "god_object",
            "God Object",
            "anti_pattern",
            "object-oriented",
            "A single class or module knows too much and does too much.",
            "Spot responsibility concentration before it blocks change.",
            "Many unrelated behaviors and dependencies accumulate in one place.",
            "Split by cohesive responsibilities, ports, workflows, or domain concepts.",
            "Refactoring lowers coupling but requires careful migration tests.",
            &["object_oriented_programming", "procedural_programming"],
            &["antipattern", "coupling"],
            "https://en.wikipedia.org/wiki/God_object",
        ),
        pat(
            "spaghetti_code",
            "Spaghetti Code",
            "anti_pattern",
            "procedural",
            "Control flow and dependencies are tangled and hard to reason about.",
            "Recognize unstructured design that resists change.",
            "Implicit jumps, shared state, and mixed concerns obscure behavior.",
            "Introduce functions, modules, explicit state, and tests around seams.",
            "Incremental untangling is safer than a rewrite.",
            &["procedural_programming", "object_oriented_programming"],
            &["antipattern", "control_flow"],
            "https://en.wikipedia.org/wiki/Spaghetti_code",
        ),
        pat(
            "callback_hell",
            "Callback Hell",
            "anti_pattern",
            "event-driven",
            "Deeply nested callbacks obscure error handling and sequencing.",
            "Avoid unreadable asynchronous control flow.",
            "Async operations are composed only by nesting continuations.",
            "Use promises/futures, async/await, reactive operators, or named stages.",
            "Flattening improves clarity; cancellation and backpressure still need design.",
            &["event_driven_programming", "concurrent_programming"],
            &["antipattern", "async"],
            "https://en.wikipedia.org/wiki/Pyramid_of_doom_(programming)",
        ),
        pat(
            "shared_mutable_state",
            "Shared Mutable State",
            "anti_pattern",
            "concurrency",
            "Multiple concurrent actors mutate the same state without clear ownership.",
            "Avoid races and temporal coupling.",
            "Threads, callbacks, or services read/write shared data freely.",
            "Prefer ownership, message passing, immutability, transactions, or narrow locks.",
            "Improves safety; may require redesigning state boundaries.",
            &["concurrent_programming", "functional_programming"],
            &["antipattern", "state"],
            "https://en.wikipedia.org/wiki/Race_condition",
        ),
        pat(
            "premature_optimization",
            "Premature Optimization",
            "anti_pattern",
            "general",
            "Optimizing before the design bottleneck is known.",
            "Avoid complexity not justified by evidence.",
            "Speculative performance work distorts simple design.",
            "Measure first, isolate hotspots, and optimize behind stable interfaces.",
            "Optimization is still important when driven by data.",
            &[
                "procedural_programming",
                "object_oriented_programming",
                "functional_programming",
            ],
            &["antipattern", "performance"],
            "https://en.wikipedia.org/wiki/Program_optimization",
        ),
        // ---------- Classic anti-patterns ----------
        pat(
            "big_ball_of_mud",
            "Big Ball of Mud",
            "anti_pattern",
            "architecture",
            "A system without recognizable architecture: pervasive shortcuts, ad-hoc structure, and tangled dependencies.",
            "Recognize systems where every change risks unexpected breakage.",
            "Expedience and no architectural vigilance compound into structural rot.",
            "Stabilize seams with tests; carve out bounded contexts; apply strangler-fig modernization.",
            "Improvement is incremental and slow; rewrites usually fail.",
            &["object_oriented_programming", "procedural_programming"],
            &["antipattern", "architecture"],
            "http://www.laputan.org/mud/",
        ),
        pat(
            "lava_flow",
            "Lava Flow",
            "anti_pattern",
            "general",
            "Dead or experimental code left in the codebase 'just in case', now too risky to remove.",
            "Avoid the accumulation of frozen ad-hoc code.",
            "Quick prototypes shipped to production without cleanup; nobody owns the decision to remove them.",
            "Add tests around suspected dead paths; use coverage to confirm; delete and rerun.",
            "Smaller, comprehensible code; requires test discipline to remove safely.",
            &["object_oriented_programming", "procedural_programming"],
            &["antipattern", "dead_code"],
            "https://en.wikipedia.org/wiki/Lava_flow_(programming)",
        ),
        pat(
            "boat_anchor",
            "Boat Anchor",
            "anti_pattern",
            "general",
            "Code, libraries, or hardware kept in the project though no longer used.",
            "Recognize sunk-cost retention that drags maintenance.",
            "Discomfort at deleting expensive past work; fear of needing it later.",
            "Inventory dependencies; delete what's unused; archive in version control if memorability matters.",
            "Less ceremony; requires honest acknowledgement of past mistakes.",
            &["object_oriented_programming", "procedural_programming"],
            &["antipattern", "dead_code"],
            "https://en.wikipedia.org/wiki/Anti-pattern#Software_design",
        ),
        pat(
            "golden_hammer",
            "Golden Hammer",
            "anti_pattern",
            "general",
            "Applying a familiar tool/pattern to every problem regardless of fit.",
            "Recognize over-application of one approach.",
            "Designers' fluency in one paradigm overrides problem-shaped analysis.",
            "Match the tool to the problem; expand the team's toolkit; require justification for choice.",
            "Better-fit solutions; requires learning investment.",
            &[
                "object_oriented_programming",
                "procedural_programming",
                "functional_programming",
            ],
            &["antipattern", "design"],
            "https://en.wikipedia.org/wiki/Law_of_the_instrument",
        ),
        pat(
            "cargo_cult_programming",
            "Cargo Cult Programming",
            "anti_pattern",
            "general",
            "Imitating patterns or rituals without understanding the underlying reason.",
            "Recognize copy-paste from tutorials/SO without intent.",
            "Lack of understanding; pressure to ship; sample code accepted as canonical.",
            "Justify each idiom; remove ceremony that doesn't earn its keep; foster understanding through reviews.",
            "Leaner, intentional code; needs space and time for learning.",
            &[
                "object_oriented_programming",
                "procedural_programming",
                "functional_programming",
            ],
            &["antipattern", "culture"],
            "https://en.wikipedia.org/wiki/Cargo_cult_programming",
        ),
        pat(
            "hard_coding",
            "Hard Coding",
            "anti_pattern",
            "general",
            "Embedding configuration, environment assumptions, or magic values directly into source code.",
            "Recognize values that should be configurable or named.",
            "Quick prototypes turn into production with values baked in.",
            "Extract config to environment/files; name magic values as constants; validate inputs at boundaries.",
            "Flexible deployment; explicit constants improve readability.",
            &["procedural_programming", "object_oriented_programming"],
            &["antipattern", "configuration"],
            "https://en.wikipedia.org/wiki/Hard_coding",
        ),
        pat(
            "copy_paste_programming",
            "Copy-Paste Programming",
            "anti_pattern",
            "general",
            "Reusing code by duplication rather than abstraction.",
            "Recognize duplication-induced drift and bug-fix multiplication.",
            "Easier to copy than to find or design the right abstraction.",
            "Identify duplicates; extract to a shared function/module; update call sites.",
            "Centralized intent; over-eager dedup creates accidental coupling.",
            &["procedural_programming", "object_oriented_programming"],
            &["antipattern", "duplication"],
            "https://en.wikipedia.org/wiki/Anti-pattern#Programming",
        ),
        pat(
            "magic_pushbutton",
            "Magic Pushbutton",
            "anti_pattern",
            "object-oriented",
            "Business logic and side effects live in UI event handlers (e.g., button click handlers).",
            "Recognize where logic must move out of UI.",
            "Easy to attach behavior to events without designing the application layer.",
            "Extract logic into application services; UI dispatches to them and renders results.",
            "Testable logic; UI shrinks to presentation and dispatch.",
            &["object_oriented_programming"],
            &["antipattern", "ui"],
            "https://wiki.c2.com/?MagicPushButton",
        ),
        pat(
            "reinventing_the_wheel",
            "Reinventing the Wheel",
            "anti_pattern",
            "general",
            "Building something from scratch when a proven solution already exists.",
            "Recognize avoidable opportunity cost.",
            "NIH attitude or unfamiliarity with the ecosystem.",
            "Survey existing libraries/frameworks; integrate or extend before building anew.",
            "Faster delivery; vendor risk and integration cost must be evaluated honestly.",
            &["object_oriented_programming", "procedural_programming"],
            &["antipattern", "process"],
            "https://en.wikipedia.org/wiki/Reinventing_the_wheel",
        ),
        pat(
            "reinventing_the_square_wheel",
            "Reinventing the Square Wheel",
            "anti_pattern",
            "general",
            "Building a custom solution worse than existing alternatives.",
            "Recognize harmful 'simplifications' that miss subtle problems.",
            "Hubris or schedule pressure; lack of awareness of why the existing solution looks complex.",
            "Study why the canonical solution looks the way it does before replacing it.",
            "Better outcomes; reduces 'we'll just write our own' regret.",
            &["object_oriented_programming", "procedural_programming"],
            &["antipattern", "process"],
            "https://wiki.c2.com/?ReinventingTheSquareWheel",
        ),
        pat(
            "vendor_lock_in",
            "Vendor Lock-In",
            "anti_pattern",
            "architecture",
            "Tightly coupling architecture to a vendor's proprietary surface, making migration expensive.",
            "Be deliberate about which vendor abstractions are worth depending on.",
            "Adopting vendor SDKs without isolation; using proprietary features that lack open equivalents.",
            "Isolate vendor APIs behind interfaces; prefer open standards; evaluate exit costs.",
            "Strategic flexibility; abstractions cost up front.",
            &["distributed_systems"],
            &["antipattern", "cloud"],
            "https://en.wikipedia.org/wiki/Vendor_lock-in",
        ),
        pat(
            "stovepipe_system",
            "Stovepipe System",
            "anti_pattern",
            "architecture",
            "A vertical silo built without integration in mind, duplicating capabilities across the enterprise.",
            "Recognize duplication across systems and missed integration leverage.",
            "Teams build in isolation under deadlines; no enterprise architecture authority.",
            "Identify shared capabilities; align via published APIs and shared services; refactor toward platforms.",
            "Less duplication; political and migration effort required.",
            &["distributed_systems"],
            &["antipattern", "architecture"],
            "https://en.wikipedia.org/wiki/Stovepipe_system",
        ),
        pat(
            "architecture_astronaut",
            "Architecture Astronaut",
            "anti_pattern",
            "architecture",
            "Designing in such abstract terms that the design loses touch with concrete needs.",
            "Recognize over-engineered architectures with little user value.",
            "Pursuit of elegance untethered from product reality; resume-driven design.",
            "Anchor architecture choices in concrete requirements and measurable benefits.",
            "Pragmatic designs; less spec-doc volume.",
            &["object_oriented_programming"],
            &["antipattern", "design"],
            "https://www.joelonsoftware.com/2001/04/21/dont-let-architecture-astronauts-scare-you/",
        ),
        pat(
            "bikeshedding",
            "Bikeshedding (Law of Triviality)",
            "anti_pattern",
            "general",
            "Disproportionate time spent on trivial decisions while important ones get rubber-stamped.",
            "Recognize misallocated debate.",
            "Trivial topics are easy to opine on; hard ones require expertise.",
            "Time-box trivial decisions; promote important ones to explicit RFCs; defer to convention where possible.",
            "Better decision quality; requires meeting facilitation discipline.",
            &["object_oriented_programming"],
            &["antipattern", "culture"],
            "https://en.wikipedia.org/wiki/Law_of_triviality",
        ),
        pat(
            "yo_yo_problem",
            "Yo-Yo Problem",
            "anti_pattern",
            "object-oriented",
            "Following control flow up and down a long inheritance chain to understand behavior.",
            "Recognize hierarchies that hurt comprehension.",
            "Behavior is split across many overriding methods, scattered across an inheritance tree.",
            "Favor composition; flatten hierarchies; co-locate related behavior.",
            "Easier comprehension; some legitimate hierarchies need explicit navigation aids.",
            &["object_oriented_programming"],
            &["antipattern", "inheritance"],
            "https://en.wikipedia.org/wiki/Yo-yo_problem",
        ),
        pat(
            "poltergeist",
            "Poltergeists",
            "anti_pattern",
            "object-oriented",
            "Short-lived 'controller' objects whose sole purpose is to invoke methods on other objects.",
            "Recognize stateless, redundant intermediaries.",
            "Misapplied design patterns or fear of putting behavior on the data-owning object.",
            "Inline the calls; move behavior to the rightful owner; remove the empty wrapper.",
            "Less indirection; lower cognitive load.",
            &["object_oriented_programming"],
            &["antipattern", "design"],
            "https://en.wikipedia.org/wiki/Poltergeist_(computer_programming)",
        ),
        pat(
            "sequential_coupling",
            "Sequential Coupling (Temporal Coupling)",
            "anti_pattern",
            "object-oriented",
            "Methods must be called in a specific order or the object misbehaves.",
            "Recognize hidden ordering contracts.",
            "API design exposes a state machine through naked methods rather than a typestate.",
            "Encode required order via the type system (typestate), or supply higher-level operations that do the right sequence.",
            "Misuse becomes impossible; type complexity may increase.",
            &["object_oriented_programming"],
            &["antipattern", "api_design"],
            "https://en.wikipedia.org/wiki/Sequential_coupling",
        ),
        pat(
            "base_bean",
            "BaseBean",
            "anti_pattern",
            "object-oriented",
            "Using inheritance only to obtain utility methods that should be a helper or composition.",
            "Recognize inheritance abuse for code reuse.",
            "It's easier to extend `BaseBean` than to inject a utility.",
            "Replace base-class inheritance with composition or static helpers; reserve inheritance for IS-A.",
            "Cleaner hierarchies; less coupling to a utility base.",
            &["object_oriented_programming"],
            &["antipattern", "inheritance"],
            "https://wiki.c2.com/?BaseBean",
        ),
        pat(
            "object_cesspool",
            "Object Cesspool",
            "anti_pattern",
            "object-oriented",
            "An object pool that hands out objects in inconsistent states.",
            "Recognize unsanitized pool checkout.",
            "Recycled objects retain residual state from previous use.",
            "Reset state on checkout (or return); use immutable values where possible; document invariants.",
            "Safer reuse; per-checkout reset has cost.",
            &["object_oriented_programming", "concurrent_programming"],
            &["antipattern", "lifecycle"],
            "https://wiki.c2.com/?ObjectCesspool",
        ),
        pat(
            "constant_interface",
            "Constant Interface",
            "anti_pattern",
            "object-oriented",
            "Defining constants in an interface so classes can 'inherit' them via implements.",
            "Recognize misuse of inheritance for static value sharing.",
            "Saving a few characters of qualification looks cheap.",
            "Place constants in a class with private constructor (or `enum` / module-level consts); refer to them explicitly.",
            "Clear ownership; explicit references are easier to navigate.",
            &["object_oriented_programming"],
            &["antipattern", "java"],
            "https://en.wikipedia.org/wiki/Constant_interface",
        ),
        pat(
            "service_locator_antipattern",
            "Service Locator (Anti-Pattern)",
            "anti_pattern",
            "object-oriented",
            "A registry of services that components ask for dependencies, hiding actual collaborators.",
            "Recognize when service locators obscure dependency graphs (controversial; not always bad).",
            "Quick-fix to share services; avoids explicit constructor wiring.",
            "Prefer constructor dependency injection so collaborators are visible in signatures.",
            "Clearer dependency graphs and easier testing; some contexts (legacy, AOP, JNDI) legitimately need a locator.",
            &["object_oriented_programming"],
            &["antipattern", "ioc"],
            "https://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/",
        ),
        pat(
            "anemic_domain_model",
            "Anemic Domain Model",
            "anti_pattern",
            "ddd",
            "Domain objects are bags of getters/setters; logic lives in 'service' procedures.",
            "Recognize procedural code masquerading as OO and the missed expressiveness.",
            "Layered architectures often centralize behavior in services and starve domain types.",
            "Move invariants and behavior to entities/value objects; reserve services for cross-aggregate orchestration.",
            "Richer, safer domain; more design effort for the model.",
            &["object_oriented_programming"],
            &["antipattern", "ddd"],
            "https://martinfowler.com/bliki/AnemicDomainModel.html",
        ),
        pat(
            "inner_platform_effect",
            "Inner-Platform Effect",
            "anti_pattern",
            "general",
            "Building a configurable system so flexible it reimplements the platform underneath.",
            "Recognize over-generalization that competes with the host environment.",
            "Pursuit of total configurability; fear of releasing 'hard-coded' behavior.",
            "Limit configurability to actual needs; use the host's language/runtime for variation.",
            "Simpler, faster systems; reduces meta-meta complexity.",
            &["object_oriented_programming"],
            &["antipattern", "design"],
            "https://en.wikipedia.org/wiki/Inner-platform_effect",
        ),
        pat(
            "empty_catch",
            "Empty Catch (Exception Swallowing)",
            "anti_pattern",
            "general",
            "Catching an exception and doing nothing, hiding errors silently.",
            "Recognize lost diagnostics and silent failures.",
            "Quick fix to make a test pass or a compiler quiet.",
            "Log + rethrow, handle meaningfully, or use typed errors that force handling decisions.",
            "Better diagnostics; some narrow catches are legitimate (must be commented).",
            &["object_oriented_programming", "procedural_programming"],
            &["antipattern", "errors"],
            "https://en.wikipedia.org/wiki/Exception_handling_syntax",
        ),
        pat(
            "smoke_and_mirrors",
            "Smoke and Mirrors",
            "anti_pattern",
            "general",
            "Demos and stubs that imply working features when nothing is implemented behind them.",
            "Recognize marketing-driven illusions in technical demos.",
            "Pressure to show progress before it exists.",
            "Label stubs explicitly; gate access; track real implementation status separately from demo readiness.",
            "Honest signaling; reduces downstream surprise.",
            &["distributed_systems"],
            &["antipattern", "process"],
            "https://en.wikipedia.org/wiki/Smoke_and_mirrors",
        ),
        pat(
            "mushroom_management",
            "Mushroom Management",
            "anti_pattern",
            "general",
            "Keeping people in the dark and feeding them rumors instead of information.",
            "Recognize information-flow dysfunction in teams.",
            "Misplaced 'need-to-know' culture; poor leadership communication.",
            "Establish regular, transparent communication; share context broadly.",
            "Healthier teams and decisions; requires leadership change.",
            &["object_oriented_programming"],
            &["antipattern", "culture"],
            "https://en.wikipedia.org/wiki/Mushroom_management",
        ),
        // ---------- Distributed ----------
        pat(
            "distributed_monolith",
            "Distributed Monolith",
            "anti_pattern",
            "architecture",
            "Microservices that must be deployed together and share databases or in-process assumptions.",
            "Recognize the worst of both worlds: operational overhead with monolith coupling.",
            "Splitting a monolith into services without splitting the coupling.",
            "Identify true bounded contexts; introduce versioned contracts; co-locate truly coupled functionality.",
            "Independent deployability; takes serious refactoring to achieve.",
            &["distributed_systems"],
            &["antipattern", "microservices"],
            "https://www.thoughtworks.com/en-us/insights/blog/microservices/distributed-monolith",
        ),
        pat(
            "chatty_io",
            "Chatty I/O",
            "anti_pattern",
            "distributed",
            "Making many small calls instead of fewer larger ones.",
            "Recognize latency-amplifying call patterns.",
            "Naturally-grained method calls escape onto the network without batching.",
            "Batch requests; use GraphQL-style aggregation, projections, or bulk endpoints.",
            "Lower latency; risk of overfetching if batches aren't shaped per use case.",
            &["distributed_systems"],
            &["antipattern", "performance"],
            "https://learn.microsoft.com/en-us/azure/architecture/antipatterns/chatty-io/",
        ),
        pat(
            "fallacies_of_distributed_computing",
            "Fallacies of Distributed Computing",
            "anti_pattern",
            "distributed",
            "Assuming the network is reliable, latency is zero, bandwidth is infinite, secure, topology doesn't change, one admin, transport cost is zero, network is homogeneous.",
            "Recognize implicit assumptions that distributed systems violate.",
            "Single-process intuition transferred to distributed code.",
            "Design for failure: timeouts, retries with backoff, idempotency, partial failure, observability, encryption.",
            "Resilient systems; more code and configuration.",
            &["distributed_systems"],
            &["antipattern", "distributed"],
            "https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing",
        ),
        pat(
            "n_plus_one_query",
            "N+1 Query Problem",
            "anti_pattern",
            "persistence",
            "Loading a parent record triggers one query per child (1 + N).",
            "Recognize ORM-induced query explosions.",
            "Lazy loading walks a collection without batch fetch.",
            "Eager-load with a join, in-list fetch, or explicit batch loader (DataLoader); detect with query logs.",
            "Fewer round trips; over-eager loads can fetch unneeded data.",
            &["distributed_systems", "object_oriented_programming"],
            &["antipattern", "persistence", "performance"],
            "https://docs.djangoproject.com/en/5.0/topics/db/optimization/#use-select-related-and-prefetch-related",
        ),
        pat(
            "select_star",
            "SELECT * Abuse",
            "anti_pattern",
            "persistence",
            "Always selecting all columns regardless of need.",
            "Recognize wasted I/O, network, and brittle schema coupling.",
            "Convenience and habit.",
            "Project only required columns; revisit schemas; let column-store databases benefit from narrow projections.",
            "Lower cost and safer schema evolution; explicit column lists must be maintained.",
            &["distributed_systems"],
            &["antipattern", "sql"],
            "https://www.sqlservercentral.com/articles/why-i-dont-select-from-tables",
        ),
        pat(
            "eav_abuse",
            "EAV Abuse",
            "anti_pattern",
            "persistence",
            "Using Entity-Attribute-Value tables to avoid schema design, sacrificing types, constraints, and queryability.",
            "Recognize when EAV is being used as a shortcut instead of a deliberate choice.",
            "Avoidance of schema migrations or perceived flexibility needs.",
            "Use real columns where structure is known; reserve EAV for genuinely sparse/heterogeneous extension; consider JSONB.",
            "Better performance and constraints; explicit schema maintenance.",
            &["distributed_systems"],
            &["antipattern", "sql"],
            "https://www.red-gate.com/simple-talk/databases/sql-server/database-administration-sql-server/bad-carma-the-entity-attribute-value-model-and-the-pivot-table-anti-pattern/",
        ),
        pat(
            "thundering_herd",
            "Thundering Herd",
            "anti_pattern",
            "distributed",
            "Many clients wake up simultaneously after an event and overwhelm shared resources.",
            "Recognize synchronized retry/recovery storms.",
            "Cache expiration, broker reconnect, or scheduled jobs aligned exactly at the same time.",
            "Add jitter; stagger retries; randomize ttls; cap fan-out; use single-flight for cache fills.",
            "Smooth recovery; deliberate randomness in scheduling.",
            &["distributed_systems"],
            &["antipattern", "resilience"],
            "https://en.wikipedia.org/wiki/Thundering_herd_problem",
        ),
        pat(
            "retry_storm",
            "Retry Storm",
            "anti_pattern",
            "distributed",
            "Aggressive retries against a struggling dependency amplify the original problem.",
            "Recognize self-inflicted DoS from naive retry logic.",
            "Default 'just retry' policies without limits or backoff.",
            "Bound retries; add exponential backoff with jitter; trip a circuit breaker; budget retries globally.",
            "Stable behavior under failure; some calls fail fast and require fallback handling.",
            &["distributed_systems"],
            &["antipattern", "resilience"],
            "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/",
        ),
        pat(
            "tight_coupling",
            "Tight Coupling",
            "anti_pattern",
            "general",
            "Modules depend on each other's internals or share a lot of types/state.",
            "Recognize change rippling across modules.",
            "Convenience access to internals; lack of interface design.",
            "Define narrow interfaces; reduce shared state; depend on abstractions.",
            "Independent change; some legitimately tight coupling exists (e.g., performance-critical pairs).",
            &["object_oriented_programming", "procedural_programming"],
            &["antipattern", "coupling"],
            "https://en.wikipedia.org/wiki/Coupling_(computer_programming)",
        ),
        pat(
            "magic_numbers",
            "Magic Numbers / Magic Strings",
            "anti_pattern",
            "general",
            "Unnamed literal values scattered through code with no explanation.",
            "Recognize hidden meaning and drift.",
            "Quick coding; rationale lost as the codebase ages.",
            "Promote to named constants in a single location; document the source of the value.",
            "Self-documenting code; constants need ownership.",
            &["procedural_programming", "object_oriented_programming"],
            &["antipattern", "readability"],
            "https://en.wikipedia.org/wiki/Magic_number_(programming)",
        ),
        pat(
            "big_design_up_front",
            "Big Design Up Front (BDUF)",
            "anti_pattern",
            "general",
            "Investing heavily in complete designs before any code, then sticking to the design despite learning.",
            "Recognize over-investment in pre-implementation design that misses real constraints.",
            "Discomfort with uncertainty; cultural expectations of 'complete' designs.",
            "Iterate via thin slices; document decisions as you go; revisit design as evidence accumulates.",
            "Lower cost of being wrong; some constraints require up-front modeling (safety/regulatory).",
            &["object_oriented_programming"],
            &["antipattern", "process"],
            "https://en.wikipedia.org/wiki/Big_Design_Up_Front",
        ),
        pat(
            "gold_plating",
            "Gold Plating",
            "anti_pattern",
            "general",
            "Adding features the customer didn't ask for and won't pay for, often at quality's expense.",
            "Recognize developer-driven scope creep.",
            "Pride, perfectionism, or boredom expressed as out-of-scope work.",
            "Document and ship what's specified; capture extra ideas in backlog; require justification for additions.",
            "Smaller, on-spec deliveries; ideas remain documented for later.",
            &["object_oriented_programming"],
            &["antipattern", "process"],
            "https://en.wikipedia.org/wiki/Gold_plating_(project_management)",
        ),
        pat(
            "speculative_generality_ap",
            "Speculative Generality",
            "anti_pattern",
            "general",
            "Adding extension points, parameters, or interfaces for hypothetical future needs.",
            "Recognize unrealized abstraction cost.",
            "Fear of being 'caught' without the extension when it's needed.",
            "Delete unused parameters/interfaces; reintroduce when a concrete second use appears.",
            "Less ceremony today; pay for actual variation when it shows up.",
            &["object_oriented_programming"],
            &["antipattern", "design"],
            "https://refactoring.guru/smells/speculative-generality",
        ),
        pat(
            "two_step_view_anti",
            "God UI Controller (Massive Controller)",
            "anti_pattern",
            "object-oriented",
            "A controller class accumulates all interactions for a screen, becoming a god object.",
            "Recognize bloated UI controllers.",
            "Lack of presentation layer; many actions naturally land in one controller.",
            "Split by use case; extract presenters/view models; introduce coordinators for navigation.",
            "Comprehensible controllers; more types to navigate.",
            &["object_oriented_programming"],
            &["antipattern", "ui"],
            "https://martinfowler.com/eaaCatalog/modelViewController.html",
        ),
        pat(
            "leaky_abstraction",
            "Leaky Abstraction",
            "anti_pattern",
            "general",
            "An abstraction that fails to fully hide the details below it, forcing callers to know them.",
            "Recognize abstractions that don't pull their weight.",
            "Implementation details bleed through because the abstraction can't model everything.",
            "Acknowledge the leak in documentation; tighten the abstraction or expose the underlying primitive directly.",
            "Realistic expectations for users; abstraction redesign cost.",
            &["object_oriented_programming"],
            &["antipattern", "abstraction"],
            "https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/",
        ),
        pat(
            "premature_abstraction",
            "Premature Abstraction",
            "anti_pattern",
            "general",
            "Introducing abstractions for variation that hasn't yet appeared.",
            "Recognize wrong-shape abstractions that lock in poor choices.",
            "Designers anticipate the wrong variations and bake them into types.",
            "Wait until two or three real use cases exist; extract the abstraction from concrete code.",
            "Better-fit abstractions; some up-front structure (e.g., DI seams) still pays off.",
            &["object_oriented_programming"],
            &["antipattern", "design"],
            "https://www.martinfowler.com/articles/preliminary.html",
        ),
        pat(
            "feature_creep_ap",
            "Feature Creep",
            "anti_pattern",
            "general",
            "Continually adding features until product cohesion and quality erode.",
            "Recognize uncontrolled scope expansion.",
            "Pressure to keep adding; lack of vision or prioritization discipline.",
            "Establish product vision; gate features through evaluation; periodically prune the surface area.",
            "Sharper product; risk of underdelivering on real needs without discipline.",
            &["object_oriented_programming"],
            &["antipattern", "product"],
            "https://en.wikipedia.org/wiki/Feature_creep",
        ),
        pat(
            "happy_path_only",
            "Happy-Path-Only Coding",
            "anti_pattern",
            "general",
            "Implementing the success path and ignoring error and edge cases.",
            "Recognize fragile code that breaks at the first unexpected input.",
            "Schedule pressure; tests focus on success cases.",
            "Enumerate error and boundary cases; encode them in types/tests; design failure modes deliberately.",
            "Robust software; more code paths to maintain.",
            &["procedural_programming", "object_oriented_programming"],
            &["antipattern", "robustness"],
            "https://en.wikipedia.org/wiki/Happy_path",
        ),
        pat(
            "exception_as_control_flow",
            "Exceptions as Control Flow",
            "anti_pattern",
            "general",
            "Using exceptions to drive normal, non-exceptional control flow.",
            "Recognize misuse that hurts performance and readability.",
            "Throw/catch is sometimes easier than designing a return type.",
            "Use Result/Option or explicit return values; reserve exceptions for truly exceptional conditions.",
            "Cleaner code; performance often improves significantly.",
            &["object_oriented_programming"],
            &["antipattern", "errors"],
            "https://wiki.c2.com/?DontUseExceptionsForFlowControl",
        ),
        // ---------- More anti-patterns ----------
        pat(
            "premature_pessimization",
            "Premature Pessimization",
            "anti_pattern",
            "general",
            "Writing code in ways that gratuitously hurt performance compared to a natural equivalent.",
            "Recognize habitual slow-by-default code.",
            "Defaults like copy-by-value, repeated allocation, unnecessary cloning are easy to write.",
            "Choose efficient defaults (move semantics, references, preallocation); don't optimize hot paths prematurely but don't slow them gratuitously either.",
            "Fast defaults; some forms (string concatenation) need profiling to confirm.",
            &["procedural_programming", "object_oriented_programming"],
            &["antipattern", "performance"],
            "https://en.wikipedia.org/wiki/Pessimization",
        ),
        pat(
            "nih_syndrome",
            "Not-Invented-Here (NIH) Syndrome",
            "anti_pattern",
            "general",
            "Avoiding external solutions out of distrust or pride, even when they would clearly serve.",
            "Recognize gratuitous re-implementation.",
            "Cultural preference for in-house work; fear of supply-chain risk.",
            "Evaluate external solutions on merit; build only when ROI is positive after considering maintenance.",
            "Faster delivery, smaller maintenance; vendor and supply-chain risk must be weighed honestly.",
            &["object_oriented_programming"],
            &["antipattern", "culture"],
            "https://en.wikipedia.org/wiki/Not_invented_here",
        ),
        pat(
            "knowledge_silos",
            "Knowledge Silos",
            "anti_pattern",
            "general",
            "Critical knowledge is held by single individuals, making them irreplaceable.",
            "Recognize organizational bus-factor risk.",
            "Specialization without documentation or knowledge transfer.",
            "Rotate roles; pair on critical systems; document decisions; insist on >1 reviewer for sensitive areas.",
            "Resilient org; takes effort to maintain.",
            &["object_oriented_programming"],
            &["antipattern", "culture"],
            "https://en.wikipedia.org/wiki/Information_silo",
        ),
        pat(
            "ivory_tower_architecture",
            "Ivory Tower Architecture",
            "anti_pattern",
            "architecture",
            "Architects produce designs disconnected from implementation realities, which engineers must work around.",
            "Recognize designs that haven't been tested against code.",
            "Architects don't write production code; feedback loops are slow.",
            "Require architects to ship code in the systems they design; rotate them through on-call.",
            "Realistic designs; reduced architect/engineer divide.",
            &["object_oriented_programming"],
            &["antipattern", "culture"],
            "https://www.martinfowler.com/articles/dont-confuse-architecture-with-engineering.html",
        ),
        pat(
            "resume_driven_development",
            "Resume-Driven Development",
            "anti_pattern",
            "general",
            "Choosing technology by what looks good on a resume rather than what fits the problem.",
            "Recognize technology choices not justified by problem fit.",
            "Career incentives reward 'experience with X' regardless of fit.",
            "Require architecture decision records (ADRs) with explicit trade-offs; prefer boring tech for unsexy problems.",
            "Right-fit tech; counter cultural pressures.",
            &["object_oriented_programming"],
            &["antipattern", "culture"],
            "https://www.rdd.dev/",
        ),
        pat(
            "distant_object_antipattern",
            "Distant Object (LoD Violation)",
            "anti_pattern",
            "object-oriented",
            "Code reaches through several object boundaries (`a.b().c().d()`) instead of asking immediate neighbors.",
            "Recognize Law-of-Demeter violations.",
            "Convenience access into object graphs spreads coupling.",
            "Apply Hide Delegate; expose operations on the immediate friend; refactor chains into single calls.",
            "Lower coupling; possibly more middleman methods (use Remove Middle Man when appropriate).",
            &["object_oriented_programming"],
            &["antipattern", "coupling"],
            "https://en.wikipedia.org/wiki/Law_of_Demeter",
        ),
        pat(
            "orm_hell",
            "ORM Hell",
            "anti_pattern",
            "persistence",
            "Over-reliance on ORM auto-magic results in unpredictable SQL, N+1 queries, lazy-load surprises.",
            "Recognize when the ORM is hurting more than helping.",
            "ORMs hide SQL until it bites.",
            "Profile generated SQL; pin to explicit fetch strategies; use raw SQL / query builders for complex queries.",
            "Predictable performance; some loss of ORM convenience.",
            &["object_oriented_programming"],
            &["antipattern", "persistence"],
            "https://www.thoughtworks.com/insights/blog/orms-survival-guide",
        ),
        pat(
            "truck_factor_one",
            "Truck/Bus Factor of 1",
            "anti_pattern",
            "general",
            "A system that would be unmaintainable if any one person were unavailable.",
            "Recognize fragile critical dependencies on individuals.",
            "Specialization + lack of cross-training accumulates risk.",
            "Identify single-owner areas; pair / rotate / document; aim for truck factor ≥ 3 for critical systems.",
            "Resilient teams; slow to build.",
            &["object_oriented_programming"],
            &["antipattern", "culture"],
            "https://en.wikipedia.org/wiki/Bus_factor",
        ),
        pat(
            "dotmocracy",
            "Dotmocracy / Decision by Voting",
            "anti_pattern",
            "general",
            "Major engineering decisions decided by group voting without deep analysis.",
            "Recognize crowd-sourced architecture without rigor.",
            "Voting feels democratic but skips the deep review hard decisions need.",
            "Use ADRs with single decider + reviewers; surface trade-offs explicitly; reserve votes for genuinely subjective choices.",
            "Better decisions; some friction.",
            &["object_oriented_programming"],
            &["antipattern", "process"],
            "https://en.wikipedia.org/wiki/Idea_voting",
        ),
        pat(
            "premature_generalization",
            "Premature Generalization",
            "anti_pattern",
            "general",
            "Building an abstraction for variation that hasn't appeared yet.",
            "Recognize speculative scaffolding cost.",
            "Designers anticipate variation incorrectly.",
            "Wait for 2-3 concrete cases before extracting an abstraction; delete unused scaffolding (YAGNI).",
            "Real-fit abstractions; some 'fool me twice' moments.",
            &["object_oriented_programming"],
            &["antipattern", "design"],
            "https://martinfowler.com/articles/preliminary.html",
        ),
        pat(
            "hot_spot_hardcoding",
            "Hot-Spot Hardcoding",
            "anti_pattern",
            "general",
            "Embedding values that will obviously change (URLs, magic IDs, feature limits) directly in code.",
            "Recognize values that should be config but aren't.",
            "Convenience pressure during early dev; deferred extraction.",
            "Identify volatile values; promote to config/env/feature-flag with documented defaults.",
            "Flexible deployment; small initial effort.",
            &["procedural_programming"],
            &["antipattern", "configuration"],
            "https://en.wikipedia.org/wiki/Hard_coding",
        ),
        pat(
            "scope_creep_antipattern",
            "Scope Creep",
            "anti_pattern",
            "general",
            "Project scope continuously expands without commensurate timeline/budget adjustment.",
            "Recognize unmanaged change to project boundaries.",
            "Stakeholders add features; PMs say yes; engineering absorbs the slip.",
            "Document scope explicitly; require change-control for additions; trade scope for time/quality.",
            "Predictable delivery; sometimes requires saying no.",
            &["object_oriented_programming"],
            &["antipattern", "process"],
            "https://en.wikipedia.org/wiki/Scope_creep",
        ),
    ]
}
