//! Aspect-oriented programming patterns and idioms.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        pat(
            "pointcut_advice",
            "Pointcut and Advice",
            "pattern",
            "aspect-oriented",
            "Select join points and attach cross-cutting behavior.",
            "Modularize concerns like logging, tracing, transactions, or policy.",
            "The same concern is scattered through many modules.",
            "Declare pointcuts that match join points and advice that runs around them.",
            "Reduces scattering; matching must be precise and discoverable.",
            &["aspect_oriented_programming"],
            &["aop", "crosscutting"],
            "https://en.wikipedia.org/wiki/Aspect-oriented_programming",
        ),
        pat(
            "aspect_weaving",
            "Aspect Weaving",
            "pattern",
            "aspect-oriented",
            "Compose aspects into base code at compile, load, or runtime.",
            "Apply cross-cutting behavior without editing core modules.",
            "A concern should be applied consistently across many call sites.",
            "Use a weaver/proxy mechanism to insert advice at matched join points.",
            "Centralizes policy; debugging woven behavior can be harder.",
            &["aspect_oriented_programming"],
            &["aop"],
            "https://en.wikipedia.org/wiki/Aspect-oriented_programming",
        ),
        pat(
            "crosscutting_concern",
            "Crosscutting Concern",
            "principle",
            "aspect-oriented",
            "A requirement (logging, security, transactions) that affects many parts of an application.",
            "Recognize where AOP or other modularization techniques apply.",
            "Crosscutting concerns tangled into core modules duplicate logic and obscure intent.",
            "Identify crosscutting concerns up front; modularize via aspects, interceptors, decorators, or middleware.",
            "Cleaner core; new mechanism (AOP/middleware) adds tooling.",
            &["aspect_oriented_programming"],
            &["aop", "concern"],
            "https://en.wikipedia.org/wiki/Cross-cutting_concern",
        ),
        pat(
            "join_point",
            "Join Point",
            "pattern",
            "aspect-oriented",
            "A well-defined point in program execution where advice can be attached.",
            "Specify exactly where crosscutting behavior is applied.",
            "Without a model of join points, AOP becomes ad-hoc and unpredictable.",
            "Identify the set of join points your AOP system supports (method call, field access, exception handler, etc.).",
            "Predictable AOP semantics; system-dependent join-point model.",
            &["aspect_oriented_programming"],
            &["aop"],
            "https://en.wikipedia.org/wiki/Join_point",
        ),
        pat(
            "around_advice",
            "Around Advice",
            "pattern",
            "aspect-oriented",
            "Advice that surrounds a join point and can choose to run the original, skip it, or wrap it.",
            "Implement transactions, retries, caching, or measurements around method calls.",
            "Before/after advice can't conditionally skip or transform the wrapped call.",
            "Use `@Around`; receive a `ProceedingJoinPoint`; call `proceed()` zero or more times with modified args.",
            "Maximum flexibility; ordering and exception handling must be designed.",
            &["aspect_oriented_programming"],
            &["aop", "advice"],
            "https://eclipse.dev/aspectj/doc/latest/progguide/semantics-advice.html",
        ),
        pat(
            "inter_type_declaration",
            "Inter-Type Declaration",
            "pattern",
            "aspect-oriented",
            "Declare members (fields, methods) on existing types from an aspect.",
            "Augment classes with crosscutting interface implementations.",
            "Modifying source for every type to add a crosscutting capability is impractical.",
            "Use AspectJ's `declare parents` / `declare field` to add methods or interface implementations from an aspect.",
            "Powerful retrofit; introduces hidden members surprising to readers.",
            &["aspect_oriented_programming"],
            &["aop"],
            "https://eclipse.dev/aspectj/doc/latest/progguide/semantics-declare.html",
        ),
        pat(
            "fragile_pointcut",
            "Fragile Pointcut",
            "anti_pattern",
            "aspect-oriented",
            "An aspect accidentally matches too much or breaks when code is renamed.",
            "Avoid invisible cross-cutting behavior drift.",
            "Pointcuts depend on brittle names, broad wildcards, or unstable structure.",
            "Use narrow semantic annotations, tests, and documented pointcut contracts.",
            "Safer aspects trade some convenience for explicitness.",
            &["aspect_oriented_programming"],
            &["antipattern", "aop"],
            "https://en.wikipedia.org/wiki/Aspect-oriented_programming",
        ),
        pat(
            "interceptor",
            "Interceptor",
            "pattern",
            "aspect-oriented",
            "A reusable component placed between a caller and target to add behavior to the call.",
            "Apply crosscutting concerns (auth, logging, metrics) to many call paths.",
            "Cross-cutting concerns added to each handler manually drift apart.",
            "Define interceptor chains (JAX-RS filters, Spring HandlerInterceptors, gRPC interceptors, middleware) ordered by responsibility.",
            "Composable crosscutting; ordering and short-circuiting semantics need design.",
            &["aspect_oriented_programming", "object_oriented_programming"],
            &["aop", "middleware"],
            "https://en.wikipedia.org/wiki/Interceptor_pattern",
        ),
    ]
}
