//! HTTP/REST/gRPC/GraphQL API design patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- Architectural styles ----------
        pat(
            "rest",
            "REST",
            "pattern",
            "api_design",
            "Resource-oriented HTTP API using URIs, HTTP methods, and standard status codes.",
            "Build interoperable APIs that leverage HTTP semantics.",
            "Ad-hoc HTTP services duplicate caching, status, and method semantics.",
            "Model resources as nouns; methods as verbs (GET/POST/PUT/PATCH/DELETE); use standard status codes; cacheable when applicable.",
            "Wide tooling support; pure REST is rarer than 'JSON-over-HTTP-RPC' in practice.",
            &["distributed_systems"],
            &["api", "rest", "http"],
            "https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm",
        ),
        pat(
            "hateoas",
            "HATEOAS (Hypermedia as the Engine of Application State)",
            "pattern",
            "api_design",
            "Responses include links to next-state actions, so clients discover capabilities at runtime.",
            "Decouple clients from URL structure and workflow knowledge.",
            "Hardcoded URL/state coupling breaks when API evolves.",
            "Embed `_links` or RFC 8288 Link headers in responses; clients follow rels rather than constructing URLs.",
            "Evolvable APIs; learning curve and tooling shortage hurt adoption.",
            &["distributed_systems"],
            &["api", "rest", "hypermedia"],
            "https://en.wikipedia.org/wiki/HATEOAS",
        ),
        pat(
            "json_api",
            "JSON:API",
            "pattern",
            "api_design",
            "Specification for JSON responses (resource objects, relationships, sparse fieldsets, pagination, errors).",
            "Standardize REST response shape across teams and clients.",
            "Ad-hoc JSON shapes force per-API client code.",
            "Adopt JSON:API spec; use libraries that conform; let clients leverage standard tools.",
            "Cross-team consistency; opinionated shape may feel heavy for simple endpoints.",
            &["distributed_systems"],
            &["api", "rest", "spec"],
            "https://jsonapi.org/",
        ),
        pat(
            "openapi_swagger",
            "OpenAPI / Swagger",
            "pattern",
            "api_design",
            "Declarative API specification (YAML/JSON) that documents endpoints, schemas, and auth; generates clients/servers.",
            "Single source of truth for API contracts.",
            "Drift between code and docs is common.",
            "Author OpenAPI specs (spec-first or codegen-from-code); generate clients/servers; gate releases on spec changes.",
            "Powerful tooling and clients; spec must stay current.",
            &["distributed_systems"],
            &["api", "spec", "tooling"],
            "https://www.openapis.org/",
        ),
        pat(
            "grpc",
            "gRPC",
            "pattern",
            "api_design",
            "HTTP/2-based RPC with Protocol Buffers; supports streaming and strict schemas.",
            "Build high-throughput, strongly-typed service-to-service APIs.",
            "REST/JSON imposes parsing and bandwidth overhead for internal RPC.",
            "Define `.proto` schemas; generate clients/servers; use HTTP/2 multiplexing; consider gRPC-Web for browsers.",
            "Performant and strict; ecosystems outside backend (browsers) need bridges.",
            &["distributed_systems"],
            &["api", "rpc", "grpc"],
            "https://grpc.io/docs/what-is-grpc/introduction/",
        ),
        pat(
            "graphql_dataloader",
            "GraphQL DataLoader",
            "pattern",
            "api_design",
            "Per-request batching and caching of fetches to avoid N+1 queries when resolving GraphQL fields.",
            "Eliminate the GraphQL N+1 problem.",
            "Naive resolvers fire one DB query per object in a list.",
            "Wrap fetches in a DataLoader instance per request; resolvers `.load(id)`; loader batches in one tick.",
            "Eliminates N+1 with minimal code change; loader scope must be per-request.",
            &["distributed_systems"],
            &["api", "graphql", "performance"],
            "https://github.com/graphql/dataloader",
        ),
        // ---------- Reliability ----------
        pat(
            "idempotency_key",
            "Idempotency Key",
            "pattern",
            "api_design",
            "Client-supplied unique key for a request so the server can dedupe retries.",
            "Make POST-style operations safely retriable.",
            "Network retries can charge a card twice or duplicate orders.",
            "Require `Idempotency-Key` header; server records (key → response) for a TTL; returns cached response on retry.",
            "Safe at-least-once clients; storage and TTL of keys must be designed.",
            &["distributed_systems"],
            &["api", "reliability", "idempotency"],
            "https://stripe.com/docs/api/idempotent_requests",
        ),
        pat(
            "cursor_pagination",
            "Cursor Pagination",
            "pattern",
            "api_design",
            "Pagination by opaque cursor encoding the last seen row's keys; clients follow next/prev links.",
            "Stable pagination over changing data.",
            "Offset/limit pagination skips or duplicates rows under inserts/deletes.",
            "Encode cursor (e.g., `(id, created_at)` base64); server decodes and queries with WHERE `(id, created_at) > cursor` ORDER BY.",
            "Consistent; cursors are opaque and not arbitrary jumpable.",
            &["distributed_systems"],
            &["api", "pagination"],
            "https://relay.dev/graphql/connections.htm",
        ),
        pat(
            "keyset_pagination",
            "Keyset Pagination",
            "pattern",
            "api_design",
            "Paginate by a stable composite key (created_at + id); clients request rows after that key.",
            "Constant-time deep pagination on indexed keys.",
            "OFFSET pagination grows in cost with offset.",
            "Build query: `WHERE (created_at, id) > (?, ?) ORDER BY (created_at, id) LIMIT N`; return the last row's key for next call.",
            "Fast and stable; can't jump to arbitrary page N.",
            &["distributed_systems"],
            &["api", "pagination", "sql"],
            "https://use-the-index-luke.com/no-offset",
        ),
        pat(
            "offset_pagination",
            "Offset Pagination",
            "pattern",
            "api_design",
            "Pagination by absolute offset (`?page=5&size=20`).",
            "Allow random-access pagination.",
            "Random-access UX (jump to page 10) requires offsets.",
            "Implement `LIMIT size OFFSET (page-1)*size`; consider total count.",
            "Familiar UX; degrades with depth; inconsistent under writes.",
            &["distributed_systems"],
            &["api", "pagination"],
            "https://en.wikipedia.org/wiki/Pagination",
        ),
        pat(
            "sparse_fieldsets",
            "Sparse Fieldsets",
            "pattern",
            "api_design",
            "Let clients request only specific fields per resource (e.g., `?fields[user]=id,email`).",
            "Reduce payload size and processing.",
            "Returning full resources wastes bandwidth on rich models.",
            "Adopt JSON:API `fields[type]=` or GraphQL field selection; server filters response.",
            "Smaller payloads; server-side serialization must respect the filter.",
            &["distributed_systems"],
            &["api", "performance"],
            "https://jsonapi.org/format/#fetching-sparse-fieldsets",
        ),
        pat(
            "api_versioning",
            "API Versioning",
            "principle",
            "api_design",
            "Strategy for evolving an API without breaking existing clients (URI / header / media-type).",
            "Roll out breaking changes safely.",
            "Breaking changes without versioning break clients silently.",
            "Choose URI versions (`/v2/`), Accept header (`application/vnd.api.v2+json`), or media types; document sunset policy.",
            "Predictable evolution; maintaining multiple versions has ongoing cost.",
            &["distributed_systems"],
            &["api", "versioning"],
            "https://www.troyhunt.com/your-api-versioning-is-wrong-which-is/",
        ),
        // ---------- Real-time ----------
        pat(
            "webhook",
            "Webhook",
            "pattern",
            "api_design",
            "Server pushes events to a client-registered URL.",
            "Replace polling with push-based delivery.",
            "Clients waste resources polling for low-frequency events.",
            "Sign payloads (HMAC); retry with exponential backoff; require receivers to be idempotent; document timeouts.",
            "Real-time and cheap; receivers must be public, signed, and idempotent.",
            &["distributed_systems", "event_driven_programming"],
            &["api", "webhooks"],
            "https://en.wikipedia.org/wiki/Webhook",
        ),
        pat(
            "long_polling",
            "Long Polling",
            "pattern",
            "api_design",
            "Client opens a request; server holds it until data is available or timeout.",
            "Get near-real-time push semantics over plain HTTP/1.1.",
            "Repeated short polling is inefficient.",
            "Server holds the request up to a timeout; closes immediately when data is ready; client reconnects.",
            "Works through legacy proxies; resource usage on idle connections.",
            &["distributed_systems", "event_driven_programming"],
            &["api", "http"],
            "https://en.wikipedia.org/wiki/Push_technology#Long_polling",
        ),
        pat(
            "server_sent_events",
            "Server-Sent Events (SSE)",
            "pattern",
            "api_design",
            "HTTP streaming with the `text/event-stream` content type for server-to-client push.",
            "Push updates to browsers without WebSocket complexity.",
            "Pure HTTP request/response can't stream updates.",
            "Server emits `event:`/`data:` lines; client uses EventSource API; supports auto-reconnect with Last-Event-ID.",
            "Simple, works through proxies; one-way (server → client) only.",
            &["distributed_systems", "reactive_programming"],
            &["api", "streaming"],
            "https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events",
        ),
        pat(
            "websocket",
            "WebSocket",
            "pattern",
            "api_design",
            "Full-duplex, low-overhead protocol over a single TCP connection.",
            "Push and pull in real-time with bidirectional channels.",
            "Long polling and SSE don't support client-to-server push.",
            "Negotiate via HTTP Upgrade; send framed messages; design ping/pong and reconnect; consider sub-protocols.",
            "Real-time bidirectional; proxies and firewalls can interfere; stateful connection cost.",
            &["distributed_systems", "reactive_programming"],
            &["api", "streaming"],
            "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API",
        ),
        // ---------- HTTP semantics ----------
        pat(
            "rate_limit_headers",
            "Rate-Limit Headers",
            "pattern",
            "api_design",
            "Communicate rate-limit budget via response headers (X-RateLimit-Limit/Remaining/Reset) and 429 status.",
            "Let clients adapt to limits gracefully.",
            "Without headers, clients re-attempt blindly and waste budget.",
            "Adopt IETF draft headers or X-RateLimit-*; return 429 with Retry-After when exceeded.",
            "Cooperative clients; consistent header naming across services matters.",
            &["distributed_systems"],
            &["api", "rate_limiting"],
            "https://datatracker.ietf.org/doc/draft-ietf-httpapi-ratelimit-headers/",
        ),
        pat(
            "problem_json",
            "Problem+JSON (RFC 7807)",
            "pattern",
            "api_design",
            "Standardized error response format with `type`, `title`, `status`, `detail`, `instance`.",
            "Consistent error responses across services.",
            "Each service invents its own error shape, breaking clients.",
            "Return `application/problem+json` per RFC 7807; extend with custom fields.",
            "Predictable error parsing; legacy clients need adapters.",
            &["distributed_systems"],
            &["api", "errors", "spec"],
            "https://www.rfc-editor.org/rfc/rfc7807",
        ),
        pat(
            "http_caching_headers",
            "HTTP Caching Headers",
            "pattern",
            "api_design",
            "Use ETag / Last-Modified / Cache-Control / Vary to enable HTTP-layer caching.",
            "Let CDNs and clients cache safely.",
            "No-cache APIs hit origins for every request.",
            "Emit strong/weak ETag; set Cache-Control max-age/s-maxage; honor If-None-Match → 304.",
            "Major bandwidth savings; consistency model must be designed.",
            &["distributed_systems"],
            &["api", "caching", "http"],
            "https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching",
        ),
        pat(
            "conditional_request",
            "Conditional Request",
            "pattern",
            "api_design",
            "Use If-Match / If-None-Match / If-Modified-Since to express preconditions on read/write.",
            "Prevent lost updates and reduce bandwidth.",
            "Blind PUT overwrites; blind GET wastes bytes.",
            "Validate If-Match against current ETag → 412 if mismatch; respond 304 to If-None-Match match.",
            "Optimistic concurrency at HTTP layer; both client and server need to participate.",
            &["distributed_systems"],
            &["api", "http", "concurrency"],
            "https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests",
        ),
        pat(
            "cors",
            "CORS (Cross-Origin Resource Sharing)",
            "pattern",
            "api_design",
            "Server explicitly allows browser access from other origins via headers.",
            "Permit cross-origin XHR/fetch under the Same-Origin Policy.",
            "Browsers block cross-origin requests by default; this prevents legitimate web apps.",
            "Configure Access-Control-Allow-Origin and friends; handle preflight OPTIONS; never use wildcard with credentials.",
            "Enables cross-origin web apps; misconfig is a security risk.",
            &["distributed_systems"],
            &["api", "web", "security"],
            "https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS",
        ),
        // ---------- Bulk / batch ----------
        pat(
            "batch_endpoint",
            "Batch Endpoint",
            "pattern",
            "api_design",
            "Single endpoint accepting many sub-requests in one HTTP call.",
            "Cut round-trips for clients that perform many operations.",
            "Many small calls suffer HTTP overhead and rate limits.",
            "Define batch shape (e.g., array of operations); return array of results with per-op status.",
            "Higher throughput; partial-failure semantics must be explicit.",
            &["distributed_systems"],
            &["api", "performance"],
            "https://learn.microsoft.com/en-us/graph/json-batching",
        ),
        pat(
            "bulk_operation",
            "Bulk Operation Endpoint",
            "pattern",
            "api_design",
            "Endpoint that accepts many entities for a single resource type (bulk create/update/delete).",
            "Reduce overhead for ETL-style data loads.",
            "Per-row APIs are inappropriate for bulk loads.",
            "Provide a JSON-lines or array endpoint; document atomicity (all-or-nothing vs partial); return per-row results.",
            "Efficient loads; atomicity semantics must match user needs.",
            &["distributed_systems"],
            &["api", "performance"],
            "https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html",
        ),
        pat(
            "healthcheck_endpoint",
            "Healthcheck Endpoint (API)",
            "pattern",
            "api_design",
            "Lightweight endpoint that returns service health for orchestrators.",
            "Allow load balancers / orchestrators to gate traffic.",
            "Without a checkable endpoint, only TCP probes are possible.",
            "Implement `/health` (cheap) and `/health/deep` (checks dependencies); return JSON with subsystem status.",
            "Automated remediation; deep probes can cascade — design carefully.",
            &["distributed_systems"],
            &["api", "observability"],
            "https://microservices.io/patterns/observability/health-check-api.html",
        ),
        pat(
            "filter_query_conventions",
            "Filter / Search Query Conventions",
            "principle",
            "api_design",
            "Consistent query-parameter syntax for filters, sorts, and includes across endpoints.",
            "Make API exploration uniform and tools-friendly.",
            "Ad-hoc query syntax differs across endpoints.",
            "Adopt JSON:API or Stripe-style conventions: `filter[field]=value&sort=-created_at&include=author`.",
            "Cross-endpoint consistency; care with operator precedence.",
            &["distributed_systems"],
            &["api", "convention"],
            "https://stripe.com/docs/api",
        ),
    ]
}
