//! Architecture, distributed-system, cloud, DDD, EIP, and persistence patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- Existing event-driven / distributed ----------
        pat(
            "publish_subscribe",
            "Publish-Subscribe",
            "pattern",
            "event-driven",
            "Publish events to topics without direct producer-consumer coupling.",
            "Fan out notifications across independent consumers.",
            "Producers should not know every subscriber.",
            "Route events through a broker, topic, or event bus.",
            "Scales integration; delivery semantics and schema evolution matter.",
            &[
                "event_driven_programming",
                "distributed_systems",
                "reactive_programming",
            ],
            &["events", "messaging"],
            "https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern",
        ),
        pat(
            "event_sourcing",
            "Event Sourcing",
            "pattern",
            "event-driven",
            "Persist state changes as an append-only event log.",
            "Preserve history and reconstruct state.",
            "Current-state storage loses auditability and temporal context.",
            "Store domain events and fold them into read models.",
            "Strong audit trail; schema evolution and replay costs must be designed.",
            &["event_driven_programming", "distributed_systems"],
            &["events", "architecture"],
            "https://en.wikipedia.org/wiki/Domain-driven_design#Event_sourcing",
        ),
        pat(
            "transactional_outbox",
            "Transactional Outbox",
            "pattern",
            "event-driven",
            "Write state and outbound events in one local transaction.",
            "Avoid dual-write inconsistency between DB and message broker.",
            "A service must update data and publish an event atomically.",
            "Store an outbox row with the domain change and relay it asynchronously.",
            "Improves reliability; requires idempotent consumers and cleanup.",
            &["event_driven_programming", "distributed_systems"],
            &["events", "reliability"],
            "https://microservices.io/patterns/data/transactional-outbox.html",
        ),
        pat(
            "transactional_inbox",
            "Transactional Inbox",
            "pattern",
            "event-driven",
            "Persist incoming messages in an inbox table within the same transaction as state change.",
            "Achieve idempotent message consumption with at-least-once delivery.",
            "Consumers see duplicates and must dedupe consistently with state changes.",
            "Insert message id + state change in one DB transaction; reject duplicates by id.",
            "Idempotent consumption; requires a unique message identity and storage.",
            &["event_driven_programming", "distributed_systems"],
            &["events", "reliability"],
            "https://microservices.io/patterns/data/idempotent-receiver.html",
        ),
        pat(
            "saga",
            "Saga",
            "pattern",
            "distributed",
            "Coordinate a long-running transaction through local steps and compensations.",
            "Maintain consistency without distributed transactions.",
            "A business workflow spans multiple services or stores.",
            "Use choreography or orchestration to execute steps and compensating actions.",
            "Practical for microservices; compensation semantics must match the domain.",
            &["event_driven_programming", "distributed_systems"],
            &["microservices", "consistency"],
            "https://en.wikipedia.org/wiki/Saga_pattern",
        ),
        pat(
            "circuit_breaker",
            "Circuit Breaker",
            "pattern",
            "resilience",
            "Stop calling a failing dependency until it has time to recover.",
            "Prevent cascading failures and resource exhaustion.",
            "Retries against a degraded dependency amplify failure.",
            "Track failures and temporarily open the circuit, then probe recovery.",
            "Protects callers; thresholds and fallback behavior need tuning.",
            &["distributed_systems", "event_driven_programming"],
            &["resilience"],
            "https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern",
        ),
        pat(
            "retry_with_backoff",
            "Retry with Backoff",
            "pattern",
            "resilience",
            "Retry transient failures with increasing delay and jitter.",
            "Recover from temporary failures without creating retry storms.",
            "Immediate repeated retries overload a dependency that is already degraded.",
            "Bound retry attempts, increase delay, add jitter, and make operations idempotent.",
            "Improves resilience; bad retry budgets amplify failures.",
            &["distributed_systems", "concurrent_programming"],
            &["resilience", "retries"],
            "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/",
        ),
        pat(
            "anti_corruption_layer",
            "Anti-Corruption Layer",
            "pattern",
            "architecture",
            "Translate between incompatible domain models at a boundary.",
            "Protect a clean model from legacy or external semantics.",
            "A new subsystem must integrate with a model that would distort its design.",
            "Create an adapter/facade layer that maps requests and concepts both ways.",
            "Preserves domain clarity; mapping code can become substantial.",
            &["object_oriented_programming", "distributed_systems"],
            &["architecture", "ddd", "integration"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer",
        ),
        pat(
            "hexagonal_architecture",
            "Hexagonal Architecture (Ports & Adapters)",
            "pattern",
            "architecture",
            "Keep domain logic behind ports and adapters.",
            "Isolate business rules from UI, databases, and external services.",
            "Infrastructure concerns leak into core logic.",
            "Define ports at the core boundary and implement adapters outside.",
            "Improves testability and replaceability; boundaries can be overdrawn.",
            &["object_oriented_programming", "distributed_systems"],
            &["architecture", "ports_adapters"],
            "https://en.wikipedia.org/wiki/Hexagonal_architecture_(software)",
        ),
        pat(
            "strangler_fig",
            "Strangler Fig",
            "pattern",
            "architecture",
            "Incrementally replace legacy behavior behind a routing boundary.",
            "Modernize without a risky big-bang rewrite.",
            "A legacy system must keep running while parts are replaced.",
            "Route selected capabilities to new implementations and shrink the old system.",
            "Reduces migration risk; needs strong routing and observability.",
            &["distributed_systems", "object_oriented_programming"],
            &["modernization"],
            "https://martinfowler.com/bliki/StranglerFigApplication.html",
        ),
        // ---------- Cloud / distributed ----------
        pat(
            "cqrs",
            "Command Query Responsibility Segregation (CQRS)",
            "pattern",
            "architecture",
            "Split write (command) and read (query) models so they can scale and evolve independently.",
            "Optimize reads and writes separately when their shapes diverge.",
            "A single model serves both fast reads and complex commands and fits neither well.",
            "Have commands mutate a write-side model; project events into specialized read models.",
            "Tailored reads and writes; eventual consistency and dual schemas to maintain.",
            &["distributed_systems", "event_driven_programming"],
            &["architecture", "ddd"],
            "https://martinfowler.com/bliki/CQRS.html",
        ),
        pat(
            "bulkhead",
            "Bulkhead",
            "pattern",
            "resilience",
            "Isolate consumers into pools so one consumer's failure doesn't exhaust resources for others.",
            "Contain the blast radius of a misbehaving dependency.",
            "Shared resource pools let a slow caller starve all others.",
            "Allocate per-tenant or per-route pools (threads, connections, queues) with their own limits.",
            "Stronger isolation; underutilization compared to one shared pool.",
            &["distributed_systems"],
            &["resilience", "isolation"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/bulkhead",
        ),
        pat(
            "sidecar",
            "Sidecar",
            "pattern",
            "architecture",
            "Run a helper process alongside a main service in the same execution context.",
            "Add cross-cutting capabilities without modifying the main app.",
            "Each service re-implements common concerns (TLS, telemetry, config).",
            "Deploy a sidecar container/process that shares the lifecycle and namespace; the app uses its services.",
            "Polyglot reuse; sidecar adds resource overhead and operational coupling.",
            &["distributed_systems"],
            &["architecture", "cloud_native"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/sidecar",
        ),
        pat(
            "ambassador",
            "Ambassador",
            "pattern",
            "architecture",
            "A proxy that mediates outbound calls from a service to remote dependencies.",
            "Centralize cross-cutting concerns (retries, TLS, observability) for outbound calls.",
            "Each service implements its own outbound resilience and telemetry inconsistently.",
            "Deploy an ambassador proxy local to the service; the service makes plain calls; the ambassador handles policy.",
            "Consistent policy; another network hop and operational component.",
            &["distributed_systems"],
            &["architecture", "cloud_native"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/ambassador",
        ),
        pat(
            "backend_for_frontend",
            "Backend for Frontend (BFF)",
            "pattern",
            "architecture",
            "Provide a dedicated backend tailored to each frontend (mobile, web, partner).",
            "Avoid the lowest-common-denominator API problem.",
            "A single backend cannot efficiently serve diverse clients with different needs.",
            "Build one BFF per frontend that aggregates and shapes data for that client.",
            "Right-sized APIs; multiple backends to evolve in step with frontends.",
            &["distributed_systems"],
            &["architecture", "api"],
            "https://samnewman.io/patterns/architectural/bff/",
        ),
        pat(
            "api_gateway",
            "API Gateway",
            "pattern",
            "architecture",
            "A single entry point that routes, authenticates, and aggregates requests to internal services.",
            "Hide internal service topology behind a uniform edge.",
            "Clients must call many services directly and re-implement auth/rate-limit/aggregation.",
            "Deploy a gateway that handles authn/authz, rate limiting, routing, response composition.",
            "Simpler clients; the gateway can become a bottleneck or god component.",
            &["distributed_systems"],
            &["architecture", "api"],
            "https://microservices.io/patterns/apigateway.html",
        ),
        pat(
            "service_mesh",
            "Service Mesh",
            "pattern",
            "architecture",
            "Inject a network proxy into every service that handles mTLS, retries, telemetry, and routing.",
            "Move connectivity policy out of application code into a uniform infrastructure layer.",
            "Each service hand-codes resilience and observability inconsistently.",
            "Deploy a sidecar proxy (Envoy/linkerd-proxy) and a control plane that configures them.",
            "Uniform connectivity policy; operational complexity and per-call latency overhead.",
            &["distributed_systems"],
            &["architecture", "cloud_native"],
            "https://istio.io/latest/about/service-mesh/",
        ),
        pat(
            "service_discovery",
            "Service Discovery",
            "pattern",
            "architecture",
            "Lookup the network locations of service instances dynamically.",
            "Decouple clients from hard-coded addresses as instances scale or move.",
            "Hard-coded service URLs break with autoscaling, blue/green, or chaos events.",
            "Register instances on start; clients (or sidecars) resolve via the registry/DNS-SRV/mesh.",
            "Elastic topologies; the registry itself must be highly available.",
            &["distributed_systems"],
            &["architecture", "discovery"],
            "https://microservices.io/patterns/service-registry.html",
        ),
        pat(
            "service_registry",
            "Service Registry",
            "pattern",
            "architecture",
            "A central database of service instances with their network locations and health.",
            "Provide the source of truth for service discovery.",
            "Without a registry, peers cannot find each other dynamically.",
            "Run a registry (Consul, etcd, Zookeeper, Eureka); services register on start and heartbeat.",
            "Foundation for service discovery; the registry is a critical infrastructure component.",
            &["distributed_systems"],
            &["architecture", "discovery"],
            "https://microservices.io/patterns/service-registry.html",
        ),
        pat(
            "leader_election",
            "Leader Election",
            "pattern",
            "distributed",
            "Select a single coordinator among peer processes to perform unique-leader tasks.",
            "Avoid concurrent leaders and split-brain scenarios.",
            "Without a leader, multiple processes attempt the same exclusive work.",
            "Use a consensus service (Raft/Paxos/ZooKeeper/etcd) or lease-based election; renew leases.",
            "Single coordinator; loss of the lease must be handled gracefully (fencing tokens).",
            &["distributed_systems"],
            &["distributed", "consensus"],
            "https://en.wikipedia.org/wiki/Leader_election",
        ),
        pat(
            "consensus_raft",
            "Consensus (Raft / Paxos)",
            "pattern",
            "distributed",
            "Agree on a single ordered log of operations across a cluster despite failures.",
            "Provide strongly-consistent replicated state.",
            "Independent replicas diverge; ad-hoc quorum schemes are wrong in subtle ways.",
            "Use a Raft/Paxos library (etcd, ZooKeeper, Multi-Paxos) for the replicated log; build state machines on top.",
            "Strong correctness; latency and throughput bounded by the slowest majority.",
            &["distributed_systems"],
            &["distributed", "consensus"],
            "https://raft.github.io/",
        ),
        pat(
            "consistent_hashing",
            "Consistent Hashing",
            "pattern",
            "distributed",
            "Map keys to a ring of nodes so adding/removing a node only moves K/N keys.",
            "Scale partitioned data with minimal rebalance churn.",
            "Modular hashing reassigns most keys on resize, breaking caches and routing.",
            "Hash nodes and keys onto a ring; assign each key to the next node clockwise; use virtual nodes for balance.",
            "Smooth scaling; uneven load without enough virtual nodes.",
            &["distributed_systems"],
            &["distributed", "sharding"],
            "https://en.wikipedia.org/wiki/Consistent_hashing",
        ),
        pat(
            "sharding",
            "Sharding (Horizontal Partitioning)",
            "pattern",
            "distributed",
            "Split a dataset across nodes by key so each node owns a subset.",
            "Scale beyond the limits of a single node.",
            "A single node cannot hold or serve all data/traffic.",
            "Choose a shard key, hash or range partition, and route operations to the owning shard.",
            "Horizontal scale; cross-shard queries and rebalancing are hard.",
            &["distributed_systems"],
            &["distributed", "data"],
            "https://en.wikipedia.org/wiki/Shard_(database_architecture)",
        ),
        pat(
            "cache_aside",
            "Cache-Aside (Lazy Loading)",
            "pattern",
            "architecture",
            "Application reads from cache first; on miss, loads from store and populates cache.",
            "Speed up reads with a side cache.",
            "Every read goes to the slow store unnecessarily.",
            "On read: check cache; if miss, read DB and store in cache. On write: update DB and invalidate cache.",
            "Simple and broadly applicable; staleness windows and cache invalidation are still hard.",
            &["distributed_systems"],
            &["caching", "performance"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/cache-aside",
        ),
        pat(
            "read_through_cache",
            "Read-Through Cache",
            "pattern",
            "architecture",
            "Cache transparently loads data from the store on miss.",
            "Hide cache misses from application code.",
            "Cache-aside forces every reader to know about the store.",
            "Configure the cache with a loader function that fetches from the store on miss.",
            "Cleaner read path; the cache becomes a critical dependency for reads.",
            &["distributed_systems"],
            &["caching"],
            "https://en.wikipedia.org/wiki/Cache_(computing)#Read",
        ),
        pat(
            "write_through_cache",
            "Write-Through Cache",
            "pattern",
            "architecture",
            "Writes go to the cache and synchronously to the underlying store.",
            "Keep cache and store consistent on write.",
            "Cache-aside writes can leave the cache stale.",
            "On write: cache and store are updated in the same operation (cache library may handle this).",
            "Strong cache freshness; write latency includes both backends.",
            &["distributed_systems"],
            &["caching"],
            "https://en.wikipedia.org/wiki/Cache_(computing)#Write",
        ),
        pat(
            "write_behind_cache",
            "Write-Behind / Write-Back Cache",
            "pattern",
            "architecture",
            "Writes go to the cache first and are flushed to the store asynchronously.",
            "Smooth burst write load.",
            "Synchronous writes to the store are too slow for write-heavy workloads.",
            "Buffer writes in the cache; background workers persist to the store with batching/coalescing.",
            "Higher write throughput; data loss risk on crash before flush.",
            &["distributed_systems"],
            &["caching"],
            "https://en.wikipedia.org/wiki/Cache_(computing)#Write-back",
        ),
        pat(
            "cache_stampede_prevention",
            "Cache Stampede Prevention",
            "pattern",
            "resilience",
            "Coordinate cache refills so a single miss doesn't trigger many concurrent rebuilds.",
            "Avoid thundering herds against the origin when a hot key expires.",
            "Many concurrent requests miss simultaneously and all rebuild the value.",
            "Use single-flight, probabilistic early expiration, mutexes, or pre-refresh before expiry.",
            "Smooth load on the origin; small extra complexity in the cache client.",
            &["distributed_systems", "concurrent_programming"],
            &["caching", "resilience"],
            "https://en.wikipedia.org/wiki/Cache_stampede",
        ),
        pat(
            "materialized_view_arch",
            "Materialized View",
            "pattern",
            "architecture",
            "Precompute and store the result of a query so reads are fast.",
            "Trade write/refresh cost for read latency.",
            "Complex queries are too slow when run per request.",
            "Define a view; refresh it on schedule or on event; reads hit the materialized table.",
            "Predictable fast reads; staleness window and refresh strategy must match SLA.",
            &["distributed_systems", "declarative_programming"],
            &["caching", "data"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/materialized-view",
        ),
        pat(
            "throttling",
            "Throttling",
            "pattern",
            "resilience",
            "Limit the rate of work accepted per period to protect a service.",
            "Maintain service responsiveness under load spikes.",
            "Unbounded acceptance causes meltdown for all callers.",
            "Apply token-bucket/leaky-bucket limits per principal/route; respond 429 when exceeded.",
            "Predictable behavior under overload; limits must be tuned per dependency.",
            &["distributed_systems"],
            &["resilience", "rate_limiting"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/throttling",
        ),
        pat(
            "token_bucket",
            "Token Bucket",
            "pattern",
            "resilience",
            "Rate-limiting algorithm: tokens added at a fixed rate; each request consumes one.",
            "Allow controlled bursts up to bucket capacity while bounding average rate.",
            "Strict per-second limits don't allow useful burst behavior.",
            "Maintain a bucket of capacity C, refill rate R; reject or queue requests when empty.",
            "Smooths bursts; doesn't constrain instantaneous max-rate beyond bucket capacity.",
            &["distributed_systems"],
            &["rate_limiting"],
            "https://en.wikipedia.org/wiki/Token_bucket",
        ),
        pat(
            "leaky_bucket",
            "Leaky Bucket",
            "pattern",
            "resilience",
            "Rate-limiting algorithm: requests fill a bucket that drains at a constant rate.",
            "Bound average rate; smooth bursts into a steady output stream.",
            "Bursts overwhelm downstream that cannot handle non-constant load.",
            "Queue requests; serve them at a fixed rate; drop or shed when the queue overflows.",
            "Constant downstream load; latency depends on queue depth.",
            &["distributed_systems"],
            &["rate_limiting"],
            "https://en.wikipedia.org/wiki/Leaky_bucket",
        ),
        pat(
            "compensating_transaction",
            "Compensating Transaction",
            "pattern",
            "distributed",
            "Undo the effects of a partially-completed business transaction via inverse operations.",
            "Maintain consistency in long-running, cross-service workflows.",
            "Distributed 2PC is impractical or unavailable.",
            "For each step, define a compensating action; on failure, run compensations in reverse order.",
            "Practical eventual consistency; some operations cannot be fully undone (notifications sent).",
            &["distributed_systems", "event_driven_programming"],
            &["distributed", "consistency"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/compensating-transaction",
        ),
        pat(
            "claim_check",
            "Claim Check",
            "pattern",
            "event-driven",
            "Store a large payload externally and pass a reference (claim) through the message bus.",
            "Keep message systems efficient when payloads are large.",
            "Brokers and queues are not designed for multi-MB messages.",
            "Upload the payload to object storage; place its URL/id in the message; consumer fetches it.",
            "Keeps brokers fast; requires the external store to be reliable and access-controlled.",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/StoreInLibrary.html",
        ),
        pat(
            "competing_consumers",
            "Competing Consumers",
            "pattern",
            "event-driven",
            "Multiple consumers pull from one queue, each processing a different message in parallel.",
            "Scale message processing horizontally.",
            "A single consumer cannot keep up with the production rate.",
            "Run a pool of identical consumers reading from the same queue with shared offsets/acks.",
            "Scales throughput; ordering is sacrificed (unless per-key partitioning is added).",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip", "throughput"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/CompetingConsumers.html",
        ),
        pat(
            "idempotent_receiver",
            "Idempotent Receiver",
            "pattern",
            "event-driven",
            "Allow a consumer to safely handle the same message multiple times.",
            "Tolerate at-least-once delivery without duplicating side effects.",
            "Retries and broker semantics inevitably duplicate messages.",
            "Track processed message ids (inbox); reject duplicates; design state changes as idempotent.",
            "Correct under retries; storage and lookup cost grow with traffic.",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip", "reliability"],
            "https://microservices.io/patterns/communication-style/idempotent-consumer.html",
        ),
        pat(
            "dead_letter_channel",
            "Dead-Letter Channel",
            "pattern",
            "event-driven",
            "Route messages that cannot be processed to a separate queue for inspection.",
            "Avoid blocking the main queue with poison messages.",
            "Failing messages re-enter the queue and starve healthy traffic.",
            "On repeated failure, move the message to a DLQ with metadata about the failure.",
            "Keeps live processing healthy; DLQ requires its own monitoring and replay tooling.",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip", "reliability"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/DeadLetterChannel.html",
        ),
        pat(
            "content_based_router",
            "Content-Based Router",
            "pattern",
            "event-driven",
            "Inspect a message and route it to the appropriate destination based on its content.",
            "Centralize routing logic for heterogeneous messages.",
            "Producers shouldn't know all consumers; consumers shouldn't filter the entire stream.",
            "Run a router that reads message attributes and emits to one of N destinations.",
            "Clean separation; the router can grow into a hotspot if its logic gets too rich.",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/ContentBasedRouter.html",
        ),
        pat(
            "message_filter",
            "Message Filter",
            "pattern",
            "event-driven",
            "Discard messages from a stream that don't match a predicate.",
            "Let consumers receive only messages they care about.",
            "Consumers waste cycles reading and rejecting irrelevant messages.",
            "Insert a filter component or use broker-side filtering to drop non-matching messages.",
            "Cleaner consumers; filters add a hop and must be maintained as schemas evolve.",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/Filter.html",
        ),
        pat(
            "splitter",
            "Splitter",
            "pattern",
            "event-driven",
            "Break a composite message into a series of smaller messages.",
            "Process the parts of a batch independently.",
            "Batch messages defeat per-item routing and tracking.",
            "Run a splitter that emits one message per child element with correlation metadata.",
            "Per-item processing; need to correlate parts back into the whole.",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/Sequencer.html",
        ),
        pat(
            "aggregator",
            "Aggregator",
            "pattern",
            "event-driven",
            "Combine related messages into a single aggregated message.",
            "Reassemble parts produced by a Splitter or correlate scatter-gather replies.",
            "Downstream needs a complete object but only sees fragments.",
            "Buffer related messages keyed by correlation id; emit when the completeness criterion is met or timeout fires.",
            "Reconstructs wholes; correlation state and timeouts must be carefully bounded.",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/Aggregator.html",
        ),
        pat(
            "resequencer",
            "Resequencer",
            "pattern",
            "event-driven",
            "Reorder out-of-order messages into a guaranteed sequence by sequence number.",
            "Restore in-order processing downstream when ordering was lost.",
            "Parallel paths or partitions deliver messages out of order.",
            "Buffer messages keyed by sequence number; release in order when gaps are filled or a window times out.",
            "Restored ordering; buffer size and timeout policy bound latency vs. correctness.",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/Resequencer.html",
        ),
        pat(
            "scatter_gather_msg",
            "Scatter-Gather (Messaging)",
            "pattern",
            "event-driven",
            "Send a request to multiple recipients in parallel and aggregate their responses.",
            "Query multiple sources and combine results into one reply.",
            "Sequential requests waste time; clients shouldn't fan out themselves.",
            "Use a scatter component to send N requests and an aggregator to merge responses with correlation ids.",
            "Lower latency; the slowest responder bounds the aggregate time.",
            &["event_driven_programming", "distributed_systems"],
            &["messaging", "eip"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/BroadcastAggregate.html",
        ),
        pat(
            "choreography",
            "Choreography",
            "pattern",
            "distributed",
            "Services react to events emitted by their peers without a central coordinator.",
            "Build loosely-coupled workflows that scale by composition of independent listeners.",
            "Central orchestrators become a bottleneck and a coupling point.",
            "Publish domain events; each interested service reacts and emits further events as needed.",
            "Highly decoupled; harder to reason about end-to-end behavior and trace.",
            &["distributed_systems", "event_driven_programming"],
            &["microservices", "saga"],
            "https://microservices.io/patterns/data/saga.html",
        ),
        pat(
            "orchestration",
            "Orchestration",
            "pattern",
            "distributed",
            "A central component drives a workflow by calling services and reacting to their responses.",
            "Make multi-service workflows explicit and observable.",
            "Choreography is hard to debug and evolve when business workflows are complex.",
            "Implement a workflow engine or stateful orchestrator (Temporal/Step Functions) that calls services and tracks state.",
            "Clear workflow visibility; orchestrator is a critical component to operate.",
            &["distributed_systems", "event_driven_programming"],
            &["microservices", "saga"],
            "https://microservices.io/patterns/data/saga.html",
        ),
        pat(
            "two_phase_commit",
            "Two-Phase Commit (2PC)",
            "pattern",
            "distributed",
            "Coordinator asks participants to prepare; if all vote yes, asks all to commit; otherwise abort.",
            "Atomic commit across multiple resources.",
            "Independent commits leave the system inconsistent under failure.",
            "Use a transaction manager that runs prepare and commit phases across resource managers.",
            "Atomicity across resources; blocking under coordinator failure makes it unsuitable for many distributed cases.",
            &["distributed_systems"],
            &["distributed", "transactions"],
            "https://en.wikipedia.org/wiki/Two-phase_commit_protocol",
        ),
        pat(
            "heartbeat",
            "Heartbeat",
            "pattern",
            "distributed",
            "Peers send periodic 'alive' signals so others can detect failures.",
            "Discover dead nodes quickly enough to react.",
            "TCP keepalives are coarse and stack-level; application-level failure detection is needed.",
            "Each node emits a heartbeat at interval T; observers mark a peer dead after K missed heartbeats.",
            "Detects failures; risks false positives in network blips (use phi-accrual or hysteresis).",
            &["distributed_systems"],
            &["distributed", "failure_detection"],
            "https://www.cs.cornell.edu/courses/cs734/2007fa/papers/keidar.pdf",
        ),
        pat(
            "lease",
            "Lease",
            "pattern",
            "distributed",
            "Time-bounded grant of a privilege that expires unless renewed.",
            "Provide failure-recovery semantics for held resources.",
            "Permanent locks are stuck when the holder crashes.",
            "Grant a lease for duration T; lessee must renew before expiry; expiry releases the resource.",
            "Self-healing on crashes; clock skew and pause-the-world risks need fencing tokens.",
            &["distributed_systems"],
            &["distributed", "locking"],
            "https://www.usenix.org/legacy/event/osdi06/tech/full_papers/burrows/burrows.pdf",
        ),
        pat(
            "quorum",
            "Quorum",
            "pattern",
            "distributed",
            "Require agreement from a majority subset of nodes for operations to succeed.",
            "Tolerate failures while preserving consistency.",
            "Strict all-or-nothing replication can't tolerate node failures.",
            "Choose R + W > N to guarantee read/write overlap; tune for latency vs. consistency.",
            "Tolerates F failures with 2F+1 nodes; quorum unavailability blocks operations.",
            &["distributed_systems"],
            &["distributed", "consistency"],
            "https://en.wikipedia.org/wiki/Quorum_(distributed_computing)",
        ),
        pat(
            "fencing_token",
            "Fencing Token",
            "pattern",
            "distributed",
            "Attach a monotonically-increasing token to every privileged operation so the resource can reject stale holders.",
            "Prevent zombies (paused leaders) from corrupting state after their lease expired.",
            "Lease-based locking is unsafe when GC pauses or network partitions let an old holder act.",
            "Issue a token per acquisition; storage checks each operation's token vs. last accepted; reject stale.",
            "Safe leases; storage must support the fencing check.",
            &["distributed_systems"],
            &["distributed", "safety"],
            "https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html",
        ),
        pat(
            "serverless",
            "Serverless / Function as a Service",
            "pattern",
            "architecture",
            "Run code in stateless functions provisioned and scaled by the platform per request.",
            "Pay per execution; offload capacity planning to the platform.",
            "Provisioning long-running servers for sporadic load wastes capacity and operational effort.",
            "Package code as functions; deploy to FaaS (Lambda/Functions); use managed event sources.",
            "Elastic scale-to-zero; cold-start latency and vendor lock-in.",
            &["distributed_systems"],
            &["architecture", "cloud"],
            "https://en.wikipedia.org/wiki/Function_as_a_service",
        ),
        // ---------- Architectural styles ----------
        pat(
            "mvc",
            "Model-View-Controller (MVC)",
            "pattern",
            "architecture",
            "Separate data (Model), presentation (View), and input handling (Controller).",
            "Decouple UI and domain so each can change independently.",
            "Monolithic UI classes mix data, rendering, and input handling.",
            "Implement domain logic in models, render-only views, and controllers that translate input to model updates.",
            "Clear boundaries; controller bloat is common; many variants exist for different platforms.",
            &["object_oriented_programming"],
            &["architecture", "ui"],
            "https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller",
        ),
        pat(
            "mvp",
            "Model-View-Presenter (MVP)",
            "pattern",
            "architecture",
            "Variant of MVC where the Presenter holds UI logic and the View is passive.",
            "Make the view trivially testable by moving logic out of it.",
            "MVC controllers grow as soon as views forward inputs to them.",
            "Views expose state setters; Presenter receives events, updates Model, then pushes data back to View.",
            "Highly testable presenters; presenter <-> view interface adds boilerplate.",
            &["object_oriented_programming"],
            &["architecture", "ui"],
            "https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93presenter",
        ),
        pat(
            "mvvm",
            "Model-View-ViewModel (MVVM)",
            "pattern",
            "architecture",
            "View binds to a ViewModel that exposes observable state and commands.",
            "Use declarative data binding to keep views in sync with model state.",
            "Imperative view updates duplicate state in many places.",
            "Define a ViewModel with observable properties; bind view widgets directly to those properties.",
            "Clean UI updates; debugging binding glitches and lifecycle issues can be hard.",
            &["object_oriented_programming", "reactive_programming"],
            &["architecture", "ui"],
            "https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel",
        ),
        pat(
            "mvi",
            "Model-View-Intent (MVI)",
            "pattern",
            "architecture",
            "Unidirectional flow: Intents drive state changes that produce a new immutable Model rendered by the View.",
            "Make UI state explicit, deterministic, and time-travel-debuggable.",
            "MVVM/MVP allow many sources of state mutation, making bugs hard to trace.",
            "Treat state as immutable; reducer-style functions take (Intent, State) -> State; the View renders State.",
            "Predictable UI state; verbose for simple screens.",
            &[
                "object_oriented_programming",
                "reactive_programming",
                "functional_programming",
            ],
            &["architecture", "ui"],
            "https://hannesdorfmann.com/android/model-view-intent/",
        ),
        pat(
            "layered_architecture",
            "Layered (N-Tier) Architecture",
            "pattern",
            "architecture",
            "Organize code into horizontal layers (presentation, application, domain, infrastructure) that depend downward.",
            "Provide structure and a default place for everything.",
            "Without a layout convention, code accretes in arbitrary modules and dependencies become tangled.",
            "Define layers and enforce one-way dependencies; cross-layer access goes through the next layer.",
            "Easy onboarding; rigid layering can cause anemic middle layers and many pass-through methods.",
            &["object_oriented_programming"],
            &["architecture"],
            "https://en.wikipedia.org/wiki/Multitier_architecture",
        ),
        pat(
            "onion_architecture",
            "Onion Architecture",
            "pattern",
            "architecture",
            "Concentric layers with domain at the center; outer layers depend inward only.",
            "Make the domain independent of infrastructure and frameworks.",
            "Frameworks and DB libraries leak into business logic.",
            "Define an inner domain layer; outer layers (application, infrastructure, UI) depend on it via interfaces.",
            "Replaceable infrastructure; mapping between layers can be verbose.",
            &["object_oriented_programming"],
            &["architecture", "ddd"],
            "https://jeffreypalermo.com/2008/07/the-onion-architecture-part-1/",
        ),
        pat(
            "clean_architecture",
            "Clean Architecture",
            "pattern",
            "architecture",
            "Robert C. Martin's synthesis of onion/hexagonal with explicit Entities, Use Cases, Interface Adapters, Frameworks & Drivers.",
            "Keep policy at the center and detail at the edges, with dependency inversion crossing boundaries.",
            "Without a discipline, framework choices dominate the design.",
            "Define rings: Entities, Use Cases, Interface Adapters, Frameworks. Inner rings know nothing of outer rings.",
            "Resilient to framework changes; mapping classes and boilerplate at boundaries.",
            &["object_oriented_programming"],
            &["architecture", "ddd"],
            "https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html",
        ),
        pat(
            "microservices",
            "Microservices",
            "pattern",
            "architecture",
            "Build an application as a suite of small, independently deployable services around business capabilities.",
            "Scale teams and deployments independently.",
            "A monolith grows beyond the team's ability to coordinate releases and scale parts independently.",
            "Identify bounded contexts; carve out services with their own data and APIs; communicate via stable contracts.",
            "Team autonomy and selective scaling; distributed-systems complexity and operational overhead.",
            &["distributed_systems"],
            &["architecture", "microservices"],
            "https://martinfowler.com/articles/microservices.html",
        ),
        pat(
            "modular_monolith",
            "Modular Monolith",
            "pattern",
            "architecture",
            "A single deployable application internally organized into well-bounded modules.",
            "Keep deployment simple while preparing for future extraction.",
            "Microservices add ops cost the team cannot yet absorb.",
            "Define modules with explicit interfaces; forbid cross-module access except through them; co-deploy.",
            "Simple ops with clean module boundaries; module discipline must be enforced (build checks).",
            &["object_oriented_programming", "distributed_systems"],
            &["architecture"],
            "https://www.kamilgrzybek.com/blog/posts/modular-monolith-primer",
        ),
        pat(
            "microkernel_architecture",
            "Microkernel (Plug-in) Architecture",
            "pattern",
            "architecture",
            "A minimal core provides extension points where plug-ins implement features.",
            "Allow third-party extension and per-deployment customization.",
            "Hardcoded features prevent customization or third-party extension.",
            "Define an SPI; allow plug-ins to register against extension points; the core orchestrates them.",
            "Highly extensible; plug-in lifecycle, isolation, and versioning take work.",
            &["object_oriented_programming"],
            &["architecture", "extensibility"],
            "https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/architectural-principles#dependency-inversion",
        ),
        pat(
            "broker_architecture",
            "Broker Architecture",
            "pattern",
            "architecture",
            "Components communicate via a broker that knows how to locate and connect services.",
            "Decouple distributed clients and servers behind a registry/middleware.",
            "Hardcoded client-server bindings prevent dynamic discovery.",
            "Servers register with a broker; clients ask the broker to locate or invoke services.",
            "Dynamic topology; the broker is a critical and possibly bottleneck component.",
            &["distributed_systems"],
            &["architecture"],
            "https://en.wikipedia.org/wiki/Broker_pattern",
        ),
        pat(
            "peer_to_peer",
            "Peer-to-Peer (P2P)",
            "pattern",
            "architecture",
            "Symmetric peers act as both clients and servers without a central coordinator.",
            "Eliminate central server bottlenecks and single points of failure.",
            "Client-server scales hits the central node's capacity.",
            "Use gossip / DHT / overlay networks; every node provides and consumes services.",
            "Highly scalable and resilient; harder consistency, discovery, and security.",
            &["distributed_systems"],
            &["architecture"],
            "https://en.wikipedia.org/wiki/Peer-to-peer",
        ),
        pat(
            "primary_replica",
            "Primary-Replica (Master-Slave) Replication",
            "pattern",
            "distributed",
            "A single primary node accepts writes; replicas receive the change stream and serve reads.",
            "Scale reads and provide failover capacity.",
            "A single node can't serve all reads and writes.",
            "Configure replication; route writes to the primary; route reads to replicas with awareness of replica lag.",
            "Read scaling and failover; stale reads on replicas and primary failover complexity.",
            &["distributed_systems"],
            &["distributed", "replication"],
            "https://en.wikipedia.org/wiki/Master%E2%80%93slave_(technology)",
        ),
        pat(
            "blackboard_architecture",
            "Blackboard Architecture",
            "pattern",
            "architecture",
            "Independent knowledge sources cooperate by reading from and writing to a shared blackboard.",
            "Combine diverse algorithms on ill-structured problems (vision, speech).",
            "No single algorithm solves the problem end-to-end.",
            "Define a blackboard data store; let specialists update it when their preconditions are met; a controller schedules them.",
            "Flexible for AI/exploratory work; coordination and termination conditions are nontrivial.",
            &["object_oriented_programming"],
            &["architecture", "ai"],
            "https://en.wikipedia.org/wiki/Blackboard_(design_pattern)",
        ),
        // ---------- DDD / persistence ----------
        pat(
            "repository_pattern",
            "Repository",
            "pattern",
            "ddd",
            "Mediate between the domain and data mapping layers using a collection-like interface.",
            "Hide persistence behind a domain-facing collection abstraction.",
            "Domain code mixed with SQL/HTTP/ORM details becomes hard to test and reason about.",
            "Define repository interfaces in the domain; implement them in infrastructure.",
            "Cleaner domain; risk of dumb repositories that just forward to the ORM.",
            &["object_oriented_programming"],
            &["ddd", "persistence"],
            "https://martinfowler.com/eaaCatalog/repository.html",
        ),
        pat(
            "unit_of_work",
            "Unit of Work",
            "pattern",
            "ddd",
            "Maintain a list of objects affected by a business transaction and coordinate the writes.",
            "Batch persistence operations and apply them atomically.",
            "Scattered writes can be inconsistent and inefficient.",
            "Register dirty objects in a UoW; on commit, write them all in one transaction.",
            "Consistent writes and one transaction; UoW must be scoped per request/use case.",
            &["object_oriented_programming"],
            &["ddd", "persistence"],
            "https://martinfowler.com/eaaCatalog/unitOfWork.html",
        ),
        pat(
            "identity_map",
            "Identity Map",
            "pattern",
            "ddd",
            "Keep one in-memory instance per entity per session to avoid divergence and redundant loads.",
            "Make sure each entity is loaded once per UoW and references are consistent.",
            "Multiple instances of the same logical entity cause subtle divergence and update conflicts.",
            "Look up the entity in the map; load only on miss; return the cached instance otherwise.",
            "Consistency and fewer queries; map lifetime must match the unit of work.",
            &["object_oriented_programming"],
            &["ddd", "persistence"],
            "https://martinfowler.com/eaaCatalog/identityMap.html",
        ),
        pat(
            "active_record",
            "Active Record",
            "pattern",
            "ddd",
            "An object wraps a row in a database table and contains both data and behavior including persistence.",
            "Provide a simple persistence model for CRUD-heavy domains.",
            "Splitting domain and data access feels heavy for simple apps.",
            "Define classes per table; each instance is one row; methods on the class fetch/save rows.",
            "Quick to build; domain logic couples to table layout, complicating evolution.",
            &["object_oriented_programming"],
            &["ddd", "persistence"],
            "https://martinfowler.com/eaaCatalog/activeRecord.html",
        ),
        pat(
            "data_mapper",
            "Data Mapper",
            "pattern",
            "ddd",
            "A layer that transfers data between objects and a database while keeping them independent.",
            "Let domain objects ignore persistence entirely.",
            "Active Record couples domain to storage.",
            "Define a mapper per aggregate that loads/saves objects without leaking storage to the object.",
            "Clean domain; mapping code grows with object structure.",
            &["object_oriented_programming"],
            &["ddd", "persistence"],
            "https://martinfowler.com/eaaCatalog/dataMapper.html",
        ),
        pat(
            "aggregate_root",
            "Aggregate Root",
            "pattern",
            "ddd",
            "An aggregate is a cluster of objects treated as a single unit; the root is the only entry point.",
            "Enforce invariants and consistency boundaries explicitly.",
            "Allowing external references into the middle of an object cluster breaks invariants and complicates concurrency.",
            "Identify aggregate roots; external code references only roots; modifications go through the root.",
            "Clear consistency boundaries; one transaction per aggregate restricts large updates.",
            &["object_oriented_programming"],
            &["ddd"],
            "https://martinfowler.com/bliki/DDD_Aggregate.html",
        ),
        pat(
            "value_object",
            "Value Object",
            "pattern",
            "ddd",
            "An immutable object whose identity is defined by its values, not by an identifier.",
            "Express domain concepts (Money, Address, DateRange) precisely.",
            "Primitive obsession leaves business invariants implicit and scattered.",
            "Model the concept as an immutable class with value equality; reject invalid construction.",
            "Strong domain types; more classes to navigate.",
            &["object_oriented_programming", "functional_programming"],
            &["ddd", "types"],
            "https://martinfowler.com/bliki/ValueObject.html",
        ),
        pat(
            "entity_ddd",
            "Entity (DDD)",
            "pattern",
            "ddd",
            "An object whose identity persists across changes to its attributes.",
            "Track domain objects by stable identity, not equality of fields.",
            "Treating things-with-identity as value objects mishandles change and lifecycle.",
            "Give the entity an immutable identifier; equality is by id; track lifecycle and state changes explicitly.",
            "Correct identity semantics; identity strategy must be chosen carefully (db sequence, UUID, etc.).",
            &["object_oriented_programming"],
            &["ddd"],
            "https://www.domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf",
        ),
        pat(
            "domain_event",
            "Domain Event",
            "pattern",
            "ddd",
            "Capture something interesting that has happened in the domain as a first-class event.",
            "Make important business state changes explicit and reactable.",
            "Side effects are scattered in command handlers and hard to observe.",
            "Define event types; raise them inside aggregates; dispatch to subscribers after commit.",
            "Decouples reactions from state changes; event schemas need governance.",
            &["object_oriented_programming", "event_driven_programming"],
            &["ddd", "events"],
            "https://martinfowler.com/eaaDev/DomainEvent.html",
        ),
        pat(
            "bounded_context",
            "Bounded Context",
            "pattern",
            "ddd",
            "An explicit boundary inside which a particular domain model applies.",
            "Avoid forcing one giant model on all teams.",
            "A single shared model becomes ambiguous and contested across teams.",
            "Define context boundaries; use context maps to specify relations to other contexts.",
            "Healthy autonomy; integrations across contexts require explicit translation (often an ACL).",
            &["object_oriented_programming"],
            &["ddd", "architecture"],
            "https://martinfowler.com/bliki/BoundedContext.html",
        ),
        pat(
            "context_map",
            "Context Map",
            "pattern",
            "ddd",
            "A visualization of bounded contexts and the relationships between them.",
            "Make integration patterns between contexts explicit.",
            "Implicit context relations cause integration drift and surprise.",
            "Document each integration (ACL, OHS, Shared Kernel, Customer/Supplier, Conformist, Partnership).",
            "Shared understanding; the map must be kept current.",
            &["object_oriented_programming"],
            &["ddd", "architecture"],
            "https://www.domainlanguage.com/ddd/strategic-design/",
        ),
        pat(
            "domain_service",
            "Domain Service",
            "pattern",
            "ddd",
            "Behavior that doesn't naturally belong to an entity or value object lives in a stateless domain service.",
            "Capture domain operations without forcing them into an entity.",
            "Some operations span aggregates or have no single owner.",
            "Place the operation in a service class within the domain layer; keep it stateless and domain-pure.",
            "Cleaner aggregates; services can become a parking lot if not curated.",
            &["object_oriented_programming"],
            &["ddd"],
            "https://www.domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf",
        ),
        pat(
            "application_service",
            "Application Service",
            "pattern",
            "ddd",
            "Coordinates use-case execution by calling domain objects and infrastructure.",
            "Provide the orchestrating layer between request handlers and the domain.",
            "Use-case logic blends into controllers or aggregates.",
            "Define a thin service per use case that orchestrates aggregates, repositories, and transactions.",
            "Clear use-case seams; risk of becoming a transaction script if it absorbs domain logic.",
            &["object_oriented_programming"],
            &["ddd"],
            "https://www.domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf",
        ),
        pat(
            "money_pattern",
            "Money",
            "pattern",
            "ddd",
            "Represent monetary amounts with currency-aware operations as a Value Object.",
            "Avoid floating-point and currency-mixing errors.",
            "Floating-point arithmetic loses precision; currency mixing produces wrong totals.",
            "Use a Money(amount, currency) value object with integer minor units and explicit currency-conversion operations.",
            "Correctness in financial code; localization rounding rules need attention.",
            &["object_oriented_programming"],
            &["ddd", "value_object"],
            "https://martinfowler.com/eaaCatalog/money.html",
        ),
        pat(
            "service_layer",
            "Service Layer",
            "pattern",
            "ddd",
            "Define the application's boundary with a layer of services that establish its set of available operations.",
            "Provide a transactional, use-case-oriented API for clients.",
            "Direct UI-to-domain coupling makes it hard to add cross-cutting concerns or alternative clients.",
            "Define a service layer interface; controllers/UIs call services; services manage transactions and orchestration.",
            "Reusable use-case API; service layer can become anemic if domain richness leaks out.",
            &["object_oriented_programming"],
            &["ddd", "architecture"],
            "https://martinfowler.com/eaaCatalog/serviceLayer.html",
        ),
        pat(
            "table_module",
            "Table Module",
            "pattern",
            "ddd",
            "One class handles all rows of a table, holding data in a record set and providing operations on the whole set.",
            "Work with data set-oriented when domain behavior is naturally per-table.",
            "Active Record's per-row classes are awkward for set-oriented operations.",
            "Define one module per table; methods take row identifiers/keys and return record sets.",
            "Set-oriented domain logic; weak per-row encapsulation.",
            &["object_oriented_programming"],
            &["ddd", "persistence"],
            "https://martinfowler.com/eaaCatalog/tableModule.html",
        ),
        pat(
            "transaction_script",
            "Transaction Script",
            "pattern",
            "ddd",
            "Organize business logic by procedures, each handling one request from the presentation.",
            "Get simple apps shipping fast.",
            "Lightweight domains don't benefit from full Domain Model overhead.",
            "Write a procedure per use case that does its work top to bottom with direct DB calls.",
            "Easy to read for small cases; bloats and duplicates as complexity grows.",
            &["procedural_programming"],
            &["ddd", "persistence"],
            "https://martinfowler.com/eaaCatalog/transactionScript.html",
        ),
        pat(
            "lazy_load",
            "Lazy Load",
            "pattern",
            "ddd",
            "Defer loading a relationship until it is first accessed.",
            "Avoid eager fetching of object graphs the client may never read.",
            "Eager loading walks too much of the graph; lazy loading per-call hits N+1.",
            "Use a proxy that loads the relationship on first access (with care to avoid N+1).",
            "Cheap initial load; N+1 query traps and session lifetime issues.",
            &["object_oriented_programming"],
            &["ddd", "persistence"],
            "https://martinfowler.com/eaaCatalog/lazyLoad.html",
        ),
        pat(
            "optimistic_offline_lock",
            "Optimistic Offline Lock",
            "pattern",
            "ddd",
            "Detect concurrent modifications by checking a version field on save and rolling back conflicts.",
            "Permit concurrent edits without blocking; reconcile only at commit.",
            "Pessimistic locking across sessions hurts throughput and is fragile.",
            "Increment a version on every save; reject updates whose version no longer matches; surface conflicts.",
            "Higher throughput; users must handle conflict resolution.",
            &["object_oriented_programming"],
            &["ddd", "persistence", "concurrency"],
            "https://martinfowler.com/eaaCatalog/optimisticOfflineLock.html",
        ),
        pat(
            "pessimistic_offline_lock",
            "Pessimistic Offline Lock",
            "pattern",
            "ddd",
            "Acquire a lock at the start of an edit session and release on save/cancel.",
            "Prevent concurrent edits when conflicts are expensive to resolve.",
            "Optimistic locking forces users into conflict UIs in domains where edits are long and complex.",
            "Persist a lock record with owner and timeout; reject other editors while held.",
            "Conflict-free editing; risk of stuck locks if sessions die without release (use timeouts).",
            &["object_oriented_programming"],
            &["ddd", "persistence", "concurrency"],
            "https://martinfowler.com/eaaCatalog/pessimisticOfflineLock.html",
        ),
        // ---------- Additional DDD / EIP / architecture ----------
        pat(
            "process_manager",
            "Process Manager (Routing Saga)",
            "pattern",
            "ddd",
            "Stateful component that coordinates a long-running business workflow across services.",
            "Centralize complex multi-step orchestration that simple choreography can't express.",
            "Choreography hides the workflow inside many event handlers, making it hard to reason about.",
            "Implement as a stateful actor / event-handler that reacts to events, holds workflow state, and issues commands; persist state for recovery.",
            "Explicit, observable workflow; the process manager is critical infrastructure.",
            &["distributed_systems", "event_driven_programming"],
            &["ddd", "saga"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/ProcessManager.html",
        ),
        pat(
            "integration_vs_domain_events",
            "Integration Event vs Domain Event",
            "principle",
            "ddd",
            "Distinguish in-bounded-context domain events from cross-context integration events.",
            "Maintain bounded-context autonomy by translating events at the boundary.",
            "Sharing domain events directly couples consumers to producer's internal model.",
            "Domain events stay inside the context; convert to integration events (schema, naming, content) at the boundary.",
            "Loose coupling; mapping layer to maintain.",
            &["distributed_systems", "event_driven_programming"],
            &["ddd"],
            "https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation",
        ),
        pat(
            "event_carried_state_transfer",
            "Event-Carried State Transfer",
            "pattern",
            "event-driven",
            "Events carry the full current state of the changed entity, allowing subscribers to maintain a local copy without callbacks.",
            "Decouple consumers from the source service for reads.",
            "Notification-only events force consumers to call back for data, creating coupling and load.",
            "Publish full-state events on change; consumers maintain materialized views; trade larger payloads for autonomy.",
            "Read-time independence; payload size grows; consumers must reconcile out-of-order or duplicate events.",
            &["event_driven_programming", "distributed_systems"],
            &["events", "eip"],
            "https://martinfowler.com/articles/201701-event-driven.html#Event-CarriedStateTransfer",
        ),
        pat(
            "event_notification",
            "Event Notification",
            "pattern",
            "event-driven",
            "Events signal that something happened but carry minimal data; subscribers call back for details.",
            "Keep event payloads small and contracts narrow.",
            "Full-state events are bandwidth-heavy and lock the producer to a specific schema.",
            "Publish lightweight notifications with an id; subscribers fetch details via API as needed.",
            "Small contracts; tight coupling for data; subject to thundering-herd callbacks.",
            &["event_driven_programming", "distributed_systems"],
            &["events", "eip"],
            "https://martinfowler.com/articles/201701-event-driven.html#EventNotification",
        ),
        pat(
            "event_collaboration",
            "Event Collaboration",
            "pattern",
            "event-driven",
            "Multiple services participate in a business process by reacting to and emitting events, with no central orchestrator.",
            "Achieve highly decoupled multi-service workflows.",
            "Synchronous orchestration centralizes business logic.",
            "Each service owns its responsibility; reacts to upstream events; emits its own; the workflow emerges from the choreography.",
            "Maximally decoupled; hard to visualize end-to-end without tracing.",
            &["event_driven_programming", "distributed_systems"],
            &["events", "saga"],
            "https://martinfowler.com/eaaDev/EventCollaboration.html",
        ),
        pat(
            "multi_tenancy_shared_schema",
            "Multi-Tenancy: Shared Schema",
            "pattern",
            "ddd",
            "Single schema with tenant_id columns; all tenants share storage and indexes.",
            "Cheapest to operate when isolation requirements are modest.",
            "Per-tenant schemas/DBs multiply ops cost.",
            "Add tenant_id everywhere; require filters in every query; enforce via row-level security or framework middleware.",
            "Lowest cost; isolation depends on application discipline; noisy-neighbor risk.",
            &["distributed_systems"],
            &["ddd", "multi_tenancy"],
            "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/data-models",
        ),
        pat(
            "multi_tenancy_schema_per_tenant",
            "Multi-Tenancy: Schema per Tenant",
            "pattern",
            "ddd",
            "Each tenant gets its own schema in a shared database.",
            "Stronger isolation than shared-schema at moderate operational cost.",
            "Shared-schema offers weak isolation; DB-per-tenant is expensive.",
            "Provision a schema per tenant on signup; route queries via a connection or search path; migrate schemas in lockstep.",
            "Better isolation; migrations apply to many schemas.",
            &["distributed_systems"],
            &["ddd", "multi_tenancy"],
            "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/data-models",
        ),
        pat(
            "multi_tenancy_db_per_tenant",
            "Multi-Tenancy: Database per Tenant",
            "pattern",
            "ddd",
            "Each tenant has a dedicated database instance.",
            "Strongest isolation, sized per tenant, regulatory-compliant.",
            "Shared databases share blast radius across tenants.",
            "Provision a DB per tenant (or per shard of tenants); route via tenant→DB map; deploy migrations per DB.",
            "Best isolation; highest ops cost; harder cross-tenant queries.",
            &["distributed_systems"],
            &["ddd", "multi_tenancy"],
            "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/data-models",
        ),
        pat(
            "vertical_slice_architecture",
            "Vertical Slice Architecture",
            "pattern",
            "architecture",
            "Organize code by feature/use case (vertical slice) rather than by layer (horizontal).",
            "Co-locate the code for one user-visible feature.",
            "Layered architectures fragment a feature across UI, app, domain, and infrastructure folders.",
            "Group by feature: `features/CreateOrder/{Handler, Validator, Repository, ...}`; each slice owns its dependencies.",
            "High feature cohesion; possible duplication across slices.",
            &["object_oriented_programming"],
            &["architecture"],
            "https://www.jimmybogard.com/vertical-slice-architecture/",
        ),
        pat(
            "micro_frontends",
            "Micro-Frontends",
            "pattern",
            "architecture",
            "Compose the UI of several independently-deployed front-end applications.",
            "Let multiple teams own UI slices independently like microservices on the backend.",
            "Monolithic frontends bottleneck on a single build and deployment.",
            "Use module federation, iframes, or custom-elements to compose; standardize design system; consider shared state carefully.",
            "Independent team velocity; bundle size and design consistency are challenges.",
            &["distributed_systems"],
            &["architecture", "ui"],
            "https://micro-frontends.org/",
        ),
        pat(
            "modular_monolith_refinement",
            "Modular Monolith Boundaries",
            "principle",
            "architecture",
            "Even within a monolith, enforce strict module boundaries via build-time checks.",
            "Get microservice-style boundaries without the operational cost.",
            "Modules drift into each other without explicit enforcement.",
            "Use ArchUnit / NDepend / cargo deps to gate cross-module imports; designate public APIs per module; CI fails on violations.",
            "Clean monolith; some up-front tooling investment.",
            &["object_oriented_programming"],
            &["architecture"],
            "https://www.kamilgrzybek.com/blog/posts/modular-monolith-primer",
        ),
    ]
}
