//! Formal-languages and automata patterns: finite/pushdown/tree/ω-automata,
//! transducers, parser and lexer families, string-index automata (trie, DAWG,
//! suffix automaton, double-array, HAMT), edit-distance algorithms and
//! approximate-matching automata, phonetic encoders, abstract machines, term
//! rewriting, and probabilistic grammars.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- finite_automaton ----------
        pat(
            "deterministic_finite_automaton",
            "Deterministic Finite Automaton (DFA)",
            "pattern",
            "finite_automaton",
            "Recognize a regular language via a 5-tuple (Q, Σ, δ, q0, F) with a single next state per (state, symbol).",
            "Express a regular-language recognizer that runs in O(n) per input with no backtracking.",
            "Ad-hoc string scanners blur tokenization rules and resist composition, minimization, and equivalence checking.",
            "Encode states and a total transition table δ: Q×Σ→Q; advance one symbol at a time; accept when the final state is in F.",
            "Linear-time recognition and standard tooling; state explosion is possible when alphabets or modes proliferate.",
            &["formal_languages_and_automata"],
            &["automaton", "dfa", "regular_language"],
            "https://en.wikipedia.org/wiki/Deterministic_finite_automaton",
        ),
        pat(
            "nondeterministic_finite_automaton",
            "Nondeterministic Finite Automaton (NFA)",
            "pattern",
            "finite_automaton",
            "FA where δ: Q×(Σ∪{ε})→2^Q permits multiple successor states and ε-transitions.",
            "Capture regular languages compactly during construction; defer determinization or simulate the NFA directly.",
            "Direct DFA construction from regexes/grammars produces large or unwieldy state sets up front.",
            "Build an NFA from the structural form of the specification; recognize by tracking the set of reachable states or by determinization.",
            "Concise representation aligned with regular expressions; recognition cost is O(|Q|·n) per input unless determinized.",
            &["formal_languages_and_automata"],
            &["automaton", "nfa", "regular_language"],
            "https://en.wikipedia.org/wiki/Nondeterministic_finite_automaton",
        ),
        pat(
            "thompson_nfa_construction",
            "Thompson NFA Construction",
            "pattern",
            "finite_automaton",
            "Inductively build an ε-NFA from a regular expression with constant-sized fragments per operator.",
            "Compile a regex into an automaton whose size is linear in the regex length.",
            "Ad-hoc regex compilers conflate parsing and construction, making maintenance and correctness analysis hard.",
            "Translate each AST node (ε, char class, concat, union, Kleene-star) into a small NFA fragment with explicit start/accept states wired together with ε-edges.",
            "Linear-size NFA aligned 1:1 with the AST; an ε-elimination or subset-construction pass is still needed to recover a runnable DFA.",
            &["formal_languages_and_automata"],
            &["nfa", "regex", "compilation"],
            "https://en.wikipedia.org/wiki/Thompson%27s_construction",
        ),
        pat(
            "subset_construction",
            "Subset / Powerset Construction",
            "pattern",
            "finite_automaton",
            "Determinize an NFA by treating each reachable subset of NFA states as a single DFA state.",
            "Convert any NFA (including ε-NFA) into an equivalent DFA suitable for linear-time matching.",
            "NFA simulation costs O(|Q|·n); ε-closure work duplicates across runs.",
            "Compute ε-closures, materialize each reached subset as a DFA state, and tabulate transitions until closure; mark a subset accepting if it contains any NFA accepting state.",
            "Yields a deterministic recognizer at the risk of exponential state-set growth; typically followed by minimization.",
            &["formal_languages_and_automata"],
            &["determinization", "nfa", "dfa"],
            "https://en.wikipedia.org/wiki/Powerset_construction",
        ),
        pat(
            "hopcroft_dfa_minimization",
            "Hopcroft DFA Minimization",
            "pattern",
            "finite_automaton",
            "Partition-refinement algorithm that minimizes a DFA in O(n log n) where n = |Q|·|Σ|.",
            "Compute the unique minimal DFA equivalent to a given DFA to shrink tables and enable equivalence checks.",
            "Naive equivalence-class merging is O(n²) and fragile under streaming refinement.",
            "Start with a partition of accepting vs non-accepting states; repeatedly split blocks by preimages under δ⁻¹(symbol) using a worklist that processes the smaller side of each split.",
            "Minimal DFA with proven log-factor cost; implementation requires careful worklist accounting to keep the bound.",
            &["formal_languages_and_automata"],
            &["minimization", "dfa", "partition_refinement"],
            "https://en.wikipedia.org/wiki/DFA_minimization#Hopcroft.27s_algorithm",
        ),
        pat(
            "brzozowski_dfa_minimization",
            "Brzozowski DFA Minimization",
            "pattern",
            "finite_automaton",
            "Reverse, determinize, reverse, determinize — yields the minimal DFA via two determinization passes.",
            "Obtain a minimal DFA with a short correctness proof, especially convenient when an NFA is already at hand.",
            "Hopcroft minimization has the better worst-case bound but is intricate to implement and audit.",
            "Apply reverse(); subset_construction(); reverse(); subset_construction(); the result is the minimal DFA.",
            "Elegant and easy to verify; potentially exponential intermediate DFAs make worst-case cost worse than Hopcroft.",
            &["formal_languages_and_automata"],
            &["minimization", "dfa", "brzozowski"],
            "https://en.wikipedia.org/wiki/DFA_minimization#Brzozowski.27s_algorithm",
        ),
        pat(
            "alphabet_equivalence_partition",
            "Alphabet Equivalence Partitioning",
            "pattern",
            "finite_automaton",
            "Group input symbols whose DFA behavior is identical into a single column to compress transition tables.",
            "Reduce 256-column byte tables to ~10–20 columns while preserving recognition behavior.",
            "Dense byte tables waste cache and memory when the DFA only distinguishes a handful of character classes.",
            "Compute an equivalence relation on Σ from the column patterns of δ; assign each class a small index; emit a (state, class) → state table plus a symbol-to-class map.",
            "Dramatic table-size and cache-footprint wins; the extra indirection costs one byte lookup per transition.",
            &["formal_languages_and_automata"],
            &["dfa", "compaction", "lexer"],
            "https://en.wikipedia.org/wiki/Equivalence_class",
        ),
        pat(
            "nfa_epsilon_elimination",
            "NFA ε-Elimination and Dead-State Pruning",
            "pattern",
            "finite_automaton",
            "Remove ε-transitions, then prune unreachable and dead states from an automaton.",
            "Get a smaller, ε-free automaton suitable for tight simulation or as an input to determinization.",
            "ε-transitions inflate runtime work and break invariants assumed by some algorithms.",
            "Compute ε-closure(q) for each state, retarget δ accordingly, then delete states unreachable from q0 or from which no accepting state is reachable.",
            "Cleaner automaton with no semantic loss; closure computation can be a quadratic preprocessing step.",
            &["formal_languages_and_automata"],
            &["nfa", "cleanup", "epsilon"],
            "https://en.wikipedia.org/wiki/Nondeterministic_finite_automaton#Removing_epsilon-transitions",
        ),
        // ---------- pushdown ----------
        pat(
            "pushdown_automaton",
            "Pushdown Automaton (PDA)",
            "pattern",
            "pushdown",
            "Finite automaton augmented with a stack; recognizes exactly the context-free languages.",
            "Recognize nested or balanced structure (parentheses, blocks, function calls) that DFAs cannot.",
            "Regular automata cannot count or match brackets without unbounded state.",
            "Define δ: Q × (Σ∪{ε}) × Γ → 2^(Q × Γ*) over input symbol and stack-top; accept by final state or empty stack.",
            "Captures CFLs at the cost of nondeterminism in general; deterministic PDAs (DPDAs) are weaker but parse fast.",
            &["formal_languages_and_automata"],
            &["pda", "context_free", "stack"],
            "https://en.wikipedia.org/wiki/Pushdown_automaton",
        ),
        pat(
            "visibly_pushdown_automaton",
            "Visibly Pushdown Automaton (VPA)",
            "pattern",
            "pushdown",
            "PDA over an alphabet partitioned into call/return/internal symbols; stack moves are determined by the symbol class.",
            "Recognize and verify nested-word languages with closure under union, intersection, and complement.",
            "General PDAs are not closed under intersection or complement, blocking compositional reasoning over CFL fragments.",
            "Constrain the stack discipline: call symbols push, return symbols pop, internal symbols leave the stack alone; this yields a robust class of nested-word languages.",
            "Powerful for XML-shaped languages, schema validation, and interprocedural verification; harder to fit when the alphabet is not naturally typed.",
            &["formal_languages_and_automata"],
            &["vpa", "nested_words", "verification"],
            "https://en.wikipedia.org/wiki/Visibly_pushdown_language",
        ),
        pat(
            "weighted_pushdown_system",
            "Weighted Pushdown System (WPDS)",
            "pattern",
            "pushdown",
            "Pushdown system whose transitions carry semiring weights, modeling interprocedural dataflow as a fixpoint.",
            "Compute precise interprocedural meet-over-all-paths solutions for analyses expressible over a semiring.",
            "Forward dataflow does not naturally handle context-sensitive call/return matching.",
            "Encode call/return as PDS rules with weights drawn from a semiring; solve via saturation (pre*, post*) over weighted regular languages.",
            "Handles unbounded call stacks with precise context sensitivity; specialized engines (e.g. WALi) are usually required for performance.",
            &["formal_languages_and_automata"],
            &["wpds", "interprocedural", "semiring"],
            "https://en.wikipedia.org/wiki/Pushdown_automaton",
        ),
        // ---------- tree_automaton ----------
        pat(
            "tree_automaton",
            "Tree Automaton (top-down and bottom-up)",
            "pattern",
            "tree_automaton",
            "Finite-state recognizer that labels nodes of a ranked tree as it traverses the structure.",
            "Recognize tree languages such as XML schemas, type-system shapes, and AST validity conditions.",
            "Word automata cannot describe constraints over hierarchical structure.",
            "Define transitions per node-label and per child arity: bottom-up automata assign states to children first, top-down threads a state from the root downward.",
            "Bottom-up automata are determinizable and closed under boolean operations; top-down automata are more natural for traversals but generally nondeterministic.",
            &["formal_languages_and_automata"],
            &["tree", "xml", "schema"],
            "https://en.wikipedia.org/wiki/Tree_automaton",
        ),
        pat(
            "alternating_automaton",
            "Alternating Finite Automaton",
            "pattern",
            "tree_automaton",
            "Finite automaton whose transition function returns a boolean formula over successor states (∧ and ∨).",
            "Capture languages exponentially more concisely than NFAs while staying in the same expressive class.",
            "NFAs blow up under intersection and complement; AFAs absorb those operations natively.",
            "Allow δ to return existential and universal moves; a run is an alternation tree all of whose accepting leaves accept.",
            "Compact representation with native intersection and complementation; conversion to DFA may be doubly exponential.",
            &["formal_languages_and_automata"],
            &["alternating", "afa", "model_checking"],
            "https://en.wikipedia.org/wiki/Alternating_finite_automaton",
        ),
        // ---------- temporal ----------
        pat(
            "buchi_omega_automaton",
            "Büchi Automaton (ω-automaton)",
            "pattern",
            "temporal",
            "Finite automaton over infinite words; accepts iff some accepting state is visited infinitely often.",
            "Decide LTL satisfiability and model-check liveness properties of reactive systems.",
            "Finite-word automata cannot express \"always eventually\" or \"infinitely often\" properties.",
            "Translate LTL formulas to Büchi automata, then take the product with the system and check emptiness of the resulting Büchi language.",
            "Foundation of automata-theoretic model checking; complementation and determinization (Safra) are notoriously intricate.",
            &["formal_languages_and_automata"],
            &["buchi", "omega", "ltl", "model_checking"],
            "https://en.wikipedia.org/wiki/B%C3%BCchi_automaton",
        ),
        // ---------- transducer ----------
        pat(
            "finite_state_transducer",
            "Finite-State Transducer (FST)",
            "pattern",
            "transducer",
            "Finite automaton whose transitions emit output symbols, computing a relation Σ* × Δ*.",
            "Translate strings between alphabets in a compositional, debuggable way (lexers, normalizers, morphological analyzers).",
            "Hand-written string transducers entangle parsing and emission and resist reuse.",
            "Annotate each transition with (input symbol, output symbol); compose, intersect with FAs, and invert as needed.",
            "Composable string-to-string translations with linear runtime; some operations require ε-removal and care with non-functional relations.",
            &["formal_languages_and_automata"],
            &["fst", "transducer", "translation"],
            "https://en.wikipedia.org/wiki/Finite-state_transducer",
        ),
        pat(
            "weighted_finite_state_transducer",
            "Weighted Finite-State Transducer (WFST)",
            "pattern",
            "transducer",
            "FST whose transitions carry weights from a semiring; computes weighted relations.",
            "Encode probabilistic, edit-distance, or shortest-path models compositionally.",
            "Composing probabilistic lexers/parsers ad hoc loses associativity and complicates beam search.",
            "Use semirings (tropical for shortest path, log for negative log-prob, real for probability) on transitions; combine WFSTs by composition and project.",
            "Backbone of ASR, MT, and approximate-matching pipelines; numerical stability and weight-pushing require attention.",
            &["formal_languages_and_automata"],
            &["wfst", "semiring", "asr"],
            "https://en.wikipedia.org/wiki/Finite-state_transducer#Weighted_automata",
        ),
        pat(
            "wfst_composition",
            "WFST Composition",
            "pattern",
            "transducer",
            "Cascade two WFSTs T1 ∘ T2 by pairing states whose transitions share input/output symbols.",
            "Build pipeline models by composing reusable building blocks (lexicon, language model, edit model).",
            "Re-implementing a full pipeline as one monolithic FST is unmaintainable.",
            "Take the product over pairs of transitions whose output (T1) matches input (T2); insert ε-filters to handle ε-transitions consistently.",
            "Modular construction with clear semantics; intermediate transducers can grow large without weight pushing and pruning.",
            &["formal_languages_and_automata"],
            &["wfst", "composition", "pipeline"],
            "https://en.wikipedia.org/wiki/Finite-state_transducer",
        ),
        pat(
            "two_way_transducer",
            "Two-Way / Multi-Tape Transducer",
            "pattern",
            "transducer",
            "Transducer whose read head can move both directions, or that reads several tapes in parallel.",
            "Express transformations that require lookahead, lookbehind, or coordinated multi-input processing.",
            "Standard one-way FSTs cannot express many natural transducers (reversal, copy, alignment) compactly.",
            "Allow head moves ±1 (two-way) or use multiple coordinated tape heads with synchronization conventions.",
            "Greater expressivity and compactness; equivalence and minimization become harder, and some classes are equivalent to one-way FSTs only up to translation.",
            &["formal_languages_and_automata"],
            &["transducer", "two_way", "multi_tape"],
            "https://en.wikipedia.org/wiki/Finite-state_transducer",
        ),
        // ---------- parser ----------
        pat(
            "lr_parser",
            "LR Parser",
            "pattern",
            "parser",
            "Bottom-up shift-reduce parser driven by action/goto tables compiled from a CFG.",
            "Parse a large class of unambiguous CFGs in linear time with reproducible tables.",
            "Hand-rolled bottom-up parsers are error-prone and hard to update when the grammar changes.",
            "Compute LR(k) item sets, derive action and goto tables, drive a stack-based shift-reduce loop guided by the lookahead.",
            "Linear time and well-understood error reporting; table sizes can balloon and conflict resolution is non-local.",
            &["formal_languages_and_automata"],
            &["parser", "lr", "shift_reduce"],
            "https://en.wikipedia.org/wiki/LR_parser",
        ),
        pat(
            "lalr_parser",
            "LALR(1) Parser",
            "pattern",
            "parser",
            "LR(1) variant that merges states with identical cores, trading some lookahead precision for smaller tables.",
            "Get most of LR(1)'s power with table sizes close to SLR(1).",
            "Full LR(1) tables are unwieldy for production languages; SLR(1) rejects too many practical grammars.",
            "Build the LR(1) collection, merge mergeable states, recompute lookahead sets; emit the merged action/goto tables.",
            "Workhorse of yacc/bison/lalrpop with tractable table sizes; some LR(1) grammars become non-LALR(1) after merging.",
            &["formal_languages_and_automata"],
            &["parser", "lalr", "yacc"],
            "https://en.wikipedia.org/wiki/LALR_parser",
        ),
        pat(
            "glr_parser",
            "Generalized LR (GLR) Parser",
            "pattern",
            "parser",
            "LR parser that forks at conflicts and shares stacks via a graph-structured stack; accepts any CFG.",
            "Parse ambiguous, context-sensitive, or evolving grammars (e.g., C++) where LR(1)/LALR(1) cannot.",
            "Real languages have grammar conflicts that neither LR nor LALR can resolve.",
            "Maintain a worklist of parser stacks merged via a GSS; advance all viable parses in lockstep and reconcile at reductions.",
            "Handles ambiguity natively and degrades gracefully to linear time on LR(1) inputs; ambiguous parses must be ranked or disambiguated downstream.",
            &["formal_languages_and_automata"],
            &["parser", "glr", "ambiguity"],
            "https://en.wikipedia.org/wiki/GLR_parser",
        ),
        pat(
            "earley_parser",
            "Earley Chart Parser",
            "pattern",
            "parser",
            "Top-down chart parser that handles any CFG in O(n³) general / O(n²) unambiguous / O(n) deterministic time.",
            "Recognize ambiguous or arbitrary CFGs with a single, uniform algorithm.",
            "LR/LALR parsers reject many practical grammars; rolling per-grammar parsers is costly.",
            "Maintain an Earley set per input position; apply predict, scan, complete operations until closure; reconstruct parses from completed items.",
            "Robust and uniform; constants are higher than LR and memory consumption is per-position chart storage.",
            &["formal_languages_and_automata"],
            &["parser", "earley", "chart"],
            "https://en.wikipedia.org/wiki/Earley_parser",
        ),
        pat(
            "pratt_operator_precedence_parser",
            "Pratt Operator-Precedence Parser",
            "pattern",
            "parser",
            "Top-down parser using per-token left/right binding powers (nud, led) to drive precedence climbing.",
            "Parse expressions with rich operator precedence, mixfix syntax, and easy extensibility.",
            "Recursive-descent expression parsers explode in size and are hard to extend with new operators.",
            "Bind each token to nud (null denotation) and led (left denotation) functions plus numeric binding powers; loop while next token's left binding power exceeds the caller's right binding power.",
            "Compact, extensible expression parsers; integrates well with hand-written top-down parsers but is less mechanically derived than LR.",
            &["formal_languages_and_automata"],
            &["parser", "pratt", "precedence"],
            "https://en.wikipedia.org/wiki/Operator-precedence_parser",
        ),
        pat(
            "recursive_descent_parser",
            "Recursive-Descent Parser",
            "pattern",
            "parser",
            "Top-down predictive parser with one mutually recursive procedure per non-terminal.",
            "Get readable, debuggable parsers tightly coupled to the grammar.",
            "Generated tables can be hard to debug or extend with custom error recovery.",
            "Write one parsing function per non-terminal; peek at the next token to choose alternatives; consume tokens with explicit expect/accept helpers.",
            "Easy to write, debug, and extend with semantic predicates; left recursion needs grammar rewriting and inefficient backtracking is a hazard.",
            &["formal_languages_and_automata"],
            &["parser", "recursive_descent", "top_down"],
            "https://en.wikipedia.org/wiki/Recursive_descent_parser",
        ),
        pat(
            "packrat_parser",
            "Packrat Parser",
            "pattern",
            "parser",
            "Memoized recursive-descent parser realizing PEG semantics in linear time and space.",
            "Get PEG's deterministic, composable matching with guaranteed linear performance.",
            "Naive PEG implementations suffer exponential blowup on left-factoring choices.",
            "Memoize every (rule, position) pair on first evaluation and reuse on revisit; treat ordered choice as commit-on-first-success.",
            "Linear time at the cost of O(n·|G|) memory; deterministic semantics differ from CFGs in subtle ways.",
            &["formal_languages_and_automata", "functional_programming"],
            &["parser", "peg", "packrat", "memoization"],
            "https://en.wikipedia.org/wiki/Parsing_expression_grammar#Implementing_parsers_from_parsing_expression_grammars",
        ),
        pat(
            "graph_structured_stack",
            "Graph-Structured Stack (GSS)",
            "pattern",
            "parser",
            "Shared-prefix stack representation that lets GLR/Earley parsers merge equivalent partial parses.",
            "Avoid exponential blowup when multiple LR parser stacks share suffixes.",
            "Maintaining one stack per fork is exponential in the worst case for ambiguous grammars.",
            "Represent stacks as a DAG where edges carry stack symbols; merge nodes whose state and parents coincide; iterate shift/reduce against the DAG.",
            "Brings worst-case ambiguous parsing down to cubic; bookkeeping for parent edges and reductions over the DAG is intricate.",
            &["formal_languages_and_automata"],
            &["gss", "glr", "parser"],
            "https://en.wikipedia.org/wiki/Graph-structured_stack",
        ),
        pat(
            "incremental_glr_treesitter",
            "Incremental GLR Parsing (tree-sitter-style)",
            "pattern",
            "parser",
            "Reparse only the subtrees affected by an edit using a cached previous parse tree and span deltas.",
            "Support live editing of source code with sub-millisecond reparses on large files.",
            "Re-parsing the whole file on every keystroke is too slow for editor-grade tooling.",
            "Compute the dirty input range from edit deltas, descend into the cached parse tree, splice in the freshly parsed nodes, and rebalance summaries.",
            "Massive latency wins for editors and LSPs; the incremental algorithm and tree representation are complex to implement correctly.",
            &["formal_languages_and_automata"],
            &["parser", "incremental", "tree_sitter", "editor"],
            "https://tree-sitter.github.io/tree-sitter/",
        ),
        pat(
            "panic_mode_error_recovery",
            "Panic-Mode / Synchronization Error Recovery",
            "pattern",
            "parser",
            "On a syntax error, skip tokens until a sentinel set is reached, then resume parsing.",
            "Continue parsing after a syntax error to report cascading problems and offer better diagnostics.",
            "Stopping at the first parse error wastes information and frustrates users.",
            "Define synchronization tokens (e.g. `;`, `}`, statement starters); on error, skip until one is found and resume with the appropriate non-terminal.",
            "Simple to implement and effective for diagnostics; may produce spurious follow-on errors and need tuning per language.",
            &["formal_languages_and_automata"],
            &["parser", "error_recovery", "diagnostics"],
            "https://en.wikipedia.org/wiki/Recursive_descent_parser#Error_recovery",
        ),
        // ---------- lexer ----------
        pat(
            "maximal_munch_lexer",
            "Maximal-Munch Lexer",
            "pattern",
            "lexer",
            "Greedy longest-match scanner with a `last_accept` snapshot for backtracking on mismatch.",
            "Tokenize input deterministically with the canonical \"longest match wins\" rule.",
            "Eager-emit lexers misclassify keywords vs identifiers and operators of differing lengths.",
            "Run the DFA forward, recording the most recent accepting position; on stuck transition, rewind to last_accept and emit the corresponding token kind.",
            "Standard lexer semantics with predictable behavior; ambiguities between equal-length tokens still require tie-breaking rules.",
            &["formal_languages_and_automata"],
            &["lexer", "maximal_munch", "tokenization"],
            "https://en.wikipedia.org/wiki/Maximal_munch",
        ),
        pat(
            "dfa_codegen_lexer",
            "Table-Driven vs Direct-Coded DFA Lexer",
            "pattern",
            "lexer",
            "Choose between a dense δ table indexed by (state, symbol) and emitted switch/goto-style code per state.",
            "Pick the codegen strategy that matches the host language's branch-prediction and cache behavior.",
            "One-size-fits-all lexer codegen leaves performance on the table.",
            "Profile both: table-driven lexers minimize code size and let JITs prefetch; direct-coded lexers let the host compiler specialize comparisons and inline character-class checks.",
            "Direct-coded lexers often beat tables on modern CPUs; tables are more cache-friendly for very large alphabets and easier to mutate at runtime.",
            &["formal_languages_and_automata"],
            &["lexer", "codegen", "dfa"],
            "https://en.wikipedia.org/wiki/Lexical_analysis",
        ),
        // ---------- string_index ----------
        pat(
            "trie_prefix_tree",
            "Trie / Digital Tree",
            "pattern",
            "string_index",
            "Tree whose edges carry single symbols of the key, supporting O(|key|) lookup, insert, and prefix search.",
            "Store a set or map keyed by strings with shared-prefix compression and prefix-range queries.",
            "Hashing loses prefix structure; sorted arrays cost log n per probe and can't do prefix range.",
            "Build child links keyed by the next symbol; mark terminal nodes; walk one symbol at a time to find/insert/delete.",
            "Cheap prefix queries and shared structure; per-node overhead dominates for sparse keys, motivating compressed variants.",
            &["formal_languages_and_automata"],
            &["trie", "prefix", "dictionary"],
            "https://en.wikipedia.org/wiki/Trie",
        ),
        pat(
            "radix_tree",
            "Radix / Compressed Trie",
            "pattern",
            "string_index",
            "Trie with single-child chains collapsed into edges labeled by substrings.",
            "Cut internal-node count when keys share long common prefixes.",
            "A vanilla trie wastes memory on single-child chains.",
            "Store substring labels on edges; split an edge when an insert diverges; merge back to a child-only chain on delete.",
            "Compact memory layout with the same O(|key|) lookup; split/merge bookkeeping adds code complexity.",
            &["formal_languages_and_automata"],
            &["trie", "radix", "compression"],
            "https://en.wikipedia.org/wiki/Radix_tree",
        ),
        pat(
            "patricia_trie",
            "PATRICIA Trie",
            "pattern",
            "string_index",
            "Bitwise radix tree that stores only the bit positions where keys branch.",
            "Index variable-length bit strings (IPv4/IPv6 prefixes, IDs) with minimum node count.",
            "Byte-oriented tries are wasteful for sparse bit-keyed data.",
            "Each internal node records a bit index to test; leaves hold the full key; traversal compares the indicated bit and descends accordingly.",
            "Very compact bit-indexed structure; care must be taken with edge cases (single-key tries, key-length boundaries).",
            &["formal_languages_and_automata"],
            &["trie", "patricia", "bitwise"],
            "https://en.wikipedia.org/wiki/Radix_tree#PATRICIA",
        ),
        pat(
            "adaptive_radix_tree",
            "Adaptive Radix Tree (ART)",
            "pattern",
            "string_index",
            "Radix tree whose node fan-out adapts (4/16/48/256) to the density of children at each level.",
            "Get hash-table-like point-lookup speed with trie-like prefix and range queries.",
            "Fixed-fan-out radix trees waste memory at sparse levels or pay pointer-chasing at dense ones.",
            "Pick a node layout per child count (linear array, sorted array with SIMD search, sparse index, dense 256-array); upgrade/downgrade on insert/delete.",
            "Excellent cache behavior and key-density adaptivity; multiple node variants increase implementation surface.",
            &["formal_languages_and_automata"],
            &["trie", "art", "in_memory_db"],
            "https://db.in.tum.de/~leis/papers/ART.pdf",
        ),
        pat(
            "hash_array_mapped_trie",
            "Hash Array-Mapped Trie (HAMT)",
            "pattern",
            "string_index",
            "Persistent trie indexed by hash chunks; each internal node stores a bitmap of present children and a compact child array.",
            "Implement persistent immutable maps with near-O(log32 n) operations and structural sharing across versions.",
            "Persistent maps with naive copy-on-write are too expensive for large collections.",
            "Slice the hash into 5- or 6-bit chunks; at each level use a bitmap + popcount to index into a dense child slice; update by path-copying the touched spine.",
            "Foundation of Clojure/Scala persistent maps; bitmap node manipulation is intricate and small maps may prefer flat structures.",
            &["formal_languages_and_automata", "functional_programming"],
            &["trie", "hamt", "persistent", "immutable"],
            "https://en.wikipedia.org/wiki/Hash_array_mapped_trie",
        ),
        pat(
            "bitwise_trie_with_bitmap",
            "Bitwise Trie with Bitmap",
            "pattern",
            "string_index",
            "Trie whose children at each level are addressed by bits of the key and packed via a popcount bitmap.",
            "Get HAMT-style compact addressing for arbitrary key bytes (paths, symbol sequences, atom strings).",
            "Byte-keyed tries with sparse fan-out waste pointer slots at every node.",
            "At each level take a fixed bit-slice of the next key chunk; use a bitmap to mark present children and popcount to index a dense array; specialize node layouts (dense byte / tiny / line list / bridge) by density.",
            "Cache-friendly, polymorphic node layouts; balancing layout transitions vs cost of polymorphic dispatch requires careful design.",
            &["formal_languages_and_automata"],
            &["trie", "bitmap", "pathmap"],
            "https://en.wikipedia.org/wiki/Bitwise_trie_with_bitmap",
        ),
        pat(
            "double_array_trie",
            "Double-Array Trie",
            "pattern",
            "string_index",
            "Static trie packed into two parallel integer arrays BASE and CHECK supporting O(1) transitions.",
            "Get the fastest possible read-only trie lookups with minimal memory overhead.",
            "Pointer-based tries pay dereference and cache-miss costs that hurt read-heavy workloads.",
            "For each transition (s, c): next = BASE[s] + c, valid iff CHECK[next] == s; build via offset search packing children contiguously.",
            "Excellent read performance for static dictionaries; updates are expensive enough that the structure is typically rebuilt offline.",
            &["formal_languages_and_automata"],
            &["trie", "double_array", "aoe"],
            "https://en.wikipedia.org/wiki/Double-array_trie",
        ),
        pat(
            "directed_acyclic_word_graph",
            "Directed Acyclic Word Graph (DAWG)",
            "pattern",
            "string_index",
            "Minimal DFA recognizing a finite set of words with suffix sharing across the dictionary.",
            "Store a large word set with both prefix and suffix compression for fast membership and traversal.",
            "Tries lose the chance to share suffixes; full DFAs of word sets can be huge without minimization.",
            "Build a trie, then minimize bottom-up via Mihov's incremental algorithm (or offline Hopcroft) merging suffix-equivalent nodes.",
            "Dramatic compression for languages with rich morphology; updates require either rebuilding or specialized dynamic-DAWG algorithms.",
            &["formal_languages_and_automata"],
            &["dawg", "minimal_dfa", "dictionary"],
            "https://en.wikipedia.org/wiki/Deterministic_acyclic_finite_state_automaton",
        ),
        pat(
            "suffix_automaton",
            "Suffix Automaton (DAWG of Factors)",
            "pattern",
            "string_index",
            "Smallest DFA recognizing all substrings of a text; ≤ 2n-1 states built in online O(n).",
            "Index a text for fast substring, factor-count, and longest-common-substring queries.",
            "Suffix trees solve the same problems but use 4-8× the memory of suffix automata.",
            "Maintain link, len, transitions per state; extend one symbol at a time using suffix-link cloning to keep the automaton minimal.",
            "Compact and linear-time online construction; the link/clone update rule is subtle and easy to get wrong.",
            &["formal_languages_and_automata"],
            &["suffix_automaton", "substring", "indexing"],
            "https://en.wikipedia.org/wiki/Suffix_automaton",
        ),
        pat(
            "cdawg_compact_dawg",
            "Compact / Symmetric Compact DAWG (CDAWG / SCDAWG)",
            "pattern",
            "string_index",
            "Path-compressed suffix automaton (CDAWG) or its symmetric variant exposing both prefix and suffix extension.",
            "Index large texts with both factor membership and bidirectional extension in compact memory.",
            "Suffix automata waste states on unary chains for long unique substrings.",
            "Collapse non-branching chains in the suffix automaton; for SCDAWG, build the analogous structure for the reversed text and link the two via shared factor nodes.",
            "Even more compact than suffix automaton with bidirectional queries; algorithms and implementation are decidedly more complex.",
            &["formal_languages_and_automata"],
            &["cdawg", "scdawg", "suffix"],
            "https://en.wikipedia.org/wiki/Compact_directed_acyclic_word_graph",
        ),
        pat(
            "merkleized_trie",
            "Merkleized / Content-Addressed Trie",
            "pattern",
            "string_index",
            "Trie whose nodes are keyed and shared by a cryptographic hash of their content.",
            "Get structural sharing across versions and verifiable Merkle-style proofs of inclusion.",
            "Ordinary tries cannot prove inclusion or share storage across rebuilt copies.",
            "Hash each subtree bottom-up; intern nodes by their hash; serialize proofs as the sibling-hash path from leaf to root.",
            "Powerful for content-addressed stores and blockchains; hash recomputation on every update has a non-trivial cost.",
            &["formal_languages_and_automata", "distributed_systems"],
            &["merkle", "trie", "content_addressed"],
            "https://en.wikipedia.org/wiki/Merkle_tree",
        ),
        // ---------- string_matching ----------
        pat(
            "aho_corasick_multi_pattern",
            "Aho-Corasick Multi-Pattern Matching",
            "pattern",
            "string_matching",
            "Trie of all patterns augmented with failure links so a single text pass finds all occurrences in O(n + m + z).",
            "Locate every occurrence of any pattern from a fixed pattern set in linear time over the text.",
            "Running each pattern's matcher independently costs O(n · |P|).",
            "Build a trie over the patterns; compute a failure link from each node to the deepest proper suffix that is also a trie prefix; walk the text, following failure links on mismatches.",
            "Classic multi-pattern matcher used in IDS, lexers, dictionary scanners; failure links and output links must be carefully precomputed.",
            &["formal_languages_and_automata"],
            &["aho_corasick", "multi_pattern", "trie"],
            "https://en.wikipedia.org/wiki/Aho%E2%80%93Corasick_algorithm",
        ),
        pat(
            "bk_tree",
            "BK-Tree (Burkhard-Keller)",
            "pattern",
            "string_matching",
            "Metric tree on strings keyed by discrete edit distance, exploiting the triangle inequality for k-NN pruning.",
            "Answer approximate-membership queries (\"all dictionary words within edit distance k\") efficiently.",
            "Scanning the dictionary linearly is too slow when dictionaries are large or queries are repeated.",
            "Insert each word as a child of an existing node under the edge labeled by the integer distance to that node; query by descending only into children whose distance label is in [d(q, node) - k, d(q, node) + k].",
            "Effective for moderate edit budgets and small alphabets; performance degrades for high-k queries or non-discrete metrics.",
            &["formal_languages_and_automata"],
            &["bk_tree", "metric_tree", "approximate"],
            "https://en.wikipedia.org/wiki/BK-tree",
        ),
        pat(
            "ngram_index_filter",
            "N-gram Index Filter",
            "pattern",
            "string_matching",
            "Pre-filter candidate strings by counting q-gram overlap with the query.",
            "Cheaply bound the candidate set for an expensive verifier (edit distance, alignment, automaton intersection).",
            "Running expensive verifiers against an entire dictionary is wasteful when most candidates have no chance of matching.",
            "Index strings by their q-grams; for a query, compute its q-grams and select candidates sharing at least ⌈(|s|-q+1) - k·q⌉ overlapping q-grams (k = edit budget).",
            "Cuts verifier work by orders of magnitude with no false negatives; choosing q and overlap thresholds is workload-dependent.",
            &["formal_languages_and_automata"],
            &["ngram", "filter", "approximate"],
            "https://en.wikipedia.org/wiki/N-gram",
        ),
        pat(
            "dawg_bloom_negative_prefilter",
            "DAWG Bloom-Filter Negative Pre-filter",
            "pattern",
            "string_matching",
            "Bloom filter sitting in front of a DAWG to reject non-members without traversing the automaton.",
            "Avoid touching the DAWG (and its cache footprint) on the common case of dictionary misses.",
            "Each DAWG traversal pays cache misses and conditional branches even when the answer is \"not present\".",
            "Insert every dictionary word into a Bloom filter sized to the desired false-positive rate; on lookup, query the Bloom first and only descend into the DAWG on a hit.",
            "Big wins on miss-heavy workloads; the Bloom filter must be regenerated when the dictionary changes and tuned for FP rate vs memory.",
            &["formal_languages_and_automata"],
            &["bloom", "dawg", "prefilter"],
            "https://en.wikipedia.org/wiki/Bloom_filter",
        ),
        // ---------- edit_distance ----------
        pat(
            "wagner_fischer_dp",
            "Wagner-Fischer Dynamic Programming",
            "pattern",
            "edit_distance",
            "Classic O(m·n) DP for Levenshtein distance with row-rolling O(min(m, n)) space.",
            "Compute exact edit distance and an alignment between two strings.",
            "Naive enumeration of edits is exponential.",
            "Fill a DP table d[i][j] = min(d[i-1][j]+1, d[i][j-1]+1, d[i-1][j-1] + (a_i != b_j)); roll two rows to drop a factor of m in memory.",
            "Foundation of edit-distance work; quadratic time is too slow for long strings without further structure.",
            &["formal_languages_and_automata"],
            &["edit_distance", "wagner_fischer", "dp"],
            "https://en.wikipedia.org/wiki/Wagner%E2%80%93Fischer_algorithm",
        ),
        pat(
            "myers_bit_parallel_edit_distance",
            "Myers Bit-Parallel Edit Distance",
            "pattern",
            "edit_distance",
            "O(m·n / w) bitmask DP for edit distance, where w is the machine word size.",
            "Compute Levenshtein distance ~32-64× faster than Wagner-Fischer when m fits in a few words.",
            "Wagner-Fischer's per-cell work dominates short-string workloads where SIMD/word parallelism is wasted.",
            "Encode the DP frontier as bitmasks Pv/Mv (positive/negative column changes); update with bitwise ops per text symbol using precomputed pattern masks.",
            "Massive speedup on short patterns and binary alphabets; restricted to integer-valued edit costs.",
            &["formal_languages_and_automata"],
            &["edit_distance", "bit_parallel", "myers"],
            "https://doi.org/10.1145/316542.316550",
        ),
        pat(
            "simd_vectorized_edit_distance",
            "SIMD-Vectorized Edit Distance",
            "pattern",
            "edit_distance",
            "Banded DP whose anti-diagonals are computed with SSE/AVX/NEON vector lanes.",
            "Squeeze out 4-16× speedup on commodity CPUs by processing multiple DP cells per instruction.",
            "Scalar DP wastes lane parallelism that modern CPUs provide for free.",
            "Compute DP cells along anti-diagonals so that lane data dependencies are absent within a step; pick lane width by runtime CPU dispatch.",
            "Excellent throughput when bands are wide enough to amortize setup; pathological short patterns underutilize wide vectors.",
            &["formal_languages_and_automata", "parallel_programming"],
            &["edit_distance", "simd", "vectorization"],
            "https://en.wikipedia.org/wiki/Single_instruction%2C_multiple_data",
        ),
        pat(
            "damerau_levenshtein_distance",
            "Damerau-Levenshtein Distance",
            "pattern",
            "edit_distance",
            "Edit distance that adds the transposition of two adjacent characters as a unit-cost operation.",
            "Better model real typing and OCR errors where neighbor swaps are common.",
            "Pure Levenshtein assigns swaps a cost of two, penalizing realistic typos.",
            "Augment the DP recurrence with d[i-1][j-1] + 1 when (a_i = b_{j-1}) ∧ (a_{i-1} = b_j); choose restricted (OSA) or full Damerau-Levenshtein semantics.",
            "More forgiving distance for human-typing models; the full (non-restricted) variant is harder to compute and uses extra DP layers.",
            &["formal_languages_and_automata"],
            &["edit_distance", "damerau", "typo"],
            "https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance",
        ),
        pat(
            "jaro_winkler_similarity",
            "Jaro / Jaro-Winkler Similarity",
            "pattern",
            "edit_distance",
            "Match-and-transposition-count similarity in [0, 1] with a configurable prefix bonus.",
            "Score record-linkage candidates (especially short names) more usefully than raw edit distance.",
            "Levenshtein assigns equal cost regardless of position, but humans weight prefixes more heavily.",
            "Count matches within a window |max(m, n)|/2 - 1; compute Jaro from (matches, transpositions, lengths); add Winkler's prefix bonus up to four shared leading characters.",
            "Workhorse for fuzzy name matching; not a metric (no triangle inequality), so cannot be used for metric indexes like BK-trees.",
            &["formal_languages_and_automata"],
            &["similarity", "jaro", "winkler", "record_linkage"],
            "https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance",
        ),
        pat(
            "move_split_merge_metric",
            "Move-Split-Merge (MSM) Metric",
            "pattern",
            "edit_distance",
            "Time-series distance with move, split, and merge operations replacing the classic substitute/insert/delete.",
            "Compute a true metric for time-series similarity with no warping bias.",
            "Dynamic Time Warping is not a metric and tolerates pathological alignments.",
            "Define costs c_move (point-to-point), c_split (split a value into a run), c_merge (merge a run); run DP analogous to Levenshtein over the new operation set.",
            "Metric property enables triangle-inequality indexing; harder to tune than DTW for some workloads.",
            &["formal_languages_and_automata"],
            &["time_series", "metric", "msm"],
            "https://doi.org/10.1109/TKDE.2012.88",
        ),
        pat(
            "lb_keogh_dtw_lower_bound",
            "LB_Keogh-style Lower-Bound Pruning",
            "pattern",
            "edit_distance",
            "Cheap envelope-based lower bound on warping distances used to prune candidates before exact DP.",
            "Skip the full O(n²) DP on the vast majority of candidates in nearest-neighbor warping search.",
            "Computing exact DTW/MSM against every candidate dominates runtime even with early-abandon.",
            "Compute upper/lower envelopes of the query within the warping band; sum squared deviations of a candidate outside the envelopes as the lower bound; only do exact DP when the bound is below the current best.",
            "Order-of-magnitude speedups for k-NN warping queries; bound tightness depends on warping bandwidth and series variability.",
            &["formal_languages_and_automata"],
            &["time_series", "lower_bound", "keogh"],
            "https://en.wikipedia.org/wiki/Dynamic_time_warping",
        ),
        // ---------- approximate_match ----------
        pat(
            "universal_levenshtein_automaton",
            "Universal Levenshtein Automaton",
            "pattern",
            "approximate_match",
            "Parameter-free DFA recognizing the bounded edit-distance neighborhood of any query word via characteristic-vector encoding.",
            "Match approximately against a dictionary in O(|text|) with no per-query automaton rebuild.",
            "Building a fresh Levenshtein NFA per query is too slow for interactive lookups.",
            "Precompute the universal automaton offline; at query time, encode the symbol-match window as a characteristic bit vector and dispatch into the corresponding state.",
            "Fastest known online approximate matcher for fixed k; non-trivial construction with subtle subsumption rules.",
            &["formal_languages_and_automata"],
            &["levenshtein", "automaton", "approximate"],
            "https://doi.org/10.1023/A:1014184110234",
        ),
        pat(
            "parameterized_levenshtein_automaton",
            "Parameterized Levenshtein Automaton",
            "pattern",
            "approximate_match",
            "Per-query automaton over Levenshtein positions (i, e) annotated with characteristic vectors.",
            "Match a single query against many candidates with one query-specific automaton.",
            "Building a full position automaton from scratch is wasteful when the alphabet is large.",
            "Maintain reachable position sets ordered by lex; advance by symbol using characteristic vectors that encode the next k+1 matches.",
            "Compact and reusable per query; coordination with subsumption is required to keep state sets minimal.",
            &["formal_languages_and_automata"],
            &["levenshtein", "automaton", "parametric"],
            "https://doi.org/10.1023/A:1014184110234",
        ),
        pat(
            "levenshtein_position_subsumption",
            "Subsumption-Based Levenshtein State Minimization",
            "pattern",
            "approximate_match",
            "Online removal of Levenshtein positions dominated by other positions in the same state under the subsumption order.",
            "Keep state sizes minimal during Levenshtein-automaton simulation.",
            "Without subsumption, position sets grow combinatorially and dominate runtime.",
            "After each transition, drop any position (i, e) for which another position (i', e') ≤^χ_s (i, e) is present.",
            "Critical for practical performance; reasoning about correctness of the subsumption order is delicate.",
            &["formal_languages_and_automata"],
            &["levenshtein", "subsumption", "minimization"],
            "https://en.wikipedia.org/wiki/Levenshtein_automaton",
        ),
        pat(
            "wallbreaker_pigeonhole_match",
            "WallBreaker Pigeonhole Approximate Match",
            "pattern",
            "approximate_match",
            "Split the query into k+1 (or 2k+1) pieces; exact-match each piece; verify by bidirectional extension.",
            "Use exact-match infrastructure (suffix array, FM-index, DAWG) to drive approximate matching with edit budget k.",
            "Approximate matchers running directly against a dictionary cost more than exact-match plus a small verifier.",
            "Partition the query into k+1 contiguous pieces; for each piece, find exact occurrences in the index; for each hit, verify by computing edit distance on a window around the hit, extending bidirectionally.",
            "Excellent throughput when k is small and the index supports fast exact search; piece-count tuning is workload-dependent.",
            &["formal_languages_and_automata"],
            &["pigeonhole", "wallbreaker", "approximate"],
            "https://doi.org/10.1007/978-3-642-39286-5_18",
        ),
        pat(
            "product_automaton_intersection",
            "Product Automaton / Intersection Traversal",
            "pattern",
            "approximate_match",
            "Walk a dictionary DFA in lockstep with a Levenshtein automaton, advancing along compatible pairs of edges.",
            "Enumerate all dictionary words within edit distance k in time proportional to the joint search size.",
            "Brute-force dictionary scans waste work on irrelevant paths.",
            "Maintain a worklist of (dict_state, lev_state) pairs; for each character of the dictionary edge, advance both automata; emit when both reach an accepting state.",
            "Optimal asymptotic algorithm for dictionary-bounded approximate match; pair-state explosion can occur for high k.",
            &["formal_languages_and_automata"],
            &["product_automaton", "intersection", "dictionary"],
            "https://en.wikipedia.org/wiki/Levenshtein_automaton",
        ),
        // ---------- phonetic ----------
        pat(
            "soundex_phonetic",
            "Soundex",
            "pattern",
            "phonetic",
            "Classical consonant-class hash that maps English names to a 4-character code.",
            "Group similar-sounding English names (Robert/Rupert) for record-linkage.",
            "Exact spelling comparison misses common phonetic equivalences.",
            "Keep the first letter; map remaining consonants to digit classes (b/f/p/v→1, c/g/j/k/q/s/x/z→2, ...); collapse adjacent duplicates; pad/truncate to length 4.",
            "Extremely cheap and universal; English-centric and famously imprecise.",
            &["formal_languages_and_automata"],
            &["phonetic", "soundex", "record_linkage"],
            "https://en.wikipedia.org/wiki/Soundex",
        ),
        pat(
            "metaphone_phonetic",
            "Metaphone / Double Metaphone",
            "pattern",
            "phonetic",
            "Context-sensitive English phonetic encoder with single and double-code variants for ambiguous pronunciations.",
            "Get more accurate English phonetic equivalence than Soundex while staying lightweight.",
            "Soundex misses many real phonetic equivalences and has no concept of pronunciation context.",
            "Apply a rule set keyed on character n-grams in their context (e.g. \"GH\" silent in some positions); Double Metaphone outputs two alternate codes when pronunciation is ambiguous.",
            "Strong general-purpose English phonetic key; rule sets are language-specific and pre-2000s in pedigree.",
            &["formal_languages_and_automata"],
            &["phonetic", "metaphone"],
            "https://en.wikipedia.org/wiki/Metaphone",
        ),
        pat(
            "nysiis_phonetic",
            "NYSIIS",
            "pattern",
            "phonetic",
            "American name-matching encoder with explicit prefix/suffix and positional substitution rules.",
            "Get phonetic equivalence tuned for the New York State Identification & Intelligence System name corpus.",
            "Soundex collisions are unhelpful for many American name patterns.",
            "Apply prefix rules (MAC→MCC, KN→NN, ...), iterate positional substitutions over the remaining characters, truncate to a fixed length.",
            "Better recall than Soundex for many American names; rule set is somewhat ad-hoc and English-centric.",
            &["formal_languages_and_automata"],
            &["phonetic", "nysiis"],
            "https://en.wikipedia.org/wiki/New_York_State_Identification_and_Intelligence_System",
        ),
        pat(
            "caverphone_phonetic",
            "Caverphone",
            "pattern",
            "phonetic",
            "NZ-English phonetic encoder developed for the Caversham historical-records project.",
            "Get phonetic equivalence tuned for late-19th-century NZ-English name spellings.",
            "Soundex/Metaphone drift for accents and orthographies far from American English.",
            "Apply Caverphone's substitution rules (vowel deletion, consonant clustering) and truncate to a fixed length to produce a key.",
            "Targeted accuracy for its corpus; limited applicability outside its design domain.",
            &["formal_languages_and_automata"],
            &["phonetic", "caverphone"],
            "https://en.wikipedia.org/wiki/Caverphone",
        ),
        pat(
            "cologne_phonetic",
            "Cologne Phonetic (Kölner Phonetik)",
            "pattern",
            "phonetic",
            "Phonetic encoder for German optimized for German pronunciation rules.",
            "Match German names and words that have varying spellings (Meyer/Maier/Mayer).",
            "Soundex misses German-specific patterns (umlauts, sch-, -ch-, c/k variation).",
            "Apply a rule table mapping each letter or digraph (in context) to a digit code; collapse repeats; drop zeros except in leading position.",
            "Strong for German corpora; not portable to other languages.",
            &["formal_languages_and_automata"],
            &["phonetic", "cologne", "german"],
            "https://en.wikipedia.org/wiki/Cologne_phonetics",
        ),
        pat(
            "beider_morse_phonetic",
            "Beider-Morse Phonetic Matching",
            "pattern",
            "phonetic",
            "Multi-language genealogical phonetic-matching system producing multiple weighted codes per name.",
            "Match historical names across European languages and orthographic conventions.",
            "Single-code phonetic encoders collapse too aggressively for cross-language genealogy.",
            "Detect the source language, apply language-specific rules, and emit a set of phonetic codes representing plausible pronunciations.",
            "Best-in-class recall for genealogy at the cost of significant per-name work and a large rules database.",
            &["formal_languages_and_automata"],
            &["phonetic", "beider_morse", "genealogy"],
            "https://en.wikipedia.org/wiki/Daitch%E2%80%93Mokotoff_Soundex",
        ),
        pat(
            "daitch_mokotoff_phonetic",
            "Daitch-Mokotoff Soundex",
            "pattern",
            "phonetic",
            "Extension of Soundex with rules for Slavic and Yiddish-derived names.",
            "Match Jewish and Eastern-European names where Soundex collapses important distinctions.",
            "Soundex was designed for English and loses fidelity on E. European patterns.",
            "Maintain a rule table that produces 6-digit codes with multiple emissions per ambiguous letter sequence.",
            "Better recall than Soundex for its target corpus; rule set is large and historical.",
            &["formal_languages_and_automata"],
            &["phonetic", "daitch_mokotoff"],
            "https://en.wikipedia.org/wiki/Daitch%E2%80%93Mokotoff_Soundex",
        ),
        // ---------- abstract_machine ----------
        pat(
            "warren_abstract_machine",
            "Warren Abstract Machine (WAM)",
            "pattern",
            "abstract_machine",
            "Heap, stack, and choice-point machine specialized for Prolog/unification execution.",
            "Run Prolog efficiently with structure sharing, choice points, and last-call optimization.",
            "Naive interpreters for resolution and unification are too slow for real Prolog workloads.",
            "Implement WAM instructions (get/put/unify family, try/retry/trust, deallocate, etc.) over a heap + stack + trail + choice-point stack; compile Prolog clauses to WAM code.",
            "Foundation of every serious Prolog system; instruction-level reasoning is intricate and tied tightly to Prolog semantics.",
            &["formal_languages_and_automata", "logic_programming"],
            &["wam", "prolog", "abstract_machine"],
            "https://en.wikipedia.org/wiki/Warren_Abstract_Machine",
        ),
        pat(
            "cesk_abstract_machine",
            "CESK / CEK Abstract Machine",
            "pattern",
            "abstract_machine",
            "Operational-semantics machine with Control, Environment, Store, and Kontinuation components.",
            "Define small-step semantics for lambda-calculus-like languages in a way that supports abstract interpretation.",
            "Big-step semantics conflate steps that abstract interpreters need to discriminate.",
            "Represent program states as 4-tuples (C, E, S, K); define a transition function over each construct; specialize to CEK by dropping the explicit store for pure languages.",
            "Cleanly separates evaluation context from environment and store; foundation for abstract-machine-based analyzers and interpreters.",
            &["formal_languages_and_automata", "functional_programming"],
            &["cesk", "cek", "operational_semantics"],
            "https://en.wikipedia.org/wiki/CEK_Machine",
        ),
        pat(
            "tiered_bytecode_vm_jit",
            "Tiered Bytecode VM with JIT",
            "pattern",
            "abstract_machine",
            "Multi-tier execution stack: interpreter → baseline compiler → optimizing JIT, with on-stack replacement at hot loops.",
            "Get fast startup and warm-up while still hitting peak performance on hot code.",
            "A single-tier interpreter is too slow; a single-tier optimizing JIT pays compilation cost up front.",
            "Begin in an interpreter that profiles call counts and types; promote hot methods to a baseline compiler; further promote ultra-hot methods to an optimizing JIT; install OSR entries so loops can transition mid-execution.",
            "Excellent startup-and-peak trade-off in V8/HotSpot/CoreCLR; tier-transition logic and deoptimization are major sources of complexity.",
            &["formal_languages_and_automata"],
            &["jit", "vm", "tiered"],
            "https://en.wikipedia.org/wiki/Tracing_just-in-time_compilation",
        ),
        // ---------- pattern_match ----------
        pat(
            "unification_first_order",
            "First-Order Unification (Robinson's Algorithm)",
            "pattern",
            "pattern_match",
            "Compute the most-general unifier of two first-order terms or fail.",
            "Engine for type inference, logic programming, term rewriting, and theorem proving.",
            "Hand-coded matchers conflate substitution and structural recursion and fail under variable aliasing.",
            "Decompose pairs of terms recursively; on variable-vs-term, bind subject to occurs check; on function symbols of equal arity, recurse pairwise; fail otherwise.",
            "Universal substitution algorithm; without occurs check, naive unification can build cyclic terms or loop forever.",
            &["formal_languages_and_automata", "logic_programming"],
            &["unification", "robinson", "mgu"],
            "https://en.wikipedia.org/wiki/Unification_(computer_science)",
        ),
        pat(
            "term_rewriting_system",
            "Term Rewriting System",
            "pattern",
            "pattern_match",
            "Set of rewrite rules l → r over terms, applied directionally to compute normal forms.",
            "Reduce expressions to normal forms (simplifier, compiler intermediate, equational engine).",
            "Hand-coded simplifiers tangle rule order, confluence, and termination.",
            "Define rules with variables; on each step, find a redex (rule-match), apply the substitution; iterate until no redex remains; prove confluence (Church-Rosser) and termination (well-founded order) where possible.",
            "Mature theory of confluence and termination; non-confluent systems can produce different answers depending on strategy.",
            &["formal_languages_and_automata"],
            &["rewriting", "trs", "normal_form"],
            "https://en.wikipedia.org/wiki/Rewriting",
        ),
        pat(
            "abstract_reduction_system",
            "Abstract Reduction System",
            "pattern",
            "pattern_match",
            "Pair (A, →) where → is a binary relation on A; abstracts term rewriting, β-reduction, and graph rewriting.",
            "Reason uniformly about confluence, termination, and normal forms across diverse rewriting calculi.",
            "Calculus-specific proofs of confluence/termination duplicate identical reasoning.",
            "State theorems (Church-Rosser, Newman's lemma) at the ARS level; instantiate to concrete systems by supplying the relation.",
            "Foundation of rewriting theory; concrete instantiations still require their own proofs of orientation and ordering.",
            &["formal_languages_and_automata"],
            &["rewriting", "ars", "confluence"],
            "https://en.wikipedia.org/wiki/Abstract_rewriting_system",
        ),
        pat(
            "multitrie_wildcard_match",
            "MultiTrie with Wildcards and Sub-Expressions",
            "pattern",
            "pattern_match",
            "Trie that indexes S-expression atoms using tokens for parenthesis open/close, wildcards, and ordinary symbols, with precomputed parenthesis-distance metadata.",
            "Match patterns containing wildcards and sub-expressions against an atom-space efficiently.",
            "Plain symbol tries cannot represent unification-style wildcards or nested sub-expression structure.",
            "Tokenize each indexed expression into (Exact symbol, Wildcard, LeftPar, RightPar); insert into a trie; on lookup, follow wildcard branches whenever a sub-expression of any structure may match, using precomputed parenthesis distances to skip irrelevant subtrees.",
            "Powerful structural pattern index for atom-spaces and meta-programming; index size and traversal complexity can grow rapidly without careful pruning.",
            &["formal_languages_and_automata"],
            &["trie", "multitrie", "atom_space"],
            "https://en.wikipedia.org/wiki/Trie",
        ),
        // ---------- graph_match ----------
        pat(
            "code_property_graph",
            "Code Property Graph (CPG)",
            "pattern",
            "graph_match",
            "Unified graph combining AST, CFG, DFG, PDG, and call-graph edges for whole-program static analysis.",
            "Query and reason about code with one graph database instead of stitching multiple analyses by hand.",
            "Running AST + CFG + DFG + PDG analyses independently complicates joint queries (e.g. taint flow that respects control flow).",
            "Build the AST; layer CFG edges over statements; overlay DFG edges between defs and uses; add PDG dependence edges; add call-graph edges; store as a property graph queryable with Gremlin/Cypher.",
            "Foundation of Joern-style vulnerability hunting and many bug-prediction analyses; graph builds are expensive and language-specific.",
            &["formal_languages_and_automata"],
            &["cpg", "graph", "static_analysis"],
            "https://en.wikipedia.org/wiki/Code_property_graph",
        ),
        pat(
            "vf2_subgraph_isomorphism",
            "VF2 / VF3 Subgraph Isomorphism",
            "pattern",
            "graph_match",
            "Backtracking subgraph-isomorphism algorithms with feasibility-pruning rules over partial mappings.",
            "Detect a pattern graph (e.g., a design pattern, a security smell) inside a larger code graph.",
            "Naive subgraph search is super-exponential and needs aggressive pruning.",
            "Maintain a partial mapping; extend by candidate pairs satisfying syntactic and look-ahead feasibility rules (Fcore, Fin, Fout); backtrack on failure.",
            "Strong general-purpose subgraph matcher; tuning depends heavily on graph density and attribute presence.",
            &["formal_languages_and_automata"],
            &["subgraph_isomorphism", "vf2", "vf3"],
            "https://en.wikipedia.org/wiki/Subgraph_isomorphism_problem",
        ),
        // ---------- probabilistic ----------
        pat(
            "weighted_automaton_semiring",
            "Semiring-Weighted Automaton",
            "pattern",
            "probabilistic",
            "Finite automaton whose transitions carry weights drawn from an arbitrary semiring.",
            "Unify probabilistic, tropical (shortest-path), log, and boolean automata under a single algebra.",
            "Ad-hoc weighted variants of automata duplicate algorithms with subtly different operators.",
            "Define the automaton over a semiring (S, ⊕, ⊗, 0, 1); compute path weights by ⊗ along the path and aggregate parallel paths by ⊕.",
            "One framework, many instantiations; numerical stability and best-path heuristics depend on semiring choice.",
            &["formal_languages_and_automata"],
            &["weighted_automaton", "semiring"],
            "https://en.wikipedia.org/wiki/Weighted_automaton",
        ),
        pat(
            "pcfg_probabilistic_grammar",
            "Probabilistic Context-Free Grammar (PCFG)",
            "pattern",
            "probabilistic",
            "CFG whose productions carry probabilities summing to 1 per non-terminal; assigns a probability to each parse tree.",
            "Score parses and disambiguate parses in NLP, code-completion, and program-synthesis contexts.",
            "Plain CFGs allow many parses with no preference; choosing arbitrarily produces poor results.",
            "Annotate each production A → α with P(A → α); compute parse probability by multiplying production probabilities; train via inside-outside or supervised counts.",
            "Cheap and interpretable parse scorer; assumes context independence that real languages violate.",
            &["formal_languages_and_automata"],
            &["pcfg", "probabilistic", "grammar"],
            "https://en.wikipedia.org/wiki/Stochastic_grammar",
        ),
        pat(
            "kneser_ney_ngram_smoothing",
            "Kneser-Ney N-gram Smoothing",
            "pattern",
            "probabilistic",
            "Absolute-discounting n-gram smoothing using continuation probabilities for backoff.",
            "Get state-of-the-art n-gram LM perplexity without resorting to neural models.",
            "Naive maximum-likelihood n-gram estimates assign zero probability to unseen events.",
            "Discount each observed n-gram count by a constant; redistribute the freed mass via a continuation probability that counts the number of distinct contexts in which a word appears.",
            "Best classical n-gram smoother; modified Kneser-Ney improves further and is the de facto baseline.",
            &[
                "formal_languages_and_automata",
                "machine_learning_engineering",
            ],
            &["ngram", "smoothing", "kneser_ney"],
            "https://en.wikipedia.org/wiki/Kneser%E2%80%93Ney_smoothing",
        ),
        // ---------- streaming ----------
        pat(
            "streaming_automaton_bounded_memory",
            "Streaming Automaton (Bounded-Memory Online Recognizer)",
            "pattern",
            "streaming",
            "Process arbitrarily long input with state size bounded independently of input length.",
            "Recognize or transform unbounded streams (logs, network traffic, sensor data) without buffering.",
            "Algorithms that need O(n) memory cannot run over genuinely unbounded streams.",
            "Restrict state representation to fixed-size summaries (sketches, fixed-arity automata states); emit decisions as input arrives.",
            "Constant memory and bounded latency; expressiveness is bounded by what can be summarized in fixed state.",
            &["formal_languages_and_automata"],
            &["streaming", "automaton", "online"],
            "https://en.wikipedia.org/wiki/Streaming_algorithm",
        ),
        pat(
            "newton_iteration_semiring_fixpoint",
            "Newton Iteration over Semirings",
            "pattern",
            "streaming",
            "Quadratic-convergence fixed-point iteration for systems of semiring equations (WPDS, dataflow, generating functions).",
            "Solve dataflow and interprocedural analyses faster than linear Kleene iteration.",
            "Kleene iteration converges linearly and can be slow for deep recursion or dense graphs.",
            "Decompose the fixed-point system as F(x) = c ⊕ x ⊗ A; iterate x_{k+1} = c ⊕ x_k ⊗ A ⊕ Δ(x_k) where Δ is the Jacobian-like correction; convergence is doubly-fast on idempotent commutative semirings.",
            "Big speedups on real analyses; the algebra and convergence analysis demand investment.",
            &["formal_languages_and_automata"],
            &["fixpoint", "newton", "wpds"],
            "https://doi.org/10.1109/LICS.2007.36",
        ),
        // ---------- constrained_decoding ----------
        pat(
            "constrained_decoding_grammar_mask",
            "Grammar-Constrained Decoding",
            "pattern",
            "constrained_decoding",
            "Mask LLM/sampler logits at each token step by the set of tokens that keep the output accepted by a grammar.",
            "Guarantee well-formed structured output (JSON, SQL, code) from an autoregressive model.",
            "Post-hoc validation of model outputs is slow, lossy, and offers no recovery.",
            "Maintain the grammar/automaton parser state as tokens are emitted; at each step, compute the prefix-acceptance mask over the model's vocabulary and zero out forbidden logits before sampling.",
            "Hard guarantees on output structure; the mask computation must be fast (incremental parser state) to keep tokens-per-second high.",
            &[
                "formal_languages_and_automata",
                "machine_learning_engineering",
            ],
            &["llm", "constrained_decoding", "grammar"],
            "https://en.wikipedia.org/wiki/Constrained_decoding",
        ),
        pat(
            "wfst_export_lm",
            "WFST Export of Language Model",
            "pattern",
            "constrained_decoding",
            "Export an n-gram or PCFG language model as a WFST with backoff ε-transitions.",
            "Compose a language model with acoustic models, edit-distance models, or grammar constraints in a single decoder.",
            "Per-model decoders cannot be combined without re-implementing each pipeline.",
            "Emit one state per LM history; transition on each next-token symbol with the appropriate weighted edge; add backoff ε-transitions from k-gram histories to (k-1)-gram histories with appropriate weights.",
            "Modular ASR/MT-style decoders; FST size grows with the LM and may require pruning or on-the-fly composition.",
            &["formal_languages_and_automata"],
            &["wfst", "lm", "decoder"],
            "https://en.wikipedia.org/wiki/Weighted_finite-state_transducer",
        ),
    ]
}
