//! Code smells (kind="code_smell") and Fowler-catalog refactorings (kind="pattern", category="refactoring").

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ========================================
        //                CODE SMELLS
        // ========================================
        pat(
            "long_method",
            "Long Method",
            "code_smell",
            "bloater",
            "A method has grown so long it is hard to understand at a glance.",
            "Recognize methods that should be decomposed.",
            "Logic accreted into one method as features were added.",
            "Apply Extract Method to lift conceptual sub-steps; replace temps with queries.",
            "Easier to read and test; over-fragmentation hurts cohesion.",
            &["procedural_programming", "object_oriented_programming"],
            &["smell", "bloater"],
            "https://refactoring.guru/smells/long-method",
        ),
        pat(
            "imports_in_function_body",
            "Imports Inside Function Bodies",
            "code_smell",
            "organization",
            "Import statements (`use`, `import`, `require`) placed inside a function / method / \
             lambda body instead of at the top of the file or module.",
            "An import that resolves to a callable enclosing scope rather than the file or module \
             top. pgmcp's `import_hygiene` tool / sweep collector flags exactly these (it joins \
             each `import_use` reference to its resolved enclosing symbol).",
            "Added ad hoc where first needed (often by codegen or LLM edits); lazy-loading habits \
             carried over from dynamic languages.",
            "Hoist the import to the top of the file — or, for test-only dependencies, to the top \
             of the test module where the test functions live. Collapse copies that were re-typed \
             across several function bodies into one top-level import.",
            "A scope's real dependencies are visible at a glance; duplicated `use` lines disappear; \
             formatters (e.g. rustfmt) can keep imports grouped and ordered.",
            &[
                "procedural_programming",
                "object_oriented_programming",
                "functional_programming",
            ],
            &["smell", "organization", "imports"],
            "https://doc.rust-lang.org/reference/items/use-declarations.html",
        ),
        pat(
            "large_class",
            "Large Class",
            "code_smell",
            "bloater",
            "A class with too many fields, methods, or responsibilities.",
            "Recognize classes that violate SRP and need splitting.",
            "Features added directly to an existing class without re-evaluating cohesion.",
            "Extract Class; Extract Subclass; Extract Interface; move features to appropriate types.",
            "Cleaner cohesion; coordinate via composition.",
            &["object_oriented_programming"],
            &["smell", "bloater"],
            "https://refactoring.guru/smells/large-class",
        ),
        pat(
            "long_parameter_list",
            "Long Parameter List",
            "code_smell",
            "bloater",
            "Many parameters make a method's signature hard to read and remember.",
            "Recognize signatures that should be simplified.",
            "Each new requirement added a parameter; some are flags; some are clumps.",
            "Introduce Parameter Object; Preserve Whole Object; Replace Parameter with Method; Remove Flag Argument.",
            "Smaller, meaningful signatures; new types to maintain.",
            &["procedural_programming", "object_oriented_programming"],
            &["smell", "bloater"],
            "https://refactoring.guru/smells/long-parameter-list",
        ),
        pat(
            "data_clumps",
            "Data Clumps",
            "code_smell",
            "bloater",
            "The same group of values travels together through many signatures.",
            "Recognize implicit types that should be made explicit.",
            "A real concept is shipped as separate variables instead of one cohesive type.",
            "Extract Class for the clump; replace its parameters with the new type.",
            "Domain types appear; data flows through fewer signatures.",
            &["object_oriented_programming"],
            &["smell", "bloater"],
            "https://refactoring.guru/smells/data-clumps",
        ),
        pat(
            "primitive_obsession",
            "Primitive Obsession",
            "code_smell",
            "bloater",
            "Using primitives (strings, numbers) for concepts that deserve their own type.",
            "Recognize unsafe representations and lost invariants.",
            "Quick and easy not to define a type.",
            "Replace Primitive with Object; introduce Value Object types (Money, Email, Coordinate).",
            "Type-safe, expressive code; more classes to navigate.",
            &["object_oriented_programming", "functional_programming"],
            &["smell", "bloater"],
            "https://refactoring.guru/smells/primitive-obsession",
        ),
        pat(
            "divergent_change",
            "Divergent Change",
            "code_smell",
            "change_preventer",
            "One module changes in many different ways for many different reasons.",
            "Recognize lack of SRP at the module level.",
            "A module accreted responsibilities across multiple change axes.",
            "Split the module so each piece changes for one reason; apply Common Closure Principle.",
            "Lower change cost; more modules to navigate.",
            &["object_oriented_programming"],
            &["smell", "change_preventer"],
            "https://refactoring.guru/smells/divergent-change",
        ),
        pat(
            "shotgun_surgery",
            "Shotgun Surgery",
            "code_smell",
            "change_preventer",
            "A single change requires many small changes in many modules.",
            "Recognize dispersion of one responsibility across the codebase.",
            "Behavior that should live in one place was duplicated or scattered.",
            "Move Method/Move Field to one home; Inline Class if a class scattered the behavior.",
            "Localized change; sometimes requires extensive moves.",
            &["object_oriented_programming"],
            &["smell", "change_preventer"],
            "https://refactoring.guru/smells/shotgun-surgery",
        ),
        pat(
            "parallel_inheritance_hierarchies",
            "Parallel Inheritance Hierarchies",
            "code_smell",
            "change_preventer",
            "Two parallel class hierarchies that must be updated together when a subclass is added.",
            "Recognize coupled hierarchies that ought to be unified.",
            "Behavior was split across hierarchies that mirror each other.",
            "Move Method/Field across the hierarchies to collapse them; favor composition.",
            "Less duplication of structure; sometimes requires significant refactor.",
            &["object_oriented_programming"],
            &["smell", "inheritance"],
            "https://refactoring.guru/smells/parallel-inheritance-hierarchies",
        ),
        pat(
            "feature_envy",
            "Feature Envy",
            "code_smell",
            "couplers",
            "A method seems more interested in another class's data than its own.",
            "Recognize methods that should move closer to the data they use.",
            "Behavior was placed away from the data it operates on.",
            "Move Method to the class with the data; if the method serves multiple owners, Extract Method first.",
            "Better cohesion and encapsulation; one less object to ask repeatedly.",
            &["object_oriented_programming"],
            &["smell", "couplers"],
            "https://refactoring.guru/smells/feature-envy",
        ),
        pat(
            "inappropriate_intimacy",
            "Inappropriate Intimacy",
            "code_smell",
            "couplers",
            "Two classes know too much about each other's internals.",
            "Recognize hidden coupling between collaborators.",
            "One class exposes internals or other reaches into private state.",
            "Move Method/Field; Hide Delegate; Change Bidirectional to Unidirectional Association.",
            "Cleaner contracts; the two classes evolve more independently.",
            &["object_oriented_programming"],
            &["smell", "couplers"],
            "https://refactoring.guru/smells/inappropriate-intimacy",
        ),
        pat(
            "message_chains",
            "Message Chains",
            "code_smell",
            "couplers",
            "Long sequences of calls (`a.b().c().d()`) that traverse many object boundaries.",
            "Recognize Law-of-Demeter violations.",
            "Clients reach through object graphs instead of asking for an operation.",
            "Hide Delegate; Extract Method that performs the required operation on the immediate friend.",
            "Reduced coupling; intermediate methods may proliferate (use Remove Middle Man if so).",
            &["object_oriented_programming"],
            &["smell", "couplers"],
            "https://refactoring.guru/smells/message-chains",
        ),
        pat(
            "middle_man_smell",
            "Middle Man",
            "code_smell",
            "couplers",
            "A class that delegates almost every method to another and adds nothing.",
            "Recognize delegation that should be eliminated.",
            "Over-applied Hide Delegate or stale wrapper.",
            "Remove Middle Man; let clients talk directly to the real collaborator.",
            "Less indirection; only safe when the middleman didn't add behavior.",
            &["object_oriented_programming"],
            &["smell", "couplers"],
            "https://refactoring.guru/smells/middle-man",
        ),
        pat(
            "switch_statements",
            "Switch Statements (Repeated)",
            "code_smell",
            "object_orientation_abusers",
            "Repeated switches on the same type indicator scatter polymorphism opportunities.",
            "Recognize missed polymorphism.",
            "Type fields drive branching across many functions.",
            "Replace Conditional with Polymorphism; Replace Type Code with Subclasses/State/Strategy.",
            "Open to new variants; care with new variants requiring updates in all sites.",
            &["object_oriented_programming"],
            &["smell", "ooa"],
            "https://refactoring.guru/smells/switch-statements",
        ),
        pat(
            "temporary_field",
            "Temporary Field",
            "code_smell",
            "object_orientation_abusers",
            "A field is only used by one or two methods, leaving it null/empty most of the time.",
            "Recognize fields that should not be class members.",
            "Quick patch to share data between methods without redesign.",
            "Extract Class for the methods+fields; introduce a Parameter Object; or pass directly.",
            "Cleaner object lifecycle; clearer responsibilities.",
            &["object_oriented_programming"],
            &["smell", "ooa"],
            "https://refactoring.guru/smells/temporary-field",
        ),
        pat(
            "refused_bequest",
            "Refused Bequest",
            "code_smell",
            "object_orientation_abusers",
            "A subclass uses only a small part of what it inherits, refusing the rest.",
            "Recognize misuse of inheritance.",
            "Inheritance chosen for reuse rather than IS-A.",
            "Replace inheritance with delegation; Push Down unused methods; reorganize hierarchy.",
            "Cleaner hierarchies; some boilerplate added by delegation.",
            &["object_oriented_programming"],
            &["smell", "inheritance"],
            "https://refactoring.guru/smells/refused-bequest",
        ),
        pat(
            "alternative_classes_diff_interfaces",
            "Alternative Classes with Different Interfaces",
            "code_smell",
            "object_orientation_abusers",
            "Two classes do similar things but have unrelated interfaces.",
            "Recognize duplicated concepts with inconsistent APIs.",
            "Independent development converged on similar abstractions with different shapes.",
            "Rename Method; Move Method; Extract Superclass once interfaces align.",
            "Reusable abstraction; some API churn during alignment.",
            &["object_oriented_programming"],
            &["smell", "ooa"],
            "https://refactoring.guru/smells/alternative-classes-with-different-interfaces",
        ),
        pat(
            "data_class",
            "Data Class",
            "code_smell",
            "object_orientation_abusers",
            "A class with only getters/setters and no behavior.",
            "Recognize anemic models that should grow behavior.",
            "Convenience of POJOs without revisiting where behavior belongs.",
            "Move behavior to the class that owns the data (Feature Envy fix); make fields immutable where possible.",
            "Richer types; some legitimate value-bag use cases remain.",
            &["object_oriented_programming"],
            &["smell", "ddd"],
            "https://refactoring.guru/smells/data-class",
        ),
        pat(
            "lazy_class",
            "Lazy Class",
            "code_smell",
            "dispensable",
            "A class that does too little to justify its existence.",
            "Recognize redundant abstractions.",
            "An anticipated need never materialized.",
            "Inline Class; collapse the hierarchy.",
            "Less indirection; sometimes a small class earns its keep via type safety.",
            &["object_oriented_programming"],
            &["smell", "dispensable"],
            "https://refactoring.guru/smells/lazy-class",
        ),
        pat(
            "duplicate_code",
            "Duplicate Code",
            "code_smell",
            "dispensable",
            "The same or very similar code appears in multiple places.",
            "Recognize duplication-induced drift and bug-fix multiplication.",
            "Copy-paste solved a short-term need; nobody returned to dedupe.",
            "Extract Method/Class/Function; Pull Up Method; Form Template Method.",
            "Single source of truth; do not dedup spurious similarity (different change axes).",
            &["procedural_programming", "object_oriented_programming"],
            &["smell", "dispensable"],
            "https://refactoring.guru/smells/duplicate-code",
        ),
        pat(
            "dead_code",
            "Dead Code",
            "code_smell",
            "dispensable",
            "Code that is never executed at runtime.",
            "Recognize maintenance cost with no benefit.",
            "Features removed, branches replaced, or flags abandoned without cleanup.",
            "Delete; rely on version control to recover if ever needed; remove related tests/configs.",
            "Less to read and maintain; coverage tooling helps identify.",
            &["procedural_programming", "object_oriented_programming"],
            &["smell", "dispensable"],
            "https://refactoring.guru/smells/dead-code",
        ),
        pat(
            "speculative_generality",
            "Speculative Generality",
            "code_smell",
            "dispensable",
            "Hooks/parameters/classes anticipating future variation that never came.",
            "Recognize over-engineering cost.",
            "Fear of being 'caught' without the extension or sunk-cost attachment.",
            "Delete unused parameters/classes; Inline Class; Collapse Hierarchy.",
            "Smaller surface area; some scaffolding (DI seams) still pays off.",
            &["object_oriented_programming"],
            &["smell", "dispensable"],
            "https://refactoring.guru/smells/speculative-generality",
        ),
        pat(
            "comments_smell",
            "Comments (as Deodorant)",
            "code_smell",
            "dispensable",
            "Comments compensating for unclear code rather than documenting intent.",
            "Recognize when comments are masking design problems.",
            "Comments are easier to write than to refactor the code being commented.",
            "Rename for clarity; Extract Method; introduce explaining variables; keep comments only for non-obvious why.",
            "Code becomes self-explaining; necessary comments stand out.",
            &["procedural_programming", "object_oriented_programming"],
            &["smell", "dispensable"],
            "https://refactoring.guru/smells/comments",
        ),
        pat(
            "mysterious_name",
            "Mysterious Name",
            "code_smell",
            "dispensable",
            "Identifiers that don't convey intent.",
            "Recognize names that make code hard to read.",
            "Speed of typing; lost domain context; abbreviations.",
            "Rename to match domain terminology; reveal intent in tests and signatures.",
            "Faster comprehension; rename pressure encourages domain awareness.",
            &["procedural_programming", "object_oriented_programming"],
            &["smell", "naming"],
            "https://martinfowler.com/bliki/TwoHardThings.html",
        ),
        pat(
            "loops_smell",
            "Loops (Where Pipelines Apply)",
            "code_smell",
            "dispensable",
            "Imperative loops where a declarative pipeline would express intent more clearly.",
            "Recognize complex loops that obscure transformations.",
            "Habit; legacy code; performance assumptions.",
            "Replace Loop with Pipeline (`map`/`filter`/`reduce`/`flatMap`); benchmark if hot.",
            "Clearer transformations; reach for loops when performance demands.",
            &["functional_programming", "procedural_programming"],
            &["smell", "fp"],
            "https://refactoring.com/catalog/replaceLoopWithPipeline.html",
        ),
        pat(
            "global_data",
            "Global Data / Singletons",
            "code_smell",
            "couplers",
            "Mutable state accessible from anywhere makes change effects unpredictable.",
            "Recognize ambient mutable state.",
            "Convenience of global access; lack of injection seams.",
            "Encapsulate the global; pass it explicitly; use Dependency Injection or per-request context.",
            "Predictable change; verbosity at injection points.",
            &["object_oriented_programming", "procedural_programming"],
            &["smell", "state"],
            "https://refactoring.guru/smells/global-data",
        ),
        pat(
            "mutable_data",
            "Mutable Data",
            "code_smell",
            "object_orientation_abusers",
            "Mutability where immutability would simplify reasoning.",
            "Recognize avoidable state changes.",
            "Default mutability inherited from imperative style.",
            "Introduce immutable types (Value Objects); change-by-construction; restrict mutators to clear seams.",
            "Easier concurrency and undo; some hot paths benefit from in-place mutation.",
            &["functional_programming", "object_oriented_programming"],
            &["smell", "fp"],
            "https://refactoring.com/catalog/changeReferenceToValue.html",
        ),
        pat(
            "long_inheritance_chain",
            "Long Inheritance Chain",
            "code_smell",
            "object_orientation_abusers",
            "Deep inheritance hierarchies make behavior hard to find and change.",
            "Recognize the Yo-Yo Problem in progress.",
            "Each iteration added another base/subclass without considering composition.",
            "Replace Inheritance with Delegation; collapse layers; favor composition.",
            "Easier reasoning; takes structural refactoring effort.",
            &["object_oriented_programming"],
            &["smell", "inheritance"],
            "https://en.wikipedia.org/wiki/Yo-yo_problem",
        ),
        // ========================================
        //            FOWLER REFACTORINGS
        //         (kind="pattern", category="refactoring")
        // ========================================
        pat(
            "extract_method",
            "Extract Method",
            "pattern",
            "refactoring",
            "Turn a fragment of code that can be grouped together into its own method whose name explains the purpose.",
            "Break up long methods; reveal intent through naming.",
            "A long method mixes details and intent.",
            "Identify a fragment with a coherent purpose; copy to a new method; replace original with a call; rename arguments.",
            "Smaller, named units; risk of over-fragmentation if applied without judgment.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/extractFunction.html",
        ),
        pat(
            "inline_method",
            "Inline Method",
            "pattern",
            "refactoring",
            "Replace a method call with the body of the method.",
            "Eliminate unnecessary indirection when the method's body is as clear as its name.",
            "A method exists only to forward to another or to redundantly name what its body says.",
            "Verify no overrides; copy body to call sites; delete the method.",
            "Less indirection; only safe when the method isn't extended or replaced elsewhere.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/inlineFunction.html",
        ),
        pat(
            "extract_variable",
            "Extract Variable",
            "pattern",
            "refactoring",
            "Replace a sub-expression with an explanatory local variable.",
            "Reveal intent of complex expressions.",
            "Compound expressions are hard to read at the use site.",
            "Introduce a `let` named after the meaning; substitute uses; keep scope narrow.",
            "Self-explaining expressions; can clutter if overdone.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/extractVariable.html",
        ),
        pat(
            "inline_variable",
            "Inline Variable",
            "pattern",
            "refactoring",
            "Replace a single-use variable with the expression that initializes it.",
            "Reduce noise when a name doesn't add clarity.",
            "A short-lived variable doesn't earn its keep.",
            "Inline the initializer at the use site if the expression is simple and the meaning is obvious.",
            "Less ceremony; only when the inlined expression is small and clear.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/inlineVariable.html",
        ),
        pat(
            "change_function_declaration",
            "Change Function Declaration",
            "pattern",
            "refactoring",
            "Rename a function or change its parameter list.",
            "Improve clarity or accommodate new requirements.",
            "The current signature obscures intent or no longer matches use.",
            "Introduce the new signature with a deprecation shim; migrate callers; remove the old signature.",
            "Better API; brief churn during migration.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/changeFunctionDeclaration.html",
        ),
        pat(
            "encapsulate_variable",
            "Encapsulate Variable",
            "pattern",
            "refactoring",
            "Replace direct access with getter/setter so changes can intercept reads/writes.",
            "Add seams for caching, validation, logging, or future migration.",
            "Direct access scatters reads/writes across the codebase.",
            "Add accessors; migrate references; eventually make field private.",
            "Intercept point established; later changes won't ripple.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/encapsulateVariable.html",
        ),
        pat(
            "rename_variable",
            "Rename Variable",
            "pattern",
            "refactoring",
            "Give a variable a name that better reveals its intent.",
            "Improve readability through naming.",
            "Names became stale or were always wrong.",
            "Use IDE-assisted rename; verify tests; consider domain vocabulary.",
            "Self-documenting code; trivial when tools support it.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/renameVariable.html",
        ),
        pat(
            "introduce_parameter_object",
            "Introduce Parameter Object",
            "pattern",
            "refactoring",
            "Group commonly-passed parameters into an object.",
            "Address Long Parameter List and Data Clumps; reveal hidden concepts.",
            "Several parameters always travel together.",
            "Define a class capturing the clump; replace parameters with the object; consider behavior to move into it.",
            "Cleaner signatures; new type to maintain.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/introduceParameterObject.html",
        ),
        pat(
            "extract_class",
            "Extract Class",
            "pattern",
            "refactoring",
            "Move some fields/methods into a new class to address Large Class.",
            "Restore cohesion by splitting along responsibilities.",
            "A class accumulates multiple responsibilities.",
            "Identify a coherent subset; move into a new class; expose via composition.",
            "Smaller, cohesive classes; new class boundary to navigate.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/extractClass.html",
        ),
        pat(
            "inline_class",
            "Inline Class",
            "pattern",
            "refactoring",
            "Fold a class into another when it's no longer pulling its weight.",
            "Address Lazy Class or premature splits.",
            "A class doesn't do enough to justify its existence.",
            "Move methods/fields into the host class; delete the lazy class.",
            "Less indirection; ensure no external dependents.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/inlineClass.html",
        ),
        pat(
            "hide_delegate",
            "Hide Delegate",
            "pattern",
            "refactoring",
            "Encapsulate a delegate behind a method on the holder rather than exposing it.",
            "Reduce Law-of-Demeter violations / Message Chains.",
            "Clients reach through holder.getDelegate().doX().",
            "Add a method on the holder that performs the desired operation on the delegate.",
            "Tighter coupling to operations, looser to structure.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/hideDelegate.html",
        ),
        pat(
            "remove_middle_man",
            "Remove Middle Man",
            "pattern",
            "refactoring",
            "Get rid of pass-through methods that don't add value.",
            "Address Middle Man smell.",
            "Hide Delegate was over-applied or the wrapper grew stale.",
            "Have clients talk directly to the underlying object; delete the empty pass-through.",
            "Less indirection; only when the middleman truly adds nothing.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/removeMiddleMan.html",
        ),
        pat(
            "move_function",
            "Move Function",
            "pattern",
            "refactoring",
            "Relocate a method to a class/module where it has more cohesion.",
            "Fix Feature Envy or Misplaced Code.",
            "A method's data lives elsewhere.",
            "Copy to the new location; adjust references; remove from the old location.",
            "Better cohesion; verify external callers.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/moveFunction.html",
        ),
        pat(
            "move_field",
            "Move Field",
            "pattern",
            "refactoring",
            "Relocate a field to the class that uses it most.",
            "Reduce coupling and improve cohesion.",
            "A field belongs more to another class than to its current owner.",
            "Add field to target class; update accessors; remove from origin.",
            "Tighter cohesion; some references must be retargeted.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/moveField.html",
        ),
        pat(
            "slide_statements",
            "Slide Statements",
            "pattern",
            "refactoring",
            "Reorder lines so related operations sit together.",
            "Set up further refactorings (Extract Method, Extract Variable).",
            "Related statements are interleaved with unrelated ones.",
            "Move statements within their scope; ensure no semantic dependency is broken.",
            "Local clarity; preserve order-sensitive code.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/slideStatements.html",
        ),
        pat(
            "split_loop",
            "Split Loop",
            "pattern",
            "refactoring",
            "Separate a loop that's doing two things into two loops.",
            "Make each loop's intent obvious; enable independent refactoring.",
            "A loop accumulates multiple unrelated computations.",
            "Duplicate the loop; remove unrelated logic from each; consider pipeline transformation.",
            "Clearer intent; runtime cost up to 2x (often negligible vs. readability gain).",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/splitLoop.html",
        ),
        pat(
            "replace_loop_with_pipeline",
            "Replace Loop with Pipeline",
            "pattern",
            "refactoring",
            "Convert a hand-written loop into a chain of collection operations.",
            "Improve clarity and composability.",
            "Loops with conditionals duplicate map/filter/reduce structure.",
            "Express the loop body as composed `map`/`filter`/`reduce`/`flatMap` operations.",
            "Easier to read and combine; check performance in hot paths.",
            &["functional_programming", "procedural_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceLoopWithPipeline.html",
        ),
        pat(
            "decompose_conditional",
            "Decompose Conditional",
            "pattern",
            "refactoring",
            "Extract the predicate and branches of an `if` into named functions.",
            "Reveal intent of complex conditionals.",
            "Long predicate and bodies make the conditional hard to read.",
            "Extract `if (isFoo()) doFoo(); else doBar();` from inline computation.",
            "Self-explaining conditionals; small extra methods.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/decomposeConditional.html",
        ),
        pat(
            "consolidate_conditional",
            "Consolidate Conditional Expression",
            "pattern",
            "refactoring",
            "Combine multiple conditionals that have the same outcome.",
            "Simplify control flow.",
            "Sequential conditionals each leading to the same result.",
            "Merge predicates with logical operators; extract the combined predicate to a name.",
            "Smaller, clearer logic; combined predicates can themselves get complex.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/consolidateConditionalExpression.html",
        ),
        pat(
            "replace_nested_conditional_with_guard_clauses",
            "Replace Nested Conditional with Guard Clauses",
            "pattern",
            "refactoring",
            "Use early returns to handle exceptional cases up front.",
            "Flatten control flow; let the main path read straight through.",
            "Nested conditionals obscure the main logic.",
            "Reverse early conditions; return early for failure; let the main case fall through.",
            "Linear main path; needs care in languages without RAII for cleanup.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html",
        ),
        pat(
            "replace_conditional_with_polymorphism",
            "Replace Conditional with Polymorphism",
            "pattern",
            "refactoring",
            "Move case branches into subclass methods.",
            "Address Switch Statements smell.",
            "Repeated `switch` on a type code scatters logic.",
            "Define a class hierarchy for the types; move each branch to the appropriate subclass.",
            "Open to new variants; class explosion possible without care.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceConditionalWithPolymorphism.html",
        ),
        pat(
            "separate_query_from_modifier",
            "Separate Query from Modifier",
            "pattern",
            "refactoring",
            "Split a method that returns a value and changes state into separate query and modifier.",
            "Enforce Command-Query Separation.",
            "Callers can't reason about side effects of reads.",
            "Add a pure query; have the modifier call the query then mutate; update callers.",
            "Safer queries; some atomic operations don't split cleanly.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/separateQueryFromModifier.html",
        ),
        pat(
            "parameterize_function",
            "Parameterize Function",
            "pattern",
            "refactoring",
            "Combine similar functions by passing the varying part as a parameter.",
            "Eliminate near-duplicate functions.",
            "Several functions differ only in a literal or strategy.",
            "Identify the variation; add a parameter; collapse callers.",
            "Less duplication; signature gets one more argument.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/parameterizeFunction.html",
        ),
        pat(
            "remove_flag_argument",
            "Remove Flag Argument",
            "pattern",
            "refactoring",
            "Split a function that branches on a boolean flag into two named functions.",
            "Make the call site self-explanatory.",
            "`doX(true)` doesn't convey what the flag means.",
            "Define `doXFast()` / `doXSafe()` (or similar) and replace flag-passing calls.",
            "Clearer call sites; two functions to maintain.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/removeFlagArgument.html",
        ),
        pat(
            "replace_temp_with_query",
            "Replace Temp with Query",
            "pattern",
            "refactoring",
            "Replace a local variable with a method call.",
            "Make data accessible from anywhere in the class.",
            "A computed temp variable could be reused as a method.",
            "Extract the computation into a (pure) method; replace temp use with the method call.",
            "Reusable computation; ensure no perf regression in hot paths.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceTempWithQuery.html",
        ),
        pat(
            "pull_up_method",
            "Pull Up Method",
            "pattern",
            "refactoring",
            "Move a method that's duplicated in subclasses up to the parent class.",
            "Eliminate duplication in hierarchies.",
            "Multiple subclasses implement the same method.",
            "Move the method to the superclass; remove duplicates; verify visibility.",
            "Single source; ensure no subclass needs different behavior.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/pullUpMethod.html",
        ),
        pat(
            "push_down_method",
            "Push Down Method",
            "pattern",
            "refactoring",
            "Move a method only some subclasses use down to those subclasses.",
            "Reduce coupling at the superclass.",
            "A superclass holds behavior relevant only to a subset of children.",
            "Move the method to the relevant subclasses; remove from parent.",
            "Cleaner hierarchy; subclasses gain responsibilities to maintain.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/pushDownMethod.html",
        ),
        pat(
            "extract_superclass",
            "Extract Superclass",
            "pattern",
            "refactoring",
            "Create a superclass to host common behavior of two or more classes.",
            "Address duplicated structure and behavior.",
            "Two classes share similar code/structure.",
            "Identify common members; create a base class; move them up; have classes extend the base.",
            "Reusable abstraction; LSP must be respected.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/extractSuperclass.html",
        ),
        pat(
            "collapse_hierarchy",
            "Collapse Hierarchy",
            "pattern",
            "refactoring",
            "Merge a class with its parent when distinction is no longer meaningful.",
            "Simplify a hierarchy that has shed its purpose.",
            "Inheritance no longer serves a need.",
            "Move members into the parent (or child); delete the redundant level.",
            "Smaller hierarchy; users may need updates.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/collapseHierarchy.html",
        ),
        pat(
            "replace_subclass_with_delegate",
            "Replace Subclass with Delegate",
            "pattern",
            "refactoring",
            "Replace inheritance with a delegate object.",
            "Avoid hierarchy issues (Refused Bequest, Yo-Yo Problem).",
            "Subclassing was chosen for reuse rather than IS-A.",
            "Identify the responsibilities; introduce a delegate field; forward selected calls; remove the subclass.",
            "Composition gain; some boilerplate added by forwarding.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceSubclassWithDelegate.html",
        ),
        pat(
            "introduce_assertion",
            "Introduce Assertion",
            "pattern",
            "refactoring",
            "Document and check an invariant explicitly with an assertion.",
            "Make implicit assumptions explicit and catch violations early.",
            "Assumptions held tacitly drift as code evolves.",
            "Add an `assert` at the point the invariant must hold; phrase it positively; tests can use stronger checks.",
            "Earlier detection of bugs; runtime cost generally negligible.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/introduceAssertion.html",
        ),
        pat(
            "replace_primitive_with_object",
            "Replace Primitive with Object",
            "pattern",
            "refactoring",
            "Wrap a primitive used as a domain concept in an object that captures behavior.",
            "Address Primitive Obsession.",
            "Strings/integers carry domain meaning but no behavior or invariants.",
            "Introduce a value object; migrate field type; move related behavior into it.",
            "Type-safe domain concepts; another class to navigate.",
            &["object_oriented_programming", "functional_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replacePrimitiveWithObject.html",
        ),
        pat(
            "replace_constructor_with_factory_function",
            "Replace Constructor with Factory Function",
            "pattern",
            "refactoring",
            "Use a static factory function instead of a constructor.",
            "Allow polymorphic creation, intention-revealing names, and validation.",
            "Constructors are limited in name and can't return subtypes.",
            "Add a named factory function; deprecate the constructor; migrate callers.",
            "Named, validated creation; constructor remains as the implementation detail.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceConstructorWithFactoryFunction.html",
        ),
        pat(
            "split_phase",
            "Split Phase",
            "pattern",
            "refactoring",
            "Separate a function that performs two distinct phases into two functions/objects.",
            "Make each phase replaceable and testable.",
            "A function parses-then-processes (or similar) in one tangle.",
            "Split into Phase 1 producing an intermediate representation and Phase 2 consuming it.",
            "Composable phases; an intermediate representation to maintain.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/splitPhase.html",
        ),
        pat(
            "replace_magic_number_with_symbolic_constant",
            "Replace Magic Number with Symbolic Constant",
            "pattern",
            "refactoring",
            "Replace literal numbers/strings with named constants that reveal intent.",
            "Make code self-documenting and updatable in one place.",
            "Bare literals scattered in code obscure meaning and complicate changes.",
            "Define `const TIMEOUT_SECONDS: u64 = 30;`; replace all 30s used as timeout with the constant.",
            "Self-documenting; constants need ownership and review.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceMagicLiteral.html",
        ),
        pat(
            "replace_method_with_method_object",
            "Replace Method with Method Object",
            "pattern",
            "refactoring",
            "Turn a long method into its own class so it can be split into many private methods.",
            "Enable Extract Method across a complex method's local variables.",
            "Local variables prevent direct Extract Method without parameter-passing pain.",
            "Create a class whose fields are the locals; original body becomes a `compute()` method; refactor freely inside.",
            "Decomposes intractable methods; introduces a class for a transient computation.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceMethodWithMethodObject.html",
        ),
        pat(
            "form_template_method",
            "Form Template Method",
            "pattern",
            "refactoring",
            "Two similar methods in subclasses → push common skeleton up; defer differing steps to subclasses.",
            "Eliminate duplication while preserving variation.",
            "Two subclasses share order/structure but differ in details.",
            "Identify the common skeleton; pull up; declare abstract hook methods; subclasses override hooks.",
            "Less duplication; inheritance coupling.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/formTemplateMethod.html",
        ),
        pat(
            "replace_inheritance_with_delegation",
            "Replace Inheritance with Delegation",
            "pattern",
            "refactoring",
            "Convert a subclass into a class that holds a delegate of the former base.",
            "Address Refused Bequest / Yo-Yo Problem from inheritance overuse.",
            "Inheritance was used for reuse rather than IS-A.",
            "Hold a `super: Base` field; forward selected calls; remove inheritance; LSP no longer applies.",
            "Looser coupling; some forwarding boilerplate.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceSubclassWithDelegate.html",
        ),
        pat(
            "tease_apart_inheritance",
            "Tease Apart Inheritance",
            "pattern",
            "refactoring",
            "Untangle a hierarchy that conflates two orthogonal variation axes into a separate composition.",
            "Address combinatorial subclass explosion.",
            "One hierarchy mixes two unrelated dimensions of variation.",
            "Identify the two axes; keep one as inheritance; turn the other into composition via a strategy/role object.",
            "Linear instead of quadratic class growth; major restructure.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/teaseApartInheritance.html",
        ),
        pat(
            "replace_recursion_with_iteration",
            "Replace Recursion with Iteration",
            "pattern",
            "refactoring",
            "Rewrite a recursive function as a loop, optionally with an explicit stack.",
            "Avoid stack overflow or improve cache/locality.",
            "Deep recursion overflows the call stack or is harder to debug.",
            "For tail recursion, convert directly to a loop; for non-tail, maintain an explicit work stack/queue.",
            "Stack-safe; loses some recursive clarity.",
            &["procedural_programming", "functional_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/",
        ),
        pat(
            "replace_iteration_with_recursion",
            "Replace Iteration with Recursion",
            "pattern",
            "refactoring",
            "Rewrite a loop with mutable state as recursion (especially over trees).",
            "Express tree/graph traversals naturally and immutably.",
            "Imperative loops over recursive structures duplicate traversal mechanics.",
            "Express the loop body as a recursive function over the structure; use tail-position where the language has TCO.",
            "Closer to the data structure; needs TCO or trampoline for deep recursion.",
            &["functional_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/",
        ),
        pat(
            "encapsulate_field",
            "Encapsulate Field",
            "pattern",
            "refactoring",
            "Replace direct public-field access with getter/setter methods.",
            "Add a seam for validation, lazy init, change events.",
            "Public field access spreads everywhere and can't be intercepted.",
            "Add accessors; migrate references; make field private.",
            "Future-proofs the API; small ceremony.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/encapsulateVariable.html",
        ),
        pat(
            "encapsulate_collection",
            "Encapsulate Collection",
            "pattern",
            "refactoring",
            "Return a read-only or copy view of an internal collection; provide add/remove methods.",
            "Prevent callers from violating invariants by mutating internals.",
            "Returning raw mutable collections leaks invariants.",
            "Return `Vec::clone` or wrap in unmodifiable view; expose add/remove methods that enforce rules.",
            "Invariants preserved; small allocation per read in some languages.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/encapsulateCollection.html",
        ),
        pat(
            "replace_type_code_with_state",
            "Replace Type Code with State / Strategy",
            "pattern",
            "refactoring",
            "Replace a type code field with a State or Strategy hierarchy.",
            "Address Switch Statements / type-code branching.",
            "Type codes scatter branching across many methods.",
            "Introduce a State/Strategy interface; one subclass per variant; the original field becomes a polymorphic instance.",
            "Open-closed for new variants; class growth.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceTypeCodeWithSubclasses.html",
        ),
        pat(
            "separate_domain_from_presentation",
            "Separate Domain from Presentation",
            "pattern",
            "refactoring",
            "Move domain logic out of UI/controller code into pure domain classes.",
            "Make domain testable independently of UI.",
            "Logic embedded in UI handlers is hard to test and reuse.",
            "Identify computation in handlers; extract to domain types; UI becomes a thin caller.",
            "Decoupled, testable domain; mapping at the boundary.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://martinfowler.com/eaaCatalog/separatedPresentation.html",
        ),
        pat(
            "replace_subclass_with_fields",
            "Replace Subclass with Fields",
            "pattern",
            "refactoring",
            "Replace subclasses whose only difference is constant return values with fields on the superclass.",
            "Eliminate trivial subclasses.",
            "Subclasses exist only to return different constants.",
            "Add fields to the superclass; instantiate with appropriate values; delete subclasses.",
            "Smaller hierarchy; loses ability to add subclass-specific behavior later.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceSubclassWithFields.html",
        ),
        pat(
            "replace_constructor_with_builder",
            "Replace Constructor with Builder",
            "pattern",
            "refactoring",
            "Replace a constructor with a fluent builder when there are many optional parameters.",
            "Improve readability of complex construction.",
            "Long constructors with many optional positional parameters are hard to read.",
            "Define a builder with fluent setters; final `build()` returns the immutable object; constructor becomes private.",
            "Self-documenting construction; one extra class.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/",
        ),
        pat(
            "replace_derived_variable_with_query",
            "Replace Derived Variable with Query",
            "pattern",
            "refactoring",
            "Delete a field whose value is always derived from other state; compute it via a method.",
            "Eliminate redundant state that can desynchronize.",
            "Stored derived values diverge from their sources.",
            "Delete the field; expose a method that computes from authoritative state.",
            "No drift; ensure compute cost is acceptable (memoize if hot).",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/replaceDerivedVariableWithQuery.html",
        ),
        pat(
            "hide_method",
            "Hide Method",
            "pattern",
            "refactoring",
            "Reduce a method's visibility (public → protected → private) when no external caller needs it.",
            "Shrink the public surface to only what callers actually need.",
            "Methods marked public for convenience increase coupling risk.",
            "Identify unused public methods; lower their visibility to the minimum that compiles; keep tests scoped accordingly.",
            "Smaller API; refactoring is easier afterwards.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/",
        ),
        pat(
            "parallel_change",
            "Parallel Change",
            "pattern",
            "refactoring",
            "Generic name for Expand-Contract migrations (also called Branch by Abstraction in code, Parallel Change in APIs).",
            "Change interfaces/schemas without breaking callers/data.",
            "In-place breaking changes require synchronized rollouts.",
            "Expand → Migrate → Contract; old and new coexist during the migration window.",
            "Continuous compatibility; more steps than a direct change.",
            &["object_oriented_programming", "distributed_systems"],
            &["refactoring", "fowler"],
            "https://martinfowler.com/bliki/ParallelChange.html",
        ),
        pat(
            "extract_interface",
            "Extract Interface",
            "pattern",
            "refactoring",
            "Introduce an interface for the public methods clients actually use.",
            "Decouple consumers from the concrete implementation.",
            "Clients import a concrete class and inherit unwanted coupling.",
            "List the methods used by clients; define an interface; have the class implement it; clients depend on the interface.",
            "Testability and substitution; one extra type to navigate.",
            &["object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/",
        ),
        pat(
            "reorder_parameters",
            "Reorder / Rename Parameters",
            "pattern",
            "refactoring",
            "Adjust parameter order or names to improve readability and consistency.",
            "Make signatures match each other and avoid mistakes.",
            "Inconsistent parameter orders cause swap bugs.",
            "Use IDE rename / change-signature; update call sites; consider Introduce Parameter Object if order is fragile.",
            "Cleaner signatures; potentially breaking change.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/changeFunctionDeclaration.html",
        ),
        pat(
            "substitute_algorithm",
            "Substitute Algorithm",
            "pattern",
            "refactoring",
            "Replace a method's body with a clearer or faster algorithm.",
            "Improve readability or performance while keeping the contract.",
            "Existing algorithm is muddled or slow.",
            "Cover with tests; swap algorithm; verify behavior identical; commit.",
            "Better performance/clarity; tests must cover edge cases.",
            &["procedural_programming", "object_oriented_programming"],
            &["refactoring", "fowler"],
            "https://refactoring.com/catalog/substituteAlgorithm.html",
        ),
        pat(
            "reify_concept",
            "Reify Concept (Introduce Type)",
            "pattern",
            "refactoring",
            "Promote an implicit concept to an explicit type with behavior.",
            "Make implicit business concepts visible and reusable.",
            "Concepts (Money, Email, OrderId) live as primitive fields and re-implement logic everywhere.",
            "Identify the concept; create a value object; migrate fields; centralize behavior.",
            "Type-safe domain; refactor effort proportional to call-site count.",
            &["object_oriented_programming"],
            &["refactoring", "ddd"],
            "https://martinfowler.com/bliki/ValueObject.html",
        ),
        // ---------- New code smells ----------
        pat(
            "indecent_exposure",
            "Indecent Exposure",
            "code_smell",
            "couplers",
            "A class exposes too much of its internals as public surface.",
            "Recognize over-broad APIs that invite tight coupling.",
            "Convenience public access blooms over time.",
            "Audit public/protected members; lower visibility to the minimum needed; add tests for the kept surface.",
            "Smaller, harder-to-misuse APIs; brief migration churn.",
            &["object_oriented_programming"],
            &["smell", "couplers"],
            "https://wiki.c2.com/?IndecentExposure",
        ),
        pat(
            "distant_object_smell",
            "Distant Object (Law-of-Demeter Violation)",
            "code_smell",
            "couplers",
            "Code reaches across multiple object boundaries to operate on a far-away object.",
            "Recognize chains that violate the Law of Demeter.",
            "Easy to write `a.b().c().d()` rather than ask the immediate neighbor.",
            "Apply Hide Delegate; let intermediaries expose only the operations callers need.",
            "Lower coupling; possibly more middleman methods.",
            &["object_oriented_programming"],
            &["smell", "couplers"],
            "https://en.wikipedia.org/wiki/Law_of_Demeter",
        ),
        pat(
            "excessive_conditionals",
            "Excessive Conditionals",
            "code_smell",
            "object_orientation_abusers",
            "Pervasive nested `if/switch` chains obscure the design.",
            "Recognize logic that should be polymorphism or table-driven.",
            "Conditionals accrete as variants are added.",
            "Replace conditionals with polymorphism, state, strategy, or lookup tables; flatten with guard clauses.",
            "Cleaner control flow; possibly more types.",
            &["object_oriented_programming"],
            &["smell"],
            "https://refactoring.guru/smells/switch-statements",
        ),
        pat(
            "underabstraction",
            "Underabstraction",
            "code_smell",
            "dispensable",
            "Code duplicates concepts because no abstraction was introduced.",
            "Recognize repeated structure that begs for an abstraction.",
            "Each use case is implemented from scratch.",
            "Identify common patterns; extract an abstraction (function, class, generic) once a few use cases exist.",
            "Reusable building blocks; not premature.",
            &["object_oriented_programming"],
            &["smell"],
            "https://refactoring.guru/smells/duplicate-code",
        ),
        pat(
            "overabstraction",
            "Overabstraction",
            "code_smell",
            "dispensable",
            "Abstractions exist for variation that never materialized; readers must traverse them anyway.",
            "Recognize speculative scaffolding that pays no return.",
            "Engineers anticipate variation and abstract preemptively.",
            "Inline abstractions whose only implementation never branches; restore concrete code.",
            "Easier reading; loss of speculative extensibility.",
            &["object_oriented_programming"],
            &["smell"],
            "https://refactoring.guru/smells/speculative-generality",
        ),
    ]
}
