//! Concurrent, parallel, actor-model, reactive, and dataflow patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- Concurrent primitives ----------
        pat(
            "mutex",
            "Mutex (Mutual Exclusion)",
            "pattern",
            "concurrency",
            "Allow only one thread at a time to hold the lock around a critical section.",
            "Serialize access to shared mutable state.",
            "Multiple threads racing on shared data produce torn writes or invariants violations.",
            "Acquire the lock before touching the protected region, release on exit (RAII/scoped guard).",
            "Simple and correct when contention is moderate; coarse-grained locking limits parallelism.",
            &["concurrent_programming"],
            &["concurrency", "synchronization"],
            "https://en.wikipedia.org/wiki/Mutual_exclusion",
        ),
        pat(
            "reader_writer_lock",
            "Reader-Writer Lock",
            "pattern",
            "concurrency",
            "Allow concurrent readers but exclusive writers on shared state.",
            "Improve throughput when reads dominate writes.",
            "A plain mutex serializes readers needlessly when writes are rare.",
            "Use a lock supporting shared read locks and exclusive write locks; bias toward writers if needed.",
            "Higher read throughput; write-heavy workloads can starve readers (or vice versa) under naive policies.",
            &["concurrent_programming"],
            &["concurrency", "synchronization"],
            "https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock",
        ),
        pat(
            "double_checked_locking",
            "Double-Checked Locking",
            "pattern",
            "concurrency",
            "Check a flag without locking, then lock and re-check before initializing.",
            "Avoid the cost of locking on the common (already-initialized) path.",
            "Single-checked initialization either always locks or races.",
            "Use atomic load + lock + atomic load + initialize + atomic store, with proper memory ordering (or `Once`).",
            "Fast common path; only correct with appropriate atomics / memory model (broken in many naive ports).",
            &["concurrent_programming"],
            &["concurrency", "initialization"],
            "https://en.wikipedia.org/wiki/Double-checked_locking",
        ),
        pat(
            "monitor",
            "Monitor",
            "pattern",
            "concurrency",
            "Bundle a lock with condition variables in one synchronized object.",
            "Coordinate threads waiting for state conditions without ad-hoc spin loops.",
            "Manual `wait/notify` and lock juggling is error prone.",
            "Use a class/object whose methods enter the lock and use `wait/signal` on its condition.",
            "Cleaner critical sections; misuse (spurious wakeups) still requires looped predicates.",
            &["concurrent_programming"],
            &["concurrency", "synchronization"],
            "https://en.wikipedia.org/wiki/Monitor_(synchronization)",
        ),
        pat(
            "semaphore",
            "Semaphore",
            "pattern",
            "concurrency",
            "A counter for permits that blocks acquirers when zero.",
            "Bound concurrent access to a resource or signal between threads.",
            "Coarse locks can't express 'at most N concurrent users' or producer/consumer counts.",
            "Initialize with N permits; `acquire` blocks if none available; `release` returns a permit.",
            "Flexible coordination; ownership is not enforced so leaks are easy.",
            &["concurrent_programming"],
            &["concurrency", "synchronization"],
            "https://en.wikipedia.org/wiki/Semaphore_(programming)",
        ),
        pat(
            "barrier",
            "Barrier",
            "pattern",
            "concurrency",
            "Block participating threads until all have arrived at the barrier point.",
            "Synchronize phases of a parallel computation.",
            "Workers race past phase boundaries and consume partial results from the next phase.",
            "Initialize a barrier with N parties; each calls `await`; control resumes when all N arrive.",
            "Clean phase synchronization; faulty parties can deadlock the group.",
            &["concurrent_programming", "parallel_programming"],
            &["concurrency", "phase_sync"],
            "https://en.wikipedia.org/wiki/Barrier_(computer_science)",
        ),
        pat(
            "count_down_latch",
            "Count-Down Latch",
            "pattern",
            "concurrency",
            "A one-shot countdown; threads wait until the count reaches zero.",
            "Wait for a set of independent tasks to finish before continuing.",
            "Joining each worker thread individually couples the coordinator to thread count.",
            "Initialize with N; each task `countDown()`; waiters block on `await()`.",
            "Easy fan-out completion gate; cannot be reset (use a Barrier or Phaser instead).",
            &["concurrent_programming"],
            &["concurrency", "completion"],
            "https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CountDownLatch.html",
        ),
        pat(
            "future_promise",
            "Future / Promise",
            "pattern",
            "concurrency",
            "Represent a value that will be available later, with composition operators on its result.",
            "Express asynchronous computation as values rather than callbacks.",
            "Callback-based async APIs nest and obscure error handling.",
            "Return a Future; consumers compose with `then`/`flatMap`; producers fulfill via the Promise side.",
            "Composable asynchrony; backpressure is not built in.",
            &["concurrent_programming", "functional_programming"],
            &["concurrency", "async"],
            "https://en.wikipedia.org/wiki/Futures_and_promises",
        ),
        pat(
            "promise_pipelining",
            "Promise Pipelining",
            "pattern",
            "concurrency",
            "Send messages to a promise's eventual target before it resolves to reduce round-trips.",
            "Cut latency in distributed call chains where each call uses the previous result.",
            "Sequential remote calls each pay a full round-trip and cannot overlap.",
            "Address messages to a promise; the broker forwards them when the target is known.",
            "Lower latency for chains; requires runtime/transport support (E, Cap'n Proto, future-RPC).",
            &["distributed_systems", "concurrent_programming"],
            &["concurrency", "rpc", "latency"],
            "https://en.wikipedia.org/wiki/Futures_and_promises#Promise_pipelining",
        ),
        pat(
            "reactor_pattern",
            "Reactor",
            "pattern",
            "concurrency",
            "Dispatch synchronous events to handlers via a single event loop.",
            "Multiplex I/O across many connections with one thread of control.",
            "Thread-per-connection doesn't scale to thousands of mostly-idle sockets.",
            "Run an event loop that uses readiness notifications (epoll/kqueue/IOCP) and dispatches to handlers.",
            "High scalability; handlers must be non-blocking or work is offloaded.",
            &["concurrent_programming", "event_driven_programming"],
            &["concurrency", "io"],
            "https://en.wikipedia.org/wiki/Reactor_pattern",
        ),
        pat(
            "proactor_pattern",
            "Proactor",
            "pattern",
            "concurrency",
            "Use asynchronous I/O completion notifications instead of readiness notifications.",
            "Let the OS perform I/O and notify when the operation has finished.",
            "Reactor pattern still requires user code to do the read/write after readiness.",
            "Issue async I/O operations; receive completion events and dispatch to handlers.",
            "Higher peak throughput; portability is harder (Windows IOCP vs Linux io_uring).",
            &["concurrent_programming", "event_driven_programming"],
            &["concurrency", "io"],
            "https://en.wikipedia.org/wiki/Proactor_pattern",
        ),
        pat(
            "half_sync_half_async",
            "Half-Sync / Half-Async",
            "pattern",
            "concurrency",
            "Split the system into an async layer (event-driven I/O) and a sync layer (worker threads) connected by a queue.",
            "Give application code synchronous ergonomics while keeping I/O scalable.",
            "Pure async code is hard to write for complex business logic; pure sync per connection doesn't scale.",
            "Have an async I/O layer enqueue work; a pool of synchronous workers dequeues and runs blocking logic.",
            "Hybrid simplicity; the queue is a backpressure bottleneck to size carefully.",
            &["concurrent_programming"],
            &["concurrency", "architecture"],
            "https://www.dre.vanderbilt.edu/~schmidt/PDF/HS-HA.pdf",
        ),
        pat(
            "active_object",
            "Active Object",
            "pattern",
            "concurrency",
            "Decouple method invocation from method execution by placing each call on a queue served by an owning thread.",
            "Provide thread-safe, asynchronous method calls behind a normal-looking interface.",
            "Direct method calls on shared objects require external synchronization at every call site.",
            "Wrap the object with a scheduler/queue; clients see method calls that enqueue work; one worker thread executes.",
            "Hides synchronization; queue depth and ordering must be managed.",
            &["concurrent_programming"],
            &["concurrency", "encapsulation"],
            "https://en.wikipedia.org/wiki/Active_object",
        ),
        pat(
            "guarded_suspension",
            "Guarded Suspension",
            "pattern",
            "concurrency",
            "If a precondition isn't met, suspend the calling thread until it becomes true.",
            "Block cleanly on resources without polling.",
            "Polling for state changes wastes CPU and adds latency jitter.",
            "Inside a monitor, loop on the predicate calling `wait`; signal whenever the predicate may have changed.",
            "Efficient blocking; predicate must be checked in a loop to handle spurious wakeups.",
            &["concurrent_programming"],
            &["concurrency", "blocking"],
            "https://en.wikipedia.org/wiki/Guarded_suspension",
        ),
        pat(
            "balking",
            "Balking",
            "pattern",
            "concurrency",
            "If the system is not in the right state, return without doing anything rather than waiting.",
            "Avoid blocking when only one of many invocations should succeed.",
            "Multiple callers issue identical requests; only the first should do work.",
            "Check state under a lock; if already set, return; otherwise perform the action and update state.",
            "Cheap and non-blocking; callers must be ok with no-op responses.",
            &["concurrent_programming"],
            &["concurrency", "idempotency"],
            "https://en.wikipedia.org/wiki/Balking_pattern",
        ),
        pat(
            "thread_specific_storage",
            "Thread-Specific Storage",
            "pattern",
            "concurrency",
            "Give each thread its own instance of a variable, accessed through a common key.",
            "Avoid synchronization on per-request state.",
            "Sharing state across threads requires locking; passing it through every call is noisy.",
            "Use ThreadLocal / TLS APIs to attach per-thread state to a logical key.",
            "Lock-free access; lifetime and cleanup must be managed (especially with pooled threads).",
            &["concurrent_programming"],
            &["concurrency", "state"],
            "https://en.wikipedia.org/wiki/Thread-local_storage",
        ),
        pat(
            "worker_pool",
            "Worker Pool",
            "pattern",
            "concurrency",
            "Run bounded workers that pull tasks from a queue.",
            "Limit resource usage while processing many jobs.",
            "One task per thread/goroutine would overload the process.",
            "Use a fixed or adaptive pool and feed it through a queue/channel.",
            "Predictable capacity; queueing and cancellation policy are essential.",
            &["concurrent_programming", "parallel_programming"],
            &["concurrency", "throughput"],
            "https://en.wikipedia.org/wiki/Thread_pool",
        ),
        pat(
            "leader_followers",
            "Leader / Followers",
            "pattern",
            "concurrency",
            "A pool of threads where one is the leader that waits for events and promotes a follower before processing.",
            "Multiplex I/O across a thread pool without a central dispatcher.",
            "A dispatcher thread becomes a bottleneck and adds context switches.",
            "Threads coordinate so exactly one waits on the event source; on event, that thread promotes another and handles the work itself.",
            "Lower latency than reactor + queue; complex coordination logic.",
            &["concurrent_programming"],
            &["concurrency", "io"],
            "https://www.dre.vanderbilt.edu/~schmidt/PDF/lf.pdf",
        ),
        pat(
            "scoped_locking",
            "Scoped Locking (RAII)",
            "pattern",
            "concurrency",
            "Acquire a lock in a constructor and release it in a destructor tied to a scope.",
            "Guarantee lock release on all exit paths including panics/exceptions.",
            "Manual lock/unlock pairs leak on early returns or exceptions.",
            "Use a lock guard object (`std::lock_guard`, `MutexGuard`) whose destructor releases the lock.",
            "Exception/panic safe; only works in languages with deterministic destruction.",
            &["concurrent_programming"],
            &["concurrency", "safety", "rust", "cpp"],
            "https://en.cppreference.com/w/cpp/thread/lock_guard",
        ),
        pat(
            "strategized_locking",
            "Strategized Locking",
            "pattern",
            "concurrency",
            "Parameterize a component by a locking strategy (no-op, mutex, RW-lock) chosen at construction.",
            "Reuse one component across single-threaded and multi-threaded contexts without rewriting.",
            "Hard-coded locks penalize single-threaded users; no locks risk multi-threaded ones.",
            "Wrap critical sections in a `Lockable` strategy passed in by the owner.",
            "One implementation, many concurrency profiles; obscures actual lock policy at the call site.",
            &["concurrent_programming"],
            &["concurrency", "policy"],
            "https://www.dre.vanderbilt.edu/~schmidt/PDF/locking-patterns.pdf",
        ),
        pat(
            "thread_safe_interface",
            "Thread-Safe Interface",
            "pattern",
            "concurrency",
            "Public methods acquire locks; private methods assume the lock is held.",
            "Avoid double-locking when public methods call each other.",
            "Public methods that call other public methods either double-lock or have inconsistent guarantees.",
            "Split interface methods that lock from implementation methods that don't; only public entry points acquire the lock.",
            "Clear contract; requires discipline to keep internal calls on private methods.",
            &["concurrent_programming"],
            &["concurrency", "api_design"],
            "https://www.dre.vanderbilt.edu/~schmidt/PDF/locking-patterns.pdf",
        ),
        pat(
            "specific_notification",
            "Specific Notification",
            "pattern",
            "concurrency",
            "Wake only the threads waiting on a specific condition rather than `notifyAll`.",
            "Avoid the thundering herd of generic broadcasts.",
            "`notifyAll` wakes everyone for every change, leading to wasted re-checks.",
            "Give each predicate its own condition variable; `signal` only the relevant one.",
            "Better scheduling; more condition variables to manage.",
            &["concurrent_programming"],
            &["concurrency", "signaling"],
            "https://en.wikipedia.org/wiki/Monitor_(synchronization)",
        ),
        // ---------- Lock-free / advanced ----------
        pat(
            "lock_free_queue",
            "Lock-Free Queue",
            "pattern",
            "concurrency",
            "Concurrent queue whose operations make global progress using atomic instructions instead of locks.",
            "Avoid contention and priority inversion of mutex-based queues.",
            "Locked queues become a bottleneck for high-throughput producers/consumers.",
            "Use Michael-Scott (MPMC), or specialized SPSC/MPSC/SPMC variants with appropriate memory ordering.",
            "High throughput; correctness is subtle (ABA, memory reclamation).",
            &["concurrent_programming"],
            &["concurrency", "lock_free"],
            "https://en.wikipedia.org/wiki/Non-blocking_algorithm",
        ),
        pat(
            "single_producer_single_consumer_queue",
            "SPSC Queue",
            "pattern",
            "concurrency",
            "Specialized lock-free queue with one producer and one consumer thread.",
            "Achieve maximum throughput / minimum latency for 1:1 producer/consumer.",
            "General-purpose MPMC queues pay synchronization cost neither side needs.",
            "Use a ring buffer with two atomic indices; only producer writes head, only consumer writes tail.",
            "Very fast; only usable when producer and consumer cardinalities are guaranteed 1:1.",
            &["concurrent_programming"],
            &["concurrency", "lock_free", "queue"],
            "https://en.wikipedia.org/wiki/Producer%E2%80%93consumer_problem",
        ),
        pat(
            "multi_producer_single_consumer_queue",
            "MPSC Queue",
            "pattern",
            "concurrency",
            "Lock-free queue with many producers and one consumer.",
            "Funnel work from many sources to a single processor (e.g., logger, event loop).",
            "Locking would serialize producers unnecessarily.",
            "Use an intrusive linked list with CAS for enqueue; consumer doesn't contend with enqueue side.",
            "Excellent for fan-in; consumer becomes the bottleneck if too slow.",
            &["concurrent_programming"],
            &["concurrency", "lock_free", "queue"],
            "https://www.1024cores.net/home/lock-free-algorithms/queues",
        ),
        pat(
            "hazard_pointers",
            "Hazard Pointers",
            "pattern",
            "concurrency",
            "Per-thread pointers to nodes that the thread is currently reading; reclamation respects these hazards.",
            "Safely reclaim memory in lock-free data structures without GC.",
            "Lock-free structures often suffer use-after-free if memory is freed too eagerly.",
            "Publish hazard pointers before dereferencing; deferred reclamation walks them before freeing.",
            "Correct and predictable; per-access overhead and storage proportional to thread count.",
            &["concurrent_programming"],
            &["concurrency", "lock_free", "memory"],
            "https://en.wikipedia.org/wiki/Hazard_pointer",
        ),
        pat(
            "rcu",
            "Read-Copy-Update (RCU)",
            "pattern",
            "concurrency",
            "Readers run lock-free; writers create new versions and reclaim old ones after a grace period.",
            "Maximize read scalability for predominantly-read structures.",
            "Locks throttle readers in read-heavy workloads.",
            "Readers traverse without locks; writers publish new versions atomically; reclaim once all pre-existing readers have left their critical sections.",
            "Excellent read throughput; readers see a slightly older view and writers are more expensive.",
            &["concurrent_programming"],
            &["concurrency", "lock_free", "kernel"],
            "https://en.wikipedia.org/wiki/Read-copy-update",
        ),
        pat(
            "software_transactional_memory",
            "Software Transactional Memory (STM)",
            "pattern",
            "concurrency",
            "Wrap reads/writes to shared state in transactions that retry on conflict.",
            "Compose concurrent updates without manual lock orchestration.",
            "Lock-based coordination of multiple shared variables is error-prone and not composable.",
            "Read inside `atomically`; commit if no conflicting writes; otherwise retry.",
            "Composable concurrency; per-transaction overhead and contention can hurt.",
            &["concurrent_programming", "functional_programming"],
            &["concurrency", "transactions"],
            "https://en.wikipedia.org/wiki/Software_transactional_memory",
        ),
        // ---------- Parallel patterns ----------
        pat(
            "fork_join",
            "Fork-Join",
            "pattern",
            "parallel",
            "Recursively split a problem into subtasks, run them in parallel, then join the results.",
            "Express divide-and-conquer parallelism naturally.",
            "Explicit thread management for recursive parallel tasks is verbose.",
            "Use a fork-join framework (Java ForkJoinPool, OpenMP tasks, Cilk) with parallel-spawn and join.",
            "Excellent for recursive parallelism; granularity must avoid task overhead.",
            &["parallel_programming", "concurrent_programming"],
            &["parallel", "recursion"],
            "https://en.wikipedia.org/wiki/Fork%E2%80%93join_model",
        ),
        pat(
            "work_stealing",
            "Work Stealing",
            "pattern",
            "parallel",
            "Idle workers steal tasks from busy workers' double-ended queues.",
            "Balance load automatically across worker threads.",
            "Static partitioning leaves some workers idle while others have backlog.",
            "Each worker has a local deque; pushes/pops from one end; idle workers steal from others' opposite end.",
            "Self-balancing; deque contention and steal protocol design are tricky.",
            &["parallel_programming", "concurrent_programming"],
            &["parallel", "scheduling"],
            "https://en.wikipedia.org/wiki/Work_stealing",
        ),
        pat(
            "fan_out_fan_in",
            "Fan-out/Fan-in",
            "pattern",
            "concurrency",
            "Split work across concurrent workers and merge results.",
            "Parallelize independent work and collect outputs.",
            "A single stage is slower than the available parallelism.",
            "Distribute input to workers and merge their result streams safely.",
            "Improves throughput; ordering, errors, and cancellation must be explicit.",
            &[
                "concurrent_programming",
                "parallel_programming",
                "dataflow_programming",
            ],
            &["concurrency", "go"],
            "https://go.dev/blog/pipelines",
        ),
        pat(
            "pipeline_cancellation",
            "Pipeline Cancellation",
            "pattern",
            "concurrency",
            "Propagate cancellation through pipeline stages.",
            "Avoid leaked workers when downstream exits early.",
            "Concurrent stages block forever after a consumer stops reading.",
            "Thread a cancellation signal through every stage and close outputs on exit.",
            "Prevents leaks; every blocking send/receive must participate.",
            &["concurrent_programming", "dataflow_programming"],
            &["concurrency", "go", "lifecycle"],
            "https://go.dev/blog/pipelines",
        ),
        pat(
            "map_reduce",
            "MapReduce",
            "pattern",
            "parallel",
            "Map independent inputs and reduce partial results.",
            "Scale data-parallel computation.",
            "A large dataset can be partitioned into independent work.",
            "Apply a map function per partition and combine outputs with an associative reducer.",
            "Robust for batch work; not ideal for low-latency workflows.",
            &[
                "parallel_programming",
                "distributed_systems",
                "functional_programming",
                "dataflow_programming",
            ],
            &["parallel", "data"],
            "https://en.wikipedia.org/wiki/MapReduce",
        ),
        pat(
            "scatter_gather_parallel",
            "Scatter-Gather (Parallel)",
            "pattern",
            "parallel",
            "Broadcast a task to many workers in parallel and collect their results.",
            "Aggregate independent computations or queries.",
            "Sequential querying or computation of independent results wastes parallelism.",
            "Scatter the request to all workers concurrently; await all responses and combine.",
            "Best when subtasks are independent and homogeneous; slowest worker dominates.",
            &["parallel_programming", "distributed_systems"],
            &["parallel", "messaging"],
            "https://www.enterpriseintegrationpatterns.com/patterns/messaging/BroadcastAggregate.html",
        ),
        pat(
            "stencil_computation",
            "Stencil Computation",
            "pattern",
            "parallel",
            "Apply the same update rule to each grid cell based on its neighbors, repeatedly.",
            "Express PDE solvers, image filters, cellular automata as data-parallel kernels.",
            "Sequential nested loops over large grids underuse modern hardware.",
            "Parallelize by tiles or rows; manage halos / ghost cells across partitions.",
            "Highly parallel and SIMD-friendly; memory bandwidth and halo exchange dominate at scale.",
            &["parallel_programming", "dataflow_programming"],
            &["parallel", "hpc"],
            "https://en.wikipedia.org/wiki/Iterative_Stencil_Loops",
        ),
        // ---------- Actor model ----------
        pat(
            "actor_model",
            "Actor Model",
            "pattern",
            "concurrency",
            "Encapsulate state inside actors that communicate with messages.",
            "Avoid shared mutable state while preserving concurrency.",
            "Locks around shared state become complex or fragile.",
            "Give each actor a mailbox and process messages serially.",
            "Strong isolation; message protocols and supervision matter.",
            &[
                "actor_model",
                "concurrent_programming",
                "distributed_systems",
                "event_driven_programming",
            ],
            &["concurrency", "messaging"],
            "https://en.wikipedia.org/wiki/Actor_model",
        ),
        pat(
            "supervisor_tree",
            "Supervisor Tree",
            "pattern",
            "concurrency",
            "Organize actors/processes into a tree where supervisors restart children on failure.",
            "Structurally encode fault-handling policy.",
            "Ad-hoc restart logic is repeated and inconsistent across processes.",
            "Use OTP-style supervisors with restart strategies (one_for_one, one_for_all, rest_for_one).",
            "Strong fault tolerance and predictable recovery; supervision tree design takes care.",
            &[
                "actor_model",
                "concurrent_programming",
                "distributed_systems",
            ],
            &["fault_tolerance", "erlang", "otp"],
            "https://www.erlang.org/doc/design_principles/sup_princ",
        ),
        pat(
            "gen_server",
            "GenServer",
            "pattern",
            "concurrency",
            "Generic server behaviour: an actor with init/handle_call/handle_cast/handle_info callbacks.",
            "Build stateful server processes consistently and supervised.",
            "Hand-rolled receive loops duplicate idiomatic boilerplate and risk subtle bugs.",
            "Implement the `gen_server` behaviour; the OTP framework drives the receive loop and supervision.",
            "Battle-tested concurrent server; OTP-specific and assumes message-passing concurrency.",
            &["actor_model", "concurrent_programming"],
            &["erlang", "elixir", "otp", "behavior"],
            "https://www.erlang.org/doc/man/gen_server",
        ),
        pat(
            "gen_statem",
            "GenStatem (Finite State Machine Behavior)",
            "pattern",
            "concurrency",
            "OTP behaviour for stateful FSMs with explicit named states and transitions.",
            "Model protocol/state machines without hand-coded `case` cascades.",
            "Encoding state in flags and conditionals scales poorly.",
            "Implement `gen_statem`; declare state functions / state-event handlers; OTP manages transitions.",
            "Clear FSM modeling; supervision-friendly; learning curve over plain gen_server.",
            &["actor_model", "concurrent_programming"],
            &["erlang", "elixir", "otp", "state_machine"],
            "https://www.erlang.org/doc/man/gen_statem",
        ),
        pat(
            "let_it_crash",
            "Let It Crash",
            "principle",
            "concurrency",
            "Allow processes to fail fast on unexpected errors; rely on supervisors to restart them in a known-good state.",
            "Replace defensive error handling with structural recovery.",
            "Try/catch everywhere obscures intent and hides bugs that should restart the actor.",
            "Write the happy path; let supervisors monitor and restart on crashes; isolate state per process.",
            "Resilient under unknown errors; requires good supervision design and state isolation.",
            &["actor_model", "concurrent_programming"],
            &["erlang", "elixir", "fault_tolerance"],
            "https://www.cs.kent.ac.uk/people/staff/sjt/TR/ICFP07.pdf",
        ),
        pat(
            "become",
            "Become",
            "pattern",
            "concurrency",
            "An actor swaps its message-handling behavior at runtime.",
            "Encode state machines as behavior swaps rather than data flags.",
            "Branching on a state field inside one handler scales poorly.",
            "Inside the handler, call `become(NewBehavior)`; subsequent messages go to that behavior.",
            "Cleaner state transitions; observers must understand the behavior model.",
            &["actor_model", "concurrent_programming"],
            &["akka", "actor"],
            "https://doc.akka.io/docs/akka/current/typed/from-classic.html#become",
        ),
        pat(
            "selective_receive",
            "Selective Receive",
            "pattern",
            "concurrency",
            "Pattern-match on the mailbox to process only messages matching specific criteria.",
            "Coordinate request/response or out-of-order arrival without an external dispatcher.",
            "Strict FIFO processing forces actors to buffer unrelated messages explicitly.",
            "Use `receive Pat -> ... end` (or selective receive primitive) to scan the mailbox for a match.",
            "Convenient for staged protocols; large mailboxes make scanning expensive.",
            &["actor_model", "concurrent_programming"],
            &["erlang", "mailbox"],
            "https://www.erlang.org/doc/getting_started/conc_prog#receive",
        ),
        pat(
            "tell_dont_block",
            "Tell, Don't Block",
            "principle",
            "concurrency",
            "Actors send messages without waiting for replies and react when they arrive.",
            "Avoid coupling actor responsiveness to peer latency.",
            "Synchronous request/response inside actors stalls their mailboxes.",
            "Use fire-and-forget tells with correlation IDs; handle replies in a future message.",
            "Maximum throughput; protocol design must track correlations and timeouts.",
            &["actor_model"],
            &["principle", "messaging"],
            "https://doc.akka.io/docs/akka/current/general/actors.html",
        ),
        // ---------- Reactive ----------
        pat(
            "observable_stream",
            "Observable / Reactive Stream",
            "pattern",
            "reactive",
            "A push-based sequence of values over time delivered to subscribed observers.",
            "Express asynchronous and event-driven data flows compositionally.",
            "Callback APIs and event listeners don't compose cleanly.",
            "Wrap event sources as Observables; subscribers receive next/error/complete; combine with operators.",
            "Compositional async streams; backpressure and scheduling need explicit handling.",
            &[
                "reactive_programming",
                "event_driven_programming",
                "functional_programming",
            ],
            &["reactive", "rx"],
            "https://reactivex.io/documentation/observable.html",
        ),
        pat(
            "cold_observable",
            "Cold Observable",
            "pattern",
            "reactive",
            "An observable that starts producing values per subscription, replaying its sequence to each subscriber.",
            "Allow each subscriber to get the full deterministic sequence.",
            "Hot streams miss the initial values for late subscribers.",
            "Use a producer function executed inside `subscribe`; each subscription has its own producer instance.",
            "Predictable per-subscriber semantics; expensive producers run multiple times.",
            &["reactive_programming"],
            &["reactive", "rx"],
            "https://reactivex.io/documentation/observable.html#hot-and-cold",
        ),
        pat(
            "hot_observable",
            "Hot Observable",
            "pattern",
            "reactive",
            "An observable that produces values regardless of subscription; subscribers see the live stream.",
            "Share a single underlying event source across many subscribers.",
            "Mouse events, ticks, sensor data are produced once and should be multicast.",
            "Drive a Subject from the source; multiple subscribers attach to the Subject.",
            "Efficient sharing; late subscribers miss earlier events unless buffered.",
            &["reactive_programming"],
            &["reactive", "rx"],
            "https://reactivex.io/documentation/observable.html#hot-and-cold",
        ),
        pat(
            "subject",
            "Subject (Reactive)",
            "pattern",
            "reactive",
            "Both an Observable and an Observer that multicasts values to all current subscribers.",
            "Bridge imperative code into reactive streams.",
            "Adapting external producers to Observables without a multicast primitive duplicates state.",
            "Use Publish/Behavior/Replay/Async variants depending on caching needs.",
            "Easy bridging; subjects can hide intended dataflow boundaries when overused.",
            &["reactive_programming"],
            &["reactive", "rx"],
            "https://reactivex.io/documentation/subject.html",
        ),
        pat(
            "backpressure",
            "Backpressure",
            "pattern",
            "reactive",
            "Negotiate flow control so fast producers do not overwhelm slow consumers.",
            "Bound resource use in asynchronous pipelines.",
            "Unbounded buffers between producer and consumer grow until OOM.",
            "Use Reactive Streams' demand-based protocol or apply strategies (buffer/drop/latest/error).",
            "Stable memory under load; misconfigured backpressure can drop or delay critical events.",
            &["reactive_programming", "dataflow_programming"],
            &["reactive", "flow_control"],
            "https://www.reactive-streams.org/",
        ),
        pat(
            "reactive_streams_jvm",
            "Reactive Streams (JVM Specification)",
            "pattern",
            "reactive",
            "Standard interfaces (Publisher/Subscriber/Subscription/Processor) with async, non-blocking backpressure.",
            "Provide interop for reactive libraries on the JVM.",
            "Reactive libraries were incompatible; backpressure semantics varied.",
            "Implement or consume `Publisher` via libraries (Project Reactor, RxJava, Akka Streams) that respect the TCK.",
            "Cross-library interop; TCK conformance imposes strictness.",
            &["reactive_programming"],
            &["reactive", "jvm", "spec"],
            "https://www.reactive-streams.org/",
        ),
        pat(
            "scheduler",
            "Scheduler",
            "pattern",
            "reactive",
            "Decouple work execution from its source by passing a scheduler that owns when/where to run.",
            "Place work on the right thread (UI, IO pool, computation pool).",
            "Hardcoding executors couples streams to their producers' thread of origin.",
            "Accept a scheduler abstraction in pipelines; use `observeOn` / `subscribeOn` to control hops.",
            "Testable, deterministic schedulers; cross-thread hops add latency.",
            &["reactive_programming", "concurrent_programming"],
            &["reactive", "scheduling"],
            "https://reactivex.io/documentation/scheduler.html",
        ),
        pat(
            "throttle",
            "Throttle",
            "pattern",
            "reactive",
            "Emit at most one value per time interval; drop the rest.",
            "Reduce downstream load from bursty sources.",
            "Bursty event sources flood consumers and amplify resource use.",
            "Apply `throttle/sample` operators to bound the emission rate.",
            "Stable downstream load; dropped values may need a separate audit path.",
            &["reactive_programming"],
            &["reactive", "rate_limiting"],
            "https://reactivex.io/documentation/operators/sample.html",
        ),
        pat(
            "debounce",
            "Debounce",
            "pattern",
            "reactive",
            "Emit a value only after a quiet period with no new values.",
            "Collapse bursts into a single 'final' value (search-as-you-type, resize end).",
            "Each keystroke or event triggers expensive work.",
            "Apply `debounce(period)` so emissions wait until the source is silent for `period`.",
            "Cuts work on bursty input; introduces an intentional delay.",
            &["reactive_programming"],
            &["reactive", "rate_limiting"],
            "https://reactivex.io/documentation/operators/debounce.html",
        ),
        pat(
            "conflate",
            "Conflate (Latest-Wins)",
            "pattern",
            "reactive",
            "Drop intermediate values and keep only the most recent when the consumer is behind.",
            "Trade fidelity for freshness in slow consumers.",
            "Backpressure should not stall, but FIFO buffering wastes work on stale data.",
            "Use `conflate` operators that overwrite the pending value with each new emission.",
            "Always-fresh values; intermediate state is lost (unacceptable for some domains).",
            &["reactive_programming"],
            &["reactive", "backpressure"],
            "https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/conflate.html",
        ),
        // ---------- Dataflow / streaming ----------
        pat(
            "pipes_and_filters",
            "Pipes and Filters",
            "pattern",
            "dataflow",
            "Compose data transformations as a sequence of independent filters connected by pipes.",
            "Build streaming pipelines from small, reusable steps.",
            "Monolithic processing functions are hard to reuse or recombine.",
            "Define filters with a uniform input/output type; pipes carry data between them.",
            "Composable and testable; cross-filter shared state must be threaded explicitly.",
            &["dataflow_programming", "reactive_programming"],
            &["dataflow", "composition"],
            "https://en.wikipedia.org/wiki/Pipeline_(software)",
        ),
        pat(
            "tumbling_window",
            "Tumbling Window",
            "pattern",
            "dataflow",
            "Group a stream into fixed-size, non-overlapping time windows.",
            "Compute per-period aggregates over an unbounded stream.",
            "Aggregating an unbounded stream into a single value isn't actionable.",
            "Buffer by `[t, t+W)` boundaries; emit aggregate when each window closes.",
            "Simple semantics; boundary effects must be considered.",
            &["dataflow_programming", "reactive_programming"],
            &["dataflow", "windowing"],
            "https://flink.apache.org/docs/stable/concepts/timely-stream-processing.html",
        ),
        pat(
            "sliding_window",
            "Sliding Window",
            "pattern",
            "dataflow",
            "Group a stream into fixed-size windows that overlap by a fixed slide.",
            "Smooth out boundary effects of tumbling windows.",
            "Tumbling windows can miss events that span boundaries.",
            "Maintain windows of width W advancing by S; emit aggregates per window.",
            "Smoother metrics; multiplied state and emission cost (W/S).",
            &["dataflow_programming", "reactive_programming"],
            &["dataflow", "windowing"],
            "https://flink.apache.org/docs/stable/concepts/timely-stream-processing.html",
        ),
        pat(
            "session_window",
            "Session Window",
            "pattern",
            "dataflow",
            "Group events into a window whose boundary is defined by activity gaps.",
            "Capture bursts of activity per session (user, device).",
            "Fixed windows don't align with logical sessions.",
            "Keep a window open while events arrive within a gap threshold; close after timeout.",
            "Matches user behavior; per-key state can grow unbounded without GC.",
            &["dataflow_programming"],
            &["dataflow", "windowing"],
            "https://flink.apache.org/docs/stable/concepts/timely-stream-processing.html",
        ),
        pat(
            "watermark",
            "Watermark",
            "pattern",
            "dataflow",
            "Carry a timestamp that asserts no events older than this will arrive (with allowed lateness).",
            "Reason about completeness in event-time stream processing.",
            "Processing time can't tell when a window is complete in the presence of out-of-order events.",
            "Generate watermarks from sources; windows close once the watermark passes their end + allowed lateness.",
            "Enables correct event-time computation; bad watermarks under-/over-estimate progress.",
            &["dataflow_programming"],
            &["dataflow", "event_time"],
            "https://flink.apache.org/docs/stable/concepts/timely-stream-processing.html#event-time-and-watermarks",
        ),
        pat(
            "exactly_once_processing",
            "Exactly-Once Processing",
            "pattern",
            "dataflow",
            "Guarantee that each input event affects state and outputs once, despite retries and failures.",
            "Produce correct totals/outputs even after restarts.",
            "At-least-once delivery can double-count without dedup.",
            "Combine checkpointing, idempotent sinks, and dedup keys (two-phase commit or transactional outbox).",
            "Correctness under failure; throughput cost and storage overhead.",
            &["dataflow_programming", "distributed_systems"],
            &["dataflow", "delivery_semantics"],
            "https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/",
        ),
        pat(
            "at_least_once_processing",
            "At-Least-Once Processing",
            "pattern",
            "dataflow",
            "Guarantee that each event is processed one or more times, never zero.",
            "Trade duplicates for no-data-loss.",
            "Exactly-once requires expensive coordination; missing data is worse than duplicates.",
            "Ack events only after durable processing; retry on failure; rely on idempotent consumers.",
            "Simpler than exactly-once; consumers must handle duplicates explicitly.",
            &["dataflow_programming", "distributed_systems"],
            &["dataflow", "delivery_semantics"],
            "https://en.wikipedia.org/wiki/Message_passing#Message_passing_systems_and_models",
        ),
        pat(
            "at_most_once_processing",
            "At-Most-Once Processing",
            "pattern",
            "dataflow",
            "Process each event zero or one times; never duplicate.",
            "Maximize throughput when duplicates are unacceptable and loss is tolerated.",
            "Retries are forbidden but throughput must be high.",
            "Fire-and-forget delivery; no retries; consumer state isn't rolled back on failure.",
            "Highest throughput; data loss must be acceptable for the use case.",
            &["dataflow_programming", "distributed_systems"],
            &["dataflow", "delivery_semantics"],
            "https://en.wikipedia.org/wiki/Message_passing#Message_passing_systems_and_models",
        ),
        pat(
            "stateful_operator",
            "Stateful Stream Operator",
            "pattern",
            "dataflow",
            "A stream operator that retains state across events (keyed or operator-level).",
            "Compute aggregates, joins, sessions across events.",
            "Stateless operators can't compute totals, joins, or session-like behaviors.",
            "Use a keyed state backend (RocksDB, in-memory, heap) with checkpointing.",
            "Powerful streaming computations; state backend choice and checkpoint cost matter.",
            &["dataflow_programming"],
            &["dataflow", "state"],
            "https://flink.apache.org/docs/stable/concepts/stateful-stream-processing.html",
        ),
        pat(
            "stateless_operator",
            "Stateless Stream Operator",
            "pattern",
            "dataflow",
            "A stream operator that transforms each event independently with no retained state.",
            "Maximize parallelism and resilience for pure transformations.",
            "State backends and checkpointing add cost when not needed.",
            "Express transformations as pure functions over each event; let the runtime parallelize freely.",
            "Trivial to scale and recover; cannot express aggregation by itself.",
            &["dataflow_programming", "functional_programming"],
            &["dataflow", "purity"],
            "https://flink.apache.org/docs/stable/concepts/stateful-stream-processing.html",
        ),
        pat(
            "dataflow_variable",
            "Dataflow Variable",
            "pattern",
            "dataflow",
            "A single-assignment variable: readers block until it is bound, then see the value.",
            "Coordinate concurrent producers/consumers declaratively.",
            "Mutexes and condition variables for one-shot coordination are heavy.",
            "Bind once; subsequent reads succeed immediately; rebinds fail.",
            "Composable concurrency; restricts mutation by construction.",
            &["dataflow_programming", "concurrent_programming"],
            &["dataflow", "single_assignment"],
            "https://en.wikipedia.org/wiki/Single_assignment",
        ),
        // ---------- Additional concurrency primitives ----------
        pat(
            "memory_barrier",
            "Memory Barrier / Fence",
            "pattern",
            "concurrency",
            "An instruction enforcing ordering constraints on memory operations across CPUs.",
            "Get correct visibility/ordering in lock-free code.",
            "Modern CPUs and compilers reorder memory ops; lock-free correctness depends on explicit ordering.",
            "Use language atomics with explicit orderings (Acquire, Release, AcqRel, SeqCst) or compiler/CPU fence intrinsics.",
            "Correct lock-free code; the wrong ordering is silently broken.",
            &["concurrent_programming"],
            &["concurrency", "lock_free", "memory_model"],
            "https://en.wikipedia.org/wiki/Memory_barrier",
        ),
        pat(
            "cas_loop",
            "Compare-and-Swap (CAS) Loop",
            "pattern",
            "concurrency",
            "Optimistic update: read value, compute new, CAS in; retry on contention.",
            "Achieve lock-free updates with hardware atomics.",
            "Locks serialize and have contention overhead.",
            "loop { let old = atomic.load(); let new = f(old); if atomic.compare_exchange(old, new) is ok break; }; use backoff under high contention.",
            "Lock-free under low contention; ABA hazards must be considered.",
            &["concurrent_programming"],
            &["concurrency", "lock_free", "atomic"],
            "https://en.wikipedia.org/wiki/Compare-and-swap",
        ),
        pat(
            "aba_problem",
            "ABA Problem",
            "anti_pattern",
            "concurrency",
            "A CAS succeeds even though the value transitioned A → B → A while the reader was paused, hiding intervening changes.",
            "Recognize a subtle correctness hazard in lock-free CAS algorithms.",
            "CAS only compares values; identity changes are invisible.",
            "Use tagged pointers (version counters), hazard pointers, or epoch-based reclamation to detect generation changes.",
            "Safe lock-free code; extra overhead per pointer.",
            &["concurrent_programming"],
            &["concurrency", "lock_free", "antipattern"],
            "https://en.wikipedia.org/wiki/ABA_problem",
        ),
        pat(
            "ticket_lock",
            "Ticket Lock",
            "pattern",
            "concurrency",
            "Fair lock where each acquirer takes a ticket and waits until 'now serving' equals their ticket.",
            "Guarantee FIFO acquisition order.",
            "Spinlocks can starve waiters under contention.",
            "Use two counters (next_ticket, now_serving); fetch_add to acquire; spin until owned.",
            "Fair; uniform cache-line traffic causes contention (use MCS for scale).",
            &["concurrent_programming"],
            &["concurrency", "lock"],
            "https://en.wikipedia.org/wiki/Ticket_lock",
        ),
        pat(
            "mcs_lock",
            "MCS Lock",
            "pattern",
            "concurrency",
            "Queue-based fair lock where each waiter spins on its own cache line.",
            "Achieve fair, scalable locking under high contention.",
            "Centralized spinlocks/ticket locks bounce a cache line across CPUs.",
            "Each thread allocates a queue node; CAS into the tail; spin on the node's `locked` flag; unlock walks to next node.",
            "Excellent scalability; per-acquisition allocation needed (often a stack-local).",
            &["concurrent_programming"],
            &["concurrency", "lock"],
            "https://www.cs.rochester.edu/u/scott/papers/1991_TOCS_synch.pdf",
        ),
        pat(
            "spinlock",
            "Spinlock",
            "pattern",
            "concurrency",
            "Lock that busy-waits in a loop until acquired.",
            "Avoid context-switch cost for very short critical sections.",
            "Mutex+park is too heavy when critical sections are nanoseconds.",
            "Use `AtomicBool::compare_exchange` in a loop; back off with `hint::spin_loop()`; avoid in user space when preemption is possible.",
            "Lowest latency; wastes CPU and can deadlock under preemption.",
            &["concurrent_programming"],
            &["concurrency", "lock"],
            "https://en.wikipedia.org/wiki/Spinlock",
        ),
        pat(
            "adaptive_mutex",
            "Adaptive Mutex",
            "pattern",
            "concurrency",
            "Spin briefly before parking — exploits short hold times without wasting CPU on long ones.",
            "Balance spin (fast acquire) and park (CPU-friendly) semantics.",
            "Pure spin wastes CPU; pure park has high latency for short sections.",
            "Spin up to N iterations; if still held, park via futex/condvar; many production mutexes do this automatically.",
            "Good real-world performance; tuning N depends on workload.",
            &["concurrent_programming"],
            &["concurrency", "lock"],
            "https://en.wikipedia.org/wiki/Spinlock#Adaptive_spinning",
        ),
        pat(
            "try_lock",
            "Try-Lock",
            "pattern",
            "concurrency",
            "Attempt to acquire a lock immediately; return failure rather than block.",
            "Avoid blocking when alternative actions are available.",
            "Plain `lock()` blocks indefinitely and can deadlock.",
            "Call `try_lock()`; on failure, do work elsewhere, retry later, or fall back.",
            "Non-blocking; caller must handle failure path.",
            &["concurrent_programming"],
            &["concurrency", "lock"],
            "https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.try_lock",
        ),
        pat(
            "sequence_lock",
            "Sequence Lock (seqlock)",
            "pattern",
            "concurrency",
            "Writers increment a sequence; readers check that the sequence is even before and after the read.",
            "Cheap reads on rarely-updated data with strong consistency.",
            "Rwlocks have reader overhead; readers spinning on writers stall.",
            "Reader: read seq; read data; read seq again; retry if seq changed or odd. Writer: increment to odd; write; increment to even.",
            "Very fast reads; writes are blocking; readers can spin in pathological cases.",
            &["concurrent_programming"],
            &["concurrency", "lock_free"],
            "https://en.wikipedia.org/wiki/Seqlock",
        ),
        pat(
            "reentrant_lock",
            "Reentrant Lock",
            "pattern",
            "concurrency",
            "Lock that can be acquired multiple times by the same thread without deadlocking itself.",
            "Allow recursive method calls that all need the same lock.",
            "Non-reentrant locks deadlock when a method holding the lock calls another method that tries to acquire it.",
            "Track owner thread and recursion count; on release, decrement count; only release when count reaches 0.",
            "Convenient; may mask design problems that need refactoring.",
            &["concurrent_programming"],
            &["concurrency", "lock"],
            "https://en.wikipedia.org/wiki/Reentrant_mutex",
        ),
        pat(
            "wait_free",
            "Wait-Free Algorithm",
            "principle",
            "concurrency",
            "Every thread completes its operation in a bounded number of steps, regardless of contention.",
            "Provide the strongest progress guarantee under any scheduling.",
            "Lock-free allows some threads to starve; wait-free does not.",
            "Use universal constructions or specialized algorithms (wait-free queues like CRQ); typically more complex than lock-free.",
            "Strongest progress; usually slower under low contention.",
            &["concurrent_programming"],
            &["concurrency", "lock_free"],
            "https://en.wikipedia.org/wiki/Non-blocking_algorithm",
        ),
        pat(
            "lock_convoy",
            "Lock Convoy",
            "anti_pattern",
            "concurrency",
            "Many threads queue on a single lock and stay synchronized as a 'convoy', killing throughput.",
            "Recognize cascading contention through a hot lock.",
            "All threads converge on the same lock and acquire it round-robin.",
            "Reduce critical-section size; shard the lock (per-key, per-shard); use lock-free structures; back off non-uniformly.",
            "Better scalability; redesign cost.",
            &["concurrent_programming"],
            &["concurrency", "antipattern"],
            "https://en.wikipedia.org/wiki/Lock_convoy",
        ),
        pat(
            "priority_inversion",
            "Priority Inversion",
            "anti_pattern",
            "concurrency",
            "A high-priority thread waits on a lock held by a low-priority thread that's been preempted by medium-priority threads.",
            "Recognize starvation of important work behind low-priority lock holders.",
            "Mixed-priority threads share locks without priority-aware scheduling.",
            "Use priority inheritance (POSIX `PTHREAD_PRIO_INHERIT`), priority ceilings, or avoid mixing priorities through shared resources.",
            "Solved by OS support; design audit needed in mixed-priority systems.",
            &["concurrent_programming"],
            &["concurrency", "antipattern", "scheduling"],
            "https://en.wikipedia.org/wiki/Priority_inversion",
        ),
        pat(
            "optimistic_concurrency_control",
            "Optimistic Concurrency Control",
            "principle",
            "concurrency",
            "Assume conflicts are rare; validate at commit; retry on conflict.",
            "Avoid lock overhead when contention is low.",
            "Pessimistic locking is wasteful when conflicts seldom occur.",
            "Read version/timestamp; compute new value; commit only if version unchanged; retry otherwise.",
            "Great under low contention; livelocks possible under high contention.",
            &["concurrent_programming"],
            &["concurrency", "transactions"],
            "https://en.wikipedia.org/wiki/Optimistic_concurrency_control",
        ),
        pat(
            "pessimistic_concurrency_control",
            "Pessimistic Concurrency Control",
            "principle",
            "concurrency",
            "Acquire locks up front to prevent conflicts.",
            "Provide strict serializability under high contention.",
            "Optimistic conflicts cause expensive retries when contention is high.",
            "Use row/page/predicate locks; honor lock ordering to prevent deadlocks; detect with timeouts.",
            "Predictable under contention; reduced concurrency.",
            &["concurrent_programming"],
            &["concurrency", "transactions"],
            "https://en.wikipedia.org/wiki/Lock_(computer_science)",
        ),
    ]
}
