//! Data engineering, warehousing, and analytics patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- Warehouse schemas ----------
        pat(
            "star_schema",
            "Star Schema",
            "pattern",
            "data_engineering",
            "Central fact table joined to denormalized dimension tables forming a star shape.",
            "Optimize analytical queries with simple joins and predictable performance.",
            "Normalized OLTP schemas yield slow, complex analytical queries.",
            "Design one fact table per business process; denormalize dimensions; pre-compute keys.",
            "Fast aggregations and BI-friendly; dimensions duplicate data.",
            &["dataflow_programming", "distributed_systems"],
            &["data_warehouse", "olap"],
            "https://en.wikipedia.org/wiki/Star_schema",
        ),
        pat(
            "snowflake_schema",
            "Snowflake Schema",
            "pattern",
            "data_engineering",
            "Star schema variant where dimensions are normalized into multiple related tables.",
            "Reduce dimension-table redundancy at the cost of more joins.",
            "Star-schema dimensions duplicate hierarchical data.",
            "Normalize dimensions into 3NF (e.g., separate brand/category from product).",
            "Less storage; more joins; some BI tools handle worse than star.",
            &["dataflow_programming", "distributed_systems"],
            &["data_warehouse", "olap"],
            "https://en.wikipedia.org/wiki/Snowflake_schema",
        ),
        pat(
            "data_vault",
            "Data Vault",
            "pattern",
            "data_engineering",
            "Modeling pattern with Hubs (business keys), Links (relationships), and Satellites (descriptive attributes with history).",
            "Build an auditable, agile warehouse that absorbs schema change without rework.",
            "Star schemas require redesign when source systems change.",
            "Model business keys as Hubs; relationships as Links; descriptive change-tracked attributes as Satellites; layer marts on top.",
            "Highly adaptable and auditable; more tables and ETL complexity than star.",
            &["dataflow_programming", "distributed_systems"],
            &["data_warehouse"],
            "https://en.wikipedia.org/wiki/Data_vault_modeling",
        ),
        // ---------- Slowly changing dimensions ----------
        pat(
            "scd_type_1",
            "Slowly Changing Dimension (SCD) Type 1",
            "pattern",
            "data_engineering",
            "Overwrite the dimension row when an attribute changes; no history kept.",
            "Always reflect current state in dimensions.",
            "History is unnecessary for some dimensions (typo fixes, renames).",
            "On change, UPDATE the row in place; downstream sees only current value.",
            "Simplest, smallest storage; loses historical analysis ability.",
            &["dataflow_programming"],
            &["data_warehouse", "scd"],
            "https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/dimensional-modeling-techniques/type-1/",
        ),
        pat(
            "scd_type_2",
            "Slowly Changing Dimension (SCD) Type 2",
            "pattern",
            "data_engineering",
            "Insert a new dimension row on change with effective/expiry dates or current-flag; keep all history.",
            "Preserve history so facts can join the dimension version that was current when they occurred.",
            "Type 1 overwrites lose the version of truth in effect at fact time.",
            "Add valid_from / valid_to / is_current; insert new row on change; mark previous as expired; facts reference surrogate key.",
            "Full history; storage grows; consumer SQL must filter by date or current flag.",
            &["dataflow_programming"],
            &["data_warehouse", "scd"],
            "https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/dimensional-modeling-techniques/type-2/",
        ),
        pat(
            "scd_type_3",
            "Slowly Changing Dimension (SCD) Type 3",
            "pattern",
            "data_engineering",
            "Add columns for previous attribute values (e.g., previous_region, current_region).",
            "Keep limited history of specific attributes without row explosion.",
            "Type 2 row explosion is overkill when only one or two attributes need history.",
            "Add prev/current columns for selected attributes; update on change.",
            "Compact; only N levels of history per attribute.",
            &["dataflow_programming"],
            &["data_warehouse", "scd"],
            "https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/dimensional-modeling-techniques/type-3/",
        ),
        pat(
            "scd_type_6",
            "Slowly Changing Dimension (SCD) Type 6 (Hybrid)",
            "pattern",
            "data_engineering",
            "Combine Type 1 + 2 + 3: keep history rows (Type 2), update current pointer (Type 1), and a current column (Type 3).",
            "Support both 'as of date' and 'always current' queries cheaply.",
            "Type 2 forces a date filter for current-only reports.",
            "Each row has surrogate id + business key + current flag + current_attribute_now (Type 1) + historical attribute (Type 2).",
            "Flexible queries; ETL is more complex.",
            &["dataflow_programming"],
            &["data_warehouse", "scd"],
            "https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/dimensional-modeling-techniques/type-6/",
        ),
        // ---------- Architectures ----------
        pat(
            "data_lake",
            "Data Lake",
            "pattern",
            "data_engineering",
            "Centralized repository of raw structured/semi-structured/unstructured data at native fidelity.",
            "Defer schema-on-write so any future analysis can use the original data.",
            "Warehouses force schema decisions before analytics needs are clear.",
            "Land raw data in object storage (S3/GCS/ADLS) partitioned by date; use schema-on-read engines (Athena, Trino).",
            "Flexibility; risk of becoming a 'data swamp' without governance.",
            &["dataflow_programming", "distributed_systems"],
            &["data_lake", "olap"],
            "https://en.wikipedia.org/wiki/Data_lake",
        ),
        pat(
            "data_lakehouse",
            "Data Lakehouse",
            "pattern",
            "data_engineering",
            "Combine lake's open storage with warehouse-style ACID tables and schema enforcement (Delta Lake, Iceberg, Hudi).",
            "Get warehouse semantics on top of lake economics.",
            "Lakes lack transactions; warehouses lack flexibility.",
            "Adopt an open table format (Delta/Iceberg/Hudi) on top of object storage; gain ACID, time travel, schema evolution.",
            "Best of both; format choice and migration effort matter.",
            &["dataflow_programming", "distributed_systems"],
            &["data_lake", "data_warehouse"],
            "https://www.databricks.com/glossary/data-lakehouse",
        ),
        pat(
            "data_mesh",
            "Data Mesh",
            "principle",
            "data_engineering",
            "Domain-oriented decentralized data ownership: each business domain owns its analytical data as a product.",
            "Scale analytics beyond a central data team's capacity.",
            "Central data teams become bottlenecks as the org grows.",
            "Define data domains; treat data as product with owners, SLAs, schemas; enforce platform standards.",
            "Org scaling; governance and platform team is essential.",
            &["dataflow_programming", "distributed_systems"],
            &["data_mesh", "data_governance"],
            "https://martinfowler.com/articles/data-mesh-principles.html",
        ),
        pat(
            "lambda_architecture",
            "Lambda Architecture",
            "pattern",
            "data_engineering",
            "Run batch and speed (streaming) layers in parallel; serving layer merges their views.",
            "Achieve both correctness (batch) and freshness (stream).",
            "Pure batch is stale; pure streaming is hard to reprocess.",
            "Implement batch view (e.g., Spark) + speed view (Flink/Kafka Streams); serving layer reconciles by key.",
            "Reliable + fresh; two code paths to maintain.",
            &["dataflow_programming", "distributed_systems"],
            &["streaming", "batch"],
            "https://en.wikipedia.org/wiki/Lambda_architecture",
        ),
        pat(
            "kappa_architecture",
            "Kappa Architecture",
            "pattern",
            "data_engineering",
            "Single streaming pipeline handles both real-time and reprocessing; replay the log for backfill.",
            "Simplify Lambda by eliminating the batch path.",
            "Lambda's duplicate logic in batch and stream is expensive.",
            "Persist the source as an immutable log (Kafka); stream-process forward; replay from log to backfill.",
            "One code path; log retention and stream-state recovery design needed.",
            &["dataflow_programming", "distributed_systems"],
            &["streaming"],
            "https://www.oreilly.com/radar/questioning-the-lambda-architecture/",
        ),
        pat(
            "medallion_architecture",
            "Medallion Architecture (Bronze/Silver/Gold)",
            "pattern",
            "data_engineering",
            "Layer data lake tables: Bronze=raw, Silver=cleansed/conformed, Gold=aggregated/business.",
            "Provide quality and lineage at clear levels.",
            "Ad-hoc table proliferation in lakes obscures lineage and quality.",
            "Land in Bronze; cleanse to Silver; serve marts from Gold; enforce schemas at boundaries.",
            "Clear data quality contract; ETL discipline required across teams.",
            &["dataflow_programming", "distributed_systems"],
            &["data_lake", "lakehouse"],
            "https://www.databricks.com/glossary/medallion-architecture",
        ),
        // ---------- ETL / ELT / CDC ----------
        pat(
            "etl",
            "ETL (Extract-Transform-Load)",
            "pattern",
            "data_engineering",
            "Extract data from sources, transform externally, then load into warehouse.",
            "Move data with consistent transformations before storage.",
            "Loading raw data first wastes warehouse compute on transforms.",
            "Run transforms in an ETL tool (Talend, Airflow + Python); load shaped data.",
            "Predictable warehouse load; transform engine becomes a separate system.",
            &["dataflow_programming"],
            &["data_engineering", "etl"],
            "https://en.wikipedia.org/wiki/Extract,_transform,_load",
        ),
        pat(
            "elt",
            "ELT (Extract-Load-Transform)",
            "pattern",
            "data_engineering",
            "Extract and load raw into the warehouse, transform with SQL inside it (dbt-style).",
            "Leverage modern warehouse compute for transformations.",
            "ETL servers are slower and harder to scale than modern warehouses.",
            "Land raw in staging schemas; use SQL transforms (dbt models) inside the warehouse.",
            "Scales with the warehouse; tools standardize on SQL; transform versioning needs effort.",
            &["dataflow_programming"],
            &["data_engineering", "elt"],
            "https://www.getdbt.com/blog/elt-vs-etl/",
        ),
        pat(
            "change_data_capture",
            "Change Data Capture (CDC)",
            "pattern",
            "data_engineering",
            "Capture row-level changes from a database's log and emit them as events.",
            "Build event streams from existing OLTP databases without dual-writes.",
            "Application-level dual writes drift; periodic snapshots are stale.",
            "Use Debezium / native logical replication (Postgres, MySQL); emit events to Kafka; downstream consumes.",
            "Real-time replication; schema evolution and offset management require care.",
            &["dataflow_programming", "distributed_systems"],
            &["cdc", "etl"],
            "https://debezium.io/documentation/reference/stable/architecture.html",
        ),
        pat(
            "idempotent_upsert",
            "Idempotent Upsert",
            "pattern",
            "data_engineering",
            "Load operations are designed so re-running them produces the same target state.",
            "Make re-runs safe for partial failures and replays.",
            "INSERT-only loaders break on retries with duplicates; UPDATE-only miss new rows.",
            "Use MERGE / INSERT...ON CONFLICT DO UPDATE keyed by natural key + watermark.",
            "Safe retries and replays; requires a stable key.",
            &["dataflow_programming"],
            &["etl", "idempotency"],
            "https://www.postgresql.org/docs/current/sql-insert.html",
        ),
        pat(
            "watermark_elt",
            "Watermark in ELT",
            "pattern",
            "data_engineering",
            "Track a per-table watermark (max(updated_at)) to extract only new/changed rows.",
            "Incremental extraction without scanning the whole source.",
            "Full-table scans are infeasible at scale.",
            "Persist last watermark per source; WHERE updated_at > watermark on each run; bump after success.",
            "Cheap incremental loads; clock skew or in-place updates can miss rows — pair with safety windows.",
            &["dataflow_programming"],
            &["etl"],
            "https://airbyte.com/blog/incremental-data-syncing",
        ),
        // ---------- Tree models ----------
        pat(
            "adjacency_list_tree",
            "Adjacency List (Hierarchy)",
            "pattern",
            "data_engineering",
            "Each row stores parent_id; recursion required to traverse the tree.",
            "Simplest hierarchical storage.",
            "Most databases lack a native tree type.",
            "Add `parent_id` column referencing the same table; query via recursive CTE.",
            "Easy writes; reads of full subtrees need recursion.",
            &["dataflow_programming"],
            &["sql", "tree"],
            "https://www.slideshare.net/billkarwin/sql-antipatterns-strike-back",
        ),
        pat(
            "materialized_path_tree",
            "Materialized Path (Hierarchy)",
            "pattern",
            "data_engineering",
            "Store the path from root as a string (e.g., `1/4/7`).",
            "Fast subtree queries with LIKE prefix.",
            "Adjacency lists need recursion for subtree queries.",
            "Add a `path` text column; subtree query = `WHERE path LIKE 'prefix/%'`.",
            "Fast subtree reads; moves require path rewrites.",
            &["dataflow_programming"],
            &["sql", "tree"],
            "https://www.depesz.com/2008/04/11/my-take-on-trees-in-sql/",
        ),
        pat(
            "nested_set_tree",
            "Nested Set Model (Hierarchy)",
            "pattern",
            "data_engineering",
            "Each node has `lft`/`rgt` bounds; subtree = nodes within bounds.",
            "Constant-time subtree queries.",
            "Materialized path queries grow with prefix length.",
            "Maintain lft/rgt via tree-traversal updates; subtree = `WHERE lft BETWEEN parent.lft AND parent.rgt`.",
            "Very fast reads; writes can update many rows.",
            &["dataflow_programming"],
            &["sql", "tree"],
            "https://en.wikipedia.org/wiki/Nested_set_model",
        ),
        pat(
            "closure_table",
            "Closure Table (Hierarchy)",
            "pattern",
            "data_engineering",
            "Separate table storing every ancestor-descendant pair plus depth.",
            "Efficient queries in both directions at the cost of write amplification.",
            "Other tree models force a tradeoff between read and write cost.",
            "Maintain `(ancestor, descendant, depth)` rows; queries become simple joins.",
            "Symmetric read performance; writes update O(depth) rows.",
            &["dataflow_programming"],
            &["sql", "tree"],
            "https://www.slideshare.net/billkarwin/sql-antipatterns-strike-back",
        ),
        pat(
            "soft_delete",
            "Soft Delete",
            "pattern",
            "data_engineering",
            "Mark rows as deleted with a flag/timestamp instead of removing them.",
            "Preserve history and allow recovery without an audit table.",
            "Hard deletes lose context and complicate audits.",
            "Add `deleted_at` nullable timestamp; partial indexes / WHERE clauses exclude deleted; periodic GC purges.",
            "Easy recovery; queries must filter; unique constraints must include the flag.",
            &["dataflow_programming"],
            &["sql", "audit"],
            "https://abibis.medium.com/soft-delete-in-postgres-and-elsewhere-3a02d04dcdee",
        ),
        pat(
            "append_only_log",
            "Append-Only Log",
            "pattern",
            "data_engineering",
            "Persist immutable records in order; never update or delete.",
            "Provide an authoritative history that can be replayed.",
            "Mutable state loses 'how we got here' information.",
            "Use Kafka, EventStore, or a transactional events table; consumers materialize state by folding events.",
            "Auditable, replayable; storage grows; readers must handle ordering.",
            &["dataflow_programming", "event_driven_programming"],
            &["log", "event_sourcing"],
            "https://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying",
        ),
        pat(
            "oltp_vs_olap",
            "OLTP vs OLAP Separation",
            "principle",
            "data_engineering",
            "Use one database tuned for transactions (OLTP) and a separate analytical store (OLAP); replicate one to the other.",
            "Avoid analytical queries crushing transactional performance.",
            "Running ad-hoc analytics on OLTP starves user-facing queries.",
            "Replicate OLTP → OLAP via CDC or scheduled ETL; route reports/dashboards to OLAP only.",
            "Healthy production performance; replication lag is a new concern.",
            &["dataflow_programming", "distributed_systems"],
            &["olap", "oltp", "architecture"],
            "https://en.wikipedia.org/wiki/Online_analytical_processing",
        ),
    ]
}
