//! Declarative programming patterns: SQL, IaC, GitOps, grammars, declarative UI, query languages.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        pat(
            "declarative_ui",
            "Declarative UI",
            "pattern",
            "ui",
            "Describe the UI as a pure function of state; the framework reconciles changes to the screen.",
            "Eliminate imperative DOM/widget mutation and the bugs it produces.",
            "Manually mutating UI components in response to events causes inconsistent state.",
            "Render a description of the UI; the framework diffs and applies changes (React, SwiftUI, Compose, Flutter).",
            "Predictable UI with simple mental model; reconciliation cost and abstraction leaks.",
            &["declarative_programming", "reactive_programming"],
            &["ui", "declarative"],
            "https://en.wikipedia.org/wiki/Declarative_programming",
        ),
        pat(
            "configuration_as_code",
            "Configuration as Code",
            "pattern",
            "declarative",
            "Store configuration in version-controlled code rather than ad-hoc files or UIs.",
            "Make configuration reviewable, reproducible, and auditable.",
            "Hand-edited config drifts across environments and is hard to roll back.",
            "Express config in a typed format (HCL, YAML, TS, Cue); apply via tooling; track in Git.",
            "Reviewable infrastructure; tooling and DSL learning curve.",
            &["declarative_programming"],
            &["config", "devops"],
            "https://martinfowler.com/bliki/ConfigurationAsCode.html",
        ),
        pat(
            "infrastructure_as_code",
            "Infrastructure as Code (IaC)",
            "pattern",
            "declarative",
            "Provision and manage infrastructure with declarative code (Terraform, CloudFormation, Pulumi, Bicep).",
            "Make environments reproducible and version-controlled.",
            "Click-ops infrastructure drifts, lacks audit trail, and can't be recreated quickly.",
            "Describe desired state in IaC; let the engine compute and apply changes; review diffs in PRs.",
            "Reproducible infra; the IaC state file is now a critical artifact to manage.",
            &["declarative_programming", "distributed_systems"],
            &["devops", "cloud"],
            "https://en.wikipedia.org/wiki/Infrastructure_as_code",
        ),
        pat(
            "gitops",
            "GitOps",
            "pattern",
            "declarative",
            "A Git repository is the single source of truth for desired system state; agents reconcile reality to it.",
            "Make deployments reproducible, auditable, and revertible via Git history.",
            "Ad-hoc deploys produce inconsistent environments with no audit trail.",
            "Store manifests in Git; run reconcilers (Flux/ArgoCD) that pull and apply; merge = deploy.",
            "Powerful audit and rollback; reconcilers and secret handling need care.",
            &["declarative_programming", "distributed_systems"],
            &["devops", "kubernetes"],
            "https://opengitops.dev/",
        ),
        // ---------- SQL ----------
        pat(
            "common_table_expression",
            "Common Table Expression (CTE)",
            "pattern",
            "sql",
            "Name a query block once and reference it within a single statement (optionally recursive).",
            "Decompose complex queries into readable, named building blocks.",
            "Nested subqueries become unreadable and hard to debug.",
            "Use `WITH name AS (SELECT ...) ...`; recursive CTEs handle hierarchies/graphs.",
            "Clear readable queries; planner may materialize CTEs (Postgres ≤ 11 always did) and miss optimizations.",
            &["declarative_programming"],
            &["sql"],
            "https://en.wikipedia.org/wiki/Hierarchical_and_recursive_queries_in_SQL",
        ),
        pat(
            "window_function",
            "SQL Window Function",
            "pattern",
            "sql",
            "Aggregate or rank rows in a window without collapsing them.",
            "Compute running totals, ranks, leads/lags without losing row detail.",
            "Self-joins and correlated subqueries express analytics awkwardly.",
            "Use `OVER (PARTITION BY ... ORDER BY ...)` with ROW_NUMBER, RANK, SUM, LAG, etc.",
            "Concise analytics; window semantics have a learning curve.",
            &["declarative_programming"],
            &["sql"],
            "https://en.wikipedia.org/wiki/Window_function_(SQL)",
        ),
        pat(
            "sql_view",
            "SQL View",
            "pattern",
            "sql",
            "Define a named virtual table backed by a query.",
            "Encapsulate complex queries as reusable abstractions.",
            "Clients duplicate complex joins and where-clauses.",
            "`CREATE VIEW name AS SELECT ...`; clients query the view as if it were a table.",
            "Reusable query abstractions; views may hide query cost and complicate planning.",
            &["declarative_programming"],
            &["sql"],
            "https://en.wikipedia.org/wiki/View_(SQL)",
        ),
        pat(
            "sql_trigger",
            "SQL Trigger",
            "pattern",
            "sql",
            "Run procedural code automatically in response to data modifications.",
            "Enforce invariants or propagate changes inside the database.",
            "Application-side maintenance of derived data is missed under direct DB writes.",
            "Define a trigger on a table for INSERT/UPDATE/DELETE; run the body atomically with the change.",
            "Strong invariants; triggers are invisible to readers of application code and can hurt performance.",
            &["declarative_programming"],
            &["sql"],
            "https://en.wikipedia.org/wiki/Database_trigger",
        ),
        pat(
            "sql_check_constraint",
            "SQL CHECK Constraint",
            "pattern",
            "sql",
            "Express row-level invariants declaratively in the schema.",
            "Reject invalid rows at the database boundary, regardless of client.",
            "Application validation is bypassed by direct SQL, ETL, or future clients.",
            "Define `CHECK (...)` on columns/tables to enforce invariants on every write.",
            "Defense in depth; some constraint forms can hurt write performance or planner choices.",
            &["declarative_programming"],
            &["sql", "invariants"],
            "https://en.wikipedia.org/wiki/Check_constraint",
        ),
        pat(
            "graphql_schema_first",
            "GraphQL Schema-First Design",
            "pattern",
            "declarative",
            "Define the API contract as a GraphQL schema before writing resolvers.",
            "Make the API a stable, typed contract negotiated between consumers and providers.",
            "Code-first APIs evolve in ways that break clients silently.",
            "Author the schema as the source of truth; generate types and stubs for client and server.",
            "Strong typing and tooling; schema governance is essential as it grows.",
            &["declarative_programming"],
            &["api", "graphql"],
            "https://graphql.org/learn/best-practices/",
        ),
        pat(
            "datalog_query",
            "Datalog Query",
            "pattern",
            "declarative",
            "Express queries as facts and rules in a decidable subset of logic programming.",
            "Solve recursive relational queries with strong termination guarantees.",
            "Recursive SQL CTEs become hard to express and reason about.",
            "Define facts and rules; queries return all derivable answers; engines apply bottom-up evaluation.",
            "Strong analytics on graphs/policies; ecosystem narrower than SQL.",
            &["declarative_programming", "logic_programming"],
            &["query", "datalog"],
            "https://en.wikipedia.org/wiki/Datalog",
        ),
        pat(
            "sparql_query",
            "SPARQL",
            "pattern",
            "declarative",
            "Query RDF graphs declaratively with pattern matching over triples.",
            "Run federated semantic-web queries.",
            "Imperative graph traversal mixes domain logic with iteration mechanics.",
            "Use SELECT/WHERE clauses of triple patterns; bind variables; OPTIONAL/FILTER refine results.",
            "Powerful semantic queries; performance depends on the graph engine.",
            &["declarative_programming"],
            &["query", "rdf", "semantic_web"],
            "https://en.wikipedia.org/wiki/SPARQL",
        ),
        pat(
            "make_rule",
            "Make Rule (Declarative Build)",
            "pattern",
            "declarative",
            "Describe targets, prerequisites, and recipes; the tool figures out the build order.",
            "Build only what changed by reasoning over file dependencies.",
            "Imperative build scripts redo work and miss dependencies.",
            "Declare `target: prereqs` rules with recipes; tools (make/Bazel/ninja) compute the DAG and execute changes.",
            "Incremental, parallel builds; rule completeness must be enforced (missing deps cause stale builds).",
            &["declarative_programming", "dataflow_programming"],
            &["build", "make"],
            "https://en.wikipedia.org/wiki/Make_(software)",
        ),
        pat(
            "ansible_playbook",
            "Ansible Playbook",
            "pattern",
            "declarative",
            "Describe desired system state in YAML with idempotent tasks; agentless SSH execution.",
            "Configure servers reproducibly without bespoke scripts.",
            "Shell scripts aren't idempotent and don't model desired state.",
            "Write playbooks of plays/tasks/roles; Ansible applies them to inventory hosts in order.",
            "Reproducible config; pure SSH model can lag against changes on long-lived hosts.",
            &["declarative_programming"],
            &["devops", "config_management"],
            "https://docs.ansible.com/ansible/latest/playbook_guide/index.html",
        ),
        pat(
            "helm_chart",
            "Helm Chart (Templated Manifests)",
            "pattern",
            "declarative",
            "Package Kubernetes manifests as parameterized templates with values.",
            "Reuse manifests across environments via templating + values overrides.",
            "Bare manifests duplicate large blocks across envs.",
            "Author templates with Go/Sprig functions; ship a chart with default values; override per release.",
            "Reusable packages; template logic can become hard to read; argument validation is weak.",
            &["declarative_programming"],
            &["devops", "kubernetes"],
            "https://helm.sh/docs/",
        ),
        pat(
            "css_cascade",
            "CSS Cascade",
            "pattern",
            "ui",
            "Style rules apply by source order, specificity, and importance; declarative styling overrides accumulate.",
            "Compose styles by declaration rather than imperative DOM manipulation.",
            "Inline imperative style changes scatter presentation logic across code.",
            "Author rules; rely on cascade and specificity to resolve conflicts.",
            "Declarative composition; specificity wars and inheritance surprises are common.",
            &["declarative_programming"],
            &["css", "ui"],
            "https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade",
        ),
        pat(
            "xslt_template",
            "XSLT Template",
            "pattern",
            "declarative",
            "Transform XML by declarative templates that match nodes and emit output.",
            "Express XML-to-X transformations without writing imperative parsers.",
            "Hand-coded XML manipulation duplicates traversal logic for every change.",
            "Write `xsl:template match=` rules; the processor applies them according to the input tree.",
            "Powerful for XML pipelines; XSLT syntax has a learning curve; less common today.",
            &["declarative_programming"],
            &["xml", "transformation"],
            "https://en.wikipedia.org/wiki/XSLT",
        ),
        pat(
            "peg_parser",
            "Parsing Expression Grammar (PEG)",
            "pattern",
            "declarative",
            "Describe a grammar with ordered choice and unlimited lookahead; parse deterministically.",
            "Get clean, executable specifications for unambiguous grammars.",
            "Ambiguous CFGs (LALR) make grammars hard to reason about.",
            "Express productions with `<-`, choice with `/`, predicates with `&`/`!`; generate or interpret directly.",
            "Deterministic, easy to compose; left recursion needs special handling (packrat with memoization).",
            &["declarative_programming"],
            &["parsing", "grammar"],
            "https://en.wikipedia.org/wiki/Parsing_expression_grammar",
        ),
        pat(
            "bnf_grammar",
            "BNF / EBNF Grammar",
            "pattern",
            "declarative",
            "Describe formal language syntax with productions; tools generate parsers.",
            "Make language syntax a precise, executable specification.",
            "Ad-hoc parsers duplicate state machines and obscure the grammar.",
            "Write a BNF/EBNF grammar; use a parser generator (yacc/bison/ANTLR/lalrpop) to produce a parser.",
            "Precise specs and parsers; ambiguity and conflict resolution add complexity.",
            &["declarative_programming"],
            &["parsing", "grammar"],
            "https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form",
        ),
        pat(
            "regular_expression",
            "Regular Expression",
            "pattern",
            "declarative",
            "Specify pattern matching over strings declaratively.",
            "Match, search, or extract from text with concise patterns.",
            "Hand-coded char-by-char scanning is verbose and error-prone.",
            "Use a regex engine (PCRE/RE2/POSIX) with the right dialect; consider performance/backtracking risks.",
            "Concise and powerful; catastrophic backtracking and readability hazards.",
            &["declarative_programming"],
            &["text", "matching"],
            "https://en.wikipedia.org/wiki/Regular_expression",
        ),
        pat(
            "rule_engine",
            "Rule Engine",
            "pattern",
            "declarative",
            "Externalize business rules as data interpreted by an engine (e.g., RETE).",
            "Let non-developers update policy without redeploying code.",
            "Hardcoded if/else logic is difficult for domain experts to evolve.",
            "Author rules in DRL/DMN; engine matches facts to rules and fires actions.",
            "Powerful for fast-changing policy; engine debugging and performance can surprise.",
            &["declarative_programming"],
            &["rules", "drools"],
            "https://en.wikipedia.org/wiki/Business_rules_engine",
        ),
        pat(
            "feature_flag",
            "Feature Flag",
            "pattern",
            "declarative",
            "Gate code paths behind named, externally-toggled flags.",
            "Decouple deployment from release; enable canaries and kill-switches.",
            "Big-bang releases of risky code are scary and hard to roll back.",
            "Read flag values from a service or config; branch on them; expose flag state to ops.",
            "Safer deploys; flag debt accumulates if old flags aren't cleaned up.",
            &["declarative_programming"],
            &["release", "operations"],
            "https://martinfowler.com/articles/feature-toggles.html",
        ),
        pat(
            "policy_as_code",
            "Policy as Code",
            "pattern",
            "declarative",
            "Express organizational policy (access, deployment, compliance) as code evaluated by an engine.",
            "Make policy decisions consistent, auditable, and testable.",
            "Policy lives in documents that drift from how systems actually behave.",
            "Author policy in Rego/OPA, Cedar, or similar; integrate via admission controllers or middleware.",
            "Testable policy; policy authoring becomes a development workflow.",
            &["declarative_programming"],
            &["policy", "security"],
            "https://www.openpolicyagent.org/",
        ),
        pat(
            "build_target_dag",
            "Build Target DAG",
            "pattern",
            "declarative",
            "Express builds as a directed acyclic graph of targets with declared inputs and outputs.",
            "Enable hermetic, incremental, parallel builds at scale.",
            "Ad-hoc scripts rebuild too much (or too little) and aren't reliably parallel.",
            "Use Bazel/Buck/Pants with strictly-declared inputs/outputs; the engine schedules and caches.",
            "Fast, correct builds at scale; ramp-up cost and BUILD-file ceremony.",
            &["declarative_programming", "dataflow_programming"],
            &["build", "bazel"],
            "https://bazel.build/",
        ),
    ]
}
