//! Deployment and release-management patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        pat(
            "blue_green_deployment",
            "Blue-Green Deployment",
            "pattern",
            "deployment",
            "Maintain two identical environments; route traffic to one (blue) while deploying to the other (green); switch on success.",
            "Achieve near-zero-downtime cutover with instant rollback.",
            "In-place upgrades cause downtime and risky rollbacks.",
            "Deploy to the idle environment; run smoke tests; switch router atomically; keep the previous env warm for rollback.",
            "Fast rollback; doubles infrastructure cost during deploy.",
            &["distributed_systems"],
            &["deployment", "release"],
            "https://martinfowler.com/bliki/BlueGreenDeployment.html",
        ),
        pat(
            "canary_release",
            "Canary Release",
            "pattern",
            "deployment",
            "Route a small fraction of traffic to the new version; ramp up if metrics stay green.",
            "Limit blast radius of a bad release while validating in production.",
            "All-or-nothing releases ship bugs to all users at once.",
            "Use a traffic-splitting LB or service mesh; progressively shift 1% → 10% → 50% → 100% based on SLO metrics.",
            "Bounded blast radius; requires good observability + automation.",
            &["distributed_systems"],
            &["deployment", "release"],
            "https://martinfowler.com/bliki/CanaryRelease.html",
        ),
        pat(
            "rolling_update",
            "Rolling Update",
            "pattern",
            "deployment",
            "Replace instances one at a time (or N at a time) until the fleet is on the new version.",
            "Continuously deploy without losing capacity.",
            "Recreate strategy causes downtime; blue-green doubles cost.",
            "Configure rolling strategy in the orchestrator (Kubernetes Deployment, ECS, Nomad); cap maxSurge / maxUnavailable.",
            "Smooth upgrades; mid-rollout the fleet runs mixed versions.",
            &["distributed_systems"],
            &["deployment", "kubernetes"],
            "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment",
        ),
        pat(
            "shadow_deployment",
            "Shadow Deployment",
            "pattern",
            "deployment",
            "Send a copy of production traffic to the new version without returning its response to users.",
            "Validate behavior under realistic load before any user impact.",
            "Synthetic load testing misses real traffic patterns and edge cases.",
            "Mirror traffic via proxy / service mesh; compare results; discard side effects (or run with isolated state).",
            "Real-traffic confidence; side-effect isolation can be tricky for stateful systems.",
            &["distributed_systems"],
            &["deployment", "testing"],
            "https://launchdarkly.com/blog/shadow-launching-with-feature-flags/",
        ),
        pat(
            "dark_launch",
            "Dark Launch",
            "pattern",
            "deployment",
            "Deploy new code to production but keep it inert behind feature flags; turn on selectively.",
            "Separate code deployment from feature release.",
            "Deployment risk is conflated with release risk.",
            "Ship gated code behind a flag; run integration in production with no user-visible change; gradually enable.",
            "Decoupled risks; gated code adds maintenance burden if left in place.",
            &["distributed_systems"],
            &["deployment", "release"],
            "https://martinfowler.com/bliki/DarkLaunch.html",
        ),
        pat(
            "recreate_deployment",
            "Recreate Deployment",
            "pattern",
            "deployment",
            "Tear down all old instances, then deploy new ones — accepting brief downtime.",
            "Simplify upgrades for systems that can't run mixed versions.",
            "Stateful migrations may break under simultaneous old/new instances.",
            "Set strategy to Recreate; orchestrator stops old before starting new; expect a brief outage.",
            "Simplest semantics; downtime equal to start-up time.",
            &["distributed_systems"],
            &["deployment", "kubernetes"],
            "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment",
        ),
        pat(
            "ab_testing",
            "A/B Testing",
            "pattern",
            "deployment",
            "Split traffic between two product variants and compare conversion or other KPIs.",
            "Make product changes data-driven, not opinion-driven.",
            "Engineering opinions on UX changes are often wrong.",
            "Randomize users into variants; collect outcome metrics; analyze with statistical rigor.",
            "Defensible product decisions; experiment design / stats literacy required.",
            &["distributed_systems"],
            &["deployment", "experimentation"],
            "https://en.wikipedia.org/wiki/A/B_testing",
        ),
        pat(
            "phased_rollout",
            "Phased Rollout",
            "pattern",
            "deployment",
            "Release in concentric audiences (internal → beta → power users → all) over hours/days.",
            "Catch issues in lower-risk populations first.",
            "Big-bang releases expose all users to bugs simultaneously.",
            "Define audience phases; gate each via feature flag; advance based on metrics and time elapsed.",
            "Containment; slower time-to-100%.",
            &["distributed_systems"],
            &["deployment", "release"],
            "https://martinfowler.com/articles/feature-toggles.html",
        ),
        pat(
            "trunk_based_development",
            "Trunk-Based Development",
            "principle",
            "deployment",
            "All developers commit small changes to a single shared branch (`main`/`trunk`) at least daily.",
            "Avoid merge-hell from long-lived branches and reduce integration risk.",
            "Long-lived feature branches drift and become painful to merge.",
            "Use short-lived branches (or commit direct) and feature flags for incomplete work; rely on CI gates.",
            "Continuous integration in fact; requires strong CI discipline.",
            &["distributed_systems"],
            &["deployment", "process"],
            "https://trunkbaseddevelopment.com/",
        ),
        pat(
            "gitflow",
            "GitFlow",
            "pattern",
            "deployment",
            "Branching model with `develop`, `feature`, `release`, `hotfix`, and `main` branches.",
            "Provide structure for teams with longer release cycles.",
            "Ad-hoc branching scales poorly for scheduled releases.",
            "Use `feature/*` off `develop`; cut `release/*` for stabilization; merge to `main` and tag; cherry-pick hotfixes back.",
            "Clear for release-train teams; over-engineered for continuous deployment.",
            &["distributed_systems"],
            &["deployment", "process"],
            "https://nvie.com/posts/a-successful-git-branching-model/",
        ),
        pat(
            "github_flow",
            "GitHub Flow",
            "pattern",
            "deployment",
            "Simple branching: every change is a short-lived branch off `main`, merged via PR.",
            "Support continuous deployment without GitFlow ceremony.",
            "Teams that deploy multiple times per day don't need release branches.",
            "Branch from `main`; PR for review; merge and deploy on green CI.",
            "Lightweight, fast; assumes mature CI/CD and main-stays-green.",
            &["distributed_systems"],
            &["deployment", "process"],
            "https://docs.github.com/en/get-started/quickstart/github-flow",
        ),
        pat(
            "branch_by_abstraction",
            "Branch by Abstraction",
            "pattern",
            "deployment",
            "Introduce an abstraction; migrate callers; swap implementations behind it; remove the old implementation.",
            "Perform large refactors in trunk without long-lived branches.",
            "Big refactors stall on branches and conflict with concurrent work.",
            "Step 1: extract interface. Step 2: implement new behind it. Step 3: switch via flag. Step 4: delete old.",
            "Mainline-safe refactors; takes more incremental work than a branch.",
            &["distributed_systems"],
            &["deployment", "refactoring"],
            "https://martinfowler.com/bliki/BranchByAbstraction.html",
        ),
        pat(
            "expand_contract_migration",
            "Expand-Contract Migration (Parallel Change)",
            "pattern",
            "deployment",
            "Add new schema/contract alongside the old (expand), migrate readers/writers, then remove the old (contract).",
            "Migrate breaking changes without downtime or coordinated releases.",
            "In-place breaking changes require synchronized deploys.",
            "Step 1: expand (dual-write or dual-read). Step 2: migrate clients. Step 3: contract (remove old).",
            "Continuous compatibility; multi-step coordination across teams.",
            &["distributed_systems"],
            &["deployment", "migration"],
            "https://martinfowler.com/bliki/ParallelChange.html",
        ),
        pat(
            "backwards_compatible_migration",
            "Backwards-Compatible Migration",
            "principle",
            "deployment",
            "Each migration step must keep both old and new code paths operational.",
            "Allow rolling deploys without coordinated releases across services.",
            "Atomic schema/API changes block rolling deploys.",
            "Add nullable columns / additive API fields; deploy producers first, then consumers; remove old only after all consumers updated.",
            "Smooth rollouts and rollback; takes more change steps.",
            &["distributed_systems"],
            &["deployment", "migration"],
            "https://martinfowler.com/bliki/ParallelChange.html",
        ),
        pat(
            "online_schema_change",
            "Online Schema Change",
            "pattern",
            "deployment",
            "Apply database schema changes without locking the table or blocking writes.",
            "Avoid downtime when altering large tables.",
            "Naive ALTER TABLE locks the table for hours on large data.",
            "Use pt-online-schema-change, gh-ost, or native online-DDL; create a shadow table, backfill, swap atomically.",
            "Zero-downtime DDL; resource overhead during backfill; tools have specific constraints.",
            &["distributed_systems"],
            &["deployment", "database"],
            "https://www.percona.com/doc/percona-toolkit/3.0/pt-online-schema-change.html",
        ),
    ]
}
