//! Conflict-free Replicated Data Types (CRDTs), logical clocks, probabilistic data structures.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- Counters ----------
        pat(
            "g_counter",
            "G-Counter (Grow-Only Counter)",
            "pattern",
            "distributed_data",
            "CRDT counter that only increments; merge = element-wise max of per-node tallies.",
            "Sum events across replicas without coordination, accepting only increments.",
            "Distributed counters under partition produce lost updates or require coordination.",
            "Each node has its own counter; merge sums max per node; total = sum of per-node values.",
            "Convergent without locks; can't decrement.",
            &["distributed_systems", "concurrent_programming"],
            &["crdt", "counter"],
            "https://hal.inria.fr/inria-00555588/",
        ),
        pat(
            "pn_counter",
            "PN-Counter (Increment + Decrement Counter)",
            "pattern",
            "distributed_data",
            "Pair of G-Counters (increments and decrements); total = P - N.",
            "Support increment and decrement with CRDT semantics.",
            "G-Counters can't decrement.",
            "Maintain P and N as G-Counters; total = sum(P) - sum(N); merge each side independently.",
            "Convergent and decrement-capable; storage is 2× G-Counter.",
            &["distributed_systems", "concurrent_programming"],
            &["crdt", "counter"],
            "https://hal.inria.fr/inria-00555588/",
        ),
        pat(
            "or_set",
            "OR-Set (Observed-Remove Set)",
            "pattern",
            "distributed_data",
            "Set where each add is tagged with a unique id; remove only deletes observed ids.",
            "Allow concurrent add/remove with intuitive 'last write wins per element' semantics.",
            "G-Set can't remove; 2P-Set can't re-add.",
            "Tag each add with (element, unique_id); set = {e | ∃ id : (e, id) ∈ A ∧ (e, id) ∉ R}; merge unions A's and R's.",
            "Add wins ties; tag set grows over time (needs GC).",
            &["distributed_systems"],
            &["crdt", "set"],
            "https://hal.inria.fr/inria-00555588/",
        ),
        pat(
            "two_phase_set",
            "2P-Set (Two-Phase Set)",
            "pattern",
            "distributed_data",
            "Set with separate add-set A and tombstone-set R; once removed, an element cannot be re-added.",
            "Simple grow-only set with removal.",
            "G-Set cannot remove; OR-Set is more complex.",
            "Maintain A and R; element ∈ set iff ∈ A and ∉ R; merge unions both.",
            "Simple; once-removed-forever semantics rules out many use cases.",
            &["distributed_systems"],
            &["crdt", "set"],
            "https://hal.inria.fr/inria-00555588/",
        ),
        pat(
            "lww_register",
            "Last-Writer-Wins Register",
            "pattern",
            "distributed_data",
            "Single-value register where merge picks the value with the highest timestamp; ties broken by replica id.",
            "Provide a CRDT register with simple LWW semantics.",
            "Naive register merges lose data under conflicts.",
            "Each write attaches a (timestamp, replica_id); merge keeps the higher pair; physical clocks usually OK with NTP, HLC better.",
            "Trivial to implement; loses concurrent writes (last writer wins).",
            &["distributed_systems"],
            &["crdt", "register"],
            "https://hal.inria.fr/inria-00555588/",
        ),
        pat(
            "lww_element_set",
            "LWW-Element-Set",
            "pattern",
            "distributed_data",
            "Set keyed by (element, last-add-ts, last-remove-ts); element present iff latest add > latest remove.",
            "Convergent set with simple wall-clock semantics.",
            "OR-Set is more complex than needed when LWW is acceptable.",
            "Maintain per-element add/remove timestamps; presence by comparison; merge keeps max ts per element per side.",
            "Easy; tied to clock semantics.",
            &["distributed_systems"],
            &["crdt", "set"],
            "https://hal.inria.fr/inria-00555588/",
        ),
        pat(
            "mv_register",
            "Multi-Value Register",
            "pattern",
            "distributed_data",
            "Register that retains all concurrent values; application reconciles or shows conflicts.",
            "Preserve concurrent writes for explicit conflict resolution.",
            "LWW silently drops concurrent writes.",
            "Use version vectors; if writes are concurrent, store both; reads return a set.",
            "Lossless; UX/application must handle multi-value reads.",
            &["distributed_systems"],
            &["crdt", "register"],
            "https://hal.inria.fr/inria-00555588/",
        ),
        pat(
            "sequence_crdt",
            "Sequence CRDT (RGA / Treedoc)",
            "pattern",
            "distributed_data",
            "Ordered list CRDT supporting concurrent insert/delete (used in collaborative editors).",
            "Allow collaborative editing of text/lists with eventual consistency.",
            "OT (Operational Transform) requires global ordering; CRDT alternative works peer-to-peer.",
            "Use RGA, Treedoc, Yjs, Automerge: insertions get position identifiers from a dense order; deletions tombstone.",
            "Collaborative editing; tombstones accumulate without GC.",
            &["distributed_systems"],
            &["crdt", "collaboration"],
            "https://github.com/automerge/automerge",
        ),
        // ---------- Clocks ----------
        pat(
            "lamport_clock",
            "Lamport Clock",
            "pattern",
            "distributed_data",
            "Scalar logical clock: each event increments; on receive, set to max(local, msg)+1.",
            "Establish a happens-before order across distributed events.",
            "Wall clocks aren't synchronized enough for causal ordering.",
            "Maintain a counter per process; tick on event/send/receive per Lamport's rules.",
            "Cheap and total-order-able; doesn't detect concurrency.",
            &["distributed_systems", "concurrent_programming"],
            &["clock", "logical"],
            "https://lamport.azurewebsites.net/pubs/time-clocks.pdf",
        ),
        pat(
            "vector_clock",
            "Vector Clock",
            "pattern",
            "distributed_data",
            "Vector of per-process counters; allows detecting concurrent vs causally-ordered events.",
            "Identify true causal ordering and concurrency.",
            "Lamport clocks miss concurrency information.",
            "Each process maintains V[i]; increment own slot on event; on receive, take element-wise max + increment own.",
            "Detects concurrency; size grows with process count; needs membership knowledge.",
            &["distributed_systems"],
            &["clock", "logical"],
            "https://en.wikipedia.org/wiki/Vector_clock",
        ),
        pat(
            "hybrid_logical_clock",
            "Hybrid Logical Clock (HLC)",
            "pattern",
            "distributed_data",
            "Combine wall-clock and logical clock: 64-bit timestamp that preserves causal order and is close to physical time.",
            "Get human-readable timestamps that still preserve happens-before.",
            "Pure logical clocks aren't human-meaningful; pure physical clocks can violate causality under skew.",
            "HLC = (physical, logical); on send/receive, advance per HLC rules; clocks remain close to physical when synced.",
            "Best of both; relies on roughly-synchronized physical clocks.",
            &["distributed_systems"],
            &["clock", "logical"],
            "https://cse.buffalo.edu/tech-reports/2014-04.pdf",
        ),
        pat(
            "version_vector",
            "Version Vector",
            "pattern",
            "distributed_data",
            "Per-replica version counter attached to data; used to detect concurrent writes in optimistic replication.",
            "Detect concurrent updates and surface conflicts.",
            "Single version numbers can't distinguish concurrent from sequential updates.",
            "Each replica has a slot; bump on write; reads carry the vector; on merge, compare slot-wise.",
            "Lossless conflict detection; size grows with replica count.",
            &["distributed_systems"],
            &["clock", "replication"],
            "https://en.wikipedia.org/wiki/Version_vector",
        ),
        pat(
            "dotted_version_vector",
            "Dotted Version Vector",
            "pattern",
            "distributed_data",
            "Version vector + a single 'dot' for the most recent write, supporting client-side replicas without unique IDs.",
            "Track causality when clients (not just servers) write.",
            "Vanilla version vectors require unique server IDs per writer.",
            "Vector represents seen versions; dot is the new event; merge handles dot inclusion explicitly.",
            "Correct under client-side writes; slightly more complex semantics.",
            &["distributed_systems"],
            &["clock", "replication"],
            "https://www.cs.princeton.edu/courses/archive/fall17/cos518/papers/dotted.pdf",
        ),
        // ---------- Gossip / Anti-Entropy ----------
        pat(
            "gossip_protocol",
            "Gossip Protocol",
            "pattern",
            "distributed_data",
            "Each node periodically exchanges state with a random peer; information spreads epidemically.",
            "Disseminate state without a central coordinator or O(N²) connectivity.",
            "All-to-all messaging scales poorly; centralized broadcast is a bottleneck.",
            "Each node picks a random peer every T seconds; exchanges digest/delta; converges in O(log N) rounds.",
            "Robust and scalable; eventual consistency only.",
            &["distributed_systems"],
            &["gossip", "replication"],
            "https://en.wikipedia.org/wiki/Gossip_protocol",
        ),
        pat(
            "anti_entropy",
            "Anti-Entropy (Merkle Sync)",
            "pattern",
            "distributed_data",
            "Periodic background reconciliation between replicas using Merkle trees to compare state.",
            "Repair divergence missed by primary replication.",
            "Lost updates and partition-recovery leave replicas inconsistent.",
            "Build Merkle trees over data ranges; exchange root hashes; recurse only into mismatched subtrees; pull missing items.",
            "Efficient repair (O(log N) for divergence); requires periodic scan.",
            &["distributed_systems"],
            &["replication", "merkle"],
            "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf",
        ),
        pat(
            "hinted_handoff",
            "Hinted Handoff",
            "pattern",
            "distributed_data",
            "When a target replica is unavailable, a coordinator stores a 'hint' and forwards the write later.",
            "Tolerate transient replica failures without blocking writes.",
            "Quorum writes block when replicas are temporarily down.",
            "Coordinator writes to W-1 healthy replicas; saves a hint for the down replica; replays when it returns; expire hints after timeout.",
            "High availability under transient failures; hints add storage and consistency risk on permanent loss.",
            &["distributed_systems"],
            &["replication", "availability"],
            "https://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsRepairNodesHintedHandoff.html",
        ),
        // ---------- Probabilistic data structures ----------
        pat(
            "bloom_filter",
            "Bloom Filter",
            "pattern",
            "distributed_data",
            "Space-efficient probabilistic set: tells you definitely-not-in or maybe-in.",
            "Cheaply rule out misses before expensive lookups.",
            "Disk/network lookups for non-existent keys are wasteful.",
            "Hash inserts to K bits in an M-bit array; lookup checks all K bits; false-positive rate ≈ (1 - e^{-Kn/M})^K.",
            "Tiny memory; no removal; tunable FPR.",
            &["distributed_systems"],
            &["sketch", "probabilistic"],
            "https://en.wikipedia.org/wiki/Bloom_filter",
        ),
        pat(
            "cuckoo_filter",
            "Cuckoo Filter",
            "pattern",
            "distributed_data",
            "Bloom-like filter supporting deletion, with better locality.",
            "Get Bloom-style probabilistic membership with removal.",
            "Counting Bloom filters use more memory; classic Bloom can't delete.",
            "Use a cuckoo hash table of fingerprints; insert relocates via cuckoo eviction; delete clears the fingerprint.",
            "Supports delete and is cache-friendly; slightly higher FPR than tuned Bloom.",
            &["distributed_systems"],
            &["sketch", "probabilistic"],
            "https://www.cs.cmu.edu/~dga/papers/cuckoo-conext2014.pdf",
        ),
        pat(
            "count_min_sketch",
            "Count-Min Sketch",
            "pattern",
            "distributed_data",
            "Probabilistic counter that estimates frequencies with bounded error using log(N) memory.",
            "Approximate counts in streaming/heavy-hitter scenarios.",
            "Exact counting per key is prohibitive at high cardinality.",
            "D hash functions index W counters each; on update, increment min position; on query, take min across rows.",
            "Sub-linear memory; over-estimates only; collisions inflate small counts.",
            &["distributed_systems"],
            &["sketch", "streaming"],
            "https://sites.google.com/site/countminsketch/",
        ),
        pat(
            "hyperloglog",
            "HyperLogLog",
            "pattern",
            "distributed_data",
            "Probabilistic cardinality estimator using few KB of memory regardless of set size.",
            "Estimate unique counts at huge scale.",
            "Exact COUNT DISTINCT is O(N) memory.",
            "Hash each item; track leading-zero counts per bucket; estimate cardinality from harmonic mean.",
            "Tiny memory, ~1% error; merging multiple HLLs is trivial.",
            &["distributed_systems"],
            &["sketch", "streaming"],
            "https://en.wikipedia.org/wiki/HyperLogLog",
        ),
        pat(
            "quantile_sketch",
            "t-Digest / Quantile Sketch",
            "pattern",
            "distributed_data",
            "Streaming approximation of order statistics (median, p99, p99.9) in bounded memory.",
            "Compute high-percentile latency without storing all samples.",
            "Exact quantiles require sorting or massive memory.",
            "Use t-digest, KLL, or DDSketch; mergeable across streams; tune accuracy at tails.",
            "Accurate p99/p99.9; choice of sketch affects merging vs accuracy.",
            &["distributed_systems"],
            &["sketch", "streaming"],
            "https://arxiv.org/abs/1902.04023",
        ),
        pat(
            "top_k_sketch",
            "Top-K Sketch (Space-Saving)",
            "pattern",
            "distributed_data",
            "Maintain approximate top-K most frequent items in a stream with bounded memory.",
            "Find heavy hitters without storing every key.",
            "Exact top-K requires per-key counting at full cardinality.",
            "Use Space-Saving algorithm: keep K (key, count, error) tuples; replace min when new key arrives.",
            "Tight memory; biased toward popular items; under-estimates rare ones.",
            &["distributed_systems"],
            &["sketch", "streaming"],
            "https://www.cs.ucsb.edu/~suri/psdir/ency.pdf",
        ),
        pat(
            "reservoir_sampling",
            "Reservoir Sampling",
            "pattern",
            "distributed_data",
            "Pick K random items from a stream of unknown length with uniform probability.",
            "Sample uniformly from an unbounded stream in O(K) memory.",
            "Two-pass sampling needs O(N) storage; per-item rejection biases samples.",
            "Algorithm R: keep first K; for item i>K, replace random reservoir slot with probability K/i.",
            "Constant memory; reservoir distribution is exact uniform.",
            &["distributed_systems"],
            &["sketch", "streaming"],
            "https://en.wikipedia.org/wiki/Reservoir_sampling",
        ),
        // ---------- Other distributed data structures ----------
        pat(
            "skip_list",
            "Skip List",
            "pattern",
            "distributed_data",
            "Probabilistic ordered data structure with O(log N) operations, simpler than balanced trees.",
            "Provide an ordered set/map without complex rebalancing logic.",
            "Balanced trees (AVL/Red-Black) are intricate; concurrent variants harder still.",
            "Layered linked lists; each level skips elements probabilistically; concurrent variants use lock-free nodes.",
            "Easy concurrent implementation; slightly worse cache behavior than tree.",
            &["distributed_systems", "concurrent_programming"],
            &["data_structure"],
            "https://en.wikipedia.org/wiki/Skip_list",
        ),
        pat(
            "lsm_tree",
            "Log-Structured Merge Tree",
            "pattern",
            "distributed_data",
            "Write-optimized store: buffer in memory, flush as sorted runs, periodically compact.",
            "Sustain very high write throughput on disk.",
            "B-Trees random-write to disk and slow.",
            "Writes go to an in-memory memtable; flush to immutable SSTables; background compactions merge SSTables; reads check memtable + bloom filters + SSTables.",
            "Excellent write throughput; reads can amplify; compaction tuning is critical.",
            &["distributed_systems"],
            &["data_structure", "storage"],
            "https://www.cs.umb.edu/~poneil/lsmtree.pdf",
        ),
        pat(
            "merkle_tree",
            "Merkle Tree",
            "pattern",
            "distributed_data",
            "Binary hash tree where each internal node hashes the concatenation of its children.",
            "Efficiently prove inclusion / detect difference between large data sets.",
            "Comparing entire datasets requires O(N) bandwidth.",
            "Hash leaves bottom-up; share roots; recurse only into mismatched subtrees for repair (anti-entropy).",
            "Logarithmic proofs; foundation for Git, blockchain, certificate transparency.",
            &["distributed_systems"],
            &["data_structure", "cryptography"],
            "https://en.wikipedia.org/wiki/Merkle_tree",
        ),
    ]
}
