//! Functional programming patterns, type-level patterns, and logic programming patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- Core FP ----------
        pat(
            "pure_function",
            "Pure Function",
            "pattern",
            "functional",
            "A function whose output depends only on inputs and has no side effects.",
            "Make behavior testable, composable, and cacheable.",
            "Hidden state and effects make reasoning difficult.",
            "Separate calculation from effects and pass dependencies explicitly.",
            "Improves reasoning; effects still need explicit boundaries.",
            &["functional_programming", "procedural_programming"],
            &["fp", "referential_transparency"],
            "https://en.wikipedia.org/wiki/Pure_function",
        ),
        pat(
            "function_composition",
            "Function Composition",
            "pattern",
            "functional",
            "Build larger behavior by connecting smaller functions.",
            "Keep transformations small and reusable.",
            "Nested or duplicated logic obscures data flow.",
            "Compose functions in explicit pipelines or combinators.",
            "Readable when types align; poor names can make pipelines opaque.",
            &["functional_programming", "procedural_programming"],
            &["fp", "composition"],
            "https://en.wikipedia.org/wiki/Function_composition_(computer_science)",
        ),
        pat(
            "immutable_data",
            "Immutable Data",
            "pattern",
            "functional",
            "Prefer values that cannot be mutated after creation.",
            "Avoid accidental shared-state changes.",
            "Aliased mutable data creates temporal coupling and race risk.",
            "Model updates as new values or persistent data structures.",
            "Simplifies concurrency; may require allocation-aware design.",
            &["functional_programming", "concurrent_programming"],
            &["fp", "state"],
            "https://en.wikipedia.org/wiki/Immutable_object",
        ),
        pat(
            "algebraic_data_type",
            "Algebraic Data Type",
            "pattern",
            "functional",
            "Model data with product and sum types.",
            "Make domain states explicit and exhaustive.",
            "Invalid combinations are easy to represent with loose records.",
            "Use tagged unions/enums and structured fields.",
            "Improves correctness; requires languages or conventions with good pattern matching.",
            &["functional_programming"],
            &["fp", "types"],
            "https://en.wikipedia.org/wiki/Algebraic_data_type",
        ),
        pat(
            "persistent_data_structure",
            "Persistent Data Structure",
            "pattern",
            "functional",
            "Updates yield a new version while preserving the previous version (structural sharing).",
            "Combine immutability with reasonable performance via shared structure.",
            "Naive copy-on-write is too expensive for repeated updates.",
            "Use a structure (HAMT, finger tree, RRB) that shares unchanged parts between versions.",
            "Efficient time-travel and snapshots; O(log n) updates instead of O(1) in-place.",
            &["functional_programming", "concurrent_programming"],
            &["fp", "data_structures"],
            "https://en.wikipedia.org/wiki/Persistent_data_structure",
        ),
        pat(
            "currying",
            "Currying",
            "pattern",
            "functional",
            "Transform a function of n arguments into a chain of single-argument functions.",
            "Enable partial application and pointfree style.",
            "Multi-arg functions are awkward to specialize incrementally.",
            "Define `f a b c` so partial application yields useful intermediate functions.",
            "Composable APIs; argument-order matters and unfamiliar readers may stumble.",
            &["functional_programming"],
            &["fp", "composition"],
            "https://en.wikipedia.org/wiki/Currying",
        ),
        pat(
            "partial_application",
            "Partial Application",
            "pattern",
            "functional",
            "Fix some arguments of a function to produce a function of the remaining arguments.",
            "Specialize generic functions to a context without ceremony.",
            "Callers repeatedly pass the same prefix of arguments.",
            "Bind the leading arguments once and reuse the resulting closure.",
            "Concise specialization; over-use can hide what's actually being called.",
            &["functional_programming"],
            &["fp", "composition"],
            "https://en.wikipedia.org/wiki/Partial_application",
        ),
        pat(
            "memoization",
            "Memoization",
            "pattern",
            "functional",
            "Cache a pure function's results keyed by its arguments.",
            "Trade memory for time on repeated identical calls.",
            "Expensive computations are repeated with the same inputs.",
            "Wrap the function in a cache (LRU, fixed-size, weak-keyed) keyed by argument tuple.",
            "Lower latency; only safe for pure functions; cache size and eviction need attention.",
            &["functional_programming"],
            &["fp", "performance", "caching"],
            "https://en.wikipedia.org/wiki/Memoization",
        ),
        pat(
            "lazy_evaluation",
            "Lazy Evaluation",
            "pattern",
            "functional",
            "Defer computing a value until it is actually needed.",
            "Avoid wasted work and support infinite data structures.",
            "Strict evaluation forces work whether or not a result is consumed.",
            "Represent values as thunks/promises that are forced on demand.",
            "Composable, supports infinite streams; reasoning about evaluation order becomes harder.",
            &["functional_programming"],
            &["fp", "evaluation"],
            "https://en.wikipedia.org/wiki/Lazy_evaluation",
        ),
        pat(
            "tail_call_optimization",
            "Tail Call Optimization (TCO)",
            "pattern",
            "functional",
            "Reuse the current stack frame when a function returns the result of another call directly.",
            "Permit unbounded recursion without stack growth.",
            "Deep recursion blows the call stack in languages that don't optimize tail calls.",
            "Write recursion in tail position and rely on or trampoline-emulate TCO.",
            "Iterative-equivalent recursion; only applies to true tail calls.",
            &["functional_programming"],
            &["fp", "recursion", "performance"],
            "https://en.wikipedia.org/wiki/Tail_call",
        ),
        pat(
            "trampoline",
            "Trampoline",
            "pattern",
            "functional",
            "Convert non-tail recursive calls into a loop that repeatedly invokes returned thunks.",
            "Emulate TCO in languages or contexts that lack it.",
            "Recursion exceeds the stack limit but the call pattern is tail-shaped after refactoring.",
            "Have each step return either a result or a continuation; a driver loop forces continuations until a result emerges.",
            "Stack-safe recursion; allocates thunks on the heap.",
            &["functional_programming"],
            &["fp", "recursion"],
            "https://en.wikipedia.org/wiki/Trampoline_(computing)",
        ),
        pat(
            "continuation_passing_style",
            "Continuation-Passing Style (CPS)",
            "pattern",
            "functional",
            "Pass each function an explicit continuation describing what to do with its result.",
            "Make control flow first-class and inversion of control explicit.",
            "Direct-style code can't easily express non-local return, multi-shot return, or asynchrony.",
            "Rewrite functions to accept a continuation; instead of returning, invoke the continuation with the value.",
            "Enables call/cc, async, exceptions; loses direct-style readability.",
            &["functional_programming"],
            &["fp", "control_flow"],
            "https://en.wikipedia.org/wiki/Continuation-passing_style",
        ),
        pat(
            "y_combinator",
            "Y Combinator (Fixed-Point Combinator)",
            "pattern",
            "functional",
            "Define recursion in untyped lambda calculus via a fixed-point combinator that supplies a function to itself.",
            "Show recursion can emerge from anonymous functions without named binding.",
            "Strict lambda calculus has no built-in recursion construct.",
            "Use Y f = f (Y f) (or Z combinator in strict languages) to construct the fixed point.",
            "Mostly didactic; in real code prefer letrec or named recursion.",
            &["functional_programming"],
            &["fp", "lambda_calculus", "theory"],
            "https://en.wikipedia.org/wiki/Fixed-point_combinator",
        ),
        // ---------- Type-class hierarchy ----------
        pat(
            "monad",
            "Monad",
            "pattern",
            "functional",
            "Sequence computations in a context such as optionality, errors, state, or IO.",
            "Compose effectful computations while preserving laws.",
            "Raw effects and nested callbacks obscure control flow.",
            "Use bind/flatMap and return/unit to chain contextual values.",
            "Powerful abstraction; can confuse teams without shared vocabulary.",
            &["functional_programming"],
            &["fp", "effects"],
            "https://en.wikipedia.org/wiki/Monad_(functional_programming)",
        ),
        pat(
            "typeclass",
            "Type Class",
            "pattern",
            "functional",
            "Define ad-hoc polymorphic behavior separately from data types.",
            "Extend behavior without inheritance or editing original types.",
            "A generic algorithm needs operations for many unrelated types.",
            "Provide instances implementing a small law-aware interface.",
            "Very extensible; instance resolution rules must be predictable.",
            &["functional_programming"],
            &["fp", "polymorphism"],
            "https://en.wikipedia.org/wiki/Type_class",
        ),
        pat(
            "functor",
            "Functor",
            "pattern",
            "functional",
            "A structure with a map operation that preserves identity and composition.",
            "Lift pure functions over a context like Option, List, or Future.",
            "Repeated unwrap/re-wrap clutter obscures the underlying transformation.",
            "Define `fmap : (a -> b) -> F a -> F b` and obey identity and composition laws.",
            "Uniform transformation API; less powerful than Applicative or Monad.",
            &["functional_programming"],
            &["fp", "abstraction", "category_theory"],
            "https://en.wikipedia.org/wiki/Functor_(functional_programming)",
        ),
        pat(
            "applicative_functor",
            "Applicative Functor",
            "pattern",
            "functional",
            "A Functor that allows lifting multi-argument functions over multiple wrapped values.",
            "Combine independent effectful values without sequencing dependencies.",
            "Mapping a two-argument function requires sequencing one value's effect into another.",
            "Provide `pure : a -> F a` and `<*> : F (a -> b) -> F a -> F b`.",
            "Parallel-friendly composition; can't express dependent effects without Monad.",
            &["functional_programming"],
            &["fp", "abstraction", "category_theory"],
            "https://en.wikipedia.org/wiki/Applicative_functor",
        ),
        pat(
            "monoid",
            "Monoid",
            "pattern",
            "functional",
            "An associative binary operation with an identity element.",
            "Combine values uniformly and exploit associativity for parallel reduction.",
            "Aggregation code is sprinkled with special cases and duplicated initial values.",
            "Define `mempty` and `mappend`, ensure associativity, and use generic fold operations.",
            "Enables parallel reduction and reusable combiners; not all operations are associative.",
            &["functional_programming", "parallel_programming"],
            &["fp", "algebra", "category_theory"],
            "https://en.wikipedia.org/wiki/Monoid_(category_theory)",
        ),
        pat(
            "semigroup",
            "Semigroup",
            "pattern",
            "functional",
            "An associative binary operation, without requiring an identity element.",
            "Combine non-empty values where no neutral element exists.",
            "Some types (non-empty list, Min, Max) don't admit a natural identity.",
            "Define `<>` and prove associativity; lift to Monoid by wrapping in Option when needed.",
            "Captures non-empty aggregations precisely; can't use empty-friendly folds directly.",
            &["functional_programming"],
            &["fp", "algebra"],
            "https://en.wikipedia.org/wiki/Semigroup",
        ),
        pat(
            "free_monad",
            "Free Monad",
            "pattern",
            "functional",
            "Build a monad from any functor, deferring interpretation of effects.",
            "Separate program description from program execution.",
            "Effectful programs hard-code their interpreter and become hard to change or test.",
            "Lift each operation into a functor; combine via Free; provide one or more interpreters.",
            "Pluggable interpreters and testable scripts; allocates per step and runtime perf must be measured.",
            &["functional_programming"],
            &["fp", "effects", "category_theory"],
            "https://en.wikipedia.org/wiki/Monad_(functional_programming)#Free_monads",
        ),
        pat(
            "tagless_final",
            "Tagless Final",
            "pattern",
            "functional",
            "Express DSLs as a type class of operations parameterized by the interpreting effect.",
            "Avoid Free's allocation and existential overhead while keeping pluggable interpreters.",
            "Free monads add allocation and tagging cost in tight loops.",
            "Define an `Algebra[F]` of operations; programs are polymorphic in F; each interpreter chooses F.",
            "Lightweight pluggable effects; cross-language polymorphism support varies.",
            &["functional_programming"],
            &["fp", "effects"],
            "https://okmij.org/ftp/tagless-final/",
        ),
        pat(
            "comonad",
            "Comonad",
            "pattern",
            "functional",
            "Dual of monad: extract a value from a context and extend a context-dependent computation.",
            "Express context-aware computations (image filters, cellular automata, store-of-state).",
            "Algorithms that need to read 'where am I' in a structure don't fit Monad cleanly.",
            "Implement `extract : W a -> a` and `extend : (W a -> b) -> W a -> W b` (or `duplicate`).",
            "Elegant for context-dependent computation; less common, fewer library helpers.",
            &["functional_programming"],
            &["fp", "abstraction", "category_theory"],
            "https://en.wikipedia.org/wiki/Comonad",
        ),
        pat(
            "profunctor",
            "Profunctor",
            "pattern",
            "functional",
            "A bifunctor contravariant in its first argument and covariant in its second.",
            "Model arrow-like transformations and form the basis for many optic types.",
            "Modeling pre/post-processing around a callable as separate types is awkward.",
            "Define `dimap : (c -> a) -> (b -> d) -> P a b -> P c d`.",
            "Foundation for lens libraries; learning curve steeper than Functor.",
            &["functional_programming"],
            &["fp", "category_theory"],
            "https://en.wikipedia.org/wiki/Profunctor",
        ),
        // ---------- Optics ----------
        pat(
            "lens",
            "Lens (Optic)",
            "pattern",
            "functional",
            "A composable getter/setter pair for focusing on one part of a larger immutable structure.",
            "Update nested immutable data without manual reconstruction.",
            "Updating a deeply nested field requires writing tedious copy-and-overwrite code.",
            "Define `Lens s a` with `view`, `set`, and `over`; compose lenses to focus deeper.",
            "Compositional immutable updates; learning curve and runtime overhead vary by encoding.",
            &["functional_programming"],
            &["fp", "optics", "immutability"],
            "https://en.wikipedia.org/wiki/Lens_(functional_programming)",
        ),
        pat(
            "prism",
            "Prism (Optic)",
            "pattern",
            "functional",
            "An optic for sum types: focus on one branch when it matches, else fail.",
            "Compose pattern-matching extraction with immutable updates.",
            "Nested ADTs need both case selection and field update in one pipeline.",
            "Define `Prism s a` with `preview : s -> Option<a>` and `review : a -> s`.",
            "Composable case access; only sensible for sum-type variants.",
            &["functional_programming"],
            &["fp", "optics"],
            "https://hackage.haskell.org/package/lens/docs/Control-Lens-Prism.html",
        ),
        pat(
            "traversal",
            "Traversal (Optic)",
            "pattern",
            "functional",
            "An optic that focuses on zero or more elements within a structure.",
            "Apply effectful updates to many parts of a structure uniformly.",
            "Mapping with side-effects over a deeply nested collection of fields is verbose.",
            "Define `Traversal s a` with `traverseOf` that walks the structure with an Applicative.",
            "Bulk updates compose with Lens/Prism; complexity matches the underlying walk.",
            &["functional_programming"],
            &["fp", "optics"],
            "https://hackage.haskell.org/package/lens/docs/Control-Lens-Traversal.html",
        ),
        // ---------- Type-level idioms ----------
        pat(
            "newtype",
            "Newtype Wrapper",
            "pattern",
            "functional",
            "Wrap an existing type in a new nominal type that carries no runtime cost.",
            "Distinguish values with the same representation but different meaning at the type level.",
            "Primitives like `String` and `i64` are passed around with no domain meaning, allowing mix-ups.",
            "Define a one-field tuple struct or `newtype` and expose only the operations that make domain sense.",
            "Type-safe distinctions for free; requires deriving or wrapping traits to use the inner ops.",
            &["functional_programming", "object_oriented_programming"],
            &["fp", "types", "rust", "haskell"],
            "https://wiki.haskell.org/Newtype",
        ),
        pat(
            "smart_constructor",
            "Smart Constructor",
            "pattern",
            "functional",
            "Hide a type's data constructor and expose only a validating builder.",
            "Guarantee invariants at the type level.",
            "Anyone can construct a record in an invalid state, forcing pervasive validation.",
            "Make the constructor private; export a function that returns `Result<T, E>` only on valid input.",
            "Type ensures validity; consumers can't bypass the check or destructure naively.",
            &["functional_programming"],
            &["fp", "types", "invariants"],
            "https://wiki.haskell.org/Smart_constructors",
        ),
        pat(
            "phantom_type",
            "Phantom Type",
            "pattern",
            "functional",
            "Use type parameters that don't appear in the runtime representation to encode states or kinds.",
            "Track compile-time facts (units, state machine stages, capability tokens) at zero cost.",
            "A single concrete type would lose distinctions the program needs to enforce.",
            "Add an unused type parameter and constrain usage by it (e.g., `Distance<Meters>`).",
            "Static safety with no runtime cost; type ergonomics depend on language inference.",
            &["functional_programming"],
            &["fp", "types"],
            "https://en.wikipedia.org/wiki/Phantom_type",
        ),
        pat(
            "gadt",
            "Generalized Algebraic Data Type (GADT)",
            "pattern",
            "functional",
            "An ADT whose constructors can refine the result type.",
            "Encode invariants in the type of each constructor.",
            "Plain ADTs can't constrain certain combinations (e.g., expression typing).",
            "Use GADT syntax to give each constructor a specific return type, then pattern-match in a way the compiler can refine.",
            "Stronger compile-time guarantees; exhaustiveness checks become more interesting.",
            &["functional_programming"],
            &["fp", "types"],
            "https://en.wikipedia.org/wiki/Generalized_algebraic_data_type",
        ),
        pat(
            "higher_kinded_type",
            "Higher-Kinded Type",
            "pattern",
            "functional",
            "Abstract over type constructors (kinds `* -> *`), not just types.",
            "Express type classes like Functor/Monad/Applicative generically.",
            "Languages limited to first-order generics can't express 'any container F' uniformly.",
            "Use type-level kinds or workaround encodings (Higher rank, GATs, defunctionalization).",
            "Unlocks library-level effect abstractions; type-system support varies by language.",
            &["functional_programming"],
            &["fp", "types"],
            "https://en.wikipedia.org/wiki/Type_constructor",
        ),
        pat(
            "rank_n_polymorphism",
            "Rank-N Polymorphism",
            "pattern",
            "functional",
            "Allow polymorphic functions to be arguments (not only at the outermost type position).",
            "Express callers that must accept polymorphic helpers without specializing.",
            "Rank-1 polymorphism forces callers to monomorphize before passing.",
            "Annotate parameters as `forall a. ...` (or equivalent) so the called code is universally quantified inside.",
            "Powerful abstraction; type inference becomes undecidable at higher ranks, so explicit types are needed.",
            &["functional_programming"],
            &["fp", "types"],
            "https://wiki.haskell.org/Rank-N_types",
        ),
        pat(
            "existential_type",
            "Existential Type",
            "pattern",
            "functional",
            "Hide a type variable so callers know an instance exists but not which one.",
            "Implement type-erased trait objects in a typed way.",
            "Collections of heterogeneous values with a common interface can't be expressed in plain ADTs.",
            "Wrap values as `exists a. (a, Class a)` (or use trait objects / dyn dispatch).",
            "Encapsulates concrete type; dispatches via the interface and loses access to the underlying type.",
            &["functional_programming", "object_oriented_programming"],
            &["fp", "types"],
            "https://wiki.haskell.org/Existential_type",
        ),
        pat(
            "type_family",
            "Type Family / Associated Type",
            "pattern",
            "functional",
            "Compute types from other types using a function defined at the type level.",
            "Express relationships between types that can't be expressed via simple parameters.",
            "Trait/typeclass instances need to refer to a related type that varies per instance.",
            "Declare an associated type (`type Item;` in Rust, `type family` in Haskell); each instance defines it.",
            "Cleaner generic APIs; type errors become more abstract.",
            &["functional_programming"],
            &["fp", "types"],
            "https://en.wikipedia.org/wiki/Type_family",
        ),
        // ---------- Recursion schemes ----------
        pat(
            "catamorphism",
            "Catamorphism (Fold)",
            "pattern",
            "functional",
            "Generic fold over a recursive structure given an algebra of how to combine layers.",
            "Express any structure-respecting reduction as data + algebra.",
            "Hand-rolled recursion duplicates the structural traversal and obscures the combining step.",
            "Express the structure as a functor; define an algebra `F a -> a`; fold with `cata`.",
            "Reusable folds; requires recursion-schemes machinery in the language/library.",
            &["functional_programming"],
            &["fp", "recursion_schemes"],
            "https://en.wikipedia.org/wiki/Catamorphism",
        ),
        pat(
            "anamorphism",
            "Anamorphism (Unfold)",
            "pattern",
            "functional",
            "Generic unfold that builds a recursive structure from a seed using a coalgebra.",
            "Generate trees, streams, or grammars from a small generator.",
            "Hand-coded unfolds intertwine generation logic with recursion.",
            "Define a coalgebra `a -> F a`; unfold with `ana` to produce the structure.",
            "Symmetric to cata; depending on language, requires explicit fixpoint encoding.",
            &["functional_programming"],
            &["fp", "recursion_schemes"],
            "https://en.wikipedia.org/wiki/Anamorphism",
        ),
        pat(
            "hylomorphism",
            "Hylomorphism",
            "pattern",
            "functional",
            "Compose an anamorphism with a catamorphism, often fused into a single pass.",
            "Build-then-fold pipelines without materializing intermediate structures.",
            "Generate-and-reduce code allocates a transient structure that wastes memory.",
            "Express as `cata alg . ana coalg`; libraries can fuse to a direct recursive function.",
            "Compositional and often allocation-free after fusion; harder to debug fused code.",
            &["functional_programming"],
            &["fp", "recursion_schemes"],
            "https://en.wikipedia.org/wiki/Hylomorphism_(computer_science)",
        ),
        pat(
            "paramorphism",
            "Paramorphism",
            "pattern",
            "functional",
            "A catamorphism where the algebra also has access to the original substructure at each step.",
            "Express folds that need both the recursive result and the original sub-tree.",
            "A vanilla cata loses access to the substructure once it folds.",
            "Use an algebra `F (a, Fix F) -> a` so each step sees the recursive result paired with the substructure.",
            "Expressive folds; algebra signatures grow.",
            &["functional_programming"],
            &["fp", "recursion_schemes"],
            "https://en.wikipedia.org/wiki/Recursion_scheme#Paramorphism",
        ),
        // ---------- Effects ----------
        pat(
            "either_for_errors",
            "Either / Result for Errors",
            "pattern",
            "functional",
            "Represent fallible computations as a sum of success and failure.",
            "Make error paths first-class without exceptions.",
            "Exceptions hide control flow and skip stack frames silently.",
            "Return `Either<E, A>` / `Result<E, A>`; propagate explicitly with `?` / `flatMap`.",
            "Predictable error flow; verbosity without `?`/`for` helpers.",
            &["functional_programming"],
            &["fp", "errors"],
            "https://en.wikipedia.org/wiki/Result_type",
        ),
        pat(
            "reader_monad",
            "Reader Monad",
            "pattern",
            "functional",
            "Thread an environment implicitly through pure computations.",
            "Avoid passing configuration through every signature.",
            "Configuration arguments leak everywhere or become hidden globals.",
            "Wrap computations in `Reader<R, A>` and use `local`/`ask` to access the environment.",
            "Composable DI without globals; explicit reader threading adds noise without sugar.",
            &["functional_programming"],
            &["fp", "effects"],
            "https://en.wikibooks.org/wiki/Haskell/Reader_monad",
        ),
        pat(
            "writer_monad",
            "Writer Monad",
            "pattern",
            "functional",
            "Accumulate a log/side-output alongside a value using a Monoid.",
            "Collect telemetry, traces, or audit data declaratively.",
            "Imperative logging interleaves IO with pure logic.",
            "Wrap values in `Writer<W, A>` where W is a Monoid; combine values and append to the log.",
            "Pure logging; the log is materialized in memory until extracted.",
            &["functional_programming"],
            &["fp", "effects"],
            "https://en.wikibooks.org/wiki/Haskell/Writer_monad",
        ),
        pat(
            "state_monad",
            "State Monad",
            "pattern",
            "functional",
            "Encapsulate threaded mutable state inside a pure computation.",
            "Use state safely in a pure environment.",
            "Threading state by hand pollutes every signature.",
            "Wrap stateful steps in `State<S, A>`; combine with `get`, `put`, `modify`.",
            "Pure-state composition; over-use can re-implement imperative code in heavier syntax.",
            &["functional_programming"],
            &["fp", "effects"],
            "https://en.wikibooks.org/wiki/Haskell/Understanding_monads/State",
        ),
        pat(
            "io_monad",
            "IO Monad",
            "pattern",
            "functional",
            "Represent side-effecting computations as values that are interpreted at program edge.",
            "Keep most of the program pure and isolate effects.",
            "Mixing pure and impure code breaks referential transparency.",
            "Build computations as `IO<A>`; only the runtime evaluates them in `main`.",
            "Pure-by-construction; effect ordering encoded in type structure.",
            &["functional_programming"],
            &["fp", "effects"],
            "https://en.wikipedia.org/wiki/IO_monad",
        ),
        pat(
            "monad_transformer",
            "Monad Transformer",
            "pattern",
            "functional",
            "Combine effects (state + error + IO + reader) by stacking monads via transformers.",
            "Compose effect layers without writing a custom monad each time.",
            "A computation needs several effects simultaneously and a single monad is insufficient.",
            "Use `StateT`, `ReaderT`, `EitherT`, `IO` and similar; lift inner operations through `lift`.",
            "Reusable effect stacks; type signatures get heavy and lifting can be noisy.",
            &["functional_programming"],
            &["fp", "effects"],
            "https://wiki.haskell.org/Monad_Transformers",
        ),
        pat(
            "algebraic_effects",
            "Algebraic Effects / Handlers",
            "pattern",
            "functional",
            "Express effects as operations whose semantics are decided by an outer handler.",
            "Decouple effect description from interpretation more flexibly than Monad transformers.",
            "Stacked monad transformers don't compose orthogonally and impose lifting boilerplate.",
            "Declare effect operations; programs use them freely; handlers around the program catch and interpret them.",
            "Compositional, swappable effect semantics; requires runtime/language support (Koka, OCaml 5, Eff).",
            &["functional_programming"],
            &["fp", "effects"],
            "https://en.wikipedia.org/wiki/Effect_system",
        ),
        // ---------- Logic programming ----------
        pat(
            "facts_rules_queries",
            "Facts, Rules, and Queries",
            "pattern",
            "logic",
            "Represent knowledge as relations and ask the runtime to search answers.",
            "Make domain constraints declarative.",
            "Control-flow code obscures the logical shape of a problem.",
            "Encode facts and rules, then query relations.",
            "Concise for symbolic domains; performance depends on search shape.",
            &["logic_programming", "declarative_programming"],
            &["logic", "prolog"],
            "https://en.wikipedia.org/wiki/Logic_programming",
        ),
        pat(
            "unification",
            "Unification",
            "pattern",
            "logic",
            "Solve symbolic equality constraints by binding variables.",
            "Let matching and binding be one operation.",
            "Manual matching code duplicates relation logic.",
            "Use terms with variables and allow the engine to unify compatible structures.",
            "Expressive but requires care with occurs checks and instantiation.",
            &["logic_programming", "declarative_programming"],
            &["logic", "prolog"],
            "https://en.wikipedia.org/wiki/Unification_(computer_science)",
        ),
        pat(
            "constraint_logic_programming",
            "Constraint Logic Programming",
            "pattern",
            "logic",
            "Combine logic relations with constraint solvers.",
            "Solve combinatorial problems declaratively.",
            "Generate-and-test search is too broad.",
            "State constraints over finite domains or other solver-backed spaces.",
            "Prunes search dramatically; solver capabilities shape the model.",
            &["logic_programming", "declarative_programming"],
            &["logic", "constraints"],
            "https://en.wikipedia.org/wiki/Constraint_logic_programming",
        ),
        pat(
            "definite_clause_grammar",
            "Definite Clause Grammar",
            "pattern",
            "logic",
            "Represent grammars as logic rules.",
            "Parse or generate structured language declaratively.",
            "Parser code is tangled with grammar rules.",
            "Encode productions as DCG clauses and let the engine thread input state.",
            "Excellent for symbolic parsing; may need cuts or constraints for performance.",
            &[
                "logic_programming",
                "declarative_programming",
                "formal_languages_and_automata",
            ],
            &["logic", "grammar"],
            "https://en.wikipedia.org/wiki/Definite_clause_grammar",
        ),
        pat(
            "tabling",
            "Tabling (Memoized Resolution)",
            "pattern",
            "logic",
            "Cache the answers to predicate calls so left-recursive and repeated queries terminate efficiently.",
            "Avoid infinite recursion and redundant work in declarative search.",
            "Naive SLD resolution loops on left-recursive grammars and re-derives sub-proofs repeatedly.",
            "Enable tabling on selected predicates (e.g., `:- table p/2.`) and reuse stored answers.",
            "Better termination and performance; tables consume memory and require dependency tracking.",
            &["logic_programming"],
            &["logic", "prolog", "memoization"],
            "https://www.swi-prolog.org/pldoc/man?section=tabling",
        ),
        pat(
            "meta_interpreter",
            "Meta-Interpreter",
            "pattern",
            "logic",
            "Write an interpreter for a logic language in itself to customize execution semantics.",
            "Add tracing, depth limits, or alternate strategies without changing the host engine.",
            "Standard resolution doesn't give access to control aspects you need (debugging, transformation).",
            "Define a `solve/1` predicate that recurses over goals, replacing built-in resolution.",
            "Powerful customization; meta-level performance is slower than native solving.",
            &["logic_programming"],
            &["logic", "prolog", "reflection"],
            "https://en.wikipedia.org/wiki/Meta-circular_evaluator",
        ),
        pat(
            "difference_lists",
            "Difference Lists",
            "pattern",
            "logic",
            "Represent a list as a pair of partial lists so concatenation is O(1).",
            "Avoid the O(n) cost of repeated list appending in Prolog.",
            "Right-folding append walks the prefix each time.",
            "Carry `(Front, Back)` and unify `Back` with the next list's `Front` for constant-time append.",
            "Efficient list construction; partial lists need careful handling.",
            &["logic_programming"],
            &["logic", "prolog", "performance"],
            "https://en.wikipedia.org/wiki/Difference_list",
        ),
        pat(
            "accumulator",
            "Accumulator Argument",
            "pattern",
            "logic",
            "Thread a running result through recursive calls so the base case returns it directly.",
            "Convert naturally-recursive predicates into tail-recursive ones.",
            "Direct recursion builds the result on the way back up, defeating last-call optimization.",
            "Add an accumulator parameter, build the result as you descend, and return it at the base case.",
            "Tail-recursive performance; result order may need a final reverse.",
            &["logic_programming", "functional_programming"],
            &["logic", "recursion"],
            "https://en.wikibooks.org/wiki/Prolog/Lists#Accumulators",
        ),
        pat(
            "negation_as_failure",
            "Negation as Failure",
            "pattern",
            "logic",
            "Treat goals that cannot be proved as false (closed-world assumption).",
            "Express negation without classical first-order logic.",
            "Pure logic programming lacks negation; some predicates need 'not provable' semantics.",
            "Use `\\+ Goal` (or `not(Goal)`) understood as 'fails iff Goal succeeds', under the closed-world assumption.",
            "Practical negation; differs from classical negation and depends on completeness.",
            &["logic_programming"],
            &["logic", "prolog", "semantics"],
            "https://en.wikipedia.org/wiki/Negation_as_failure",
        ),
        pat(
            "answer_set_programming",
            "Answer Set Programming (ASP)",
            "pattern",
            "logic",
            "Declarative paradigm where a problem is encoded as logic rules whose stable models are the solutions.",
            "Solve hard combinatorial problems (planning, scheduling, configuration) declaratively.",
            "Search-and-test is impractical and writing custom solvers is expensive.",
            "Encode constraints as rules in ASP (clingo, dlv); the grounder + solver enumerates stable models.",
            "Powerful for combinatorial domains; performance hinges on encoding and grounding size.",
            &["logic_programming", "declarative_programming"],
            &["logic", "asp", "combinatorial"],
            "https://en.wikipedia.org/wiki/Answer_set_programming",
        ),
        pat(
            "constraint_handling_rules",
            "Constraint Handling Rules (CHR)",
            "pattern",
            "logic",
            "Rule-based language for defining constraint solvers as rewriting rules on a constraint store.",
            "Implement custom constraint propagators and simplifiers declaratively.",
            "Hand-coded propagation algorithms duplicate generic rewriting machinery.",
            "Write propagation/simplification rules over a constraint store and let the CHR engine apply them.",
            "Concise solver definitions; performance and termination depend on rule design.",
            &["logic_programming", "declarative_programming"],
            &["logic", "constraints"],
            "https://en.wikipedia.org/wiki/Constraint_Handling_Rules",
        ),
        pat(
            "clp_fd",
            "CLP(FD) — Finite Domains",
            "pattern",
            "logic",
            "Constraint logic over finite-domain integer variables with propagation and labeling.",
            "Solve integer constraint problems (puzzles, scheduling) declaratively.",
            "Generate-and-test is too slow for any non-trivial domain.",
            "Declare domain bounds with `in`, post constraints with `#=`, `#<`, etc., then `label/1` to search.",
            "Combines declarative constraints with efficient propagation; behavior depends on labeling heuristics.",
            &["logic_programming", "declarative_programming"],
            &["logic", "constraints", "prolog"],
            "https://www.swi-prolog.org/pldoc/man?section=clpfd",
        ),
        pat(
            "cut_abuse",
            "Prolog Cut Abuse",
            "anti_pattern",
            "logic",
            "Using cut to force procedural control breaks declarative meaning.",
            "Keep logic programs relational and explainable.",
            "Cuts are inserted to patch performance or determinism without preserving semantics.",
            "Prefer mode-aware predicates, constraints, indexing, or well-scoped green cuts.",
            "Can improve performance; red cuts make queries brittle.",
            &["logic_programming"],
            &["antipattern", "prolog"],
            "https://www.metalevel.at/prolog",
        ),
        // ---------- Advanced FP / type theory ----------
        pat(
            "church_encoding",
            "Church Encoding",
            "pattern",
            "functional",
            "Encode data (booleans, numbers, pairs, lists) as functions in pure lambda calculus.",
            "Demonstrate that data is computation; foundation of CPS and tagless techniques.",
            "Untyped lambda calculus has no built-in data.",
            "Encode true = λxy.x; false = λxy.y; pair = λabf.f a b; numerals via repeated application.",
            "Theoretical foundation; impractical for everyday code but core to many compiler tricks.",
            &["functional_programming"],
            &["fp", "lambda_calculus", "theory"],
            "https://en.wikipedia.org/wiki/Church_encoding",
        ),
        pat(
            "defunctionalization",
            "Defunctionalization",
            "pattern",
            "functional",
            "Compile higher-order programs by replacing each function-typed value with an ADT tag and an apply function.",
            "Implement higher-order functions in first-order or limited-target languages.",
            "Languages without closures need a translation strategy.",
            "Replace lambdas with constructors of an ADT capturing their free variables; write a top-level `apply(tag, arg)` function.",
            "First-order, debuggable; loss of compositional convenience.",
            &["functional_programming"],
            &["fp", "compilation"],
            "https://en.wikipedia.org/wiki/Defunctionalization",
        ),
        pat(
            "codensity_transformation",
            "Codensity Transformation",
            "pattern",
            "functional",
            "Convert a monad to its codensity transform to make sequencing left-associated (avoids quadratic blowup of nested binds).",
            "Optimize free-monad-style programs that build with `>>=` heavily.",
            "Right-associated binds in free monads cost O(n²).",
            "Wrap programs in `Codensity m a = ∀r. (a -> m r) -> m r`; reverses associativity.",
            "Linear-time sequencing; type and conceptual overhead.",
            &["functional_programming"],
            &["fp", "category_theory"],
            "https://hackage.haskell.org/package/kan-extensions/docs/Control-Monad-Codensity.html",
        ),
        pat(
            "day_convolution",
            "Day Convolution",
            "pattern",
            "functional",
            "Construction that yields a free Applicative from two Functors.",
            "Build composable Applicative parsers/computations.",
            "Direct ad-hoc parser composition lacks lawful Applicative structure.",
            "Define `Day f g a = ∃b c. (b -> c -> a, f b, g c)`; this is the free applicative tensor.",
            "Lawful free constructions; pure theory until you build the right library.",
            &["functional_programming"],
            &["fp", "category_theory"],
            "https://hackage.haskell.org/package/kan-extensions/docs/Data-Functor-Day.html",
        ),
        pat(
            "indexed_monad",
            "Indexed Monad",
            "pattern",
            "functional",
            "A monad whose type tracks an effect-state index that changes through computation.",
            "Encode pre/post state machines (file open/close, transactional state) in types.",
            "Plain monads can't reflect state transitions in their type.",
            "Define `IxMonad m :: i -> j -> a -> Type` with bind that threads indices; use for protocol-correctness types.",
            "Compile-time protocol safety; type machinery is heavier.",
            &["functional_programming"],
            &["fp", "types"],
            "https://en.wikibooks.org/wiki/Haskell/Indexed_monad",
        ),
        pat(
            "selective_functor",
            "Selective Functor",
            "pattern",
            "functional",
            "Between Applicative and Monad: supports static analysis of conditional branches.",
            "Optimize effects when branching choices can be determined ahead of time.",
            "Applicative is too rigid; Monad makes static analysis impossible.",
            "Implement `select :: f (Either a b) -> f (a -> b) -> f b`; both branches' shape is known statically.",
            "Useful for build systems / planning; less expressive than Monad.",
            &["functional_programming"],
            &["fp", "category_theory"],
            "https://blogs.ncl.ac.uk/andreymokhov/selective/",
        ),
        pat(
            "coyoneda",
            "Coyoneda",
            "pattern",
            "functional",
            "Suspend `fmap` calls so a Functor can be derived for any type by deferred mapping.",
            "Make a non-Functor type usable as a Functor in algorithms.",
            "Some structures aren't easily made into Functors directly.",
            "Encode `Coyoneda f a = ∃b. (b -> a, f b)`; later `lowerCoyoneda` runs the deferred map.",
            "Free Functor; mostly a building-block in library code.",
            &["functional_programming"],
            &["fp", "category_theory"],
            "https://en.wikipedia.org/wiki/Yoneda_lemma",
        ),
        pat(
            "zipper",
            "Zipper",
            "pattern",
            "functional",
            "Functional data structure for navigating and locally updating a recursive structure.",
            "Allow O(1) updates at the focus and bidirectional movement.",
            "Persistent updates traverse from the root each time.",
            "Represent a tree as (focused subtree, breadcrumb path); move up/left/right preserves O(1) edits.",
            "Efficient focused edits; not necessarily simpler for many use cases.",
            &["functional_programming"],
            &["fp", "data_structure"],
            "https://en.wikipedia.org/wiki/Zipper_(data_structure)",
        ),
        pat(
            "apomorphism",
            "Apomorphism",
            "pattern",
            "functional",
            "Dual of paramorphism: unfold with the ability to short-circuit by emitting a pre-built subtree.",
            "Construct structures where some branches are already known.",
            "Plain anamorphisms can't stop building partway.",
            "Use `apo :: (a -> F (Either (Fix F) a)) -> a -> Fix F`; Left fragments stop recursion.",
            "Compositional builders with early termination; recursion-scheme machinery required.",
            &["functional_programming"],
            &["fp", "recursion_schemes"],
            "https://hackage.haskell.org/package/recursion-schemes",
        ),
        pat(
            "futumorphism",
            "Futumorphism",
            "pattern",
            "functional",
            "Anamorphism variant that can build multiple levels of the result in one step.",
            "Express generators that produce structured chunks rather than one layer at a time.",
            "Plain anamorphism builds layer-by-layer, which is awkward for some grammars.",
            "Use `futu :: (a -> F (Free F a)) -> a -> Fix F`; Free trees encode 'output now / recurse later'.",
            "Powerful; rarely needed outside DSL/compilers.",
            &["functional_programming"],
            &["fp", "recursion_schemes"],
            "https://hackage.haskell.org/package/recursion-schemes",
        ),
        pat(
            "mutual_recursion_fix",
            "Mutual Recursion via Fix",
            "pattern",
            "functional",
            "Express mutually recursive functions as a fixed point of a record of functions.",
            "Decouple mutual definitions for refactoring or memoization.",
            "Mutually recursive functions are normally tightly coupled.",
            "Define a record `Self = { f: A → B, g: B → A }`; build with `fix(λself. { f: ..self.g.., g: ..self.f.. })`.",
            "Refactorable, memoizable; loses some compiler optimizations.",
            &["functional_programming"],
            &["fp", "recursion"],
            "https://en.wikipedia.org/wiki/Fixed-point_combinator",
        ),
        pat(
            "hughes_lists",
            "Hughes Lists (DiffList)",
            "pattern",
            "functional",
            "Represent lists as functions `[a] -> [a]` so concatenation is O(1) function composition.",
            "Avoid O(n²) repeated appends.",
            "Right-associated `++` on linked lists is O(n²) overall.",
            "Wrap with `DList a = ([a] -> [a])`; cons = (x:); append = (.); convert to list via `($ [])`.",
            "O(n) total construction; needs final toList call.",
            &["functional_programming"],
            &["fp", "data_structure"],
            "https://hackage.haskell.org/package/dlist",
        ),
    ]
}
