//! Gang of Four design patterns and classic object-oriented patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- GoF: Creational ----------
        pat(
            "singleton",
            "Singleton",
            "pattern",
            "creational",
            "Ensure one shared instance with a global access point.",
            "Coordinate a genuinely unique resource.",
            "Multiple instances would violate correctness or waste scarce resources.",
            "Hide construction behind a controlled accessor and make lifetime explicit.",
            "Easy access but high coupling; avoid using it as ambient mutable state.",
            &["object_oriented_programming"],
            &["gof", "creational", "global_state"],
            "https://en.wikipedia.org/wiki/Singleton_pattern",
        ),
        pat(
            "factory_method",
            "Factory Method",
            "pattern",
            "creational",
            "Let subclasses or collaborators choose concrete products behind a stable creation interface.",
            "Decouple object creation from object use.",
            "Clients know an abstraction but not the concrete type to instantiate.",
            "Move creation into an overridable method or factory interface.",
            "Improves extension points; can add indirection if product families are simple.",
            &["object_oriented_programming"],
            &["gof", "creational"],
            "https://en.wikipedia.org/wiki/Factory_method_pattern",
        ),
        pat(
            "abstract_factory",
            "Abstract Factory",
            "pattern",
            "creational",
            "Create related object families without naming concrete classes.",
            "Keep product families consistent.",
            "A system must switch between families of compatible products.",
            "Expose a factory interface with creation methods for each product role.",
            "Useful for platform/product families; heavier than a single factory.",
            &["object_oriented_programming"],
            &["gof", "creational"],
            "https://en.wikipedia.org/wiki/Abstract_factory_pattern",
        ),
        pat(
            "builder",
            "Builder",
            "pattern",
            "creational",
            "Separate complex object construction from representation.",
            "Make construction explicit and readable.",
            "Constructors or factories have too many optional or ordered parameters.",
            "Accumulate configuration through a builder and validate at build time.",
            "Improves clarity; may be unnecessary for small immutable values.",
            &["object_oriented_programming"],
            &["gof", "creational"],
            "https://en.wikipedia.org/wiki/Builder_pattern",
        ),
        pat(
            "prototype",
            "Prototype",
            "pattern",
            "creational",
            "Create new objects by copying a configured exemplar.",
            "Avoid repeated complex initialization.",
            "New instances resemble existing ones more than fixed classes.",
            "Clone or copy a prototype and vary the small part that changes.",
            "Good for configured objects; copy semantics must be clear.",
            &["object_oriented_programming"],
            &["gof", "creational"],
            "https://en.wikipedia.org/wiki/Prototype_pattern",
        ),
        // ---------- GoF: Structural ----------
        pat(
            "adapter",
            "Adapter",
            "pattern",
            "structural",
            "Convert one interface into another expected by clients.",
            "Integrate incompatible abstractions without changing either side.",
            "A useful component exposes the wrong interface for the caller.",
            "Wrap it with a translation layer implementing the expected contract.",
            "Keeps boundaries clean; can hide impedance mismatch costs.",
            &["object_oriented_programming", "procedural_programming"],
            &["gof", "structural", "integration"],
            "https://en.wikipedia.org/wiki/Adapter_pattern",
        ),
        pat(
            "bridge",
            "Bridge",
            "pattern",
            "structural",
            "Separate abstraction from implementation so both can vary independently.",
            "Avoid combinatorial subclass hierarchies.",
            "Two dimensions of variation are tangled in one inheritance tree.",
            "Move implementation behind a composed interface.",
            "Improves extensibility; requires careful naming of roles.",
            &["object_oriented_programming"],
            &["gof", "structural"],
            "https://en.wikipedia.org/wiki/Bridge_pattern",
        ),
        pat(
            "composite",
            "Composite",
            "pattern",
            "structural",
            "Treat individual objects and object groups uniformly.",
            "Represent recursive part-whole structures.",
            "Clients should not branch on leaf versus container behavior.",
            "Give leaves and composites a common interface.",
            "Natural for trees; can overgeneralize operations that only make sense for composites.",
            &["object_oriented_programming", "functional_programming"],
            &["gof", "structural", "tree"],
            "https://en.wikipedia.org/wiki/Composite_pattern",
        ),
        pat(
            "decorator",
            "Decorator",
            "pattern",
            "structural",
            "Add responsibilities dynamically by wrapping an object.",
            "Compose behavior without subclass explosion.",
            "Features need optional combinations at runtime.",
            "Implement the same interface and delegate to the wrapped component.",
            "Flexible composition; nested wrappers can obscure behavior.",
            &["object_oriented_programming", "functional_programming"],
            &["gof", "structural", "composition"],
            "https://en.wikipedia.org/wiki/Decorator_pattern",
        ),
        pat(
            "facade",
            "Facade",
            "pattern",
            "structural",
            "Provide a simple interface over a complex subsystem.",
            "Reduce coupling to subsystem internals.",
            "Clients must coordinate many low-level operations.",
            "Create a higher-level entry point for common workflows.",
            "Improves usability; can become a god interface if it grows without boundaries.",
            &["object_oriented_programming", "procedural_programming"],
            &["gof", "structural"],
            "https://en.wikipedia.org/wiki/Facade_pattern",
        ),
        pat(
            "flyweight",
            "Flyweight",
            "pattern",
            "structural",
            "Share fine-grained immutable state across many objects to reduce memory.",
            "Use sharing to support large numbers of similar objects efficiently.",
            "A program creates millions of small objects whose intrinsic state is largely duplicated.",
            "Extract shared intrinsic state into reusable flyweights and keep extrinsic state outside.",
            "Saves memory; clients must supply context explicitly and mutation becomes harder.",
            &["object_oriented_programming"],
            &["gof", "structural", "memory"],
            "https://en.wikipedia.org/wiki/Flyweight_pattern",
        ),
        pat(
            "proxy",
            "Proxy",
            "pattern",
            "structural",
            "Control access to another object through a stand-in.",
            "Add lazy loading, remote access, caching, or authorization around a target.",
            "The caller should not manage target lifecycle or access policy directly.",
            "Expose the same interface and mediate calls.",
            "Powerful boundary tool; can surprise callers if proxy semantics differ.",
            &["object_oriented_programming", "distributed_systems"],
            &["gof", "structural"],
            "https://en.wikipedia.org/wiki/Proxy_pattern",
        ),
        // ---------- GoF: Behavioral ----------
        pat(
            "chain_of_responsibility",
            "Chain of Responsibility",
            "pattern",
            "behavioral",
            "Pass a request through handlers until one handles it.",
            "Decouple senders from receivers.",
            "The responsible handler is context-dependent or extensible.",
            "Compose ordered handlers sharing a common request interface.",
            "Flexible pipelines; ordering and fall-through behavior must be explicit.",
            &["object_oriented_programming", "event_driven_programming"],
            &["gof", "behavioral", "pipeline"],
            "https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern",
        ),
        pat(
            "command",
            "Command",
            "pattern",
            "behavioral",
            "Encapsulate an operation as an object.",
            "Queue, log, undo, schedule, or parameterize requests.",
            "Callers need to treat actions as data.",
            "Represent each action with an execute contract and captured inputs.",
            "Enables history and dispatch; may add boilerplate for simple calls.",
            &["object_oriented_programming", "event_driven_programming"],
            &["gof", "behavioral"],
            "https://en.wikipedia.org/wiki/Command_pattern",
        ),
        pat(
            "interpreter",
            "Interpreter",
            "pattern",
            "behavioral",
            "Represent a small language by a class per grammar rule and an evaluation step.",
            "Evaluate sentences in a domain-specific language directly from its grammar.",
            "Repeated ad-hoc parsing of a recurring mini-language clutters code.",
            "Model each non-terminal as a class with an interpret(context) method composing children.",
            "Clear for tiny DSLs; verbose and slow for sizable grammars or performance-sensitive paths.",
            &["object_oriented_programming", "functional_programming"],
            &["gof", "behavioral", "dsl"],
            "https://en.wikipedia.org/wiki/Interpreter_pattern",
        ),
        pat(
            "iterator",
            "Iterator",
            "pattern",
            "behavioral",
            "Expose sequential access to a collection without revealing its representation.",
            "Decouple traversal from data structure.",
            "Clients need to walk a collection but should not depend on its layout.",
            "Provide a cursor object with next/hasNext (or equivalent) operations.",
            "Uniform traversal; allocation and lifetime of iterators must be clear.",
            &["object_oriented_programming", "functional_programming"],
            &["gof", "behavioral", "traversal"],
            "https://en.wikipedia.org/wiki/Iterator_pattern",
        ),
        pat(
            "mediator",
            "Mediator",
            "pattern",
            "behavioral",
            "Centralize complex many-to-many interactions in a single coordinator.",
            "Reduce direct coupling between colleagues that would otherwise reference each other.",
            "A web of objects communicate via direct references, producing combinatorial coupling.",
            "Let colleagues talk to a mediator that knows their roles and routes interactions.",
            "Lowers coupling; the mediator can become a god object if its protocol grows unbounded.",
            &["object_oriented_programming", "event_driven_programming"],
            &["gof", "behavioral", "coordination"],
            "https://en.wikipedia.org/wiki/Mediator_pattern",
        ),
        pat(
            "memento",
            "Memento",
            "pattern",
            "behavioral",
            "Capture and restore an object's internal state without exposing its representation.",
            "Support undo/checkpointing while preserving encapsulation.",
            "Saving state from outside forces a class to leak its internals.",
            "Have the originator produce an opaque memento and accept it back to restore.",
            "Keeps encapsulation; memento storage cost depends on snapshot size and frequency.",
            &["object_oriented_programming"],
            &["gof", "behavioral", "undo"],
            "https://en.wikipedia.org/wiki/Memento_pattern",
        ),
        pat(
            "observer",
            "Observer",
            "pattern",
            "behavioral",
            "Notify dependents when a subject changes.",
            "Keep producers independent of consumers.",
            "Multiple consumers react to state changes or events.",
            "Register observers and publish updates through a stable callback contract.",
            "Foundational for events; requires lifecycle and backpressure care.",
            &[
                "object_oriented_programming",
                "event_driven_programming",
                "reactive_programming",
            ],
            &["gof", "behavioral", "events"],
            "https://en.wikipedia.org/wiki/Observer_pattern",
        ),
        pat(
            "state",
            "State",
            "pattern",
            "behavioral",
            "Let an object alter its behavior when its internal state changes; the object appears to change class.",
            "Replace large conditional state machines with polymorphism.",
            "Behavior depends on a state field threaded through many conditionals.",
            "Model each state as an object that implements the same interface and transitions on events.",
            "Clean state machine; state explosion is possible if not bounded.",
            &["object_oriented_programming"],
            &["gof", "behavioral", "state_machine"],
            "https://en.wikipedia.org/wiki/State_pattern",
        ),
        pat(
            "strategy",
            "Strategy",
            "pattern",
            "behavioral",
            "Encapsulate interchangeable algorithms behind one interface.",
            "Vary behavior without branching or subclassing clients.",
            "A workflow needs different policy choices.",
            "Inject an algorithm object or function implementing the strategy contract.",
            "Excellent for testable policy variation; avoid one-class-per-branch ceremony.",
            &["object_oriented_programming", "functional_programming"],
            &["gof", "behavioral", "policy"],
            "https://en.wikipedia.org/wiki/Strategy_pattern",
        ),
        pat(
            "template_method",
            "Template Method",
            "pattern",
            "behavioral",
            "Fix algorithm structure while deferring selected steps.",
            "Reuse an invariant workflow with customizable hooks.",
            "Subclasses share order but differ in steps.",
            "Put the skeleton in a base operation and override hook methods.",
            "Can work well in frameworks; inheritance coupling can become rigid.",
            &["object_oriented_programming"],
            &["gof", "behavioral"],
            "https://en.wikipedia.org/wiki/Template_method_pattern",
        ),
        pat(
            "visitor",
            "Visitor",
            "pattern",
            "behavioral",
            "Add operations over an object structure without changing element classes.",
            "Separate algorithms from a stable type hierarchy.",
            "Many operations must traverse a fixed set of element types.",
            "Use double dispatch to route element types to visitor methods.",
            "Good for compilers/ASTs; awkward when element types change often.",
            &["object_oriented_programming"],
            &["gof", "behavioral"],
            "https://en.wikipedia.org/wiki/Visitor_pattern",
        ),
        pat(
            "null_object",
            "Null Object",
            "pattern",
            "behavioral",
            "Use a do-nothing object instead of null checks.",
            "Make absence safe and polymorphic.",
            "Callers repeatedly branch around missing collaborators.",
            "Provide an implementation with neutral behavior.",
            "Reduces conditionals; can hide missing-data bugs if overused.",
            &["object_oriented_programming"],
            &["behavioral", "defensive_design"],
            "https://en.wikipedia.org/wiki/Null_object_pattern",
        ),
        // ---------- Classic OO (post-GoF) ----------
        pat(
            "object_pool",
            "Object Pool",
            "pattern",
            "creational",
            "Reuse a bounded set of expensive objects through a checkout/return cycle.",
            "Amortize allocation cost for resources like sockets, threads, or large buffers.",
            "Constructing or destroying these objects is significantly slower than reusing them.",
            "Maintain a pool that lends idle instances and resets them on return.",
            "Lowers latency under load; pool sizing, leak detection, and state reset must be careful.",
            &["object_oriented_programming", "concurrent_programming"],
            &["creational", "performance", "lifecycle"],
            "https://en.wikipedia.org/wiki/Object_pool_pattern",
        ),
        pat(
            "lazy_initialization",
            "Lazy Initialization",
            "pattern",
            "creational",
            "Defer creation of an object or value until its first use.",
            "Avoid pay-up-front cost for resources that may never be needed.",
            "Eager construction wastes time/memory for rarely used dependencies.",
            "Initialize on first access, guarded for thread safety where required.",
            "Smoother startup; first access is slower and concurrency hazards must be handled.",
            &["object_oriented_programming", "concurrent_programming"],
            &["creational", "performance"],
            "https://en.wikipedia.org/wiki/Lazy_initialization",
        ),
        pat(
            "multiton",
            "Multiton",
            "pattern",
            "creational",
            "Maintain a bounded keyed map of singletons rather than just one.",
            "Coordinate one shared instance per logical key.",
            "Several disjoint contexts each need a controlled single instance.",
            "Look up by key in a registry that creates on demand and caches.",
            "Useful for per-tenant resources; the registry is itself a global and must be managed.",
            &["object_oriented_programming"],
            &["creational", "registry"],
            "https://en.wikipedia.org/wiki/Multiton_pattern",
        ),
        pat(
            "dependency_injection",
            "Dependency Injection",
            "pattern",
            "creational",
            "Supply collaborators to an object from the outside instead of letting it construct its own.",
            "Decouple usage from wiring; make replacement and testing trivial.",
            "Internal new-ing hard-codes implementations and blocks substitution.",
            "Accept dependencies via constructor, setter, or interface, assembled by an outside composer.",
            "Improves testability; container magic can obscure construction graphs.",
            &["object_oriented_programming"],
            &["wiring", "ioc", "testability"],
            "https://en.wikipedia.org/wiki/Dependency_injection",
        ),
        pat(
            "inversion_of_control",
            "Inversion of Control",
            "pattern",
            "creational",
            "Hand control of program flow to a framework or container rather than the application code calling out.",
            "Let infrastructure invoke domain code at well-defined extension points.",
            "Hard-coded call chains tie application logic to particular runtime wiring.",
            "Define interfaces the framework will call; let an outer composer assemble the application.",
            "Highly extensible; debugging can be harder because the entry path is not local.",
            &["object_oriented_programming"],
            &["wiring", "frameworks"],
            "https://en.wikipedia.org/wiki/Inversion_of_control",
        ),
        pat(
            "registry",
            "Registry",
            "pattern",
            "structural",
            "Use a well-known object that other objects use to find common services.",
            "Centralize lookup without making every collaborator a singleton.",
            "Many components need access to the same shared services or values.",
            "Provide a registry interface and consult it explicitly; prefer scoped registries.",
            "Useful integration seam; global registries can become hidden coupling points.",
            &["object_oriented_programming"],
            &["structural", "lookup"],
            "https://martinfowler.com/eaaCatalog/registry.html",
        ),
        pat(
            "extension_object",
            "Extension Object",
            "pattern",
            "structural",
            "Anticipate adding behavior to objects by letting clients query for typed extensions.",
            "Allow open-ended new capabilities without modifying the core type.",
            "A core class would need many new responsibilities that not all clients require.",
            "Expose getExtension(Type) on the core; clients cast or query supported extensions.",
            "Open for extension; discoverability and typing of available extensions can suffer.",
            &["object_oriented_programming"],
            &["structural", "extension"],
            "https://wiki.c2.com/?ExtensionObject",
        ),
        pat(
            "marker_interface",
            "Marker Interface",
            "pattern",
            "structural",
            "Use an empty interface to tag types with a property the runtime checks.",
            "Express a binary type-level fact without adding behavior.",
            "Some types should opt into a behavior controlled by reflection or generic code.",
            "Declare a method-less interface and check `instanceof` at the dispatch site.",
            "Lightweight tagging; modern languages prefer annotations or attributes that carry data.",
            &["object_oriented_programming"],
            &["structural", "tagging"],
            "https://en.wikipedia.org/wiki/Marker_interface_pattern",
        ),
        pat(
            "type_object",
            "Type Object",
            "pattern",
            "structural",
            "Model dynamic 'types' as instances of a Type class instead of as language-level subclasses.",
            "Allow types to be added at runtime without recompiling.",
            "Variation across instances would otherwise demand a new subclass for each kind.",
            "Give each instance a reference to a TypeObject describing its kind, with shared metadata and behavior.",
            "Highly extensible; dispatch is data-driven and may be slower than static dispatch.",
            &["object_oriented_programming"],
            &["structural", "metamodel"],
            "https://gameprogrammingpatterns.com/type-object.html",
        ),
        pat(
            "double_dispatch",
            "Double Dispatch",
            "pattern",
            "behavioral",
            "Dispatch a call based on the runtime types of two participants, not just one.",
            "Resolve method choice when behavior depends on a pair of types.",
            "Single dispatch forces ugly type checks on the second argument.",
            "Use Visitor-style accept/visit so the second type's class chooses the actual handler.",
            "Powerful for type-pair behavior; adds boilerplate proportional to type combinations.",
            &["object_oriented_programming"],
            &["behavioral", "dispatch"],
            "https://en.wikipedia.org/wiki/Double_dispatch",
        ),
        pat(
            "specification_oo",
            "Specification (OO)",
            "pattern",
            "behavioral",
            "Represent business rules as composable predicate objects.",
            "Make rules first-class so they can be combined, reused, and tested.",
            "Repeated ad-hoc boolean checks scatter business logic.",
            "Encapsulate each rule as a Specification with isSatisfiedBy and AND/OR/NOT combinators.",
            "Composable rules; can become over-engineered for simple checks.",
            &["object_oriented_programming"],
            &["behavioral", "rules"],
            "https://en.wikipedia.org/wiki/Specification_pattern",
        ),
    ]
}
