//! Language-specific patterns and idioms.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- C++ / Rust resource management ----------
        pat(
            "raii",
            "Resource Acquisition Is Initialization (RAII)",
            "pattern",
            "idiom",
            "Tie resource lifetime to object lifetime; acquisition in constructor, release in destructor.",
            "Guarantee deterministic cleanup of resources.",
            "Manual acquire/release is error-prone under exceptions/early returns.",
            "Wrap each resource in a class whose constructor acquires and destructor releases.",
            "Exception-safe resource management; only works in languages with deterministic destruction.",
            &["object_oriented_programming", "procedural_programming"],
            &["idiom", "cpp", "rust"],
            "https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization",
        ),
        pat(
            "smart_pointer",
            "Smart Pointer",
            "pattern",
            "idiom",
            "An object that owns or shares a heap-allocated value and cleans it up automatically.",
            "Eliminate manual `new`/`delete` cycles and ownership confusion.",
            "Raw pointers leak, double-free, and obscure ownership.",
            "Use `unique_ptr` for unique ownership, `shared_ptr` for shared, `weak_ptr` for non-owning links.",
            "Safer ownership; some reference-counting overhead.",
            &["object_oriented_programming"],
            &["idiom", "cpp", "rust"],
            "https://en.wikipedia.org/wiki/Smart_pointer",
        ),
        pat(
            "move_semantics",
            "Move Semantics",
            "pattern",
            "idiom",
            "Transfer ownership of resources without copying.",
            "Avoid expensive deep copies and clarify ownership transfer.",
            "Copy semantics duplicate large resources unnecessarily.",
            "Mark with `&&` (C++) or use `let x = move y` (Rust); old binding becomes invalid.",
            "Performant ownership transfer; understanding lvalue/rvalue (or borrow checker) takes effort.",
            &["object_oriented_programming"],
            &["idiom", "cpp", "rust"],
            "https://en.wikipedia.org/wiki/Move_assignment_operator",
        ),
        pat(
            "rule_of_zero",
            "Rule of Zero / Three / Five",
            "principle",
            "idiom",
            "If a class manages a resource, define copy/move/destructor as needed; otherwise none.",
            "Avoid resource leaks and double-frees from special-member confusion.",
            "Default-generated copy/move can do the wrong thing for resource-owning classes.",
            "Either depend on RAII members (Rule of Zero) or explicitly define all 5 (move/copy/destructor pair).",
            "Safer resource management; only relevant in languages with explicit copy/move/destructors.",
            &["object_oriented_programming"],
            &["idiom", "cpp"],
            "https://en.cppreference.com/w/cpp/language/rule_of_three",
        ),
        pat(
            "pimpl",
            "Pointer to Implementation (PIMPL)",
            "pattern",
            "idiom",
            "Hide implementation details behind a pointer to keep the public header stable and minimal.",
            "Achieve ABI stability and reduce compile-time coupling.",
            "Exposing implementation details in headers forces recompilation of all dependents on change.",
            "Forward-declare an `Impl` struct; hold a `unique_ptr<Impl>`; implement methods in the .cpp.",
            "Stable ABI and faster compiles; one extra allocation and indirection.",
            &["object_oriented_programming"],
            &["idiom", "cpp", "abi"],
            "https://en.cppreference.com/w/cpp/language/pimpl",
        ),
        pat(
            "crtp",
            "Curiously Recurring Template Pattern (CRTP)",
            "pattern",
            "idiom",
            "A class inherits from a template specialization parameterized on itself, enabling static polymorphism.",
            "Get polymorphic behavior at compile time without virtual dispatch.",
            "Virtual dispatch has indirection cost; macros are ugly.",
            "`class Derived : public Base<Derived> { ... };` and call self-pointer methods.",
            "Zero-cost polymorphism; template error messages can be intimidating.",
            &["object_oriented_programming"],
            &["idiom", "cpp"],
            "https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern",
        ),
        pat(
            "tag_dispatch",
            "Tag Dispatch",
            "pattern",
            "idiom",
            "Select between overloads using a tag type that encodes a category.",
            "Specialize generic code by trait/category without runtime cost.",
            "if-constexpr or type checks at runtime obscure dispatch.",
            "Define empty tag types; overload functions taking each tag; call with the appropriate tag at compile time.",
            "Clear compile-time dispatch; works in C++ and Rust traits.",
            &["object_oriented_programming", "functional_programming"],
            &["idiom", "cpp", "rust"],
            "https://en.cppreference.com/w/cpp/iterator/iterator_tags",
        ),
        // ---------- Rust ----------
        pat(
            "typestate_pattern",
            "Typestate",
            "pattern",
            "idiom",
            "Encode the state of an object in its type so invalid transitions are compile errors.",
            "Make state machines unrepresentable in the wrong state.",
            "Runtime state checks are easy to forget and don't catch misuse at compile time.",
            "Define one type per state; transitions consume `self` and return the next type.",
            "Strong static safety; type signatures grow.",
            &["functional_programming", "object_oriented_programming"],
            &["idiom", "rust"],
            "https://docs.rust-embedded.org/book/static-guarantees/typestate-programming.html",
        ),
        pat(
            "drop_idiom",
            "Drop Idiom (Rust)",
            "pattern",
            "idiom",
            "Implement `Drop` to release resources deterministically when a value goes out of scope.",
            "Get RAII semantics in Rust without manual cleanup.",
            "Manual close/release calls are easy to skip on early returns or panics.",
            "Implement `impl Drop for Foo { fn drop(&mut self) { ... } }`; never call `drop` explicitly except for early-release semantics.",
            "Deterministic cleanup; cleanup must be infallible (cannot return errors).",
            &["object_oriented_programming"],
            &["idiom", "rust"],
            "https://doc.rust-lang.org/std/ops/trait.Drop.html",
        ),
        pat(
            "interior_mutability",
            "Interior Mutability (Rust)",
            "pattern",
            "idiom",
            "Use `Cell`/`RefCell`/`Mutex`/`RwLock` to mutate data through a shared reference.",
            "Allow controlled mutation in otherwise-immutable contexts.",
            "Rust's borrow checker forbids `&mut` while `&` exists; some legitimate patterns need it.",
            "Pick the right cell: `Cell` for `Copy`, `RefCell` for single-threaded runtime borrows, `Mutex`/`RwLock` for multi-thread.",
            "Flexible mutation patterns; misuse panics at runtime (`RefCell`) or deadlocks (`Mutex`).",
            &["object_oriented_programming"],
            &["idiom", "rust"],
            "https://doc.rust-lang.org/book/ch15-05-interior-mutability.html",
        ),
        pat(
            "send_sync_bounds",
            "Send/Sync Bounds (Rust)",
            "principle",
            "idiom",
            "Mark types as `Send` (movable across threads) and `Sync` (shareable across threads) precisely.",
            "Let the compiler prove thread safety.",
            "Implicit thread safety is hard to verify; raw pointers and FFI defeat default inference.",
            "Implement or auto-derive Send/Sync; use `PhantomData` to control auto-derivation; require bounds in APIs.",
            "Compiler-enforced thread safety; understanding the rules takes time.",
            &["concurrent_programming"],
            &["idiom", "rust", "concurrency"],
            "https://doc.rust-lang.org/nomicon/send-and-sync.html",
        ),
        pat(
            "rust_newtype_idiom",
            "Newtype Idiom (Rust)",
            "pattern",
            "idiom",
            "Wrap a type in a one-field tuple struct to add type-level distinction and impl traits without orphan rules.",
            "Distinguish semantically-different values and add behavior to foreign types.",
            "Primitives lose meaning; you cannot add traits to types you don't own.",
            "Define `struct Meters(f64);`; implement the traits you need; expose only the operations that make sense.",
            "Type safety and trait extension; small wrapping overhead in code.",
            &["functional_programming", "object_oriented_programming"],
            &["idiom", "rust"],
            "https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#using-the-newtype-pattern-to-implement-external-traits-on-external-types",
        ),
        // ---------- Go ----------
        pat(
            "functional_options",
            "Functional Options (Go)",
            "pattern",
            "idiom",
            "Configure complex constructors via variadic options that mutate a builder/config.",
            "Avoid telescoping constructors and oversized arg lists.",
            "Go has no overloading or default arguments.",
            "Define `type Option func(*config)`; expose `WithX`/`WithY` constructors; accept `...Option` in the factory.",
            "Backward-compatible APIs; opaque options can hurt discoverability without docs.",
            &["procedural_programming"],
            &["idiom", "go"],
            "https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html",
        ),
        pat(
            "go_channels",
            "Channels & Select (Go)",
            "pattern",
            "idiom",
            "Communicate between goroutines via typed channels and multiplex with `select`.",
            "Implement CSP-style concurrency without explicit locks.",
            "Shared-memory concurrency in goroutines is unsafe by default.",
            "Use channels to pass data; `select` to await one of several operations; close channels to signal completion.",
            "Idiomatic concurrency; deadlocks on bad coordination remain possible.",
            &["concurrent_programming"],
            &["idiom", "go"],
            "https://go.dev/tour/concurrency/1",
        ),
        pat(
            "go_defer",
            "Defer (Go)",
            "pattern",
            "idiom",
            "Schedule a function call to run when the surrounding function returns.",
            "Ensure cleanup runs on every exit path.",
            "Manual cleanup after early returns or panics is error-prone.",
            "`defer file.Close()` immediately after acquisition; deferred calls run LIFO at function exit.",
            "Reliable cleanup; defers in tight loops add overhead.",
            &["procedural_programming"],
            &["idiom", "go"],
            "https://go.dev/blog/defer-panic-and-recover",
        ),
        pat(
            "go_empty_interface",
            "Empty Interface (Go)",
            "anti_pattern",
            "idiom",
            "Using `interface{}` (or `any`) as a catch-all type to avoid generics or proper typing.",
            "Recognize loss of type safety.",
            "Pre-generics Go forced `interface{}` for container-like code; habits persist.",
            "Prefer generics (Go 1.18+); add explicit types or interfaces where behavior matters.",
            "Type safety restored; some generic-free code legitimately uses `any`.",
            &["object_oriented_programming"],
            &["idiom", "go", "antipattern"],
            "https://golangspec.medium.com/empty-interface-on-go-89e5fed7c047",
        ),
        pat(
            "go_embedding",
            "Type Embedding (Go)",
            "pattern",
            "idiom",
            "Compose behavior by embedding one type in another and promoting its methods.",
            "Reuse behavior without inheritance.",
            "Go has no class inheritance; composition without method promotion is verbose.",
            "Embed a named type as an anonymous field; outer type can call promoted methods directly.",
            "Composition with delegation; method conflicts surface at compile time.",
            &["object_oriented_programming"],
            &["idiom", "go"],
            "https://go.dev/doc/effective_go#embedding",
        ),
        // ---------- Python ----------
        pat(
            "context_manager",
            "Context Manager (with-statement)",
            "pattern",
            "idiom",
            "Encapsulate setup/teardown in a `with`-compatible object using `__enter__`/`__exit__`.",
            "Make resource lifetime explicit and exception-safe.",
            "try/finally cleanup is verbose and easy to misuse.",
            "Implement `__enter__`/`__exit__`; or use `contextlib.contextmanager` decorator on a generator.",
            "Clean resource handling; context manager design requires symmetric cleanup.",
            &["procedural_programming", "object_oriented_programming"],
            &["idiom", "python"],
            "https://docs.python.org/3/library/contextlib.html",
        ),
        pat(
            "generator_function",
            "Generator Function",
            "pattern",
            "idiom",
            "Produce a sequence lazily using `yield` instead of building a list.",
            "Stream large/expensive data without materializing it.",
            "Building large lists wastes memory and forces upfront work.",
            "Replace list-building with `yield`; consumers iterate; pipelines compose with itertools.",
            "Streaming and composability; mind the single-use iteration semantics.",
            &["functional_programming", "procedural_programming"],
            &["idiom", "python", "fp"],
            "https://docs.python.org/3/glossary.html#term-generator",
        ),
        pat(
            "decorator_idiom",
            "Decorator (Python)",
            "pattern",
            "idiom",
            "Wrap a function/class with another that augments behavior, applied via `@decorator`.",
            "Add cross-cutting concerns (caching, logging, auth) without modifying the target.",
            "Repeating cross-cutting code inline scatters intent.",
            "Define a decorator function/class that returns the wrapped callable; apply with `@`; preserve metadata via `functools.wraps`.",
            "Composable cross-cutting; debugging through stacked decorators can be harder.",
            &["functional_programming", "aspect_oriented_programming"],
            &["idiom", "python"],
            "https://peps.python.org/pep-0318/",
        ),
        pat(
            "dunder_methods",
            "Dunder (Double-Underscore) Methods",
            "pattern",
            "idiom",
            "Implement protocol methods like `__iter__`, `__enter__`, `__len__`, `__eq__` so objects integrate with built-ins.",
            "Make user types behave like built-in types.",
            "Custom types lacking protocols can't be iterated, compared, or `with`-managed.",
            "Implement the dunder methods you need; honor the documented contracts (e.g., `__hash__` consistency).",
            "Idiomatic Python; subtle protocol pitfalls (e.g., `__eq__` without `__hash__`).",
            &["object_oriented_programming"],
            &["idiom", "python"],
            "https://docs.python.org/3/reference/datamodel.html",
        ),
        pat(
            "dataclass",
            "Dataclass / Pydantic Model",
            "pattern",
            "idiom",
            "Declare typed data records with automatic __init__, __eq__, __repr__.",
            "Eliminate boilerplate for value-oriented classes.",
            "Manual constructors and repr methods are noisy and easy to get wrong.",
            "Use `@dataclass` / Pydantic / attrs to declare fields with types and defaults; opt into immutability with `frozen=True`.",
            "Concise records; some runtime overhead vs hand-written classes.",
            &["object_oriented_programming"],
            &["idiom", "python"],
            "https://docs.python.org/3/library/dataclasses.html",
        ),
        // ---------- Java/Kotlin ----------
        pat(
            "companion_object",
            "Companion Object (Kotlin) / static (Java)",
            "pattern",
            "idiom",
            "Group factory methods and constants associated with a class type.",
            "Provide class-level utilities without losing OO encapsulation.",
            "Naked static utility classes detach from the type they support.",
            "Use `companion object` in Kotlin / static members in Java for factory/util/constants belonging to the type.",
            "Clear association of static members; can become an anti-pattern if it grows unbounded.",
            &["object_oriented_programming"],
            &["idiom", "kotlin", "java"],
            "https://kotlinlang.org/docs/object-declarations.html#companion-objects",
        ),
        pat(
            "kotlin_scope_functions",
            "Scope Functions (Kotlin)",
            "pattern",
            "idiom",
            "Use `let`, `run`, `with`, `apply`, `also` to operate on a value within a temporary scope.",
            "Reduce noise around configuration and conditional access.",
            "Repeating the same receiver name clutters configuration code.",
            "Pick the scope function by need: `apply` for builder-like config, `let` for null-safe transformation, etc.",
            "Concise code; overuse can confuse 'this'/'it' semantics.",
            &["object_oriented_programming"],
            &["idiom", "kotlin"],
            "https://kotlinlang.org/docs/scope-functions.html",
        ),
        pat(
            "kotlin_extension_function",
            "Extension Function (Kotlin)",
            "pattern",
            "idiom",
            "Add methods to existing types without modifying them or using inheritance.",
            "Augment foreign types ergonomically.",
            "Utility classes (`StringUtils.foo(s)`) read worse than `s.foo()`.",
            "Define `fun TargetType.foo() = ...` at the top level or in a class; call as `target.foo()`.",
            "Cleaner call sites; extension resolution is static (no virtual dispatch).",
            &["object_oriented_programming"],
            &["idiom", "kotlin"],
            "https://kotlinlang.org/docs/extensions.html",
        ),
        pat(
            "kotlin_sealed_class",
            "Sealed Class (Kotlin) / Sealed Interface",
            "pattern",
            "idiom",
            "Restrict subtypes of a class/interface to a known set.",
            "Get exhaustive `when` on a closed type hierarchy.",
            "Open hierarchies prevent exhaustive pattern matching.",
            "Declare `sealed class`/`sealed interface`; the compiler enforces that `when` cover all variants.",
            "Type-safe state modeling; only direct subclasses must live in the same module.",
            &["functional_programming", "object_oriented_programming"],
            &["idiom", "kotlin"],
            "https://kotlinlang.org/docs/sealed-classes.html",
        ),
        // ---------- Scala ----------
        pat(
            "scala_implicits",
            "Implicits / Givens (Scala)",
            "pattern",
            "idiom",
            "Pass arguments or define conversions that the compiler supplies based on type.",
            "Reduce boilerplate for type classes, contexts, and configuration.",
            "Threading typeclass instances or contexts manually is noisy.",
            "Use `implicit`/`given` parameters; design conversions cautiously; prefer named givens.",
            "Powerful abstraction; overuse hurts readability and breaks 'find usages'.",
            &["functional_programming", "object_oriented_programming"],
            &["idiom", "scala"],
            "https://docs.scala-lang.org/scala3/book/ca-given-using-clauses.html",
        ),
        pat(
            "scala_for_comprehension",
            "For-Comprehension (Scala)",
            "pattern",
            "idiom",
            "Sequencing monadic operations with `for { ... } yield` syntax.",
            "Make nested `flatMap`/`map` chains readable.",
            "Hand-rolled `flatMap` chains are noisy and obscure intent.",
            "Use `for (x <- m1; y <- m2(x)) yield f(x, y)` over any monad/functor.",
            "Imperative-looking syntax for monadic code; only desugars correctly for FlatMap-shaped types.",
            &["functional_programming"],
            &["idiom", "scala"],
            "https://docs.scala-lang.org/tour/for-comprehensions.html",
        ),
        // ---------- Erlang/Elixir (OTP) ----------
        pat(
            "otp_behaviour",
            "OTP Behaviour",
            "pattern",
            "idiom",
            "Implement standard process roles (gen_server, gen_statem, supervisor) by providing callbacks.",
            "Reuse battle-tested concurrency, fault-tolerance, and lifecycle machinery.",
            "Custom receive loops duplicate idiomatic Erlang behaviour and miss subtleties.",
            "Implement the callbacks defined by each behaviour; OTP supplies the driver loop and supervision.",
            "Robust concurrent services; behaviour learning curve.",
            &["actor_model", "concurrent_programming"],
            &["idiom", "erlang", "elixir", "otp"],
            "https://www.erlang.org/doc/design_principles/des_princ",
        ),
        pat(
            "elixir_pipe_operator",
            "Pipe Operator (Elixir)",
            "pattern",
            "idiom",
            "Pass the previous expression as the first argument to the next function via `|>`.",
            "Express data transformations as left-to-right pipelines.",
            "Nested function calls read right-to-left and obscure data flow.",
            "Chain transformations with `|>`; design functions to take the data as the first parameter.",
            "Readable pipelines; non-first-arg functions need wrapping.",
            &["functional_programming"],
            &["idiom", "elixir"],
            "https://elixir-lang.org/getting-started/enumerables-and-streams.html",
        ),
        // ---------- Ruby ----------
        pat(
            "ruby_mixin_module",
            "Mixin Module (Ruby)",
            "pattern",
            "idiom",
            "Share behavior across classes by including a module rather than inheriting.",
            "Compose orthogonal behaviors without single-inheritance constraints.",
            "Inheritance is single; behavior often spans multiple axes.",
            "Define a `module`; `include` it in classes that need its instance methods (or `extend` for class methods).",
            "Composable behavior; method lookup order can become surprising with many mixins.",
            &["object_oriented_programming"],
            &["idiom", "ruby"],
            "https://docs.ruby-lang.org/en/3.3/Module.html",
        ),
        pat(
            "ruby_block_yield",
            "Block / Yield (Ruby)",
            "pattern",
            "idiom",
            "Pass an anonymous block to a method which invokes it with `yield`.",
            "Inject behavior into iteration, resource management, or DSLs ergonomically.",
            "Function-pointer-style callbacks are verbose for short, inline behavior.",
            "Define methods that `yield`; callers pass a `do ... end` or `{ }` block.",
            "Highly readable callbacks; block semantics differ from proc/lambda.",
            &["object_oriented_programming", "functional_programming"],
            &["idiom", "ruby"],
            "https://docs.ruby-lang.org/en/3.3/syntax/methods_rdoc.html#label-Blocks",
        ),
        // ---------- JavaScript/TypeScript ----------
        pat(
            "destructuring_assignment",
            "Destructuring Assignment (JS/TS)",
            "pattern",
            "idiom",
            "Bind variables to fields of objects or elements of arrays in one expression.",
            "Make object/array unpacking concise and intentional.",
            "Repeated `const a = obj.a; const b = obj.b;` is noisy and easy to mistype.",
            "Use `const { a, b } = obj` or `const [first, ...rest] = arr`; provide defaults inline.",
            "Concise access; defaulting interacts subtly with `undefined`.",
            &["functional_programming"],
            &["idiom", "javascript", "typescript"],
            "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment",
        ),
        pat(
            "typescript_discriminated_union",
            "Discriminated Union (TS)",
            "pattern",
            "idiom",
            "Use a string literal tag on union members to enable exhaustive narrowing.",
            "Express ADT-like data with safe pattern matching.",
            "Plain TS unions don't narrow without explicit type guards.",
            "Add `kind: 'a' | 'b'`; switch on `kind`; let `never` enforce exhaustiveness via a default case.",
            "ADT ergonomics in TS; tags must be kept consistent across producers.",
            &["functional_programming"],
            &["idiom", "typescript"],
            "https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions",
        ),
        pat(
            "react_hooks_pattern",
            "React Hooks",
            "pattern",
            "idiom",
            "Express component state and lifecycle via composable functions called from function components.",
            "Reuse stateful logic across components without classes or HOCs.",
            "Class-based lifecycle methods and HOC chains entangle component code.",
            "Use built-in hooks (useState/useEffect/useMemo); write custom hooks for shared concerns; obey rules of hooks.",
            "Composable state logic; hook ordering and dependency arrays add discipline.",
            &["functional_programming", "reactive_programming"],
            &["idiom", "javascript", "react"],
            "https://react.dev/learn/escape-hatches",
        ),
        // ---------- Smalltalk / dynamic ----------
        pat(
            "method_missing",
            "method_missing / __getattr__ (Dynamic Dispatch)",
            "pattern",
            "idiom",
            "Handle unrecognized method calls by intercepting them.",
            "Implement dynamic proxies, DSLs, or remote method dispatch.",
            "Static methods can't express open-ended APIs (e.g., for `User#find_by_email`).",
            "Override `method_missing` (Ruby) / `__getattr__` (Python) / `doesNotUnderstand:` (Smalltalk); also override the introspection predicate.",
            "Highly expressive APIs; harder to debug, profile, and statically analyze.",
            &["object_oriented_programming"],
            &["idiom", "ruby", "python", "smalltalk"],
            "https://en.wikipedia.org/wiki/Method_(computer_programming)#Special_methods",
        ),
        pat(
            "duck_typing",
            "Duck Typing",
            "pattern",
            "idiom",
            "Treat objects by what they can do, not what they are.",
            "Decouple consumers from concrete types in dynamic languages.",
            "Strict type checks limit polymorphism in languages without trait/interface systems.",
            "Accept any object with the required methods; document expectations; rely on tests.",
            "Flexible polymorphism; relies on testing to catch misuse.",
            &["object_oriented_programming"],
            &["idiom", "python", "ruby"],
            "https://en.wikipedia.org/wiki/Duck_typing",
        ),
        // ---------- Other ----------
        pat(
            "multiple_dispatch",
            "Multiple Dispatch",
            "pattern",
            "idiom",
            "Select a function implementation by the runtime types of all arguments.",
            "Express type-pair (or n-ary) behavior without Visitor boilerplate.",
            "Single-dispatch languages force awkward type-check chains for n-ary behavior.",
            "Use a language with native multimethods (Julia, CLOS, Clojure) or simulate with type-tag dispatch.",
            "Expressive type-aware behavior; static analysis is harder than single-dispatch.",
            &["functional_programming", "object_oriented_programming"],
            &["idiom", "julia", "clos", "clojure"],
            "https://en.wikipedia.org/wiki/Multiple_dispatch",
        ),
        pat(
            "haskell_typeclass_pattern",
            "Haskell Type Class Idiom",
            "pattern",
            "idiom",
            "Define ad-hoc polymorphism via type classes with laws (Functor, Monad, Show, ...).",
            "Get extensible, principled polymorphism without inheritance.",
            "OOP-style interfaces require modifying the type definition to add behavior.",
            "Declare classes with method signatures and laws; provide instances per type; rely on type inference.",
            "Highly compositional polymorphism; instance resolution rules require discipline.",
            &["functional_programming"],
            &["idiom", "haskell"],
            "https://www.haskell.org/tutorial/classes.html",
        ),
        pat(
            "haskell_do_notation",
            "Do-Notation (Haskell)",
            "pattern",
            "idiom",
            "Sequence monadic computations with imperative-looking `do` blocks.",
            "Make monadic code readable.",
            "Chains of `>>=` and `>>` are noisy for sequenced effects.",
            "Use `do { x <- m1; y <- m2 x; return (f x y) }`; obeys monad laws.",
            "Familiar syntax for sequencing effects; remember it's just sugar for bind.",
            &["functional_programming"],
            &["idiom", "haskell"],
            "https://en.wikibooks.org/wiki/Haskell/do_notation",
        ),
        pat(
            "lisp_macro",
            "Lisp Macro",
            "pattern",
            "idiom",
            "Extend the language with new syntactic forms that expand at compile time.",
            "Capture syntactic patterns the host language doesn't provide.",
            "Repetitive boilerplate can't be removed by ordinary functions.",
            "Define a macro with `defmacro`/`define-syntax`; expand carefully (hygiene); test the expanded forms.",
            "Highly expressive; macros add complexity to readers and tooling.",
            &["functional_programming"],
            &["idiom", "lisp", "clojure", "scheme"],
            "https://en.wikipedia.org/wiki/Macro_(computer_science)",
        ),
        pat(
            "shell_pipeline",
            "Shell Pipeline",
            "pattern",
            "idiom",
            "Compose small programs into pipelines via stdin/stdout.",
            "Build ad-hoc data processing from reusable, single-purpose tools.",
            "Custom one-off scripts duplicate functionality the shell already provides.",
            "Connect commands with `|`; lean on coreutils (`grep`, `awk`, `jq`); handle errors with `set -euo pipefail`.",
            "Powerful and reusable; shell quoting and signal handling are surprisingly subtle.",
            &["dataflow_programming"],
            &["idiom", "shell", "unix"],
            "https://en.wikipedia.org/wiki/Pipeline_(Unix)",
        ),
        pat(
            "memoization_decorator",
            "Memoization Decorator",
            "pattern",
            "idiom",
            "Decorate a pure function with a cache to avoid recomputation.",
            "Trade memory for time on repeated identical calls.",
            "Recomputation of pure functions wastes cycles.",
            "Use `functools.lru_cache` (Python), memo packages in other ecosystems; ensure inputs are hashable and the function is pure.",
            "Easy speedups; cache invalidation/bounding matters in long-running processes.",
            &["functional_programming"],
            &["idiom", "python"],
            "https://docs.python.org/3/library/functools.html#functools.lru_cache",
        ),
        pat(
            "result_chain",
            "Result Chain (Try/Result `?` Operator)",
            "pattern",
            "idiom",
            "Propagate errors via early-exit on `Result`/`Either` using a dedicated operator.",
            "Eliminate nested `match`/`if let` cascades for error handling.",
            "Manual error propagation produces deeply nested code.",
            "Use Rust's `?` (Swift's `try`, OCaml's `let*`, JS `try/catch`); unwrap success, propagate failure.",
            "Linear happy-path; type conversions for unified error type may be needed.",
            &["functional_programming"],
            &["idiom", "rust", "swift"],
            "https://doc.rust-lang.org/std/result/#the-question-mark-operator-",
        ),
        pat(
            "iterator_invalidation_aware",
            "Iterator Invalidation Awareness",
            "principle",
            "idiom",
            "Avoid mutating a container while iterating over it in a way that invalidates iterators.",
            "Prevent undefined behavior, panics, or skipped elements.",
            "Adding/removing during iteration silently corrupts traversal in many languages.",
            "Collect indices/keys first, mutate after; use language-provided safe-iteration APIs (`retain`, `removeIf`).",
            "Stable iteration; some operations require an explicit two-pass design.",
            &["procedural_programming", "object_oriented_programming"],
            &["idiom", "cpp", "rust", "java"],
            "https://en.cppreference.com/w/cpp/container#Iterator_invalidation",
        ),
        pat(
            "raii_lock_guard",
            "RAII Lock Guard",
            "pattern",
            "idiom",
            "Wrap a lock in a scoped guard that acquires on construction and releases on destruction.",
            "Guarantee lock release on every exit path.",
            "Manual lock/unlock leaks on early return or exception.",
            "Use `std::lock_guard`/`std::unique_lock` (C++), `MutexGuard` (Rust), `synchronized` block (Java).",
            "Exception/panic-safe critical sections; works only where deterministic destruction exists.",
            &["concurrent_programming"],
            &["idiom", "cpp", "rust"],
            "https://en.cppreference.com/w/cpp/thread/lock_guard",
        ),
        pat(
            "haskell_record_syntax",
            "Record Syntax with Update",
            "pattern",
            "idiom",
            "Define product types with named fields and update with `r { field = new }`.",
            "Avoid positional confusion in large records.",
            "Positional construction is brittle and error-prone.",
            "Use record syntax; combine with smart constructors for invariants; consider lenses for nested update.",
            "Readable construction/update; positional vs named confusion can creep in.",
            &["functional_programming"],
            &["idiom", "haskell"],
            "https://en.wikibooks.org/wiki/Haskell/More_on_datatypes",
        ),
        // ---------- C++20 features ----------
        pat(
            "cpp20_concepts",
            "Concepts (C++20)",
            "pattern",
            "idiom",
            "Constrain template parameters with named predicates instead of SFINAE.",
            "Get readable template constraints and clear error messages.",
            "SFINAE-based constraints are arcane and produce cryptic errors.",
            "Define `concept Foo = requires(T t) { ... };` and use `template<Foo T>` or `requires` clauses.",
            "Readable generic code; requires C++20 + recent compilers.",
            &["object_oriented_programming"],
            &["idiom", "cpp"],
            "https://en.cppreference.com/w/cpp/language/constraints",
        ),
        pat(
            "cpp20_coroutines",
            "Coroutines (C++20)",
            "pattern",
            "idiom",
            "Functions can suspend and resume via `co_await`, `co_yield`, `co_return`.",
            "Express async code and generators without callback chains.",
            "Pre-C++20 async required hand-coded state machines or callbacks.",
            "Author with `co_await` futures; use a coroutine library (cppcoro) until std::coroutine is fully fleshed.",
            "Powerful async style; standard support still developing.",
            &["object_oriented_programming", "functional_programming"],
            &["idiom", "cpp", "async"],
            "https://en.cppreference.com/w/cpp/language/coroutines",
        ),
        pat(
            "cpp20_modules",
            "Modules (C++20)",
            "pattern",
            "idiom",
            "Replace `#include` with an actual module system supporting export/import semantics.",
            "Drop compile times and enforce real encapsulation.",
            "Header-based compilation is slow and macros leak.",
            "Define module units with `export module foo;` and `import foo;`; build with module-aware tooling.",
            "Faster compiles, real boundaries; ecosystem support still maturing.",
            &["object_oriented_programming"],
            &["idiom", "cpp"],
            "https://en.cppreference.com/w/cpp/language/modules",
        ),
        pat(
            "cpp_span",
            "std::span / View Types",
            "pattern",
            "idiom",
            "Non-owning view over a contiguous sequence (pointer + size).",
            "Pass arrays/vectors/buffers without copies and without coupling to the container type.",
            "`std::vector&`/`T*+size` are noisy and inflexible.",
            "Use `std::span<T>` (C++20); analogous to Rust `&[T]`; never own the underlying storage.",
            "Clean array APIs; lifetime discipline crucial.",
            &["object_oriented_programming"],
            &["idiom", "cpp"],
            "https://en.cppreference.com/w/cpp/container/span",
        ),
        pat(
            "sfinae",
            "SFINAE",
            "pattern",
            "idiom",
            "Substitution Failure Is Not An Error: template specializations that fail to substitute are ignored, enabling compile-time dispatch.",
            "Enable type-trait based overloading before Concepts.",
            "Pre-C++20 had no direct way to constrain templates.",
            "Use `std::enable_if_t`, `void_t`, detection idiom; prefer Concepts when available.",
            "Powerful but cryptic; obsoleted by Concepts.",
            &["object_oriented_programming"],
            &["idiom", "cpp"],
            "https://en.cppreference.com/w/cpp/language/sfinae",
        ),
        pat(
            "empty_base_optimization",
            "Empty Base Optimization (EBO)",
            "pattern",
            "idiom",
            "Empty base classes occupy no space in derived class layouts (a C++ rule).",
            "Allow zero-sized policy classes via inheritance.",
            "Composition with empty types still costs at least 1 byte per member.",
            "Inherit privately from empty policy classes; let the compiler optimize the layout.",
            "Zero-cost policy types; only applies when inherited from, not composed.",
            &["object_oriented_programming"],
            &["idiom", "cpp"],
            "https://en.cppreference.com/w/cpp/language/ebo",
        ),
        pat(
            "strong_typedef",
            "Strong Typedef (Tagged Alias)",
            "pattern",
            "idiom",
            "Create a type that is structurally identical to another but not implicitly convertible.",
            "Get the type safety of newtype in languages where `typedef` is an alias.",
            "C/C++ typedefs don't create new types — primitive obsession survives.",
            "Use `struct Meters { double v; };` (C++) or `std::strong_typedef` libraries; expose only operations that make domain sense.",
            "Type safety; some boilerplate.",
            &["object_oriented_programming"],
            &["idiom", "cpp", "rust"],
            "https://www.foonathan.net/2016/10/strong-typedefs/",
        ),
        // ---------- JS/TS modern idioms ----------
        pat(
            "top_level_await",
            "Top-Level Await",
            "pattern",
            "idiom",
            "Use `await` at the top of an ES module without wrapping in an async function.",
            "Simplify async initialization in module scope.",
            "Pre-ESM required IIFEs `(async () => {...})()` for top-level async.",
            "In an ES module, `const x = await fetchConfig();` works directly; dependents are loaded after.",
            "Cleaner initialization; affects module instantiation order.",
            &["functional_programming"],
            &["idiom", "javascript", "typescript"],
            "https://v8.dev/features/top-level-await",
        ),
        pat(
            "optional_chaining_nullish",
            "Optional Chaining + Nullish Coalescing",
            "pattern",
            "idiom",
            "`a?.b?.c` short-circuits on null/undefined; `a ?? b` returns `b` only when `a` is null/undefined.",
            "Safely traverse and default optional values.",
            "Manual `&&` guards are noisy; `||` confuses 0/'' with absence.",
            "Use `obj?.prop?.method?.()` for access; `val ?? fallback` for defaults distinct from falsy.",
            "Concise; loose-equality-to-null still applies to `??`.",
            &["functional_programming"],
            &["idiom", "javascript", "typescript"],
            "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining",
        ),
        pat(
            "tagged_template_literal",
            "Tagged Template Literals",
            "pattern",
            "idiom",
            "Function tags template strings, receiving raw strings and interpolated values.",
            "Build safe DSLs (HTML escaping, SQL parameter binding, styled-components).",
            "Plain template strings allow injection bugs.",
            "Define a tag function `html` `` html`<p>${user}</p>` `` that escapes interpolations.",
            "Safe-by-construction DSLs; usage convention required.",
            &["functional_programming"],
            &["idiom", "javascript", "typescript", "dsl"],
            "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates",
        ),
        pat(
            "js_iterable_protocol",
            "Symbol.iterator (Iterable Protocol)",
            "pattern",
            "idiom",
            "Implement `[Symbol.iterator]()` to make a value participate in `for..of`, spread, destructuring.",
            "Provide custom iteration for user types.",
            "Without the protocol, types can't integrate with iteration syntax.",
            "Return an object with `next()` returning `{value, done}`; or define a generator function as the iterator.",
            "Idiomatic JS; lazy by default.",
            &["functional_programming"],
            &["idiom", "javascript", "typescript"],
            "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols",
        ),
        // ---------- Python modern idioms ----------
        pat(
            "python_walrus",
            "Walrus Operator (:=)",
            "pattern",
            "idiom",
            "Assignment expression that binds a name within a larger expression.",
            "Avoid duplicate computation in conditions/comprehensions.",
            "Patterns like `while (chunk := f.read()): ...` previously required clunky structure.",
            "Use `:=` inside `if`, `while`, comprehensions to bind once and use in the predicate and body.",
            "Concise; over-use can hurt readability.",
            &["procedural_programming"],
            &["idiom", "python"],
            "https://peps.python.org/pep-0572/",
        ),
        pat(
            "python_match_statement",
            "Match Statement (Structural Pattern Matching)",
            "pattern",
            "idiom",
            "PEP 634 structural pattern matching with cases over class shapes, sequences, and mappings.",
            "Express case-by-class destructuring cleanly.",
            "Long `isinstance` / `if/elif` chains over types are noisy.",
            "Use `match obj: case Point(x=0, y=y): ...`; supports guards via `if`; class match works with `__match_args__`.",
            "ADT-style ergonomics; Python ≥ 3.10 required.",
            &["functional_programming", "object_oriented_programming"],
            &["idiom", "python"],
            "https://peps.python.org/pep-0634/",
        ),
        pat(
            "python_async_iterator",
            "Python Async Iterator (PEP 525)",
            "pattern",
            "idiom",
            "Async generators producing values across `await` boundaries.",
            "Stream values from async I/O in a Pythonic loop.",
            "Manual queues / callbacks make async streaming clumsy.",
            "Define `async def gen(): yield ...`; consume with `async for x in gen():`.",
            "Async streaming; only inside `async` contexts.",
            &["functional_programming"],
            &["idiom", "python", "async"],
            "https://peps.python.org/pep-0525/",
        ),
    ]
}
