//! Kubernetes and cloud-native patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        pat(
            "operator_pattern",
            "Operator Pattern",
            "pattern",
            "kubernetes",
            "Encode operational knowledge for a stateful application in a custom controller that watches CRDs and reconciles state.",
            "Automate complex day-2 operations (failover, backup, scale) declaratively.",
            "Stateful systems (DBs, message queues) need bespoke ops that don't fit generic controllers.",
            "Define CRDs; write a controller that reconciles desired vs observed; package as Helm/OLM; consume via Kubernetes API.",
            "Powerful automation; correctness of the controller is critical.",
            &["distributed_systems"],
            &["kubernetes", "controller"],
            "https://kubernetes.io/docs/concepts/extend-kubernetes/operator/",
        ),
        pat(
            "custom_resource_definition",
            "Custom Resource Definition (CRD)",
            "pattern",
            "kubernetes",
            "Extend the Kubernetes API with domain types via YAML schemas.",
            "Make domain objects first-class kubectl-manageable resources.",
            "Configuration outside Kubernetes drifts and isn't auditable.",
            "Author a CRD YAML with OpenAPI schema; install in cluster; users `kubectl apply` instances; controller reconciles.",
            "Native API for domain objects; schema versioning needs upgrade handling.",
            &["distributed_systems", "declarative_programming"],
            &["kubernetes"],
            "https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/",
        ),
        pat(
            "init_container",
            "Init Container",
            "pattern",
            "kubernetes",
            "One or more containers that run to completion before the main containers start in a Pod.",
            "Perform pre-start setup (config fetch, schema check, fixture data).",
            "Doing setup inside the main container conflates startup with running concerns.",
            "Declare initContainers in the Pod spec; they run sequentially; main containers wait until all complete.",
            "Clean separation; serial init can add startup latency.",
            &["distributed_systems"],
            &["kubernetes", "pod"],
            "https://kubernetes.io/docs/concepts/workloads/pods/init-containers/",
        ),
        pat(
            "adapter_container",
            "Adapter Container",
            "pattern",
            "kubernetes",
            "A sidecar that normalizes the main container's output into a standard format (logs, metrics).",
            "Bring legacy services into a uniform observability surface without modifying them.",
            "Main containers emit varied formats that monitoring can't consume.",
            "Deploy an adapter sidecar that reads logs/metrics from the main; normalizes them; exports.",
            "Uniform telemetry; sidecar resource overhead.",
            &["distributed_systems"],
            &["kubernetes", "sidecar"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/ambassador",
        ),
        pat(
            "pod_disruption_budget",
            "Pod Disruption Budget (PDB)",
            "pattern",
            "kubernetes",
            "Declare the minimum number of pods that must remain available during voluntary disruptions.",
            "Survive node drains, upgrades, scale-downs without losing quorum.",
            "Voluntary disruptions can simultaneously evict a quorum of replicas.",
            "Create a PDB with `minAvailable` or `maxUnavailable`; eviction respects the budget; cluster ops queue.",
            "Safer upgrades; misconfig can block legitimate drains indefinitely.",
            &["distributed_systems"],
            &["kubernetes", "availability"],
            "https://kubernetes.io/docs/concepts/workloads/pods/disruptions/",
        ),
        pat(
            "horizontal_pod_autoscaler",
            "Horizontal Pod Autoscaler (HPA)",
            "pattern",
            "kubernetes",
            "Scale replica count up/down based on CPU, memory, or custom metrics.",
            "Match capacity to demand automatically.",
            "Fixed replica counts over- or under-provision under variable load.",
            "Define HPA with metric targets; controller adjusts replica count; combine with custom-metrics adapter for app-level signals.",
            "Cost-efficient elasticity; metrics quality and minReplicas/maxReplicas bounds matter.",
            &["distributed_systems"],
            &["kubernetes", "autoscaling"],
            "https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/",
        ),
        pat(
            "vertical_pod_autoscaler",
            "Vertical Pod Autoscaler (VPA)",
            "pattern",
            "kubernetes",
            "Recommend or apply right-sized CPU/memory requests for pods based on usage.",
            "Avoid manual right-sizing of resource requests.",
            "Hand-tuned requests drift from actual usage, causing waste or evictions.",
            "Deploy the VPA controller in `recommend` or `auto` mode; apply suggested requests; combine carefully with HPA.",
            "Better packing; auto-mode triggers pod restarts.",
            &["distributed_systems"],
            &["kubernetes", "autoscaling"],
            "https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler",
        ),
        pat(
            "cluster_autoscaler",
            "Cluster Autoscaler",
            "pattern",
            "kubernetes",
            "Add/remove worker nodes based on unschedulable pods and idle capacity.",
            "Match cluster size to workload without manual node management.",
            "Static node counts either waste money or starve workloads.",
            "Run the autoscaler controller; integrate with cloud node-pools; configure min/max; ensure pod requests are accurate.",
            "Cost elasticity; scale-up latency depends on cloud and image pulls.",
            &["distributed_systems"],
            &["kubernetes", "autoscaling"],
            "https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler",
        ),
        pat(
            "service_account",
            "Service Account",
            "pattern",
            "kubernetes",
            "Namespace-scoped identity for processes running in pods.",
            "Authenticate workloads to the Kubernetes API and to cloud IAM.",
            "Sharing user credentials in pods is unsafe.",
            "Bind ServiceAccounts to RBAC roles; mount projected tokens; map to cloud IAM via IRSA/Workload Identity for cloud auth.",
            "Least-privilege workloads; namespace boundaries matter.",
            &["distributed_systems"],
            &["kubernetes", "security"],
            "https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/",
        ),
        pat(
            "pod_security_standards",
            "Pod Security Standards",
            "pattern",
            "kubernetes",
            "Namespace-level policy enforcing Privileged / Baseline / Restricted security profiles for pods.",
            "Block insecure pod specs before they run.",
            "Default Kubernetes allows root containers and host-namespace access.",
            "Label namespaces with `pod-security.kubernetes.io/enforce`: baseline or restricted; admission rejects non-compliant pods.",
            "Strong baseline security; restricted profile rejects some legitimate workloads (need exceptions).",
            &["distributed_systems"],
            &["kubernetes", "security"],
            "https://kubernetes.io/docs/concepts/security/pod-security-standards/",
        ),
        pat(
            "network_policy",
            "Network Policy",
            "pattern",
            "kubernetes",
            "Namespace/pod-level rules describing allowed ingress/egress traffic.",
            "Implement zero-trust networking inside the cluster.",
            "By default, all pods can talk to all pods.",
            "Author NetworkPolicy resources; CNI plugins (Calico, Cilium) enforce; default deny + explicit allow.",
            "Strong segmentation; requires CNI support and policy management discipline.",
            &["distributed_systems"],
            &["kubernetes", "security", "networking"],
            "https://kubernetes.io/docs/concepts/services-networking/network-policies/",
        ),
        pat(
            "job_cronjob",
            "Job / CronJob",
            "pattern",
            "kubernetes",
            "Job runs pods to completion; CronJob runs Jobs on a schedule.",
            "Run batch and scheduled work natively in Kubernetes.",
            "Running periodic work as long-running pods wastes resources and risks duplication.",
            "Define Job with completion count + parallelism; CronJob wraps Job with schedule; configure backoff and history limits.",
            "Native batch execution; concurrency policy on CronJob avoids overlap.",
            &["distributed_systems"],
            &["kubernetes", "batch"],
            "https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/",
        ),
        pat(
            "statefulset",
            "StatefulSet",
            "pattern",
            "kubernetes",
            "Workload controller for ordered, stable pods with stable network identity and storage.",
            "Run stateful apps (DBs, queues) that need stable identity per replica.",
            "Deployments give random pod names and lose volume-pod binding on restart.",
            "Define StatefulSet; each replica gets predictable name and PVC; rolling updates ordered; headless service for DNS.",
            "Native stateful orchestration; ordered semantics constrain rollouts.",
            &["distributed_systems"],
            &["kubernetes", "stateful"],
            "https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/",
        ),
        pat(
            "daemonset",
            "DaemonSet",
            "pattern",
            "kubernetes",
            "Run exactly one pod per node (or per matching node set).",
            "Deploy node-local agents (log shippers, CSI, monitoring).",
            "Per-node agents shouldn't be Deployments since they need per-node identity.",
            "Define a DaemonSet with node selectors/tolerations; one pod per matching node; auto-scale on node add/remove.",
            "Right tool for node agents; resource budget per node matters.",
            &["distributed_systems"],
            &["kubernetes", "agents"],
            "https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/",
        ),
        pat(
            "kustomize",
            "Kustomize",
            "pattern",
            "kubernetes",
            "Template-free Kubernetes manifest customization via overlays and bases.",
            "Manage per-environment differences without Helm templating syntax.",
            "Helm templates are powerful but complex; copy-paste manifests drift.",
            "Author base manifests; per-env overlay patches; `kubectl apply -k`.",
            "Native kubectl support; less powerful than Helm for parameterization.",
            &["distributed_systems", "declarative_programming"],
            &["kubernetes", "configuration"],
            "https://kustomize.io/",
        ),
        pat(
            "configmap_secret",
            "ConfigMap / Secret",
            "pattern",
            "kubernetes",
            "Inject configuration (ConfigMap) and credentials (Secret) into pods via env vars or volumes.",
            "Decouple config from container images.",
            "Hardcoding config rebakes images for every change.",
            "Reference ConfigMap/Secret in pod spec; mount or env-inject; rotate via reload-on-change tools.",
            "Image reuse across environments; Secrets at rest need encryption (KMS / SealedSecrets).",
            &["distributed_systems"],
            &["kubernetes", "configuration"],
            "https://kubernetes.io/docs/concepts/configuration/configmap/",
        ),
        pat(
            "ingress_controller",
            "Ingress Controller",
            "pattern",
            "kubernetes",
            "Cluster-level reverse proxy that routes external HTTP(S) traffic to internal services via Ingress resources.",
            "Provide a single TLS-terminating entry point with host/path routing.",
            "NodePort/LoadBalancer per service is expensive and lacks routing.",
            "Run an Ingress controller (nginx, Traefik, Envoy-based); author Ingress resources; centralize TLS and rate limits.",
            "Cost-effective routing; controller is a critical shared component.",
            &["distributed_systems"],
            &["kubernetes", "networking"],
            "https://kubernetes.io/docs/concepts/services-networking/ingress/",
        ),
        pat(
            "namespace_isolation",
            "Namespace Isolation",
            "pattern",
            "kubernetes",
            "Use namespaces as logical units of isolation for multi-team or multi-environment clusters.",
            "Separate quotas, policies, and access in one cluster.",
            "Single-namespace clusters mix teams and environments unsafely.",
            "Allocate namespaces per team/env; apply ResourceQuotas, LimitRanges, RBAC, NetworkPolicy per namespace.",
            "Shared-cluster economy with logical separation; multi-tenant security requires hardening.",
            &["distributed_systems"],
            &["kubernetes", "multi_tenancy"],
            "https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/",
        ),
    ]
}
