//! Metaprogramming patterns: programs that manipulate, transform, or generate
//! other programs as data. Term rewriting, macro systems, partial evaluation,
//! Futamura projections, staged compilation, reflection, homoiconicity, and
//! hyperedge graph rewriting (MeTTa, Hyperon).

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        pat(
            "metta_term_rewriting_rule",
            "MeTTa term-rewriting rule (`(= lhs rhs)`)",
            "pattern",
            "term_rewriting",
            "A rule `(= (head $args…) body)` rewrites any term matching the head pattern into the body, with `$`-variables bound by structural unification.",
            "Express computation directly as conditional graph rewrites in a hyperedge-graph database (MeTTa space) rather than as call-by-value functions.",
            "Function-based languages cannot natively express bidirectional rules, multi-head matches, or open extension of behavior over an external data graph.",
            "Add `(= lhs rhs)` atoms to a space; the runtime applies them by matching the LHS against an active term and substituting bindings into the RHS.",
            "First-class extensibility and reflectivity; rule selection / confluence become global properties that need attention as catalogs grow.",
            &[
                "metaprogramming",
                "declarative_programming",
                "logic_programming",
            ],
            &["metta", "term_rewriting", "hyperon", "rewriting"],
            "https://github.com/trueagi-io/hyperon-experimental",
        ),
        pat(
            "dependent_type_annotation",
            "Dependent type annotation (`(: name Type)`)",
            "pattern",
            "type_signature",
            "A `(: name TypeExpr)` atom declares that `name` inhabits `TypeExpr`, where `TypeExpr` is itself an ordinary MeTTa term — types and terms share the same syntax.",
            "Encode signatures in the same hyperedge graph as the program, enabling reflective type inspection and dependent-type idioms.",
            "External type systems require parallel infrastructure (parser, AST, checker) and decouple from the program's own evaluator.",
            "Insert `(: f (-> A B))` atoms into the space; pattern-match on them during dispatch or proof construction; treat type-equality as standard MeTTa equality.",
            "Reflective and extensible type discipline; type-checking complexity scales with the expressivity of the type-term language.",
            &[
                "metaprogramming",
                "declarative_programming",
                "functional_programming",
            ],
            &["metta", "dependent_types", "curry_howard", "annotation"],
            "https://en.wikipedia.org/wiki/Dependent_type",
        ),
        pat(
            "hyperedge_graph_substitution",
            "Hyperedge graph substitution",
            "pattern",
            "graph_rewriting",
            "Represent program and data as an ordered hyperedge graph; substitution replaces a matched subgraph (under variable binding) with another subgraph.",
            "Provide a uniform substrate that subsumes terms, rules, types, and metadata — the MeTTa space model.",
            "Distinguishing AST vs heap vs metadata vs rules requires multiple parallel representations and translation glue between layers.",
            "Store every atom as a hyperedge; matching is structural unification over hyperedges; rewriting commits the substitution back to the space.",
            "Unified runtime + metadata model; performance demands careful indexing (e.g., trie-by-head-symbol) to keep matching tractable.",
            &["metaprogramming", "declarative_programming"],
            &["hyperedge_graph", "metta", "graph_rewriting", "hyperon"],
            "https://en.wikipedia.org/wiki/Graph_rewriting",
        ),
        pat(
            "quasiquote_unquote",
            "Quasiquote / unquote",
            "pattern",
            "macro_systems",
            "Quote a template literally with `\\``, but selectively splice in computed sub-expressions with `,` (unquote) or `,@` (unquote-splicing).",
            "Construct code that is mostly literal but parameterized by a few computed fragments — the most readable form of code generation.",
            "Building ASTs node-by-node hides the resulting code's shape; string templating loses syntactic safety.",
            "Use Lisp/Scheme/Racket `(quasiquote (let ((,x 1)) ,@body))` — the host language reads the template as data and splices the unquoted parts in place.",
            "Concise code-as-data construction with full lexical context; debug output requires `pp` to round-trip back to source form.",
            &["metaprogramming", "functional_programming"],
            &["macro", "quasiquote", "splicing", "lisp", "scheme"],
            "https://en.wikipedia.org/wiki/Quasi-quotation",
        ),
        pat(
            "hygienic_macro_expansion",
            "Hygienic macro expansion",
            "pattern",
            "macro_systems",
            "A macro system that automatically alpha-renames bound identifiers so user-supplied names cannot accidentally capture or be captured by template names.",
            "Provide referential-transparency guarantees for textual code transformations.",
            "Plain text-substitution macros (C `#define`) leak template bindings and capture surrounding scope, producing notoriously fragile expansions.",
            "Use a syntactic-closure / sets-of-scopes / mark-based renaming algorithm (Scheme `syntax-rules`, Racket `syntax-parse`, Rust `macro_rules!`).",
            "Compositional and safe code generation; the macro authoring model becomes more nuanced than naive substitution.",
            &["metaprogramming", "functional_programming"],
            &["macro", "hygiene", "alpha_rename", "scheme", "rust"],
            "https://en.wikipedia.org/wiki/Hygienic_macro",
        ),
        pat(
            "staged_compilation",
            "Staged compilation (`MetaOCaml`-style)",
            "pattern",
            "compilation",
            "Languages with `<expr>` (quote) and `.~expr` (splice) construct level-1 (next-stage) code at level 0 (current stage); the runtime compiles and runs it.",
            "Specialize generic code with respect to known parameters at one stage, emitting a faster specialized version at the next.",
            "Hand-rolled `Code` types blur stage levels; type errors surface at run time rather than at the compile-time of the staged program.",
            "Annotate stage levels in the type system (`<int>` is a level-1 int producer); use brackets/escape to construct and splice; the type checker enforces stage discipline.",
            "Generic libraries that compile to monomorphized specializations; tooling (debuggers, profilers) must understand multiple stages.",
            &["metaprogramming", "functional_programming"],
            &["staged_compilation", "metaocaml", "lms", "type_directed"],
            "https://okmij.org/ftp/ML/MetaOCaml.html",
        ),
        pat(
            "partial_evaluation",
            "Partial evaluation",
            "pattern",
            "specialization",
            "Specialize a program with respect to a subset of its inputs at compile or analysis time, producing a residual program that only takes the remaining inputs.",
            "Eliminate per-call interpretation overhead in a configurable program by burning known inputs into a faster residual.",
            "Hand-coded specializations bit-rot; reaching them requires duplicate maintenance of generic and specialized versions.",
            "Apply a binding-time analysis to mark inputs as static/dynamic; evaluate the static parts away (offline or online PE) and emit the residual.",
            "Often dramatic speedups for interpreters / config-driven code; PE soundness requires care with non-strict semantics and effects.",
            &["metaprogramming", "functional_programming"],
            &["partial_evaluation", "specialization", "supercompilation"],
            "https://en.wikipedia.org/wiki/Partial_evaluation",
        ),
        pat(
            "futamura_projection",
            "Futamura projection",
            "pattern",
            "specialization",
            "Specializing an interpreter w.r.t. a program yields a compiled program; specializing a partial evaluator w.r.t. an interpreter yields a compiler; specializing it w.r.t. itself yields a compiler-generator.",
            "Derive compilers automatically from interpreters via repeated partial evaluation — a foundational result of metaprogramming theory.",
            "Hand-writing both an interpreter and a compiler for the same language duplicates semantics and risks divergence.",
            "Build an interpreter; run a sufficiently aggressive partial evaluator on (interpreter, source); the residual is a compiled program (1st projection). Iterate for higher-order compilers.",
            "Compilers as a by-product of interpreters; quality of the result is bounded by the PE's binding-time analysis sophistication.",
            &["metaprogramming"],
            &["futamura", "partial_evaluation", "interpreter_compiler"],
            "https://en.wikipedia.org/wiki/Partial_evaluation#Futamura_projections",
        ),
        pat(
            "homoiconicity",
            "Homoiconicity (code-as-data)",
            "pattern",
            "language_design",
            "The language's source representation is itself a value in the language — programs and ASTs share one data type (Lisp's lists, MeTTa's atoms, Prolog's terms).",
            "Make program manipulation a first-class library activity: macros, interpreters, transformations are ordinary code.",
            "Languages whose AST is distinct from runtime values force metaprogramming into a separate stage with bespoke tooling.",
            "Choose a uniform data representation (S-expr, term, atom) for both source and runtime values; provide a small reader/printer pair so programs can read and emit themselves.",
            "Lisp-family superpower for metaprogramming; surface syntax is constrained to the data representation's shape.",
            &["metaprogramming", "declarative_programming"],
            &["homoiconicity", "code_as_data", "lisp", "metta", "prolog"],
            "https://en.wikipedia.org/wiki/Homoiconicity",
        ),
        pat(
            "reflection_introspection",
            "Reflection / introspection",
            "pattern",
            "runtime_metaprogramming",
            "A running program inspects, modifies, or extends its own structure (classes, modules, types, ASTs) via reified handles.",
            "Enable late-bound features such as plugin systems, dynamic dispatch, ORM mapping, debuggers, and ad-hoc serialization.",
            "Static dispatch is fast but inflexible; growing a system without recompiling requires reified meta-information.",
            "Expose program structure as runtime values: `Class`, `Method`, `Atom`, `Term`. Provide invocation/introspection APIs that mirror the static program.",
            "Pervasive late-binding power; reflection-driven code is hard to type-check, optimize, and reason about statically.",
            &["metaprogramming", "object_oriented_programming"],
            &["reflection", "introspection", "rtti", "java", "python"],
            "https://en.wikipedia.org/wiki/Reflective_programming",
        ),
        pat(
            "unification_pattern_matching",
            "Unification pattern matching",
            "pattern",
            "matching",
            "Symbolic structural matching that solves an equation system over terms with variables, producing a most-general substitution.",
            "Match patterns against open terms with unbound logic variables — the foundation of Prolog, MeTTa, miniKanren, and ML pattern compilation.",
            "Direct equality matching cannot handle variables; backtracking pattern guards re-derive what unification gives in one pass.",
            "Implement Robinson's algorithm (or Martelli-Montanari) on first-order terms; build a most-general unifier (MGU) for the equation set or fail.",
            "Compact declarative matching; unification can be quadratic without occur-check optimization, and the MGU machinery adds overhead vs direct equality.",
            &[
                "metaprogramming",
                "logic_programming",
                "declarative_programming",
            ],
            &["unification", "mgu", "metta", "prolog", "minikanren"],
            "https://en.wikipedia.org/wiki/Unification_(computer_science)",
        ),
        pat(
            "code_generation_from_schema",
            "Schema-driven code generation",
            "pattern",
            "code_generation",
            "Generate typed source code from an external schema (protobuf, OpenAPI, GraphQL, SQL DDL, Avro) at build time rather than hand-writing it.",
            "Keep type definitions and serialization code in sync with an authoritative schema, eliminating an entire class of drift bugs.",
            "Hand-written DTOs and serializers drift from the schema, producing wire-format incompatibilities that surface only at integration time.",
            "Add a build step that reads the schema and emits language-specific source; emit code into a generated/ directory that is not edited by hand.",
            "Strong consistency between schema and program; generated code may be verbose, and build complexity grows with the codegen toolchain.",
            &["metaprogramming"],
            &["codegen", "protobuf", "openapi", "schema_driven"],
            "https://protobuf.dev/",
        ),
        pat(
            "relational_metaprogramming",
            "Relational metaprogramming (Datalog / miniKanren)",
            "pattern",
            "term_rewriting",
            "Express computation as a set of relations and queries rather than functions — pattern matching over a knowledge base, with backtracking search.",
            "Provide declarative specifications for analysis, inference, and graph queries where the search strategy is best left to the runtime.",
            "Procedural search over relational data conflates search strategy with the relation's definition; refactoring is brittle.",
            "Write relations (Datalog rules, miniKanren goals); query by running the relations in any mode — forward, backward, or generative.",
            "Direct declarative specification of static analyses, graph queries, and inference; non-trivial relations may require careful indexing and termination control.",
            &[
                "metaprogramming",
                "logic_programming",
                "declarative_programming",
            ],
            &["datalog", "minikanren", "relational", "metta"],
            "https://en.wikipedia.org/wiki/Datalog",
        ),
    ]
}
