//! Machine learning, MLOps, and LLM/agent engineering patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- Retrieval / vector search ----------
        pat(
            "retrieval_augmented_generation",
            "Retrieval-Augmented Generation (RAG)",
            "pattern",
            "ml_ai",
            "Augment an LLM's prompt with content retrieved from an external corpus, grounding answers in real data.",
            "Reduce hallucinations and let the model use information beyond its training cut-off.",
            "Bare LLMs invent details and can't access private/recent data.",
            "Index documents → embed → store in vector DB; at query time, retrieve top-K, inject into prompt, let LLM answer.",
            "Grounded, citeable outputs; quality depends entirely on retrieval recall and prompt design.",
            &["machine_learning_engineering"],
            &["llm", "rag", "retrieval"],
            "https://arxiv.org/abs/2005.11401",
        ),
        pat(
            "vector_database",
            "Vector Database",
            "pattern",
            "ml_ai",
            "Database optimized for storing and querying high-dimensional embedding vectors via approximate nearest-neighbor (ANN) search.",
            "Enable fast similarity search at scale.",
            "Naive cosine over millions of vectors is too slow.",
            "Use pgvector, Pinecone, Qdrant, Weaviate, Milvus; build ANN index (HNSW/IVF); query with cosine/inner product.",
            "Sub-linear similarity search; tradeoff recall vs latency via index params.",
            &["machine_learning_engineering", "distributed_systems"],
            &["llm", "vector_db", "ann"],
            "https://www.pinecone.io/learn/vector-database/",
        ),
        pat(
            "embedding_based_retrieval",
            "Embedding-Based Retrieval",
            "pattern",
            "ml_ai",
            "Encode documents and queries to dense vectors; retrieve by vector similarity.",
            "Capture semantic similarity that keyword search misses.",
            "BM25 misses paraphrases and concept matches.",
            "Use a sentence-encoder (e.g., all-MiniLM, BGE, e5); index documents; query by embedding the user query and retrieving top-K.",
            "Concept-level matching; loses exact-phrase precision unless paired with lexical search.",
            &["machine_learning_engineering"],
            &["llm", "rag", "retrieval"],
            "https://www.sbert.net/",
        ),
        pat(
            "hybrid_search_rrf",
            "Hybrid Search (Reciprocal Rank Fusion)",
            "pattern",
            "ml_ai",
            "Combine lexical (BM25) and dense (embedding) retrieval, fusing rankings with RRF.",
            "Get the recall of dense + precision of lexical.",
            "Either alone misses queries the other catches.",
            "Run BM25 and vector search; fuse with RRF: score = Σ 1/(k + rank_i); take top-K of fused.",
            "Robust recall+precision; an extra index to maintain.",
            &["machine_learning_engineering"],
            &["search", "ir"],
            "https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf",
        ),
        pat(
            "reranking",
            "Reranking",
            "pattern",
            "ml_ai",
            "Use a stronger (slower) model to rerank a small set retrieved by a fast first-stage retriever.",
            "Improve top-K precision without paying the cost on every document.",
            "Cheap retrieval gives high recall but coarse ranking.",
            "Retrieve top-100 with bi-encoder; rerank with a cross-encoder (e.g., bge-reranker, Cohere Rerank); keep top-5/10.",
            "Big precision gains; second-stage latency must fit budget.",
            &["machine_learning_engineering"],
            &["llm", "retrieval"],
            "https://www.sbert.net/examples/applications/retrieve_rerank/",
        ),
        pat(
            "hnsw_index",
            "HNSW Index",
            "pattern",
            "ml_ai",
            "Hierarchical Navigable Small World graph: layered proximity graph for ANN search.",
            "Achieve high-recall, low-latency similarity search.",
            "Brute-force kNN is O(N) per query.",
            "Build a multi-layer graph; insertions choose layers probabilistically; queries greedy-descend; tunable m / ef_construction / ef_search.",
            "Excellent recall/latency tradeoff; index size larger than IVF.",
            &["machine_learning_engineering"],
            &["ann", "index"],
            "https://arxiv.org/abs/1603.09320",
        ),
        pat(
            "ivf_index",
            "IVF (Inverted File) Index",
            "pattern",
            "ml_ai",
            "Partition vectors into clusters via k-means; search only relevant clusters.",
            "Trade some recall for lower memory than HNSW.",
            "HNSW graphs can be memory-heavy.",
            "Cluster vectors with k-means; at query, probe nearest N clusters; combine with PQ for compression (IVF-PQ).",
            "Compact; tuning nlist / nprobe matters; some recall loss.",
            &["machine_learning_engineering"],
            &["ann", "index"],
            "https://www.pinecone.io/learn/series/faiss/vector-indexes/",
        ),
        pat(
            "product_quantization",
            "Product Quantization (PQ)",
            "pattern",
            "ml_ai",
            "Compress vectors by splitting into sub-vectors and quantizing each to a small codebook.",
            "Massively reduce memory and disk for billion-vector indexes.",
            "Storing raw float32 vectors at scale is prohibitive.",
            "Split d into m parts; k-means each part to k=256 centroids; store one byte per part.",
            "Tiny indexes; accuracy loss requires reranking for high-precision needs.",
            &["machine_learning_engineering"],
            &["ann", "compression"],
            "https://faiss.ai/cpp_api/struct/structfaiss_1_1ProductQuantizer.html",
        ),
        // ---------- MLOps ----------
        pat(
            "feature_store",
            "Feature Store",
            "pattern",
            "ml_ai",
            "Central system for computing, storing, and serving ML features with offline (training) and online (serving) symmetry.",
            "Avoid training/serving skew and duplicate feature pipelines.",
            "Training jobs and serving paths often compute features differently, causing online performance regressions.",
            "Define feature transforms once; materialize to both batch (warehouse) and online (low-latency KV) stores; serve via a feature store SDK.",
            "Reusable features and parity; ops overhead and freshness vs cost tradeoffs.",
            &["machine_learning_engineering"],
            &["mlops"],
            "https://www.featurestore.org/",
        ),
        pat(
            "model_registry",
            "Model Registry",
            "pattern",
            "ml_ai",
            "Versioned catalog of trained models with metadata, lineage, and stage tags (staging/production/archived).",
            "Make model promotion auditable and reversible.",
            "Untracked model artifacts on engineer laptops are unreproducible.",
            "Register models with versioning (MLflow, Vertex, SageMaker); store metrics, hyperparams, lineage; promote via API.",
            "Reproducible deploys; registry becomes a critical system to operate.",
            &["machine_learning_engineering"],
            &["mlops"],
            "https://mlflow.org/docs/latest/model-registry.html",
        ),
        pat(
            "model_card",
            "Model Card",
            "principle",
            "ml_ai",
            "Documented profile of a model: intended use, dataset, performance breakdown by subgroup, limitations.",
            "Communicate model behavior for responsible use.",
            "Undocumented models get misused outside their training distribution.",
            "Author a card with intended use, training data, metrics by demographic slice, ethical considerations; ship with the model.",
            "Better-informed consumers; takes effort to maintain.",
            &["machine_learning_engineering"],
            &["mlops", "responsible_ai"],
            "https://arxiv.org/abs/1810.03993",
        ),
        pat(
            "online_inference",
            "Online Inference",
            "pattern",
            "ml_ai",
            "Serve model predictions in real-time via a low-latency API.",
            "Power user-facing features (search ranking, fraud, recommendations).",
            "Batch jobs can't meet request-time latency requirements.",
            "Wrap the model in a service (Triton, Ray Serve, FastAPI); use GPU if needed; size autoscaling; cache where appropriate.",
            "Real-time predictions; ops cost of GPUs and tail-latency control.",
            &["machine_learning_engineering"],
            &["mlops", "inference"],
            "https://huyenchip.com/2020/12/27/real-time-machine-learning.html",
        ),
        pat(
            "batch_inference",
            "Batch Inference",
            "pattern",
            "ml_ai",
            "Score large datasets offline on a schedule; persist results.",
            "Cheaply produce predictions when freshness > minutes is acceptable.",
            "Online inference costs are unnecessary for non-realtime cases.",
            "Run a scheduled job (Airflow + Spark/Ray); write predictions to a table; downstream reads from the table.",
            "Cost-efficient and simple; stale by job interval.",
            &["machine_learning_engineering"],
            &["mlops", "inference"],
            "https://docs.aws.amazon.com/sagemaker/latest/dg/batch-transform.html",
        ),
        pat(
            "champion_challenger",
            "Champion-Challenger (Model)",
            "pattern",
            "ml_ai",
            "Production runs the champion; a challenger model gets a fraction of traffic; promote when metrics beat champion.",
            "Continuously evolve models with risk control.",
            "Offline metrics don't always match live performance.",
            "Route 5-10% traffic to challenger; compare KPIs (CTR, error rate, latency); promote/demote based on stat-sig results.",
            "Data-driven model promotion; experiment design matters.",
            &["machine_learning_engineering"],
            &["mlops", "experiments"],
            "https://en.wikipedia.org/wiki/A/B_testing",
        ),
        pat(
            "shadow_model_deployment",
            "Shadow Model Deployment",
            "pattern",
            "ml_ai",
            "Run the new model in parallel with the current; record predictions but don't serve them.",
            "Compare new vs old on real traffic before exposing users.",
            "Champion-challenger still exposes some users to a worse model.",
            "Send same input to both models; record both predictions and outcomes; analyze offline.",
            "Zero user impact during validation; doubles inference cost during shadow period.",
            &["machine_learning_engineering"],
            &["mlops"],
            "https://huyenchip.com/2020/12/27/real-time-machine-learning.html",
        ),
        pat(
            "online_learning",
            "Online Learning",
            "pattern",
            "ml_ai",
            "Update model parameters as new data arrives, not in periodic batches.",
            "Adapt to non-stationary distributions in (near) real time.",
            "Periodic retraining lags behind drift.",
            "Use models supporting incremental updates (SGD-based, river); guard against catastrophic forgetting and feedback loops.",
            "Fresh model; harder to debug, evaluate, and rollback.",
            &["machine_learning_engineering"],
            &["ml", "online"],
            "https://en.wikipedia.org/wiki/Online_machine_learning",
        ),
        pat(
            "active_learning",
            "Active Learning",
            "pattern",
            "ml_ai",
            "Train iteratively; have the model select the most informative unlabeled examples for human labeling.",
            "Reduce labeling cost by focusing on examples that improve the model most.",
            "Random labeling wastes annotator effort on easy/redundant examples.",
            "Train initial model; score unlabeled pool; pick highest-uncertainty/disagreement; label; retrain.",
            "10× labeling efficiency in many tasks; selection biases must be monitored.",
            &["machine_learning_engineering"],
            &["ml", "labeling"],
            "https://en.wikipedia.org/wiki/Active_learning_(machine_learning)",
        ),
        pat(
            "train_validate_test_split",
            "Train/Validate/Test Split",
            "principle",
            "ml_ai",
            "Partition labeled data into training, validation (tuning), and test (final eval) sets that never overlap.",
            "Get unbiased estimates of generalization performance.",
            "Tuning on test data inflates reported metrics ('train-test contamination').",
            "Split disjoint; use validation for hyperparameters/early stopping; test for final reporting only; freeze test set.",
            "Trustworthy metrics; small data may need cross-validation instead.",
            &["machine_learning_engineering"],
            &["ml", "evaluation"],
            "https://scikit-learn.org/stable/modules/cross_validation.html",
        ),
        pat(
            "cross_validation",
            "Cross-Validation",
            "pattern",
            "ml_ai",
            "Average performance across K folds of the data to estimate generalization more reliably than a single split.",
            "Reduce variance of evaluation metrics on small datasets.",
            "Single train/val split is noisy when data is scarce.",
            "Use stratified k-fold (k=5/10); for time series, use forward-chaining splits; report mean ± std.",
            "Better estimates; k× training cost.",
            &["machine_learning_engineering"],
            &["ml", "evaluation"],
            "https://en.wikipedia.org/wiki/Cross-validation_(statistics)",
        ),
        // ---------- LLM / agent patterns ----------
        pat(
            "few_shot_prompting",
            "Few-Shot Prompting",
            "pattern",
            "ml_ai",
            "Provide examples of input→output in the prompt to teach the LLM the desired pattern.",
            "Steer outputs without fine-tuning.",
            "Zero-shot prompts misinterpret format and style.",
            "Include 2-8 diverse examples in the prompt; place near the task; pick examples that cover the input distribution.",
            "Effective for new tasks; consumes context; examples must be representative.",
            &["machine_learning_engineering"],
            &["llm", "prompting"],
            "https://arxiv.org/abs/2005.14165",
        ),
        pat(
            "chain_of_thought",
            "Chain-of-Thought Prompting (CoT)",
            "pattern",
            "ml_ai",
            "Prompt the LLM to reason step-by-step before producing the final answer.",
            "Improve accuracy on multi-step reasoning tasks.",
            "Direct-answer prompts skip intermediate computation and err.",
            "Add 'Let's think step by step' or step-by-step exemplars; parse the final answer separately.",
            "Higher accuracy on reasoning; longer outputs and latency; exposes reasoning surface area.",
            &["machine_learning_engineering"],
            &["llm", "prompting"],
            "https://arxiv.org/abs/2201.11903",
        ),
        pat(
            "self_consistency",
            "Self-Consistency",
            "pattern",
            "ml_ai",
            "Generate multiple CoT samples and take majority vote on the final answer.",
            "Reduce variance of CoT and improve accuracy.",
            "Single CoT samples are sensitive to randomness.",
            "Sample N reasoning paths; extract the answer from each; pick the most common.",
            "Significant accuracy gains; N× inference cost.",
            &["machine_learning_engineering"],
            &["llm", "prompting"],
            "https://arxiv.org/abs/2203.11171",
        ),
        pat(
            "tree_of_thoughts",
            "Tree-of-Thoughts",
            "pattern",
            "ml_ai",
            "Search over a tree of partial reasoning states; evaluate and prune to find the best solution.",
            "Solve search-y problems that benefit from backtracking.",
            "CoT can't backtrack from bad steps.",
            "Generate K candidate next steps; score each; expand the best; repeat (BFS/DFS).",
            "Stronger on hard problems; exponentially more inference.",
            &["machine_learning_engineering"],
            &["llm", "search"],
            "https://arxiv.org/abs/2305.10601",
        ),
        pat(
            "react_pattern",
            "ReAct (Reason + Act)",
            "pattern",
            "ml_ai",
            "Interleave reasoning steps with tool-use actions and observations.",
            "Let the LLM use external tools mid-reasoning.",
            "Static prompts can't access live data or compute exactly.",
            "Prompt format: Thought → Action → Observation → Thought ...; provide tools (search, calculator, code-runner); stop on Answer.",
            "Powerful agentic behavior; long traces; tool-call validation needed.",
            &["machine_learning_engineering"],
            &["llm", "agent"],
            "https://arxiv.org/abs/2210.03629",
        ),
        pat(
            "function_calling",
            "Function Calling (Tool Use)",
            "pattern",
            "ml_ai",
            "Define functions/tools with JSON schemas; LLM emits structured call requests; runtime executes and returns results.",
            "Bridge LLM reasoning to deterministic systems.",
            "Free-text LLM responses are hard to parse reliably.",
            "Declare tools with name/description/parameters JSON Schema; pass to model; iterate model↔tool until done.",
            "Reliable structured interactions; tool quality and timeouts must be designed.",
            &["machine_learning_engineering"],
            &["llm", "agent"],
            "https://platform.openai.com/docs/guides/function-calling",
        ),
        pat(
            "multi_agent_workflow",
            "Multi-Agent Workflow",
            "pattern",
            "ml_ai",
            "Decompose a task across multiple specialized LLM 'agents' that collaborate via messages.",
            "Solve complex problems by division of labor.",
            "Single-agent prompts conflate roles and degrade.",
            "Define agent roles (planner, coder, critic); pass messages; cap iteration count; supervise from outside.",
            "Capable of complex tasks; non-determinism multiplies; cost and observability matter.",
            &["machine_learning_engineering"],
            &["llm", "agent"],
            "https://www.anthropic.com/news/building-effective-agents",
        ),
        pat(
            "constitutional_ai",
            "Constitutional AI / Self-Critique",
            "pattern",
            "ml_ai",
            "Have the LLM critique its own output against a written set of principles, then revise.",
            "Improve safety/quality without per-instance human review.",
            "Direct outputs miss policy violations subtle to detect.",
            "Pipeline: draft → critique against principles → revise; principles drawn from constitution; can be done in one call (CoT) or two-stage.",
            "Higher policy adherence; depends on principle quality and model.",
            &["machine_learning_engineering"],
            &["llm", "safety"],
            "https://arxiv.org/abs/2212.08073",
        ),
        // ---------- Model lifecycle ----------
        pat(
            "data_drift_monitoring",
            "Data Drift Monitoring",
            "pattern",
            "ml_ai",
            "Track distribution shifts in input features over time and alert.",
            "Catch silent degradation when production data drifts from training data.",
            "Models silently lose accuracy when reality changes.",
            "Compute PSI / KL divergence / Wasserstein per feature per window; alert on threshold breach; correlate with downstream metrics.",
            "Early-warning system; needs baseline statistics and threshold tuning.",
            &["machine_learning_engineering"],
            &["mlops", "monitoring"],
            "https://www.evidentlyai.com/ml-in-production/data-drift",
        ),
        pat(
            "concept_drift",
            "Concept Drift Monitoring",
            "pattern",
            "ml_ai",
            "Track changes in the relationship P(y | x) over time, not just input distribution.",
            "Detect when retraining or labels-need-update is required.",
            "Data drift alone misses cases where inputs are stable but labels evolve.",
            "Monitor model accuracy / calibration / prediction-actual residuals over time; trigger retraining when degraded.",
            "Catches real performance loss; requires fresh labels.",
            &["machine_learning_engineering"],
            &["mlops", "monitoring"],
            "https://en.wikipedia.org/wiki/Concept_drift",
        ),
        pat(
            "knowledge_distillation",
            "Knowledge Distillation",
            "pattern",
            "ml_ai",
            "Train a small 'student' model to mimic a larger 'teacher'.",
            "Get most of the teacher's accuracy at a fraction of the cost.",
            "Teacher inference is too slow/expensive for production.",
            "Use teacher logits/outputs as targets for student training; combine with hard labels (temperature softmax).",
            "Cheap inference; some accuracy loss; student may have different inductive biases.",
            &["machine_learning_engineering"],
            &["ml", "compression"],
            "https://arxiv.org/abs/1503.02531",
        ),
        pat(
            "model_quantization",
            "Model Quantization",
            "pattern",
            "ml_ai",
            "Reduce model precision (FP32 → INT8 / FP16 / 4-bit) to shrink memory and accelerate inference.",
            "Run large models on constrained hardware.",
            "FP32 inference is memory-bound and slow for LLMs.",
            "Apply post-training quantization (PTQ) or quantization-aware training (QAT); evaluate accuracy drop; pick format (GGUF, AWQ, GPTQ).",
            "Substantial speedup + memory savings; some accuracy loss, especially in extreme low-bit.",
            &["machine_learning_engineering"],
            &["ml", "compression"],
            "https://huggingface.co/docs/optimum/concept_guides/quantization",
        ),
        pat(
            "lora_fine_tuning",
            "LoRA Fine-Tuning",
            "pattern",
            "ml_ai",
            "Fine-tune a model by training low-rank adapter matrices instead of full weights.",
            "Customize large models with a fraction of compute and storage.",
            "Full fine-tuning of large models requires expensive hardware.",
            "Insert low-rank adapters into attention layers; train only adapters; ship adapter weights (often MB instead of GB).",
            "Cheap, swappable adapters; can underperform full fine-tune on hard tasks.",
            &["machine_learning_engineering"],
            &["ml", "fine_tuning"],
            "https://arxiv.org/abs/2106.09685",
        ),
    ]
}
