//! Observability, SRE, and incident-management patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- Metric methodologies ----------
        pat(
            "red_method",
            "RED Method (Rate, Errors, Duration)",
            "principle",
            "observability",
            "Track Rate (requests/sec), Errors (count or %), and Duration (latency distribution) for every request-driven service.",
            "Cover the fundamental request-driven service metrics with one cohesive standard.",
            "Ad-hoc metric choices yield blind spots and inconsistent dashboards across services.",
            "For each service, expose RED metrics with consistent labels; build dashboards and SLOs from them.",
            "Uniform service health view; misses resource-saturation symptoms (use USE alongside).",
            &["distributed_systems"],
            &["observability", "sre", "metrics"],
            "https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/",
        ),
        pat(
            "use_method",
            "USE Method (Utilization, Saturation, Errors)",
            "principle",
            "observability",
            "Track Utilization, Saturation, and Errors for every resource (CPU, memory, disk, network, file descriptors).",
            "Cover resource-level health that request-level RED metrics don't see.",
            "Request-level monitoring misses CPU steal, swap pressure, queue backlogs.",
            "Per-resource: emit utilization, saturation (queue length), and error counters; alert on saturation trends.",
            "Strong resource visibility; complements RED rather than replacing it.",
            &["distributed_systems"],
            &["observability", "sre", "metrics"],
            "https://www.brendangregg.com/usemethod.html",
        ),
        pat(
            "golden_signals",
            "Golden Signals (Latency, Traffic, Errors, Saturation)",
            "principle",
            "observability",
            "Google SRE's four signals to monitor for any user-facing service.",
            "Provide a minimal, complete observability baseline for every service.",
            "Teams pick scattered metrics that miss core failure modes.",
            "Instrument latency, traffic, errors, and saturation for each service; tie SLOs to them.",
            "Comprehensive baseline; tail-latency targeting is critical for latency.",
            &["distributed_systems"],
            &["observability", "sre"],
            "https://sre.google/sre-book/monitoring-distributed-systems/",
        ),
        // ---------- Health / probes ----------
        pat(
            "health_endpoint",
            "Health Endpoint",
            "pattern",
            "observability",
            "Expose a known URL (e.g., `/health` or `/healthz`) that returns service health for orchestrators and load balancers.",
            "Let infrastructure detect unhealthy instances and reroute traffic.",
            "Orchestrators can't tell whether a process is up but broken.",
            "Implement an endpoint that returns 200 when healthy, ≠200 when not; keep checks cheap; differentiate liveness vs readiness.",
            "Automated remediation possible; over-eager checks can flap; deep dependency checks can cascade.",
            &["distributed_systems"],
            &["observability", "cloud_native"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/health-endpoint-monitoring",
        ),
        pat(
            "liveness_probe",
            "Liveness Probe",
            "pattern",
            "observability",
            "A periodic check that determines whether a process should be restarted.",
            "Detect deadlocks/hangs that the process can't recover from on its own.",
            "Crashed processes may still hold their port; an external probe is needed.",
            "Expose a cheap endpoint that fails only on truly dead state; the orchestrator restarts on failure.",
            "Auto-recovery from hangs; flapping probes can cause restart loops.",
            &["distributed_systems"],
            &["observability", "kubernetes"],
            "https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/",
        ),
        pat(
            "readiness_probe",
            "Readiness Probe",
            "pattern",
            "observability",
            "A periodic check that determines whether a process should receive traffic.",
            "Hide instances that are alive but not ready to serve (loading, draining).",
            "Loading instances served partial responses; draining instances dropped in-flight requests.",
            "Probe expensive dependencies (DB connections, caches); flip to ready only once loaded; flip to not-ready during drain.",
            "Smooth rollouts and graceful shutdowns; expensive readiness checks add startup latency.",
            &["distributed_systems"],
            &["observability", "kubernetes"],
            "https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/",
        ),
        pat(
            "startup_probe",
            "Startup Probe",
            "pattern",
            "observability",
            "A one-time check during slow start-up that prevents liveness/readiness from killing a process too early.",
            "Give slow-starting processes (JVM warmup, model loading) a deterministic readiness window.",
            "Liveness probes kill slow-starting processes before they finish initializing.",
            "Use a startup probe with a generous timeout; liveness/readiness only begin after it passes.",
            "Reliable cold starts; the probe must accurately distinguish startup from hang.",
            &["distributed_systems"],
            &["observability", "kubernetes"],
            "https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/",
        ),
        // ---------- Logging / tracing ----------
        pat(
            "structured_logging",
            "Structured Logging",
            "pattern",
            "observability",
            "Emit logs as machine-parseable structured records (JSON/Logfmt) with consistent fields, not free-form text.",
            "Make logs queryable, aggregatable, and joinable with traces/metrics.",
            "Free-form text logs require fragile regex parsing and break aggregation.",
            "Use a structured-logging library; standardize field names (timestamp, level, trace_id, span_id, service, message).",
            "Powerful queries; minor extra runtime overhead vs printf.",
            &["distributed_systems"],
            &["observability", "logging"],
            "https://www.elastic.co/blog/structured-logging-filebeat",
        ),
        pat(
            "correlation_id",
            "Correlation ID / Request ID",
            "pattern",
            "observability",
            "Generate a unique identifier per request and propagate it through every service, log, and message in the request path.",
            "Stitch together logs and traces for a single user action across services.",
            "Distributed debugging is impossible without a shared identifier.",
            "Generate at the edge (or accept inbound); propagate via headers (e.g., X-Request-Id); include in every log line.",
            "Cross-service stitching; relies on every service to honor the header.",
            &["distributed_systems"],
            &["observability", "tracing"],
            "https://learn.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring#correlation",
        ),
        pat(
            "distributed_tracing",
            "Distributed Tracing",
            "pattern",
            "observability",
            "Capture a request's path through services as a tree of spans with timing and metadata.",
            "Reveal latency contributions and failures across multi-service requests.",
            "Per-service logs alone can't show where time was spent or where errors originated.",
            "Instrument with OpenTelemetry; propagate W3C Trace Context; export to a backend (Jaeger/Tempo/Honeycomb).",
            "End-to-end visibility; sampling and storage costs must be designed.",
            &["distributed_systems"],
            &["observability", "tracing"],
            "https://opentelemetry.io/docs/concepts/observability-primer/#distributed-traces",
        ),
        pat(
            "trace_context_w3c",
            "W3C Trace Context",
            "pattern",
            "observability",
            "Standardize headers (`traceparent`, `tracestate`) for propagating trace identity across services and vendors.",
            "Enable interop between tracing systems and vendors.",
            "Vendor-specific propagation breaks at integration boundaries.",
            "Adopt W3C Trace Context; libraries inject/extract `traceparent` automatically; vendor-specific data goes in `tracestate`.",
            "Vendor-neutral interop; some legacy systems still need B3 or Jaeger fallback.",
            &["distributed_systems"],
            &["observability", "tracing", "spec"],
            "https://www.w3.org/TR/trace-context/",
        ),
        pat(
            "span_baggage",
            "Span Baggage",
            "pattern",
            "observability",
            "Attach key-value context to a trace that propagates to all descendant spans.",
            "Carry request-level context (tenant, feature flag, experiment) through trace and logs.",
            "Per-service code re-derives context on every call.",
            "Set baggage at the request edge; readers in any service can pull it via the OpenTelemetry baggage API.",
            "Cleaner cross-service context; sensitive data must not be put in baggage without policy.",
            &["distributed_systems"],
            &["observability", "tracing"],
            "https://opentelemetry.io/docs/concepts/signals/baggage/",
        ),
        pat(
            "tail_based_sampling",
            "Tail-Based Sampling",
            "pattern",
            "observability",
            "Decide whether to keep a trace after the trace is complete, based on tail attributes (errors, latency).",
            "Keep all interesting traces while sampling the rest aggressively.",
            "Head-based sampling either keeps too much (cost) or too little (misses errors).",
            "Buffer spans in a collector; on trace completion, apply a sampling policy that always keeps errors and slow traces.",
            "Cost-effective and high-signal; collector memory and latency add operational complexity.",
            &["distributed_systems"],
            &["observability", "tracing"],
            "https://opentelemetry.io/docs/collector/configuration/#tail-sampling",
        ),
        pat(
            "head_based_sampling",
            "Head-Based Sampling",
            "pattern",
            "observability",
            "Decide at the start of a trace whether to keep it, using probability or a hash-based rule.",
            "Reduce trace volume cheaply at the cost of biased sampling.",
            "Keeping every trace overwhelms backends; full storage is prohibitive.",
            "Make the sampling decision at root span creation; propagate via Trace Context flags.",
            "Cheap and uniform; can't preferentially keep error/slow traces.",
            &["distributed_systems"],
            &["observability", "tracing"],
            "https://opentelemetry.io/docs/concepts/sampling/",
        ),
        pat(
            "exemplars",
            "Metric Exemplars",
            "pattern",
            "observability",
            "Attach example trace IDs to a metric bucket so you can jump from a metric spike to the trace that exemplifies it.",
            "Bridge metrics and traces for rapid diagnosis.",
            "Metrics summarize; finding the offending trace requires manual correlation.",
            "Emit metrics with exemplars (OpenMetrics format); Grafana / Prometheus link to traces directly.",
            "Faster MTTR; storage and exporter support must be present.",
            &["distributed_systems"],
            &["observability", "metrics", "tracing"],
            "https://prometheus.io/docs/concepts/exemplars/",
        ),
        pat(
            "log_levels_discipline",
            "Log Levels Discipline",
            "principle",
            "observability",
            "Use ERROR/WARN/INFO/DEBUG/TRACE consistently across services with clear semantics.",
            "Make log severity actionable rather than noisy.",
            "INFO and ERROR are used interchangeably; ops can't tune signal-to-noise.",
            "Define explicit semantics (ERROR=needs human; WARN=anomalous but handled; INFO=major events); review at boundaries.",
            "Useful alerts; requires team agreement and code review.",
            &["distributed_systems"],
            &["observability", "logging"],
            "https://www.dataset.com/blog/the-10-commandments-of-logging/",
        ),
        // ---------- SLO / error budget ----------
        pat(
            "slo_sla_sli",
            "SLI / SLO / SLA",
            "principle",
            "observability",
            "Define SLIs (measurable indicators), SLOs (internal objectives), and SLAs (external contracts) explicitly.",
            "Convert vague reliability into measurable, negotiable targets.",
            "Without targets, reliability work has no priority and no ceiling.",
            "Pick a small set of SLIs (request latency, availability); set realistic SLOs; SLA is a customer contract that is strictly weaker.",
            "Aligned product/eng priorities; SLI choice matters more than threshold tuning.",
            &["distributed_systems"],
            &["observability", "sre"],
            "https://sre.google/sre-book/service-level-objectives/",
        ),
        pat(
            "error_budget",
            "Error Budget",
            "principle",
            "observability",
            "Define the allowed unreliability between 100% and the SLO; spend it on velocity, replenish via reliability work.",
            "Make the reliability/velocity tradeoff explicit and quantitative.",
            "Reliability and velocity teams argue without a shared currency.",
            "If SLO is 99.9%, error budget is 0.1%; track burn; freeze releases when budget exhausted.",
            "Healthy tradeoff conversation; requires accurate SLI measurement.",
            &["distributed_systems"],
            &["observability", "sre"],
            "https://sre.google/workbook/error-budget-policy/",
        ),
        pat(
            "burn_rate_alerting",
            "Burn-Rate Alerting",
            "pattern",
            "observability",
            "Alert based on multi-window error-budget burn rates instead of static thresholds.",
            "Avoid both false-positive page storms and slow detection.",
            "Static thresholds on error rate either flap or miss slow burns.",
            "Page on fast burn (e.g., 5%/hour) and slow burn (e.g., 5%/day) using OR of the two; from Google SRE workbook.",
            "Tunable signal; requires good SLI baselines.",
            &["distributed_systems"],
            &["observability", "sre", "alerting"],
            "https://sre.google/workbook/alerting-on-slos/",
        ),
        pat(
            "symptom_based_alerting",
            "Symptom-Based Alerting",
            "principle",
            "observability",
            "Alert on user-visible symptoms (error rates, latency), not on causes (CPU, queue depth) which may not affect users.",
            "Reduce false-positives; ensure pages match real impact.",
            "Cause-based alerts fire on benign internal changes.",
            "Restrict pageable alerts to SLO burn; treat cause metrics as diagnostic, not pageable.",
            "Higher alert quality; cause metrics still needed for diagnosis.",
            &["distributed_systems"],
            &["observability", "alerting"],
            "https://sre.google/sre-book/monitoring-distributed-systems/",
        ),
        // ---------- Anti-patterns ----------
        pat(
            "cardinality_explosion",
            "Cardinality Explosion",
            "anti_pattern",
            "observability",
            "Adding a high-cardinality label (user_id, request_id) to a metric series creates millions of unique series.",
            "Recognize OOMs and cost blow-ups in metrics backends.",
            "Easy to add labels without considering storage; some backends silently truncate.",
            "Restrict label values to bounded sets; use logs/traces for per-request data.",
            "Sustainable metrics costs; some loss of granular slicing.",
            &["distributed_systems"],
            &["observability", "metrics", "antipattern"],
            "https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels",
        ),
        pat(
            "alert_fatigue",
            "Alert Fatigue",
            "anti_pattern",
            "observability",
            "On-call gets so many low-quality alerts that real incidents are missed.",
            "Recognize ignored alerts that erode trust in the system.",
            "Per-symptom alerting accumulates until the on-call drowns.",
            "Audit alerts by acknowledge-rate and false-positive ratio; delete or downgrade non-actionable alerts.",
            "Trustworthy alerting; requires sustained discipline.",
            &["distributed_systems"],
            &["observability", "alerting", "antipattern"],
            "https://sre.google/workbook/alerting-on-slos/",
        ),
        pat(
            "page_storm",
            "Page Storm",
            "anti_pattern",
            "observability",
            "A single incident triggers many duplicate or downstream alerts simultaneously.",
            "Recognize cascading alerting that overwhelms responders.",
            "Many services share a failed dependency and each pages independently.",
            "Use alert dependency graphs / inhibition rules to suppress dependent alerts when the root is firing.",
            "Cleaner incident response; dependency model must be kept current.",
            &["distributed_systems"],
            &["observability", "alerting", "antipattern"],
            "https://sre.google/sre-book/practical-alerting/",
        ),
        // ---------- Process patterns ----------
        pat(
            "runbook",
            "Runbook",
            "pattern",
            "observability",
            "A written procedure that an on-call engineer can follow to mitigate a known class of incident.",
            "Reduce MTTR by giving responders deterministic steps.",
            "On-call recreates diagnosis from scratch each time.",
            "Link each alert to a runbook in the alert annotation; keep them short, current, and tested.",
            "Faster recovery; outdated runbooks are worse than none — review regularly.",
            &["distributed_systems"],
            &["observability", "sre", "process"],
            "https://sre.google/sre-book/being-on-call/",
        ),
        pat(
            "blameless_postmortem",
            "Blameless Postmortem",
            "principle",
            "observability",
            "Investigate incidents with a focus on systemic causes, not individual error.",
            "Encourage honest reporting and structural improvements.",
            "Blame-based culture suppresses incident reporting.",
            "Follow a postmortem template (timeline, impact, root cause, action items); name people only with consent; share broadly.",
            "Deeper learnings; some legal/compliance contexts limit detail.",
            &["distributed_systems"],
            &["observability", "sre", "culture"],
            "https://sre.google/sre-book/postmortem-culture/",
        ),
        pat(
            "chaos_game_day",
            "Chaos Game Day",
            "pattern",
            "observability",
            "Pre-scheduled exercise where teams inject controlled failures into production-like systems.",
            "Verify resilience claims and on-call readiness without surprise.",
            "Resilience designs only get tested during real incidents.",
            "Plan scenarios; brief responders; execute under observation; review and document gaps; repeat.",
            "Better real-incident readiness; requires production-like environment and safety guardrails.",
            &["distributed_systems"],
            &["observability", "sre", "resilience"],
            "https://principlesofchaos.org/",
        ),
        pat(
            "incident_command",
            "Incident Command",
            "pattern",
            "observability",
            "A single Incident Commander coordinates response; everyone else has a defined role (comms, scribe, ops, subject-matter expert).",
            "Avoid confused parallel responders during a high-pressure incident.",
            "During incidents, multiple people give conflicting instructions.",
            "Adopt FEMA-derived Incident Command System (IC, Operations, Comms, Planning, Logistics); rotate roles.",
            "Clear, fast response; the IC role requires training.",
            &["distributed_systems"],
            &["observability", "sre", "process"],
            "https://response.pagerduty.com/before/different_roles/",
        ),
        pat(
            "toil_reduction",
            "Toil Reduction",
            "principle",
            "observability",
            "Identify manual, repetitive operational work (toil) and eliminate or automate it.",
            "Free SRE capacity for engineering improvements.",
            "Operational load grows linearly with services if every action is manual.",
            "Track toil as a fraction of team time; cap it (Google: 50%); prioritize automation when over budget.",
            "Sustainable operations; over-strict caps under-invest in necessary firefighting.",
            &["distributed_systems"],
            &["observability", "sre"],
            "https://sre.google/sre-book/eliminating-toil/",
        ),
        pat(
            "production_readiness_review",
            "Production Readiness Review (PRR)",
            "pattern",
            "observability",
            "Pre-launch checklist that a service must pass before going live (monitoring, alerts, runbooks, capacity, rollback).",
            "Ensure new services meet a uniform operational bar.",
            "Services launch with missing observability or runbooks and create incidents.",
            "Maintain a PRR checklist; require sign-off; track items between launches and post-incident.",
            "Higher launch quality; checklist must evolve based on incidents.",
            &["distributed_systems"],
            &["observability", "sre", "process"],
            "https://sre.google/workbook/evolving-sre-engagement-model/",
        ),
        pat(
            "service_catalog",
            "Service Catalog",
            "pattern",
            "observability",
            "Central registry of every service with owner, runbook, dashboards, SLOs, dependencies.",
            "Make 'who owns this and where does it live' answerable in seconds.",
            "During incidents, finding service owners or runbooks wastes minutes.",
            "Adopt a service catalog (Backstage, internal); enforce metadata via CI; integrate with alerts and dashboards.",
            "Faster onboarding and incident response; catalog drift kills usefulness — automate ownership data.",
            &["distributed_systems"],
            &["observability", "sre", "process"],
            "https://backstage.io/",
        ),
        pat(
            "embedded_sre",
            "Embedded SRE",
            "pattern",
            "observability",
            "A site reliability engineer joins a product team for a fixed period to raise its reliability practice.",
            "Transfer SRE skills without permanent shared ownership.",
            "Pure consult or pure ownership models fail to change product-team habits.",
            "Embed 1 SRE per product team for 6 months; mentor, build automation, then exit; track improved SLOs.",
            "Lasting practice change; requires SRE staffing capacity.",
            &["distributed_systems"],
            &["observability", "sre", "process"],
            "https://sre.google/workbook/evolving-sre-engagement-model/",
        ),
    ]
}
