//! Cross-paradigm software design principles. All entries use `kind = "principle"`.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        pat(
            "dry",
            "Don't Repeat Yourself (DRY)",
            "principle",
            "general",
            "Every piece of knowledge should have a single, unambiguous representation in the system.",
            "Eliminate duplication of intent so that change happens in exactly one place.",
            "The same business rule or computation is encoded in many places and drifts out of sync.",
            "Extract the duplicated knowledge into a single source-of-truth (function, type, table, configuration).",
            "Reduces drift; over-eager DRY can create false couplings between accidentally-similar code.",
            &[
                "procedural_programming",
                "object_oriented_programming",
                "functional_programming",
            ],
            &["principle", "pragmatic_programmer"],
            "https://en.wikipedia.org/wiki/Don%27t_repeat_yourself",
        ),
        pat(
            "kiss",
            "Keep It Simple, Stupid (KISS)",
            "principle",
            "general",
            "Prefer the simplest design that satisfies the requirements.",
            "Avoid adding complexity that doesn't earn its keep.",
            "Designs accumulate cleverness, abstractions, and indirection beyond what the problem requires.",
            "Choose the most boring solution that meets the spec; add complexity only when forced.",
            "Easier to read and maintain; risk of underdesign for inherently complex problems.",
            &[
                "procedural_programming",
                "object_oriented_programming",
                "functional_programming",
            ],
            &["principle"],
            "https://en.wikipedia.org/wiki/KISS_principle",
        ),
        pat(
            "yagni",
            "You Aren't Gonna Need It (YAGNI)",
            "principle",
            "general",
            "Do not add functionality until it is actually needed.",
            "Avoid speculative code that is never used.",
            "Engineers build extension points and configuration for use cases that never materialize.",
            "Implement only what current requirements demand; defer speculative work until evidence appears.",
            "Less code to maintain; ill-applied YAGNI can defer architecture that turns out to be needed.",
            &[
                "procedural_programming",
                "object_oriented_programming",
                "functional_programming",
            ],
            &["principle", "xp"],
            "https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it",
        ),
        pat(
            "law_of_demeter",
            "Law of Demeter (Principle of Least Knowledge)",
            "principle",
            "general",
            "An object should only talk to its immediate friends, not strangers.",
            "Reduce coupling by limiting how far a unit reaches into others' object graphs.",
            "Chains like `a.b().c().d()` leak structure and break when any link changes.",
            "Have collaborators expose the operations a caller needs, so it talks only to direct neighbors.",
            "Lower coupling; mechanical application produces wrappers that just delegate.",
            &["object_oriented_programming"],
            &["principle", "coupling"],
            "https://en.wikipedia.org/wiki/Law_of_Demeter",
        ),
        pat(
            "tell_dont_ask",
            "Tell, Don't Ask",
            "principle",
            "general",
            "Tell objects what to do; don't ask them for their data and then decide.",
            "Keep behavior with the data that informs it.",
            "Callers fetch state from an object and execute logic externally, leaking encapsulation.",
            "Move the decision into the object that owns the state; callers issue commands.",
            "Better cohesion; some workflows genuinely require external orchestration.",
            &["object_oriented_programming"],
            &["principle", "encapsulation"],
            "https://martinfowler.com/bliki/TellDontAsk.html",
        ),
        pat(
            "composition_over_inheritance",
            "Composition over Inheritance",
            "principle",
            "general",
            "Prefer composing behaviors from collaborator objects rather than extending classes.",
            "Avoid the rigidity and fragility of deep inheritance trees.",
            "Sharing behavior via inheritance creates strong coupling and limits independent change.",
            "Model variation by injecting strategy/policy objects and delegating to them.",
            "Flexible reuse; requires discipline to name and wire collaborators clearly.",
            &["object_oriented_programming"],
            &["principle", "composition"],
            "https://en.wikipedia.org/wiki/Composition_over_inheritance",
        ),
        pat(
            "separation_of_concerns",
            "Separation of Concerns",
            "principle",
            "general",
            "Distinct concerns should be addressed by distinct sections of code.",
            "Make the structure of the system mirror the structure of its responsibilities.",
            "Different concerns (UI, persistence, business rules) are interleaved and changes in one ripple into others.",
            "Identify concerns and place each in its own module/layer/file with explicit boundaries.",
            "Independent change and testing; over-strict layering can produce ceremony.",
            &[
                "object_oriented_programming",
                "procedural_programming",
                "functional_programming",
            ],
            &["principle", "architecture"],
            "https://en.wikipedia.org/wiki/Separation_of_concerns",
        ),
        pat(
            "program_to_interface",
            "Program to an Interface, Not an Implementation",
            "principle",
            "general",
            "Depend on abstractions, not concrete types.",
            "Decouple consumers from the choice of provider.",
            "Code that imports concrete classes is locked into those choices and is hard to substitute.",
            "Type method signatures and dependencies in terms of interfaces or traits; let composition pick the concrete.",
            "Easier replacement and testing; interface design must reflect a real polymorphic need.",
            &["object_oriented_programming"],
            &["principle", "abstraction"],
            "https://en.wikipedia.org/wiki/Dependency_inversion_principle",
        ),
        pat(
            "encapsulate_what_varies",
            "Encapsulate What Varies",
            "principle",
            "general",
            "Identify the parts of a system that are likely to change and isolate them behind a stable interface.",
            "Localize change so the rest of the system stays unaffected.",
            "Volatile decisions leak across many call sites, making change risky.",
            "Wrap the variation behind an interface; expose only the stable abstraction.",
            "Lowers change cost; encapsulating non-varying things creates dead abstractions.",
            &["object_oriented_programming"],
            &["principle", "design"],
            "https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)",
        ),
        pat(
            "hollywood_principle",
            "Hollywood Principle (Don't Call Us, We'll Call You)",
            "principle",
            "general",
            "Lower-level modules should not call higher-level ones; the framework calls them at known extension points.",
            "Make the framework own control flow and the application own behavior.",
            "Applications hard-code the order of operations the framework would otherwise orchestrate.",
            "Define callbacks/hooks the framework invokes; the application registers them.",
            "Composable, testable; the entry path is no longer local.",
            &["object_oriented_programming"],
            &["principle", "frameworks"],
            "https://en.wikipedia.org/wiki/Hollywood_principle",
        ),
        pat(
            "command_query_separation",
            "Command-Query Separation (CQS)",
            "principle",
            "general",
            "Every method should either change state (command) or return a value (query), but not both.",
            "Make it safe to call queries arbitrarily without side effects.",
            "Methods that read and mutate together are easy to misuse and hard to reason about.",
            "Split into pure queries and explicit commands; let names signal which is which.",
            "Predictable semantics; some I/O genuinely couples read and write (e.g., dequeue).",
            &["object_oriented_programming", "functional_programming"],
            &["principle", "side_effects"],
            "https://en.wikipedia.org/wiki/Command%E2%80%93query_separation",
        ),
        pat(
            "postels_law",
            "Postel's Law (Robustness Principle)",
            "principle",
            "general",
            "Be conservative in what you send and liberal in what you accept.",
            "Tolerate variation at the input while keeping output strict.",
            "Strict producers and strict consumers brittle when peers evolve at different rates.",
            "Reject only inputs that are unambiguously wrong; emit strictly conformant outputs.",
            "Smoother interop; over-liberal parsers can hide bugs and create security risks.",
            &["distributed_systems"],
            &["principle", "protocols"],
            "https://en.wikipedia.org/wiki/Robustness_principle",
        ),
        pat(
            "principle_of_least_astonishment",
            "Principle of Least Astonishment (POLA)",
            "principle",
            "general",
            "A component should behave in a way that minimally surprises its users.",
            "Match user expectations to reduce mistakes and learning cost.",
            "APIs do things that look obvious but actually behave subtly differently.",
            "Choose behaviors and names that match domain conventions and the most likely interpretation.",
            "Better usability; sometimes correctness requires surprising-but-explicit behavior.",
            &["object_oriented_programming", "procedural_programming"],
            &["principle", "ux"],
            "https://en.wikipedia.org/wiki/Principle_of_least_astonishment",
        ),
        pat(
            "convention_over_configuration",
            "Convention over Configuration",
            "principle",
            "general",
            "Let the framework supply sensible defaults so only deviations require explicit configuration.",
            "Reduce boilerplate by encoding common choices as conventions.",
            "Every project re-declares the same wiring, file layouts, naming, and binding decisions.",
            "Define conventions in the framework; require config only when the user departs from them.",
            "Fast onboarding; magic conventions hurt when they don't match the project.",
            &["object_oriented_programming"],
            &["principle", "frameworks"],
            "https://en.wikipedia.org/wiki/Convention_over_configuration",
        ),
        // ---------- Martin's package principles ----------
        pat(
            "reuse_release_equivalence_principle",
            "Reuse/Release Equivalence Principle (REP)",
            "principle",
            "package",
            "The granule of reuse is the granule of release.",
            "Make sure released packages are tracked and consumed as cohesive units.",
            "Reusable code is shared as loose snippets without release versioning, breaking consumers silently.",
            "Group reusable code into versioned packages and treat the version as a contract.",
            "Predictable upgrades; finer-grained packages add release overhead.",
            &["object_oriented_programming"],
            &["principle", "packaging"],
            "https://en.wikipedia.org/wiki/Package_principles",
        ),
        pat(
            "common_reuse_principle",
            "Common Reuse Principle (CRP)",
            "principle",
            "package",
            "Classes that are used together belong in the same package; classes you don't use shouldn't force you to depend on a package.",
            "Avoid dragging in unrelated dependencies through package inclusion.",
            "A package mixes unrelated classes, so consumers depend on far more than they use.",
            "Split packages so each contains classes that callers consistently reuse together.",
            "Tighter dependency graphs; more packages to maintain.",
            &["object_oriented_programming"],
            &["principle", "packaging"],
            "https://en.wikipedia.org/wiki/Package_principles",
        ),
        pat(
            "common_closure_principle",
            "Common Closure Principle (CCP)",
            "principle",
            "package",
            "Classes that change together should be packaged together.",
            "Localize the impact of common change drivers.",
            "Related changes are scattered across packages, multiplying the surface area of every change.",
            "Group classes whose changes are driven by the same axis (e.g., same business actor) into one package.",
            "Lower change cost; packages can grow if change drivers are broad.",
            &["object_oriented_programming"],
            &["principle", "packaging"],
            "https://en.wikipedia.org/wiki/Package_principles",
        ),
        pat(
            "acyclic_dependencies_principle",
            "Acyclic Dependencies Principle (ADP)",
            "principle",
            "package",
            "Allow no cycles in the package dependency graph.",
            "Keep dependencies releasable in topological order.",
            "Mutually-dependent packages must be released together; testing and deployment become brittle.",
            "Break cycles with interface ownership, dependency inversion, or extraction of shared pieces.",
            "Releasable, testable independent packages; some cycles require structural refactors to remove.",
            &["object_oriented_programming"],
            &["principle", "packaging", "architecture"],
            "https://en.wikipedia.org/wiki/Package_principles",
        ),
        pat(
            "stable_dependencies_principle",
            "Stable Dependencies Principle (SDP)",
            "principle",
            "package",
            "Depend in the direction of stability.",
            "Volatile code should depend on stable code, not the other way around.",
            "Stable foundation code transitively depends on volatile UI/extension code.",
            "Measure instability (fan-out / (fan-in + fan-out)) and ensure dependencies flow toward stable nodes.",
            "Stable foundations; some upward dependencies must be inverted with interfaces.",
            &["object_oriented_programming"],
            &["principle", "packaging", "architecture"],
            "https://en.wikipedia.org/wiki/Package_principles",
        ),
        pat(
            "stable_abstractions_principle",
            "Stable Abstractions Principle (SAP)",
            "principle",
            "package",
            "A package should be as abstract as it is stable.",
            "Avoid stable packages full of concrete code that resists change.",
            "Stable packages calcify when they're stuffed with concrete classes that should evolve.",
            "Make stable packages abstract (interfaces, base types) and put concrete details in less-stable ones.",
            "Healthier evolution; requires conscious placement of abstractions vs concretes.",
            &["object_oriented_programming"],
            &["principle", "packaging", "architecture"],
            "https://en.wikipedia.org/wiki/Package_principles",
        ),
        pat(
            "boy_scout_rule",
            "Boy Scout Rule",
            "principle",
            "general",
            "Leave the code cleaner than you found it.",
            "Continuously reduce entropy through small, opportunistic improvements.",
            "Code rots slowly as everyone touches it without ever improving it.",
            "On each change, apply a small unrelated cleanup in the area you're editing.",
            "Gradual recovery of code health; opportunistic refactors must not creep into the same commit as risky changes.",
            &[
                "procedural_programming",
                "object_oriented_programming",
                "functional_programming",
            ],
            &["principle", "discipline"],
            "https://wiki.c2.com/?BoyScoutRule",
        ),
        pat(
            "fail_fast",
            "Fail Fast",
            "principle",
            "general",
            "Report invalid inputs or invariant violations as early and loudly as possible.",
            "Catch bugs near their source so they're cheap to diagnose.",
            "Errors are swallowed or deferred until far-away symptoms appear.",
            "Validate at boundaries; assert invariants where they should hold; throw or panic on impossible states.",
            "Earlier detection; in production paths must be paired with graceful user-facing failure handling.",
            &["procedural_programming", "object_oriented_programming"],
            &["principle", "robustness"],
            "https://martinfowler.com/ieeeSoftware/failFast.pdf",
        ),
        pat(
            "make_invalid_states_unrepresentable",
            "Make Invalid States Unrepresentable",
            "principle",
            "general",
            "Encode constraints in the type system so impossible states cannot be constructed.",
            "Move bug-prevention from tests/asserts into types.",
            "Records permit illegal combinations that runtime validation must constantly police.",
            "Use sum types, smart constructors, newtypes, and exhaustive matching to make invalid combinations type errors.",
            "Stronger correctness; type-design effort up front.",
            &["functional_programming", "object_oriented_programming"],
            &["principle", "types"],
            "https://blog.janestreet.com/effective-ml-revisited/",
        ),
        pat(
            "parse_dont_validate",
            "Parse, Don't Validate",
            "principle",
            "general",
            "Transform unstructured input into a stronger type so downstream code never sees the unsafe form.",
            "Carry the proof of validity in the type rather than re-checking.",
            "Validation succeeds, but the same untyped string keeps flowing and must be re-validated everywhere.",
            "Have validation return a new, narrower type (e.g., `EmailAddress`, `Sanitized<T>`); discard the loose form.",
            "Eliminates redundant checks; requires investment in domain-specific types.",
            &["functional_programming", "object_oriented_programming"],
            &["principle", "types"],
            "https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/",
        ),
        pat(
            "principle_of_least_privilege",
            "Principle of Least Privilege",
            "principle",
            "general",
            "Grant a subject only the privileges it strictly needs to do its job.",
            "Minimize the blast radius of compromise or bug.",
            "Components run with broad capabilities they don't need (root, full DB access, etc.).",
            "Decompose responsibilities; issue narrow, scoped credentials or capabilities to each.",
            "Reduces damage from incidents; requires discipline in capability design.",
            &["distributed_systems"],
            &["principle", "security"],
            "https://en.wikipedia.org/wiki/Principle_of_least_privilege",
        ),
        // ---------- Additional cross-paradigm principles ----------
        pat(
            "worse_is_better",
            "Worse Is Better",
            "principle",
            "general",
            "Simpler, less complete designs spread faster than 'right' designs and adapt over time.",
            "Recognize when simplicity beats correctness/completeness in practice.",
            "Pursuing 'the right thing' produces designs that lose to simpler rivals.",
            "Prefer implementation simplicity and ship; accept correctness compromises that don't bite users; iterate.",
            "Faster adoption; some correctness debt accumulates.",
            &["procedural_programming", "object_oriented_programming"],
            &["principle"],
            "https://www.dreamsongs.com/RiseOfWorseIsBetter.html",
        ),
        pat(
            "principle_of_least_power",
            "Principle of Least Power",
            "principle",
            "general",
            "Choose the least powerful language/tool that solves the problem.",
            "Maximize analyzability and reduce attack surface.",
            "Powerful languages (Turing-complete config, full scripting) are harder to reason about or sandbox.",
            "Prefer data over scripts, declarative over imperative, restricted DSLs over general languages where they suffice.",
            "Easier reasoning; some flexibility loss when simple tools are extended ad hoc.",
            &["declarative_programming"],
            &["principle"],
            "https://www.w3.org/2001/tag/doc/leastPower.html",
        ),
        pat(
            "composition_over_configuration",
            "Composition over Configuration",
            "principle",
            "general",
            "Prefer composing small, single-purpose components over configuring monolithic ones.",
            "Avoid complex config DSLs and inner-platform effects.",
            "Highly configurable monoliths drift toward reimplementing a programming language in YAML.",
            "Decompose into small components with simple interfaces; assemble via code or simple wiring.",
            "Flexible and inspectable; requires more upfront decomposition.",
            &["object_oriented_programming"],
            &["principle"],
            "https://martinfowler.com/bliki/CompositionOverConfiguration.html",
        ),
        pat(
            "single_level_of_abstraction",
            "Single Level of Abstraction (SLA)",
            "principle",
            "general",
            "Within a function, keep all statements at the same level of abstraction.",
            "Reduce cognitive friction when reading code.",
            "Mixed-level functions force readers to switch mental gears.",
            "If a function contains both high-level orchestration and low-level details, extract the low-level pieces into helper functions.",
            "Readable functions; more named helpers.",
            &["procedural_programming", "object_oriented_programming"],
            &["principle"],
            "https://principles-wiki.net/principles:single_level_of_abstraction",
        ),
        pat(
            "antifragility",
            "Antifragility",
            "principle",
            "general",
            "Build systems that gain robustness from disorder, not merely tolerate it.",
            "Move beyond resilience to systems that improve under stress.",
            "Robust systems hold up under shocks but don't learn from them.",
            "Inject controlled stress (chaos engineering, fire drills, soak tests); use learnings to harden; reward postmortem-driven improvements.",
            "Continuous improvement under volatility; cultural and process investment.",
            &["distributed_systems"],
            &["principle", "sre"],
            "https://en.wikipedia.org/wiki/Antifragility",
        ),
        pat(
            "rule_of_least_surprise",
            "Rule of Least Surprise (UNIX)",
            "principle",
            "general",
            "Programs should integrate easily and behave in expected ways for their users.",
            "Foster ecosystem interop and reduce learning cost.",
            "Bespoke interfaces hurt adoption and tooling.",
            "Honor conventions: exit codes, env vars, stdin/stdout, signal semantics, file formats; document deviations.",
            "Better ecosystem fit; some creativity sacrificed.",
            &["procedural_programming"],
            &["principle", "unix"],
            "http://www.catb.org/~esr/writings/taoup/html/ch01s06.html",
        ),
    ]
}
