//! Process-calculus patterns: π-calculus, ambient calculus, join calculus,
//! CSP, CCS, and the reflective π-calculus underlying Rholang. Patterns here
//! describe concurrent computation as message-passing processes communicating
//! over named channels.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        pat(
            "pi_calculus_channel_communication",
            "π-calculus channel communication",
            "pattern",
            "process_calculus_primitive",
            "Two processes synchronize on a shared channel name: one sends, one receives, both unblock.",
            "Model concurrent communication primitively as send/receive on a named channel rather than via shared memory.",
            "Threads sharing mutable state require locks; the resulting invariants are non-local and notoriously hard to reason about.",
            "Each process holds channel references; `c!(v)` and `for(x <- c)` synchronize via name equality. State is exchanged only through messages.",
            "Compositional reasoning, transparent distribution, automatic per-message backpressure; per-message overhead is higher than direct shared-memory access.",
            &["process_calculus", "concurrent_programming", "actor_model"],
            &["pi_calculus", "channel", "send_receive", "rholang"],
            "https://en.wikipedia.org/wiki/%CE%A0-calculus",
        ),
        pat(
            "rholang_contract_continuation",
            "Rholang contract continuation",
            "pattern",
            "process_calculus_service",
            "A `contract name(args) = { … }` declaration installs a persistent listener: every send to `name` triggers a fresh execution of the body.",
            "Express a long-lived service in process-calculus terms as a replicated input that consumes one message per invocation.",
            "Hand-rolled `for(x <- c) | for(x <- c) | …` replication is verbose, error-prone, and hides the service abstraction.",
            "Declare a contract that binds formal parameters and a body; the runtime ensures each send-receive pair runs the body once with that message's arguments.",
            "Service-oriented decomposition with first-class addresses; persistence guarantee shifts cost to the runtime's scheduler.",
            &[
                "process_calculus",
                "concurrent_programming",
                "distributed_systems",
            ],
            &["rholang", "contract", "replicated_input", "service"],
            "https://rchain.coop/",
        ),
        pat(
            "mobile_channel_passing",
            "Mobile channel passing (π's name mobility)",
            "pattern",
            "process_calculus_primitive",
            "Channel names are first-class values: a process can send a channel name as a message, granting the receiver capability to communicate over it.",
            "Reconfigure communication topology dynamically — π-calculus's hallmark over CCS.",
            "Static topologies cannot express handoff, callback registration, or capability transfer without breaking encapsulation.",
            "Send the channel name itself: `c!(*resp)` lets the receiver send back via `resp`. The receiver's address is plumbed through the message graph.",
            "Dynamic capability-based concurrency; analysis requires tracking name scopes (open/close) across communication.",
            &["process_calculus"],
            &["pi_calculus", "name_mobility", "capability"],
            "https://en.wikipedia.org/wiki/%CE%A0-calculus#Mobility",
        ),
        pat(
            "name_restriction_new",
            "Name restriction (`new x in P`)",
            "pattern",
            "process_calculus_scoping",
            "Introduce a fresh channel name that is not exposed outside the scope of `P` unless explicitly sent as a message.",
            "Establish channel-level encapsulation analogous to lexical scoping but operating on inter-process communication.",
            "Globally visible channels leak coupling; ad-hoc name collision schemes do not compose.",
            "Allocate a new name with `new x in P`; the name is guaranteed fresh and only visible to subprocesses that received it.",
            "Compositional reasoning about scope and leakage; equivalent to ν in the formal calculus and the seam for security proofs.",
            &["process_calculus"],
            &["pi_calculus", "scope", "fresh_name", "encapsulation"],
            "https://en.wikipedia.org/wiki/%CE%A0-calculus#Syntax",
        ),
        pat(
            "replicated_input_server",
            "Replicated input server (`!for(x <- c) P`)",
            "pattern",
            "process_calculus_service",
            "An input prefixed by replication consumes one message per copy and immediately spawns another copy of itself; effectively a stateless service handler.",
            "Express a stateless service in the calculus's reduction semantics without first-class function definitions.",
            "Imperative `while (true) { … }` loops are non-compositional and entangle service lifetime with caller scope.",
            "Write `!for(x <- c) P` (or its `contract` sugar in Rholang); the runtime always supplies one waiting input at `c`.",
            "Lightweight stateless services; replicated copies are independent — for shared state, materialize an internal channel.",
            &["process_calculus", "concurrent_programming"],
            &["pi_calculus", "replication", "stateless_service"],
            "https://en.wikipedia.org/wiki/%CE%A0-calculus#Replication",
        ),
        pat(
            "polyadic_send_receive",
            "Polyadic send/receive",
            "pattern",
            "process_calculus_primitive",
            "A single send or receive transmits a tuple of values atomically, not just one — encoding what monadic π expresses with extra channels.",
            "Reduce protocol verbosity and make message shapes explicit without sacrificing compositionality.",
            "Encoding multi-value messages as sequential sends loses atomicity and complicates pattern matching at the receiver.",
            "Use `c!(a, b, c)` and `for(@x, @y, @z <- c)` — the calculus's polyadic form, semantically a tuple-typed channel.",
            "Direct multi-value protocols; loses some of monadic π's minimal-syntax elegance but simplifies real-world coding.",
            &["process_calculus"],
            &["pi_calculus", "polyadic", "tuple_send"],
            "https://en.wikipedia.org/wiki/%CE%A0-calculus#Polyadic_pi-calculus",
        ),
        pat(
            "synchronous_rendezvous",
            "Synchronous rendezvous (CSP-style handshake)",
            "pattern",
            "process_calculus_primitive",
            "Send and receive both block until they meet at the same channel; the message exchange is the synchronization point.",
            "Couple control-flow to message exchange so backpressure is structural, not policy.",
            "Asynchronous send-then-poll requires per-channel buffering and explicit ACK protocols; reordering and overflow become caller concerns.",
            "Use unbuffered channels (CSP, occam, Go's `make(chan T)` w/o capacity, or Rholang's synchronous `!?`). The slower side waits.",
            "Built-in flow control and provable absence of buffer overflow; throughput requires sufficient concurrency to keep both sides busy.",
            &["process_calculus", "concurrent_programming"],
            &["csp", "rendezvous", "synchronous_send"],
            "https://en.wikipedia.org/wiki/Communicating_sequential_processes",
        ),
        pat(
            "ambient_boundary",
            "Ambient boundary",
            "pattern",
            "process_calculus_locality",
            "Processes live inside named ambients (locations); communication can only happen within an ambient or across ambient capabilities (`in`, `out`, `open`).",
            "Model mobility, security domains, and locality first-class — relevant for code mobility, sandboxing, and distributed scheduling.",
            "Plain π-calculus has no notion of where a process runs; modeling mobile or sandboxed computation requires manual encoding.",
            "Wrap processes in named ambients; require explicit capability messages (`in m`, `out n`, `open p`) to cross boundaries.",
            "Direct modeling of network/process locality, sandboxes, and migration; analysis adds capability-flow tracking on top of name flow.",
            &["process_calculus"],
            &["ambient_calculus", "mobility", "sandbox", "locality"],
            "https://en.wikipedia.org/wiki/Ambient_calculus",
        ),
        pat(
            "join_pattern_synchronization",
            "Join pattern synchronization",
            "pattern",
            "process_calculus_primitive",
            "A single reduction fires only when messages are available on every channel in a conjunctive pattern; otherwise all participants block.",
            "Express atomic multi-channel rendezvous (the n-ary generalization of CSP's binary handshake).",
            "Encoding atomic multi-channel waits with binary primitives requires sentinel channels and risks lost wakeups.",
            "Define join patterns over channel sets: `(x <- c1) & (y <- c2) => P`. The runtime commits only when all conjuncts have a pending message.",
            "Atomic multi-party synchronization; the runtime's matching engine becomes more complex (often a generalized GHC-style match).",
            &["process_calculus", "concurrent_programming"],
            &["join_calculus", "rholang", "atomic_match"],
            "https://en.wikipedia.org/wiki/Join-calculus",
        ),
        pat(
            "linear_channel_use",
            "Linear channel use",
            "pattern",
            "process_calculus_typing",
            "Linear types restrict each channel-end (input or output) to one use, so resource hand-off and protocol completion are statically tracked.",
            "Encode protocol obligations in the type system: a channel that must be replied to, a buffer that must be freed, a once-only callback.",
            "Untyped channel discipline drops messages, leaks unused responses, or double-replies — bugs that are hard to find at runtime.",
            "Annotate channels as linear (one-use) or non-linear (replicated); the type checker enforces single-receive / single-send obligations along control flow.",
            "Static protocol checking and resource safety; programs must thread linear references explicitly through their control flow.",
            &["process_calculus", "functional_programming"],
            &["linear_types", "session_types", "protocol_safety"],
            "https://en.wikipedia.org/wiki/Linear_type_system",
        ),
        pat(
            "bisimulation_equivalence",
            "Bisimulation equivalence",
            "pattern",
            "process_calculus_reasoning",
            "Two processes are bisimilar if every action of one can be matched by the other, with their successors again bisimilar — a coinductive notion of behavioral equivalence.",
            "Reason about when one process can be safely substituted for another (refactoring, optimization, compiler verification).",
            "Trace equivalence is too coarse and observational equivalence is undecidable in general; bisimulation gives a compositional, often decidable, refinement.",
            "Construct a relation R such that for every related pair, every transition of one is matched by the other landing in R; the largest such relation is bisimilarity.",
            "Compositional substitution proofs and many algorithmic checks (especially for finite-state systems); manual bisimulation construction is involved for non-trivial systems.",
            &["process_calculus", "formal_languages_and_automata"],
            &["bisimulation", "equivalence", "coinduction"],
            "https://en.wikipedia.org/wiki/Bisimulation",
        ),
        pat(
            "barbed_congruence",
            "Barbed congruence",
            "pattern",
            "process_calculus_reasoning",
            "An observational equivalence built from `barbs` (which channels are eventually-active) plus closure under arbitrary contexts.",
            "Define behavioral equivalence directly in terms of observation rather than internal structure — independent of any specific bisimulation game.",
            "Bisimulation-based equivalences depend on the calculus's internal step relation; barbed equivalence isolates the observable interface.",
            "Equate processes `P ≈ Q` iff for every reduction context `C[·]`, `C[P]` and `C[Q]` have the same barbs.",
            "Robust contextual equivalence directly comparable across calculi; often coincides with weak bisimilarity but is more flexible for proofs.",
            &["process_calculus"],
            &["barbed_congruence", "contextual_equivalence", "observation"],
            "https://en.wikipedia.org/wiki/Pi-calculus#Barbed_equivalence",
        ),
    ]
}
