//! Security design patterns and principles.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        pat(
            "defense_in_depth",
            "Defense in Depth",
            "principle",
            "security",
            "Layer multiple independent controls so a single failure doesn't compromise the system.",
            "Avoid relying on a single barrier to attackers or bugs.",
            "Single-layer controls fail open under sophisticated or accidental breach.",
            "Apply authn + authz + input validation + monitoring + encryption + privilege separation at independent layers.",
            "Stronger overall security; higher operational complexity and cost.",
            &["distributed_systems"],
            &["security", "principle"],
            "https://en.wikipedia.org/wiki/Defense_in_depth_(computing)",
        ),
        pat(
            "fail_secure",
            "Fail Secure / Fail Safe",
            "principle",
            "security",
            "When the system encounters an error, default to denying access or operating safely.",
            "Avoid open behavior on failure.",
            "Errors in auth/auth code default to allow because that's the optimistic path.",
            "Ensure error/exception branches deny by default; tests cover failure modes.",
            "Safer fallback; user-visible errors during outages.",
            &["distributed_systems"],
            &["security", "principle"],
            "https://en.wikipedia.org/wiki/Fail-safe",
        ),
        pat(
            "input_validation",
            "Input Validation",
            "pattern",
            "security",
            "Validate data at trust boundaries before it influences logic or storage.",
            "Reject malformed/malicious input early.",
            "Untrusted input drives downstream behavior unchecked.",
            "Validate type, length, format, range, encoding; prefer allow-listing; centralize at boundaries.",
            "Smaller attack surface; over-strict validation can reject legitimate inputs.",
            &["distributed_systems"],
            &["security", "owasp"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html",
        ),
        pat(
            "output_encoding",
            "Output Encoding",
            "pattern",
            "security",
            "Encode/escape data per its destination (HTML, JS, URL, SQL, shell) at the point of output.",
            "Prevent injection by ensuring data can't be interpreted as code.",
            "String concatenation produces output where data and code are indistinguishable.",
            "Use context-aware encoders (HTML attribute vs body vs JS); never trust ahead-of-time encoding.",
            "Eliminates XSS/SQLi/shell injection categories; correct encoder choice is non-trivial.",
            &["distributed_systems"],
            &["security", "owasp", "xss"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html",
        ),
        pat(
            "parameterized_queries",
            "Parameterized Queries (Prepared Statements)",
            "pattern",
            "security",
            "Send queries with placeholders; bind values as data, never as concatenated SQL.",
            "Eliminate SQL injection by construction.",
            "String-concatenated SQL trusts user input as code.",
            "Use prepared statements / ORM parameter binding; for dynamic identifiers, allow-list values.",
            "SQLi-immune; small performance benefit from query plan caching.",
            &["distributed_systems"],
            &["security", "owasp", "sql"],
            "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html",
        ),
        pat(
            "rbac",
            "Role-Based Access Control (RBAC)",
            "pattern",
            "security",
            "Grant permissions to roles; assign users to roles.",
            "Scale access management by abstraction.",
            "Per-user permissions become unmanageable as users and resources grow.",
            "Model roles aligned with job functions; assign users to roles; check role membership at policy enforcement points.",
            "Manageable access; role explosion can occur without governance.",
            &["distributed_systems"],
            &["security", "authz"],
            "https://en.wikipedia.org/wiki/Role-based_access_control",
        ),
        pat(
            "abac",
            "Attribute-Based Access Control (ABAC)",
            "pattern",
            "security",
            "Decide access by evaluating attributes of subject, resource, action, and environment.",
            "Express fine-grained, context-aware policies.",
            "RBAC's coarse-grained model can't express conditions like time-of-day or relationship.",
            "Define policies (XACML/OPA/Cedar) over attributes; evaluate at runtime.",
            "Highly flexible; policy author tools and performance must be engineered.",
            &["distributed_systems"],
            &["security", "authz"],
            "https://en.wikipedia.org/wiki/Attribute-based_access_control",
        ),
        pat(
            "capability_based_security",
            "Capability-Based Security",
            "pattern",
            "security",
            "Authority is conveyed by unforgeable references that combine designation and authorization.",
            "Implement least privilege precisely; eliminate ambient authority.",
            "Ambient authority (current user) is granted broadly even for actions that need narrow scope.",
            "Issue capability tokens that confer access to specific objects/actions; pass them explicitly.",
            "Fine-grained least privilege; capability storage and revocation must be managed.",
            &["distributed_systems"],
            &["security", "authz"],
            "https://en.wikipedia.org/wiki/Capability-based_security",
        ),
        pat(
            "multi_factor_auth",
            "Multi-Factor Authentication",
            "pattern",
            "security",
            "Require multiple independent factors (something you know/have/are) for authentication.",
            "Reduce account takeover risk from credential leaks.",
            "Single-factor auth (password) is regularly compromised.",
            "Pair passwords with TOTP / FIDO2 / hardware key; require for sensitive actions.",
            "Significantly higher account security; UX cost; recovery flows need design.",
            &["distributed_systems"],
            &["security", "authn"],
            "https://en.wikipedia.org/wiki/Multi-factor_authentication",
        ),
        pat(
            "salted_password_hashing",
            "Salted Password Hashing (KDF)",
            "pattern",
            "security",
            "Store user passwords as the output of a slow, salted, password-specific KDF.",
            "Resist offline brute force if the database is leaked.",
            "Plaintext or fast-hash storage exposes credentials at breach time.",
            "Use Argon2id / scrypt / bcrypt with per-user salt and high cost parameters; rotate parameters over time.",
            "Significant breach resilience; CPU/memory cost per login.",
            &["distributed_systems"],
            &["security", "authn"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html",
        ),
        pat(
            "oauth2_oidc",
            "OAuth 2.0 / OpenID Connect",
            "pattern",
            "security",
            "Delegate authentication and resource authorization to an identity provider using standard flows.",
            "Reuse identity services and standardized tokens.",
            "Rolling custom auth across services repeats mistakes and fragments identity.",
            "Choose the right flow (Auth Code + PKCE for web/mobile, Client Credentials for service-to-service); use signed JWT or opaque tokens.",
            "Standard, interoperable identity; specification breadth and security pitfalls require care.",
            &["distributed_systems"],
            &["security", "authn", "authz"],
            "https://oauth.net/2/",
        ),
        pat(
            "jwt_bearer_token",
            "JWT Bearer Token",
            "pattern",
            "security",
            "Self-contained signed token carrying claims about the subject.",
            "Authenticate without a session lookup at the verifier.",
            "Server-side sessions require shared state across instances.",
            "Issue short-lived signed JWTs; verify signature and claims at every request; rotate signing keys.",
            "Stateless and scalable; revocation requires extra design (blacklists or short TTL).",
            &["distributed_systems"],
            &["security", "authn"],
            "https://jwt.io/introduction",
        ),
        pat(
            "mtls",
            "Mutual TLS (mTLS)",
            "pattern",
            "security",
            "Both sides of a TLS connection authenticate each other with X.509 certificates.",
            "Strong service-to-service authentication without bearer tokens.",
            "Bearer tokens can leak; service identity needs cryptographic verification.",
            "Provision per-service certs; require client auth; use a service mesh or sidecar to manage rotation.",
            "Strong identity binding; cert lifecycle is operationally heavy without automation.",
            &["distributed_systems"],
            &["security", "transport"],
            "https://en.wikipedia.org/wiki/Mutual_authentication",
        ),
        pat(
            "zero_trust_architecture",
            "Zero Trust Architecture",
            "principle",
            "security",
            "Trust no network boundary; verify every request based on identity, device, and context.",
            "Eliminate implicit trust granted by being inside a perimeter.",
            "Perimeter-based security fails once attackers cross the boundary.",
            "Authenticate and authorize every request; enforce least privilege; continuously evaluate trust signals.",
            "Resistant to lateral movement; requires identity and policy infrastructure.",
            &["distributed_systems"],
            &["security", "architecture"],
            "https://en.wikipedia.org/wiki/Zero_trust_security_model",
        ),
        pat(
            "secret_rotation",
            "Secret Rotation",
            "pattern",
            "security",
            "Periodically generate new secrets and decommission old ones.",
            "Limit the window of damage from leaked credentials.",
            "Long-lived secrets accumulate exposure risk over time.",
            "Automate rotation through a secret manager; rolling rotation with overlap; alerts on stale secrets.",
            "Lower breach impact; secret-handling code must support overlap and reload without downtime.",
            &["distributed_systems"],
            &["security", "operations"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html",
        ),
        pat(
            "audit_logging",
            "Audit Logging",
            "pattern",
            "security",
            "Record security-relevant events with sufficient detail to investigate after the fact.",
            "Provide forensic and compliance evidence.",
            "Without audit logs, breaches and policy violations can't be reconstructed.",
            "Define what to log (who, what, when, where, why); ship to a tamper-evident store; protect sensitive fields.",
            "Investigatable systems; log governance, retention, and PII handling matter.",
            &["distributed_systems"],
            &["security", "compliance"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html",
        ),
        pat(
            "tamper_evident_log",
            "Tamper-Evident Log",
            "pattern",
            "security",
            "Chain log entries cryptographically so tampering is detectable.",
            "Provide integrity guarantees for audit trails.",
            "Plain logs can be edited by anyone with sufficient access.",
            "Hash each entry into the next (Merkle tree, hash chain); publish roots externally; verify periodically.",
            "Detect manipulation; cost of hashing and publishing depends on volume.",
            &["distributed_systems"],
            &["security", "integrity"],
            "https://en.wikipedia.org/wiki/Hash_chain",
        ),
        pat(
            "csrf_token",
            "CSRF Token",
            "pattern",
            "security",
            "Require a server-issued token on state-changing requests to prove user intent.",
            "Prevent cross-site request forgery.",
            "Browsers send cookies with cross-site requests, allowing forged actions.",
            "Issue a per-session/per-form token; check it on state-changing POSTs; combine with SameSite cookies.",
            "CSRF-resistant; tokens must be unguessable and bound correctly.",
            &["distributed_systems"],
            &["security", "web", "owasp"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html",
        ),
        pat(
            "content_security_policy",
            "Content Security Policy (CSP)",
            "pattern",
            "security",
            "Browser-enforced policy restricting which sources can supply scripts, styles, and other resources.",
            "Reduce blast radius of XSS by limiting executable origins.",
            "Default browser behavior loads anything the page references.",
            "Send a strict CSP header; nonce or hash script tags; report violations.",
            "Strong XSS mitigation; legacy inline scripts must be eliminated or hashed.",
            &["distributed_systems"],
            &["security", "web", "owasp"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html",
        ),
        pat(
            "subresource_integrity",
            "Subresource Integrity (SRI)",
            "pattern",
            "security",
            "Hash-pin third-party scripts and styles so a tampered CDN won't be loaded.",
            "Prevent compromise of external CDN content.",
            "CDN compromise injects malicious code into many sites at once.",
            "Compute integrity hashes; place in `integrity=` and `crossorigin=` attributes; rotate when assets update.",
            "Strong supply-chain protection at the page level; tooling for hashes must integrate with builds.",
            &["distributed_systems"],
            &["security", "web"],
            "https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity",
        ),
        pat(
            "hmac_message_auth",
            "HMAC for Message Authentication",
            "pattern",
            "security",
            "Authenticate a message with a keyed hash using a shared secret.",
            "Detect tampering and prove authenticity.",
            "Plain hashes don't prove who computed them.",
            "Compute HMAC(secret, message); transmit alongside; verify on receipt with constant-time compare.",
            "Strong integrity; secret distribution and rotation are operationally important.",
            &["distributed_systems"],
            &["security", "cryptography"],
            "https://en.wikipedia.org/wiki/HMAC",
        ),
        pat(
            "constant_time_compare",
            "Constant-Time Comparison",
            "pattern",
            "security",
            "Compare secrets in a way that doesn't reveal information through timing.",
            "Defeat timing side-channel attacks on equality checks.",
            "Standard equality short-circuits, leaking byte-by-byte agreement.",
            "Use a constant-time comparison function for tokens, MACs, password hashes.",
            "Closed timing side-channel for equality; only one piece of a defense-in-depth strategy.",
            &["distributed_systems"],
            &["security", "cryptography"],
            "https://en.wikipedia.org/wiki/Timing_attack",
        ),
        pat(
            "rate_limit_security",
            "Rate Limiting (Security)",
            "pattern",
            "security",
            "Throttle requests per identity/IP/route to slow brute-force and abuse.",
            "Make automated attacks impractical at scale.",
            "Unlimited request rates enable credential stuffing, scraping, and DoS.",
            "Apply per-account and per-IP limits; respond with 429; combine with progressive delays and CAPTCHAs.",
            "Slows abuse; legitimate users hit limits under bursts; careful key design needed.",
            &["distributed_systems"],
            &["security", "rate_limiting"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Denial_of_Service_Cheat_Sheet.html",
        ),
        pat(
            "input_sanitization_html",
            "HTML Sanitization",
            "pattern",
            "security",
            "Process untrusted HTML through a robust sanitizer that strips dangerous constructs.",
            "Allow rich text without XSS.",
            "Hand-rolled allow-lists miss countless edge cases.",
            "Use a battle-tested sanitizer (DOMPurify, OWASP Java HTML Sanitizer) with a strict policy.",
            "Reasonably-safe rich content; never rely on regex-based stripping.",
            &["distributed_systems"],
            &["security", "web", "xss"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html",
        ),
        pat(
            "sandboxing",
            "Sandboxing",
            "pattern",
            "security",
            "Run untrusted code in a confined environment with limited capabilities.",
            "Contain the impact of compromised or malicious code.",
            "Code with full system access can do anything if exploited.",
            "Use OS sandboxes (seccomp, AppArmor), containers, WebAssembly, or JS realms with constrained APIs.",
            "Confines damage; some sandbox boundaries have proven imperfect (audit and update).",
            &["distributed_systems"],
            &["security"],
            "https://en.wikipedia.org/wiki/Sandbox_(computer_security)",
        ),
        pat(
            "threat_modeling_stride",
            "Threat Modeling (STRIDE)",
            "pattern",
            "security",
            "Systematically enumerate threats by category: Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege.",
            "Discover threats before attackers do.",
            "Designs ship with implicit assumptions and unconsidered threats.",
            "Diagram the system; identify trust boundaries; per-component apply STRIDE; track mitigations.",
            "Proactive defense; an upfront workshop, kept lightweight, pays back.",
            &["distributed_systems"],
            &["security", "process"],
            "https://en.wikipedia.org/wiki/STRIDE_(security)",
        ),
        pat(
            "owasp_top_10_awareness",
            "OWASP Top-10 Awareness",
            "principle",
            "security",
            "Continuously train and review against the most common web vulnerability categories.",
            "Avoid the most-exploited web vulnerabilities by design.",
            "Without explicit awareness, teams ship vulnerable patterns from memory.",
            "Educate, gate with linters/SAST/DAST, and review against the current OWASP Top-10.",
            "Reduces common-vulnerability rate; not a substitute for threat modeling.",
            &["distributed_systems"],
            &["security", "owasp"],
            "https://owasp.org/www-project-top-ten/",
        ),
        pat(
            "secure_default_configuration",
            "Secure by Default",
            "principle",
            "security",
            "Ship with secure defaults so misuse takes deliberate effort.",
            "Make security the path of least resistance.",
            "Defaults often dominate deployments; insecure defaults become production reality.",
            "Default to deny; require explicit opt-in for risky features; document the secure baseline.",
            "Safer deployments; sometimes friction with users expecting permissive defaults.",
            &["distributed_systems"],
            &["security", "principle"],
            "https://www.cisa.gov/securebydefault",
        ),
        pat(
            "key_separation",
            "Key Separation by Purpose",
            "principle",
            "security",
            "Use distinct keys for distinct purposes (signing vs encrypting, env A vs env B).",
            "Limit the damage of a single key compromise.",
            "Reused keys couple unrelated systems to one another's risk.",
            "Generate per-purpose keys; document scope; rotate independently.",
            "Smaller blast radius per key; more keys to manage.",
            &["distributed_systems"],
            &["security", "cryptography"],
            "https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html",
        ),
        // ---------- Additional security patterns ----------
        pat(
            "aead",
            "Authenticated Encryption with Associated Data (AEAD)",
            "pattern",
            "security",
            "Encryption mode that provides confidentiality AND integrity in one primitive (AES-GCM, ChaCha20-Poly1305).",
            "Eliminate encrypt-then-MAC bugs by using a primitive that does both.",
            "Manual encrypt-then-MAC has subtle ordering and key-reuse pitfalls.",
            "Use AEAD constructions (GCM, ChaCha20-Poly1305); bind associated data (header) to ciphertext; never reuse nonces.",
            "Atomic encryption + auth; nonce management is critical.",
            &["distributed_systems"],
            &["security", "cryptography"],
            "https://en.wikipedia.org/wiki/Authenticated_encryption",
        ),
        pat(
            "forward_secrecy",
            "Forward Secrecy",
            "principle",
            "security",
            "Compromise of long-term keys does not compromise past session traffic.",
            "Protect historical sessions against future key compromise.",
            "Static-key encryption lets attackers decrypt recorded traffic if long-term keys leak.",
            "Use ephemeral Diffie-Hellman (ECDHE) per session; rotate session keys; do not log session keys.",
            "Past sessions stay safe; ECDHE has small performance cost.",
            &["distributed_systems"],
            &["security", "cryptography"],
            "https://en.wikipedia.org/wiki/Forward_secrecy",
        ),
        pat(
            "ocsp_stapling",
            "OCSP Stapling",
            "pattern",
            "security",
            "Server presents a recent OCSP response with its TLS handshake instead of asking clients to query the CA.",
            "Speed up TLS and reduce client privacy leaks to CAs.",
            "Per-handshake OCSP requests are slow and leak browsing history.",
            "Enable OCSP must-staple; server periodically fetches and staples the response; rotate before expiry.",
            "Faster TLS; server must keep stapled response fresh.",
            &["distributed_systems"],
            &["security", "tls"],
            "https://en.wikipedia.org/wiki/OCSP_stapling",
        ),
        pat(
            "hsts",
            "HTTP Strict Transport Security (HSTS)",
            "pattern",
            "security",
            "Browser must use HTTPS for the host for a fixed duration after seeing the HSTS header.",
            "Prevent SSL-stripping attacks.",
            "Initial HTTP requests can be intercepted and redirected.",
            "Send `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`; consider preload list.",
            "Strong upgrade enforcement; once preloaded, mistakes are persistent.",
            &["distributed_systems"],
            &["security", "web"],
            "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security",
        ),
        pat(
            "samesite_cookies",
            "SameSite Cookies",
            "pattern",
            "security",
            "Restrict cookie sending in cross-site contexts via the SameSite attribute.",
            "Prevent many CSRF attacks at the browser level.",
            "Cookies are sent on every cross-site request unless restricted.",
            "Set `SameSite=Lax` (default for most) or `Strict`; combine with `Secure` and `HttpOnly`.",
            "Strong default CSRF defense; Strict may break legitimate cross-site flows.",
            &["distributed_systems"],
            &["security", "web"],
            "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite",
        ),
        pat(
            "cookie_prefixes",
            "Cookie Prefixes (__Host-, __Secure-)",
            "pattern",
            "security",
            "Cookies with `__Host-` or `__Secure-` name prefixes must have specific security attributes.",
            "Make cookie security guarantees enforced by name.",
            "Cookies without Secure can be set over HTTP and stolen.",
            "Use `__Host-Cookie` (must be Secure, no Domain, Path=/) or `__Secure-Cookie` (must be Secure); browsers reject non-conforming sets.",
            "Hard-to-bypass cookie security; legacy code might need migration.",
            &["distributed_systems"],
            &["security", "web"],
            "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#cookie_prefixes",
        ),
        pat(
            "permissions_policy",
            "Permissions-Policy Header",
            "pattern",
            "security",
            "Server tells the browser which powerful features (camera, mic, geolocation) the page may use.",
            "Reduce attack surface by denying unused features.",
            "Pages have default access to many sensitive APIs.",
            "Send `Permissions-Policy: camera=(), microphone=(), geolocation=()` etc.; allow only what's needed.",
            "Smaller surface; ensure required features are listed.",
            &["distributed_systems"],
            &["security", "web"],
            "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy",
        ),
        pat(
            "frame_options",
            "X-Frame-Options / frame-ancestors",
            "pattern",
            "security",
            "Restrict who can frame your page to prevent clickjacking.",
            "Block UI-redress attacks.",
            "Iframed pages can be made invisible and clicked through by user.",
            "Send `X-Frame-Options: DENY` (or `SAMEORIGIN`); modern equivalent: `Content-Security-Policy: frame-ancestors 'self'`.",
            "Anti-clickjacking; may break legitimate embedders if not pre-approved.",
            &["distributed_systems"],
            &["security", "web"],
            "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options",
        ),
        pat(
            "oauth_device_flow",
            "OAuth Device Code Flow",
            "pattern",
            "security",
            "Flow for devices without browsers (CLI, TV, embedded) to obtain user-delegated tokens.",
            "Authenticate users from input-constrained devices.",
            "Browser-redirect flows require a browser.",
            "Device requests a code; user visits a URL on another device and approves; device polls token endpoint until granted (RFC 8628).",
            "Works on any device; polling interval and code TTL must be tuned.",
            &["distributed_systems"],
            &["security", "oauth"],
            "https://www.rfc-editor.org/rfc/rfc8628",
        ),
        pat(
            "pkce",
            "PKCE (Proof Key for Code Exchange)",
            "pattern",
            "security",
            "Public OAuth clients prove possession of a code verifier when exchanging an auth code for tokens.",
            "Prevent code-interception attacks on public clients (mobile, SPA, CLI).",
            "Bearer code interception lets attackers redeem tokens.",
            "Client generates a random verifier; sends SHA256(verifier) as code_challenge; presents verifier at token exchange (RFC 7636).",
            "Strong protection without client secrets; supported by major IdPs.",
            &["distributed_systems"],
            &["security", "oauth"],
            "https://www.rfc-editor.org/rfc/rfc7636",
        ),
        pat(
            "threshold_cryptography",
            "Threshold Cryptography / Shamir's Secret Sharing",
            "pattern",
            "security",
            "Split a secret into N shares such that any K shares can reconstruct it; K-1 reveal nothing.",
            "Distribute trust across multiple parties without giving any single one the secret.",
            "Single key custodians are a single point of compromise.",
            "Use Shamir's Secret Sharing or threshold signatures (FROST, BLS); choose K appropriately for governance.",
            "Strong custody; requires distributing and protecting shares.",
            &["distributed_systems"],
            &["security", "cryptography"],
            "https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing",
        ),
        pat(
            "certificate_transparency",
            "Certificate Transparency",
            "pattern",
            "security",
            "Publicly auditable, append-only logs of issued certificates; browsers require SCTs from logs.",
            "Detect misissued certificates.",
            "Rogue CAs and misissued certs went undetected for years.",
            "Issue certs with SCTs; monitor CT logs for unexpected certs for your domains; alert on misissuance.",
            "Detection within hours; SCT verification is part of the TLS handshake.",
            &["distributed_systems"],
            &["security", "tls"],
            "https://certificate.transparency.dev/",
        ),
        pat(
            "jwks_endpoint",
            "JWKS Endpoint",
            "pattern",
            "security",
            "Server publishes its public keys in JWK Set format at a well-known URL.",
            "Let verifiers discover and rotate trust keys without manual config.",
            "Hardcoded public keys force coordinated rotation.",
            "Publish `/.well-known/jwks.json` (or per-vendor); cache with appropriate TTL; rotate keys by adding new and removing old.",
            "Smooth rotation; verifier caching policy must respect kid.",
            &["distributed_systems"],
            &["security", "oauth"],
            "https://datatracker.ietf.org/doc/html/rfc7517",
        ),
        pat(
            "mtls_cert_rotation",
            "mTLS Certificate Rotation",
            "principle",
            "security",
            "Routinely issue short-lived mTLS certs and rotate before expiry.",
            "Limit damage from key compromise; force keys to be exercised.",
            "Long-lived certs accumulate risk; manual rotation is missed.",
            "Use cert-manager / SPIFFE / service mesh to rotate every hours/days; keep CA hierarchy with intermediates.",
            "Strong security; automation is essential.",
            &["distributed_systems"],
            &["security", "tls", "operations"],
            "https://spiffe.io/docs/latest/spire-about/overview/",
        ),
    ]
}
