//! SOLID and GRASP principles. All entries use `kind = "principle"`.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        // ---------- SOLID (Robert C. Martin) ----------
        pat(
            "single_responsibility_principle",
            "Single Responsibility Principle",
            "principle",
            "solid",
            "A class or module should have one, and only one, reason to change.",
            "Localize change drivers so they don't ripple across unrelated code.",
            "A module accreted multiple concerns and now any change touches several axes.",
            "Identify the actors that demand change and split modules so each serves one actor.",
            "Smaller, more cohesive modules; risk of fragmenting cohesive workflows if applied dogmatically.",
            &["object_oriented_programming"],
            &["solid", "cohesion"],
            "https://en.wikipedia.org/wiki/Single-responsibility_principle",
        ),
        pat(
            "open_closed_principle",
            "Open/Closed Principle",
            "principle",
            "solid",
            "Software entities should be open for extension but closed for modification.",
            "Add new behavior without editing the existing, tested code.",
            "Changes ripple through unrelated callers because behavior is hardcoded.",
            "Design extension points (interfaces, hooks, strategy injection) where variation is expected.",
            "Easier to extend safely; over-anticipating variation creates dead abstractions.",
            &["object_oriented_programming"],
            &["solid", "extensibility"],
            "https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle",
        ),
        pat(
            "liskov_substitution_principle",
            "Liskov Substitution Principle",
            "principle",
            "solid",
            "Subtypes must be substitutable for their base types without breaking client expectations.",
            "Preserve behavioral contracts across an inheritance hierarchy.",
            "A subclass overrides behavior in a way that violates its parent's contract.",
            "Strengthen preconditions cautiously, preserve postconditions, and never throw new exceptions clients can't handle.",
            "Polymorphic clients stay correct; some classes must instead favor composition over inheritance.",
            &["object_oriented_programming"],
            &["solid", "polymorphism"],
            "https://en.wikipedia.org/wiki/Liskov_substitution_principle",
        ),
        pat(
            "interface_segregation_principle",
            "Interface Segregation Principle",
            "principle",
            "solid",
            "Clients should not be forced to depend on interfaces they don't use.",
            "Keep abstractions narrow so each client only sees what it needs.",
            "A single fat interface forces unrelated clients to recompile or stub methods they ignore.",
            "Split the interface along client roles, exposing only the methods each role uses.",
            "Smaller, more cohesive contracts; more interfaces to wire together.",
            &["object_oriented_programming"],
            &["solid", "interfaces"],
            "https://en.wikipedia.org/wiki/Interface_segregation_principle",
        ),
        pat(
            "dependency_inversion_principle",
            "Dependency Inversion Principle",
            "principle",
            "solid",
            "High-level policy should not depend on low-level details; both should depend on abstractions.",
            "Decouple business policy from infrastructure choices.",
            "Domain code imports concrete database, HTTP, or filesystem types and is hard to test.",
            "Define an abstraction owned by the high-level module and let low-level modules implement it.",
            "Enables testability and replacement; requires discipline about who defines each interface.",
            &["object_oriented_programming"],
            &["solid", "abstraction"],
            "https://en.wikipedia.org/wiki/Dependency_inversion_principle",
        ),
        // ---------- GRASP (Craig Larman) ----------
        pat(
            "information_expert",
            "Information Expert (GRASP)",
            "principle",
            "grasp",
            "Assign a responsibility to the class that has the information needed to fulfill it.",
            "Locate behavior where the data lives to maximize cohesion and minimize coupling.",
            "Behavior is placed away from the data, forcing it to ask many objects for fragments.",
            "For each responsibility, identify the information needed and the class that owns it; place the method there.",
            "Tight cohesion; danger of overloading the data-owning class if many responsibilities accrue.",
            &["object_oriented_programming"],
            &["grasp", "cohesion"],
            "https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)",
        ),
        pat(
            "creator_grasp",
            "Creator (GRASP)",
            "principle",
            "grasp",
            "Class B creates instances of class A if B aggregates, contains, records, or closely uses A.",
            "Locate creation responsibility where context makes it natural.",
            "Object creation is scattered, hiding ownership and lifecycle relationships.",
            "Identify the class that uses, owns, or aggregates A and let it construct A.",
            "Clear ownership; risk that the creator accumulates unrelated responsibilities.",
            &["object_oriented_programming"],
            &["grasp", "creation"],
            "https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)",
        ),
        pat(
            "controller_grasp",
            "Controller (GRASP)",
            "principle",
            "grasp",
            "Assign the responsibility of handling a system event to a class representing the overall system or use case.",
            "Provide a single entry point between UI/external requests and the domain.",
            "UI code directly invokes domain logic, mixing presentation and application concerns.",
            "Introduce a controller class (use-case or session-scoped) that orchestrates domain calls for each request.",
            "Clear seam between layers; bloated controllers become 'service' god objects if not split.",
            &["object_oriented_programming"],
            &["grasp", "controller"],
            "https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)",
        ),
        pat(
            "low_coupling_grasp",
            "Low Coupling (GRASP)",
            "principle",
            "grasp",
            "Assign responsibilities so that coupling remains low.",
            "Minimize the impact of change in one module on others.",
            "Modules know too much about each other's internals, so changes ripple widely.",
            "When choosing where to put behavior, prefer the option that creates the fewest new dependencies.",
            "Easier change and reuse; can drive over-abstraction if pursued in isolation.",
            &["object_oriented_programming"],
            &["grasp", "coupling"],
            "https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)",
        ),
        pat(
            "high_cohesion_grasp",
            "High Cohesion (GRASP)",
            "principle",
            "grasp",
            "Assign responsibilities so that a class focuses on a single, well-defined purpose.",
            "Make modules easier to understand, maintain, and reuse.",
            "A class collects unrelated responsibilities and becomes a maintenance hazard.",
            "Group responsibilities that change together and split out unrelated ones into focused classes.",
            "Comprehensible modules; too-strict cohesion can produce many tiny classes.",
            &["object_oriented_programming"],
            &["grasp", "cohesion"],
            "https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)",
        ),
        pat(
            "polymorphism_grasp",
            "Polymorphism (GRASP)",
            "principle",
            "grasp",
            "Use polymorphism to handle alternatives based on type rather than explicit type checks.",
            "Avoid scattered `if/switch` on type when behavior varies by kind.",
            "Type-based conditionals duplicate the type-check whenever a new variant is added.",
            "Define a common interface and let each variant implement the relevant operations.",
            "Open to new variants; choose composition when a type-check is genuinely about identity, not behavior.",
            &["object_oriented_programming"],
            &["grasp", "polymorphism"],
            "https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)",
        ),
        pat(
            "pure_fabrication_grasp",
            "Pure Fabrication (GRASP)",
            "principle",
            "grasp",
            "Assign a responsibility to a fabricated class that does not represent a domain concept, when domain placement would harm cohesion or coupling.",
            "Avoid distorting the domain model for technical concerns.",
            "Placing technical responsibility on a domain class would couple it to infrastructure.",
            "Introduce a service/helper class outside the domain (e.g., persistence, transport) that handles the concern.",
            "Cleaner domain; risk of anemic domain if fabrications absorb behavior that belongs in entities.",
            &["object_oriented_programming"],
            &["grasp"],
            "https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)",
        ),
        pat(
            "indirection_grasp",
            "Indirection (GRASP)",
            "principle",
            "grasp",
            "Insert an intermediate object to mediate between two collaborators when direct coupling is undesirable.",
            "Decouple components so each can evolve independently.",
            "Two components are tightly bound and changes to one ripple to the other.",
            "Insert a mediator/adapter that translates and isolates each side from the other's details.",
            "Reduced coupling; another layer to traverse during debugging.",
            &["object_oriented_programming"],
            &["grasp", "decoupling"],
            "https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)",
        ),
        pat(
            "protected_variations_grasp",
            "Protected Variations (GRASP)",
            "principle",
            "grasp",
            "Identify points of predicted variation and create a stable interface around them.",
            "Localize the cost of changes that are likely to happen.",
            "Volatile decisions (formats, providers, policies) leak across many call sites.",
            "Wrap each predicted variation behind an interface; provide pluggable implementations behind it.",
            "Stable callers; protecting the wrong variation creates needless ceremony.",
            &["object_oriented_programming"],
            &["grasp", "abstraction"],
            "https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)",
        ),
    ]
}
