//! Software testing patterns.

use super::{PatternSeed, pat};

pub(super) fn seeds() -> Vec<PatternSeed> {
    vec![
        pat(
            "arrange_act_assert",
            "Arrange-Act-Assert (AAA)",
            "pattern",
            "testing",
            "Structure each test in three explicit sections: set up, exercise, verify.",
            "Make tests readable and uniform.",
            "Tests intermix setup, action, and verification, hindering quick comprehension.",
            "Label or visually separate the three sections; keep each minimal.",
            "Readable tests; one cohesive scenario per test.",
            &["procedural_programming", "object_oriented_programming"],
            &["testing", "style"],
            "https://martinfowler.com/bliki/GivenWhenThen.html",
        ),
        pat(
            "given_when_then",
            "Given-When-Then (GWT)",
            "pattern",
            "testing",
            "Express test scenarios in BDD-style sentences capturing precondition, action, and expectation.",
            "Make tests double as living specifications.",
            "Tests phrased in technical jargon don't communicate intent to non-developers.",
            "Phrase each scenario as Given <state>, When <action>, Then <outcome>; align with feature files.",
            "Shared vocabulary with stakeholders; small overhead in test syntax.",
            &["procedural_programming", "object_oriented_programming"],
            &["testing", "bdd"],
            "https://martinfowler.com/bliki/GivenWhenThen.html",
        ),
        pat(
            "test_double_dummy",
            "Test Double: Dummy",
            "pattern",
            "testing",
            "An object passed to satisfy a parameter but never actually used.",
            "Fulfill API requirements without simulating behavior.",
            "A test needs to pass an argument that the system under test never inspects.",
            "Use a sentinel or trivial implementation; document intent.",
            "Minimal noise; only valid when truly unused.",
            &["object_oriented_programming"],
            &["testing", "test_doubles"],
            "https://martinfowler.com/articles/mocksArentStubs.html",
        ),
        pat(
            "test_double_stub",
            "Test Double: Stub",
            "pattern",
            "testing",
            "Provide canned responses to calls made during the test.",
            "Isolate the system under test from a dependency's variability.",
            "Real dependency returns differing values across runs or environments.",
            "Implement only the methods invoked; return preconfigured values; assert state, not interactions.",
            "Deterministic tests; stubs aren't for verifying calls.",
            &["object_oriented_programming"],
            &["testing", "test_doubles"],
            "https://martinfowler.com/articles/mocksArentStubs.html",
        ),
        pat(
            "test_double_fake",
            "Test Double: Fake",
            "pattern",
            "testing",
            "A working implementation suitable for tests but not for production (e.g., in-memory repo).",
            "Replace a slow or external dependency with a faster, deterministic equivalent.",
            "Hitting the real database/queue per test is too slow.",
            "Implement a simplified version that satisfies the production contract; reuse across tests.",
            "Fast deterministic tests; fakes must stay in sync with the real contract.",
            &["object_oriented_programming"],
            &["testing", "test_doubles"],
            "https://martinfowler.com/articles/mocksArentStubs.html",
        ),
        pat(
            "test_double_mock",
            "Test Double: Mock",
            "pattern",
            "testing",
            "Pre-program with expectations about which calls should be received.",
            "Assert how the system under test interacts with a collaborator.",
            "Verifying side-effecting interactions via final state is impossible.",
            "Set expectations via a mocking framework; verify at the end of the test.",
            "Interaction-based testing; over-specification can create brittle tests.",
            &["object_oriented_programming"],
            &["testing", "test_doubles"],
            "https://martinfowler.com/articles/mocksArentStubs.html",
        ),
        pat(
            "test_double_spy",
            "Test Double: Spy",
            "pattern",
            "testing",
            "Record information about how it was called, examined after the test.",
            "Capture interaction details without pre-programming expectations.",
            "Mocks force pre-specified interactions; sometimes post-hoc verification reads better.",
            "Wrap a real object or create a spy that records calls; assert recorded values later.",
            "Flexible verification; risk of weak assertions if not used carefully.",
            &["object_oriented_programming"],
            &["testing", "test_doubles"],
            "https://martinfowler.com/articles/mocksArentStubs.html",
        ),
        pat(
            "object_mother",
            "Object Mother",
            "pattern",
            "testing",
            "Centralize test fixture creation in a factory of named, intention-revealing variants.",
            "Reduce duplication and obscure setup across tests.",
            "Every test rebuilds the same complex fixtures inline.",
            "Define `Mother.aValid<Customer>()`, `Mother.withOverdraft()`, etc.; tests call the mothers.",
            "Readable tests; mothers can grow into god-objects without care.",
            &["object_oriented_programming"],
            &["testing", "fixtures"],
            "https://martinfowler.com/bliki/ObjectMother.html",
        ),
        pat(
            "test_data_builder",
            "Test Data Builder",
            "pattern",
            "testing",
            "Use a builder API to assemble fixtures with sensible defaults and per-test overrides.",
            "Express only the relevant differences in each test.",
            "Inline fixture construction hides which fields matter and which are noise.",
            "Provide a fluent builder with all defaults set; tests override only what they care about.",
            "Intention-revealing fixtures; builder maintenance cost.",
            &["object_oriented_programming"],
            &["testing", "fixtures"],
            "http://www.natpryce.com/articles/000714.html",
        ),
        pat(
            "property_based_testing",
            "Property-Based Testing",
            "pattern",
            "testing",
            "Express properties that should hold for all inputs and let the framework generate examples.",
            "Find edge cases automatically.",
            "Hand-written examples miss combinations a generator would find.",
            "State properties (round-trip, idempotence, invariants); use QuickCheck/Hypothesis/proptest with shrinkers.",
            "Powerful bug discovery; counterexample debugging takes practice.",
            &["functional_programming", "procedural_programming"],
            &["testing"],
            "https://en.wikipedia.org/wiki/QuickCheck",
        ),
        pat(
            "fuzz_testing",
            "Fuzz Testing",
            "pattern",
            "testing",
            "Feed random/structured-random inputs to find crashes, hangs, and assertion failures.",
            "Exercise robustness across the input space.",
            "Hand-curated inputs don't surface edge or adversarial cases.",
            "Run fuzzers (libFuzzer, AFL, cargo-fuzz, Jazzer) with sanitizers; collect and triage findings.",
            "High-leverage robustness; CPU cost and triage workload to budget.",
            &["procedural_programming", "object_oriented_programming"],
            &["testing", "security"],
            "https://en.wikipedia.org/wiki/Fuzzing",
        ),
        pat(
            "snapshot_testing",
            "Snapshot Testing",
            "pattern",
            "testing",
            "Compare current output to a stored snapshot, regenerated only when explicitly approved.",
            "Detect unintended output changes cheaply.",
            "Asserting many fields by hand is verbose and brittle.",
            "Generate the snapshot; review diffs in PRs; regenerate when an intentional change occurs.",
            "Catches unexpected changes; weak at expressing intent.",
            &["object_oriented_programming"],
            &["testing"],
            "https://jestjs.io/docs/snapshot-testing",
        ),
        pat(
            "contract_testing",
            "Contract Testing",
            "pattern",
            "testing",
            "Verify that two services can communicate according to a shared contract independently.",
            "Catch integration breakage without running both services in concert.",
            "End-to-end tests are slow and flaky; mocking diverges from reality.",
            "Define provider/consumer contracts; run consumer-driven tests (Pact); publish/consume in CI.",
            "Fast, reliable integration confidence; contract management is ongoing work.",
            &["distributed_systems"],
            &["testing", "microservices"],
            "https://martinfowler.com/bliki/ContractTest.html",
        ),
        pat(
            "page_object_model",
            "Page Object Model",
            "pattern",
            "testing",
            "Wrap UI pages as objects exposing high-level actions and queries.",
            "Decouple test scenarios from UI implementation details.",
            "Tests directly poke selectors and break on every UI tweak.",
            "Each screen has a Page Object; tests invoke methods like `loginAs(user)`; selectors live in the Page Object.",
            "Stable, readable UI tests; per-screen abstraction maintenance.",
            &["object_oriented_programming"],
            &["testing", "ui"],
            "https://martinfowler.com/bliki/PageObject.html",
        ),
        pat(
            "test_pyramid",
            "Test Pyramid",
            "principle",
            "testing",
            "Use many fast unit tests, fewer service tests, and few end-to-end tests.",
            "Balance feedback speed and coverage.",
            "Inverted pyramids (lots of slow e2e) make CI slow and flaky; missing unit tests lets bugs slip in.",
            "Allocate effort across layers per the pyramid; prefer unit + contract tests; reserve e2e for happy-path smokes.",
            "Fast and reliable suites; right ratios depend on the system shape.",
            &["object_oriented_programming"],
            &["testing", "principle"],
            "https://martinfowler.com/bliki/TestPyramid.html",
        ),
        pat(
            "test_trophy",
            "Test Trophy",
            "principle",
            "testing",
            "For modern frontends, emphasize integration and component tests with fewer pure unit tests at the bottom and few e2e at the top.",
            "Match the testing shape to UI realities where component integration matters most.",
            "Strict pyramid under-tests UI integrations that produce most user-visible bugs.",
            "Invest in component/integration tests (React Testing Library, Vue Test Utils); top with limited e2e.",
            "Better confidence per dollar in UI code; the right model depends on stack.",
            &["object_oriented_programming"],
            &["testing", "ui", "principle"],
            "https://kentcdodds.com/blog/the-testing-trophy-and-testing-classifications",
        ),
        pat(
            "mutation_testing",
            "Mutation Testing",
            "pattern",
            "testing",
            "Mutate the source code and rerun tests; surviving mutants reveal weak tests.",
            "Measure the true quality of a test suite beyond line coverage.",
            "High line coverage can coexist with weak assertions.",
            "Run a mutation-testing tool (PIT, Stryker, mutmut); investigate surviving mutants and strengthen tests.",
            "Reveals weak assertions; computationally expensive on large suites.",
            &["object_oriented_programming"],
            &["testing", "quality"],
            "https://en.wikipedia.org/wiki/Mutation_testing",
        ),
        pat(
            "golden_test",
            "Golden Test (Approval Test)",
            "pattern",
            "testing",
            "Persist the expected output and assert that current output matches.",
            "Lock in complex outputs that are otherwise hard to assert piece by piece.",
            "Asserting deeply structured output by hand is impractical.",
            "Capture an approved file; on diff, surface to a reviewer who updates if intended.",
            "Strong drift detection; intent of changes needs reviewer discipline.",
            &["object_oriented_programming"],
            &["testing"],
            "https://approvaltests.com/",
        ),
        pat(
            "smoke_test",
            "Smoke Test",
            "pattern",
            "testing",
            "Minimal end-to-end test verifying that the system can start and serve basic functionality.",
            "Detect catastrophic regressions quickly.",
            "Full e2e suites are too slow to gate every commit.",
            "Run a short scripted scenario per environment after deploy; alert on failure.",
            "Fast safety net; not a substitute for deeper tests.",
            &["distributed_systems"],
            &["testing", "deployment"],
            "https://en.wikipedia.org/wiki/Smoke_testing_(software)",
        ),
        pat(
            "chaos_engineering",
            "Chaos Engineering",
            "pattern",
            "testing",
            "Deliberately inject failures into production-like environments to test resilience.",
            "Find unknown weaknesses before they cause outages.",
            "Pre-production tests don't surface real distributed failure modes.",
            "Define steady-state metrics; introduce controlled failures (kill nodes, add latency); learn from observations.",
            "Strong resilience; needs organizational commitment and safety guardrails.",
            &["distributed_systems"],
            &["testing", "resilience"],
            "https://principlesofchaos.org/",
        ),
        pat(
            "load_test",
            "Load Testing",
            "pattern",
            "testing",
            "Subject the system to expected and peak load while measuring response and resource use.",
            "Validate capacity planning before users do.",
            "Capacity assumptions are wrong until measured.",
            "Generate realistic traffic patterns (k6, JMeter, Locust); measure latency/throughput/errors; track regressions.",
            "Reliable scaling decisions; load test environment must approximate production.",
            &["distributed_systems"],
            &["testing", "performance"],
            "https://en.wikipedia.org/wiki/Load_testing",
        ),
        pat(
            "soak_test",
            "Soak Test",
            "pattern",
            "testing",
            "Run the system at sustained load over a long period to catch leaks, drifts, or degradation.",
            "Find resource leaks and slow accumulation bugs.",
            "Short tests miss memory leaks, queue growth, and slow degradation.",
            "Run sustained load for hours/days; track memory, CPU, queue depths, and tail latency over time.",
            "Catches creep bugs; requires long test windows.",
            &["distributed_systems"],
            &["testing", "performance"],
            "https://en.wikipedia.org/wiki/Soak_testing",
        ),
        pat(
            "hermetic_test",
            "Hermetic Test",
            "principle",
            "testing",
            "A test that depends only on declared inputs and produces deterministic outputs.",
            "Eliminate flakiness from environment, time, network, or shared state.",
            "Tests reach out to the network, file system, or shared databases and flake.",
            "Inject all dependencies (clock, IO, randomness); use process-local fixtures; avoid shared global state.",
            "Reliable suites; some initial work to inject dependencies.",
            &["object_oriented_programming"],
            &["testing", "reliability"],
            "https://abseil.io/resources/swe-book/html/ch11.html#hermetic_tests",
        ),
        pat(
            "flaky_test_quarantine",
            "Flaky Test Quarantine",
            "pattern",
            "testing",
            "Isolate intermittently failing tests in a quarantine while the suite remains green.",
            "Stop flaky tests from masking real failures.",
            "Flaky tests trigger ignore-fatigue; teams stop trusting CI.",
            "Mark known-flaky tests; route them to a separate suite; track them down with strict SLAs.",
            "Trustworthy main suite; flaky list must not grow without bound.",
            &["object_oriented_programming"],
            &["testing", "reliability"],
            "https://martinfowler.com/articles/nonDeterminism.html",
        ),
        // ---------- Additional testing practices ----------
        pat(
            "bdd_cucumber",
            "Behavior-Driven Development (BDD / Cucumber)",
            "pattern",
            "testing",
            "Write tests as Given/When/Then feature scenarios in plain language; step definitions execute them.",
            "Align tests with business-readable specifications.",
            "Technical-only tests don't surface acceptance criteria to non-developers.",
            "Author `.feature` files in Gherkin; map steps to code; run with Cucumber / SpecFlow / Behave.",
            "Shared vocabulary; framework overhead for small teams.",
            &["object_oriented_programming"],
            &["testing", "bdd"],
            "https://cucumber.io/docs/bdd/",
        ),
        pat(
            "atdd",
            "Acceptance Test-Driven Development (ATDD)",
            "pattern",
            "testing",
            "Three-amigos (PM, dev, QA) co-author acceptance tests before coding.",
            "Align everyone on what 'done' means and produce executable specs.",
            "Devs and PMs interpret stories differently without explicit criteria.",
            "Hold a 3-amigos session; write Given/When/Then scenarios; commit; implement.",
            "Shared understanding; meeting overhead per story.",
            &["object_oriented_programming"],
            &["testing", "process"],
            "https://en.wikipedia.org/wiki/Acceptance_test%E2%80%93driven_development",
        ),
        pat(
            "outside_in_tdd",
            "Outside-In TDD (London-style)",
            "pattern",
            "testing",
            "Start with high-level acceptance tests; mock collaborators; drive down through layers.",
            "Get end-to-end behavior right first; details emerge from outside.",
            "Inside-out can miss the actual interaction shape.",
            "Write a failing acceptance test; build the outermost class with mocked collaborators; drill down; remove mocks as real classes appear.",
            "Behavior-driven design; mocking discipline required.",
            &["object_oriented_programming"],
            &["testing", "tdd"],
            "https://www.growing-object-oriented-software.com/",
        ),
        pat(
            "inside_out_tdd",
            "Inside-Out TDD (Classicist)",
            "pattern",
            "testing",
            "Start with the lowest-level domain unit; build outward.",
            "Get core domain logic right before integration.",
            "Outside-in heavy mocking can lock in poor interfaces.",
            "Write a failing unit test for the innermost domain concept; build outward; integrate concretely.",
            "Strong core; integration concerns appear later.",
            &["object_oriented_programming"],
            &["testing", "tdd"],
            "https://martinfowler.com/articles/mocksArentStubs.html",
        ),
        pat(
            "spec_by_example",
            "Specification by Example",
            "principle",
            "testing",
            "Capture requirements as concrete examples (test scenarios) rather than abstract prose.",
            "Make ambiguity-free, executable specifications.",
            "Prose specs hide ambiguity; examples don't.",
            "Author tables of examples (Concordion / Fitness style) per story; agree on table values; automate execution.",
            "Specifications you can run; some authoring overhead.",
            &["object_oriented_programming"],
            &["testing", "spec"],
            "https://www.specificationbyexample.com/",
        ),
        pat(
            "visual_regression_testing",
            "Visual Regression Testing",
            "pattern",
            "testing",
            "Capture screenshots of UIs and compare to baseline on every change.",
            "Catch unintended visual changes that unit/integration tests miss.",
            "CSS/asset changes silently alter UI without breaking tests.",
            "Use Percy/Chromatic/Playwright snapshots; review diffs; approve intentional changes.",
            "Catches design regressions; flaky on font/rendering differences without normalization.",
            &["object_oriented_programming"],
            &["testing", "ui"],
            "https://www.browserstack.com/guide/visual-regression-testing",
        ),
        pat(
            "a11y_testing",
            "Accessibility (A11y) Testing",
            "pattern",
            "testing",
            "Automated and manual checks for keyboard nav, screen-reader labels, color contrast, ARIA roles.",
            "Ship inclusive UIs as a baseline, not an afterthought.",
            "Accessibility bugs ship in droves without automated guards.",
            "Run axe-core / Pa11y in CI; require manual audit for new flows; include keyboard-only testing.",
            "Baseline a11y compliance; some issues only manual testing finds.",
            &["object_oriented_programming"],
            &["testing", "a11y", "ui"],
            "https://www.w3.org/WAI/standards-guidelines/wcag/",
        ),
        pat(
            "i18n_testing",
            "Internationalization (i18n) Testing",
            "pattern",
            "testing",
            "Test UIs in multiple locales: text expansion, RTL languages, locale-specific formatting.",
            "Catch i18n bugs (overflow, hardcoded strings, broken dates) before users do.",
            "English-only testing misses problems that surface in other locales.",
            "Add pseudo-localization in CI; test screenshots in at least one CJK and RTL locale; lint hardcoded strings.",
            "Reliable global UX; small CI overhead.",
            &["object_oriented_programming"],
            &["testing", "i18n", "ui"],
            "https://en.wikipedia.org/wiki/Pseudolocalization",
        ),
        pat(
            "mutation_score_threshold",
            "Mutation Score Threshold",
            "principle",
            "testing",
            "Gate CI on a minimum mutation-test score, not just line coverage.",
            "Force tests to make meaningful assertions, not just exercise code.",
            "Coverage can be high while tests assert nothing.",
            "Set a baseline mutation score; fail PRs that drop below; investigate surviving mutants.",
            "Stronger tests; mutation testing is expensive — run nightly, not per PR if necessary.",
            &["object_oriented_programming"],
            &["testing", "quality"],
            "https://en.wikipedia.org/wiki/Mutation_testing",
        ),
    ]
}
