//! Embeds the tree-sitter grammar assets (`resources/grammars/**`) into the
//! binary as a `&[(&str, &[u8])]` table so the release daemon can serve them at
//! `/webui/grammars/...` without a runtime filesystem dependency (mirroring how
//! `assets.rs` `include_str!`s app.js/app.css/index.html). The `.wasm` grammars
//! are binary, so they cannot go through `include_str!` — hence this generated
//! `include_bytes!` table.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=resources/grammars");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let base = Path::new("resources/grammars");

    let mut entries: Vec<(String, String)> = Vec::new();
    walk(base, base, &mut entries);
    entries.sort();

    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit.\n");
    code.push_str("pub static GRAMMAR_ASSETS: &[(&str, &[u8])] = &[\n");
    for (rel, abs) in &entries {
        writeln!(code, "    ({rel:?}, include_bytes!({abs:?})),").expect("write grammar entry");
    }
    code.push_str("];\n");

    std::fs::write(Path::new(&out_dir).join("grammar_assets.rs"), code)
        .expect("write grammar_assets.rs");
}

fn walk(base: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(read) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(base, &path, out);
        } else if let Ok(rel) = path.strip_prefix(base) {
            let rel = rel.to_string_lossy().replace('\\', "/");
            let abs = std::fs::canonicalize(&path)
                .expect("canonicalize grammar asset")
                .to_string_lossy()
                .to_string();
            out.push((rel, abs));
        }
    }
}
