//! Built-in software pattern catalog metadata.
//!
//! The text in this module is intentionally compact: it is the local,
//! repo-bundled "card" layer that gives the agent stable labels,
//! paradigms, and source associations before any opted-in full-text source
//! imports run. Full article bodies are fetched into the local database at
//! runtime and are not committed to the repository.

#[derive(Debug, Clone, Copy)]
pub struct ParadigmSeed {
    pub slug: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub wikipedia_url: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub struct PatternSeed {
    pub slug: &'static str,
    pub name: &'static str,
    pub kind: &'static str,
    pub category: &'static str,
    pub summary: &'static str,
    pub intent: &'static str,
    pub problem: &'static str,
    pub solution: &'static str,
    pub consequences: &'static str,
    pub paradigms: &'static [&'static str],
    pub tags: &'static [&'static str],
    pub canonical_url: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub struct SourceDescriptor {
    pub source_family: &'static str,
    pub title: &'static str,
    pub url: &'static str,
    pub license_label: &'static str,
    pub source_type: &'static str,
    pub ingest_policy: &'static str,
    pub pattern_slugs: &'static [&'static str],
    pub tags: &'static [&'static str],
}

pub fn paradigm_seeds() -> Vec<ParadigmSeed> {
    vec![
        ParadigmSeed {
            slug: "procedural_programming",
            name: "Procedural programming",
            description: "Procedure/module-oriented design with explicit control flow and state.",
            wikipedia_url: "https://en.wikipedia.org/wiki/Procedural_programming",
        },
        ParadigmSeed {
            slug: "object_oriented_programming",
            name: "Object-oriented programming",
            description: "Design around objects, encapsulation, polymorphism, and responsibility assignment.",
            wikipedia_url: "https://en.wikipedia.org/wiki/Object-oriented_programming",
        },
        ParadigmSeed {
            slug: "functional_programming",
            name: "Functional programming",
            description: "Design with pure functions, immutable data, composition, and algebraic abstractions.",
            wikipedia_url: "https://en.wikipedia.org/wiki/Functional_programming",
        },
        ParadigmSeed {
            slug: "logic_programming",
            name: "Logic programming",
            description: "Declarative design with facts, rules, relations, unification, and search.",
            wikipedia_url: "https://en.wikipedia.org/wiki/Logic_programming",
        },
        ParadigmSeed {
            slug: "event_driven_programming",
            name: "Event-driven programming",
            description: "Design around event production, delivery, handlers, streams, and reactions.",
            wikipedia_url: "https://en.wikipedia.org/wiki/Event-driven_programming",
        },
        ParadigmSeed {
            slug: "concurrent_programming",
            name: "Concurrent programming",
            description: "Design for overlapping tasks, coordination, cancellation, and shared-resource safety.",
            wikipedia_url: "https://en.wikipedia.org/wiki/Concurrent_computing",
        },
        ParadigmSeed {
            slug: "parallel_programming",
            name: "Parallel programming",
            description: "Design for decomposing computation across cores, workers, and data partitions.",
            wikipedia_url: "https://en.wikipedia.org/wiki/Parallel_computing",
        },
        ParadigmSeed {
            slug: "aspect_oriented_programming",
            name: "Aspect-oriented programming",
            description: "Design for modularizing cross-cutting concerns with join points, pointcuts, and advice.",
            wikipedia_url: "https://en.wikipedia.org/wiki/Aspect-oriented_programming",
        },
        ParadigmSeed {
            slug: "distributed_systems",
            name: "Distributed systems",
            description: "Design for networked services, partial failure, consistency, resilience, and operations.",
            wikipedia_url: "https://en.wikipedia.org/wiki/Distributed_computing",
        },
    ]
}

#[allow(clippy::too_many_arguments)]
const fn pat(
    slug: &'static str,
    name: &'static str,
    kind: &'static str,
    category: &'static str,
    summary: &'static str,
    intent: &'static str,
    problem: &'static str,
    solution: &'static str,
    consequences: &'static str,
    paradigms: &'static [&'static str],
    tags: &'static [&'static str],
    canonical_url: &'static str,
) -> PatternSeed {
    PatternSeed {
        slug,
        name,
        kind,
        category,
        summary,
        intent,
        problem,
        solution,
        consequences,
        paradigms,
        tags,
        canonical_url,
    }
}

pub fn pattern_seeds() -> Vec<PatternSeed> {
    vec![
        // Object-oriented / GoF
        pat(
            "singleton",
            "Singleton",
            "pattern",
            "creational",
            "Ensure one shared instance with a global access point.",
            "Coordinate a genuinely unique resource.",
            "Multiple instances would violate correctness or waste scarce resources.",
            "Hide construction behind a controlled accessor and make lifetime explicit.",
            "Easy access but high coupling; avoid using it as ambient mutable state.",
            &["object_oriented_programming"],
            &["gof", "creational", "global_state"],
            "https://en.wikipedia.org/wiki/Singleton_pattern",
        ),
        pat(
            "factory_method",
            "Factory Method",
            "pattern",
            "creational",
            "Let subclasses or collaborators choose concrete products behind a stable creation interface.",
            "Decouple object creation from object use.",
            "Clients know an abstraction but not the concrete type to instantiate.",
            "Move creation into an overridable method or factory interface.",
            "Improves extension points; can add indirection if product families are simple.",
            &["object_oriented_programming"],
            &["gof", "creational"],
            "https://en.wikipedia.org/wiki/Factory_method_pattern",
        ),
        pat(
            "abstract_factory",
            "Abstract Factory",
            "pattern",
            "creational",
            "Create related object families without naming concrete classes.",
            "Keep product families consistent.",
            "A system must switch between families of compatible products.",
            "Expose a factory interface with creation methods for each product role.",
            "Useful for platform/product families; heavier than a single factory.",
            &["object_oriented_programming"],
            &["gof", "creational"],
            "https://en.wikipedia.org/wiki/Abstract_factory_pattern",
        ),
        pat(
            "builder",
            "Builder",
            "pattern",
            "creational",
            "Separate complex object construction from representation.",
            "Make construction explicit and readable.",
            "Constructors or factories have too many optional or ordered parameters.",
            "Accumulate configuration through a builder and validate at build time.",
            "Improves clarity; may be unnecessary for small immutable values.",
            &["object_oriented_programming"],
            &["gof", "creational"],
            "https://en.wikipedia.org/wiki/Builder_pattern",
        ),
        pat(
            "prototype",
            "Prototype",
            "pattern",
            "creational",
            "Create new objects by copying a configured exemplar.",
            "Avoid repeated complex initialization.",
            "New instances resemble existing ones more than fixed classes.",
            "Clone or copy a prototype and vary the small part that changes.",
            "Good for configured objects; copy semantics must be clear.",
            &["object_oriented_programming"],
            &["gof", "creational"],
            "https://en.wikipedia.org/wiki/Prototype_pattern",
        ),
        pat(
            "adapter",
            "Adapter",
            "pattern",
            "structural",
            "Convert one interface into another expected by clients.",
            "Integrate incompatible abstractions without changing either side.",
            "A useful component exposes the wrong interface for the caller.",
            "Wrap it with a translation layer implementing the expected contract.",
            "Keeps boundaries clean; can hide impedance mismatch costs.",
            &["object_oriented_programming", "procedural_programming"],
            &["gof", "structural", "integration"],
            "https://en.wikipedia.org/wiki/Adapter_pattern",
        ),
        pat(
            "bridge",
            "Bridge",
            "pattern",
            "structural",
            "Separate abstraction from implementation so both can vary independently.",
            "Avoid combinatorial subclass hierarchies.",
            "Two dimensions of variation are tangled in one inheritance tree.",
            "Move implementation behind a composed interface.",
            "Improves extensibility; requires careful naming of roles.",
            &["object_oriented_programming"],
            &["gof", "structural"],
            "https://en.wikipedia.org/wiki/Bridge_pattern",
        ),
        pat(
            "composite",
            "Composite",
            "pattern",
            "structural",
            "Treat individual objects and object groups uniformly.",
            "Represent recursive part-whole structures.",
            "Clients should not branch on leaf versus container behavior.",
            "Give leaves and composites a common interface.",
            "Natural for trees; can overgeneralize operations that only make sense for composites.",
            &["object_oriented_programming", "functional_programming"],
            &["gof", "structural", "tree"],
            "https://en.wikipedia.org/wiki/Composite_pattern",
        ),
        pat(
            "decorator",
            "Decorator",
            "pattern",
            "structural",
            "Add responsibilities dynamically by wrapping an object.",
            "Compose behavior without subclass explosion.",
            "Features need optional combinations at runtime.",
            "Implement the same interface and delegate to the wrapped component.",
            "Flexible composition; nested wrappers can obscure behavior.",
            &["object_oriented_programming", "functional_programming"],
            &["gof", "structural", "composition"],
            "https://en.wikipedia.org/wiki/Decorator_pattern",
        ),
        pat(
            "facade",
            "Facade",
            "pattern",
            "structural",
            "Provide a simple interface over a complex subsystem.",
            "Reduce coupling to subsystem internals.",
            "Clients must coordinate many low-level operations.",
            "Create a higher-level entry point for common workflows.",
            "Improves usability; can become a god interface if it grows without boundaries.",
            &["object_oriented_programming", "procedural_programming"],
            &["gof", "structural"],
            "https://en.wikipedia.org/wiki/Facade_pattern",
        ),
        pat(
            "proxy",
            "Proxy",
            "pattern",
            "structural",
            "Control access to another object through a stand-in.",
            "Add lazy loading, remote access, caching, or authorization around a target.",
            "The caller should not manage target lifecycle or access policy directly.",
            "Expose the same interface and mediate calls.",
            "Powerful boundary tool; can surprise callers if proxy semantics differ.",
            &["object_oriented_programming", "distributed_systems"],
            &["gof", "structural"],
            "https://en.wikipedia.org/wiki/Proxy_pattern",
        ),
        pat(
            "chain_of_responsibility",
            "Chain of Responsibility",
            "pattern",
            "behavioral",
            "Pass a request through handlers until one handles it.",
            "Decouple senders from receivers.",
            "The responsible handler is context-dependent or extensible.",
            "Compose ordered handlers sharing a common request interface.",
            "Flexible pipelines; ordering and fall-through behavior must be explicit.",
            &["object_oriented_programming", "event_driven_programming"],
            &["gof", "behavioral", "pipeline"],
            "https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern",
        ),
        pat(
            "command",
            "Command",
            "pattern",
            "behavioral",
            "Encapsulate an operation as an object.",
            "Queue, log, undo, schedule, or parameterize requests.",
            "Callers need to treat actions as data.",
            "Represent each action with an execute contract and captured inputs.",
            "Enables history and dispatch; may add boilerplate for simple calls.",
            &["object_oriented_programming", "event_driven_programming"],
            &["gof", "behavioral"],
            "https://en.wikipedia.org/wiki/Command_pattern",
        ),
        pat(
            "observer",
            "Observer",
            "pattern",
            "behavioral",
            "Notify dependents when a subject changes.",
            "Keep producers independent of consumers.",
            "Multiple consumers react to state changes or events.",
            "Register observers and publish updates through a stable callback contract.",
            "Foundational for events; requires lifecycle and backpressure care.",
            &["object_oriented_programming", "event_driven_programming"],
            &["gof", "behavioral", "events"],
            "https://en.wikipedia.org/wiki/Observer_pattern",
        ),
        pat(
            "strategy",
            "Strategy",
            "pattern",
            "behavioral",
            "Encapsulate interchangeable algorithms behind one interface.",
            "Vary behavior without branching or subclassing clients.",
            "A workflow needs different policy choices.",
            "Inject an algorithm object or function implementing the strategy contract.",
            "Excellent for testable policy variation; avoid one-class-per-branch ceremony.",
            &["object_oriented_programming", "functional_programming"],
            &["gof", "behavioral", "policy"],
            "https://en.wikipedia.org/wiki/Strategy_pattern",
        ),
        pat(
            "template_method",
            "Template Method",
            "pattern",
            "behavioral",
            "Fix algorithm structure while deferring selected steps.",
            "Reuse an invariant workflow with customizable hooks.",
            "Subclasses share order but differ in steps.",
            "Put the skeleton in a base operation and override hook methods.",
            "Can work well in frameworks; inheritance coupling can become rigid.",
            &["object_oriented_programming"],
            &["gof", "behavioral"],
            "https://en.wikipedia.org/wiki/Template_method_pattern",
        ),
        pat(
            "visitor",
            "Visitor",
            "pattern",
            "behavioral",
            "Add operations over an object structure without changing element classes.",
            "Separate algorithms from a stable type hierarchy.",
            "Many operations must traverse a fixed set of element types.",
            "Use double dispatch to route element types to visitor methods.",
            "Good for compilers/ASTs; awkward when element types change often.",
            &["object_oriented_programming"],
            &["gof", "behavioral"],
            "https://en.wikipedia.org/wiki/Visitor_pattern",
        ),
        pat(
            "null_object",
            "Null Object",
            "pattern",
            "behavioral",
            "Use a do-nothing object instead of null checks.",
            "Make absence safe and polymorphic.",
            "Callers repeatedly branch around missing collaborators.",
            "Provide an implementation with neutral behavior.",
            "Reduces conditionals; can hide missing-data bugs if overused.",
            &["object_oriented_programming"],
            &["behavioral", "defensive_design"],
            "https://en.wikipedia.org/wiki/Null_object_pattern",
        ),
        // Functional
        pat(
            "pure_function",
            "Pure Function",
            "pattern",
            "functional",
            "A function whose output depends only on inputs and has no side effects.",
            "Make behavior testable, composable, and cacheable.",
            "Hidden state and effects make reasoning difficult.",
            "Separate calculation from effects and pass dependencies explicitly.",
            "Improves reasoning; effects still need explicit boundaries.",
            &["functional_programming", "procedural_programming"],
            &["fp", "referential_transparency"],
            "https://en.wikipedia.org/wiki/Pure_function",
        ),
        pat(
            "function_composition",
            "Function Composition",
            "pattern",
            "functional",
            "Build larger behavior by connecting smaller functions.",
            "Keep transformations small and reusable.",
            "Nested or duplicated logic obscures data flow.",
            "Compose functions in explicit pipelines or combinators.",
            "Readable when types align; poor names can make pipelines opaque.",
            &["functional_programming", "procedural_programming"],
            &["fp", "composition"],
            "https://en.wikipedia.org/wiki/Function_composition_(computer_science)",
        ),
        pat(
            "immutable_data",
            "Immutable Data",
            "pattern",
            "functional",
            "Prefer values that cannot be mutated after creation.",
            "Avoid accidental shared-state changes.",
            "Aliased mutable data creates temporal coupling and race risk.",
            "Model updates as new values or persistent data structures.",
            "Simplifies concurrency; may require allocation-aware design.",
            &["functional_programming", "concurrent_programming"],
            &["fp", "state"],
            "https://en.wikipedia.org/wiki/Immutable_object",
        ),
        pat(
            "algebraic_data_type",
            "Algebraic Data Type",
            "pattern",
            "functional",
            "Model data with product and sum types.",
            "Make domain states explicit and exhaustive.",
            "Invalid combinations are easy to represent with loose records.",
            "Use tagged unions/enums and structured fields.",
            "Improves correctness; requires languages or conventions with good pattern matching.",
            &["functional_programming"],
            &["fp", "types"],
            "https://en.wikipedia.org/wiki/Algebraic_data_type",
        ),
        pat(
            "monad",
            "Monad",
            "pattern",
            "functional",
            "Sequence computations in a context such as optionality, errors, state, or IO.",
            "Compose effectful computations while preserving laws.",
            "Raw effects and nested callbacks obscure control flow.",
            "Use bind/flatMap and return/unit to chain contextual values.",
            "Powerful abstraction; can confuse teams without shared vocabulary.",
            &["functional_programming"],
            &["fp", "effects"],
            "https://en.wikipedia.org/wiki/Monad_(functional_programming)",
        ),
        pat(
            "typeclass",
            "Type Class",
            "pattern",
            "functional",
            "Define ad-hoc polymorphic behavior separately from data types.",
            "Extend behavior without inheritance or editing original types.",
            "A generic algorithm needs operations for many unrelated types.",
            "Provide instances implementing a small law-aware interface.",
            "Very extensible; instance resolution rules must be predictable.",
            &["functional_programming"],
            &["fp", "polymorphism"],
            "https://en.wikipedia.org/wiki/Type_class",
        ),
        // Logic
        pat(
            "facts_rules_queries",
            "Facts, Rules, and Queries",
            "pattern",
            "logic",
            "Represent knowledge as relations and ask the runtime to search answers.",
            "Make domain constraints declarative.",
            "Control-flow code obscures the logical shape of a problem.",
            "Encode facts and rules, then query relations.",
            "Concise for symbolic domains; performance depends on search shape.",
            &["logic_programming"],
            &["logic", "prolog"],
            "https://en.wikipedia.org/wiki/Logic_programming",
        ),
        pat(
            "unification",
            "Unification",
            "pattern",
            "logic",
            "Solve symbolic equality constraints by binding variables.",
            "Let matching and binding be one operation.",
            "Manual matching code duplicates relation logic.",
            "Use terms with variables and allow the engine to unify compatible structures.",
            "Expressive but requires care with occurs checks and instantiation.",
            &["logic_programming"],
            &["logic", "prolog"],
            "https://en.wikipedia.org/wiki/Unification_(computer_science)",
        ),
        pat(
            "constraint_logic_programming",
            "Constraint Logic Programming",
            "pattern",
            "logic",
            "Combine logic relations with constraint solvers.",
            "Solve combinatorial problems declaratively.",
            "Generate-and-test search is too broad.",
            "State constraints over finite domains or other solver-backed spaces.",
            "Prunes search dramatically; solver capabilities shape the model.",
            &["logic_programming"],
            &["logic", "constraints"],
            "https://en.wikipedia.org/wiki/Constraint_logic_programming",
        ),
        pat(
            "definite_clause_grammar",
            "Definite Clause Grammar",
            "pattern",
            "logic",
            "Represent grammars as logic rules.",
            "Parse or generate structured language declaratively.",
            "Parser code is tangled with grammar rules.",
            "Encode productions as DCG clauses and let the engine thread input state.",
            "Excellent for symbolic parsing; may need cuts or constraints for performance.",
            &["logic_programming"],
            &["logic", "grammar"],
            "https://en.wikipedia.org/wiki/Definite_clause_grammar",
        ),
        // Event/distributed
        pat(
            "publish_subscribe",
            "Publish-Subscribe",
            "pattern",
            "event-driven",
            "Publish events to topics without direct producer-consumer coupling.",
            "Fan out notifications across independent consumers.",
            "Producers should not know every subscriber.",
            "Route events through a broker, topic, or event bus.",
            "Scales integration; delivery semantics and schema evolution matter.",
            &["event_driven_programming", "distributed_systems"],
            &["events", "messaging"],
            "https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern",
        ),
        pat(
            "event_sourcing",
            "Event Sourcing",
            "pattern",
            "event-driven",
            "Persist state changes as an append-only event log.",
            "Preserve history and reconstruct state.",
            "Current-state storage loses auditability and temporal context.",
            "Store domain events and fold them into read models.",
            "Strong audit trail; schema evolution and replay costs must be designed.",
            &["event_driven_programming", "distributed_systems"],
            &["events", "architecture"],
            "https://en.wikipedia.org/wiki/Domain-driven_design#Event_sourcing",
        ),
        pat(
            "transactional_outbox",
            "Transactional Outbox",
            "pattern",
            "event-driven",
            "Write state and outbound events in one local transaction.",
            "Avoid dual-write inconsistency between DB and message broker.",
            "A service must update data and publish an event atomically.",
            "Store an outbox row with the domain change and relay it asynchronously.",
            "Improves reliability; requires idempotent consumers and cleanup.",
            &["event_driven_programming", "distributed_systems"],
            &["events", "reliability"],
            "https://microservices.io/patterns/data/transactional-outbox.html",
        ),
        pat(
            "saga",
            "Saga",
            "pattern",
            "distributed",
            "Coordinate a long-running transaction through local steps and compensations.",
            "Maintain consistency without distributed transactions.",
            "A business workflow spans multiple services or stores.",
            "Use choreography or orchestration to execute steps and compensating actions.",
            "Practical for microservices; compensation semantics must match the domain.",
            &["event_driven_programming", "distributed_systems"],
            &["microservices", "consistency"],
            "https://en.wikipedia.org/wiki/Saga_pattern",
        ),
        pat(
            "circuit_breaker",
            "Circuit Breaker",
            "pattern",
            "resilience",
            "Stop calling a failing dependency until it has time to recover.",
            "Prevent cascading failures and resource exhaustion.",
            "Retries against a degraded dependency amplify failure.",
            "Track failures and temporarily open the circuit, then probe recovery.",
            "Protects callers; thresholds and fallback behavior need tuning.",
            &["distributed_systems", "event_driven_programming"],
            &["resilience"],
            "https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern",
        ),
        pat(
            "retry_with_backoff",
            "Retry with Backoff",
            "pattern",
            "resilience",
            "Retry transient failures with increasing delay and jitter.",
            "Recover from temporary failures without creating retry storms.",
            "Immediate repeated retries overload a dependency that is already degraded.",
            "Bound retry attempts, increase delay, add jitter, and make operations idempotent.",
            "Improves resilience; bad retry budgets amplify failures.",
            &["distributed_systems", "concurrent_programming"],
            &["resilience", "retries"],
            "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/",
        ),
        pat(
            "anti_corruption_layer",
            "Anti-Corruption Layer",
            "pattern",
            "architecture",
            "Translate between incompatible domain models at a boundary.",
            "Protect a clean model from legacy or external semantics.",
            "A new subsystem must integrate with a model that would distort its design.",
            "Create an adapter/facade layer that maps requests and concepts both ways.",
            "Preserves domain clarity; mapping code can become substantial.",
            &["object_oriented_programming", "distributed_systems"],
            &["architecture", "ddd", "integration"],
            "https://learn.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer",
        ),
        pat(
            "hexagonal_architecture",
            "Hexagonal Architecture",
            "pattern",
            "architecture",
            "Keep domain logic behind ports and adapters.",
            "Isolate business rules from UI, databases, and external services.",
            "Infrastructure concerns leak into core logic.",
            "Define ports at the core boundary and implement adapters outside.",
            "Improves testability and replaceability; boundaries can be overdrawn.",
            &["object_oriented_programming", "distributed_systems"],
            &["architecture", "ports_adapters"],
            "https://en.wikipedia.org/wiki/Hexagonal_architecture_(software)",
        ),
        pat(
            "strangler_fig",
            "Strangler Fig",
            "pattern",
            "architecture",
            "Incrementally replace legacy behavior behind a routing boundary.",
            "Modernize without a risky big-bang rewrite.",
            "A legacy system must keep running while parts are replaced.",
            "Route selected capabilities to new implementations and shrink the old system.",
            "Reduces migration risk; needs strong routing and observability.",
            &["distributed_systems", "object_oriented_programming"],
            &["modernization"],
            "https://martinfowler.com/bliki/StranglerFigApplication.html",
        ),
        // Concurrent/parallel
        pat(
            "worker_pool",
            "Worker Pool",
            "pattern",
            "concurrency",
            "Run bounded workers that pull tasks from a queue.",
            "Limit resource usage while processing many jobs.",
            "One task per thread/goroutine would overload the process.",
            "Use a fixed or adaptive pool and feed it through a queue/channel.",
            "Predictable capacity; queueing and cancellation policy are essential.",
            &["concurrent_programming", "parallel_programming"],
            &["concurrency", "throughput"],
            "https://en.wikipedia.org/wiki/Thread_pool",
        ),
        pat(
            "fan_out_fan_in",
            "Fan-out/Fan-in",
            "pattern",
            "concurrency",
            "Split work across concurrent workers and merge results.",
            "Parallelize independent work and collect outputs.",
            "A single stage is slower than the available parallelism.",
            "Distribute input to workers and merge their result streams safely.",
            "Improves throughput; ordering, errors, and cancellation must be explicit.",
            &["concurrent_programming", "parallel_programming"],
            &["concurrency", "go"],
            "https://go.dev/blog/pipelines",
        ),
        pat(
            "pipeline_cancellation",
            "Pipeline Cancellation",
            "pattern",
            "concurrency",
            "Propagate cancellation through pipeline stages.",
            "Avoid leaked workers when downstream exits early.",
            "Concurrent stages block forever after a consumer stops reading.",
            "Thread a cancellation signal through every stage and close outputs on exit.",
            "Prevents leaks; every blocking send/receive must participate.",
            &["concurrent_programming"],
            &["concurrency", "go", "lifecycle"],
            "https://go.dev/blog/pipelines",
        ),
        pat(
            "actor_model",
            "Actor Model",
            "pattern",
            "concurrency",
            "Encapsulate state inside actors that communicate with messages.",
            "Avoid shared mutable state while preserving concurrency.",
            "Locks around shared state become complex or fragile.",
            "Give each actor a mailbox and process messages serially.",
            "Strong isolation; message protocols and supervision matter.",
            &["concurrent_programming", "event_driven_programming"],
            &["concurrency", "messaging"],
            "https://en.wikipedia.org/wiki/Actor_model",
        ),
        pat(
            "map_reduce",
            "MapReduce",
            "pattern",
            "parallel",
            "Map independent inputs and reduce partial results.",
            "Scale data-parallel computation.",
            "A large dataset can be partitioned into independent work.",
            "Apply a map function per partition and combine outputs with an associative reducer.",
            "Robust for batch work; not ideal for low-latency workflows.",
            &[
                "parallel_programming",
                "distributed_systems",
                "functional_programming",
            ],
            &["parallel", "data"],
            "https://en.wikipedia.org/wiki/MapReduce",
        ),
        // AOP
        pat(
            "pointcut_advice",
            "Pointcut and Advice",
            "pattern",
            "aspect-oriented",
            "Select join points and attach cross-cutting behavior.",
            "Modularize concerns like logging, tracing, transactions, or policy.",
            "The same concern is scattered through many modules.",
            "Declare pointcuts that match join points and advice that runs around them.",
            "Reduces scattering; matching must be precise and discoverable.",
            &["aspect_oriented_programming"],
            &["aop", "crosscutting"],
            "https://en.wikipedia.org/wiki/Aspect-oriented_programming",
        ),
        pat(
            "aspect_weaving",
            "Aspect Weaving",
            "pattern",
            "aspect-oriented",
            "Compose aspects into base code at compile, load, or runtime.",
            "Apply cross-cutting behavior without editing core modules.",
            "A concern should be applied consistently across many call sites.",
            "Use a weaver/proxy mechanism to insert advice at matched join points.",
            "Centralizes policy; debugging woven behavior can be harder.",
            &["aspect_oriented_programming"],
            &["aop"],
            "https://en.wikipedia.org/wiki/Aspect-oriented_programming",
        ),
        // Anti-patterns
        pat(
            "god_object",
            "God Object",
            "anti_pattern",
            "object-oriented",
            "A single class or module knows too much and does too much.",
            "Spot responsibility concentration before it blocks change.",
            "Many unrelated behaviors and dependencies accumulate in one place.",
            "Split by cohesive responsibilities, ports, workflows, or domain concepts.",
            "Refactoring lowers coupling but requires careful migration tests.",
            &["object_oriented_programming", "procedural_programming"],
            &["antipattern", "coupling"],
            "https://en.wikipedia.org/wiki/God_object",
        ),
        pat(
            "spaghetti_code",
            "Spaghetti Code",
            "anti_pattern",
            "procedural",
            "Control flow and dependencies are tangled and hard to reason about.",
            "Recognize unstructured design that resists change.",
            "Implicit jumps, shared state, and mixed concerns obscure behavior.",
            "Introduce functions, modules, explicit state, and tests around seams.",
            "Incremental untangling is safer than a rewrite.",
            &["procedural_programming", "object_oriented_programming"],
            &["antipattern", "control_flow"],
            "https://en.wikipedia.org/wiki/Spaghetti_code",
        ),
        pat(
            "callback_hell",
            "Callback Hell",
            "anti_pattern",
            "event-driven",
            "Deeply nested callbacks obscure error handling and sequencing.",
            "Avoid unreadable asynchronous control flow.",
            "Async operations are composed only by nesting continuations.",
            "Use promises/futures, async/await, reactive operators, or named stages.",
            "Flattening improves clarity; cancellation and backpressure still need design.",
            &["event_driven_programming", "concurrent_programming"],
            &["antipattern", "async"],
            "https://en.wikipedia.org/wiki/Pyramid_of_doom_(programming)",
        ),
        pat(
            "shared_mutable_state",
            "Shared Mutable State",
            "anti_pattern",
            "concurrency",
            "Multiple concurrent actors mutate the same state without clear ownership.",
            "Avoid races and temporal coupling.",
            "Threads, callbacks, or services read/write shared data freely.",
            "Prefer ownership, message passing, immutability, transactions, or narrow locks.",
            "Improves safety; may require redesigning state boundaries.",
            &["concurrent_programming", "functional_programming"],
            &["antipattern", "state"],
            "https://en.wikipedia.org/wiki/Race_condition",
        ),
        pat(
            "fragile_pointcut",
            "Fragile Pointcut",
            "anti_pattern",
            "aspect-oriented",
            "An aspect accidentally matches too much or breaks when code is renamed.",
            "Avoid invisible cross-cutting behavior drift.",
            "Pointcuts depend on brittle names, broad wildcards, or unstable structure.",
            "Use narrow semantic annotations, tests, and documented pointcut contracts.",
            "Safer aspects trade some convenience for explicitness.",
            &["aspect_oriented_programming"],
            &["antipattern", "aop"],
            "https://en.wikipedia.org/wiki/Aspect-oriented_programming",
        ),
        pat(
            "cut_abuse",
            "Prolog Cut Abuse",
            "anti_pattern",
            "logic",
            "Using cut to force procedural control breaks declarative meaning.",
            "Keep logic programs relational and explainable.",
            "Cuts are inserted to patch performance or determinism without preserving semantics.",
            "Prefer mode-aware predicates, constraints, indexing, or well-scoped green cuts.",
            "Can improve performance; red cuts make queries brittle.",
            &["logic_programming"],
            &["antipattern", "prolog"],
            "https://www.metalevel.at/prolog",
        ),
        pat(
            "premature_optimization",
            "Premature Optimization",
            "anti_pattern",
            "general",
            "Optimizing before the design bottleneck is known.",
            "Avoid complexity not justified by evidence.",
            "Speculative performance work distorts simple design.",
            "Measure first, isolate hotspots, and optimize behind stable interfaces.",
            "Optimization is still important when driven by data.",
            &[
                "procedural_programming",
                "object_oriented_programming",
                "functional_programming",
            ],
            &["antipattern", "performance"],
            "https://en.wikipedia.org/wiki/Program_optimization",
        ),
    ]
}

pub fn source_registry() -> Vec<SourceDescriptor> {
    vec![
        SourceDescriptor {
            source_family: "wikipedia",
            title: "Software design pattern",
            url: "https://en.wikipedia.org/wiki/Software_design_pattern",
            license_label: "CC BY-SA",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "singleton",
                "factory_method",
                "abstract_factory",
                "builder",
                "adapter",
                "decorator",
                "observer",
                "strategy",
                "visitor",
            ],
            tags: &["general"],
        },
        SourceDescriptor {
            source_family: "wikipedia",
            title: "Anti-pattern",
            url: "https://en.wikipedia.org/wiki/Anti-pattern",
            license_label: "CC BY-SA",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "god_object",
                "spaghetti_code",
                "callback_hell",
                "shared_mutable_state",
                "premature_optimization",
            ],
            tags: &["anti_pattern"],
        },
        SourceDescriptor {
            source_family: "oodesign",
            title: "Object Oriented Design Patterns",
            url: "https://www.oodesign.com/",
            license_label: "site terms not detected",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "singleton",
                "factory_method",
                "abstract_factory",
                "builder",
                "prototype",
                "adapter",
                "bridge",
                "composite",
                "decorator",
                "facade",
                "proxy",
                "chain_of_responsibility",
                "command",
                "observer",
                "strategy",
                "template_method",
                "visitor",
                "null_object",
            ],
            tags: &["object_oriented_programming", "gof", "solid"],
        },
        SourceDescriptor {
            source_family: "java_design_patterns",
            title: "Java Design Patterns",
            url: "https://github.com/iluwatar/java-design-patterns",
            license_label: "MIT",
            source_type: "repository",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "singleton",
                "factory_method",
                "abstract_factory",
                "builder",
                "adapter",
                "decorator",
                "observer",
                "strategy",
                "circuit_breaker",
                "actor_model",
            ],
            tags: &["object_oriented_programming", "java"],
        },
        SourceDescriptor {
            source_family: "refactoring_guru",
            title: "Refactoring.Guru Design Patterns",
            url: "https://refactoring.guru/design-patterns",
            license_label: "site copyright",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "factory_method",
                "abstract_factory",
                "builder",
                "prototype",
                "adapter",
                "bridge",
                "composite",
                "decorator",
                "facade",
                "proxy",
                "command",
                "observer",
                "strategy",
                "template_method",
                "visitor",
            ],
            tags: &["object_oriented_programming", "gof"],
        },
        SourceDescriptor {
            source_family: "sourcemaking",
            title: "SourceMaking Design Patterns and Refactoring",
            url: "https://sourcemaking.com/",
            license_label: "site copyright",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "god_object",
                "spaghetti_code",
                "singleton",
                "factory_method",
                "adapter",
            ],
            tags: &["object_oriented_programming", "anti_pattern"],
        },
        SourceDescriptor {
            source_family: "mostly_adequate",
            title: "Mostly Adequate Guide to Functional Programming",
            url: "https://github.com/MostlyAdequate/mostly-adequate-guide",
            license_label: "CC BY-SA 4.0",
            source_type: "repository",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "pure_function",
                "function_composition",
                "immutable_data",
                "monad",
            ],
            tags: &["functional_programming"],
        },
        SourceDescriptor {
            source_family: "scala_docs",
            title: "Scala Functional Programming",
            url: "https://docs.scala-lang.org/overviews/scala-book/functional-programming.html",
            license_label: "Scala docs license",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "pure_function",
                "function_composition",
                "immutable_data",
                "typeclass",
            ],
            tags: &["functional_programming", "scala"],
        },
        SourceDescriptor {
            source_family: "haskell",
            title: "A Gentle Introduction to Haskell: Monads",
            url: "https://www.haskell.org/tutorial/monads.html",
            license_label: "Haskell documentation terms",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["monad"],
            tags: &["functional_programming", "haskell"],
        },
        SourceDescriptor {
            source_family: "rust_patterns",
            title: "Rust Design Patterns",
            url: "https://github.com/rust-unofficial/patterns",
            license_label: "MPL-2.0",
            source_type: "repository",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["immutable_data", "builder", "strategy"],
            tags: &[
                "functional_programming",
                "object_oriented_programming",
                "rust",
            ],
        },
        SourceDescriptor {
            source_family: "swi_prolog",
            title: "SWI-Prolog Documentation",
            url: "https://www.swi-prolog.org/pldoc/index.html",
            license_label: "BSD / CC BY-SA documentation",
            source_type: "manual",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "facts_rules_queries",
                "unification",
                "constraint_logic_programming",
                "definite_clause_grammar",
            ],
            tags: &["logic_programming", "prolog"],
        },
        SourceDescriptor {
            source_family: "power_of_prolog",
            title: "The Power of Prolog",
            url: "https://www.metalevel.at/prolog",
            license_label: "site copyright",
            source_type: "book",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "facts_rules_queries",
                "unification",
                "constraint_logic_programming",
                "definite_clause_grammar",
                "cut_abuse",
            ],
            tags: &["logic_programming", "prolog"],
        },
        SourceDescriptor {
            source_family: "aws",
            title: "AWS Cloud Design Patterns",
            url: "https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/introduction.html",
            license_label: "AWS documentation terms",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "anti_corruption_layer",
                "circuit_breaker",
                "event_sourcing",
                "hexagonal_architecture",
                "publish_subscribe",
                "saga",
                "strangler_fig",
                "transactional_outbox",
            ],
            tags: &["distributed_systems", "event_driven_programming", "cloud"],
        },
        SourceDescriptor {
            source_family: "aws",
            title: "AWS Prescriptive Guidance Patterns",
            url: "https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/welcome.html",
            license_label: "AWS documentation terms",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["strangler_fig", "circuit_breaker", "transactional_outbox"],
            tags: &["distributed_systems", "cloud"],
        },
        SourceDescriptor {
            source_family: "aws_builders_library",
            title: "Amazon Builders' Library",
            url: "https://aws.amazon.com/builders-library/",
            license_label: "AWS site terms",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["circuit_breaker", "retry_with_backoff", "worker_pool"],
            tags: &["distributed_systems", "resilience", "operations"],
        },
        SourceDescriptor {
            source_family: "enterprise_integration_patterns",
            title: "Enterprise Integration Patterns",
            url: "https://www.enterpriseintegrationpatterns.com/",
            license_label: "site copyright",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "publish_subscribe",
                "event_sourcing",
                "chain_of_responsibility",
                "transactional_outbox",
            ],
            tags: &["event_driven_programming", "integration"],
        },
        SourceDescriptor {
            source_family: "reactivex",
            title: "ReactiveX Documentation",
            url: "https://reactivex.io/documentation",
            license_label: "CC BY 3.0 / BSD samples",
            source_type: "manual",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["observer", "function_composition", "callback_hell"],
            tags: &["event_driven_programming", "reactive"],
        },
        SourceDescriptor {
            source_family: "cloudevents",
            title: "CloudEvents Specification",
            url: "https://github.com/cloudevents/spec",
            license_label: "Apache-2.0",
            source_type: "spec",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["publish_subscribe"],
            tags: &["event_driven_programming", "spec"],
        },
        SourceDescriptor {
            source_family: "go_blog",
            title: "Go Concurrency Patterns: Pipelines and cancellation",
            url: "https://go.dev/blog/pipelines",
            license_label: "Go documentation license",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["fan_out_fan_in", "pipeline_cancellation", "worker_pool"],
            tags: &["concurrent_programming", "go"],
        },
        SourceDescriptor {
            source_family: "rust_book",
            title: "The Rust Programming Language",
            url: "https://github.com/rust-lang/book",
            license_label: "MIT OR Apache-2.0",
            source_type: "book",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["immutable_data", "shared_mutable_state", "worker_pool"],
            tags: &["concurrent_programming", "rust"],
        },
        SourceDescriptor {
            source_family: "uxl_onetbb",
            title: "oneTBB Design Patterns",
            url: "https://uxlfoundation.github.io/oneTBB/main/tbb_userguide/design_patterns/Design_Patterns.html",
            license_label: "UXL Foundation documentation",
            source_type: "manual",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["map_reduce", "worker_pool", "fan_out_fan_in"],
            tags: &["parallel_programming", "cpp"],
        },
        SourceDescriptor {
            source_family: "aspectj",
            title: "AspectJ Programming Guide",
            url: "https://eclipse.dev/aspectj/doc/latest/progguide/progguide.html",
            license_label: "Eclipse / document copyright",
            source_type: "manual",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["pointcut_advice", "aspect_weaving", "fragile_pointcut"],
            tags: &["aspect_oriented_programming"],
        },
        SourceDescriptor {
            source_family: "spring",
            title: "Spring AOP Reference",
            url: "https://docs.spring.io/spring-framework/reference/core/aop.html",
            license_label: "Spring documentation terms",
            source_type: "manual",
            ingest_policy: "local_opt_in",
            pattern_slugs: &["pointcut_advice", "aspect_weaving"],
            tags: &["aspect_oriented_programming", "java"],
        },
        SourceDescriptor {
            source_family: "azure",
            title: "Azure Architecture Center",
            url: "https://learn.microsoft.com/en-us/azure/architecture",
            license_label: "Microsoft Learn terms / CC BY where applicable",
            source_type: "article",
            ingest_policy: "local_opt_in",
            pattern_slugs: &[
                "circuit_breaker",
                "publish_subscribe",
                "strangler_fig",
                "anti_corruption_layer",
            ],
            tags: &["distributed_systems", "cloud"],
        },
    ]
}

pub fn card_content(pattern: &PatternSeed) -> String {
    format!(
        "Pattern: {name}\nKind: {kind}\nCategory: {category}\nParadigms: {paradigms}\nTags: {tags}\nSummary: {summary}\nIntent: {intent}\nProblem: {problem}\nSolution: {solution}\nConsequences and tradeoffs: {consequences}\nCanonical URL: {url}\n",
        name = pattern.name,
        kind = pattern.kind,
        category = pattern.category,
        paradigms = pattern.paradigms.join(", "),
        tags = pattern.tags.join(", "),
        summary = pattern.summary,
        intent = pattern.intent,
        problem = pattern.problem,
        solution = pattern.solution,
        consequences = pattern.consequences,
        url = pattern.canonical_url
    )
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::*;

    #[test]
    fn source_registry_references_seeded_patterns() {
        let slugs = pattern_seeds()
            .into_iter()
            .map(|p| p.slug)
            .collect::<HashSet<_>>();

        for source in source_registry() {
            for slug in source.pattern_slugs {
                assert!(
                    slugs.contains(slug),
                    "source {} references unknown pattern slug {}",
                    source.title,
                    slug
                );
            }
        }
    }

    #[test]
    fn patterns_reference_seeded_paradigms() {
        let paradigms = paradigm_seeds()
            .into_iter()
            .map(|p| p.slug)
            .collect::<HashSet<_>>();

        for pattern in pattern_seeds() {
            for paradigm in pattern.paradigms {
                assert!(
                    paradigms.contains(paradigm),
                    "pattern {} references unknown paradigm {}",
                    pattern.slug,
                    paradigm
                );
            }
        }
    }
}
